MaxOS::drivers::DriverManager Class Reference
Manages the drivers, handles the adding and removing of drivers.
#include <driver.h>
Public Member Functions
DriverManager ()
Constructs the Driver Manager, adding any default driver selectors.
~DriverManager ()
Destructor for the Driver Manager, removes all drivers and driver selectors.
void add_driver_selector (DriverSelector *)
Add a driver selector to the manager.
void remove_driver_selector (DriverSelector *)
Remove a driver selector from the manager.
void add_driver (Driver *)
Adds a driver to the manager.
void remove_driver (Driver *)
Removes a driver from the driver vector.
void on_driver_selected (Driver *) final
When a driver is selected add it to the manager.
void find_drivers ()
Find the drivers.
uint32_t reset_devices ()
Reset all the devices.
void initialise_drivers ()
Initialise the drivers.
void deactivate_drivers ()
Deactivate the drivers.
void activate_drivers ()
Activate the drivers.
Detailed Description
Manages the drivers, handles the adding and removing of drivers.
Definition at line 69 of file driver.h.
Constructor & Destructor Documentation
DriverManager()
DriverManager::DriverManager ()
Constructs the Driver Manager, adding any default driver selectors.
Definition at line 97 of file driver.cpp.
                             {
    Logger::INFO() << "Setting up Driver Manager \n";
    add_driver_selector(new PCIController);
    // add_driver_selector(new UniversalSerialBusController);
}
References add_driver_selector(), and MaxOS::Logger::INFO().
~DriverManager()
DriverManager::~DriverManager ()
Destructor for the Driver Manager, removes all drivers and driver selectors.
Definition at line 107 of file driver.cpp.
                              {
    // Remove any drivers that are still attached
    while (!m_drivers.empty())
        remove_driver(*m_drivers.begin());
    // Free the driver selectors
    for (auto &driver_selector: m_driver_selectors)
        delete driver_selector;
}
References remove_driver().
Member Function Documentation
activate_drivers()
void DriverManager::activate_drivers ()
Activate the drivers.
Definition at line 232 of file driver.cpp.
                                     {
    Logger::INFO() << "Activating Drivers \n";
    // Activate the drivers
    for (auto &driver: m_drivers)
        driver->activate();
}
References MaxOS::Logger::INFO().
add_driver()
void DriverManager::add_driver (Driver * driver)
Adds a driver to the manager.
Parameters
driver The driver to add
Definition at line 124 of file driver.cpp.
                                             {
    m_drivers.push_back(driver);
}
Referenced by on_driver_selected().
add_driver_selector()
void DriverManager::add_driver_selector (DriverSelector * driver_selector)
Add a driver selector to the manager.
Parameters
driver_selector The driver selector to add
Definition at line 154 of file driver.cpp.
                                                                       {
    m_driver_selectors.push_back(driver_selector);
}
Referenced by DriverManager().
deactivate_drivers()
void DriverManager::deactivate_drivers ()
Deactivate the drivers.
Definition at line 221 of file driver.cpp.
                                       {
    // Deactivate the drivers
    for (auto &driver: m_drivers)
        driver->deactivate();
}
find_drivers()
void DriverManager::find_drivers ()
Find the drivers.
Definition at line 174 of file driver.cpp.
                                 {
    Logger::INFO() << "Finding Drivers \n";
    // Select the drivers
    for (auto &driver_selector: m_driver_selectors)
        driver_selector->select_drivers(this);
}
References MaxOS::Logger::INFO().
initialise_drivers()
void DriverManager::initialise_drivers ()
Initialise the drivers.
Definition at line 208 of file driver.cpp.
                                       {
    Logger::INFO() << "Initialising Drivers \n";
    // Initialise the drivers
    for (auto &driver: m_drivers)
        driver->initialise();
}
References MaxOS::Logger::INFO().
on_driver_selected()
void DriverManager::on_driver_selected (Driver * driver) [final], [virtual]
When a driver is selected add it to the manager.
Parameters
driver The driver that was selected
Reimplemented from MaxOS::drivers::DriverSelectorEventHandler.
Definition at line 145 of file driver.cpp.
                                                     {
    add_driver(driver);
}
References add_driver().
remove_driver()
void DriverManager::remove_driver (Driver * driver)
Removes a driver from the driver vector.
Parameters
driver The driver to remove
Definition at line 133 of file driver.cpp.
                                                {
    driver->deactivate();
    m_drivers.erase(driver);
}
Referenced by ~DriverManager().
remove_driver_selector()
void DriverManager::remove_driver_selector (DriverSelector * driver_selector)
Remove a driver selector from the manager.
Parameters
driver_selector The driver selector to remove
Definition at line 165 of file driver.cpp.
                                                                          {
    m_driver_selectors.erase(driver_selector);
}
reset_devices()
uint32_t DriverManager::reset_devices ()
Reset all the devices.
Returns
The longest time it takes to reset a device
Definition at line 188 of file driver.cpp.
                                      {
    Logger::INFO() << "Resetting Devices \n";
    uint32_t reset_wait_time = 0;
    for (auto &driver: m_drivers) {
        // Reset the driver
        uint32_t wait_time = driver->reset();
        // If the wait time is longer than the current longest wait time, set it as the new longest wait time
        if (wait_time > reset_wait_time)
            reset_wait_time = wait_time;
    }
    return reset_wait_time;
}
References MaxOS::Logger::INFO().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/driver.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/driver.cpp