MaxOS::drivers::peripherals::KeyboardDriver Class Reference
Driver for the Keyboard Controller, manages the events and the keyboard state.
#include <keyboard.h>
Public Member Functions
KeyboardDriver ()
Construct a new Keyboard Driver object, registering it as an interrupt handler for interrupt 0x21.
void handle_interrupt () final
deactivate the keyboard driver
void activate () final
activate the keyboard driver
string device_name () final
Get the device name.
Public Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
virtual system::cpu_status_t * handle_interrupt (system::cpu_status_t *status)
Handles an interrupt and returns the status.
Public Member Functions inherited from MaxOS::drivers::Driver
virtual void deactivate ()
Deactivate the driver.
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
virtual string vendor_name ()
Get who created the device.
Public Member Functions inherited from MaxOS::common::GenericInputStream< uint8_t >
GenericInputStream ()
Creates a new GenericInputStream.
GenericInputStream (InputStreamEventHandler< uint8_t > *)
Creates a new GenericInputStream and connects it to the handler.
~GenericInputStream ()
Destroys the GenericInputStream and disconnects all handlers.
void connect_input_stream_event_handler (InputStreamEventHandler< uint8_t > *)
Adds a inputStreamEventHandler to the list of internetProtocolHandlers.
void disconnect_input_stream_event_handler (InputStreamEventHandler< uint8_t > *)
Removes a handler from the list of handlers.
Additional Inherited Members
Protected Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
InterruptHandler (uint8_t interrupt_number, int64_t redirect=-1, uint64_t redirect_index=0)
Creates a new interrupt handler and registers it with the interrupt manager.
~InterruptHandler ()
Destroys the interrupt handler and unregisters it from the interrupt manager.
Protected Attributes inherited from MaxOS::hardwarecommunication::InterruptHandler
uint8_t m_interrupt_number
The interrupt number this handler handles.
Protected Attributes inherited from MaxOS::common::GenericInputStream< uint8_t >
common::Vector< InputStreamEventHandler< uint8_t > * > m_input_stream_event_handlers
List of streams being observed by this handler.
Detailed Description
Driver for the Keyboard Controller, manages the events and the keyboard state.
Definition at line 446 of file keyboard.h.
Constructor & Destructor Documentation
KeyboardDriver()
KeyboardDriver::KeyboardDriver ()
Construct a new Keyboard Driver object, registering it as an interrupt handler for interrupt 0x21.
Definition at line 67 of file keyboard.cpp.
: InterruptHandler(0x21, 0x1, 0x12),
  m_data_port(0x60),
  m_command_port(0x64)
{
}
Member Function Documentation
activate()
void KeyboardDriver::activate () [final], [virtual]
activate the keyboard driver
Reimplemented from MaxOS::drivers::Driver.
Definition at line 81 of file keyboard.cpp.
                              {
    // Wait for user to stop pressing key (this is for the start-up key e.g. hold 'F12' for boot menu or hold 'del' for bios)
    while (m_command_port.read() & 0x1)
        m_data_port.read();
    // Enable keyboard interrupts
    m_command_port.write(0xAE);
    // Get the current state of the keyboard
    m_command_port.write(0x20);
    uint8_t status = (m_data_port.read() | 1) & ~0x10;
    // Reset the keyboard
    m_command_port.write(0x60);
    m_data_port.write(status);
    // Activate the keyboard
    m_data_port.write(0xF4);
}
References MaxOS::hardwarecommunication::Port8Bit::read(), and MaxOS::hardwarecommunication::Port8Bit::write().
device_name()
string KeyboardDriver::device_name () [final], [virtual]
Get the device name.
Returns
The device name
Reimplemented from MaxOS::drivers::Driver.
Definition at line 117 of file keyboard.cpp.
                                   {
    return "Keyboard";
}
handle_interrupt()
void KeyboardDriver::handle_interrupt () [final], [virtual]
deactivate the keyboard driver
Reimplemented from MaxOS::hardwarecommunication::InterruptHandler.
Definition at line 105 of file keyboard.cpp.
                                      {
    // Pass the scan code to the m_handlers
    uint8_t key = m_data_port.read();
    for (auto &handler: m_input_stream_event_handlers)
        handler->on_stream_read(key);
}
References MaxOS::common::GenericInputStream< uint8_t >::m_input_stream_event_handlers, and MaxOS::hardwarecommunication::Port8Bit::read().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/peripherals/keyboard.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/peripherals/keyboard.cpp