MaxOS::drivers::console::Console Class Reference
Abstract class for a console, allows for the printing of characters and strings with colours.
#include <console.h>
Public Member Functions
Console ()
~Console ()
virtual uint16_t width ()
Get the width of the console in characters.
virtual uint16_t height ()
Get the height of the console in characters.
virtual void put_character (uint16_t x, uint16_t y, char c)
Put a character on the console.
virtual char get_character (uint16_t x, uint16_t y)
Get the character at a given coordinate on the console.
virtual void set_foreground_color (uint16_t x, uint16_t y, common::ConsoleColour foreground)
Set the foreground color of a character on the console.
virtual void set_background_color (uint16_t x, uint16_t y, common::ConsoleColour background)
Set the background color of a character on the console.
virtual common::ConsoleColour get_foreground_color (uint16_t x, uint16_t y)
Get the background color of a character on the console.
virtual common::ConsoleColour get_background_color (uint16_t x, uint16_t y)
Get the background color of a character on the console.
virtual void put_character (uint16_t x, uint16_t y, char c, common::ConsoleColour foreground, common::ConsoleColour background)
Put a character on the console with a given foreground and background color.
virtual void put_string (uint16_t x, uint16_t y, string s, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black)
Put a string on the console.
virtual void scroll_up ()
Scroll the entire console up by 1 line.
virtual void scroll_up (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black, char fill=' ')
Scroll an area of the console up by 1 line.
virtual void clear ()
virtual void clear (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black, char fill=' ')
Clear an area of the console.
virtual void invert_colors (uint16_t x, uint16_t y)
Invert the colors of a character on the console.
Detailed Description
Abstract class for a console, allows for the printing of characters and strings with colours.
Definition at line 23 of file console.h.
Constructor & Destructor Documentation
Console()
Console::Console () [default]
~Console()
Console::~Console () [default]
Member Function Documentation
clear() [1/2]
void Console::clear () [virtual]
Clear the entire console
Definition at line 170 of file console.cpp.
                    {
    clear(0, 0, width(), height());
}
References clear(), height(), and width().
Referenced by clear(), and MaxOS::drivers::console::VESABootConsole::VESABootConsole().
clear() [2/2]
void Console::clear (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground = common::ConsoleColour::LightGrey, common::ConsoleColour background = common::ConsoleColour::Black, char fill = ' ') [virtual]
Clear an area of the console.
Parameters
left The left coordinate of the area to clear
top The top coordinate of the area to clear
width The m_width of the area to clear
height The m_height of the area to clear
foreground The foreground color of the area
background The background color of the area
fill The character to fill the area with
Definition at line 187 of file console.cpp.
                                                                                                                                               {
    // Check bounds
    if (left > this -> width() || top > this -> height() || width > this -> width() || height > this -> height())
        return;
    // Fill the area with the character
    for(uint16_t y = top; y < top + height; y++)
        for(uint16_t x = left; x < left + width; x++)
            put_character(x, y, fill, foreground, background);
}
References height(), put_character(), and width().
get_background_color()
ConsoleColour Console::get_background_color (uint16_t x, uint16_t y) [virtual]
Get the background color of a character on the console.
Parameters
x The x coordinate of the character
y The y coordinate of the character
Returns
The background color of the character
Reimplemented in MaxOS::drivers::console::TextModeConsole, MaxOS::drivers::console::VESABootConsole, and MaxOS::drivers::console::ConsoleArea.
Definition at line 95 of file console.cpp.
                                                              {
    return ConsoleColour::Green;
}
Referenced by MaxOS::drivers::console::ConsoleArea::get_background_color(), invert_colors(), and scroll_up().
get_character()
char Console::get_character (uint16_t x, uint16_t y) [virtual]
Get the character at a given coordinate on the console.
Parameters
x The x coordinate of the character
y The y coordinate of the character
Returns
The character at the given coordinate
Reimplemented in MaxOS::drivers::console::TextModeConsole, MaxOS::drivers::console::VESABootConsole, and MaxOS::drivers::console::ConsoleArea.
Definition at line 73 of file console.cpp.
                                              {
    return ' ';
}
Referenced by MaxOS::drivers::console::ConsoleArea::get_character(), and scroll_up().
get_foreground_color()
ConsoleColour Console::get_foreground_color (uint16_t x, uint16_t y) [virtual]
Get the background color of a character on the console.
Parameters
x The x coordinate of the character
y The y coordinate of the character
Returns
The background color of the character
Reimplemented in MaxOS::drivers::console::TextModeConsole, MaxOS::drivers::console::VESABootConsole, and MaxOS::drivers::console::ConsoleArea.
Definition at line 84 of file console.cpp.
                                                              {
    return ConsoleColour::Green;
}
Referenced by MaxOS::drivers::console::ConsoleArea::get_foreground_color(), invert_colors(), and scroll_up().
height()
uint16_t Console::height () [virtual]
Get the height of the console in characters.
Returns
The height of the console in characters
Reimplemented in MaxOS::drivers::console::TextModeConsole, MaxOS::drivers::console::VESABootConsole, and MaxOS::drivers::console::ConsoleArea.
Definition at line 30 of file console.cpp.
                         {
    return 0;
}
Referenced by clear(), clear(), scroll_up(), scroll_up(), and MaxOS::drivers::console::ConsoleStream::write_char().
invert_colors()
void Console::invert_colors (uint16_t x, uint16_t y) [virtual]
Invert the colors of a character on the console.
Parameters
x The x coordinate of the character
y The y coordinate of the character
Definition at line 206 of file console.cpp.
                                                  {
    // Get the colors of the character
    ConsoleColour foreground = get_foreground_color(x, y);
    ConsoleColour background = get_background_color(x, y);
    // Set the colors of the character
    set_foreground_color(x, y, background);
    set_background_color(x, y, foreground);
}
References get_background_color(), get_foreground_color(), set_background_color(), and set_foreground_color().
put_character() [1/2]
void Console::put_character (uint16_t x, uint16_t y, char c) [virtual]
Put a character on the console.
Parameters
x The x coordinate of the character
y The y coordinate of the character
c The character to put on the console
Reimplemented in MaxOS::drivers::console::TextModeConsole, MaxOS::drivers::console::ConsoleArea, and MaxOS::drivers::console::VESABootConsole.
Definition at line 41 of file console.cpp.
                                                    {
}
Referenced by clear(), MaxOS::drivers::console::ConsoleArea::put_character(), put_character(), put_string(), scroll_up(), and MaxOS::drivers::console::ConsoleStream::write_char().
put_character() [2/2]
void Console::put_character (uint16_t x, uint16_t y, char c, common::ConsoleColour foreground, common::ConsoleColour background) [virtual]
Put a character on the console with a given foreground and background color.
Parameters
x The x coordinate of the character
y The y coordinate of the character
c The character to put on the console
foreground The foreground color of the character
background The background color of the character
Definition at line 108 of file console.cpp.
                                                                                                              {
    // Set the colors of the character
    set_foreground_color(x, y, foreground);
    set_background_color(x, y, background);
    // Put the character on the console
    put_character(x, y, c);
}
References put_character(), set_background_color(), and set_foreground_color().
put_string()
void Console::put_string (uint16_t x, uint16_t y, string string, common::ConsoleColour foreground = common::ConsoleColour::LightGrey, common::ConsoleColour background = common::ConsoleColour::Black) [virtual]
Put a string on the console.
Parameters
x The x coordinate of the string
y The y coordinate of the string
s The string to put on the console
foreground The foreground color of the string
background The background color of the string
Definition at line 128 of file console.cpp.
                                                                                                                  {
    // Print each character on the screen
    for(int i = 0; i < string.length(); i++)
        put_character(x + i, y, string[i], foreground, background);
}
References put_character().
scroll_up() [1/2]
void Console::scroll_up () [virtual]
Scroll the entire console up by 1 line.
Reimplemented in MaxOS::drivers::console::ConsoleArea.
Definition at line 138 of file console.cpp.
                        {
    scroll_up(0, 0, width(), height());
}
References height(), scroll_up(), and width().
Referenced by scroll_up(), MaxOS::drivers::console::ConsoleArea::scroll_up(), MaxOS::drivers::console::ConsoleArea::scroll_up(), and MaxOS::drivers::console::ConsoleStream::write_char().
scroll_up() [2/2]
void Console::scroll_up (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground = common::ConsoleColour::LightGrey, common::ConsoleColour background = common::ConsoleColour::Black, char fill = ' ') [virtual]
Scroll an area of the console up by 1 line.
Parameters
left The left coordinate of the area to scroll
top The top coordinate of the area to scroll
width The m_width of the area to scroll
height The m_height of the area to scroll
foreground The foreground color of the new line
background The background color of the new line
fill The character to fill the new line with
Reimplemented in MaxOS::drivers::console::VESABootConsole, and MaxOS::drivers::console::ConsoleArea.
Definition at line 154 of file console.cpp.
                                                                                                                                                   {
    // Shift everything but the last line by getting what is below it
    for(uint32_t y = top; y < top+height-1; y++)
        for(uint32_t x = left; x < left+width; x++)
            put_character(x, y, get_character(x, y + 1), get_foreground_color(x, y + 1), get_background_color(x, y + 1));
    // Fill the last line
    for(uint16_t x = left; x < left+width; x++)
        put_character(x, top + height - 1, fill, foreground, background);
}
References get_background_color(), get_character(), get_foreground_color(), height(), put_character(), and width().
set_background_color()
void Console::set_background_color (uint16_t x, uint16_t y, common::ConsoleColour background) [virtual]
Set the background color of a character on the console.
Parameters
x The x coordinate of the character
y The y coordinate of the character
background The background color to set
Reimplemented in MaxOS::drivers::console::ConsoleArea, MaxOS::drivers::console::TextModeConsole, and MaxOS::drivers::console::VESABootConsole.
Definition at line 62 of file console.cpp.
                                                                    {
}
Referenced by MaxOS::drivers::console::ConsoleArea::ConsoleArea(), invert_colors(), put_character(), and MaxOS::drivers::console::ConsoleArea::set_background_color().
set_foreground_color()
void Console::set_foreground_color (uint16_t x, uint16_t y, common::ConsoleColour foreground) [virtual]
Set the foreground color of a character on the console.
Parameters
x The x coordinate of the character
y The y coordinate of the character
foreground The foreground color to set
Reimplemented in MaxOS::drivers::console::ConsoleArea, MaxOS::drivers::console::TextModeConsole, and MaxOS::drivers::console::VESABootConsole.
Definition at line 51 of file console.cpp.
                                                                    {
}
Referenced by MaxOS::drivers::console::ConsoleArea::ConsoleArea(), invert_colors(), put_character(), and MaxOS::drivers::console::ConsoleArea::set_foreground_color().
width()
uint16_t Console::width () [virtual]
Get the width of the console in characters.
Returns
The width of the console in characters
Reimplemented in MaxOS::drivers::console::TextModeConsole, MaxOS::drivers::console::VESABootConsole, and MaxOS::drivers::console::ConsoleArea.
Definition at line 21 of file console.cpp.
                        {
    return 0;
}
Referenced by clear(), clear(), scroll_up(), scroll_up(), and MaxOS::drivers::console::ConsoleStream::write_char().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/console.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/console/console.cpp