MaxOS::tests::Test Class Reference
A basic test class.
#include <test.h>
Public Member Functions
Test (const string &name, TestType type)
Constructs a Test with a name and type, and registers it with the TestRunner.
TestStatus run ()
Runs the test and returns the result.
virtual TestStatus execute ()=0
Executes the test and returns the status of the test.
const string & name () const
Gets the name of the test.
TestType type () const
Gets the type of the test.
Detailed Description
A basic test class.
Definition at line 69 of file test.h.
Constructor & Destructor Documentation
Test()
Test::Test (const string & name, TestType type)
Constructs a Test with a name and type, and registers it with the TestRunner.
Parameters
name The name of the test
type The type of the test
Definition at line 21 of file test.cpp.
: m_name(name),
  m_type(type)
{
    TestRunner::add_test(this);
}
References MaxOS::tests::TestRunner::add_test().
Member Function Documentation
execute()
virtual TestStatus MaxOS::tests::Test::execute () [pure virtual]
Executes the test and returns the status of the test.
Returns
The result of the test execution
Implemented in MaxOS::tests::ConditionalTest.
Referenced by run().
name()
const string & Test::name () const
Gets the name of the test.
Returns
The name of the test
Definition at line 68 of file test.cpp.
                               {
    return m_name;
}
run()
TestStatus Test::run ()
Runs the test and returns the result.
Returns
TestStatus The status of the test after running
Definition at line 33 of file test.cpp.
                     {
    // Run the test
    auto result = execute();
    StringBuilder msg;
    // Build the message
    msg << "Test ";
    switch(result) {
        case TestStatus::PASS:
            msg << "PASSED";
            break;
        case TestStatus::SKIP:
            msg << "SKIPPED";
            break;
        case TestStatus::FAIL:
            msg << "FAILED";
            break;
    }
    msg << " - " << m_name << "\n";
    // Print the outcome
    if (result == TestStatus::FAIL)
        Logger::ERROR() << msg.out;
    else
        Logger::TEST() << msg.out;
    return result;
}
References MaxOS::Logger::ERROR(), execute(), MaxOS::StringBuilder::out, and MaxOS::Logger::TEST().
type()
TestType Test::type () const
Gets the type of the test.
Returns
The type of the test
Definition at line 77 of file test.cpp.
                          {
    return m_type;
}
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/tests/test.h
/home/runner/work/MaxOS/MaxOS/kernel/src/tests/test.cpp