MaxOS::common::Vector< Type > Class Template Reference
Dynamically stores an array of elements.
#include <vector.h>
Public Types
typedef Type * iterator
The iterator type for the Vector.
Public Member Functions
Vector ()
______________________________________Implementation__________________________________________________
Vector (int size, Type element)
Constructor for Vector.
Vector (const Vector< Type > &other)
Copy constructor for Vector.
Vector (Vector< Type > &&other)
Move constructor for Vector.
~Vector ()
Destructor for Vector, de-allocates the array.
Type & operator[] (uint32_t index) const
Overloads the [] operator to return the element at the index.
Vector< Type > & operator= (const Vector< Type > &other)
Assignment by copy, data is copied into a new buffer stored in this vector.
Vector< Type > & operator= (Vector< Type > &&other)
Assignment by move, data is moved into the buffer stored in this vector and the other vector is cleared.
bool empty () const
Checks if the Vector is empty.
uint32_t size () const
Returns the number of elements in the Vector.
iterator begin () const
Returns the first element of the Vector.
iterator end () const
Returns the last element of the Vector.
iterator find (Type) const
Finds an element in the Vector and returns the iterator of the element.
iterator push_back (Type)
Adds an element to the end of the vector and returns the iterator of the element.
Type pop_back ()
Removes the last element from the Vector.
iterator push_front (Type)
Adds an element to the front of the Vector and returns the iterator of the element.
Type pop_front ()
Removes the m_first_memory_chunk element from the Vector.
void erase (Type)
Removes all elements from the Vector that are equal to the element.
void erase (typename Vector< Type >::iterator position)
Removes the element at the m_position.
void clear ()
Removes all elements from the Vector.
void reserve (size_t amount)
Reserves space in the Vector for a certain amount of elements.
void increase_size ()
Increases the size of the Vector by doubling the capacity.
void iterate (VectorIterationHandler< Type > *)
Iterates over the Vector and calls the OnRead function of the handler for each element.
void iterate (void callback(Type &))
Iterates over the Vector and calls the callback function for each element.
Protected Attributes
Type * m_elements
The array of elements.
uint32_t m_size { 0 }
How many elements are currently stored.
uint32_t m_capacity { 1 }
How many elements can be stored without resizing.
Detailed Description
template<class Type>
class MaxOS::common::Vector< Type >
Dynamically stores an array of elements.
Template Parameters
Type Type of the Vector
Definition at line 39 of file vector.h.
Member Typedef Documentation
iterator
template<class Type >
typedef Type* MaxOS::common::Vector< Type >::iterator
The iterator type for the Vector.
Definition at line 46 of file vector.h.
Constructor & Destructor Documentation
Vector() [1/4]
template<class Type >
MaxOS::common::Vector< Type >::Vector ()
______________________________________Implementation__________________________________________________
Constructor for Vector
Template Parameters
Type Type of the Vector
Definition at line 88 of file vector.h.
                                              {
        // Allocate space for the array
        m_elements = new Type[m_capacity];
    }
Vector() [2/4]
template<class Type >
MaxOS::common::Vector< Type >::Vector (int size, Type element)
Constructor for Vector.
Template Parameters
Type Type of the Vector
Parameters
size Size of the Vector
element Element to fill the Vector with
Definition at line 102 of file vector.h.
                                                                    {
        // Allocate space for the array
        m_elements = new Type[size];
        m_capacity = size > 0 ? size : 1;
        m_size = 0;
        // Push all the elements to the Vector
        for(int i = 0; i < size; ++i)
            push_back(element);
    }
Vector() [3/4]
template<class Type >
MaxOS::common::Vector< Type >::Vector (const Vector< Type > & other)
Copy constructor for Vector.
Template Parameters
Type The type of data to be stored
Parameters
other The vector to copy from
Definition at line 120 of file vector.h.
            : m_size(other.m_size),
            m_capacity(other.m_capacity) {
        // Copy each element into a new array
        m_elements = new Type[m_capacity];
        for(uint32_t i = 0; i < m_size; ++i)
            m_elements[i] = other.m_elements[i];
    }
References MaxOS::common::Vector< Type >::m_capacity, MaxOS::common::Vector< Type >::m_elements, and MaxOS::common::Vector< Type >::m_size.
Vector() [4/4]
template<class Type >
MaxOS::common::Vector< Type >::Vector (Vector< Type > && other)
Move constructor for Vector.
Template Parameters
Type The type of data to be stored
Parameters
other The vector to copy from
Definition at line 135 of file vector.h.
            : m_elements(other.m_elements),
            m_size(other.m_size),
            m_capacity(other.m_capacity) {
        // Clear the other Vector
        other.m_elements = nullptr;
        other.m_size = 0;
        other.m_capacity = 0;
    }
~Vector()
template<class Type >
MaxOS::common::Vector< Type >::~Vector ()
Destructor for Vector, de-allocates the array.
Template Parameters
Type Type data stored in the Vector
Definition at line 152 of file vector.h.
                                               {
        // De-allocate the array
        delete[] m_elements;
    }
Member Function Documentation
begin()
template<class Type >
Vector< Type >::iterator MaxOS::common::Vector< Type >::begin () const
Returns the first element of the Vector.
Template Parameters
Type Type of the Vector
Returns
The first element of the Vector
Definition at line 283 of file vector.h.
                                                                                 {
        return &m_elements[0];
    }
Referenced by MaxOS::common::Map< Key, Value >::begin().
clear()
template<class Type >
void MaxOS::common::Vector< Type >::clear ()
Removes all elements from the Vector.
Template Parameters
Type Type of the Vector
Definition at line 461 of file vector.h.
                                                  {
        m_size = 0;
    }
Referenced by MaxOS::common::Map< Key, Value >::clear(), and MaxOS::filesystem::format::ext2::Ext2Directory::read_from_disk().
empty()
template<class Type >
bool MaxOS::common::Vector< Type >::empty () const
Checks if the Vector is empty.
Template Parameters
Type Type of the Vector
Returns
True if the Vector is empty, false otherwise
Definition at line 321 of file vector.h.
                                                        {
        return begin() == end();
    }
Referenced by MaxOS::common::Map< Key, Value >::empty(), and MaxOS::common::BlockingLock::release().
end()
template<class Type >
Vector< Type >::iterator MaxOS::common::Vector< Type >::end () const
Returns the last element of the Vector.
Template Parameters
Type Type of the Vector
Returns
The last element of the Vector
Definition at line 293 of file vector.h.
                                                                               {
        return &m_elements[0] + m_size;
    }
Referenced by MaxOS::common::Map< Key, Value >::end().
erase() [1/2]
template<class Type >
void MaxOS::common::Vector< Type >::erase (Type element)
Removes all elements from the Vector that are equal to the element.
Template Parameters
Type Type of the Vector
Parameters
element The element to remove
Definition at line 415 of file vector.h.
                                                              {
        // Search for the element
        int hits = 0;
        for(iterator i = begin(); i != end(); ++i) {
            // If it is the element we are looking for
            if(*i == element) {
                ++hits;
            } else {
                // If there are hits move the element to the left
                if(hits > 0)
                    *(i - hits) = *i;
            }
        }
        // Decrease the size of the Vector
        m_size -= hits;
    }
References MaxOS::common::Rectangle< Type >::Rectangle().
Referenced by MaxOS::common::Map< Key, Value >::erase(), and MaxOS::common::Map< Key, Value >::erase().
erase() [2/2]
template<class Type >
void MaxOS::common::Vector< Type >::erase (typename Vector< Type >::iterator position)
Removes the element at the m_position.
Template Parameters
Type The type of the Vector
Parameters
position The m_position of the element to remove
Definition at line 442 of file vector.h.
                                                                                        {
        // If the m_position is not in the Vector
        if(position < begin() || position >= end())
            return;
        // Move all elements one index to the left
        for(++position; position != end(); ++position)
            *(position - 1) = *position;
        // Decrease the size of the Vector
        --m_size;
    }
find()
template<class Type >
Vector< Type >::iterator MaxOS::common::Vector< Type >::find (Type element) const
Finds an element in the Vector and returns the iterator of the element.
Template Parameters
Type Type of the Vector
Parameters
element The element to find
Returns
The iterator of the element or the end of the Vector if the element is not found
Definition at line 304 of file vector.h.
                                                                                            {
        // Find the element
        for(iterator i = begin(); i != end(); ++i)
            if(*i == element)
                return i;
        // The element must not be in the Vector
        return end();
    }
increase_size()
template<class Type >
void MaxOS::common::Vector< Type >::increase_size ()
Increases the size of the Vector by doubling the capacity.
Template Parameters
Type Type of the Vector
Definition at line 164 of file vector.h.
                                                          {
        reserve(m_capacity * 2);
    }
Referenced by MaxOS::common::Map< Key, Value >::increase_size().
iterate() [1/2]
template<class Type >
void MaxOS::common::Vector< Type >::iterate (VectorIterationHandler< Type > * vector_iteration_handler)
Iterates over the Vector and calls the OnRead function of the handler for each element.
Template Parameters
Type Type of the Vector
Parameters
vector_iteration_handler The handler
Definition at line 471 of file vector.h.
                                                                                                          {
        // Call the OnRead function of the handler for each element
        for(auto& element : m_elements)
            vector_iteration_handler->on_read(element);
        // Call the OnEndOfStream function of the handler
        vector_iteration_handler->on_end_of_stream();
    }
iterate() [2/2]
template<class Type >
void MaxOS::common::Vector< Type >::iterate (void callbackType &)
Iterates over the Vector and calls the callback function for each element.
Template Parameters
Type Type of the Vector
Parameters
callback The callback function
Definition at line 488 of file vector.h.
                                                                        {
        // Call the callback function for each element
        for(auto& element : m_elements)
            callback(element);
    }
References MaxOS::common::Rectangle< Type >::Rectangle().
operator=() [1/2]
template<class Type >
Vector< Type > & MaxOS::common::Vector< Type >::operator= (const Vector< Type > & other)
Assignment by copy, data is copied into a new buffer stored in this vector.
Template Parameters
Type Type of the Vector
Parameters
other The vector to copy from
Returns
This vector, with the copied elements
Definition at line 221 of file vector.h.
                                                                                         {
        // Setting to itself?
        if(this == &other)
            return *this;
        // Create a new buffer to store the elements
        delete[] m_elements;
        m_elements = new Type[other.m_capacity];
        // Copy data
        m_size = other.m_size;
        m_capacity = other.m_capacity;
        for(uint32_t i = 0; i < m_size; ++i)
            m_elements[i] = other.m_elements[i];
        return *this;
    }
operator=() [2/2]
template<class Type >
Vector< Type > & MaxOS::common::Vector< Type >::operator= (Vector< Type > && other)
Assignment by move, data is moved into the buffer stored in this vector and the other vector is cleared.
Template Parameters
Type Type of the Vector
Parameters
other The vector to copy from
Returns
This vector, with the copied elements
Definition at line 247 of file vector.h.
                                                                                    {
        // Moving to itself?
        if(this == &other)
            return *this;
        // Move into this vector
        delete[] m_elements;
        m_elements = other.m_elements;
        m_size = other.m_size;
        m_capacity = other.m_capacity;
        // Remove from other vector
        other.m_elements = nullptr;
        other.m_size = 0;
        other.m_capacity = 0;
        return *this;
    }
operator[]()
template<class Type >
Type & MaxOS::common::Vector< Type >::operator[] (uint32_t index) const
Overloads the [] operator to return the element at the index.
Template Parameters
Type Type of the Vector
Parameters
index The index of the element
Returns
the element at the index or the end of the Vector if the index is out of bounds
Definition at line 203 of file vector.h.
                                                                             {
        // If the index is in the Vector
        if(index < m_size)
            return m_elements[index];
        // Return the last element of the Vector
        return m_elements[m_size - 1];
    }
pop_back()
template<class Type >
Type MaxOS::common::Vector< Type >::pop_back ()
Removes the last element from the Vector.
Template Parameters
Type Type of the Vector
Returns
The element that was removed
Definition at line 350 of file vector.h.
                                                     {
        // Remove the last element from the Vector
        if(m_size > 0)
            --m_size;
        return m_elements[m_size];
    }
Referenced by MaxOS::common::Map< Key, Value >::pop_back().
pop_front()
template<class Type >
Type MaxOS::common::Vector< Type >::pop_front ()
Removes the m_first_memory_chunk element from the Vector.
Template Parameters
Type Type of the Vector
Returns
The element that was removed, or a default constructed element if the Vector is empty
Definition at line 390 of file vector.h.
                                                      {
        // Make sure the Vector is not empty
        if(m_size == 0)
            return Type();
        // Store the element to return
        Type element = m_elements[0];
        // Move all elements one index to the left
        for(uint32_t i = 0; i < m_size - 1; ++i)
            m_elements[i] = m_elements[i + 1];
        // Decrease the size of the Vector
        --m_size;
        return element;
    }
References MaxOS::common::Rectangle< Type >::Rectangle().
Referenced by MaxOS::common::Map< Key, Value >::pop_front(), and MaxOS::common::BlockingLock::release().
push_back()
template<class Type >
Vector< Type >::iterator MaxOS::common::Vector< Type >::push_back (Type element)
Adds an element to the end of the vector and returns the iterator of the element.
Template Parameters
Type Type of the Vector
Parameters
element The element to add
Returns
The iterator of the element, if the Vector is full it returns the end of the Vector
Definition at line 333 of file vector.h.
                                                                                           {
        // Check if we need to allocate more space for the array
        if(m_size == m_capacity)
            increase_size();
        // Add the element to the Vector and return the iterator of the element
        m_elements[m_size++] = element;
        return end() - 1;
    }
References MaxOS::common::Rectangle< Type >::Rectangle().
Referenced by MaxOS::common::BlockingLock::acquire(), MaxOS::filesystem::format::ext2::InodeHandler::InodeHandler(), MaxOS::common::Map< Key, Value >::insert(), MaxOS::common::Map< Key, Value >::push_back(), and MaxOS::common::EventManager< EventType >::raise_event().
push_front()
template<class Type >
Vector< Type >::iterator MaxOS::common::Vector< Type >::push_front (Type element)
Adds an element to the front of the Vector and returns the iterator of the element.
Template Parameters
Type Type of the Vector
Parameters
element The element to add
Returns
The iterator of the element, if the Vector is full it returns the end of the Vector
Definition at line 366 of file vector.h.
                                                                                            {
        // Check if we need to allocate more space for the array
        if(m_size == m_capacity)
            increase_size();
        // Move all elements one index to the right
        for(iterator i = end(); i > begin(); --i)
            *i = *(i - 1);
        // Add the element to the front of the Vector
        m_elements[0] = element;
        ++m_size;
        // Return the iterator of the element
        return begin();
    }
References MaxOS::common::Rectangle< Type >::Rectangle().
Referenced by MaxOS::common::Map< Key, Value >::push_front().
reserve()
template<class Type >
void MaxOS::common::Vector< Type >::reserve (size_t amount)
Reserves space in the Vector for a certain amount of elements.
Template Parameters
Type Type of the Vector
Parameters
amount The amount of elements to reserve space for
Definition at line 174 of file vector.h.
                                                                 {
        // Increase the capacity of the Vector
        if(m_capacity < amount)
            m_capacity = amount;
        // Allocate more space for the array
        Type* new_elements = new Type[amount];
        // Copy the elements to the new array
        for(uint32_t i = 0; i < m_size; ++i)
            new_elements[i] = m_elements[i];
        // De-allocate the old array
        delete[] m_elements;
        // Set the new array
        m_elements = new_elements;
    }
References MaxOS::common::Rectangle< Type >::Rectangle().
Referenced by MaxOS::common::Map< Key, Value >::reserve().
size()
template<class Type >
uint32_t MaxOS::common::Vector< Type >::size () const
Returns the number of elements in the Vector.
Template Parameters
Type Type of the Vector
Returns
The size of the Vector
Definition at line 273 of file vector.h.
                                                           {
        return m_size;
    }
Referenced by MaxOS::common::Map< Key, Value >::size().
Member Data Documentation
m_capacity
template<class Type >
uint32_t MaxOS::common::Vector< Type >::m_capacity { 1 } [protected]
How many elements can be stored without resizing.
Definition at line 43 of file vector.h.
{ 1 };
Referenced by MaxOS::common::Vector< Type >::Vector().
m_elements
template<class Type >
Type* MaxOS::common::Vector< Type >::m_elements [protected]
The array of elements.
Definition at line 41 of file vector.h.
Referenced by MaxOS::common::Vector< Type >::Vector().
m_size
template<class Type >
uint32_t MaxOS::common::Vector< Type >::m_size { 0 } [protected]
How many elements are currently stored.
Definition at line 42 of file vector.h.
{ 0 };
Referenced by MaxOS::common::Vector< Type >::Vector().
The documentation for this class was generated from the following file:
/home/runner/work/MaxOS/MaxOS/kernel/include/common/vector.h