MaxOS::common::GraphicsContext Class Reference
Draws pixels to the screen, and handles drawing lines, rectangles and circles.
#include <graphicsContext.h>
Public Member Functions
GraphicsContext ()
~GraphicsContext ()
uint32_t colour_to_int (Colour)
Converts a colour to an integer value based on the current color depth.
Colour int_to_colour (uint32_t)
Converts an integer value to a colour based on the current color depth.
uint32_t get_width ()
Gets the width of the screen.
uint32_t get_height ()
Gets the height of the screen.
uint32_t get_color_depth ()
uint64_t * get_framebuffer_address ()
void put_pixel (int32_t x, int32_t y, Colour colour)
Renders a pixel to the screen (automatically converts the colour to an integer)
void putPixel (int32_t x, int32_t y, int32_t colour)
Renders a pixel to the screen (automatically converts the colour to an integer), will not render the pixel if it is outside the screen.
Colour get_pixel (int32_t x, int32_t y)
Gets the colour of a pixel, or returns black if the pixel is outside the screen.
void invert_pixel (int32_t x, int32_t y)
Inverts a pixel.
void draw_line (int32_t x0, int32_t y0, int32_t x1, int32_t y1, Colour colour)
Draws a line on the screen.
void drawLine (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a line on the screen.
void draw_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, Colour colour)
Draws a rectangle on the screen.
void draw_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a rectangle on the screen.
void fill_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, Colour colour)
Draws a rectangle on the screen, filled with a colour.
void fill_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a rectangle on the screen, filled with a colour.
void draw_circle (int32_t x0, int32_t y0, int32_t radius, Colour colour)
Draws a circle on the screen.
void draw_circle (int32_t x0, int32_t y0, int32_t radius, uint32_t colour)
Draws a circle on the screen.
void fill_circle (int32_t x0, int32_t y0, int32_t radius, Colour colour)
Draws a circle on the screen, filled with a colour.
void fillCircle (int32_t x0, int32_t y0, int32_t radius, uint32_t colour)
Draws a circle on the screen, filled with a colour.
Protected Member Functions
virtual void render_pixel (uint32_t x, uint32_t y, uint32_t colour)
Renders a pixel to the screen based on the current color depth.
virtual void render_pixel_8_bit (uint32_t x, uint32_t y, uint8_t colour)
Renders a pixel to the screen using the 8 bit color depth.
virtual void render_pixel_16_bit (uint32_t x, uint32_t y, uint16_t colour)
Renders a pixel to the screen using the 16 bit color depth.
virtual void render_pixel_24_bit (uint32_t x, uint32_t y, uint32_t colour)
Renders a pixel to the screen using the 24 bit color depth.
virtual void render_pixel_32_bit (uint32_t x, uint32_t y, uint32_t colour)
Renders a pixel to the screen using the 32 bit color depth.
virtual uint32_t get_rendered_pixel (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen, automatically uses the correct color depth.
virtual uint8_t get_rendered_pixel_8_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 8 bit color depth.
virtual uint16_t get_rendered_pixel_16_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 16 bit color depth.
virtual uint32_t get_rendered_pixel_24_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 24 bit color depth.
virtual uint32_t get_rendered_pixel_32_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 32 bit color depth.
Protected Attributes
bool mirror_y_axis { false }
uint32_t m_width { 0 }
uint32_t m_height { 0 }
uint32_t m_color_depth { 0 }
Colour m_colour_pallet [256]
uint64_t * m_framebuffer_address { nullptr }
Detailed Description
Draws pixels to the screen, and handles drawing lines, rectangles and circles.
Definition at line 19 of file graphicsContext.h.
Constructor & Destructor Documentation
GraphicsContext()
GraphicsContext::GraphicsContext ()
Definition at line 11 of file graphicsContext.cpp.
{
    // VirtualBox VGA palette
    m_colour_pallet[0x00] = Colour(0x00,0x00,0x00); // Black
    m_colour_pallet[0x01] = Colour(0x00,0x00,0xA8); // Duke Blue
    m_colour_pallet[0x02] = Colour(0x00,0xA8,0x00); // Islamic Green
    m_colour_pallet[0x03] = Colour(0x00,0xA8,0xA8); // Persian Green
    m_colour_pallet[0x04] = Colour(0xA8,0x00,0x00); // Dark Candy Apple Red
    m_colour_pallet[0x05] = Colour(0xA8,0x00,0xA8); // Heliotrope Magenta
    m_colour_pallet[0x06] = Colour(0xA8,0xA8,0x00); // Light Gold
    m_colour_pallet[0x07] = Colour(0xA8,0xA8,0xA8); // Dark Gray (X11)
    m_colour_pallet[0x08] = Colour(0x00,0x00,0x57); // Cetacean Blue
    m_colour_pallet[0x09] = Colour(0x00,0x00,0xFF); // Blue
    m_colour_pallet[0x0A] = Colour(0x00,0xA8,0x57); // Green (Pigment)
    m_colour_pallet[0x0B] = Colour(0x00,0xA8,0xFF); // Vivid Cerulean
    m_colour_pallet[0x0C] = Colour(0xA8,0x00,0x57); // Jazzberry Jam
    m_colour_pallet[0x0D] = Colour(0xA8,0x00,0x57); // Jazzberry Jam
    m_colour_pallet[0x0E] = Colour(0xA8,0xA8,0x57); // Olive Green
    m_colour_pallet[0x0F] = Colour(0xA8,0xA8,0xFF); // Maximum Blue Purple
    m_colour_pallet[0x10] = Colour(0x00,0x57,0x00); // Dark Green (X11)
    m_colour_pallet[0x11] = Colour(0x00,0x57,0xA8); // Cobalt Blue
    m_colour_pallet[0x12] = Colour(0x00,0xFF,0x00); // Electric Green
    m_colour_pallet[0x13] = Colour(0x00,0xFF,0xA8); // Medium Spring Green
    m_colour_pallet[0x14] = Colour(0xA8,0x57,0x00); // Windsor Tan
    m_colour_pallet[0x15] = Colour(0xA8,0x57,0xA8); // Purpureus
    m_colour_pallet[0x16] = Colour(0xA8,0xFF,0x00); // Spring Bud
    m_colour_pallet[0x17] = Colour(0xA8,0xFF,0xA8); // Mint Green
    m_colour_pallet[0x18] = Colour(0x00,0x57,0x57); // Midnight Green (Eagle Green)
    m_colour_pallet[0x19] = Colour(0x00,0x57,0xFF); // Blue (RYB)
    m_colour_pallet[0x1A] = Colour(0x00,0xFF,0x57); // Malachite
    m_colour_pallet[0x1B] = Colour(0x00,0xFF,0xFF); // Aqua
    m_colour_pallet[0x1C] = Colour(0xA8,0x57,0x57); // Middle Red Purple
    m_colour_pallet[0x1D] = Colour(0xA8,0x57,0xFF); // Lavender Indigo
    m_colour_pallet[0x1E] = Colour(0xA8,0xFF,0x57); // Olive Green
    m_colour_pallet[0x1F] = Colour(0xA8,0xFF,0xFF); // Celeste
    m_colour_pallet[0x20] = Colour(0x57,0x00,0x00); // Blood Red
    m_colour_pallet[0x21] = Colour(0x57,0x00,0xA8); // Metallic Violet
    m_colour_pallet[0x22] = Colour(0x57,0xA8,0x00); // Kelly Green
    m_colour_pallet[0x23] = Colour(0x57,0xA8,0xA8); // Cadet Blue
    m_colour_pallet[0x24] = Colour(0xFF,0x00,0x00); // Red
    m_colour_pallet[0x25] = Colour(0xFF,0x00,0xA8); // Fashion Fuchsia
    m_colour_pallet[0x26] = Colour(0xFF,0xA8,0x00); // Chrome Yellow
    m_colour_pallet[0x27] = Colour(0xFF,0xA8,0xA8); // Light Salmon Pink
    m_colour_pallet[0x28] = Colour(0x57,0x00,0x57); // Imperial Purple
    m_colour_pallet[0x29] = Colour(0x57,0x00,0xFF); // Electric Indigo
    m_colour_pallet[0x2A] = Colour(0x57,0xA8,0x57); // Apple
    m_colour_pallet[0x2B] = Colour(0x57,0xA8,0xFF); // Blue Jeans
    m_colour_pallet[0x2C] = Colour(0xFF,0x00,0x57); // Folly
    m_colour_pallet[0x2D] = Colour(0xFF,0x00,0xFF); // Fuchsia
    m_colour_pallet[0x2E] = Colour(0xFF,0xA8,0x57); // Rajah
    m_colour_pallet[0x2F] = Colour(0xFF,0xA8,0xFF); // Rich Brilliant Lavender
    m_colour_pallet[0x30] = Colour(0x57,0x57,0x00); // Dark Bronze (Coin)
    m_colour_pallet[0x31] = Colour(0x57,0x57,0xA8); // Liberty
    m_colour_pallet[0x32] = Colour(0x57,0xFF,0x00); // Chlorophyll Green
    m_colour_pallet[0x33] = Colour(0x57,0xFF,0xA8); // Medium Aquamarine
    m_colour_pallet[0x34] = Colour(0xFF,0x57,0x00); // Orange (Pantone)
    m_colour_pallet[0x35] = Colour(0xFF,0x57,0xA8); // Brilliant Rose
    m_colour_pallet[0x36] = Colour(0xFF,0xFF,0x00); // Yellow
    m_colour_pallet[0x37] = Colour(0xFF,0xFF,0xA8); // Calamansi
    m_colour_pallet[0x38] = Colour(0x57,0x57,0x57); // Davy's Grey
    m_colour_pallet[0x39] = Colour(0x57,0x57,0xFF); // Very Light Blue
    m_colour_pallet[0x3A] = Colour(0x57,0xFF,0x57); // Screamin' Green
    m_colour_pallet[0x3B] = Colour(0x57,0xFF,0xFF); // Electric Blue
    m_colour_pallet[0x3C] = Colour(0xFF,0x57,0x57); // Sunset Orange
    m_colour_pallet[0x3D] = Colour(0xFF,0x57,0xFF); // Shocking Pink (Crayola)
    m_colour_pallet[0x3E] = Colour(0xFF,0xFF,0x57); // Shocking Pink (Crayola)
    m_colour_pallet[0x3F] = Colour(0xFF,0xFF,0xFF); // White
    // Set the rest of the palette to black
    for(uint8_t color_code = 255; color_code >= 0x40; --color_code)
      m_colour_pallet[color_code] = Colour(0,0,0);
}
References m_colour_pallet.
 GraphicsContext()
GraphicsContext::~GraphicsContext ()
Definition at line 93 of file graphicsContext.cpp.
                                  {
}
Member Function Documentation
colour_to_int()
uint32_t GraphicsContext::colour_to_int (Colour colour)
Converts a colour to an integer value based on the current color depth.
Parameters
colour The colour class to convert
Returns
The integer value of the colour
Definition at line 242 of file graphicsContext.cpp.
                                                     {
    switch(m_color_depth)
    {
        case 8:
        {
            uint32_t result = 0;
            int mindistance = 0xfffffff;
            for(uint32_t i = 0; i <= 255; ++i)
            {
                Colour* c = &m_colour_pallet[i];
                int distance =
                        ((int)colour.red-(int)c->red)*((int)colour.red-(int)c->red)
                        +((int)colour.green-(int)c->green)*((int)colour.green-(int)c->green)
                        +((int)colour.blue-(int)c->blue)*((int)colour.blue-(int)c->blue);
                if(distance < mindistance)
                {
                    mindistance = distance;
                    result = i;
                }
            }
            return result;
        }
        case 16:
        {
            // 16-Bit colours RRRRRGGGGGGBBBBB
            return ((uint16_t)(colour.red & 0xF8)) << 8
                   | ((uint16_t)(colour.green & 0xFC)) << 3
                   | ((uint16_t)(colour.blue & 0xF8) >> 3);
        }
        case 24:
        {
            return (uint32_t)colour.red << 16
                   | (uint32_t)colour.green << 8
                   | (uint32_t)colour.blue;
        }
        default:
        case 32:
        {
            uint32_t red_hex = ((uint32_t)colour.red & 0xFF) << 16;
            uint32_t green_hex = ((uint32_t)colour.green & 0xFF) << 8;
            uint32_t blue_hex = (uint32_t)colour.blue & 0xFF;
            uint32_t alpha_hex = ((uint32_t)colour.alpha & 0xFF) << 24;
            uint32_t hexValue = red_hex | green_hex | blue_hex | alpha_hex;
            return hexValue;
        }
    }
}
References MaxOS::common::Colour::alpha, MaxOS::common::Colour::blue, MaxOS::drivers::peripherals::c, MaxOS::common::Colour::green, MaxOS::drivers::peripherals::i, m_color_depth, m_colour_pallet, and MaxOS::common::Colour::red.
Referenced by draw_circle(), draw_line(), draw_rectangle(), MaxOS::gui::Font::draw_text(), fill_circle(), fill_rectangle(), get_rendered_pixel(), put_pixel(), and MaxOS::drivers::console::VESABootConsole::scroll_up().
draw_circle() [1/2]
void GraphicsContext::draw_circle (int32_t x0, int32_t y0, int32_t radius, Colour colour)
Draws a circle on the screen.
Parameters
x0 The x coordinate of the centre of the circle
y0 The y coordinate of the centre of the circle
radius The radius of the circle
colour The colour of the circle
Definition at line 673 of file graphicsContext.cpp.
                                                                                      {
  draw_circle(x0, y0, radius, colour_to_int(colour));
}
References colour_to_int().
draw_circle() [2/2]
void GraphicsContext::draw_circle (int32_t x0, int32_t y0, int32_t radius, uint32_t colour)
Draws a circle on the screen.
Parameters
x0 The x coordinate of the centre of the circle
y0 The y coordinate of the centre of the circle
radius The radius of the circle
colour The colour of the circle
Definition at line 685 of file graphicsContext.cpp.
                                                                                         {
    // Make sure the circle is with in the width and height of the screen
    if(x0 < 0) x0 = 0;
    if((uint32_t)x0 > m_width) x0 = m_width;
    if(y0 < 0) y0 = 0;
    if((uint32_t)y0 > m_height) y0 = m_height;
    // Mirror the Y axis as directly calling put_pixel will not do this
    if(mirror_y_axis)
        y0 = m_height -y0-1;
    // Begin drawing at the left most point of the circle and draw a line to the right most point of the circle
    for(int32_t x = -radius; x <= radius; ++x){
        // Draw a line from the top most point of the circle to the bottom most point of the circle
        for(int32_t y = -radius; y <= radius; ++y){
            // If the point is within the circle, draw it but make sure it is only part of the outline
            if(x*x + y*y <= radius*radius && x*x + y*y >= (radius-1)*(radius-1))
                putPixel(x0+x,y0+y,colour);
        }
    }
}
References m_height, m_width, mirror_y_axis, putPixel(), MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
draw_line()
void GraphicsContext::draw_line (int32_t x0, int32_t y0, int32_t x1, int32_t y1, Colour colour)
Draws a line on the screen.
Parameters
x0 The x coordinate of the m_first_memory_chunk point
y0 The y coordinate of the m_first_memory_chunk point
x1 The x coordinate of the final point
y1 The y coordinate of the final point
colour The colour of the line
Definition at line 467 of file graphicsContext.cpp.
                                                                                             {
    drawLine(x0,y0,x1,y1, colour_to_int(colour));
}
References colour_to_int(), and drawLine().
Referenced by MaxOS::gui::widgets::InputBox::draw(), and MaxOS::gui::widgets::Button::draw().
draw_rectangle() [1/2]
void GraphicsContext::draw_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, Colour colour)
Draws a rectangle on the screen.
Parameters
x0 The x coordinate of the top left corner
y0 The y coordinate of the top left corner
x1 The x coordinate of the bottom right corner
y1 The y coordinate of the bottom right corner
colour The colour of the rectangle
Definition at line 577 of file graphicsContext.cpp.
                                                                                                  {
  draw_rectangle(x0, y0, x1, y1, colour_to_int(colour));
}
References colour_to_int().
draw_rectangle() [2/2]
void GraphicsContext::draw_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a rectangle on the screen.
Parameters
x0 The x coordinate of the top left corner
y0 The y coordinate of the top left corner
x1 The x coordinate of the bottom right corner
y1 The y coordinate of the bottom right corner
colour The colour of the rectangle
Definition at line 591 of file graphicsContext.cpp.
                                                                                                    {
    // Ensure x and y 0 is smaller than x and y 1
    --y0;
    --x0;
    // Draw the rectangle
    drawLine(x0,y0,x1,y0,colour); // Top
    drawLine(x0,y1,x1,y1,colour); // Bottom
    drawLine(x0,y0,x0,y1,colour); // Left
    drawLine(x1,y0,x1,y1,colour); // Right
}
References drawLine().
drawLine()
void GraphicsContext::drawLine (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a line on the screen.
Parameters
x0 The x coordinate of the m_first_memory_chunk point
y0 The y coordinate of the m_first_memory_chunk point
x1 The x coordinate of the final point
y1 The y coordinate of the final point
colour The colour of the line
Definition at line 480 of file graphicsContext.cpp.
                                                                                              {
    // Store the minimum and maximum y values
    bool y_0_is_smaller = y0 < y1;
    int32_t y_min = y_0_is_smaller ? y0 : y1;
    int32_t y_max = y_0_is_smaller ? y1 : y0;
    //Reverse the points to draw from left to right
    if(x1 < x0){
        drawLine(x1,y1,x0,y0,colour);
        return;
    }
    // Vertical line
    if(x1 == x0)
    {
        // Force the line to be within the screen
        if(y_min < 0) y_min = 0;
        if((uint32_t)y_max >= m_height)
          y_max = m_height - 1;
        // Mirror the Y axis as directly calling put_pixel will not do this
        if(mirror_y_axis)
        {
            int32_t temp = y_max;
            y_max = m_height - y_min - 1;
            y_min = m_height - temp - 1;
        }
        // Check that the line is within the screen
        if (0 > x0 || (uint32_t) x0 >= m_width) {
            return;
        }
        // Draw the line
        for(int32_t y = y_min; y <= y_max; ++y)
            putPixel(x0, y, colour);
        return;
    }
    // Horizontal line
    if(y1 == y0)
    {
        // Ensure the line is within the screen
        if(x0 < 0) x0 = 0;
        if((uint32_t)x1 >= m_width) x1 = m_width -1;
        // Mirror the Y axis as directly calling put_pixel will not do this
        if(mirror_y_axis)
            y0 = m_height -y0-1;
        // Check that the line is within the screen
        if (0 > y0 || (uint32_t) y0 >= m_height)
            return;
        // Draw the line
        for(int32_t x = x0; x <= x1; ++x)
            putPixel(x,y0,colour);
    }
    // TODO: Slope once SSE is implemented
    return;
    // If the line is not horizontal or vertical then it must be a diagonal line
    // Find the slope of the line
    float slope = ((float)(y1-y0))/(x1-x0);
    // A slope that is more horizontal should be drawn by incrementing x
    if(-1 <= slope && slope <= 1)
    {
        float y = y0;
        for(int32_t x = x0; x <= x1; x++, y+=slope)
            putPixel(x, (int32_t)y, colour);
    }
    // A slope that is more vertical should be drawn by incrementing y
    else
    {
        // Invert the slope
        slope = 1.0f/slope;
        float x = x0;
        for(int32_t y = y_min; y <= y_max; x+=slope, y++)
            putPixel((int32_t)x, y, colour);
    }
}
References m_height, m_width, mirror_y_axis, putPixel(), MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
Referenced by draw_line(), and draw_rectangle().
fill_circle()
void GraphicsContext::fill_circle (int32_t x0, int32_t y0, int32_t radius, Colour colour)
Draws a circle on the screen, filled with a colour.
Parameters
x0 The x coordinate of the centre of the circle
y0 The y coordinate of the centre of the circle
radius The radius of the circle
colour The colour of the circle
Definition at line 721 of file graphicsContext.cpp.
                                                                                       {
    fillCircle(x0,y0,radius, colour_to_int(colour));
}
References colour_to_int(), and fillCircle().
fill_rectangle() [1/2]
void GraphicsContext::fill_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, Colour colour)
Draws a rectangle on the screen, filled with a colour.
Parameters
x0 The x coordinate of the top left corner
y0 The y coordinate of the top left corner
x1 The x coordinate of the bottom right corner
y1 The y coordinate of the bottom right corner
colour The colour of the rectangle
Definition at line 614 of file graphicsContext.cpp.
                                                                                                  {
  fill_rectangle(x0, y0, x1, y1, colour_to_int(colour));
}
References colour_to_int().
Referenced by MaxOS::gui::widgets::Text::draw(), MaxOS::gui::widgets::InputBox::draw(), MaxOS::gui::widgets::Button::draw(), MaxOS::gui::Desktop::draw_self(), MaxOS::gui::Window::draw_self(), and fill_rectangle().
fill_rectangle() [2/2]
void GraphicsContext::fill_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a rectangle on the screen, filled with a colour.
Parameters
x0 The x coordinate of the top left corner
y0 The y coordinate of the top left corner
x1 The x coordinate of the bottom right corner
y1 The y coordinate of the bottom right corner
colour The colour of the rectangle
Definition at line 627 of file graphicsContext.cpp.
                                                                                                    {
    // Draw from left to right
    if(y1 < y0){
        fill_rectangle(x1, y1, x0, y0, colour);
        return;
    }
    // Make sure the rectangle is within the height of the screen
    if(y0 < 0) y0 = 0;
    if((uint32_t)y1 > m_height) y1 = m_height;
    // Make sure the rectangle is within the width of the screen
    bool x_0_is_smaller = x0 < x1;
    int32_t x_min = x_0_is_smaller ? x0 : x1;
    int32_t x_max = x_0_is_smaller ? x1 : x0;
    if(x_min < 0) x_min = 0;
    if((uint32_t)x_max > m_width)
      x_max = m_width;
    // Mirror the Y axis as directly calling put_pixel will not do this
    if(mirror_y_axis)
    {
        uint32_t temp = y1;
        y1 = m_height - y0 - 1;
        y0 = m_height - temp - 1;
    }
    // Draw the rectangle
    for(int32_t y = y0; y < y1; ++y){
        for (int32_t x = x_min; x < x_max; ++x) {
            putPixel(x, y, colour);
        }
    }
}
References fill_rectangle(), m_height, m_width, mirror_y_axis, putPixel(), MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
fillCircle()
void GraphicsContext::fillCircle (int32_t x0, int32_t y0, int32_t radius, uint32_t colour)
Draws a circle on the screen, filled with a colour.
Parameters
x0 The x coordinate of the centre of the circle
y0 The y coordinate of the centre of the circle
radius The radius of the circle
colour The colour of the circle
Definition at line 734 of file graphicsContext.cpp.
                                                                                        {
        // Make sure the circle is with in the width and height of the screen
        if(x0 < 0) x0 = 0;
        if((uint32_t)x0 > m_width) x0 = m_width;
        if(y0 < 0) y0 = 0;
        if((uint32_t)y0 > m_height) y0 = m_height;
        // Mirror the Y axis as directly calling put_pixel will not do this
        if(mirror_y_axis)
            y0 = m_height -y0-1;
        // Draw the circle
        // Begin drawing at the left most point of the circle and draw a line to the right most point of the circle
        for(int32_t x = -radius; x <= radius; ++x){
            // Draw a line from the top most point of the circle to the bottom most point of the circle
            for(int32_t y = -radius; y <= radius; ++y){
                // Only draw the pixel if it is within the circle
                if(x*x + y*y <= radius*radius)
                    putPixel(x0+x,y0+y,colour);
            }
        }
}
References m_height, m_width, mirror_y_axis, putPixel(), MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
Referenced by fill_circle().
get_color_depth()
uint32_t GraphicsContext::get_color_depth ()
@breif Gets the current color depth (bits per pixel)
Returns
The color depth
Definition at line 372 of file graphicsContext.cpp.
                                          {
  return m_color_depth;
}
References m_color_depth.
Referenced by MaxOS::drivers::console::VESABootConsole::scroll_up().
get_framebuffer_address()
uint64_t * GraphicsContext::get_framebuffer_address ()
Definition at line 760 of file graphicsContext.cpp.
                                                   {
    return m_framebuffer_address;
}
References m_framebuffer_address.
Referenced by MaxOS::drivers::console::VESABootConsole::scroll_up().
get_height()
uint32_t GraphicsContext::get_height ()
Gets the height of the screen.
Returns
The height of the screen
Definition at line 364 of file graphicsContext.cpp.
                                     {
    return m_height;
}
References m_height.
Referenced by MaxOS::gui::Desktop::Desktop(), MaxOS::drivers::console::VESABootConsole::height(), and MaxOS::drivers::console::VESABootConsole::scroll_up().
get_pixel()
Colour GraphicsContext::get_pixel (int32_t x, int32_t y)
Gets the colour of a pixel, or returns black if the pixel is outside the screen.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
Returns
The colour of the pixel or black if the pixel is outside the screen
Definition at line 419 of file graphicsContext.cpp.
                                                      {
    // Check if the pixel is within the m_width of the screen
    if (0 > x || (uint32_t)x >= m_width) {
        return Colour(0,0,0);
    }
    // Check if the pixel is within the m_height of the screen
    if (0 > y || (uint32_t) y >= m_height) {
        return Colour(0,0,0);
    }
    // Get the pixel and convert it to a colour
    uint32_t translated_color = get_rendered_pixel(x, mirror_y_axis ? m_height - y - 1 : y);
    return int_to_colour(translated_color);
}
References get_rendered_pixel(), int_to_colour(), m_height, m_width, mirror_y_axis, MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
Referenced by invert_pixel().
get_rendered_pixel()
uint32_t GraphicsContext::get_rendered_pixel (uint32_t x, uint32_t y) [protected], [virtual]
Gets the colour of a pixel on the screen, automatically uses the correct color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
Returns
The colour of the pixel or white if the pixel is not supported
Definition at line 176 of file graphicsContext.cpp.
                                                                   {
    // Call the correct get_pixel function based on the color depth
    switch (m_color_depth) {
        case 8:
            return get_rendered_pixel_8_bit(x, y);
        case 16:
            return get_rendered_pixel_16_bit(x, y);
        case 24:
            return get_rendered_pixel_24_bit(x, y);
        case 32:
            return get_rendered_pixel_32_bit(x, y);
    }
    return colour_to_int(Colour(0xFF, 0xFF, 0xFF));
}
References colour_to_int(), get_rendered_pixel_16_bit(), get_rendered_pixel_24_bit(), get_rendered_pixel_32_bit(), get_rendered_pixel_8_bit(), m_color_depth, MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
Referenced by get_pixel().
get_rendered_pixel_16_bit()
uint16_t GraphicsContext::get_rendered_pixel_16_bit (uint32_t x, uint32_t y) [protected], [virtual]
Gets the colour of a pixel on the screen using the 16 bit color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
Returns
The 16Bit colour of the pixel
Definition at line 210 of file graphicsContext.cpp.
                                                                      {
    return 0;
}
Referenced by get_rendered_pixel().
get_rendered_pixel_24_bit()
uint32_t GraphicsContext::get_rendered_pixel_24_bit (uint32_t x, uint32_t y) [protected], [virtual]
Gets the colour of a pixel on the screen using the 24 bit color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
Returns
The 24Bit colour of the pixel
Definition at line 221 of file graphicsContext.cpp.
                                                                      {
    return 0;
}
Referenced by get_rendered_pixel().
get_rendered_pixel_32_bit()
uint32_t GraphicsContext::get_rendered_pixel_32_bit (uint32_t x, uint32_t y) [protected], [virtual]
Gets the colour of a pixel on the screen using the 32 bit color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
Returns
The 32Bit colour of the pixel
Reimplemented in MaxOS::drivers::video::VideoElectronicsStandardsAssociation.
Definition at line 232 of file graphicsContext.cpp.
                                                                      {
    return 0;
}
Referenced by get_rendered_pixel().
get_rendered_pixel_8_bit()
uint8_t GraphicsContext::get_rendered_pixel_8_bit (uint32_t x, uint32_t y) [protected], [virtual]
Gets the colour of a pixel on the screen using the 8 bit color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
Returns
The 8Bit colour of the pixel
Reimplemented in MaxOS::drivers::video::VideoGraphicsArray.
Definition at line 199 of file graphicsContext.cpp.
                                                                    {
    return 0;
}
Referenced by get_rendered_pixel().
get_width()
uint32_t GraphicsContext::get_width ()
Gets the width of the screen.
Returns
The width of the screen
Definition at line 355 of file graphicsContext.cpp.
                                    {
    return m_width;
}
References m_width.
Referenced by MaxOS::gui::Desktop::Desktop(), MaxOS::drivers::console::VESABootConsole::scroll_up(), and MaxOS::drivers::console::VESABootConsole::width().
int_to_colour()
Colour GraphicsContext::int_to_colour (uint32_t colour)
Converts an integer value to a colour based on the current color depth.
Parameters
colour The integer value to convert
Returns
The colour class of the integer value
Definition at line 300 of file graphicsContext.cpp.
                                                     {
    switch (m_color_depth) {
        case 8:
        {
            // Return the colour from the palette
            return m_colour_pallet[colour & 0xFF];
        }
        case 16:
        {
            // 16-Bit Colour: 5 bits for red, 6 bits for green, 5 bits for blue (RRRRR,GGGGGG,BBBBB)
            Colour result;
            result.red = (colour & 0xF800) >> 8;
            result.green = (colour & 0x07E0) >> 3;
            result.blue = (colour & 0x001F) << 3;
            return result;
        }
        case 24:
        {
            // 24-Bit Colour: 8 bits for red, 8 bits for green, 8 bits for blue (RRRRRRRR,GGGGGGGG,BBBBBBBB)
            Colour result;
            result.red = (colour & 0xFF0000) >> 16;
            result.green = (colour & 0x00FF00) >> 8;
            result.blue = (colour & 0x0000FF);
            return result;
        }
        default:
        case 32:
        {
            Colour result;
            uint32_t hex_value = colour;
            result.red = (hex_value >> 16) & 0xFF;
            result.green = (hex_value >> 8) & 0xFF;
            result.blue = hex_value & 0xFF;
            result.alpha = (hex_value >> 24) & 0xFF;
            return result;
        }
    }
}
References MaxOS::common::Colour::alpha, MaxOS::common::Colour::blue, MaxOS::common::Colour::green, m_color_depth, m_colour_pallet, and MaxOS::common::Colour::red.
Referenced by get_pixel().
invert_pixel()
void GraphicsContext::invert_pixel (int32_t x, int32_t y)
Inverts a pixel.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
Definition at line 444 of file graphicsContext.cpp.
                                                       {
    // Get the pixel
    Colour colour = get_pixel(x, y);
    // Invert the pixel
    colour.red = 255 - colour.red;
    colour.green = 255 - colour.green;
    colour.blue = 255 - colour.blue;
    // Render the pixel
    put_pixel(x, y, colour);
}
References MaxOS::common::Colour::blue, get_pixel(), MaxOS::common::Colour::green, put_pixel(), MaxOS::common::Colour::red, MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
Referenced by MaxOS::gui::Desktop::invert_mouse_cursor().
put_pixel()
void GraphicsContext::put_pixel (int32_t x, int32_t y, Colour colour)
Renders a pixel to the screen (automatically converts the colour to an integer)
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
colour The colour of the pixel
Definition at line 383 of file graphicsContext.cpp.
                                                                   {
    // Convert the colour to an integer and then print it
    putPixel(x,y, colour_to_int(colour));
}
References colour_to_int(), putPixel(), MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
Referenced by invert_pixel().
putPixel()
void GraphicsContext::putPixel (int32_t x, int32_t y, int32_t colour)
Renders a pixel to the screen (automatically converts the colour to an integer), will not render the pixel if it is outside the screen.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
colour The colour of the pixel
Definition at line 396 of file graphicsContext.cpp.
                                                                   {
    if (0 > x || (uint32_t)x >= m_width) {
        return;
    }
    // Check if the pixel is within the m_height of the screen
    if (0 > y || (uint32_t) y >= m_height) {
        return;
    }
    // Render the pixel
    render_pixel(x, mirror_y_axis ? m_height - y - 1 : y, colour);
}
References m_height, m_width, mirror_y_axis, render_pixel(), MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
Referenced by draw_circle(), drawLine(), fill_rectangle(), fillCircle(), and put_pixel().
render_pixel()
void GraphicsContext::render_pixel (uint32_t x, uint32_t y, uint32_t colour) [protected], [virtual]
Renders a pixel to the screen based on the current color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
colour The colour of the pixel
Definition at line 104 of file graphicsContext.cpp.
                                                                          {
    // Call the correct put_pixel function based on the color depth
    switch (m_color_depth) {
        case 8:
          render_pixel_8_bit(x, y, colour);
            break;
        case 16:
          render_pixel_16_bit(x, y, colour);
            break;
        case 24:
          render_pixel_24_bit(x, y, colour);
            break;
        case 32:
          render_pixel_32_bit(x, y, colour);
            break;
    }
}
References m_color_depth, render_pixel_16_bit(), render_pixel_24_bit(), render_pixel_32_bit(), render_pixel_8_bit(), MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
Referenced by putPixel().
render_pixel_16_bit()
void GraphicsContext::render_pixel_16_bit (uint32_t x, uint32_t y, uint16_t colour) [protected], [virtual]
Renders a pixel to the screen using the 16 bit color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
colour The 16Bit colour of the pixel
Definition at line 143 of file graphicsContext.cpp.
                                                                      {
}
Referenced by render_pixel().
render_pixel_24_bit()
void GraphicsContext::render_pixel_24_bit (uint32_t x, uint32_t y, uint32_t colour) [protected], [virtual]
Renders a pixel to the screen using the 24 bit color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
colour The 24Bit colour of the pixel
Definition at line 154 of file graphicsContext.cpp.
                                                                      {
}
Referenced by render_pixel().
render_pixel_32_bit()
void GraphicsContext::render_pixel_32_bit (uint32_t x, uint32_t y, uint32_t colour) [protected], [virtual]
Renders a pixel to the screen using the 32 bit color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
colour The 32Bit colour of the pixel
Reimplemented in MaxOS::drivers::video::VideoElectronicsStandardsAssociation.
Definition at line 165 of file graphicsContext.cpp.
                                                                      {
}
Referenced by render_pixel().
render_pixel_8_bit()
void GraphicsContext::render_pixel_8_bit (uint32_t x, uint32_t y, uint8_t colour) [protected], [virtual]
Renders a pixel to the screen using the 8 bit color depth.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
colour The 8Bit colour of the pixel
Reimplemented in MaxOS::drivers::video::VideoGraphicsArray.
Definition at line 132 of file graphicsContext.cpp.
                                                                    {
}
Referenced by render_pixel().
Member Data Documentation
m_color_depth
uint32_t MaxOS::common::GraphicsContext::m_color_depth { 0 } [protected]
Definition at line 26 of file graphicsContext.h.
Referenced by colour_to_int(), get_color_depth(), get_rendered_pixel(), int_to_colour(), render_pixel(), and MaxOS::drivers::video::VideoDriver::set_mode().
m_colour_pallet
Colour MaxOS::common::GraphicsContext::m_colour_pallet[256] [protected]
Definition at line 28 of file graphicsContext.h.
Referenced by colour_to_int(), GraphicsContext(), and int_to_colour().
m_framebuffer_address
uint64_t* MaxOS::common::GraphicsContext::m_framebuffer_address { nullptr } [protected]
Definition at line 30 of file graphicsContext.h.
Referenced by get_framebuffer_address(), MaxOS::drivers::video::VideoElectronicsStandardsAssociation::get_rendered_pixel_32_bit(), MaxOS::drivers::video::VideoElectronicsStandardsAssociation::render_pixel_32_bit(), and MaxOS::drivers::video::VideoElectronicsStandardsAssociation::VideoElectronicsStandardsAssociation().
m_height
uint32_t MaxOS::common::GraphicsContext::m_height { 0 } [protected]
Definition at line 25 of file graphicsContext.h.
Referenced by draw_circle(), drawLine(), fill_rectangle(), fillCircle(), get_height(), get_pixel(), putPixel(), and MaxOS::drivers::video::VideoDriver::set_mode().
m_width
uint32_t MaxOS::common::GraphicsContext::m_width { 0 } [protected]
Definition at line 24 of file graphicsContext.h.
Referenced by draw_circle(), drawLine(), fill_rectangle(), fillCircle(), get_pixel(), get_width(), putPixel(), and MaxOS::drivers::video::VideoDriver::set_mode().
mirror_y_axis
bool MaxOS::common::GraphicsContext::mirror_y_axis { false } [protected]
Definition at line 22 of file graphicsContext.h.
Referenced by draw_circle(), drawLine(), fill_rectangle(), fillCircle(), get_pixel(), and putPixel().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/common/graphicsContext.h
/home/runner/work/MaxOS/MaxOS/kernel/src/common/graphicsContext.cpp