MaxOS::drivers::console::ConsoleArea Class Reference
A console that is a subsection of another console, limited by a width and height.
#include <console.h>
Public Member Functions
ConsoleArea (Console *console, uint16_t left, uint16_t top, uint16_t width, uint16_t height)
Construct a new Console Area object.
ConsoleArea (Console *console, uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground, common::ConsoleColour background)
Construct a new Console Area object with specified foreground and background colors.
uint16_t width () override
Return the width of the console area.
uint16_t height () override
Return the height of the console area.
void put_character (uint16_t x, uint16_t y, char c) override
Place a character on the console area if the coordinates are within the area.
void set_foreground_color (uint16_t x, uint16_t y, common::ConsoleColour foreground) override
Change the foreground color of a character on the console area if the coordinates are within the area.
void set_background_color (uint16_t x, uint16_t y, common::ConsoleColour background) override
Change the background color of a character on the console area if the coordinates are within the area.
void scroll_up () override
Scroll the console area up by 1 line.
void scroll_up (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black, char fill=' ') override
Scroll an area of the console up by 1 line.
char get_character (uint16_t x, uint16_t y) override
Return the character at the given coordinates if the coordinates are within the console area.
common::ConsoleColour get_foreground_color (uint16_t x, uint16_t y) override
Return the foreground color of the character at the given coordinates if the coordinates are within the console area.
common::ConsoleColour get_background_color (uint16_t x, uint16_t y) override
Return the background color of the character at the given coordinates if the coordinates are within the console area.
Public Member Functions inherited from MaxOS::drivers::console::Console
virtual void put_character (uint16_t x, uint16_t y, char c, common::ConsoleColour foreground, common::ConsoleColour background)
Put a character on the console with a given foreground and background color.
virtual void put_string (uint16_t x, uint16_t y, string s, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black)
Put a string on the console.
virtual void clear ()
virtual void clear (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black, char fill=' ')
Clear an area of the console.
virtual void invert_colors (uint16_t x, uint16_t y)
Invert the colors of a character on the console.
Detailed Description
A console that is a subsection of another console, limited by a width and height.
Definition at line 59 of file console.h.
Constructor & Destructor Documentation
ConsoleArea() [1/2]
ConsoleArea::ConsoleArea (Console * console, uint16_t left, uint16_t top, uint16_t width, uint16_t height)
Construct a new Console Area object.
Parameters
console The console to create the area on
left How far from the left the area starts
top How far from the top the area starts
width The width of the area
height The height of the area
Definition at line 231 of file console.cpp.
        : m_console(console),
        m_left(left),
        m_top(top),
        m_width(width),
        m_height(height) {
}
ConsoleArea() [2/2]
ConsoleArea::ConsoleArea (Console * console, uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground, common::ConsoleColour background)
Construct a new Console Area object with specified foreground and background colors.
Parameters
console The console to create the area on
left How far from the left the area starts
top How far from the top the area starts
width The width of the area
height The height of the area
foreground The foreground color of the area
background The background color of the area
Definition at line 251 of file console.cpp.
        : m_console(console),
        m_left(left),
        m_top(top),
        m_width(width),
        m_height(height) {
    // Store the colours of the console
    for(uint16_t y = top; y < top + height; y++)
        for(uint16_t x = left; x < left + width; x++) {
            console->set_foreground_color(x, y, foreground);
            console->set_background_color(x, y, background);
        }
}
References height(), MaxOS::drivers::console::Console::set_background_color(), MaxOS::drivers::console::Console::set_foreground_color(), and width().
Member Function Documentation
get_background_color()
ConsoleColour ConsoleArea::get_background_color (uint16_t x, uint16_t y) [override], [virtual]
Return the background color of the character at the given coordinates if the coordinates are within the console area.
Parameters
x The x coordinate of the character
y The y coordinate of the character
Returns
The background color of the character at the given coordinates, if the coordinates are within the console area otherwise ConsoleColour::Black
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 383 of file console.cpp.
                                                                      {
    // Make sure the coordinates are within the console area
    if(x >= m_width || y >= m_height)
        return ConsoleColour::Black;
    // Return the background color of the character at the given coordinates
    return m_console->get_background_color(m_left + x, m_top + y);
}
References MaxOS::drivers::console::Console::get_background_color().
get_character()
char ConsoleArea::get_character (uint16_t x, uint16_t y) [override], [virtual]
Return the character at the given coordinates if the coordinates are within the console area.
Parameters
x The x coordinate of the character
y The y coordinate of the character
Returns
The character at the given coordinates, if the coordinates are within the console area otherwise " "
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 348 of file console.cpp.
                                                      {
    // Make sure the coordinates are within the console area
    if(x >= m_width || y >= m_height)
        return ' ';
    // Return the character at the given coordinates
    return m_console->get_character(m_left + x, m_top + y);
}
References MaxOS::drivers::console::Console::get_character().
get_foreground_color()
ConsoleColour ConsoleArea::get_foreground_color (uint16_t x, uint16_t y) [override], [virtual]
Return the foreground color of the character at the given coordinates if the coordinates are within the console area.
Parameters
x The x coordinate of the character
y The y coordinate of the character
Returns
The foreground color of the character at the given coordinates, if the coordinates are within the console area otherwise ConsoleColour::LightGrey
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 365 of file console.cpp.
                                                                      {
    // Make sure the coordinates are within the console area
    if(x >= m_width || y >= m_height)
        return ConsoleColour::LightGrey;
    // Return the foreground color of the character at the given coordinates
    return m_console->get_foreground_color(m_left + x, m_top + y);
}
References MaxOS::drivers::console::Console::get_foreground_color().
height()
uint16_t ConsoleArea::height () [override], [virtual]
Return the height of the console area.
Returns
The height of the console area
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 283 of file console.cpp.
                             {
    return m_height;
}
Referenced by ConsoleArea(), and scroll_up().
put_character()
void ConsoleArea::put_character (uint16_t x, uint16_t y, char c) [override], [virtual]
Place a character on the console area if the coordinates are within the area.
Parameters
x The x coordinate of the character
y The y coordinate of the character
c The character to put on the console
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 294 of file console.cpp.
                                                              {
    // Check bounds
    if(x >= m_width || y >= m_height)
        return;
    // Write to the console
    m_console->put_character(m_left + x, m_top + y, c);
}
References MaxOS::drivers::console::Console::put_character().
scroll_up() [1/2]
void ConsoleArea::scroll_up () [override], [virtual]
Scroll the console area up by 1 line.
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 396 of file console.cpp.
                            {
    m_console->scroll_up(m_left, m_top, m_width, m_height);
}
References MaxOS::drivers::console::Console::scroll_up().
scroll_up() [2/2]
void ConsoleArea::scroll_up (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground = common::ConsoleColour::LightGrey, common::ConsoleColour background = common::ConsoleColour::Black, char fill = ' ') [override], [virtual]
Scroll an area of the console up by 1 line.
Parameters
left The left coordinate of the area to scroll
top The top coordinate of the area to scroll
width The m_width of the area to scroll
height The m_height of the area to scroll
foreground The foreground color of the new line
background The background color of the new line
fill The character to fill the new line with
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 412 of file console.cpp.
                                                                       {
    m_console->scroll_up(m_left + left, m_top + top, width, height, foreground, background, fill);
}
References height(), MaxOS::drivers::console::Console::scroll_up(), and width().
set_background_color()
void ConsoleArea::set_background_color (uint16_t x, uint16_t y, common::ConsoleColour background) [override], [virtual]
Change the background color of a character on the console area if the coordinates are within the area.
Parameters
x The x coordinate of the character
y The y coordinate of the character
background The background color of the character
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 330 of file console.cpp.
                                                                                       {
    // Make sure the coordinates are within the console area
    if(x >= m_width || y >= m_height)
        return;
    // Set the background color of the character
    m_console->set_background_color(m_left + x, m_top + y, background);
}
References MaxOS::drivers::console::Console::set_background_color().
set_foreground_color()
void ConsoleArea::set_foreground_color (uint16_t x, uint16_t y, common::ConsoleColour foreground) [override], [virtual]
Change the foreground color of a character on the console area if the coordinates are within the area.
Parameters
x The x coordinate of the character
y The y coordinate of the character
foreground The foreground color of the character
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 312 of file console.cpp.
                                                                                       {
    // Make sure the coordinates are within the console area
    if(x >= m_width || y >= m_height)
        return;
    // Set the foreground color of the character
    m_console->set_foreground_color(m_left + x, m_top + y, foreground);
}
References MaxOS::drivers::console::Console::set_foreground_color().
width()
uint16_t ConsoleArea::width () [override], [virtual]
Return the width of the console area.
Returns
The width of the console area
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 274 of file console.cpp.
                            {
    return m_width;
}
Referenced by ConsoleArea(), and scroll_up().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/console.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/console/console.cpp