MaxOS::filesystem::format::Fat32Volume Class Reference
Handles the FAT table that stores the information about the files on the disk and operations on the disk.
#include <fat32.h>
Public Member Functions
Fat32Volume (drivers::disk::Disk *disk, lba_t partition_offset)
Construct a new Fat32 Volume object.
uint32_t next_cluster (uint32_t cluster) const
Take the cluster and gets the next cluster in the chain.
uint32_t set_next_cluster (uint32_t cluster, uint32_t next_cluster) const
Sets the next cluster in the chain (where the base cluster should point)
uint32_t find_free_cluster () const
Searches the fat table for a free cluster starting from the first free cluster in the fsinfo, will then wrap around.
uint32_t allocate_cluster (uint32_t cluster)
Allocate a cluster in the FAT table.
uint32_t allocate_cluster (uint32_t cluster, size_t amount)
Allocate a number of clusters in the FAT table, updates the fsinfo and the chain.
void free_cluster (uint32_t cluster)
Free a cluster in the FAT table.
void free_cluster (uint32_t cluster, size_t amount)
Free a number of clusters in the FAT table.
Public Attributes
bpb32_t bpb = { }
The BIOS Parameter Block for the FAT32 volume.
fs_info_t fsinfo = { }
The FSInfo structure for the FAT32 volume.
size_t fat_total_clusters
How many clusters are in the FAT table.
lba_t fat_lba
The starting LBA of the FAT table.
lba_t fat_info_lba
The LBA of the FSInfo structure.
lba_t fat_copies
How many FAT tables are present.
lba_t data_lba
The starting LBA of the data region.
lba_t root_lba
The starting LBA of the root directory.
drivers::disk::Disk * disk
The disk that this volume is on.
Detailed Description
Handles the FAT table that stores the information about the files on the disk and operations on the disk.
Definition at line 171 of file fat32.h.
Constructor & Destructor Documentation
Fat32Volume()
Fat32Volume::Fat32Volume (drivers::disk::Disk * disk, lba_t partition_offset)
Construct a new Fat32 Volume object.
Parameters
disk The disk to read from
partition_offset The offset of the partition on the disk
Definition at line 26 of file fat32.cpp.
        : disk(disk) {
    // Read the BIOS parameter block
    buffer_t bpb_buffer(&bpb, sizeof(bpb32_t));
    disk->read(partition_offset, &bpb_buffer);
    // Parse the FAT info
    uint32_t total_data_sectors =
            bpb.total_sectors_32 - (bpb.reserved_sectors + (bpb.table_copies * bpb.table_size_32));
    fat_total_clusters = total_data_sectors / bpb.sectors_per_cluster;
    fat_lba = partition_offset + bpb.reserved_sectors;
    fat_copies = bpb.table_copies;
    fat_info_lba = partition_offset + bpb.fat_info;
    data_lba = fat_lba + (bpb.table_copies * bpb.table_size_32);
    root_lba = data_lba + bpb.sectors_per_cluster * (bpb.root_cluster - 2);
    // Read the fs info
    buffer_t fs_buffer(&fsinfo, sizeof(fs_info_t));
    disk->read(fat_info_lba, &fs_buffer);
    // Validate the fat information
    if(fsinfo.lead_signature != 0x41615252 || fsinfo.structure_signature != 0x61417272 ||
       fsinfo.trail_signature != 0xAA550000) {
        Logger::ERROR() << "Invalid FAT32 filesystem information TODO: Handle this\n";
        return;
    }
}
References bpb, data_lba, disk, MaxOS::Logger::ERROR(), fat_copies, fat_info_lba, fat_lba, fat_total_clusters, fsinfo, MaxOS::drivers::disk::Disk::read(), and root_lba.
Member Function Documentation
allocate_cluster() [1/2]
uint32_t Fat32Volume::allocate_cluster (uint32_t cluster)
Allocate a cluster in the FAT table.
Parameters
cluster The base cluster to start from or 0 if this is a new chain
Returns
The next cluster in the chain
Definition at line 141 of file fat32.cpp.
                                                       {
    // Allocate 1 cluster
    return allocate_cluster(cluster, 1);
}
References allocate_cluster().
Referenced by allocate_cluster(), and MaxOS::filesystem::format::Fat32File::write().
allocate_cluster() [2/2]
uint32_t Fat32Volume::allocate_cluster (uint32_t cluster, size_t amount)
Allocate a number of clusters in the FAT table, updates the fsinfo and the chain.
Parameters
cluster The base cluster to start from or 0 if this is a new chain
amount The number of clusters to allocate
Returns
The next cluster in the chain
Definition at line 154 of file fat32.cpp.
                                                                      {
    // Make sure within bounds
    if(cluster > fat_total_clusters || cluster + amount > fat_total_clusters)
        return 0;
    // Go through allocating the clusters
    for(size_t i = 0; i < amount; i++) {
        uint32_t next_cluster = find_free_cluster();
        // Update the fsinfo
        fsinfo.next_free_cluster = next_cluster + 1;
        fsinfo.free_cluster_count -= 1;
        // If there is an existing chain it needs to be updated
        if(cluster != 0)
            set_next_cluster(cluster, next_cluster);
        cluster = next_cluster;
    }
    // Once all the updates are done flush the changes to the disk
    buffer_t fs_info_buffer(&fsinfo, sizeof(fs_info_t));
    disk->write(fat_info_lba, &fs_info_buffer);
    // Finish the chain
    set_next_cluster(cluster, (uint32_t) ClusterState::END_OF_CHAIN);
    return cluster;
}
References disk, fat_info_lba, fat_total_clusters, find_free_cluster(), fsinfo, next_cluster(), set_next_cluster(), and MaxOS::drivers::disk::Disk::write().
find_free_cluster()
uint32_t Fat32Volume::find_free_cluster () const
Searches the fat table for a free cluster starting from the first free cluster in the fsinfo, will then wrap around.
Returns
The first free cluster in the FAT table
Definition at line 119 of file fat32.cpp.
                                              {
    // Get the first free cluster
    for(uint32_t start = fsinfo.next_free_cluster; start < fat_total_clusters + 1; start++)
        if(next_cluster(start) == 0)
            return start;
    // Check any clusters before the first free cluster
    for(uint32_t start = 2; start < fsinfo.next_free_cluster; start++)
        if(next_cluster(start) == 0)
            return start;
    ASSERT(false, "No free clusters found in the FAT table");
    return 0;
}
References ASSERT, fat_total_clusters, fsinfo, and next_cluster().
Referenced by allocate_cluster().
free_cluster() [1/2]
void Fat32Volume::free_cluster (uint32_t cluster)
Free a cluster in the FAT table.
Parameters
cluster The base cluster to start from
Definition at line 189 of file fat32.cpp.
                                            {
    // Free 1 cluster
    free_cluster(cluster, 1);
}
References free_cluster().
Referenced by free_cluster().
free_cluster() [2/2]
void Fat32Volume::free_cluster (uint32_t cluster, size_t amount)
Free a number of clusters in the FAT table.
Parameters
cluster The base cluster to start from
amount The number of clusters to free
Definition at line 202 of file fat32.cpp.
                                                              {
    // Make sure within bounds
    if(cluster < 2 || cluster > fat_total_clusters || cluster + amount > fat_total_clusters)
        return;
    // Go through freeing the clusters
    for(size_t i = 0; i < amount; i++) {
        // Find the next cluster before it is removed from the chain
        uint32_t next_in_chain = next_cluster(cluster);
        // Update the fsinfo
        fsinfo.next_free_cluster = cluster;
        fsinfo.free_cluster_count += 1;
        // Update the chain
        set_next_cluster(cluster, (lba_t) ClusterState::FREE);
        cluster = next_in_chain;
    }
    // Save the fsinfo
    buffer_t fs_info_buffer(&fsinfo, sizeof(fs_info_t));
    disk->write(fat_info_lba, &fs_info_buffer);
    // Mark the end of the chain
    set_next_cluster(cluster, (uint32_t) ClusterState::END_OF_CHAIN);
}
References disk, fat_info_lba, fat_total_clusters, fsinfo, next_cluster(), set_next_cluster(), and MaxOS::drivers::disk::Disk::write().
next_cluster()
lba_t Fat32Volume::next_cluster (uint32_t cluster) const
Take the cluster and gets the next cluster in the chain.
Parameters
cluster The base cluster to start from
Returns
The next cluster in the chain
Todo
Todo The auto entry = uint32_t* '&' is weird, fix it
Definition at line 65 of file fat32.cpp.
                                                   {
    // Get the location in the FAT table
    lba_t offset = cluster * sizeof(uint32_t);
    lba_t sector = fat_lba + (offset / bpb.bytes_per_sector);
    uint32_t entry_index = offset % bpb.bytes_per_sector;
    // Read the FAT entry
    buffer_t fat(bpb.bytes_per_sector);
    disk->read(sector, &fat);
    // Get the next cluster info (mask the upper 4 bits)
    auto entry = (uint32_t*) (&(fat.raw()[entry_index]));
    return *entry & 0x0FFFFFFF;
}
References bpb, disk, fat_lba, and MaxOS::drivers::disk::Disk::read().
Referenced by allocate_cluster(), find_free_cluster(), free_cluster(), MaxOS::filesystem::format::Fat32File::read(), set_next_cluster(), MaxOS::filesystem::format::Fat32Directory::update_entry_on_disk(), and MaxOS::filesystem::format::Fat32File::write().
set_next_cluster()
uint32_t Fat32Volume::set_next_cluster (uint32_t cluster, uint32_t next_cluster) const
Sets the next cluster in the chain (where the base cluster should point)
Parameters
cluster The base cluster to start from
next_cluster The next cluster in the chain
Returns
The next cluster in the chain
Todo
Todo when in userspace: For performance cache fat entirely, cache file data, cache cluster chains
Definition at line 90 of file fat32.cpp.
                                                                                    {
    // Get the location in the FAT table
    lba_t offset = cluster * sizeof(uint32_t);
    for(uint32_t i = 0; i < fat_copies; ++i) {
        lba_t sector = (fat_lba + i * bpb.table_size_32) + (offset / bpb.bytes_per_sector);
        uint32_t entry_index = offset % bpb.bytes_per_sector;
        // Read the FAT entry
        buffer_t fat(bpb.bytes_per_sector);
        disk->read(sector, &fat);
        // Set the next cluster info (mask the upper 4 bits)
        auto entry = (uint32_t*) (&(fat.raw()[entry_index]));
        *entry = next_cluster & 0x0FFFFFFF;
        disk->write(sector, &fat);
    }
    return next_cluster;
}
References bpb, disk, fat_copies, fat_lba, next_cluster(), MaxOS::drivers::disk::Disk::read(), and MaxOS::drivers::disk::Disk::write().
Referenced by allocate_cluster(), and free_cluster().
Member Data Documentation
bpb
bpb32_t MaxOS::filesystem::format::Fat32Volume::bpb = { }
The BIOS Parameter Block for the FAT32 volume.
Definition at line 176 of file fat32.h.
{ };
Referenced by MaxOS::filesystem::format::Fat32FileSystem::Fat32FileSystem(), Fat32Volume(), next_cluster(), MaxOS::filesystem::format::Fat32File::read(), set_next_cluster(), MaxOS::filesystem::format::Fat32Directory::update_entry_on_disk(), and MaxOS::filesystem::format::Fat32File::write().
data_lba
lba_t MaxOS::filesystem::format::Fat32Volume::data_lba
The starting LBA of the data region.
Definition at line 184 of file fat32.h.
Referenced by Fat32Volume(), MaxOS::filesystem::format::Fat32File::read(), MaxOS::filesystem::format::Fat32Directory::update_entry_on_disk(), and MaxOS::filesystem::format::Fat32File::write().
disk
drivers::disk::Disk* MaxOS::filesystem::format::Fat32Volume::disk
The disk that this volume is on.
Definition at line 187 of file fat32.h.
Referenced by allocate_cluster(), Fat32Volume(), free_cluster(), next_cluster(), MaxOS::filesystem::format::Fat32File::read(), set_next_cluster(), MaxOS::filesystem::format::Fat32Directory::update_entry_on_disk(), and MaxOS::filesystem::format::Fat32File::write().
fat_copies
lba_t MaxOS::filesystem::format::Fat32Volume::fat_copies
How many FAT tables are present.
Definition at line 182 of file fat32.h.
Referenced by Fat32Volume(), and set_next_cluster().
fat_info_lba
lba_t MaxOS::filesystem::format::Fat32Volume::fat_info_lba
The LBA of the FSInfo structure.
Definition at line 181 of file fat32.h.
Referenced by allocate_cluster(), Fat32Volume(), and free_cluster().
fat_lba
lba_t MaxOS::filesystem::format::Fat32Volume::fat_lba
The starting LBA of the FAT table.
Definition at line 180 of file fat32.h.
Referenced by Fat32Volume(), next_cluster(), and set_next_cluster().
fat_total_clusters
size_t MaxOS::filesystem::format::Fat32Volume::fat_total_clusters
How many clusters are in the FAT table.
Definition at line 179 of file fat32.h.
Referenced by allocate_cluster(), Fat32Volume(), find_free_cluster(), and free_cluster().
fsinfo
fs_info_t MaxOS::filesystem::format::Fat32Volume::fsinfo = { }
The FSInfo structure for the FAT32 volume.
Definition at line 177 of file fat32.h.
{ };
Referenced by allocate_cluster(), Fat32Volume(), find_free_cluster(), and free_cluster().
root_lba
lba_t MaxOS::filesystem::format::Fat32Volume::root_lba
The starting LBA of the root directory.
Definition at line 185 of file fat32.h.
Referenced by Fat32Volume().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/format/fat32.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/format/fat32.cpp