MaxOS::processes::Process Class Reference
A process that can be scheduled by the Scheduler, wraps & manages threads as well as its own address space and resources.
#include <process.h>
Public Member Functions
Process (const string &name, bool is_kernel=false)
Base Constructor for the Process.
Process (const string &name, void(*_entry_point)(void *), void *args, int arg_amount, bool is_kernel=false)
Constructor for the Process class (from a function)
Process (const string &name, void *args, int arg_amount, ELF64 *elf, bool is_kernel=false)
Constructor for the Process class (from an elf, will free the elf memory after loading)
~Process ()
Destructor for the Process class.
common::Vector< Thread * > threads ()
Gets the threads of the process.
void add_thread (Thread *thread)
Adds a thread to the process.
void remove_thread (uint64_t tid)
Remove a thread by its tid (NOTE: this will not remove it from the scheduler)
void set_pid (uint64_t pid)
Sets the pid of the process once added to the queue.
uint64_t pid () const
Gets the pid of the process.
uint64_t total_ticks ()
Gets the total ticks of the threads in the process (not this does not include any past killed threads)
Public Attributes
bool is_kernel
Whether this process is a kernel process.
string name
The name of the process.
string working_directory = "/"
The working directory of the process.
memory::MemoryManager * memory_manager = nullptr
The manager for memory used by this process.
ResourceManager resource_manager
The manger for resources used by this process.
Detailed Description
A process that can be scheduled by the Scheduler, wraps & manages threads as well as its own address space and resources.
Definition at line 85 of file process.h.
Constructor & Destructor Documentation
Process() [1/3]
Process::Process (const string & p_name, bool is_kernel = false) [explicit]
Base Constructor for the Process.
Parameters
p_name The name of the process
is_kernel If the process is a kernel process
Definition at line 181 of file process.cpp.
: is_kernel(is_kernel),
  name(p_name)
{
    // If it is a kernel process then don't need a new memory manager
    memory_manager = is_kernel ? MemoryManager::s_kernel_memory_manager : new MemoryManager();
}
References is_kernel, memory_manager, and MaxOS::memory::MemoryManager::s_kernel_memory_manager.
Process() [2/3]
Process::Process (const string & p_name, void(*)(void *) _entry_point, void * args, int arg_amount, bool is_kernel = false)
Constructor for the Process class (from a function)
Parameters
p_name The name of the process
_entry_point The entry point of the process
args The arguments to pass to the process
arg_amount The amount of arguments
is_kernel If the process is a kernel process
Definition at line 198 of file process.cpp.
: Process(p_name, is_kernel)
{
    // Create the main thread
    auto* main_thread = new Thread(_entry_point, args, arg_amount, this);
    // Add the thread
    add_thread(main_thread);
}
References add_thread().
Process() [3/3]
Process::Process (const string & p_name, void * args, int arg_amount, ELF64 * elf, bool is_kernel = false)
Constructor for the Process class (from an elf, will free the elf memory after loading)
Parameters
p_name The name of the process
args The arguments to pass to the process
arg_amount The amount of arguments
elf The elf file to load the process from
is_kernel If the process is a kernel process
Definition at line 218 of file process.cpp.
: Process(p_name, is_kernel)
{
    // Get the entry point
    elf->load();
    auto* entry_point = (void (*)(void*)) elf->header()->entry;
    // Create the main thread
    auto* main_thread = new Thread(entry_point, args, arg_amount, this);
    add_thread(main_thread);
}
References add_thread().
~Process()
Process::~Process ()
Destructor for the Process class.
Definition at line 235 of file process.cpp.
                  {
    uint64_t pages = PhysicalMemoryManager::s_current_manager->memory_used();
    // Free the threads
    for (auto thread: m_threads)
        delete thread;
    // Free the memory manager (only if it was created)
    if (!is_kernel)
        delete memory_manager;
    // Log the cleanup
    Logger::DEBUG() << "Process " << name.c_str() << " cleaned up, memory before: " << pages << " bytes, after cleanup: " << PhysicalMemoryManager::s_current_manager->memory_used() << " bytes\n";
}
References MaxOS::Logger::DEBUG(), is_kernel, memory_manager, name, and MaxOS::memory::PhysicalMemoryManager::s_current_manager.
Member Function Documentation
add_thread()
void Process::add_thread (Thread * thread)
Adds a thread to the process.
Parameters
thread The thread to add
Definition at line 256 of file process.cpp.
                                       {
    m_lock.lock();
    // Store the thread
    m_threads.push_back(thread);
    thread->parent_pid = m_pid;
    m_lock.unlock();
}
References MaxOS::common::Spinlock::lock(), and MaxOS::common::Spinlock::unlock().
Referenced by Process(), and Process().
pid()
uint64_t Process::pid () const
Gets the pid of the process.
Returns
The pid of the process
Definition at line 326 of file process.cpp.
                            {
    return m_pid;
}
Referenced by MaxOS::processes::Scheduler::current_process(), MaxOS::processes::GlobalScheduler::force_remove_process(), MaxOS::processes::Scheduler::get_process(), MaxOS::processes::GlobalScheduler::remove_process(), and set_pid().
remove_thread()
void Process::remove_thread (uint64_t tid)
Remove a thread by its tid (NOTE: this will not remove it from the scheduler)
Parameters
tid
Definition at line 272 of file process.cpp.
                                        {
    // Find the thread
    for (uint32_t i = 0; i < m_threads.size(); i++) {
        // Thread is not what is being removed
        if (m_threads[i]->tid != tid)
            continue;
        // Delete the thread
        Thread* thread = m_threads[i];
        delete thread;
        // Remove the thread from the list
        m_threads.erase(m_threads.begin() + i);
        return;
    }
}
Referenced by MaxOS::processes::Scheduler::force_remove_process(), and MaxOS::processes::Scheduler::schedule_next().
set_pid()
void Process::set_pid (uint64_t pid)
Sets the pid of the process once added to the queue.
Parameters
pid
Definition at line 296 of file process.cpp.
                                  {
    // Check if the pid is already set
    if (m_pid != 0)
        return;
    // Set the pid
    m_pid = pid;
    // Assign the pid to the threads
    for (auto thread: m_threads)
        thread->parent_pid = pid;
}
References pid().
Referenced by MaxOS::processes::Scheduler::add_process().
threads()
Vector< Thread * > Process::threads ()
Gets the threads of the process.
Returns
The threads of the process
Definition at line 316 of file process.cpp.
                                 {
    return m_threads;
}
Referenced by MaxOS::processes::Scheduler::add_process(), MaxOS::processes::Scheduler::force_remove_process(), MaxOS::processes::Scheduler::remove_process(), and MaxOS::processes::Scheduler::schedule_next().
total_ticks()
uint64_t Process::total_ticks ()
Gets the total ticks of the threads in the process (not this does not include any past killed threads)
Returns
The total ticks of the threads in the process
Definition at line 336 of file process.cpp.
                              {
    uint64_t total_ticks = 0;
    for (auto thread: m_threads)
        total_ticks += thread->ticks;
    return total_ticks;
}
References total_ticks().
Referenced by total_ticks().
Member Data Documentation
is_kernel
bool MaxOS::processes::Process::is_kernel
Whether this process is a kernel process.
Definition at line 107 of file process.h.
Referenced by Process(), and ~Process().
memory_manager
memory::MemoryManager* MaxOS::processes::Process::memory_manager = nullptr
The manager for memory used by this process.
Definition at line 112 of file process.h.
Referenced by Process(), and ~Process().
name
string MaxOS::processes::Process::name
The name of the process.
Definition at line 109 of file process.h.
Referenced by MaxOS::processes::GlobalScheduler::add_process(), and ~Process().
resource_manager
ResourceManager MaxOS::processes::Process::resource_manager
The manger for resources used by this process.
Definition at line 113 of file process.h.
working_directory
string MaxOS::processes::Process::working_directory = "/"
The working directory of the process.
Definition at line 110 of file process.h.
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/processes/process.h
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/process.cpp