MaxOS::filesystem::FileResource Class Reference
A wrapper for a File which exposes File operations as Resource operations.
#include <vfsresource.h>
Public Member Functions
FileResource (const string &name, size_t flags, processes::resource_type_t type)
Construct a new File Resource object.
int read (void *buffer, size_t size, size_t flags) final
read from a file resource
int write (const void *buffer, size_t size, size_t flags) final
write to a file resource
Public Member Functions inherited from MaxOS::processes::Resource
Resource (const string &name, size_t flags, resource_type_t type)
Constructs a new Resource object.
string name ()
Gets the name of this resource.
resource_type_t type ()
Gets the type of this resource.
virtual void open (size_t flags)
Opens the resource.
virtual void close (size_t flags)
Closes the resource.
Public Attributes
File * file
The file that this resource handles & exposes.
Detailed Description
A wrapper for a File which exposes File operations as Resource operations.
See also
File
Resource
Todo
Todo Should this free the memory of the file when the resource is done??
Definition at line 32 of file vfsresource.h.
Constructor & Destructor Documentation
FileResource()
FileResource::FileResource (const string & name, size_t flags, processes::resource_type_t type)
Construct a new File Resource object.
Parameters
name The name of the resource
flags The flags for the resource when opened
type The type of the resource
Definition at line 24 of file vfsresource.cpp.
: Resource(name, flags, type),
  file(nullptr) // Initialised by the registry
{
}
Member Function Documentation
read()
int FileResource::read (void * buffer, size_t size, size_t flags) [final], [virtual]
read from a file resource
Parameters
buffer The buffer to read into
size The number of bytes to read
flags The flags to pass to the reading
Returns
The number of bytes successfully read or -1 on error
Reimplemented from MaxOS::processes::Resource.
Definition at line 41 of file vfsresource.cpp.
                                                              {
    // File not found
    if(!file)
        return -1;
    // Handle the operation
    switch ((FileFlags)flags) {
        case FileFlags::DEFAULT:{
            buffer_t file_buffer(buffer, size);
            file->read(&file_buffer, size);
            break;
        }
        case FileFlags::READ_SIZE:{
            return file->size();
        }
        case FileFlags::READ_OFFSET:{
            return file->position();
        }
        default:
            return -1;
    }
    return size;
}
References file, MaxOS::filesystem::File::position(), MaxOS::filesystem::File::read(), and MaxOS::filesystem::File::size().
write()
int FileResource::write (const void * buffer, size_t size, size_t flags) [final], [virtual]
write to a file resource
Parameters
buffer The buffer to write from
size The number of bytes to write
flags The flags to pass to the writing
Returns
The number of bytes successfully written or -1 on error
Reimplemented from MaxOS::processes::Resource.
Definition at line 80 of file vfsresource.cpp.
                                                                     {
    // File not found
    if(!file)
        return -1;
    // Handle the operation
    switch ((FileFlags)flags) {
        case FileFlags::DEFAULT:{
            buffer_t file_buffer((void*)buffer, size);
            file->write(&file_buffer, size);
            break;
        }
        case FileFlags::WRITE_SEEK_SET:
            file->seek(SeekType::SET, size);
            break;
        case FileFlags::WRITE_SEEK_CUR:
            file->seek(SeekType::CURRENT, size);
            break;
        case FileFlags::WRITE_SEEK_END:
            file->seek(SeekType::END, size);
            break;
        case FileFlags::WRITE_NAME:{
            // Open the parent
            Resource* parent = GlobalResourceRegistry::get_registry(resource_type_t::FILESYSTEM)->get_resource(Path::parent_directory(name()));
            auto parent_directory = ((DirectoryResource*)parent)->directory;
            // Rename
            string new_name = string((uint8_t*)buffer, size);
            parent_directory->rename_file(file, new_name);
            break;
        }
        default:
            return -1;
    }
    return size;
}
References file, MaxOS::processes::GlobalResourceRegistry::get_registry(), MaxOS::processes::Resource::name(), MaxOS::filesystem::Path::parent_directory(), MaxOS::filesystem::File::seek(), and MaxOS::filesystem::File::write().
Member Data Documentation
file
File* MaxOS::filesystem::FileResource::file
The file that this resource handles & exposes.
Definition at line 38 of file vfsresource.h.
Referenced by read(), and write().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/vfsresource.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/vfsresource.cpp