MaxOS::processes::BaseResourceRegistry Class Reference
Manages the creation, retention and destruction of resources of a certain type. Should be subclassed for each resource type.
#include <resource.h>
Public Member Functions
BaseResourceRegistry (resource_type_t type)
Constructs a new BaseResourceRegistry object and registers it globally.
~BaseResourceRegistry ()
Destructor for BaseResourceRegistry, removes it from the global list.
resource_type_t type ()
Gets the type of resources this registry handles.
virtual Resource * get_resource (const string &name)
Gets a resource from the registry by name.
virtual bool register_resource (Resource *resource)
Registers a resource in the registry.
virtual void close_resource (Resource *resource, size_t flags)
Close the resource provided, if it exists in this registry.
virtual Resource * create_resource (const string &name, size_t flags)
Try to create a new resource with the specified name, will fail if the name is in use.
Protected Attributes
common::Map< string, Resource * > m_resources
The map of resource names to resource instances.
common::Map< string, uint64_t > m_resource_uses
The map of resource names to how many processes are using them.
resource_type_t m_type
The resource type that this registry manages.
Detailed Description
Manages the creation, retention and destruction of resources of a certain type. Should be subclassed for each resource type.
Definition at line 54 of file resource.h.
Constructor & Destructor Documentation
BaseResourceRegistry()
BaseResourceRegistry::BaseResourceRegistry (resource_type_t type) [explicit]
Constructs a new BaseResourceRegistry object and registers it globally.
Parameters
type The type of resources this registry will handle
Definition at line 98 of file resource.cpp.
: m_type(type)
{
    GlobalResourceRegistry::add_registry(type, this);
}
References MaxOS::processes::GlobalResourceRegistry::add_registry(), and type().
~BaseResourceRegistry()
BaseResourceRegistry::~BaseResourceRegistry ()
Destructor for BaseResourceRegistry, removes it from the global list.
Definition at line 107 of file resource.cpp.
                                           {
    GlobalResourceRegistry::remove_registry(this);
}
References MaxOS::processes::GlobalResourceRegistry::remove_registry().
Member Function Documentation
close_resource()
void BaseResourceRegistry::close_resource (Resource * resource, size_t flags) [virtual]
Close the resource provided, if it exists in this registry.
Parameters
resource The resource to close
flags Optional flags to pass (unused by default but registry type specific)
Definition at line 164 of file resource.cpp.
                                                                          {
    // Resource isn't stored in this registry
    if(m_resources.find(resource->name()) == m_resources.end())
        return;
    m_resource_uses[resource->name()]--;
    // Don't close a resource that has more processes using it
    if(m_resource_uses[resource->name()])
        return;
    // Can safely close the resource
    resource->close(flags);
    m_resources.erase(resource->name());
    m_resource_uses.erase(resource->name());
    delete resource;
}
References MaxOS::processes::Resource::close(), MaxOS::common::Map< Key, Value >::erase(), m_resource_uses, m_resources, and MaxOS::processes::Resource::name().
create_resource()
Resource * BaseResourceRegistry::create_resource (const string & name, size_t flags) [virtual]
Try to create a new resource with the specified name, will fail if the name is in use.
Parameters
name The name of the resource to create
flags Optional flags to pass (unused by default but registry type specific)
Returns
The resource created or nullptr if failed to create the resource
Reimplemented in MaxOS::filesystem::VFSResourceRegistry, MaxOS::processes::ResourceRegistry< Type >, MaxOS::processes::ResourceRegistry< MaxOS::processes::SharedMemory >, and MaxOS::processes::ResourceRegistry< MaxOS::processes::SharedMessageEndpoint >.
Definition at line 190 of file resource.cpp.
                                                                                {
    return nullptr;
}
get_resource()
Resource * BaseResourceRegistry::get_resource (const string & name) [virtual]
Gets a resource from the registry by name.
Parameters
name The name of the resource to find
Returns
The resource or nullptr if the resource was not found
Reimplemented in MaxOS::filesystem::VFSResourceRegistry.
Definition at line 128 of file resource.cpp.
                                                               {
    // Resource isn't stored in this registry
    if(m_resources.find(name) == m_resources.end())
        return nullptr;
    // Increment the use count of the resource and return it
    m_resource_uses[name]++;
    return m_resources[name];
}
References m_resource_uses, and m_resources.
Referenced by MaxOS::filesystem::VFSResourceRegistry::create_resource(), and MaxOS::filesystem::VFSResourceRegistry::get_resource().
register_resource()
bool BaseResourceRegistry::register_resource (Resource * resource) [virtual]
Registers a resource in the registry.
Parameters
resource The resource to store
Returns
True if the register was successful, false if not
Definition at line 146 of file resource.cpp.
                                                               {
    // Resource name is already stored in this registry
    if(m_resources.find(resource->name()) != m_resources.end())
        return false;
    m_resources.insert(resource->name(), resource);
    m_resource_uses.insert(resource->name(), 0);
    return true;
}
References MaxOS::common::Map< Key, Value >::insert(), m_resource_uses, m_resources, and MaxOS::processes::Resource::name().
Referenced by MaxOS::processes::ResourceRegistry< Type >::create_resource().
type()
resource_type_t BaseResourceRegistry::type ()
Gets the type of resources this registry handles.
Returns
The type
Definition at line 117 of file resource.cpp.
                                           {
    return m_type;
}
References m_type.
Referenced by BaseResourceRegistry(), MaxOS::processes::ResourceRegistry< Type >::create_resource(), and MaxOS::processes::GlobalResourceRegistry::remove_registry().
Member Data Documentation
m_resource_uses
common::Map<string, uint64_t> MaxOS::processes::BaseResourceRegistry::m_resource_uses [protected]
The map of resource names to how many processes are using them.
Definition at line 58 of file resource.h.
Referenced by close_resource(), get_resource(), and register_resource().
m_resources
common::Map<string, Resource*> MaxOS::processes::BaseResourceRegistry::m_resources [protected]
The map of resource names to resource instances.
Definition at line 57 of file resource.h.
Referenced by close_resource(), get_resource(), and register_resource().
m_type
resource_type_t MaxOS::processes::BaseResourceRegistry::m_type [protected]
The resource type that this registry manages.
Definition at line 60 of file resource.h.
Referenced by type().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/processes/resource.h
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/resource.cpp