MaxOS::filesystem::Path Class Reference
Handles file & directory paths.
#include <path.h>
Static Public Member Functions
static bool valid (const string &path)
Check if a path is valid.
static bool is_file (const string &path)
Check if a path is a file.
static string file_name (const string &path)
Get the file name component of a path if it exists or an empty string.
static string file_extension (const string &path)
Try to get the file extension from a path (assumes split by ".")
static string file_path (const string &path)
Finds the path to the directory the file is in.
static string top_directory (const string &path)
Get the top directory of a path.
static string parent_directory (const string &path)
Get the parent directory of the path.
static string absolute_path (const string &path)
Calculates path with out any "../" or "./".
static string join_path (const string &base, const string &extended)
Joins two paths together.
Detailed Description
Handles file & directory paths.
Definition at line 21 of file path.h.
Member Function Documentation
absolute_path()
string Path::absolute_path (const string & path) [static]
Calculates path with out any "../" or "./".
Parameters
path The path
Returns
The new path, direct from root
Definition at line 170 of file path.cpp.
                                             {
    // Split the path into components
    auto components = path.split("/");
    common::Vector<string> absolute_components;
    for (auto &component: components) {
        // Skip empty or self references
        if (component == "" || component == ".")
            continue;
        // Handle parent directory references
        if (component == "..") {
            if (!absolute_components.empty())
                absolute_components.pop_back();
        } else
            absolute_components.push_back(component);
    }
    // Join the components back into a path
    string absolute_path = "/";
    for(const auto& component : absolute_components)
        absolute_path += component + "/";
    // Remove trailing slash if file
    if(Path::is_file(absolute_path) && absolute_path.length() > 1)
        absolute_path = absolute_path.substring(0, absolute_path.length() - 1);
    return absolute_path;
}
References absolute_path(), and is_file().
Referenced by absolute_path(), MaxOS::filesystem::VFSResourceRegistry::create_resource(), and MaxOS::filesystem::VFSResourceRegistry::get_resource().
file_extension()
string Path::file_extension (const string & path) [static]
Try to get the file extension from a path (assumes split by ".")
Parameters
path The path to get the file extension from
Returns
The file extension or the original path if it does not exist
Definition at line 77 of file path.cpp.
                                              {
    // Find the last .
    int last_dot = -1;
    for (size_t i = 0; i < path.length(); i++)
        if (path[i] == '.')
            last_dot = i;
    // Make sure there was a dot to split
    if (last_dot == -1)
        return "";
    // Get the file extension (what is after the ".")
    string file_extension = path.substring(last_dot + 1, path.length() - last_dot - 1);
    return file_extension;
}
References file_extension().
Referenced by file_extension(), and is_file().
file_name()
string Path::file_name (const string & path) [static]
Get the file name component of a path if it exists or an empty string.
Parameters
path The path to get the file name from
Returns
The file name or the original path if it does not exist
Definition at line 54 of file path.cpp.
                                         {
    // Find the last /
    int last_slash = -1;
    for (size_t i = 0; i < path.length(); i++)
        if (path[i] == '/')
            last_slash = i;
    // Make sure there was a slash to split
    if (last_slash == -1)
        return path;
    // Get the file name
    string file_name = path.substring(last_slash + 1, path.length() - last_slash - 1);
    return file_name;
}
References file_name().
Referenced by MaxOS::filesystem::VirtualFileSystem::create_directory(), MaxOS::filesystem::VirtualFileSystem::create_file(), MaxOS::filesystem::VirtualFileSystem::delete_directory(), MaxOS::filesystem::VirtualFileSystem::delete_file(), MaxOS::filesystem::FileSystem::exists(), file_name(), is_file(), and MaxOS::filesystem::VirtualFileSystem::open_file().
file_path()
string Path::file_path (const string & path) [static]
Finds the path to the directory the file is in.
Parameters
path The path to get the file path from
Returns
The file path or the original path if it does not exist
Definition at line 101 of file path.cpp.
                                         {
    // Try to find the last /
    int last_slash = -1;
    for (size_t i = 0; i < path.length(); i++)
        if (path[i] == '/')
            last_slash = i;
    // Make sure there was a slash to split
    if (last_slash == -1)
        return path;
    // Get the file path
    string file_path = path.substring(0, last_slash);
    return file_path;
}
References file_path().
Referenced by MaxOS::filesystem::FileSystem::exists(), file_path(), and MaxOS::filesystem::VirtualFileSystem::open_directory().
is_file()
bool Path::is_file (const string & path) [static]
Check if a path is a file.
Parameters
path The path to check
Returns
True if the path is a file, false otherwise
Definition at line 42 of file path.cpp.
                                     {
    return file_name(path).length() > 0 && file_extension(path).length() > 0;
}
References file_extension(), and file_name().
Referenced by absolute_path(), MaxOS::filesystem::VFSResourceRegistry::create_resource(), and MaxOS::filesystem::VFSResourceRegistry::get_resource().
join_path()
string Path::join_path (const string & base, const string & extended) [static]
Joins two paths together.
Parameters
base The base path
extended What to add to the base path (if its from root, "/", then it will just return this)
Returns
The joint path
Definition at line 208 of file path.cpp.
                                                                 {
    // The new path is from root
    if(extended[0] == '/')
        return extended;
    return base + extended;
}
Referenced by MaxOS::filesystem::VFSResourceRegistry::create_resource(), and MaxOS::filesystem::VFSResourceRegistry::get_resource().
parent_directory()
string Path::parent_directory (const string & path) [static]
Get the parent directory of the path.
Parameters
path The path to either the file or the directory
Returns
Definition at line 148 of file path.cpp.
                                                {
    // Find the last /
    int last_slash = -1;
    for (size_t i = 0; i < path.length(); i++)
        if (path[i] == '/')
            last_slash = i;
    // If no slash or only root, return empty string
    if (last_slash <= 0)
        return "/";
    // Return substring up to last slash
    return path.substring(0, last_slash);
}
Referenced by MaxOS::filesystem::FileResource::write(), and MaxOS::filesystem::DirectoryResource::write().
top_directory()
string Path::top_directory (const string & path) [static]
Get the top directory of a path.
Parameters
path The path to get the top directory from
Returns
The top directory or the original path if it does not exist
Definition at line 125 of file path.cpp.
                                             {
    // Find the first /
    int first_slash = -1;
    for (size_t i = 0; i < path.length(); i++)
        if (path[i] == '/')
            first_slash = i;
    // Make sure there was a slash to split
    if (first_slash == -1)
        return path;
    // Get the top directory
    string top_directory = path.substring(0, first_slash);
    return top_directory;
}
References top_directory().
Referenced by MaxOS::filesystem::FileSystem::get_directory(), and top_directory().
valid()
bool Path::valid (const string & path) [static]
Check if a path is valid.
Parameters
path The path to check
Returns
True if the path is valid, false otherwise
Definition at line 21 of file path.cpp.
                                   {
    // Must not be empty
    if (path.length() == 0)
        return false;
    // Must start with a /
    if (path[0] != '/')
        return false;
    // Valid
    return true;
}
Referenced by MaxOS::filesystem::VirtualFileSystem::create_directory(), MaxOS::filesystem::VirtualFileSystem::create_file(), MaxOS::filesystem::VirtualFileSystem::delete_directory(), MaxOS::filesystem::VirtualFileSystem::delete_file(), MaxOS::filesystem::VirtualFileSystem::open_directory(), and MaxOS::filesystem::VirtualFileSystem::open_file().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/path.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/path.cpp