MaxOS::gui::Font Class Reference
A class that can be used to draw text.
#include <font.h>
Public Member Functions
Font (const uint8_t *font_data)
~Font ()
virtual void draw_text (int32_t x, int32_t y, common::Colour foreground_colour, common::Colour background_colour, common::GraphicsContext *context, string text)
write the entire text to the screen
virtual void draw_text (int32_t x, int32_t y, common::Colour foreground_colour, common::Colour background_colour, common::GraphicsContext *context, string text, common::Rectangle< int32_t > limitArea)
write the entire text to the screen
virtual int32_t get_text_height (string)
Get the height of the text.
virtual int32_t get_text_width (string)
Get the width of the text.
Public Attributes
bool is_bold { false }
bool is_italic { false }
bool is_underlined { false }
bool is_strikethrough { false }
Static Public Attributes
static const uint8_t padding = 3
static const uint16_t font_height = 8 + 2 * padding
static const uint16_t font_width = 8
Protected Attributes
bool m_is_8_by_8 = { true }
uint8_t m_font8x8 [2048] = {0}
Detailed Description
A class that can be used to draw text.
Definition at line 21 of file font.h.
Constructor & Destructor Documentation
Font()
Font::Font (const uint8_t * font_data)
Definition at line 11 of file font.cpp.
                                   {
    // Store the font data
    for (int i = 0; i < 2048; ++i) {
        m_font8x8[i] = font_data[i];
    }
}
References m_font8x8.
~Font()
Font::~Font () [default]
Member Function Documentation
draw_text() [1/2]
void Font::draw_text (int32_t x, int32_t y, common::Colour foreground_colour, common::Colour background_colour, common::GraphicsContext * context, string text) [virtual]
write the entire text to the screen
Parameters
x The x coordinate of the text
y The y coordinate of the text
context The graphics context to draw the text on
text The text to draw
Definition at line 28 of file font.cpp.
                                                                  {
    // Calculate the rectangle of the text
    int32_t top = 0;
    int32_t left = 0;
    int32_t width = get_text_width(text);
    int32_t height = get_text_height(text);
    // Create the rectangle
    Rectangle<int32_t> text_area(left, top, width, height);
    // Draw the text
    draw_text(x, y, foreground_colour, background_colour, context, text, text_area);
}
References draw_text(), get_text_height(), and get_text_width().
Referenced by MaxOS::gui::widgets::Button::draw(), MaxOS::gui::widgets::InputBox::draw(), MaxOS::gui::widgets::Text::draw(), draw_text(), and MaxOS::drivers::console::VESABootConsole::put_character().
draw_text() [2/2]
void Font::draw_text (int32_t x, int32_t y, common::Colour foreground_colour, common::Colour background_colour, common::GraphicsContext * context, string text, common::Rectangle< int32_t > limitArea) [virtual]
write the entire text to the screen
Parameters
x The x coordinate of the text
y The y coordinate of the text
context The graphics context to draw the text on
text The text to draw
limitArea The area of the text to draw
Definition at line 55 of file font.cpp.
                                                         {
    // Convert the colours
    uint32_t foreground = context->colour_to_int(foreground_colour);
    uint32_t background = context->colour_to_int(background_colour);
    // Ensure the area is within the actual area of the text
    if (limitArea.top < 0) {
        limitArea.height += limitArea.top;
        limitArea.top = 0;
    }
    if (limitArea.left < 0) {
        limitArea.width += limitArea.left;
        limitArea.left = 0;
    }
    // Clamp the height and width max
    if (limitArea.top + limitArea.height > (int) get_text_height(text))
        limitArea.height = get_text_height(text) - limitArea.top;
    if (limitArea.left + limitArea.width > (int) get_text_width(text))
        limitArea.width = get_text_width(text) - limitArea.left;
    // Calculate limits
    int32_t xLimit = limitArea.left + limitArea.width;
    int32_t yLimit = limitArea.top + limitArea.height;
    // Draw the text from top to bottom
    for (int yBitMapOffset = limitArea.top; yBitMapOffset < yLimit; yBitMapOffset++) {
        for (int xBitMapOffset = limitArea.left; xBitMapOffset < xLimit; ++xBitMapOffset) {
            // If the y is the middle then add a strikethrough
            if (is_strikethrough && yBitMapOffset == yLimit / 2) {
                // Draw the pixel
                context->putPixel(x + xBitMapOffset, y + yBitMapOffset, foreground);
                continue;
            }
            // If the y is the bottom then add an underline
            if (is_underlined && yBitMapOffset == yLimit - 1) {
                // Draw the pixel
                context->putPixel(x + xBitMapOffset, y + yBitMapOffset, foreground);
                continue;
            }
            //TODO: Bold, Italic when other fonts are working
            // Get the character
            uint8_t character = text[xBitMapOffset / 8];
            // Check if this pixel is set or not
            bool set = m_font8x8[(uint16_t) character * 8 + yBitMapOffset] & (128 >> (xBitMapOffset % 8));
            // Draw the pixel
            context->putPixel(x + xBitMapOffset, y + yBitMapOffset, set ? foreground : background);
        }
    }
}
References get_text_height(), get_text_width(), MaxOS::common::Rectangle< Type >::height, is_strikethrough, is_underlined, MaxOS::common::Rectangle< Type >::left, m_font8x8, MaxOS::common::Rectangle< Type >::top, and MaxOS::common::Rectangle< Type >::width.
get_text_height()
int32_t Font::get_text_height (string) [virtual]
Get the height of the text.
Parameters
text The text to get the height of
Returns
The height of the text
Definition at line 127 of file font.cpp.
                                    {
    return 8;
}
Referenced by draw_text(), and draw_text().
get_text_width()
int32_t Font::get_text_width (string text) [virtual]
Get the width of the text.
Parameters
text The text to get the width of
Returns
The width of the text
Definition at line 139 of file font.cpp.
                                        {
    return text.length() * 8;
}
References MaxOS::String::length().
Referenced by draw_text(), and draw_text().
Member Data Documentation
font_height
const uint16_t MaxOS::gui::Font::font_height = 8 + 2 * padding [static]
Definition at line 33 of file font.h.
Referenced by MaxOS::drivers::console::VESABootConsole::height(), MaxOS::drivers::console::VESABootConsole::put_character(), and MaxOS::drivers::console::VESABootConsole::scroll_up().
font_width
const uint16_t MaxOS::gui::Font::font_width = 8 [static]
Definition at line 34 of file font.h.
Referenced by MaxOS::drivers::console::VESABootConsole::scroll_up().
is_bold
bool MaxOS::gui::Font::is_bold { false }
Definition at line 36 of file font.h.
{ false };
is_italic
bool MaxOS::gui::Font::is_italic { false }
Definition at line 37 of file font.h.
{ false };
is_strikethrough
bool MaxOS::gui::Font::is_strikethrough { false }
Definition at line 39 of file font.h.
{ false };
Referenced by draw_text().
is_underlined
bool MaxOS::gui::Font::is_underlined { false }
Definition at line 38 of file font.h.
{ false };
Referenced by draw_text().
m_font8x8
uint8_t MaxOS::gui::Font::m_font8x8[2048] = {0} [protected]
Definition at line 24 of file font.h.
{0};
Referenced by draw_text(), and Font().
m_is_8_by_8
bool MaxOS::gui::Font::m_is_8_by_8 = { true } [protected]
Definition at line 23 of file font.h.
{ true };
padding
const uint8_t MaxOS::gui::Font::padding = 3 [static]
Definition at line 32 of file font.h.
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/font.h
/home/runner/work/MaxOS/MaxOS/kernel/src/gui/font.cpp