MaxOS::drivers::console::ConsoleStream Class Reference
A stream that can be used to write to a console.
#include <console.h>
Public Member Functions
ConsoleStream (Console *)
~ConsoleStream ()
void write_char (char c) override
write a character to the console stream
void set_cursor (uint16_t x, uint16_t y)
Set the m_position of the cursor.
Public Member Functions inherited from MaxOS::common::OutputStream
OutputStream ()
~OutputStream ()
virtual void lineFeed ()
Writes a newline to the output stream.
virtual void carriageReturn ()
Writes a carriage return to the output stream.
virtual void clear ()
Clears the output stream.
void write (string string_to_write) override
Writes a string to the output stream.
void write (const char *string_to_write)
Writes a string to the output stream.
virtual void write_int (int int_to_write)
Writes an integer to the output stream.
virtual void write_hex (uint64_t hex_to_write)
Writes a hex to the output stream.
OutputStream & operator<< (string string_to_write) override
Writes a string to the output stream.
OutputStream & operator<< (const char *string_to_write)
Writes a string to the output stream.
OutputStream & operator<< (int int_to_write)
Writes a integer to the output stream.
OutputStream & operator<< (uint64_t hex_to_write)
Writes a hexadecimal to the output stream.
OutputStream & operator<< (char char_to_write)
Writes a character to the output stream.
Public Member Functions inherited from MaxOS::common::GenericOutputStream< string >
GenericOutputStream ()
__________________________________________Templates__________________________________________________///
~GenericOutputStream ()
Destructor of the GenericOutputStream class.
void on_stream_read (string) override
Writes the date that was read from the input stream to the output stream.
void on_end_of_stream (GenericInputStream< string > *) override
Close the stream and remove it from the list of streams when the end of the stream is reached.
virtual void write (string)
write an element to the stream.
virtual void close ()
Close the stream.
virtual GenericOutputStream< string > & operator<< (string)
Overload the << operator to write an element to the stream.
Public Member Functions inherited from MaxOS::common::InputStreamProcessor< Type, ProcessorType >
InputStreamProcessor ()
InputStreamProcessor (InputStreamEventHandler< ProcessorType > *generic_stream_event_handler)
~InputStreamProcessor ()
void on_end_of_stream (GenericInputStream< Type > *stream) override
Public Member Functions inherited from MaxOS::common::InputStreamEventHandler< Type >
InputStreamEventHandler ()
_______________________________________________TEMPLATES_________________________________________________________________///
~InputStreamEventHandler ()
Public Member Functions inherited from MaxOS::common::GenericInputStream< ProcessorType >
GenericInputStream ()
GenericInputStream (InputStreamEventHandler< ProcessorType > *)
~GenericInputStream ()
void connect_input_stream_event_handler (InputStreamEventHandler< ProcessorType > *)
void disconnect_input_stream_event_handler (InputStreamEventHandler< ProcessorType > *)
Protected Attributes
Console * m_console
common::ConsoleColour m_foreground { common::ConsoleColour::LightGrey }
common::ConsoleColour m_background { common::ConsoleColour::Black }
bool is_ansi = false
uint16_t m_cursor_x { 0 }
uint16_t m_cursor_y { 0 }
Protected Attributes inherited from MaxOS::common::InputStreamEventHandler< Type >
common::Vector< GenericInputStream< Type > * > m_generic_input_streams
Protected Attributes inherited from MaxOS::common::GenericInputStream< ProcessorType >
common::Vector< InputStreamEventHandler< ProcessorType > * > m_input_stream_event_handlers
Detailed Description
A stream that can be used to write to a console.
Definition at line 92 of file console.h.
Constructor & Destructor Documentation
ConsoleStream()
ConsoleStream::ConsoleStream (Console * console)
Definition at line 397 of file console.cpp.
: m_console(console)
{
}
~ConsoleStream()
ConsoleStream::~ConsoleStream ()
Definition at line 403 of file console.cpp.
                              {
}
Member Function Documentation
set_cursor()
void ConsoleStream::set_cursor (uint16_t x, uint16_t y)
Set the m_position of the cursor.
Parameters
x The x coordinate of the cursor
y The y coordinate of the cursor
Definition at line 486 of file console.cpp.
                                                     {
    // Set the x and y coordinates
    m_cursor_x = x;
    m_cursor_y = y;
}
References m_cursor_x, and m_cursor_y.
Referenced by MaxOS::drivers::console::VESABootConsole::finish().
write_char()
void ConsoleStream::write_char (char c) [override], [virtual]
write a character to the console stream
Parameters
c The character to write
Reimplemented from MaxOS::common::OutputStream.
Definition at line 412 of file console.cpp.
                                     {
    uint16_t spaces = 0;
    // If the character placement is more than the width of the console go on a new line
    if(m_cursor_x >= m_console->width() && c != '\n'){
        lineFeed();
        write(" ");
    }
    // Check if the character is an ANSI escape code
    if(c == '\033') is_ansi = true;
    // Handle the character
    switch (c) {
        // New line
        case '\n':
            // Go to the next line, if it is more then what the console can fit then scroll
            if(++m_cursor_y >= m_console->height()){
                m_console->scroll_up();
                // Ensure there is space at the bottom to write
                m_cursor_y = m_console->height()-1;
            }
            // don't break here, we want to go to the next case because of the \r
            [[fallthrough]];
        // Carriage return
        case '\r':
            m_cursor_x = 0;
            break;
        // End of string
        case '\0':
            break;
        // Backspace
        case '\b':
            m_cursor_x--;
            break;
        // Tab
        case '\t':
            // Pad with spaces until a tab is reached
            spaces = 8 - (m_cursor_x % 8);
            for(uint16_t i = 0; i < spaces; i++)
                write_char(' ');
            break;
        default:
            // Put the character on the console
            m_console->put_character(m_cursor_x, m_cursor_y, c);
            // Increment the x coordinate (ANSI aren't rendered)
            if(!is_ansi)
              m_cursor_x++;
            break;
    }
    // Check if the ANSI code is complete
    if(c == 'm') is_ansi = false;
}
References MaxOS::drivers::console::Console::height(), is_ansi, MaxOS::common::OutputStream::lineFeed(), m_console, m_cursor_x, m_cursor_y, MaxOS::drivers::console::Console::put_character(), MaxOS::drivers::console::Console::scroll_up(), MaxOS::drivers::console::Console::width(), write, and write_char().
Referenced by write_char().
Member Data Documentation
is_ansi
bool MaxOS::drivers::console::ConsoleStream::is_ansi = false [protected]
Definition at line 99 of file console.h.
Referenced by write_char().
m_background
common::ConsoleColour MaxOS::drivers::console::ConsoleStream::m_background { common::ConsoleColour::Black } [protected]
Definition at line 98 of file console.h.
{ common::ConsoleColour::Black };
m_console
Console* MaxOS::drivers::console::ConsoleStream::m_console [protected]
Definition at line 95 of file console.h.
Referenced by write_char().
m_cursor_x
uint16_t MaxOS::drivers::console::ConsoleStream::m_cursor_x { 0 } [protected]
Definition at line 101 of file console.h.
{ 0 };
Referenced by set_cursor(), and write_char().
m_cursor_y
uint16_t MaxOS::drivers::console::ConsoleStream::m_cursor_y { 0 } [protected]
Definition at line 102 of file console.h.
{ 0 };
Referenced by set_cursor(), and write_char().
m_foreground
common::ConsoleColour MaxOS::drivers::console::ConsoleStream::m_foreground { common::ConsoleColour::LightGrey } [protected]
Definition at line 97 of file console.h.
{ common::ConsoleColour::LightGrey };
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/console.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/console/console.cpp