MaxOS::processes::SharedMessageEndpoint Class Reference
A endpoint that allows processes to queue messages on.
#include <ipc.h>
Public Member Functions
SharedMessageEndpoint (const string &name, size_t size, resource_type_t type)
Creates a new shared message endpoint.
~SharedMessageEndpoint () final
Destroys the shared message endpoint and frees all messages.
int read (void *buffer, size_t size, size_t flags) final
Reads the first message from the endpoint or will yield until a message has been written.
int write (const void *buffer, size_t size, size_t flags) final
Handles writing to the message endpoint resource by writing the buffer as a message.
Public Member Functions inherited from MaxOS::processes::Resource
Resource (const string &name, size_t flags, resource_type_t type)
Constructs a new Resource object.
string name ()
Gets the name of this resource.
resource_type_t type ()
Gets the type of this resource.
virtual void open (size_t flags)
Opens the resource.
virtual void close (size_t flags)
Closes the resource.
Detailed Description
A endpoint that allows processes to queue messages on.
Definition at line 54 of file ipc.h.
Constructor & Destructor Documentation
SharedMessageEndpoint()
SharedMessageEndpoint::SharedMessageEndpoint (const string & name, size_t size, resource_type_t type)
Creates a new shared message endpoint.
Parameters
name The name of the endpoint
size The size of messages that can be sent
type The type of resource
Definition at line 112 of file ipc.cpp.
: Resource(name, size, type)
{
}
~SharedMessageEndpoint()
SharedMessageEndpoint::~SharedMessageEndpoint () [final]
Destroys the shared message endpoint and frees all messages.
Definition at line 121 of file ipc.cpp.
                                              {
    // Free the messages
    for(auto& message : m_queue)
        delete message;
}
Member Function Documentation
read()
int SharedMessageEndpoint::read (void * buffer, size_t size, size_t flags) [final], [virtual]
Reads the first message from the endpoint or will yield until a message has been written.
Parameters
buffer Where to write the message to
size Max size of the message to be read
flags Unused
Returns
The amount of bytes read
Reimplemented from MaxOS::processes::Resource.
Definition at line 136 of file ipc.cpp.
                                                                       {
    // Wait for a message
    if(m_queue.empty())
        return -1 * (int)resource_error_base_t::SHOULD_BLOCK;
    // Read the message into the buffer
    buffer_t* message = m_queue.pop_front();
    size_t readable = size > message->capacity() ? message->capacity() : size;
    memcpy(buffer, message -> raw(), readable);
    return readable;
}
References memcpy().
write()
int SharedMessageEndpoint::write (const void * buffer, size_t size, size_t flags) [final], [virtual]
Handles writing to the message endpoint resource by writing the buffer as a message.
Parameters
buffer The message to write to the endpoint
size The size of the message
flags Unused
Returns
The amount of bytes written
Reimplemented from MaxOS::processes::Resource.
Definition at line 158 of file ipc.cpp.
                                                                              {
    m_message_lock.lock();
    // Create the message
    auto* new_message = new buffer_t(size);
    new_message->copy_from(buffer, size);
    m_queue.push_back(new_message);
    m_message_lock.unlock();
    return size;
}
References MaxOS::common::Spinlock::lock(), and MaxOS::common::Spinlock::unlock().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/processes/ipc.h
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/ipc.cpp