MaxOS::net::TransmissionControlProtocolSocket Class Reference
#include <tcp.h>
Public Member Functions
TransmissionControlProtocolSocket (TransmissionControlProtocolHandler *transmissionControlProtocolHandler)
Socket///
~TransmissionControlProtocolSocket ()
virtual void Send (uint8_t *data, uint16_t size)
Send data over the socket.
virtual void Disconnect ()
Disconnect the socket.
void Disconnected ()
void Connected ()
bool handleTransmissionControlProtocolPayload (uint8_t *data, uint16_t size)
Handle the TCP message (socket end)
Public Member Functions inherited from MaxOS::common::EventManager< TransmissionControlProtocolPayloadHandlerEvents >
EventManager ()
~EventManager ()
void connect_event_handler (EventHandler< TransmissionControlProtocolPayloadHandlerEvents > *handler)
Connect an event handler to the event manager if it is not already connected.
void disconnect_event_handler (EventHandler< TransmissionControlProtocolPayloadHandlerEvents > *handler)
Disconnect an event handler from the event manager if it is connected.
Vector< Event< TransmissionControlProtocolPayloadHandlerEvents > * > raise_event (Event< TransmissionControlProtocolPayloadHandlerEvents > *event)
Calls the on_event function of all the event m_handlers connected to the event manager and returns a list of the results.
Protected Attributes
uint16_t remotePort = 0
uint32_t remoteIP = 0
uint16_t localPort = 0
uint32_t localIP = 0
uint32_t sequenceNumber = 0
uint32_t acknowledgementNumber = 0
TransmissionControlProtocolHandler * transmissionControlProtocolHandler
TCPSocketState state
Protected Attributes inherited from MaxOS::common::EventManager< TransmissionControlProtocolPayloadHandlerEvents >
Vector< EventHandler< TransmissionControlProtocolPayloadHandlerEvents > * > m_handlers
Friends
class TransmissionControlProtocolHandler
class TransmissionControlProtocolPortListener
Detailed Description
Definition at line 131 of file tcp.h.
Constructor & Destructor Documentation
TransmissionControlProtocolSocket()
TransmissionControlProtocolSocket::TransmissionControlProtocolSocket (TransmissionControlProtocolHandler * transmissionControlProtocolHandler)
Socket///
Definition at line 56 of file tcp.cpp.
{
    //Set the default values
    this -> transmissionControlProtocolHandler = transmissionControlProtocolHandler;
    //Closed as default
    state = TCPSocketState::CLOSED;
}
References MaxOS::net::CLOSED, state, and transmissionControlProtocolHandler.
~TransmissionControlProtocolSocket()
TransmissionControlProtocolSocket::~TransmissionControlProtocolSocket () [default]
Member Function Documentation
Connected()
void TransmissionControlProtocolSocket::Connected ()
Definition at line 112 of file tcp.cpp.
                                                  {
    auto* event = new ConnectedEvent(this);
    raise_event(event);
    MemoryManager::kfree(event);
}
References MaxOS::memory::MemoryManager::kfree(), and MaxOS::common::EventManager< TransmissionControlProtocolPayloadHandlerEvents >::raise_event().
Disconnect()
void TransmissionControlProtocolSocket::Disconnect () [virtual]
Disconnect the socket.
Definition at line 100 of file tcp.cpp.
{
    transmissionControlProtocolHandler -> Disconnect(this);
}
References Disconnect(), and transmissionControlProtocolHandler.
Referenced by Disconnect().
Disconnected()
void TransmissionControlProtocolSocket::Disconnected ()
Definition at line 105 of file tcp.cpp.
                                                     {
    auto* event = new DisconnectedEvent(this);
    raise_event(event);
    MemoryManager::kfree(event);
}
References MaxOS::memory::MemoryManager::kfree(), and MaxOS::common::EventManager< TransmissionControlProtocolPayloadHandlerEvents >::raise_event().
handleTransmissionControlProtocolPayload()
bool TransmissionControlProtocolSocket::handleTransmissionControlProtocolPayload (uint8_t * data, uint16_t size)
Handle the TCP message (socket end)
Parameters
data The datah
size The size of the data
Returns
True if the connection is to be terminated after hadnling or false if not
Definition at line 74 of file tcp.cpp.
{
    auto* event = new DataReceivedEvent(this, data, size);
    raise_event(event);
    MemoryManager::kfree(event);
    return true;
}
References data, MaxOS::memory::MemoryManager::kfree(), MaxOS::common::EventManager< TransmissionControlProtocolPayloadHandlerEvents >::raise_event(), and size.
Send()
void TransmissionControlProtocolSocket::Send (uint8_t * data, uint16_t size) [virtual]
Send data over the socket.
Parameters
data The data to send
size The size of the data
Definition at line 88 of file tcp.cpp.
{
    //Wait for the socket to be connected
    while(state != TCPSocketState::ESTABLISHED);
    //Pass the data to the backend
    transmissionControlProtocolHandler -> sendTransmissionControlProtocolPacket(this, data, size, (uint16_t)TCPFlag::PSH | (uint16_t)TCPFlag::ACK);
}
References MaxOS::net::ACK, data, MaxOS::net::ESTABLISHED, MaxOS::net::PSH, size, state, and transmissionControlProtocolHandler.
Friends And Related Symbol Documentation
TransmissionControlProtocolHandler
friend class TransmissionControlProtocolHandler [friend]
Definition at line 133 of file tcp.h.
TransmissionControlProtocolPortListener
friend class TransmissionControlProtocolPortListener [friend]
Definition at line 134 of file tcp.h.
Member Data Documentation
acknowledgementNumber
uint32_t MaxOS::net::TransmissionControlProtocolSocket::acknowledgementNumber = 0 [protected]
Definition at line 141 of file tcp.h.
localIP
uint32_t MaxOS::net::TransmissionControlProtocolSocket::localIP = 0 [protected]
Definition at line 139 of file tcp.h.
localPort
uint16_t MaxOS::net::TransmissionControlProtocolSocket::localPort = 0 [protected]
Definition at line 138 of file tcp.h.
remoteIP
uint32_t MaxOS::net::TransmissionControlProtocolSocket::remoteIP = 0 [protected]
Definition at line 137 of file tcp.h.
remotePort
uint16_t MaxOS::net::TransmissionControlProtocolSocket::remotePort = 0 [protected]
Definition at line 136 of file tcp.h.
sequenceNumber
uint32_t MaxOS::net::TransmissionControlProtocolSocket::sequenceNumber = 0 [protected]
Definition at line 140 of file tcp.h.
state
TCPSocketState MaxOS::net::TransmissionControlProtocolSocket::state [protected]
Definition at line 144 of file tcp.h.
Referenced by Send(), and TransmissionControlProtocolSocket().
transmissionControlProtocolHandler
TransmissionControlProtocolHandler* MaxOS::net::TransmissionControlProtocolSocket::transmissionControlProtocolHandler [protected]
Definition at line 143 of file tcp.h.
Referenced by Disconnect(), Send(), and TransmissionControlProtocolSocket().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/net/tcp.h
/home/runner/work/MaxOS/MaxOS/kernel/src/net/tcp.cpp