MaxOS::filesystem::format::ext2::Ext2File Class Reference
Handles the file operations on the ext2 filesystem.
#include <ext2.h>
Public Member Functions
Ext2File (Ext2Volume *volume, uint32_t inode, const string &name)
Construct a new Ext2 File object.
void write (const common::buffer_t *data, size_t amount) final
Write data to the file (at the current seek position, updated to be += amount)
void read (common::buffer_t *data, size_t amount) final
Read data from the file (at the current seek position, updated to be += amount)
void flush () final
Flush the file to the disk.
Public Member Functions inherited from MaxOS::filesystem::File
void seek (SeekType seek_type, size_t offset)
Seek to a position in the file.
uint32_t position ()
Get where the file is currently at (amount read/write/seeked)
size_t size ()
Get the size of the file.
string name ()
Get the name of the file.
Additional Inherited Members
Protected Attributes inherited from MaxOS::filesystem::File
uint32_t m_offset
The current offset in the file.
string m_name
The name of the file.
size_t m_size
The size of the file.
Detailed Description
Handles the file operations on the ext2 filesystem.
Definition at line 388 of file ext2.h.
Constructor & Destructor Documentation
Ext2File()
Ext2File::Ext2File (Ext2Volume * volume, uint32_t inode, const string & name)
Construct a new Ext2 File object.
Parameters
volume The volume the file exists on
inode The inode number of the file (will be used to setup the internal InodeHandler)
name The name of the file
Definition at line 723 of file ext2.cpp.
: m_volume(volume),
  m_inode(volume, inode)
{
    // Set up the base information
    m_name = name;
    m_size = m_inode.size();
}
References MaxOS::filesystem::File::m_name, MaxOS::filesystem::File::m_size, MaxOS::filesystem::File::name(), and MaxOS::filesystem::format::ext2::InodeHandler::size().
Member Function Documentation
flush()
void Ext2File::flush () [final], [virtual]
Flush the file to the disk.
Reimplemented from MaxOS::filesystem::File.
Definition at line 840 of file ext2.cpp.
                     {
    File::flush();
}
References MaxOS::filesystem::File::flush().
read()
void Ext2File::read (common::buffer_t * data, size_t amount) [final], [virtual]
Read data from the file (at the current seek position, updated to be += amount)
Parameters
data The byte buffer to read into
amount The amount of data to read
Reimplemented from MaxOS::filesystem::File.
Definition at line 794 of file ext2.cpp.
                                                 {
    // Nothing to read
    if (m_size == 0 || amount == 0)
        return;
    // Prepare for reading
    m_volume->ext2_lock.lock();
    const uint32_t block_size = m_volume->block_size;
    buffer_t buffer(block_size);
    // Force bounds
    if (m_offset + amount > m_size)
        amount = m_size - m_offset;
    // Convert bytes to blocks
    uint32_t block_start = m_offset / block_size;
    uint32_t block_offset = m_offset % block_size;
    // Read each block
    size_t current_block = block_start;
    size_t read = 0;
    while (read < amount) {
        // Read the block
        uint32_t block = m_inode.block_cache[current_block++];
        m_volume->read_block(block, &buffer);
        // Where in this block to start reading
        size_t buffer_start = (current_block - 1 == block_start) ? block_offset : 0;
        size_t readable = (amount - read < block_size - buffer_start) ? (amount - read) : (block_size - buffer_start);
        // Read the block
        buffer.copy_to(data, readable, buffer_start, read);
        read += readable;
    }
    // Clean up
    m_offset += amount;
    m_volume->ext2_lock.unlock();
}
References MaxOS::filesystem::format::ext2::InodeHandler::block_cache, block_size, MaxOS::filesystem::format::ext2::Ext2Volume::block_size, MaxOS::common::Buffer::copy_to(), data, MaxOS::filesystem::format::ext2::Ext2Volume::ext2_lock, MaxOS::common::Spinlock::lock(), MaxOS::filesystem::File::m_offset, MaxOS::filesystem::File::m_size, read(), MaxOS::filesystem::format::ext2::Ext2Volume::read_block(), and MaxOS::common::Spinlock::unlock().
Referenced by read().
write()
void Ext2File::write (const common::buffer_t * data, size_t amount) [final], [virtual]
Write data to the file (at the current seek position, updated to be += amount)
Parameters
data The byte buffer to write
amount The amount of data to write
Reimplemented from MaxOS::filesystem::File.
Definition at line 740 of file ext2.cpp.
                                                        {
    // Nothing to write
    if (amount == 0)
        return;
    // Prepare for writing
    m_volume->ext2_lock.lock();
    const uint32_t block_size = m_volume->block_size;
    buffer_t buffer(block_size);
    // Expand the file
    if (m_offset + amount > m_size)
        m_size = m_inode.grow((m_offset + amount) - m_size, false);
    // Save the updated metadata
    m_inode.inode.last_modification_time = time_to_epoch(Clock::active_clock()->get_time());
    m_inode.save();
    // Convert bytes to blocks
    uint32_t block_start = m_offset / block_size;
    uint32_t block_offset = m_offset % block_size;
    // Write each block
    size_t current_block = block_start;
    size_t written = 0;
    while (written < amount) {
        // Read the block
        uint32_t block = m_inode.block_cache[current_block++];
        m_volume->read_block(block, &buffer);
        // Where in this block to start writing
        size_t buffer_start = (current_block - 1 == block_start) ? block_offset : 0;
        size_t writable = (amount - written < block_size - buffer_start) ? (amount - written) : (block_size -
                                                                                                 buffer_start);
        // Update the block
        buffer.copy_from(data, writable, buffer_start, written);
        m_volume->write_block(block, &buffer);
        written += writable;
    }
    // Clean up
    m_offset += amount;
    m_volume->ext2_lock.unlock();
}
References MaxOS::drivers::clock::Clock::active_clock(), MaxOS::filesystem::format::ext2::InodeHandler::block_cache, block_size, MaxOS::filesystem::format::ext2::Ext2Volume::block_size, MaxOS::common::Buffer::copy_from(), data, MaxOS::filesystem::format::ext2::Ext2Volume::ext2_lock, MaxOS::filesystem::format::ext2::InodeHandler::grow(), MaxOS::filesystem::format::ext2::InodeHandler::inode, MaxOS::common::Spinlock::lock(), MaxOS::filesystem::File::m_offset, MaxOS::filesystem::File::m_size, MaxOS::filesystem::format::ext2::Ext2Volume::read_block(), MaxOS::filesystem::format::ext2::InodeHandler::save(), MaxOS::common::Spinlock::unlock(), and MaxOS::filesystem::format::ext2::Ext2Volume::write_block().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/format/ext2.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/format/ext2.cpp