MaxOS::net::IPV4PayloadHandler Class Reference
Handles the payload of a specific IP protocol.
#include <ipv4.h>
Public Member Functions
IPV4PayloadHandler (InternetProtocolHandler *internet_protocol_handler, uint8_t protocol)
Construct a new IPV4 Payload Handler object and register it with the Internet Protocol Handler.
virtual bool handle_internet_protocol_payload (net::InternetProtocolAddress src_ip_be, net::InternetProtocolAddress dst_ip_be, uint8_t *internetprotocol_payload, uint32_t size)
Called when an IP packet is received. (Deafult, does nothing, overide for use)
void send (InternetProtocolAddress destination_ip, uint8_t *payload_data, uint32_t size)
Sends an IP packet.
Protected Attributes
InternetProtocolHandler * internet_protocol_handler
The Internet protocol handler this payload handler is connected to.
uint8_t ip_protocol
The IP protocol this handler handles.
Friends
class InternetProtocolHandler
Detailed Description
Handles the payload of a specific IP protocol.
Definition at line 66 of file ipv4.h.
Constructor & Destructor Documentation
IPV4PayloadHandler()
IPV4PayloadHandler::IPV4PayloadHandler (InternetProtocolHandler * internet_protocol_handler, uint8_t protocol)
Construct a new IPV4 Payload Handler object and register it with the Internet Protocol Handler.
Parameters
internet_protocol_handler The Internet Protocol Handler to register with
protocol The IP protocol to handle
Definition at line 57 of file ipv4.cpp.
                                                                                                           {
    // Store vars
    this->internet_protocol_handler = internet_protocol_handler;
    this->ip_protocol = protocol;
    //Register handler
    internet_protocol_handler->connect_ipv_4_payload_handler(this);
}
References MaxOS::net::InternetProtocolHandler::connect_ipv_4_payload_handler(), internet_protocol_handler, and ip_protocol.
Member Function Documentation
handle_internet_protocol_payload()
bool IPV4PayloadHandler::handle_internet_protocol_payload (net::InternetProtocolAddress src_ip_be, net::InternetProtocolAddress dst_ip_be, uint8_t * internetprotocol_payload, uint32_t size) [virtual]
Called when an IP packet is received. (Deafult, does nothing, overide for use)
Parameters
src_ip_be The source IP address.
dst_ip_be The destination IP address.
internetprotocol_payload The payload of the IP packet.
size The size of the IP packet.
Returns
True if the packet was handled, false otherwise.
Reimplemented in MaxOS::net::TransmissionControlProtocolHandler, MaxOS::net::UserDatagramProtocolHandler, and MaxOS::net::InternetControlMessageProtocol.
Definition at line 79 of file ipv4.cpp.
                                                                         {
    return false;
}
send()
void IPV4PayloadHandler::send (InternetProtocolAddress destination_ip, uint8_t * payload_data, uint32_t size)
Sends an IP packet.
Parameters
destination_ip The destination IP address.
payload_data The payload of the IP packet.
size The size of the IP packet.
Definition at line 93 of file ipv4.cpp.
                                                                                                          {
    //Pass to backend
    internet_protocol_handler->send_internet_protocol_packet(destination_ip, ip_protocol, payload_data, size);
}
References internet_protocol_handler, ip_protocol, and MaxOS::net::InternetProtocolHandler::send_internet_protocol_packet().
Referenced by MaxOS::net::InternetControlMessageProtocol::request_echo_reply(), MaxOS::net::UserDatagramProtocolHandler::send(), and MaxOS::net::TransmissionControlProtocolHandler::send_transmission_control_protocol_packet().
Friends And Related Symbol Documentation
InternetProtocolHandler
friend class InternetProtocolHandler [friend]
Definition at line 67 of file ipv4.h.
Member Data Documentation
internet_protocol_handler
InternetProtocolHandler* MaxOS::net::IPV4PayloadHandler::internet_protocol_handler [protected]
The Internet protocol handler this payload handler is connected to.
Definition at line 70 of file ipv4.h.
Referenced by MaxOS::net::TransmissionControlProtocolHandler::connect(), MaxOS::net::UserDatagramProtocolHandler::connect(), IPV4PayloadHandler(), MaxOS::net::TransmissionControlProtocolHandler::listen(), MaxOS::net::UserDatagramProtocolHandler::listen(), and send().
ip_protocol
uint8_t MaxOS::net::IPV4PayloadHandler::ip_protocol [protected]
The IP protocol this handler handles.
Definition at line 71 of file ipv4.h.
Referenced by IPV4PayloadHandler(), and send().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/net/ipv4.h
/home/runner/work/MaxOS/MaxOS/kernel/src/net/ipv4.cpp