MaxOS::drivers::clock::Clock Class Reference
Driver for the APIC clock.
#include <clock.h>
Public Member Functions
Clock (hardwarecommunication::AdvancedProgrammableInterruptController *apic, uint16_t time_between_events=10)
Constructor for the Clock class.
~Clock ()
void activate () override
Activates the clock, setting the binary coded decimal representation flag.
void delay (uint32_t milliseconds) const
Delays the program for a specified number of milliseconds (rounded up to the nearest degree of accuracy - ensured the delay is at least the specified number of milliseconds). This on the kernel level is a busy wait, for user level see the sleep function in the Thread class.
void calibrate (uint64_t ms_per_tick=1)
Configures the APIC clock to fire an interrupt at a specified interval in milliseconds.
common::Time get_time ()
Reads the current time from the APIC clock (in 24hr time)
string vendor_name () final
Gets the vendor who created the device.
string device_name () final
Gets the name of the device.
Public Member Functions inherited from MaxOS::drivers::Driver
Driver ()
~Driver ()
virtual void deactivate ()
deactivate the driver
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
Public Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
virtual system::cpu_status_t * handle_interrupt (system::cpu_status_t *status)
Handles an interrupt and returns the status.
Public Member Functions inherited from MaxOS::common::EventManager< ClockEvents >
EventManager ()
~EventManager ()
void connect_event_handler (EventHandler< ClockEvents > *handler)
Connect an event handler to the event manager if it is not already connected.
void disconnect_event_handler (EventHandler< ClockEvents > *handler)
Disconnect an event handler from the event manager if it is connected.
Vector< Event< ClockEvents > * > raise_event (Event< ClockEvents > *event)
Calls the on_event function of all the event m_handlers connected to the event manager and returns a list of the results.
Static Public Member Functions
static Clock * active_clock ()
Public Attributes
uint64_t clock_accuracy = 1
Protected Member Functions
void handle_interrupt () final
Handle the clock interrupt, raising the clock event if enough time has passed.
uint8_t read_hardware_clock (uint8_t address)
read the current time from the hardware clock and return it
uint8_t binary_representation (uint8_t number) const
The binary representation of a number.
Protected Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
InterruptHandler (uint8_t interrupt_number, int64_t redirect=-1, uint64_t redirect_index=0)
~InterruptHandler ()
Protected Attributes
bool m_binary { true }
bool m_24_hour_clock { true }
hardwarecommunication::Port8Bit m_data_port { 0x71 }
hardwarecommunication::Port8Bit m_command_port { 0x70 }
hardwarecommunication::AdvancedProgrammableInterruptController * m_apic
uint16_t m_ticks_between_events { 0 }
uint16_t m_ticks_until_next_event { 1 }
Protected Attributes inherited from MaxOS::hardwarecommunication::InterruptHandler
uint8_t m_interrupt_number
Protected Attributes inherited from MaxOS::common::EventManager< ClockEvents >
Vector< EventHandler< ClockEvents > * > m_handlers
Static Protected Attributes
static Clock * s_active_clock = nullptr
Detailed Description
Driver for the APIC clock.
Definition at line 128 of file clock.h.
Constructor & Destructor Documentation
Clock()
Clock::Clock (hardwarecommunication::AdvancedProgrammableInterruptController * apic, uint16_t time_between_events = 10)
Constructor for the Clock class.
Parameters
interrupt_manager The interrupt manager
time_between_events The time between events in 10ths of a second
Definition at line 53 of file clock.cpp.
: InterruptHandler(0x20),
  m_apic(apic),
  m_ticks_between_events(time_between_events)
{
    Logger::INFO() << "Setting up Clock \n";
}
References Logger::INFO().
~Clock()
Clock::~Clock () [default]
Member Function Documentation
activate()
void Clock::activate () [override], [virtual]
Activates the clock, setting the binary coded decimal representation flag.
Reimplemented from MaxOS::drivers::Driver.
Definition at line 117 of file clock.cpp.
                     {
    s_active_clock = this;
    // Get the stats from the clock
    uint8_t status = read_hardware_clock(0xB);
    // Store the clock status
    m_24_hour_clock = status & 0x02;
    m_binary = status & 0x04;
}
References m_24_hour_clock, m_binary, read_hardware_clock(), s_active_clock, and status.
active_clock()
Clock * Clock::active_clock () [static]
Definition at line 223 of file clock.cpp.
                           {
    return s_active_clock;
}
References s_active_clock.
Referenced by MaxOS::filesystem::format::ext2::Ext2Volume::create_inode(), and MaxOS::filesystem::format::ext2::Ext2File::write().
binary_representation()
uint8_t Clock::binary_representation (uint8_t number) const [protected]
The binary representation of a number.
Parameters
number The number to convert
Returns
The binary representation of the number if the binary coded decimal representation is used, otherwise the number
Definition at line 104 of file clock.cpp.
                                                         {
    // Check if the conversion needed
    if (m_binary)
        return number;
    // Convert to the binary representation
    return ((number / 16) * 10) + (number & 0x0f);
}
References m_binary.
Referenced by get_time().
calibrate()
void Clock::calibrate (uint64_t ms_per_tick = 1)
Configures the APIC clock to fire an interrupt at a specified interval in milliseconds.
Parameters
ms_per_tick How many milliseconds per interrupt
Definition at line 173 of file clock.cpp.
                                          {
    Logger::INFO() << "Calibrating Clock \n";
    clock_accuracy = ms_per_tick;
    // Get the ticks per ms
    PIT pit(m_apic);
    uint32_t ticks_per_ms = pit.ticks_per_ms();
    // Configure the clock to periodic mode
    uint32_t lvt = 0x20 | (1 << 17);
    m_apic->local_apic()->write(0x320, lvt);
    // Set the initial count
    m_apic->local_apic()->write(0x380, ms_per_tick * ticks_per_ms);
    // Clear the interrupt mask for the clock
    lvt &= ~(1 << 16);
    m_apic->local_apic()->write(0x380, lvt);
    Logger::DEBUG() << "Clock: Calibrated to " << ms_per_tick << "ms per tick\n";
}
References clock_accuracy, Logger::DEBUG(), Logger::INFO(), MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController::local_apic(), m_apic, and MaxOS::hardwarecommunication::LocalAPIC::write().
delay()
void Clock::delay (uint32_t milliseconds) const
Delays the program for a specified number of milliseconds (rounded up to the nearest degree of accuracy - ensured the delay is at least the specified number of milliseconds). This on the kernel level is a busy wait, for user level see the sleep function in the Thread class.
See also
Thread::sleep
Parameters
milliseconds How many milliseconds to delay the program for.
Definition at line 139 of file clock.cpp.
                                             {
    // Round the number of milliseconds UP to the nearest clock accuracy
    uint64_t rounded_milliseconds = (milliseconds + clock_accuracy - 1) / clock_accuracy;
    // Wait until the time has passed
    uint64_t ticks_until_delay_is_over = m_ticks + rounded_milliseconds;
    while (m_ticks < ticks_until_delay_is_over)
        asm volatile("nop");
}
References clock_accuracy.
device_name()
string Clock::device_name () [final], [virtual]
Gets the name of the device.
Returns
The name of the device
Reimplemented from MaxOS::drivers::Driver.
Definition at line 164 of file clock.cpp.
                          {
    return "Clock";
}
get_time()
common::Time Clock::get_time ()
Reads the current time from the APIC clock (in 24hr time)
Returns
The current time in a Time struct format
Definition at line 201 of file clock.cpp.
                           {
    // Wait for the clock to be ready
    while (read_hardware_clock(0xA) & 0x80)
        asm volatile("nop");
    // Read the time from the clock
    Time time{};
    time.year = binary_representation(read_hardware_clock(0x9)) + 2000;
    time.month = binary_representation(read_hardware_clock(0x8));
    time.day = binary_representation(read_hardware_clock(0x7));
    time.hour = binary_representation(read_hardware_clock(0x4));
    time.minute = binary_representation(read_hardware_clock(0x2));
    time.second = binary_representation(read_hardware_clock(0x0));
    // If the clock is using 12hr format and PM is set then add 12 to the hour
    if (!m_24_hour_clock && (time.hour & 0x80) != 0)
        time.hour = ((time.hour & 0x7F) + 12) % 24;
    return time;
}
References binary_representation(), m_24_hour_clock, read_hardware_clock(), and MaxOS::common::Time::year.
handle_interrupt()
void Clock::handle_interrupt () [final], [protected], [virtual]
Handle the clock interrupt, raising the clock event if enough time has passed.
Reimplemented from MaxOS::hardwarecommunication::InterruptHandler.
Definition at line 67 of file clock.cpp.
                             {
    // Clock has ticked
    m_ticks++;
    m_ticks_until_next_event--;
    // Dont raise events until needed
    if (m_ticks_until_next_event != 0)
        return;
    // Raise the time event
// Time time = get_time();
// raise_event(new TimeEvent(&time));
    // Reset
    m_ticks_until_next_event = m_ticks_between_events;
}
References m_ticks_between_events, and m_ticks_until_next_event.
read_hardware_clock()
uint8_t Clock::read_hardware_clock (uint8_t address) [protected]
read the current time from the hardware clock and return it
Parameters
address The address of the register to read from
Returns
The value of the register
Definition at line 92 of file clock.cpp.
                                                  {
    m_command_port.write(address);
    return m_data_port.read();
}
References address, m_command_port, m_data_port, MaxOS::hardwarecommunication::Port8Bit::read(), and MaxOS::hardwarecommunication::Port8Bit::write().
Referenced by activate(), and get_time().
vendor_name()
string Clock::vendor_name () [final], [virtual]
Gets the vendor who created the device.
Returns
The name of the vendor
Reimplemented from MaxOS::drivers::Driver.
Definition at line 155 of file clock.cpp.
                          {
    return "Generic";
}
Member Data Documentation
clock_accuracy
uint64_t MaxOS::drivers::clock::Clock::clock_accuracy = 1
Definition at line 160 of file clock.h.
Referenced by calibrate(), and delay().
m_24_hour_clock
bool MaxOS::drivers::clock::Clock::m_24_hour_clock { true } [protected]
Definition at line 136 of file clock.h.
{ true };
Referenced by activate(), and get_time().
m_apic
hardwarecommunication::AdvancedProgrammableInterruptController* MaxOS::drivers::clock::Clock::m_apic [protected]
Definition at line 143 of file clock.h.
Referenced by calibrate().
m_binary
bool MaxOS::drivers::clock::Clock::m_binary { true } [protected]
Definition at line 135 of file clock.h.
{ true };
Referenced by activate(), and binary_representation().
m_command_port
hardwarecommunication::Port8Bit MaxOS::drivers::clock::Clock::m_command_port { 0x70 } [protected]
Definition at line 140 of file clock.h.
{ 0x70 };
Referenced by read_hardware_clock().
m_data_port
hardwarecommunication::Port8Bit MaxOS::drivers::clock::Clock::m_data_port { 0x71 } [protected]
Definition at line 139 of file clock.h.
{ 0x71 };
Referenced by read_hardware_clock().
m_ticks_between_events
uint16_t MaxOS::drivers::clock::Clock::m_ticks_between_events { 0 } [protected]
Definition at line 146 of file clock.h.
{ 0 };
Referenced by handle_interrupt().
m_ticks_until_next_event
uint16_t MaxOS::drivers::clock::Clock::m_ticks_until_next_event { 1 } [protected]
Definition at line 147 of file clock.h.
{ 1 };
Referenced by handle_interrupt().
s_active_clock
Clock* MaxOS::drivers::clock::Clock::s_active_clock = nullptr [inline], [static], [protected]
Definition at line 154 of file clock.h.
Referenced by activate(), and active_clock().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/clock/clock.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/clock/clock.cpp