MaxOS::processes::Thread Class Reference
The execution context of a sub-process thread.
#include <process.h>
Public Member Functions
Thread (void(*_entry_point)(void *), void *args, int arg_amount, Process *parent)
Constructor for the Thread class.
~Thread ()
Destructor for the Thread class.
system::cpu_status_t * sleep (size_t milliseconds)
Sleeps the thread for a certain amount of time (Yields the thread)
uintptr_t tss_pointer () const
void save_sse_state ()
Saves the SSE, x87 FPU, and MMX states from memory to the thread.
void restore_sse_state ()
Restores the SSE, x87 FPU, and MMX states from the thread to memory.
Public Attributes
uint64_t tid
uint64_t parent_pid
system::cpu_status_t * execution_state
thread_state_t thread_state
size_t ticks
size_t wakeup_time
Detailed Description
The execution context of a sub-process thread.
Definition at line 42 of file process.h.
Constructor & Destructor Documentation
Thread()
Thread::Thread (void(*)(void *) _entry_point, void * args, int arg_amount, Process * parent)
Constructor for the Thread class.
Definition at line 18 of file process.cpp.
                                                                                        {
    // Basic setup
    thread_state = ThreadState::NEW;
    wakeup_time = 0;
    ticks = 0;
    // Create the stack
    m_stack_pointer = (uintptr_t) MemoryManager::malloc(s_stack_size);
    // Create the TSS stack
    if (parent->is_kernel) {
        // Use the kernel stack
        m_tss_stack_pointer = CPU::tss.rsp0;
    } else {
        m_tss_stack_pointer = (uintptr_t) MemoryManager::kmalloc(s_stack_size) + s_stack_size;
    }
    // Mak sure there is a stack
    ASSERT(m_stack_pointer != 0 && m_tss_stack_pointer != 0, "Failed to allocate stack for thread");
    // Set up the execution state
    execution_state = new cpu_status_t;
    execution_state->rip = (uint64_t) _entry_point;
    execution_state->ss = parent->is_kernel ? 0x10 : 0x23;
    execution_state->cs = parent->is_kernel ? 0x8 : 0x1B;
    execution_state->rflags = 0x202;
    execution_state->interrupt_number = 0;
    execution_state->error_code = 0;
    execution_state->rsp = m_stack_pointer;
    execution_state->rbp = 0;
    // Copy the args into userspace
    uint64_t argc = arg_amount;
    void* argv = MemoryManager::malloc(arg_amount * sizeof(void*));
    memcpy(argv, args, arg_amount * sizeof(void*));
    execution_state->rdi = argc;
    execution_state->rsi = (uint64_t) argv;
    //execution_state->rdx = (uint64_t)env_args;
    // Begin scheduling this thread
    parent_pid = parent->pid();
    tid = Scheduler::system_scheduler()->add_thread(this);
}
References ASSERT, execution_state, MaxOS::memory::MemoryManager::kmalloc(), MaxOS::memory::MemoryManager::malloc(), memcpy(), MaxOS::processes::NEW, parent_pid, MaxOS::processes::Scheduler::system_scheduler(), thread_state, ticks, tid, MaxOS::system::CPU::tss, and wakeup_time.
~Thread()
Thread::~Thread () [default]
Destructor for the Thread class.
Member Function Documentation
restore_sse_state()
void Thread::restore_sse_state ()
Restores the SSE, x87 FPU, and MMX states from the thread to memory.
Definition at line 103 of file process.cpp.
                               {
    // Ensure the state saving is enabled
    if (!CPU::s_xsave)
        return;
    // Restore the state
    asm volatile("fxrstor %0" : : "m" (m_sse_save_region));
}
References MaxOS::system::CPU::s_xsave.
Referenced by MaxOS::processes::Scheduler::schedule_next().
save_sse_state()
void Thread::save_sse_state ()
Saves the SSE, x87 FPU, and MMX states from memory to the thread.
Definition at line 90 of file process.cpp.
                            {
    // Ensure the state saving is enabled
    if (!CPU::s_xsave)
        return;
    // Save the state
    asm volatile("fxsave %0" : "=m" (m_sse_save_region));
}
References MaxOS::system::CPU::s_xsave.
Referenced by MaxOS::processes::Scheduler::schedule_next().
sleep()
cpu_status_t * Thread::sleep (size_t milliseconds)
Sleeps the thread for a certain amount of time (Yields the thread)
Parameters
milliseconds The amount of time to sleep for
Returns
The status of the CPU for the next thread to run
Definition at line 77 of file process.cpp.
                                               {
    // Update the state
    thread_state = ThreadState::SLEEPING;
    wakeup_time = Scheduler::system_scheduler()->ticks() + milliseconds;
    // Let other processes do stuff while this thread is sleeping
    return Scheduler::system_scheduler()->yield();
}
References MaxOS::processes::SLEEPING, MaxOS::processes::Scheduler::system_scheduler(), thread_state, and wakeup_time.
tss_pointer()
uintptr_t MaxOS::processes::Thread::tss_pointer () const [inline]
Definition at line 68 of file process.h.
{ return m_tss_stack_pointer; }
Referenced by MaxOS::processes::Scheduler::schedule_next().
Member Data Documentation
execution_state
system::cpu_status_t* MaxOS::processes::Thread::execution_state
Definition at line 62 of file process.h.
Referenced by MaxOS::processes::Scheduler::schedule_next(), Thread(), and MaxOS::processes::Scheduler::yield().
parent_pid
uint64_t MaxOS::processes::Thread::parent_pid
Definition at line 60 of file process.h.
Referenced by MaxOS::processes::Scheduler::add_thread(), MaxOS::processes::Scheduler::current_process(), and Thread().
thread_state
thread_state_t MaxOS::processes::Thread::thread_state
Definition at line 63 of file process.h.
Referenced by MaxOS::processes::Scheduler::schedule_next(), sleep(), and Thread().
ticks
size_t MaxOS::processes::Thread::ticks
Definition at line 65 of file process.h.
Referenced by MaxOS::processes::Scheduler::schedule(), and Thread().
tid
uint64_t MaxOS::processes::Thread::tid
Definition at line 59 of file process.h.
Referenced by Thread().
wakeup_time
size_t MaxOS::processes::Thread::wakeup_time
Definition at line 66 of file process.h.
Referenced by MaxOS::processes::Scheduler::schedule_next(), sleep(), and Thread().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/processes/process.h
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/process.cpp