MaxOS::filesystem::format::Fat32Directory Class Reference
Handles the directory operations on the FAT32 filesystem.
#include <fat32.h>
Public Member Functions
Fat32Directory (Fat32Volume *volume, lba_t cluster, const string &name)
~Fat32Directory ()
void read_from_disk () final
Read the directory from the disk.
File * create_file (const string &name) final
Create a new file in the directory.
void remove_file (const string &name) final
Delete a file from the subdirectory.
Directory * create_subdirectory (const string &name) final
Create a new directory in the directory.
void remove_subdirectory (const string &name) final
Remove a directory entry from the directory.
lba_t first_cluster () const
Public Member Functions inherited from MaxOS::filesystem::Directory
Directory ()
virtual ~Directory ()
common::Vector< File * > files ()
Get the files in the directory.
common::Vector< Directory * > subdirectories ()
Get the subdirectories in the directory.
File * open_file (const string &name)
Open a file in the directory.
Directory * open_subdirectory (const string &name)
Open a directory in the directory.
void rename_file (File *file, const string &new_name)
Rename a file in the directory.
virtual void rename_file (const string &old_name, const string &new_name)
Rename a file in the directory.
void rename_subdirectory (Directory *directory, const string &new_name)
Rename a subdirectory in the directory.
virtual void rename_subdirectory (const string &old_name, const string &new_name)
Rename a subdirectory in the directory.
string name ()
Get the name of the directory.
size_t size ()
Get the size of the directory.
Static Public Attributes
static const size_t MAX_NAME_LENGTH = 255
Protected Member Functions
void save_entry_to_disk (dir_entry_t *entry)
Writes an updated directory entry to the disk.
void update_entry_on_disk (int index)
Friends
class Fat32File
Additional Inherited Members
Protected Attributes inherited from MaxOS::filesystem::Directory
common::Vector< File * > m_files
common::Vector< Directory * > m_subdirectories
string m_name
Detailed Description
Handles the directory operations on the FAT32 filesystem.
Definition at line 228 of file fat32.h.
Constructor & Destructor Documentation
Fat32Directory()
Fat32Directory::Fat32Directory (Fat32Volume * volume, lba_t cluster, const string & name)
Definition at line 399 of file fat32.cpp.
: m_volume(volume),
  m_first_cluster(cluster)
{
    m_name = name;
}
References MaxOS::filesystem::Directory::m_name, and MaxOS::filesystem::Directory::name().
~Fat32Directory()
Fat32Directory::~Fat32Directory () [default]
Member Function Documentation
create_file()
File * Fat32Directory::create_file (const string & name) [final], [virtual]
Create a new file in the directory.
Parameters
name The name of the file to create
Returns
The new file object or null if it could not be created
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 862 of file fat32.cpp.
                                                    {
    // Check if the file already exists
    for (auto &file: m_files)
        if (file->name() == name)
            return nullptr;
    // Check if the name is too long
    if (name.length() > MAX_NAME_LENGTH)
        return nullptr;
    // Create the file
    auto file = new Fat32File(m_volume, this, create_entry(name, false), name);
    m_files.push_back(file);
    return file;
}
References Fat32File, MaxOS::String::length(), MaxOS::filesystem::Directory::m_files, MAX_NAME_LENGTH, and MaxOS::filesystem::Directory::name().
create_subdirectory()
Directory * Fat32Directory::create_subdirectory (const string & name) [final], [virtual]
Create a new directory in the directory.
Parameters
name The name of the directory to create
Returns
The new directory object or null if it could not be created
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 905 of file fat32.cpp.
                                                                 {
    // Check if the directory already exists
    for (auto &subdirectory: m_subdirectories)
        if (subdirectory->name() == name)
            return nullptr;
    // Check if the name is too long
    if (name.length() > MAX_NAME_LENGTH)
        return nullptr;
    // Create the directory
    auto entry = create_entry(name, true);
    uint32_t cluster = ((entry->first_cluster_high << 16) | entry->first_cluster_low);
    // Store the directory
    auto directory = new Fat32Directory(m_volume, cluster, name);
    m_subdirectories.push_back(directory);
    return directory;
}
References MaxOS::String::length(), MaxOS::filesystem::Directory::m_subdirectories, MAX_NAME_LENGTH, and MaxOS::filesystem::Directory::name().
first_cluster()
lba_t MaxOS::filesystem::format::Fat32Directory::first_cluster () const [inline]
Definition at line 271 of file fat32.h.
{ return m_first_cluster; }
Referenced by remove_file(), and remove_subdirectory().
read_from_disk()
void Fat32Directory::read_from_disk () [final], [virtual]
Read the directory from the disk.
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 801 of file fat32.cpp.
                                    {
    for (auto &file: m_files)
        delete file;
    m_files.clear();
    for (auto &directory: m_subdirectories)
        delete directory;
    m_subdirectories.clear();
    // Load the entries from the disk into memory
    read_all_entries();
    // Parse the entries
    string long_name = "";
    for (auto &entry: m_entries) {
        // Skip free entries and volume labels
        if (entry.name[0] == (uint8_t) DirectoryEntryType::FREE
            || entry.attributes == (uint8_t) DirectoryEntryAttributes::FREE
            || entry.attributes == (uint8_t) DirectoryEntryAttributes::VOLUME_ID)
            continue;
        // Extract the long name
        if (entry.attributes == (uint8_t) DirectoryEntryAttributes::LONG_NAME) {
            long_name = parse_long_filename((long_file_name_entry_t *) &entry, long_name);
            continue;
        }
        bool is_directory = entry.attributes == (uint8_t) DirectoryEntryAttributes::DIRECTORY;
        // Get the name of the entry
        string name = long_name;
        if (long_name == "") {
            name = string(entry.name, 8);
            // Add the extension
            if (!is_directory)
                name = name.strip() + "." + string(entry.extension, 3);
        }
        long_name = "";
        // Get the starting cluster
        uint32_t start_cluster = (entry.first_cluster_high << 16) | entry.first_cluster_low;
        // Store the file or directory
        if (is_directory)
            m_subdirectories.push_back(new Fat32Directory(m_volume, start_cluster, name.strip()));
        else
            m_files.push_back(new Fat32File(m_volume, this, &entry, name));
    }
}
References MaxOS::filesystem::format::DIRECTORY, Fat32File, MaxOS::filesystem::format::FREE, MaxOS::filesystem::format::LONG_NAME, MaxOS::filesystem::Directory::m_files, MaxOS::filesystem::Directory::m_subdirectories, MaxOS::filesystem::Directory::name(), MaxOS::String::strip(), and MaxOS::filesystem::format::VOLUME_ID.
remove_file()
void Fat32Directory::remove_file (const string & name) [final], [virtual]
Delete a file from the subdirectory.
Parameters
name The name of the file to delete
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 884 of file fat32.cpp.
                                                   {
    // Find the file if it exists
    for (auto &file: m_files)
        if (file->name() == name) {
            // Remove the file from the directory
            m_files.erase(file);
            remove_entry(((Fat32File *) file)->first_cluster(), name);
            // Delete the file reference
            delete file;
            return;
        }
}
References first_cluster(), MaxOS::filesystem::Directory::m_files, and MaxOS::filesystem::Directory::name().
remove_subdirectory()
void Fat32Directory::remove_subdirectory (const string & name) [final], [virtual]
Remove a directory entry from the directory.
Parameters
name The name of the entry to remove
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 931 of file fat32.cpp.
                                                           {
    // Find the directory if it exists
    for (auto &subdirectory: m_subdirectories) {
        if (subdirectory->name() != name)
            continue;
        // Remove all the files in the directory
        for (auto &file: subdirectory->files())
            subdirectory->remove_file(file->name());
        // Remove all the subdirectories in the directory
        for (auto &subdirectory: subdirectory->subdirectories())
            subdirectory->remove_subdirectory(subdirectory->name());
        // Remove the entry
        m_subdirectories.erase(subdirectory);
        remove_entry(((Fat32Directory *) subdirectory)->first_cluster(), name);
        // Delete the directory
        delete subdirectory;
        return;
    }
}
References first_cluster(), MaxOS::filesystem::Directory::m_subdirectories, and MaxOS::filesystem::Directory::name().
save_entry_to_disk()
void Fat32Directory::save_entry_to_disk (dir_entry_t * entry) [protected]
Writes an updated directory entry to the disk.
Parameters
entry The entry to write
Definition at line 566 of file fat32.cpp.
                                                             {
    int index = 0;
    for (auto &m_entry: m_entries) {
        if (&m_entry == entry)
            break;
        index++;
    }
    update_entry_on_disk(index);
}
References update_entry_on_disk().
Referenced by MaxOS::filesystem::format::Fat32File::write().
update_entry_on_disk()
void Fat32Directory::update_entry_on_disk (int index) [protected]
Definition at line 578 of file fat32.cpp.
                                                   {
    // Get the entry
    auto entry = m_entries[index];
    // Determine sector offset and in-sector byte offset
    uint32_t bytes_per_sector = m_volume->bpb.bytes_per_sector;
    uint32_t entry_offset = index * sizeof(dir_entry_t);
    uint32_t sector_offset = entry_offset / bytes_per_sector;
    uint32_t in_sector_offset = entry_offset % bytes_per_sector;
    // Find which cluster has the entry
    uint32_t cluster = m_first_cluster;
    for (uint32_t offset_remaining = entry_offset;
         offset_remaining >= bytes_per_sector; offset_remaining -= bytes_per_sector)
        cluster = m_volume->next_cluster(cluster);
    // Read the full sector into a buffer
    lba_t base_lba = m_volume->data_lba + (cluster - 2) * m_volume->bpb.sectors_per_cluster;
    buffer_t sector_buffer(bytes_per_sector, false);
    m_volume->disk->read(base_lba + sector_offset, &sector_buffer);
    // Update the entry in the buffer
    sector_buffer.copy_from(&entry, sizeof(dir_entry_t), in_sector_offset);
    m_volume->disk->write(base_lba + sector_offset, &sector_buffer);
}
References MaxOS::filesystem::format::Fat32Volume::bpb, bytes_per_sector, MaxOS::filesystem::format::Fat32Volume::data_lba, MaxOS::filesystem::format::Fat32Volume::disk, MaxOS::filesystem::format::Fat32Volume::next_cluster(), MaxOS::drivers::disk::Disk::read(), and MaxOS::drivers::disk::Disk::write().
Referenced by save_entry_to_disk().
Friends And Related Symbol Documentation
Fat32File
friend class Fat32File [friend]
Definition at line 230 of file fat32.h.
Referenced by create_file(), and read_from_disk().
Member Data Documentation
MAX_NAME_LENGTH
const size_t MaxOS::filesystem::format::Fat32Directory::MAX_NAME_LENGTH = 255 [static]
Definition at line 261 of file fat32.h.
Referenced by create_file(), and create_subdirectory().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/format/fat32.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/format/fat32.cpp