MaxOS::hardwarecommunication::PCIController Class Reference
Handles the selecting and loading of drivers for PCI devices.
#include <pci.h>
Public Member Functions
PCIController ()
Construct a new PCI Controller object.
void select_drivers (drivers::DriverSelectorEventHandler *handler) override
Select the driver for the device.
Static Public Member Functions
static drivers::Driver * get_driver (PCIDeviceDescriptor dev)
Get the driver for the device.
static void list_known_device (const PCIDeviceDescriptor &dev)
Print the vednor and device id of known devices, or "Unknown" + their ids if not known.
Detailed Description
Handles the selecting and loading of drivers for PCI devices.
Definition at line 88 of file pci.h.
Constructor & Destructor Documentation
PCIController()
PCIController::PCIController ()
Construct a new PCI Controller object.
Definition at line 99 of file pci.cpp.
: m_data_port(0xCFC),
  m_command_port(0xCF8)
{
}
Member Function Documentation
get_driver()
Driver * PCIController::get_driver (PCIDeviceDescriptor dev) [static]
Get the driver for the device.
Parameters
dev Device descriptor
Returns
Driver for the device, null pointer if there is no driver
Definition at line 251 of file pci.cpp.
                                                         {
    switch (dev.vendor_id) {
        case 0x1022: //AMD
        {
            switch (dev.device_id) {
                case 0x2000: {
                    return new AMD_AM79C973(&dev);
                }
                default:
                    break;
            }
            break;
        }
        case 0x8086: //Intel
        {
            switch (dev.device_id) {
                case 0x100E: //i217 (Ethernet Controller)
                {
                    return new IntelI217(&dev);
                }
                case 0x7010: // PIIX4 (IDE Controller)
                {
                    return new IntegratedDriveElectronicsController(&dev);
                }
                default:
                    break;
            }
            break;
        }//End Intel
    }
    //If there is no driver for the particular device, go into generic devices
    switch (dev.class_id) {
        case 0x03: //Graphics
        {
            switch (dev.subclass_id) {
                case 0x00: //VGA
                {
                    return new VideoGraphicsArray();
                }
            }
            break;
        }
    }
    return nullptr;
}
Referenced by select_drivers().
list_known_device()
void PCIController::list_known_device (const PCIDeviceDescriptor & dev) [static]
Print the vednor and device id of known devices, or "Unknown" + their ids if not known.
Parameters
dev The device to print
Definition at line 310 of file pci.cpp.
                                                                     {
    switch (dev.vendor_id) {
        case 0x1022: {
            // The vendor is AMD
            Logger::Out() << "AMD ";
            // List the device
            switch (dev.device_id) {
                default:
                    Logger::Out() << "0x%x" << dev.device_id;
                    break;
            }
            break;
        }
        case 0x106B: {
            // The vendor is Apple
            Logger::Out() << "Apple ";
            // List the device
            switch (dev.device_id) {
                case 0x003F: {
                    Logger::Out() << "KeyLargo/Intrepid USB";
                    break;
                }
                default:
                    Logger::Out() << "0x%x" << dev.device_id;
                    break;
            }
            break;
        }
        case 1234: {
            // The vendor is QEMU
            Logger::Out() << "QEMU ";
            // List the device
            switch (dev.device_id) {
                case 0x1111: {
                    Logger::Out() << "Virtual Video Controller";
                    break;
                }
            }
            break;
        }
        case 0x8086: {
            // The vendor is Intel
            Logger::Out() << "Intel ";
            // List the device
            switch (dev.device_id) {
                case 0x1237: {
                    Logger::Out() << "440FX";
                    break;
                }
                case 0x2415: {
                    Logger::Out() << "AC'97";
                    break;
                }
                case 0x7000: {
                    Logger::Out() << "PIIX3";
                    break;
                }
                case 0x7111: {
                    Logger::Out() << "PIIX3 ACPI";
                    break;
                }
                case 0x7113: {
                    Logger::Out() << "PIIX4 ACPI";
                    break;
                }
                default:
                    Logger::Out() << "0x%x" << dev.device_id;
                    break;
            }
            break;
        }
        case 0x80EE: {
            // The vendor is VirtualBox
            Logger::Out() << "VirtualBox ";
            // List the device
            switch (dev.device_id) {
                case 0xBEEF: {
                    Logger::Out() << "Graphics Adapter";
                    break;
                }
                case 0xCAFE: {
                    Logger::Out() << "Guest Service";
                    break;
                }
            }
            break;
        }
            // Unknown
        default:
            Logger::Out() << "Unknown (0x" << dev.vendor_id << ":0x" << dev.device_id << ")";
            break;
    }
}
References MaxOS::Logger::Out().
Referenced by select_drivers().
select_drivers()
void PCIController::select_drivers (drivers::DriverSelectorEventHandler * handler) [override], [virtual]
Select the driver for the device.
Parameters
handler device driver event manager
Reimplemented from MaxOS::drivers::DriverSelector.
Definition at line 176 of file pci.cpp.
                                                                      {
    for (int bus = 0; bus < 8; ++bus) {
        for (int device = 0; device < 32; ++device) {
            int num_functions = (device_has_functions(bus, device)) ? 8 : 1;
            for (int function = 0; function < num_functions; ++function) {
                // Get the device descriptor, if the vendor id is 0x0000 or 0xFFFF, the device is not present/ready
                PCIDeviceDescriptor device_descriptor = get_device_descriptor(bus, device,
                                                                              function);
                if (device_descriptor.vendor_id == 0x0000 || device_descriptor.vendor_id == 0x0001 ||
                    device_descriptor.vendor_id == 0xFFFF)
                    continue;
                // Get the earliest port number
                for (int bar_num = 5; bar_num >= 0; bar_num--) {
                    BaseAddressRegister bar = get_base_address_register(bus, device, function, bar_num);
                    if (bar.address && (bar.type == BARType::InputOutput))
                        device_descriptor.port_base = (uint64_t) bar.address;
                }
                Logger::DEBUG() << "DEVICE FOUND: " << device_descriptor.get_type() << " - ";
                // Select the driver and print information about the device
                Driver* driver = get_driver(device_descriptor);
                if (driver != nullptr) {
                    handler->on_driver_selected(driver);
                    Logger::Out() << driver->vendor_name() << " " << driver->device_name();
                } else {
                    list_known_device(device_descriptor);
                }
                Logger::Out() << "\n";
            }
        }
    }
}
References MaxOS::Logger::DEBUG(), get_driver(), list_known_device(), and MaxOS::Logger::Out().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/pci.h
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/pci.cpp