maxOS::system::ThreadManager Class Reference
Manages the scheduling of threads.
#include <multithreading.h>
Public Member Functions
ThreadManager ()
ThreadManager (system::GlobalDescriptorTable *gdt)
~ThreadManager ()
int create_thread (void entrypoint())
Add a thread to an empty place in the array.
CPUState * schedule (CPUState *cpu_state)
Schedules the next thread to be executed by checking its yieldsStatus.
bool terminate_thread (int tid)
Terminates a thread.
Detailed Description
Manages the scheduling of threads.
Definition at line 40 of file multithreading.h.
Constructor & Destructor Documentation
ThreadManager() [1/2]
ThreadManager::ThreadManager ()
Definition at line 40 of file multithreading.cpp.
{
}
ThreadManager() [2/2]
ThreadManager::ThreadManager (system::GlobalDescriptorTable * gdt)
Definition at line 44 of file multithreading.cpp.
{ m_gdt = gdt;
}
 ThreadManager()
ThreadManager::~ThreadManager ()
Definition at line 48 of file multithreading.cpp.
{
}
Member Function Documentation
create_thread()
int ThreadManager::create_thread (void entrypoint())
Add a thread to an empty place in the array.
Parameters
Thread thread to add
Returns
true if successfully added
false if error
Definition at line 59 of file multithreading.cpp.
{
    // Create a new thread
    Thread* new_thread = new Thread();
    new_thread -> init(m_gdt, entrypoint);
    new_thread -> m_tid = m_threads.size();
    new_thread -> m_cpu_state -> cs = m_gdt-> code_segment_selector();
    // Add the thread to the array
    m_threads.push_back(new_thread);
    return new_thread -> m_tid;
}
References cs.
schedule()
CPUState * ThreadManager::schedule (CPUState * cpu_state)
Schedules the next thread to be executed by checking its yieldsStatus.
Parameters
cpu_state state
Returns
CPUState* The state of the next thread to be executed
Definition at line 78 of file multithreading.cpp.
{
    // If the eax register is 37, terminate the thread
    if(cpu_state-> eax == 37)
      terminate_thread(m_current_thread);
    // If there are no threads to schedule, return the current state
    if (m_threads.size() <= 0 || m_threads[m_current_thread] == nullptr)
        return cpu_state;
    // Save the current state
    m_threads[m_current_thread]->m_cpu_state = cpu_state;
    // Switch to the next thread
    if(++m_current_thread >= m_threads.size())
      m_current_thread %= m_threads.size();
    // If this thread is yielded then skip it
    if(m_threads[m_current_thread]->m_yield_status){
      m_threads[m_current_thread]->m_yield_status = false;
        return schedule(cpu_state);
    }
    // Return the next thread's state
    return m_threads[m_current_thread]->m_cpu_state;
}
References eax, and terminate_thread().
Referenced by maxOS::hardwarecommunication::InterruptManager::handle_interrupt_request().
terminate_thread()
bool ThreadManager::terminate_thread (int tid)
Terminates a thread.
Parameters
tid thread id to terminate
Returns
true if successfully terminated thread or false if error
Definition at line 112 of file multithreading.cpp.
{
    // Check if the thread is actually running
    if (tid < 0 || tid >= m_threads.size())
        return false;
    // Delete the thread
    delete m_threads[tid];
    // Erase the thread from the array
    m_threads.erase(m_threads.begin() + tid);
    // TODO: Thread ID needs to be updated
    return true;
}
Referenced by schedule().
The documentation for this class was generated from the following files:
/home/runner/work/max-os/max-os/kernel/include/system/multithreading.h
/home/runner/work/max-os/max-os/kernel/src/system/multithreading.cpp