MaxOS::drivers::ethernet::EthernetDriverEventHandler Class Reference
Handles the events that are triggered by the Ethernet Driver.
#include <ethernet.h>
Public Member Functions
EthernetDriverEventHandler ()
__EVENT HANDLER___
common::Event< EthernetDriverEvents > * on_event (common::Event< EthernetDriverEvents > *event) override
Handle an event.
virtual void before_send (uint8_t *buffer, uint32_t size)
Handle before send event.
virtual void data_sent (uint8_t *buffer, uint32_t size)
Handle data sent event.
virtual bool data_received (uint8_t *buffer, uint32_t size)
Handle data received event.
Public Member Functions inherited from MaxOS::common::EventHandler< EthernetDriverEvents >
virtual Event< EthernetDriverEvents > * on_event (Event< EthernetDriverEvents > *event)
This function is called when an event is raised.
Detailed Description
Handles the events that are triggered by the Ethernet Driver.
Definition at line 73 of file ethernet.h.
Member Function Documentation
before_send()
void EthernetDriverEventHandler::before_send (uint8_t * buffer, uint32_t size) [virtual]
Handle before send event.
Parameters
buffer The buffer to handle
size The size of the buffer
Definition at line 39 of file ethernet.cpp.
                                                                           {
}
Referenced by on_event().
data_received()
bool EthernetDriverEventHandler::data_received (uint8_t * buffer, uint32_t size) [virtual]
Handle data received event.
Parameters
buffer The buffer to handle
size The size of the buffer
Returns
True if the data should be sent back, false otherwise
Reimplemented in MaxOS::net::EthernetFrameHandler.
Definition at line 29 of file ethernet.cpp.
                                                                             {
    return false;
}
Referenced by on_event().
data_sent()
void EthernetDriverEventHandler::data_sent (uint8_t * buffer, uint32_t size) [virtual]
Handle data sent event.
Parameters
buffer The buffer to handle
size The size of the buffer
Definition at line 48 of file ethernet.cpp.
                                                                         {
}
Referenced by on_event().
on_event()
Event< EthernetDriverEvents > * EthernetDriverEventHandler::on_event (common::Event< EthernetDriverEvents > * event) [override]
Handle an event.
Parameters
event The event to handle
Returns
The handled event
Definition at line 57 of file ethernet.cpp.
                                                                                                    {
    switch (event->type) {
        case EthernetDriverEvents::BEFORE_SEND:
            before_send(((BeforeSendEvent*) event)->buffer, ((BeforeSendEvent*) event)->size);
            break;
        case EthernetDriverEvents::DATA_SENT:
            data_sent(((DataSentEvent*) event)->buffer, ((DataSentEvent*) event)->size);
            break;
        case EthernetDriverEvents::DATA_RECEIVED:
            event->return_value.bool_value = data_received(((DataReceivedEvent*) event)->buffer,
                                                           ((DataReceivedEvent*) event)->size);
            break;
        default:
            break;
    }
    return event;
}
References before_send(), data_received(), and data_sent().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/ethernet/ethernet.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/ethernet/ethernet.cpp