MaxOS::drivers::disk::Disk Class Reference
Generic Disk, handles the reading and writing of data to the hard drive.
#include <disk.h>
Public Member Functions
void read (uint32_t sector, common::buffer_t *data_buffer)
Read data from the disk into a buffer (max capacity 512 bytes)
virtual void read (uint32_t sector, common::buffer_t *data_buffer, size_t amount)
Read data from the disk.
void write (uint32_t sector, const common::buffer_t *data)
Write data to the disk from a buffer (max capacity 512 bytes)
virtual void write (uint32_t sector, const common::buffer_t *data, size_t count)
Write data to the disk.
virtual void flush ()
Flush the disk cache.
void activate () override
Activate the disk driver.
string device_name () override
Get the device name.
string vendor_name () override
Get the vendor name.
Public Member Functions inherited from MaxOS::drivers::Driver
virtual void deactivate ()
deactivate the driver
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
Detailed Description
Generic Disk, handles the reading and writing of data to the hard drive.
Definition at line 28 of file disk.h.
Member Function Documentation
activate()
void Disk::activate () [override], [virtual]
Activate the disk driver.
Reimplemented from MaxOS::drivers::Driver.
Definition at line 78 of file disk.cpp.
                    {
    Driver::activate();
}
References MaxOS::drivers::Driver::activate().
device_name()
string Disk::device_name () [override], [virtual]
Get the device name.
Returns
The name of the device
Reimplemented from MaxOS::drivers::Driver.
Definition at line 87 of file disk.cpp.
                         {
    return "Disk";
}
flush()
void Disk::flush () [virtual]
Flush the disk cache.
This function is used to flush the disk cache to ensure that all data is written to the disk.
Reimplemented in MaxOS::drivers::disk::AdvancedTechnologyAttachment.
Definition at line 72 of file disk.cpp.
                 {
}
read() [1/2]
void Disk::read (uint32_t sector, common::buffer_t * data_buffer)
Read data from the disk into a buffer (max capacity 512 bytes)
Parameters
sector The sector to read from
data_buffer The buffer to read the data into
Definition at line 26 of file disk.cpp.
                                                            {
    size_t amount = (data_buffer->capacity() > 512) ? 512 : data_buffer->capacity();
    read(sector, data_buffer, amount);
}
References read().
Referenced by MaxOS::filesystem::format::ext2::Ext2Volume::Ext2Volume(), MaxOS::filesystem::format::Fat32Volume::Fat32Volume(), MaxOS::filesystem::partition::MSDOSPartition::mount_partitions(), MaxOS::filesystem::format::Fat32Volume::next_cluster(), MaxOS::filesystem::format::Fat32File::read(), read(), MaxOS::filesystem::format::ext2::Ext2Volume::read_block(), MaxOS::filesystem::format::Fat32Volume::set_next_cluster(), MaxOS::filesystem::format::Fat32Directory::update_entry_on_disk(), and MaxOS::filesystem::format::Fat32File::write().
read() [2/2]
void Disk::read (uint32_t sector, common::buffer_t * data_buffer, size_t amount) [virtual]
Read data from the disk.
Parameters
sector The sector to read from
data_buffer The buffer to read the data into
amount The amount of data to read
Reimplemented in MaxOS::drivers::disk::AdvancedTechnologyAttachment.
Definition at line 40 of file disk.cpp.
                                                                     {
}
vendor_name()
string Disk::vendor_name () [override], [virtual]
Get the vendor name.
Returns
The name of the vendor
Reimplemented from MaxOS::drivers::Driver.
Definition at line 96 of file disk.cpp.
                         {
    return "Generic";
}
write() [1/2]
void Disk::write (uint32_t sector, const common::buffer_t * data)
Write data to the disk from a buffer (max capacity 512 bytes)
Parameters
sector The sector to write to
data The buffer to write the data from
Definition at line 50 of file disk.cpp.
                                                            {
    size_t amount = (data->capacity() > 512) ? 512 : data->capacity();
    write(sector, data, amount);
}
References data, and write.
Referenced by MaxOS::filesystem::format::Fat32Volume::allocate_cluster(), MaxOS::filesystem::format::Fat32Volume::free_cluster(), MaxOS::filesystem::format::Fat32Volume::set_next_cluster(), MaxOS::filesystem::format::Fat32Directory::update_entry_on_disk(), MaxOS::filesystem::format::Fat32File::write(), and MaxOS::filesystem::format::ext2::Ext2Volume::write_block().
write() [2/2]
void Disk::write (uint32_t sector, const common::buffer_t * data, size_t count) [virtual]
Write data to the disk.
Parameters
sector The sector to write to
data The buffer to write the data into
count The amount of data to write
Reimplemented in MaxOS::drivers::disk::AdvancedTechnologyAttachment.
Definition at line 64 of file disk.cpp.
                                                                    {
}
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/disk/disk.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/disk/disk.cpp