MaxOS::runtime::UBSanHandler Class Reference
Handles undefined behaviour sanitizer.
#include <ubsan.h>
Public Member Functions
UBSanHandler ()
~UBSanHandler ()
Static Public Member Functions
static void handle (source_location_t location)
Handles the UBSan error (currently only printing the location and panicking)
static void print_type_mismatch (type_mismatch_info_t *info, uintptr_t ptr)
Prints the type mismatch error for UBSan.
static void print_type_mismatch_v1 (type_mismatch_info_v1_t *info, uintptr_t ptr)
Prints the type mismatch error for UBSan v1.
Detailed Description
Handles undefined behaviour sanitizer.
Definition at line 90 of file ubsan.h.
Constructor & Destructor Documentation
UBSanHandler()
UBSanHandler::UBSanHandler () [default]
~UBSanHandler()
UBSanHandler::~UBSanHandler () [default]
Member Function Documentation
handle()
void UBSanHandler::handle (source_location_t location) [static]
Handles the UBSan error (currently only printing the location and panicking)
Parameters
location The location of the error
Definition at line 20 of file ubsan.cpp.
                                                    {
    // Print the location
    ASSERT(false, "UBSAN ERROR AT %s:%d:%d\n", location.file, location.line, location.column);
}
References ASSERT, MaxOS::runtime::source_location::column, MaxOS::runtime::source_location::file, and MaxOS::runtime::source_location::line.
Referenced by __ubsan_handle_add_overflow(), __ubsan_handle_builtin_unreachable(), __ubsan_handle_divrem_overflow(), __ubsan_handle_load_invalid_value(), __ubsan_handle_missing_return(), __ubsan_handle_mul_overflow(), __ubsan_handle_negate_overflow(), __ubsan_handle_out_of_bounds(), __ubsan_handle_pointer_overflow(), __ubsan_handle_shift_out_of_bounds(), __ubsan_handle_sub_overflow(), __ubsan_handle_type_mismatch(), __ubsan_handle_type_mismatch_v1(), __ubsan_handle_vla_bound_not_positive(), print_type_mismatch(), and print_type_mismatch_v1().
print_type_mismatch()
void UBSanHandler::print_type_mismatch (type_mismatch_info_t * info, uintptr_t ptr) [static]
Prints the type mismatch error for UBSan.
Parameters
info The type mismatch info
ptr The pointer to the object
Definition at line 34 of file ubsan.cpp.
                                                                                {
    // Print the error
    Logger::DEBUG() << "UBSan: ";
    if (info->alignment != 0 && ubsan_aligned(ptr, info->alignment))
        Logger::Out() << "misaligned memory access\n";
    else
        Logger::Out() << Type_Check_Kinds[info->type_check_kind] << " address 0x" << ptr << " with insufficient space for an object of type " << info->type->name << "\n";
    // Print the location
    handle(info->location);
}
References MaxOS::runtime::type_mismatch_info::alignment, Logger::DEBUG(), handle(), MaxOS::runtime::type_mismatch_info::location, MaxOS::runtime::type_descriptor::name, Logger::Out(), MaxOS::runtime::type_mismatch_info::type, MaxOS::runtime::type_mismatch_info::type_check_kind, MaxOS::runtime::Type_Check_Kinds, and ubsan_aligned.
Referenced by __ubsan_handle_type_mismatch().
print_type_mismatch_v1()
void UBSanHandler::print_type_mismatch_v1 (type_mismatch_info_v1_t * info, uintptr_t ptr) [static]
Prints the type mismatch error for UBSan v1.
Parameters
info The type mismatch info
ptr The pointer to the object
Definition at line 53 of file ubsan.cpp.
                                                                                      {
    // Print the error
    Logger::DEBUG() << "UBSan: ";
    if (info->log_alignment != 0 && ubsan_aligned(ptr, (1 << (info->log_alignment))))
        Logger::Out() << "misaligned memory access\n";
    else
        Logger::Out() << Type_Check_Kinds[info->type_check_kind] << " address 0x" << ptr << " with insufficient space for an object of type " << info->type->name << "\n";
    // Print the location
    handle(info->location);
}
References Logger::DEBUG(), handle(), MaxOS::runtime::type_mismatch_info_v1::location, MaxOS::runtime::type_mismatch_info_v1::log_alignment, MaxOS::runtime::type_descriptor::name, Logger::Out(), MaxOS::runtime::type_mismatch_info_v1::type, MaxOS::runtime::type_mismatch_info_v1::type_check_kind, MaxOS::runtime::Type_Check_Kinds, and ubsan_aligned.
Referenced by __ubsan_handle_type_mismatch_v1().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/runtime/ubsan.h
/home/runner/work/MaxOS/MaxOS/kernel/src/runtime/ubsan.cpp