MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController Class Reference
#include <apic.h>
Public Member Functions
AdvancedProgrammableInterruptController (AdvancedConfigurationAndPowerInterface *acpi)
~AdvancedProgrammableInterruptController ()
LocalAPIC * local_apic () const
Get the local apic.
IOAPIC * io_apic () const
Get the io apic.
Protected Member Functions
void disable_pic ()
Disable the legacy PIC to prevent it from sending interrupts.
Protected Attributes
LocalAPIC * m_local_apic
IOAPIC * m_io_apic
Port8BitSlow m_pic_master_command_port
Port8BitSlow m_pic_master_data_port
Port8BitSlow m_pic_slave_command_port
Port8BitSlow m_pic_slave_data_port
Detailed Description
Definition at line 120 of file apic.h.
Constructor & Destructor Documentation
AdvancedProgrammableInterruptController()
AdvancedProgrammableInterruptController::AdvancedProgrammableInterruptController (AdvancedConfigurationAndPowerInterface * acpi)
Definition at line 332 of file apic.cpp.
: m_pic_master_command_port(0x20),
  m_pic_master_data_port(0x21),
  m_pic_slave_command_port(0xA0),
  m_pic_slave_data_port(0xA1)
{
    // Register this APIC
    Logger::INFO() << "Setting up APIC\n";
    InterruptManager::active_interrupt_manager()->set_apic(this);
    // Init the Local APIC
    Logger::DEBUG() << "Initialising Local APIC\n";
    m_local_apic = new LocalAPIC();
    // Disable the legacy mode PIC
    Logger::DEBUG() << "Disabling PIC\n";
    disable_pic();
    // Init the IO APIC
    Logger::DEBUG() << "Initialising IO APIC\n";
    m_io_apic = new IOAPIC(acpi);
}
References MaxOS::hardwarecommunication::InterruptManager::active_interrupt_manager(), Logger::DEBUG(), disable_pic(), Logger::INFO(), m_io_apic, m_local_apic, and MaxOS::hardwarecommunication::InterruptManager::set_apic().
~AdvancedProgrammableInterruptController()
AdvancedProgrammableInterruptController::~AdvancedProgrammableInterruptController ()
Definition at line 356 of file apic.cpp.
                                                                                  {
    // Free the memory
    delete m_local_apic;
    delete m_io_apic;
}
References m_io_apic, and m_local_apic.
Member Function Documentation
disable_pic()
void AdvancedProgrammableInterruptController::disable_pic () [protected]
Disable the legacy PIC to prevent it from sending interrupts.
Definition at line 366 of file apic.cpp.
                                                          {
    // Initialise the PIC
    m_pic_master_command_port.write(0x11);
    m_pic_slave_command_port.write(0x11);
    // Set the offsets
    m_pic_master_data_port.write(0x20);
    m_pic_slave_data_port.write(0x28);
    // Set the slave/master relationships
    m_pic_master_data_port.write(0x04);
    m_pic_slave_data_port.write(0x02);
    // Set the modes (8086/8086)
    m_pic_master_data_port.write(0x01);
    m_pic_slave_data_port.write(0x01);
    // Mask the interrupts
    m_pic_master_data_port.write(0xFF);
    m_pic_slave_data_port.write(0xFF);
}
References m_pic_master_command_port, m_pic_master_data_port, m_pic_slave_command_port, m_pic_slave_data_port, and MaxOS::hardwarecommunication::Port8BitSlow::write().
Referenced by AdvancedProgrammableInterruptController().
io_apic()
IOAPIC * AdvancedProgrammableInterruptController::io_apic () const
Get the io apic.
Returns
The io apic
Definition at line 404 of file apic.cpp.
                                                               {
    return m_io_apic;
}
References m_io_apic.
local_apic()
LocalAPIC * AdvancedProgrammableInterruptController::local_apic () const
Get the local apic.
Returns
The local apic
Definition at line 394 of file apic.cpp.
                                                                     {
    return m_local_apic;
}
References m_local_apic.
Referenced by MaxOS::drivers::clock::Clock::calibrate(), and MaxOS::hardwarecommunication::InterruptManager::handle_interrupt_request().
Member Data Documentation
m_io_apic
IOAPIC* MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController::m_io_apic [protected]
Definition at line 124 of file apic.h.
Referenced by AdvancedProgrammableInterruptController(), io_apic(), and ~AdvancedProgrammableInterruptController().
m_local_apic
LocalAPIC* MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController::m_local_apic [protected]
Definition at line 123 of file apic.h.
Referenced by AdvancedProgrammableInterruptController(), local_apic(), and ~AdvancedProgrammableInterruptController().
m_pic_master_command_port
Port8BitSlow MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController::m_pic_master_command_port [protected]
Definition at line 126 of file apic.h.
Referenced by disable_pic().
m_pic_master_data_port
Port8BitSlow MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController::m_pic_master_data_port [protected]
Definition at line 127 of file apic.h.
Referenced by disable_pic().
m_pic_slave_command_port
Port8BitSlow MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController::m_pic_slave_command_port [protected]
Definition at line 128 of file apic.h.
Referenced by disable_pic().
m_pic_slave_data_port
Port8BitSlow MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController::m_pic_slave_data_port [protected]
Definition at line 129 of file apic.h.
Referenced by disable_pic().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/apic.h
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/apic.cpp