MaxOS::processes::Elf64 Class Reference
Handles the loading and parsing of 64-bit ELF files.
#include <elf.h>
Public Member Functions
Elf64 (uintptr_t elf_header_address)
Constructor for the Elf64 class.
~Elf64 ()
Destructor for the Elf64 class.
void load ()
Loads the elf program into memory if a valid elf file.
bool is_valid () const
Checks if the elf file is valid for MaxOS runtime.
elf_64_header_t * header () const
Gets the header of the elf file.
elf_64_program_header_t * get_program_header (size_t index) const
Gets a program header from the elf file.
elf_64_section_header_t * get_section_header (size_t index) const
Gets a section header from the elf file.
Static Public Member Functions
static uint64_t to_vmm_flags (uint32_t type)
Converts elf flags to vmm flags.
Detailed Description
Handles the loading and parsing of 64-bit ELF files.
Definition at line 154 of file elf.h.
Constructor & Destructor Documentation
Elf64()
Elf64::Elf64 (uintptr_t elf_header_address)
Constructor for the Elf64 class.
Parameters
elf_header_address The address of the elf header, this must be mapped to memory before uses
Definition at line 19 of file elf.cpp.
: m_elf_header_address(elf_header_address)
{
}
~Elf64()
Elf64::~Elf64 () [default]
Destructor for the Elf64 class.
Member Function Documentation
get_program_header()
elf_64_program_header_t * Elf64::get_program_header (size_t index) const
Gets a program header from the elf file.
Parameters
index The index of the program header
Returns
The program header at that index or nullptr if out of bounds
Definition at line 58 of file elf.cpp.
                                                                     {
    // Check bounds
    if (index >= header()->program_header_count)
        return nullptr;
    // Find the program headers and return the item
    auto* program_headers = (elf_64_program_header_t*) (m_elf_header_address + header()->program_header_offset);
    return &program_headers[index];
}
References header(), and MaxOS::processes::elf_64_header_t::program_header_offset.
get_section_header()
elf_64_section_header_t * Elf64::get_section_header (size_t index) const
Gets a section header from the elf file.
Parameters
index The index of the section header
Returns
The section header at that index or nullptr if out of bounds
Definition at line 76 of file elf.cpp.
                                                                     {
    // Check bound
    if (index >= header()->section_header_count)
        return nullptr;
    // Find the section headers and return the item
    auto* section_headers = (elf_64_section_header_t*) (m_elf_header_address + header()->section_header_offset);
    return &section_headers[index];
}
References header(), and MaxOS::processes::elf_64_header_t::section_header_offset.
header()
elf_64_header_t * Elf64::header () const
Gets the header of the elf file.
Returns
The header of the elf file
Definition at line 47 of file elf.cpp.
                                     {
    return (elf_64_header_t*) m_elf_header_address;
}
Referenced by get_program_header(), get_section_header(), and is_valid().
is_valid()
bool Elf64::is_valid () const
Checks if the elf file is valid for MaxOS runtime.
Definition at line 91 of file elf.cpp.
                           {
    // Validate the magic number
    for (size_t i = 0; i < 4; i++)
        if (header()->identification[i] != elf_magic[i])
            return false;
    // Check if the elf is 64 bit
    if (header()->identification[(int) ElfIdentification::Class] != (int) ElfClass::Bits64)
        return false;
    // Check if the elf is little endian
    if (header()->identification[(int) ElfIdentification::Data] != (int) ElfData::LittleEndian)
        return false;
    // Check if the elf is version 1
    if (header()->identification[(int) ElfIdentification::Version] != (int) ElfVersion::Current)
        return false;
    // Check if the elf is for the MaxOS platform
    // if(header() -> identification[OSABI] != MaxOSABI)
    // return false; TODO: Would be nice to have an OS ABI
    // Check if the elf is executable
    if (header()->type != (int) ElfType::Executable)
        return false;
    // Check if the elf is for the x86_64 platform
    if (header()->machine != (int) ElfMachine::x86_64)
        return false;
    // LGTM
    return true;
}
References MaxOS::processes::Bits64, MaxOS::processes::Class, MaxOS::processes::Current, MaxOS::processes::Data, MaxOS::processes::Executable, header(), MaxOS::processes::LittleEndian, type, MaxOS::processes::Version, and MaxOS::processes::x86_64.
Referenced by load().
load()
void Elf64::load ()
Loads the elf program into memory if a valid elf file.
Definition at line 32 of file elf.cpp.
                 {
    //TODO: error handling when the syscall for this is implemented
    if (!is_valid())
        return;
    load_program_headers();
}
References is_valid().
to_vmm_flags()
uint64_t Elf64::to_vmm_flags (uint32_t type) [static]
Converts elf flags to vmm flags.
Parameters
type The elf flags of the program header
Returns
The vmm flags
Definition at line 164 of file elf.cpp.
                                          {
    // Conversion
    // ELF | VMM
    // 0x0 | Executable
    // 0x1 | Write
    // 0x2 | Read
    uint64_t flags = Present | User | NoExecute;
    // Enable write
    if (type & ElfWrite)
        flags |= Write;
    // Disable no execute
    if (type & ElfExecute)
        flags &= ~NoExecute;
    return flags;
}
References MaxOS::processes::ElfExecute, MaxOS::processes::ElfWrite, flags, MaxOS::memory::NoExecute, MaxOS::memory::Present, type, MaxOS::memory::User, and MaxOS::memory::Write.
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/processes/elf.h
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/elf.cpp