Logger Class Reference
A class that handles logging messages to the console and files.
#include <logger.h>
Public Member Functions
Logger ()
~Logger ()
void add_log_writer (OutputStream *log_writer)
Adds an output stream to the logger.
void disable_log_writer (OutputStream *log_writer)
Removes an output stream from the logger.
void set_log_level (LogLevel log_level)
Sets the log level of the logger.
void write_char (char c) final
Writes a character to the logger.
void printf (const char *format,...)
Prints a formatted string to the logger.
Logger & operator<< (LogLevel log_level)
Sets the log level of the logger.
Public Member Functions inherited from MaxOS::common::OutputStream
OutputStream ()
~OutputStream ()
virtual void lineFeed ()
Writes a newline to the output stream.
virtual void carriageReturn ()
Writes a carriage return to the output stream.
virtual void clear ()
Clears the output stream.
void write (string string_to_write) override
Writes a string to the output stream.
void write (const char *string_to_write)
Writes a string to the output stream.
virtual void write_int (int int_to_write)
Writes an integer to the output stream.
virtual void write_hex (uint64_t hex_to_write)
Writes a hex to the output stream.
OutputStream & operator<< (string string_to_write) override
Writes a string to the output stream.
OutputStream & operator<< (const char *string_to_write)
Writes a string to the output stream.
OutputStream & operator<< (int int_to_write)
Writes a integer to the output stream.
OutputStream & operator<< (uint64_t hex_to_write)
Writes a hexadecimal to the output stream.
OutputStream & operator<< (char char_to_write)
Writes a character to the output stream.
Public Member Functions inherited from MaxOS::common::GenericOutputStream< string >
GenericOutputStream ()
__________________________________________Templates__________________________________________________///
~GenericOutputStream ()
Destructor of the GenericOutputStream class.
void on_stream_read (string) override
Writes the date that was read from the input stream to the output stream.
void on_end_of_stream (GenericInputStream< string > *) override
Close the stream and remove it from the list of streams when the end of the stream is reached.
virtual void write (string)
write an element to the stream.
virtual void close ()
Close the stream.
virtual GenericOutputStream< string > & operator<< (string)
Overload the << operator to write an element to the stream.
Public Member Functions inherited from MaxOS::common::InputStreamProcessor< Type, ProcessorType >
InputStreamProcessor ()
InputStreamProcessor (InputStreamEventHandler< ProcessorType > *generic_stream_event_handler)
~InputStreamProcessor ()
void on_end_of_stream (GenericInputStream< Type > *stream) override
Public Member Functions inherited from MaxOS::common::InputStreamEventHandler< Type >
InputStreamEventHandler ()
_______________________________________________TEMPLATES_________________________________________________________________///
~InputStreamEventHandler ()
Public Member Functions inherited from MaxOS::common::GenericInputStream< ProcessorType >
GenericInputStream ()
GenericInputStream (InputStreamEventHandler< ProcessorType > *)
~GenericInputStream ()
void connect_input_stream_event_handler (InputStreamEventHandler< ProcessorType > *)
void disconnect_input_stream_event_handler (InputStreamEventHandler< ProcessorType > *)
Static Public Member Functions
static void ASSERT (bool condition, const char *message,...)
Puts the system into a panic state if the condition is false, printing the message first.
static Logger * active_logger ()
Gets the active logger (to be used to modify the logger)
static Logger & Out ()
Gets the active logger.
static Logger HEADER ()
Gets active logger set to task level.
static Logger INFO ()
Gets active logger set to info level.
static Logger DEBUG ()
Gets active logger set to DEBUG level.
static Logger WARNING ()
Gets active logger set to WARNING level.
static Logger ERROR ()
Gets active logger set to ERROR level.
Additional Inherited Members
Protected Attributes inherited from MaxOS::common::InputStreamEventHandler< Type >
common::Vector< GenericInputStream< Type > * > m_generic_input_streams
Protected Attributes inherited from MaxOS::common::GenericInputStream< ProcessorType >
common::Vector< InputStreamEventHandler< ProcessorType > * > m_input_stream_event_handlers
Detailed Description
A class that handles logging messages to the console and files.
Definition at line 31 of file logger.h.
Constructor & Destructor Documentation
Logger()
Logger::Logger ()
Definition at line 14 of file logger.cpp.
: m_log_writers()
{
    s_active_logger = this;
    // The following line is generated automatically by the MaxOS build system.
    s_progress_total = 22;
}
~Logger()
Logger::~Logger ()
Definition at line 26 of file logger.cpp.
                {
}
Member Function Documentation
active_logger()
Logger * Logger::active_logger () [static]
Gets the active logger (to be used to modify the logger)
Returns
The active logger
Definition at line 203 of file logger.cpp.
                              {
    return s_active_logger;
}
Referenced by MaxOS::drivers::console::VESABootConsole::finish(), Out(), and MaxOS::drivers::console::VESABootConsole::VESABootConsole().
add_log_writer()
void Logger::add_log_writer (OutputStream * log_writer)
Adds an output stream to the logger.
Parameters
output_stream The output stream to add
Definition at line 36 of file logger.cpp.
                                                    {
    // If the list is not empty
    if (m_log_writer_count >= m_max_log_writers)
        return;
    // Add the output stream to the list
    m_log_writers[m_log_writer_count] = log_writer;
    m_log_writers_enabled[m_log_writer_count] = true;
    m_log_writer_count++;
    // Print the setup info
    *this << LogLevel::INFO << "Logger setup: " << m_log_writer_count << "\n";
    *this << LogLevel::HEADER << "MaxOS v" << VERSION_STRING << " [ build " << BUILD_NUMBER << " ]\n";
}
References HEADER, and INFO.
Referenced by MaxOS::drivers::SerialConsole::SerialConsole().
ASSERT()
void Logger::ASSERT (bool condition, const char * message, ...) [static]
Puts the system into a panic state if the condition is false, printing the message first.
Parameters
condition The condition to check if is met
message The message to print if the condition fails
Definition at line 259 of file logger.cpp.
                                                            {
    // If the condition is met then everything is ok
    if (condition)
        return;
    // Print the message
    s_active_logger->set_log_level(LogLevel::ERROR);
    s_active_logger->printf(message);
    // Hang the system
    system::CPU::PANIC("Check previous logs for more information");
}
References ERROR, and MaxOS::system::CPU::PANIC().
DEBUG()
Logger Logger::DEBUG () [static]
Gets active logger set to DEBUG level.
Returns
The debug logger
Definition at line 168 of file logger.cpp.
                     {
    s_active_logger->set_log_level(LogLevel::DEBUG);
    return Out();
}
References DEBUG, and Out().
Referenced by __ubsan_handle_add_overflow(), __ubsan_handle_builtin_unreachable(), __ubsan_handle_divrem_overflow(), __ubsan_handle_load_invalid_value(), __ubsan_handle_missing_return(), __ubsan_handle_mul_overflow(), __ubsan_handle_negate_overflow(), __ubsan_handle_out_of_bounds(), __ubsan_handle_pointer_overflow(), __ubsan_handle_shift_out_of_bounds(), __ubsan_handle_sub_overflow(), __ubsan_handle_vla_bound_not_positive(), MaxOS::processes::Scheduler::add_process(), MaxOS::processes::Scheduler::add_thread(), MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::AdvancedConfigurationAndPowerInterface(), MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController::AdvancedProgrammableInterruptController(), MaxOS::drivers::clock::Clock::calibrate(), MaxOS::system::CPU::check_nx(), MaxOS::system::GlobalDescriptorTable::GlobalDescriptorTable(), MaxOS::system::CPU::init_sse(), MaxOS::system::CPU::init_tss(), MaxOS::drivers::disk::IntegratedDriveElectronicsController::initialise(), MaxOS::hardwarecommunication::IOAPIC::IOAPIC(), MaxOS::processes::Scheduler::load_multiboot_elfs(), MaxOS::hardwarecommunication::LocalAPIC::LocalAPIC(), MaxOS::filesystem::partition::MSDOSPartition::mount_partitions(), MaxOS::system::Multiboot::Multiboot(), MaxOS::memory::PhysicalMemoryManager::PhysicalMemoryManager(), MaxOS::runtime::UBSanHandler::print_type_mismatch(), MaxOS::runtime::UBSanHandler::print_type_mismatch_v1(), MaxOS::memory::PhysicalMemoryManager::reserve(), MaxOS::memory::PhysicalMemoryManager::reserve(), MaxOS::memory::PhysicalMemoryManager::reserve_kernel_regions(), MaxOS::hardwarecommunication::PeripheralComponentInterconnectController::select_drivers(), MaxOS::drivers::clock::PIT::ticks_per_ms(), MaxOS::drivers::video::VideoElectronicsStandardsAssociation::VideoElectronicsStandardsAssociation(), MaxOS::memory::VirtualMemoryManager::VirtualMemoryManager(), and MaxOS::processes::Process::~Process().
disable_log_writer()
void Logger::disable_log_writer (OutputStream * log_writer)
Removes an output stream from the logger.
Parameters
output_stream The output stream to remove
Definition at line 58 of file logger.cpp.
                                                        {
    // If the list is empty
    if (m_log_writer_count == 0)
        return;
    // Find the output stream in the list
    for (int i = 0; i < m_log_writer_count; i++)
        if (m_log_writers[i] == log_writer)
            m_log_writers_enabled[i] = false;
}
ERROR()
Logger Logger::ERROR () [static]
Gets active logger set to ERROR level.
Returns
The error logger
Definition at line 191 of file logger.cpp.
                     {
    s_active_logger->set_log_level(LogLevel::ERROR);
    return Out();
}
References ERROR, and Out().
Referenced by MaxOS::filesystem::format::Fat32Volume::Fat32Volume(), MaxOS::system::SyscallManager::handle_interrupt(), MaxOS::hardwarecommunication::InterruptManager::HandleInterrupt(), MaxOS::system::CPU::PANIC(), MaxOS::system::CPU::prepare_for_panic(), MaxOS::system::CPU::print_registers(), and MaxOS::system::CPU::stack_trace().
HEADER()
Logger Logger::HEADER () [static]
Gets active logger set to task level.
Returns
The task logger
Definition at line 145 of file logger.cpp.
                      {
    s_active_logger->set_log_level(LogLevel::HEADER);
    return Out();
}
References HEADER, and Out().
Referenced by MaxOS::drivers::console::VESABootConsole::finish(), and kernel_main().
INFO()
Logger Logger::INFO () [static]
Gets active logger set to info level.
Returns
The info logger
Definition at line 157 of file logger.cpp.
                    {
    s_active_logger->set_log_level(LogLevel::INFO);
    return Out();
}
References INFO, and Out().
Referenced by MaxOS::hardwarecommunication::InterruptManager::activate(), MaxOS::drivers::DriverManager::activate_drivers(), MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::AdvancedConfigurationAndPowerInterface(), MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController::AdvancedProgrammableInterruptController(), MaxOS::drivers::clock::Clock::calibrate(), MaxOS::drivers::clock::Clock::Clock(), MaxOS::system::CPU::CPU(), MaxOS::drivers::DriverManager::DriverManager(), MaxOS::drivers::DriverManager::find_drivers(), MaxOS::system::GlobalDescriptorTable::GlobalDescriptorTable(), MaxOS::drivers::DriverManager::initialise_drivers(), MaxOS::hardwarecommunication::InterruptManager::InterruptManager(), kernel_main(), MaxOS::memory::PhysicalMemoryManager::PhysicalMemoryManager(), MaxOS::drivers::DriverManager::reset_devices(), MaxOS::processes::Scheduler::Scheduler(), MaxOS::system::SyscallManager::syscall_klog(), MaxOS::system::SyscallManager::SyscallManager(), MaxOS::drivers::console::VESABootConsole::VESABootConsole(), and MaxOS::drivers::video::VideoElectronicsStandardsAssociation::VideoElectronicsStandardsAssociation().
operator<<()
Logger & Logger::operator<< (LogLevel log_level)
Sets the log level of the logger.
Parameters
log_level The log level to set
Returns
This logger
Definition at line 279 of file logger.cpp.
                                             {
    set_log_level(log_level);
    return *this;
}
References set_log_level().
Out()
Logger & Logger::Out () [static]
Gets the active logger.
Returns
The active logger
Definition at line 136 of file logger.cpp.
                    {
    return *active_logger();
}
References active_logger().
Referenced by DEBUG(), ERROR(), HEADER(), INFO(), MaxOS::hardwarecommunication::PeripheralComponentInterconnectController::list_known_device(), MaxOS::filesystem::partition::MSDOSPartition::mount_partitions(), MaxOS::runtime::UBSanHandler::print_type_mismatch(), MaxOS::runtime::UBSanHandler::print_type_mismatch_v1(), MaxOS::hardwarecommunication::PeripheralComponentInterconnectController::select_drivers(), MaxOS::system::SyscallManager::syscall_klog(), and WARNING().
printf()
void Logger::printf (const char * format, ...)
Prints a formatted string to the logger.
Parameters
format The format string
... The arguments to format
Definition at line 213 of file logger.cpp.
                                           {
    // Create a pointer to the data
    va_list parameters;
    va_start(parameters, format);
    // Loop through the format string
    for (; *format != '\0'; format++) {
        // If it is not a %, print the character
        if (*format != '%') {
            write_char(*format);
            continue;
        }
        // Move to the next character
        format++;
        switch (*format) {
            case 'd': {
                // Print a decimal
                int number = va_arg (parameters, int);
                write_int(number);
                break;
            }
            case 'x': {
                // Print a hex
                uint64_t number = va_arg (parameters, uint64_t);
                write_hex(number);
                break;
            }
            case 's': {
                // Print a string
                char *str = va_arg (parameters, char*);
                write(str);
                break;
            }
        }
    }
}
References write, write_char(), MaxOS::common::OutputStream::write_hex(), and MaxOS::common::OutputStream::write_int().
set_log_level()
void Logger::set_log_level (LogLevel log_level)
Sets the log level of the logger.
Parameters
log_level The log level to set
Definition at line 75 of file logger.cpp.
                                             {
    // Set the log level
    m_log_level = log_level;
    // Update the progress bar
    if (log_level == LogLevel::INFO) {
        VESABootConsole::update_progress_bar((m_progress_current * 100) / s_progress_total);
        m_progress_current++;
    }
    // Print the header
    switch (log_level) {
        case LogLevel::HEADER:
            *this << ANSI_COLOURS[ANSIColour::FG_Blue] << "[ BOOT ] ";
            break;
        case LogLevel::INFO:
            *this << ANSI_COLOURS[ANSIColour::FG_Cyan] << "[ INFO ]" << ANSI_COLOURS[ANSIColour::FG_White] << " ";
            break;
        case LogLevel::DEBUG:
            *this << ANSI_COLOURS[ANSIColour::FG_Yellow] << "[ DEBUG ]" << ANSI_COLOURS[ANSIColour::Reset] << " ";
            break;
        case LogLevel::WARNING:
            *this << ANSI_COLOURS[ANSIColour::BG_Yellow] << ANSI_COLOURS[FG_White] << "[ WARNING ]"
                  << ANSI_COLOURS[ANSIColour::Reset] << " ";
            break;
        case LogLevel::ERROR:
            *this << ANSI_COLOURS[ANSIColour::BG_Red] << "[ ERROR ]" << ANSI_COLOURS[ANSIColour::Reset] << " ";
            break;
    }
}
References MaxOS::common::ANSI_COLOURS, DEBUG, ERROR, MaxOS::common::FG_White, HEADER, INFO, MaxOS::drivers::console::VESABootConsole::update_progress_bar(), and WARNING.
Referenced by operator<<().
WARNING()
Logger Logger::WARNING () [static]
Gets active logger set to WARNING level.
Returns
The warning logger
Definition at line 180 of file logger.cpp.
                       {
    s_active_logger->set_log_level(LogLevel::WARNING);
    return Out();
}
References Out(), and WARNING.
Referenced by MaxOS::drivers::ethernet::AMD_AM79C973::handle_interrupt(), MaxOS::hardwarecommunication::InterruptManager::handle_interrupt_request(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::identify(), MaxOS::hardwarecommunication::LocalAPIC::LocalAPIC(), MaxOS::filesystem::VirtualFileSystem::mount_filesystem(), MaxOS::filesystem::VirtualFileSystem::mount_filesystem(), MaxOS::filesystem::partition::MSDOSPartition::mount_partitions(), and MaxOS::filesystem::VirtualFileSystem::unmount_filesystem().
write_char()
void Logger::write_char (char c) [final], [virtual]
Writes a character to the logger.
Parameters
c The character to write
Reimplemented from MaxOS::common::OutputStream.
Definition at line 118 of file logger.cpp.
                              {
    // Ensure logging at this level is enabled
    if (m_log_level > s_max_log_level)
        return;
    // Write the character to all output streams
    for (int i = 0; i < m_log_writer_count; i++)
        if (m_log_writers_enabled[i] || m_log_level == LogLevel::ERROR)
            m_log_writers[i]->write_char(c);
}
References ERROR, and MaxOS::common::OutputStream::write_char().
Referenced by printf().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/common/logger.h
/home/runner/work/MaxOS/MaxOS/kernel/src/common/logger.cpp