MaxOS::hardwarecommunication::Port16Bit Class Reference
Handles 16 bit ports.
#include <port.h>
Public Member Functions
Port16Bit (uint16_t port_number)
Construct a new Port object for ports handling 16 bit read/writes.
virtual void write (uint16_t data)
write a word to the port
virtual uint16_t read ()
read a word from the port
Additional Inherited Members
Protected Member Functions inherited from MaxOS::hardwarecommunication::Port
Port (uint16_t port_number)
Construct a new Port object.
Protected Attributes inherited from MaxOS::hardwarecommunication::Port
uint16_t m_port_number
The port to write to / read from.
Detailed Description
Handles 16 bit ports.
Definition at line 57 of file port.h.
Constructor & Destructor Documentation
Port16Bit()
Port16Bit::Port16Bit (uint16_t port_number)
Construct a new Port object for ports handling 16 bit read/writes.
Parameters
port_number The IO port number
Definition at line 84 of file port.cpp.
: Port(port_number) {
}
Member Function Documentation
read()
uint16_t Port16Bit::read () [virtual]
read a word from the port
Returns
the word read
Definition at line 105 of file port.cpp.
                         {
    uint16_t result;
    asm volatile("inw %1, %0" : "=a" (result) : "Nd" (m_port_number));
    return result;
}
References MaxOS::hardwarecommunication::Port::m_port_number.
Referenced by MaxOS::drivers::ethernet::AMD_AM79C973::activate(), MaxOS::drivers::ethernet::AMD_AM79C973::AMD_AM79C973(), MaxOS::drivers::ethernet::AMD_AM79C973::handle_interrupt(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::identify(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::read(), and MaxOS::drivers::ethernet::AMD_AM79C973::reset().
write()
void Port16Bit::write (uint16_t data) [virtual]
write a word to the port
Parameters
data the word to write
Definition at line 95 of file port.cpp.
                                   {
    asm volatile("outw %0, %1" : : "a" (data), "Nd" (m_port_number));
}
References data, and MaxOS::hardwarecommunication::Port::m_port_number.
Referenced by MaxOS::drivers::ethernet::AMD_AM79C973::activate(), MaxOS::drivers::ethernet::AMD_AM79C973::AMD_AM79C973(), MaxOS::drivers::ethernet::AMD_AM79C973::DoSend(), MaxOS::drivers::ethernet::AMD_AM79C973::handle_interrupt(), MaxOS::drivers::ethernet::AMD_AM79C973::reset(), and MaxOS::drivers::disk::AdvancedTechnologyAttachment::write().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/port.h
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/port.cpp