MaxOS::net::TransmissionControlProtocolPayloadHandler Class Reference
#include <tcp.h>
Public Member Functions
TransmissionControlProtocolPayloadHandler ()
Handler///
~TransmissionControlProtocolPayloadHandler ()
common::Event< TransmissionControlProtocolPayloadHandlerEvents > * on_event (common::Event< TransmissionControlProtocolPayloadHandlerEvents > *event) override
virtual void handleTransmissionControlProtocolPayload (TransmissionControlProtocolSocket *socket, uint8_t *data, uint16_t size)
virtual void Connected (TransmissionControlProtocolSocket *socket)
virtual void Disconnected (TransmissionControlProtocolSocket *socket)
Public Member Functions inherited from MaxOS::common::EventHandler< TransmissionControlProtocolPayloadHandlerEvents >
EventHandler ()
~EventHandler ()
virtual Event< TransmissionControlProtocolPayloadHandlerEvents > * on_event (Event< TransmissionControlProtocolPayloadHandlerEvents > *event)
This function is called when an event is raised.
Detailed Description
Definition at line 115 of file tcp.h.
Constructor & Destructor Documentation
TransmissionControlProtocolPayloadHandler()
TransmissionControlProtocolPayloadHandler::TransmissionControlProtocolPayloadHandler () [default]
Handler///
~TransmissionControlProtocolPayloadHandler()
TransmissionControlProtocolPayloadHandler::~TransmissionControlProtocolPayloadHandler () [default]
Member Function Documentation
Connected()
void TransmissionControlProtocolPayloadHandler::Connected (TransmissionControlProtocolSocket * socket) [virtual]
Definition at line 26 of file tcp.cpp.
                                                                                            {
}
Referenced by on_event().
Disconnected()
void TransmissionControlProtocolPayloadHandler::Disconnected (TransmissionControlProtocolSocket * socket) [virtual]
Definition at line 30 of file tcp.cpp.
                                                                                               {
}
Referenced by on_event().
handleTransmissionControlProtocolPayload()
void TransmissionControlProtocolPayloadHandler::handleTransmissionControlProtocolPayload (TransmissionControlProtocolSocket * socket, uint8_t * data, uint16_t size) [virtual]
Definition at line 22 of file tcp.cpp.
                                                                                                                                               {
}
Referenced by on_event().
on_event()
Event< TransmissionControlProtocolPayloadHandlerEvents > * TransmissionControlProtocolPayloadHandler::on_event (common::Event< TransmissionControlProtocolPayloadHandlerEvents > * event) [override]
Definition at line 34 of file tcp.cpp.
                                                                                                                                                                         {
    switch (event -> type)
    {
      case TransmissionControlProtocolPayloadHandlerEvents::CONNECTED:
            Connected(((ConnectedEvent*)event) -> socket);
            break;
        case TransmissionControlProtocolPayloadHandlerEvents::DISCONNECTED:
            Disconnected(((DisconnectedEvent*)event) -> socket);
            break;
        case TransmissionControlProtocolPayloadHandlerEvents::DATA_RECEIVED:
            handleTransmissionControlProtocolPayload(((DataReceivedEvent*)event) -> socket, ((DataReceivedEvent*)event) -> data, ((DataReceivedEvent*)event) -> size);
            break;
    }
    return event;
}
References MaxOS::net::CONNECTED, Connected(), data, MaxOS::net::DATA_RECEIVED, MaxOS::net::DISCONNECTED, Disconnected(), handleTransmissionControlProtocolPayload(), size, and type.
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/net/tcp.h
/home/runner/work/MaxOS/MaxOS/kernel/src/net/tcp.cpp