MaxOS::filesystem::format::ext2::Ext2Directory Class Reference
Handles the directory operations on the ext2 filesystem.
#include <ext2.h>
Public Member Functions
Ext2Directory (Ext2Volume *volume, uint32_t inode, const string &name)
Construct a new Ext2 Directory object.
void read_from_disk () final
Read the directory from the inode on the disk.
File * create_file (const string &name) final
Create a new file in the directory.
void remove_file (const string &name) final
Delete a file from this directory.
void rename_file (const string &old_name, const string &new_name) final
Renames the file from the old name to the new name if it exists.
Directory * create_subdirectory (const string &name) final
Create a new directory in the directory.
void remove_subdirectory (const string &name) final
Remove a directory entry from the directory.
void rename_subdirectory (const string &old_name, const string &new_name) final
Renames the directory from the old name to the new name if it exists.
Public Member Functions inherited from MaxOS::filesystem::Directory
common::Vector< File * > files ()
Get the files in the directory.
common::Vector< Directory * > subdirectories ()
Get the subdirectories in the directory.
File * open_file (const string &name)
Open a file in the directory.
Directory * open_subdirectory (const string &name)
Open a directory in the directory.
void rename_file (File *file, const string &new_name)
Rename a file in the directory.
void rename_subdirectory (Directory *directory, const string &new_name)
Rename a subdirectory in the directory.
string name ()
Get the name of the directory.
size_t size ()
Get the size of the directory.
Additional Inherited Members
Protected Attributes inherited from MaxOS::filesystem::Directory
common::Vector< File * > m_files
The files in this directory.
common::Vector< Directory * > m_subdirectories
The subdirectories in this directory.
string m_name
The name of this directory.
Detailed Description
Handles the directory operations on the ext2 filesystem.
Definition at line 406 of file ext2.h.
Constructor & Destructor Documentation
Ext2Directory()
Ext2Directory::Ext2Directory (Ext2Volume * volume, uint32_t inode, const string & name)
Construct a new Ext2 Directory object.
Parameters
volume The volume the directory exists on
inode The inode number of the directory (will be used to setup the internal InodeHandler)
name The name of the directory
Definition at line 853 of file ext2.cpp.
: m_volume(volume),
  m_inode(m_volume, inode)
{
    m_name = name;
}
References MaxOS::filesystem::Directory::m_name, and MaxOS::filesystem::Directory::name().
Member Function Documentation
create_file()
File * Ext2Directory::create_file (const string & name) [final], [virtual]
Create a new file in the directory.
Parameters
name The name of the file to create
Returns
The new file object or null if it could not be created
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 1083 of file ext2.cpp.
                                                   {
    // Check if the file already exists
    for (auto &file: m_files)
        if (file->name() == name)
            return nullptr;
    // Create the file
    auto file = new Ext2File(m_volume, create_entry(name, 0, false).inode, name);
    m_files.push_back(file);
    return file;
}
References inode, MaxOS::filesystem::Directory::m_files, and MaxOS::filesystem::Directory::name().
create_subdirectory()
Directory * Ext2Directory::create_subdirectory (const string & name) [final], [virtual]
Create a new directory in the directory.
Parameters
name The name of the directory to create
Returns
The new directory object or null if it could not be created
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 1121 of file ext2.cpp.
                                                                {
    // Check if the directory already exists
    for (auto &subdirectory: m_subdirectories)
        if (subdirectory->name() == name)
            return nullptr;
    // Store the directory
    auto directory = new Ext2Directory(m_volume, create_entry(name, 0, true).inode, name);
    m_subdirectories.push_back(directory);
    // Create self & parent references
    directory->create_entry(".", directory->m_inode.inode_number, true);
    directory->create_entry("..", m_inode.inode_number, true);
    return directory;
}
References inode, MaxOS::filesystem::format::ext2::InodeHandler::inode_number, MaxOS::filesystem::Directory::m_subdirectories, and MaxOS::filesystem::Directory::name().
read_from_disk()
void Ext2Directory::read_from_disk () [final], [virtual]
Read the directory from the inode on the disk.
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 959 of file ext2.cpp.
                                   {
    m_volume->ext2_lock.lock();
    m_entries.clear();
    m_entry_names.clear();
    // Clear the old files & Directories
    for (auto &file: m_files)
        delete file;
    m_files.clear();
    for (auto &directory: m_subdirectories)
        delete directory;
    m_subdirectories.clear();
    // Read the direct blocks (cant use for(:))
    buffer_t buffer(m_volume->block_size);
    for (int i = 0; i < m_inode.block_cache.size(); ++i) {
        uint32_t block_pointer = m_inode.block_cache[i];
        // Invalid block
        if (block_pointer == 0)
            break;
        // Parse the block
        m_volume->read_block(block_pointer, &buffer);
        parse_block(&buffer);
    }
    m_volume->ext2_lock.unlock();
}
References MaxOS::filesystem::format::ext2::InodeHandler::block_cache, MaxOS::filesystem::format::ext2::Ext2Volume::block_size, MaxOS::common::Vector< Type >::clear(), MaxOS::filesystem::format::ext2::Ext2Volume::ext2_lock, MaxOS::common::Spinlock::lock(), MaxOS::filesystem::Directory::m_files, MaxOS::filesystem::Directory::m_subdirectories, MaxOS::filesystem::format::ext2::Ext2Volume::read_block(), MaxOS::common::Vector< Type >::size(), and MaxOS::common::Spinlock::unlock().
remove_file()
void Ext2Directory::remove_file (const string & name) [final], [virtual]
Delete a file from this directory.
Parameters
name The name of the file to delete
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 1101 of file ext2.cpp.
                                                  {
    remove_entry(name, false);
}
References MaxOS::filesystem::Directory::name().
remove_subdirectory()
void Ext2Directory::remove_subdirectory (const string & name) [final], [virtual]
Remove a directory entry from the directory.
Parameters
name The name of the entry to remove
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 1144 of file ext2.cpp.
                                                          {
    remove_entry(name, true);
}
References MaxOS::filesystem::Directory::name().
rename_file()
void Ext2Directory::rename_file (const string & old_name, const string & new_name) [final], [virtual]
Renames the file from the old name to the new name if it exists.
Parameters
old_name The current name of the file that is to be changed
new_name What the new name should be
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 1111 of file ext2.cpp.
                                                                              {
    rename_entry(old_name, new_name, false);
}
rename_subdirectory()
void Ext2Directory::rename_subdirectory (const string & old_name, const string & new_name) [final], [virtual]
Renames the directory from the old name to the new name if it exists.
Parameters
old_name The current name of the directory that is to be changed
new_name What the new name should be
Reimplemented from MaxOS::filesystem::Directory.
Definition at line 1154 of file ext2.cpp.
                                                                                      {
    rename_entry(old_name, new_name, true);
}
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/format/ext2.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/format/ext2.cpp