MaxOS::system::Multiboot Class Reference
#include <multiboot.h>
Public Member Functions
Multiboot (unsigned long address, unsigned long magic)
~Multiboot ()
multiboot_tag_framebuffer * framebuffer ()
multiboot_tag_basic_meminfo * basic_meminfo ()
multiboot_tag_string * bootloader_name ()
multiboot_tag_mmap * mmap ()
multiboot_tag_old_acpi * old_acpi ()
multiboot_tag_new_acpi * new_acpi ()
multiboot_tag * start_tag () const
bool is_reserved (multiboot_uint64_t address)
Check if an address is reserved by a multiboot module.
Public Attributes
unsigned long start_address
unsigned long end_address
Protected Attributes
multiboot_tag_framebuffer * m_framebuffer
multiboot_tag_basic_meminfo * m_basic_meminfo
multiboot_tag_string * m_bootloader_name
multiboot_tag_mmap * m_mmap
multiboot_tag_old_acpi * m_old_acpi
multiboot_tag_new_acpi * m_new_acpi
multiboot_tag_module * m_module
Detailed Description
Definition at line 420 of file multiboot.h.
Constructor & Destructor Documentation
Multiboot()
Multiboot::Multiboot (unsigned long address, unsigned long magic)
Definition at line 14 of file multiboot.cpp.
: start_address(address)
{
    // Confirm the bootloader
    ASSERT(magic == MULTIBOOT2_BOOTLOADER_MAGIC, "Multiboot2 Bootloader Not Detected");
    Logger::DEBUG() << "Multiboot2 Bootloader Detected at 0x" << (uint64_t) address << "\n";
    multiboot_tag* tag = start_tag();
    // Loop through the tags and load them
    while (true) {
        // Handle the tag
        switch (tag->type) {
            case MULTIBOOT_TAG_TYPE_END:
                end_address = (unsigned long) PhysicalMemoryManager::to_lower_region((uint64_t) tag);
                return;
            case MULTIBOOT_TAG_TYPE_FRAMEBUFFER:
                m_framebuffer = (multiboot_tag_framebuffer*) tag;
                break;
            case MULTIBOOT_TAG_TYPE_BASIC_MEMINFO:
                m_basic_meminfo = (multiboot_tag_basic_meminfo*) tag;
                break;
            case MULTIBOOT_TAG_TYPE_BOOT_LOADER_NAME:
                m_bootloader_name = (multiboot_tag_string*) tag;
                Logger::DEBUG() << "Bootloader: " << m_bootloader_name->string << "\n";
                break;
            case MULTIBOOT_TAG_TYPE_BOOTDEV:
                multiboot_tag_bootdev* bootdev;
                bootdev = (multiboot_tag_bootdev*) tag;
                Logger::DEBUG() << "Boot device: drive=0x" << (uint64_t) bootdev->biosdev << ", partition=0x" << (uint64_t) bootdev->part << "\n";
                break;
            case MULTIBOOT_TAG_TYPE_MMAP:
                // If there is not already a mmap tag, set it
                if (m_mmap == nullptr)
                    m_mmap = (multiboot_tag_mmap*) tag;
                break;
            case MULTIBOOT_TAG_TYPE_ACPI_OLD:
                m_old_acpi = (multiboot_tag_old_acpi*) tag;
                break;
            case MULTIBOOT_TAG_TYPE_ACPI_NEW:
                m_new_acpi = (multiboot_tag_new_acpi*) tag;
                break;
            case MULTIBOOT_TAG_TYPE_MODULE:
                multiboot_tag_module* module;
                module = (multiboot_tag_module*) tag;
                Logger::DEBUG() << "Module: start=0x" << (uint64_t) module->mod_start << ", end=0x" << (uint64_t) module->mod_end << ", cmdline=" << module->cmdline << "\n";
                m_module = module;
                break;
        }
        // Move to the next tag
        tag = (struct multiboot_tag*) ((multiboot_uint8_t*) tag + ((tag->size + 7) & ~7));
    }
}
References address, ASSERT, Logger::DEBUG(), end_address, m_basic_meminfo, m_bootloader_name, m_framebuffer, m_mmap, m_module, m_new_acpi, m_old_acpi, magic, MULTIBOOT2_BOOTLOADER_MAGIC, MULTIBOOT_TAG_TYPE_ACPI_NEW, MULTIBOOT_TAG_TYPE_ACPI_OLD, MULTIBOOT_TAG_TYPE_BASIC_MEMINFO, MULTIBOOT_TAG_TYPE_BOOT_LOADER_NAME, MULTIBOOT_TAG_TYPE_BOOTDEV, MULTIBOOT_TAG_TYPE_END, MULTIBOOT_TAG_TYPE_FRAMEBUFFER, MULTIBOOT_TAG_TYPE_MMAP, MULTIBOOT_TAG_TYPE_MODULE, start_tag(), multiboot_tag_string::string, and MaxOS::memory::PhysicalMemoryManager::to_lower_region().
~Multiboot()
Multiboot::~Multiboot () [default]
Member Function Documentation
basic_meminfo()
multiboot_tag_basic_meminfo * Multiboot::basic_meminfo ()
Definition at line 91 of file multiboot.cpp.
                                                      {
    return m_basic_meminfo;
}
References m_basic_meminfo.
bootloader_name()
multiboot_tag_string * Multiboot::bootloader_name ()
Definition at line 96 of file multiboot.cpp.
                                                 {
    return m_bootloader_name;
}
References m_bootloader_name.
framebuffer()
multiboot_tag_framebuffer * Multiboot::framebuffer ()
Definition at line 86 of file multiboot.cpp.
                                                  {
    return m_framebuffer;
}
References m_framebuffer.
is_reserved()
bool Multiboot::is_reserved (multiboot_uint64_t address)
Check if an address is reserved by a multiboot module.
Parameters
address The address to check
Returns
True if the address is reserved
Definition at line 122 of file multiboot.cpp.
                                                      {
    // Loop through the tags checking if the address is reserved
    for (multiboot_tag* tag = start_tag(); tag->type != MULTIBOOT_TAG_TYPE_END; tag = (struct multiboot_tag*) ((multiboot_uint8_t*) tag + ((tag->size + 7) & ~7))) {
        // Check if the tag is a module or mmap
        if (tag->type != MULTIBOOT_TAG_TYPE_MODULE && tag->type != MULTIBOOT_TAG_TYPE_MMAP)
            continue;
        // Get the module tag
        auto* module = (struct multiboot_tag_module*) tag;
        // Check if the address is within the module
        if (address >= module->mod_start && address < module->mod_end)
            return true;
    }
    // Not part of multiboot
    return false;
}
References address, MULTIBOOT_TAG_TYPE_END, MULTIBOOT_TAG_TYPE_MMAP, MULTIBOOT_TAG_TYPE_MODULE, and start_tag().
Referenced by MaxOS::memory::PhysicalMemoryManager::is_anonymous_available().
mmap()
multiboot_tag_mmap * Multiboot::mmap ()
Definition at line 101 of file multiboot.cpp.
                                    {
    return m_mmap;
}
References m_mmap.
new_acpi()
multiboot_tag_new_acpi * Multiboot::new_acpi ()
Definition at line 112 of file multiboot.cpp.
                                            {
    return m_new_acpi;
}
References m_new_acpi.
old_acpi()
multiboot_tag_old_acpi * Multiboot::old_acpi ()
Definition at line 106 of file multiboot.cpp.
                                            {
    return m_old_acpi;
}
References m_old_acpi.
start_tag()
multiboot_tag * Multiboot::start_tag () const
Get the start tag of the multiboot information (useful for iterating through the tags)
Returns
The start tag
Definition at line 150 of file multiboot.cpp.
                                          {
    return (multiboot_tag*) (start_address + PhysicalMemoryManager::s_higher_half_kernel_offset + 8);
}
References MaxOS::memory::PhysicalMemoryManager::s_higher_half_kernel_offset, and start_address.
Referenced by is_reserved(), MaxOS::processes::Scheduler::load_multiboot_elfs(), and Multiboot().
Member Data Documentation
end_address
unsigned long MaxOS::system::Multiboot::end_address
Definition at line 442 of file multiboot.h.
Referenced by Multiboot().
m_basic_meminfo
multiboot_tag_basic_meminfo* MaxOS::system::Multiboot::m_basic_meminfo [protected]
Definition at line 423 of file multiboot.h.
Referenced by basic_meminfo(), and Multiboot().
m_bootloader_name
multiboot_tag_string* MaxOS::system::Multiboot::m_bootloader_name [protected]
Definition at line 424 of file multiboot.h.
Referenced by bootloader_name(), and Multiboot().
m_framebuffer
multiboot_tag_framebuffer* MaxOS::system::Multiboot::m_framebuffer [protected]
Definition at line 422 of file multiboot.h.
Referenced by framebuffer(), and Multiboot().
m_mmap
multiboot_tag_mmap* MaxOS::system::Multiboot::m_mmap [protected]
Definition at line 425 of file multiboot.h.
Referenced by mmap(), and Multiboot().
m_module
multiboot_tag_module* MaxOS::system::Multiboot::m_module [protected]
Definition at line 428 of file multiboot.h.
Referenced by Multiboot().
m_new_acpi
multiboot_tag_new_acpi* MaxOS::system::Multiboot::m_new_acpi [protected]
Definition at line 427 of file multiboot.h.
Referenced by Multiboot(), and new_acpi().
m_old_acpi
multiboot_tag_old_acpi* MaxOS::system::Multiboot::m_old_acpi [protected]
Definition at line 426 of file multiboot.h.
Referenced by Multiboot(), and old_acpi().
start_address
unsigned long MaxOS::system::Multiboot::start_address
Definition at line 441 of file multiboot.h.
Referenced by MaxOS::memory::PhysicalMemoryManager::is_anonymous_available(), and start_tag().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/system/multiboot.h
/home/runner/work/MaxOS/MaxOS/kernel/src/system/multiboot.cpp