MaxOS::drivers::peripherals::KeyboardEventHandler Class Reference
Handles the events that are triggered by the Keyboard Driver.
#include <keyboard.h>
Public Member Functions
KeyboardEventHandler ()
~KeyboardEventHandler ()
common::Event< KeyboardEvents > * on_event (common::Event< KeyboardEvents > *) override
Handle the trigger of an event.
virtual void on_key_down (KeyCode, KeyboardState)
Handle the key down event.
virtual void on_key_up (KeyCode, KeyboardState)
Handle the key up event.
Public Member Functions inherited from MaxOS::common::EventHandler< KeyboardEvents >
EventHandler ()
~EventHandler ()
virtual Event< KeyboardEvents > * on_event (Event< KeyboardEvents > *event)
This function is called when an event is raised.
Detailed Description
Handles the events that are triggered by the Keyboard Driver.
Definition at line 259 of file keyboard.h.
Constructor & Destructor Documentation
KeyboardEventHandler()
KeyboardEventHandler::KeyboardEventHandler () [default]
~KeyboardEventHandler()
KeyboardEventHandler::~KeyboardEventHandler () [default]
Member Function Documentation
on_event()
Event< KeyboardEvents > * KeyboardEventHandler::on_event (common::Event< KeyboardEvents > * event) [override]
Handle the trigger of an event.
Parameters
event The event to handle
Returns
The event that was passed with the data modified
Definition at line 41 of file keyboard.cpp.
                                                                                  {
    switch (event->type) {
        case KeyboardEvents::KEYDOWN:
            this->on_key_down(((KeyDownEvent *) event)->key_code, ((KeyDownEvent *) event)->keyboard_state);
            break;
        case KeyboardEvents::KEYUP:
            this->on_key_up(((KeyUpEvent *) event)->key_code, ((KeyUpEvent *) event)->keyboard_state);
            break;
        default:
            break;
    }
    return event;
}
References MaxOS::drivers::peripherals::KEYDOWN, MaxOS::drivers::peripherals::KEYUP, on_key_down(), and on_key_up().
on_key_down()
void KeyboardEventHandler::on_key_down (KeyCode , KeyboardState) [virtual]
Handle the key down event.
Parameters
key_down_code The keycode of the key that was pressed
key_down_state The state of the keyboard when the key was pressed
Reimplemented in MaxOS::gui::Desktop, and MaxOS::gui::widgets::InputBox.
Definition at line 23 of file keyboard.cpp.
                                                             {
}
Referenced by on_event(), and MaxOS::gui::Desktop::on_key_down().
on_key_up()
void KeyboardEventHandler::on_key_up (KeyCode , KeyboardState) [virtual]
Handle the key up event.
Parameters
key_up_code The keycode of the key that was released
key_up_state The state of the keyboard when the key was released
Reimplemented in MaxOS::gui::Desktop.
Definition at line 32 of file keyboard.cpp.
                                                           {
}
Referenced by on_event(), and MaxOS::gui::Desktop::on_key_up().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/peripherals/keyboard.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/peripherals/keyboard.cpp