MaxOS::drivers::console::VESABootConsole Class Reference
Driver for the VESA Console during boot, handles the printing of characters and strings to the screen using VESA protocol.
#include <vesaboot.h>
Public Member Functions
VESABootConsole (common::GraphicsContext *)
~VESABootConsole ()
uint16_t width () final
Gets the width of the console.
uint16_t height () final
Gets the height of the console.
void finish ()
Cleans up the boot console.
void put_character (uint16_t x, uint16_t y, char) final
Places a character at the specified location.
void set_foreground_color (uint16_t x, uint16_t y, common::ConsoleColour) final
Sets the foreground color at the specified location.
void set_background_color (uint16_t x, uint16_t y, common::ConsoleColour) final
Sets the background color at the specified location.
void scroll_up (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground, common::ConsoleColour background, char fill) final
Scrolls the console up by 1 line.
char get_character (uint16_t x, uint16_t y) final
Gets the character at the specified location.
common::ConsoleColour get_foreground_color (uint16_t x, uint16_t y) final
Gets the foreground color at the specified location.
common::ConsoleColour get_background_color (uint16_t x, uint16_t y) final
Gets the background color at the specified location.
void print_logo ()
Prints the logo to the center of the screen.
Public Member Functions inherited from MaxOS::drivers::Driver
Driver ()
~Driver ()
virtual void activate ()
activate the driver
virtual void deactivate ()
deactivate the driver
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
virtual string vendor_name ()
Get who created the device.
virtual string device_name ()
Get the device name of the driver.
Public Member Functions inherited from MaxOS::drivers::console::Console
Console ()
~Console ()
virtual void put_character (uint16_t x, uint16_t y, char c, common::ConsoleColour foreground, common::ConsoleColour background)
Put a character on the console with a given foreground and background color.
virtual void put_string (uint16_t x, uint16_t y, string s, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black)
Put a string on the console.
virtual void scroll_up ()
Scroll the entire console up by 1 line.
virtual void clear ()
virtual void clear (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black, char fill=' ')
Clear an area of the console.
virtual void invert_colors (uint16_t x, uint16_t y)
Invert the colors of a character on the console.
Static Public Member Functions
static void print_logo_kernel_panic ()
Print the panic logo in the bottom right corner of the screen.
static void update_progress_bar (uint8_t percentage)
Updates the progress bar.
Public Attributes
ConsoleStream * cout
Detailed Description
Driver for the VESA Console during boot, handles the printing of characters and strings to the screen using VESA protocol.
Definition at line 29 of file vesaboot.h.
Constructor & Destructor Documentation
VESABootConsole()
VESABootConsole::VESABootConsole (common::GraphicsContext * graphics_context)
Definition at line 17 of file vesaboot.cpp.
: m_font((uint8_t *)AMIGA_FONT)
{
    // Set up
    Logger::INFO() << "Setting up VESA console\n";
    s_graphics_context = graphics_context;
    m_video_memory_meta = (uint16_t *) MemoryManager::kmalloc(width() * height() * sizeof(uint16_t));
    // Prepare the console
    VESABootConsole::clear();
    print_logo();
    m_console_area = new ConsoleArea(this, 0, 0, width() / 2 - 25, height(), ConsoleColour::DarkGrey,
                                     ConsoleColour::Black);
    cout = new ConsoleStream(m_console_area);
    // Only log to the screen when debugging
    #ifdef TARGET_DEBUG
        Logger::active_logger()->add_log_writer(cout);
        Logger::INFO() << "Console Stream set up \n";
    #endif
    update_progress_bar(0);
}
References Logger::active_logger(), MaxOS::drivers::console::Console::clear(), cout, height(), Logger::INFO(), MaxOS::memory::MemoryManager::kmalloc(), print_logo(), update_progress_bar(), and width().
~VESABootConsole()
VESABootConsole::~VESABootConsole () [default]
Member Function Documentation
finish()
void VESABootConsole::finish ()
Cleans up the boot console.
Definition at line 361 of file vesaboot.cpp.
                             {
    // Done
    Logger::HEADER() << "MaxOS Kernel Successfully Booted\n";
    // CPU::PANIC will override a disabled logger so the console should scroll itself into view as it is unknown what
    // will be on the screen now and that may mess with the presentation of the text (ie white text on a white background)
    cout->set_cursor(width(), height());
    Logger::active_logger()->disable_log_writer(cout);
}
References Logger::active_logger(), cout, Logger::HEADER(), height(), MaxOS::drivers::console::ConsoleStream::set_cursor(), and width().
Referenced by kernel_main().
get_background_color()
ConsoleColour VESABootConsole::get_background_color (uint16_t x, uint16_t y) [final], [virtual]
Gets the background color at the specified location.
Parameters
x The x coordinate
y The y coordinate
Returns
The background color at the specified location or black if the coordinates are out of bounds
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 222 of file vesaboot.cpp.
                                                                          {
    // If the coordinates are out of bounds, return
    if (x >= width() || y >= height())
        return ConsoleColour::Black;
    // Calculate the offset
    int offset = (y * width() + x);
    // Return the background color at the offset, by masking the background color with the current background color (bits 12-15)
    return (ConsoleColour) ((m_video_memory_meta[offset] & 0xF000) >> 12);
}
References height(), and width().
Referenced by put_character(), and scroll_up().
get_character()
char VESABootConsole::get_character (uint16_t x, uint16_t y) [final], [virtual]
Gets the character at the specified location.
Parameters
x The x coordinate
y The y coordinate
Returns
The character at the specified location or a space if the coordinates are out of bounds
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 182 of file vesaboot.cpp.
                                                          {
    // If the coordinates are out of bounds, return
    if (x >= width() || y >= height())
        return ' ';
    // Calculate the offset
    int offset = (y * width() + x);
    // Return the character at the offset, by masking the character with the current character (last 8 bits)
    return (char) (m_video_memory_meta[offset] & 0x00FF);
}
References height(), and width().
get_foreground_color()
ConsoleColour VESABootConsole::get_foreground_color (uint16_t x, uint16_t y) [final], [virtual]
Gets the foreground color at the specified location.
Parameters
x The x coordinate
y The y coordinate
Returns
The foreground color at the specified location or white if the coordinates are out of bounds
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 202 of file vesaboot.cpp.
                                                                          {
    // If the coordinates are out of bounds, return
    if (x >= width() || y >= height())
        return ConsoleColour::White;
    // Calculate the offset
    int offset = (y * width() + x);
    // Return the foreground color at the offset, by masking the foreground color with the current foreground color (bits 8-11)
    return (ConsoleColour) ((m_video_memory_meta[offset] & 0x0F00) >> 8);
}
References height(), and width().
Referenced by put_character(), and scroll_up().
height()
uint16_t VESABootConsole::height () [final], [virtual]
Gets the height of the console.
Returns
The height of the console in characters
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 58 of file vesaboot.cpp.
                                 {
    return s_graphics_context->height() / Font::font_height;
}
References MaxOS::gui::Font::font_height, and MaxOS::common::Rectangle< Type >::height.
Referenced by finish(), get_background_color(), get_character(), get_foreground_color(), put_character(), scroll_up(), set_background_color(), set_foreground_color(), and VESABootConsole().
print_logo()
void VESABootConsole::print_logo ()
Prints the logo to the center of the screen.
Definition at line 238 of file vesaboot.cpp.
                                 {
    // Load the logo
    const char *logo = header_data;
    // Find the center of the screen
    uint32_t center_x = s_graphics_context->width() / 2;
    uint32_t center_y = s_graphics_context->height() / 2 - 80;
    // Draw the logo
    for (uint32_t logoY = 0; logoY < logo_height; ++logoY) {
        for (uint32_t logoX = 0; logoX < logo_width; ++logoX) {
            // Store the pixel in the logo
            uint8_t pixel[3] = {0};
            // Get the pixel from the logo
            LOGO_HEADER_PIXEL(logo, pixel)
            // Draw the pixel
            s_graphics_context->put_pixel(center_x - logo_width / 2 + logoX,
                                          center_y - logo_height / 2 + logoY,
                                          common::Colour(pixel[0], pixel[1], pixel[2]));
        }
    }
}
References MaxOS::common::Rectangle< Type >::height, LOGO_HEADER_PIXEL, and MaxOS::common::Rectangle< Type >::width.
Referenced by VESABootConsole().
print_logo_kernel_panic()
void VESABootConsole::print_logo_kernel_panic () [static]
Print the panic logo in the bottom right corner of the screen.
Definition at line 332 of file vesaboot.cpp.
                                              {
    // Load the logo
    const char *logo = header_data_kp;
    // Find the bottom right of the screen
    uint32_t right_x = s_graphics_context->width() - kp_width - 10;
    uint32_t bottom_y = s_graphics_context->height() - kp_height - 10;
    // Draw the logo
    for (uint32_t logoY = 0; logoY < kp_height; ++logoY) {
        for (uint32_t logoX = 0; logoX < kp_width; ++logoX) {
            // Store the pixel in the logo
            uint8_t pixel[3] = {0};
            // Get the pixel from the logo
            LOGO_HEADER_PIXEL(logo, pixel)
            // Draw the pixel
            s_graphics_context->put_pixel(right_x + logoX, bottom_y + logoY, common::Colour(pixel[0], pixel[1], pixel[2]));
        }
    }
}
References MaxOS::common::Rectangle< Type >::height, LOGO_HEADER_PIXEL, and MaxOS::common::Rectangle< Type >::width.
Referenced by MaxOS::system::CPU::PANIC().
put_character()
void VESABootConsole::put_character (uint16_t x, uint16_t y, char c) [final], [virtual]
Places a character at the specified location.
Parameters
x The x coordinate
y The y coordinate
c The character to place
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 69 of file vesaboot.cpp.
                                                                  {
    // Parse any ansi codes
    if (c == '\033') {
        // Store the character
        ansi_code_length = 0;
        ansi_code[ansi_code_length++] = c;
        // Do not draw the escape character
        return;
    }
    if (ansi_code_length < 8) {
        // Add the character to the ANSI code
        ansi_code[ansi_code_length++] = c;
        // If the ANSI code is complete
        if (c == 'm') {
            ansi_code[ansi_code_length] = '\0';
            ansi_code_length = -1;
            if (strcmp("\033[0m", ansi_code) != 0) {
                m_foreground_color = ConsoleColour::Uninitialised;
                m_background_color = ConsoleColour::Uninitialised;
                return;
            }
            // Get the colour from the ANSI code
            const Colour colour(ansi_code);
            // Set the colour
            bool foreground = ansi_code[4] == '3';
            if (foreground)
                m_foreground_color = colour.to_console_colour();
            else
                m_background_color = colour.to_console_colour();
        }
        // Do not draw the escape character
        return;
    }
    // If the coordinates are out of bounds, return
    if (x >= width() || y >= height())
        return;
    // Calculate the offset
    int offset = (y * width() + x);
    // Set the character at the offset, by masking the character with the current character (last 8 bits)
    m_video_memory_meta[offset] = (m_video_memory_meta[offset] & 0xFF00) | (uint16_t) c;
    // Convert the char into a string
    char s[] = " ";
    s[0] = c;
    Colour foreground = m_foreground_color == ConsoleColour::Uninitialised ? get_foreground_color(x, y) : Colour(m_foreground_color);
    Colour background = m_background_color == ConsoleColour::Uninitialised ? get_background_color(x, y) : Colour(m_background_color);
    // Use the m_font to draw the character
    m_font.draw_text(x * 8, y * Font::font_height, foreground, background, s_graphics_context, s);
}
References MaxOS::gui::Font::draw_text(), MaxOS::gui::Font::font_height, get_background_color(), get_foreground_color(), height(), strcmp(), MaxOS::common::Colour::to_console_colour(), and width().
scroll_up()
void VESABootConsole::scroll_up (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground, common::ConsoleColour background, char fill) [final], [virtual]
Scrolls the console up by 1 line.
Parameters
left The left coordinate of the area to scroll
top The top coordinate of the area to scroll
width The width of the area to scroll
height The height of the area to scroll
foreground The foreground color of the new line
background The background color of the new line
fill The character to fill the new line with
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 277 of file vesaboot.cpp.
                                                                           {
    // Get the framebuffer info
    auto *framebuffer_address = (uint8_t *) s_graphics_context->framebuffer_address();
    uint64_t framebuffer_width = s_graphics_context->width();
    uint64_t framebuffer_bpp = s_graphics_context->color_depth(); // in bits per pixel
    uint64_t bytes_per_pixel = framebuffer_bpp / 8;
    uint64_t framebuffer_pitch = framebuffer_width * bytes_per_pixel;
    uint16_t line_height = Font::font_height;
    // Region conversions
    uint16_t region_pixel_y = top * line_height;
    uint16_t region_pixel_height = height * line_height;
    uint16_t region_pixel_left = left * Font::font_width;
    uint16_t region_pixel_width = width * Font::font_width;
    size_t row_bytes = region_pixel_width * bytes_per_pixel;
    // Decide the colour of the pixel
    ConsoleColour to_set_foreground = CPU::is_panicking ? ConsoleColour::White : get_foreground_color(left, top + height - 1);
    ConsoleColour to_set_background = CPU::is_panicking ? ConsoleColour::Red : get_background_color(left, top + height - 1);
    Colour fill_colour = Colour(to_set_background);
    uint32_t fill_value = s_graphics_context->colour_to_int(to_set_background);
    // Scroll the region upward by one text line
    for (uint16_t row = 0; row < region_pixel_height - line_height; row++) {
        uint8_t *src = framebuffer_address + (region_pixel_y + row + line_height) * framebuffer_pitch + region_pixel_left * bytes_per_pixel;
        uint8_t *dest = framebuffer_address + (region_pixel_y + row) * framebuffer_pitch + region_pixel_left * bytes_per_pixel;
        memmove(dest, src, row_bytes);
    }
    // Clear the last line of the region
    uint16_t clear_start_y = region_pixel_y + region_pixel_height - line_height;
    for (uint16_t row = 0; row < line_height; row++) {
        auto row_add = (uint32_t *) (framebuffer_address + (clear_start_y + row) * framebuffer_pitch + region_pixel_left * 4);
        for (uint16_t col = 0; col < region_pixel_width; col++) {
            row_add[col] = fill_value;
        }
    }
    //Update any per-pixel colour metadata
    uint16_t text_row = top + height - 1;
    for (uint16_t x = left; x < left + width; x++) {
        set_foreground_color(x, text_row, to_set_foreground);
        set_background_color(x, text_row, to_set_background);
    }
}
References MaxOS::gui::Font::font_height, MaxOS::gui::Font::font_width, get_background_color(), get_foreground_color(), height(), MaxOS::system::CPU::is_panicking, memmove(), set_background_color(), set_foreground_color(), MaxOS::common::Rectangle< Type >::width, and width().
set_background_color()
void VESABootConsole::set_background_color (uint16_t x, uint16_t y, common::ConsoleColour background) [final], [virtual]
Sets the background color at the specified location.
Parameters
x The x coordinate
y The y coordinate
background The background color
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 162 of file vesaboot.cpp.
                                                                                           {
    // If the coordinates are out of bounds, return
    if (x >= width() || y >= height())
        return;
    // Calculate the offset
    int offset = (y * width() + x);
    // Set the background color at the offset, by masking the background color with the current background color (bits 12-15)
    m_video_memory_meta[offset] = (m_video_memory_meta[offset] & 0x0FFF) | ((uint16_t) background << 12);
}
References height(), and width().
Referenced by scroll_up().
set_foreground_color()
void VESABootConsole::set_foreground_color (uint16_t x, uint16_t y, common::ConsoleColour foreground) [final], [virtual]
Sets the foreground color at the specified location.
Parameters
x The x coordinate
y The y coordinate
foreground The foreground color
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 142 of file vesaboot.cpp.
                                                                                           {
    // If the coordinates are out of bounds, return
    if (x >= width() || y >= height())
        return;
    // Calculate the offset
    int offset = (y * width() + x);
    // Set the foreground color at the offset, by masking the foreground color with the current foreground color (bits 8-11)
    m_video_memory_meta[offset] = (m_video_memory_meta[offset] & 0xF0FF) | ((uint16_t) foreground << 8);
}
References height(), and width().
Referenced by scroll_up().
update_progress_bar()
void VESABootConsole::update_progress_bar (uint8_t percentage) [static]
Updates the progress bar.
Parameters
percentage The percentage to update the progress bar to (0-100)
Definition at line 378 of file vesaboot.cpp.
                                                            {
    // Check bounds
    if (percentage > 100)
        percentage = 100;
    // Must have a valid graphics context
    if (s_graphics_context == nullptr)
        return;
    uint8_t progress_height = 15;
    uint8_t progress_spacing = 20;
    uint8_t progress_width_cull = 40;
    // Find the center of the screen
    uint32_t right_x = (s_graphics_context->width() / 2) - logo_width / 2;
    uint32_t bottom_y = (s_graphics_context->height() / 2 - 80) - logo_height / 2;
    // Find the bounds
    uint32_t start_x = progress_width_cull;
    uint32_t start_y = logo_height + progress_spacing;
    uint32_t end_x = logo_width - progress_width_cull;
    uint32_t end_y = logo_height + progress_height + progress_spacing;
    // Draw the progress bar
    for (uint32_t progress_y = start_y; progress_y < end_y; ++progress_y) {
        for (uint32_t progress_x = start_x; progress_x < end_x; ++progress_x) {
            // Check if drawing border
            bool is_border = (progress_y == start_y) || (progress_y == end_y - 1) ||
                             (progress_x == start_x) || (progress_x == end_x - 1);
            // Only draw the border if it is the first time drawing it
            is_border = is_border && percentage == 0;
            // If it is not within the percentage, skip it
            if (progress_x > logo_width * percentage / 100 && !is_border)
                continue;
            s_graphics_context->put_pixel(right_x + progress_x, bottom_y + progress_y, Colour(0xFF, 0xFF, 0xFF));
        }
    }
}
References MaxOS::common::Rectangle< Type >::height, and MaxOS::common::Rectangle< Type >::width.
Referenced by Logger::set_log_level(), and VESABootConsole().
width()
uint16_t VESABootConsole::width () [final], [virtual]
Gets the width of the console.
Returns
The width of the console in characters
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 49 of file vesaboot.cpp.
                                {
    return s_graphics_context->width() / 8; // 8 pixels per character
}
References MaxOS::common::Rectangle< Type >::width.
Referenced by finish(), get_background_color(), get_character(), get_foreground_color(), put_character(), scroll_up(), set_background_color(), set_foreground_color(), and VESABootConsole().
Member Data Documentation
cout
ConsoleStream* MaxOS::drivers::console::VESABootConsole::cout
Definition at line 51 of file vesaboot.h.
Referenced by finish(), and VESABootConsole().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/vesaboot.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/console/vesaboot.cpp