MaxOS::processes::Scheduler Class Reference
Schedules processes to run on the CPU via their threads.
#include <scheduler.h>
Public Member Functions
Scheduler (system::Multiboot &multiboot)
~Scheduler ()
system::cpu_status_t * handle_interrupt (system::cpu_status_t *status) final
Handles the interrupt 0x20.
system::cpu_status_t * schedule (system::cpu_status_t *status)
Schedules the next thread to run.
system::cpu_status_t * schedule_next (system::cpu_status_t *status)
Schedules the next thread to run.
system::cpu_status_t * yield ()
Pass execution to the next thread.
uint64_t add_process (Process *process)
Adds a process to the scheduler.
uint64_t remove_process (Process *process)
Removes a process from the scheduler if the process has no threads, if it does then the threads are stopped but the process is not removed (this will be done automatically when all threads are stopped)
system::cpu_status_t * force_remove_process (Process *process)
Removes a process from the scheduler and deletes all threads, begins running the next process.
uint64_t add_thread (Thread *thread)
Adds a thread to the scheduler.
uint64_t ticks () const
Gets how long the system has been running for.
void activate ()
Activates the scheduler.
void deactivate ()
Deactivates the scheduler.
Public Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
virtual void handle_interrupt ()
Handles an interrupt.
Static Public Member Functions
static Scheduler * system_scheduler ()
Gets the system scheduler.
static Process * current_process ()
Gets the current process.
static Process * get_process (uint64_t pid)
Gets a process by its PID.
static Thread * current_thread ()
Gets the currently executing thread.
static Thread * get_thread (uint64_t tid)
Gets a thread by its TID.
static void load_multiboot_elfs (system::Multiboot *multiboot)
Loads any valid ELF files from the multiboot structure.
Additional Inherited Members
Protected Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
InterruptHandler (uint8_t interrupt_number, int64_t redirect=-1, uint64_t redirect_index=0)
~InterruptHandler ()
Protected Attributes inherited from MaxOS::hardwarecommunication::InterruptHandler
uint8_t m_interrupt_number
Detailed Description
Schedules processes to run on the CPU via their threads.
Definition at line 23 of file scheduler.h.
Constructor & Destructor Documentation
Scheduler()
Scheduler::Scheduler (system::Multiboot & multiboot)
Definition at line 14 of file scheduler.cpp.
: InterruptHandler(0x20),
  m_current_thread_index(0),
  m_active(false),
  m_ticks(0),
  m_next_pid(-1),
  m_next_tid(-1),
  m_shared_memory_registry(resource_type_t::SHARED_MEMORY),
  m_shared_messages_registry(resource_type_t::MESSAGE_ENDPOINT)
{
    // Set up the basic scheduler
    Logger::INFO() << "Setting up Scheduler \n";
    s_instance = this;
    // Create the idle process
    auto* idle = new Process("kernelMain Idle", nullptr, nullptr, 0, true);
    idle->memory_manager = MemoryManager::s_kernel_memory_manager;
    add_process(idle);
    idle->set_pid(0);
    // Load the elfs
    load_multiboot_elfs(&multiboot);
}
References add_process(), Logger::INFO(), load_multiboot_elfs(), and MaxOS::memory::MemoryManager::s_kernel_memory_manager.
~Scheduler()
Scheduler::~Scheduler ()
Definition at line 39 of file scheduler.cpp.
                      {
    // Deactivate this scheduler
    s_instance = nullptr;
    m_active = false;
}
Member Function Documentation
activate()
void Scheduler::activate ()
Activates the scheduler.
Definition at line 234 of file scheduler.cpp.
                         {
    m_active = true;
}
add_process()
uint64_t Scheduler::add_process (Process * process)
Adds a process to the scheduler.
Parameters
process The process to add
Returns
The process ID
Definition at line 161 of file scheduler.cpp.
                                                {
    // Get the next process ID
    m_next_pid++;
    // Add the process to the list
    m_processes.push_back(process);
    Logger::DEBUG() << "Adding process " << m_next_pid << ": " << process->name << "\n";
    // Return the process ID
    return m_next_pid;
}
References Logger::DEBUG(), and MaxOS::processes::Process::name.
Referenced by Scheduler().
add_thread()
uint64_t Scheduler::add_thread (Thread * thread)
Adds a thread to the scheduler.
Parameters
thread The thread to add
Returns
The thread ID
Definition at line 180 of file scheduler.cpp.
                                             {
    // Get the next thread ID
    m_next_tid++;
    // Add the thread to the list
    m_threads.push_back(thread);
    Logger::DEBUG() << "Adding thread " << m_next_tid << " to process " << thread->parent_pid << "\n";
    // Return the thread ID
    return m_next_tid;
}
References Logger::DEBUG(), and MaxOS::processes::Thread::parent_pid.
current_process()
Process * Scheduler::current_process () [static]
Gets the current process.
Returns
The current process, or nullptr if not found
Definition at line 309 of file scheduler.cpp.
                                    {
    Process* current_process = nullptr;
    // Make sure there is something with process attached
    if (!s_instance)
        return nullptr;
    // Find the process that has the thread being executed
    for (auto process: s_instance->m_processes)
        if (process->pid() == current_thread()->parent_pid) {
            current_process = process;
            break;
        }
    return current_process;
}
References current_process(), current_thread(), and MaxOS::processes::Thread::parent_pid.
Referenced by MaxOS::filesystem::VFSResourceRegistry::create_resource(), current_process(), MaxOS::memory::VirtualMemoryManager::free(), MaxOS::filesystem::VFSResourceRegistry::get_resource(), MaxOS::memory::VirtualMemoryManager::load_shared_memory(), MaxOS::processes::SharedMemory::open(), MaxOS::system::CPU::PANIC(), MaxOS::system::CPU::prepare_for_panic(), MaxOS::processes::SharedMemory::read(), schedule_next(), MaxOS::system::SyscallManager::syscall_close_process(), MaxOS::system::SyscallManager::syscall_klog(), MaxOS::system::SyscallManager::syscall_resource_close(), MaxOS::system::SyscallManager::syscall_resource_open(), MaxOS::system::SyscallManager::syscall_resource_read(), and MaxOS::system::SyscallManager::syscall_resource_write().
current_thread()
Thread * Scheduler::current_thread () [static]
Gets the currently executing thread.
Returns
The currently executing thread
Definition at line 350 of file scheduler.cpp.
                                  {
    return s_instance->m_threads[s_instance->m_current_thread_index];
}
Referenced by current_process(), force_remove_process(), schedule(), schedule_next(), MaxOS::system::SyscallManager::syscall_klog(), MaxOS::system::SyscallManager::syscall_thread_close(), MaxOS::system::SyscallManager::syscall_thread_sleep(), MaxOS::system::SyscallManager::syscall_thread_yield(), and yield().
deactivate()
void Scheduler::deactivate ()
Deactivates the scheduler.
Definition at line 358 of file scheduler.cpp.
                           {
    m_active = false;
}
force_remove_process()
cpu_status_t * Scheduler::force_remove_process (Process * process)
Removes a process from the scheduler and deletes all threads, begins running the next process.
Parameters
process The process to remove
Returns
The status of the CPU for the next process to run or nullptr if the process was not found
Definition at line 281 of file scheduler.cpp.
                                                              {
    // If there is no process, fail
    if (!process)
        return nullptr;
    // Remove all the threads
    for (auto thread: process->threads()) {
        // Remove the thread from the scheduler
        int index = m_threads.find(thread) - m_threads.begin();
        m_threads.erase(m_threads.begin() + index);
        // Delete the thread
        process->remove_thread(thread->tid);
    }
    // Process will be dead now so run the next process (don't care about the execution state being outdated as it is being
    // removed regardless)
    return schedule_next(current_thread()->execution_state);
}
References current_thread(), MaxOS::processes::Process::remove_thread(), schedule_next(), and MaxOS::processes::Process::threads().
Referenced by MaxOS::system::CPU::prepare_for_panic().
get_process()
Process * Scheduler::get_process (uint64_t pid) [static]
Gets a process by its PID.
Parameters
pid The process ID
Returns
The process or nullptr if not found
Definition at line 333 of file scheduler.cpp.
                                            {
    // Try to find the process
    for (auto process: s_instance->m_processes)
        if (process->pid() == pid)
            return process;
    // Not found
    return nullptr;
}
Referenced by MaxOS::system::SyscallManager::syscall_close_process(), and MaxOS::system::SyscallManager::syscall_thread_close().
get_thread()
Thread * Scheduler::get_thread (uint64_t tid) [static]
Gets a thread by its TID.
Parameters
tid The thread ID
Returns
The thread or nullptr if not found
Definition at line 401 of file scheduler.cpp.
                                          {
    // Try to find the thread
    for (auto thread: s_instance->m_threads)
        if (thread->tid == tid)
            return thread;
    return nullptr;
}
Referenced by MaxOS::system::SyscallManager::syscall_thread_close().
handle_interrupt()
cpu_status_t * Scheduler::handle_interrupt (system::cpu_status_t * status) [final], [virtual]
Handles the interrupt 0x20.
Parameters
status The current CPU status
Returns
The new CPU status
Reimplemented from MaxOS::hardwarecommunication::InterruptHandler.
Definition at line 52 of file scheduler.cpp.
                                                              {
    return schedule(status);
}
References schedule(), and status.
load_multiboot_elfs()
void Scheduler::load_multiboot_elfs (system::Multiboot * multiboot) [static]
Loads any valid ELF files from the multiboot structure.
Parameters
multiboot The multiboot structure
Definition at line 368 of file scheduler.cpp.
                                                        {
    for (multiboot_tag* tag = multiboot->start_tag(); tag->type != MULTIBOOT_TAG_TYPE_END; tag = (struct multiboot_tag*) ((multiboot_uint8_t*) tag + ((tag->size + 7) & ~7))) {
        // Tag is not an ELF
        if (tag->type != MULTIBOOT_TAG_TYPE_MODULE)
            continue;
        // Try create the elf from the module
        auto* module = (struct multiboot_tag_module*) tag;
        auto* elf = new Elf64((uintptr_t) PhysicalMemoryManager::to_dm_region(module->mod_start));
        if (!elf->is_valid())
            continue;
        Logger::DEBUG() << "Creating process from multiboot module for " << module->cmdline << " (at 0x" << (uint64_t) module->mod_start << ")\n";
        // Create an array of args for the process TODO: handle multiple args ("" & spaces)
        char* args[1] = {module->cmdline};
        // Create the process
        auto* process = new Process(module->cmdline, args, 1, elf);
        Logger::DEBUG() << "Elf loaded to pid " << process->pid() << "\n";
        delete elf;
    }
}
References Logger::DEBUG(), MULTIBOOT_TAG_TYPE_END, MULTIBOOT_TAG_TYPE_MODULE, MaxOS::system::Multiboot::start_tag(), and MaxOS::memory::PhysicalMemoryManager::to_dm_region().
Referenced by Scheduler().
remove_process()
uint64_t Scheduler::remove_process (Process * process)
Removes a process from the scheduler if the process has no threads, if it does then the threads are stopped but the process is not removed (this will be done automatically when all threads are stopped)
Parameters
process The process to remove
force If true, the process will be removed and so will all threads
Returns
-1 if the process has threads, 0 otherwise
Definition at line 246 of file scheduler.cpp.
                                                   {
    // Check if the process has no threads
    if (!process->threads().empty()) {
        // Set the threads to stopped or remove them if forced
        for (auto thread: process->threads())
            thread->thread_state = ThreadState::STOPPED;
        // Need to wait until the threads are stopped before removing the process (this will be called again when all threads are stopped)
        return -1;
    }
    // Remove the process
    for (uint32_t i = 0; i < m_processes.size(); i++) {
        if (m_processes[i] == process) {
            m_processes.erase(m_processes.begin() + i);
            // Delete the process mem
            delete process;
            return 0;
        }
    }
    // Process not found
    return -1;
}
References MaxOS::processes::STOPPED, and MaxOS::processes::Process::threads().
schedule()
cpu_status_t * Scheduler::schedule (system::cpu_status_t * status)
Schedules the next thread to run.
Parameters
cpu_state The current CPU state
Returns
The next CPU state
Definition at line 64 of file scheduler.cpp.
                                                         {
    // Scheduler cant schedule anything
    if (m_threads.empty() || !m_active)
        return cpu_state;
    // Thread that we are dealing with
    Thread* current_thread = m_threads[m_current_thread_index];
    // Ticked
    m_ticks++;
    current_thread->ticks++;
    // Wait for a bit so that the scheduler doesn't run too fast TODO: fix
    if (m_ticks % s_ticks_per_event != 0) return cpu_state;
    // Schedule the next thread
    return schedule_next(cpu_state);
}
References current_thread(), schedule_next(), and MaxOS::processes::Thread::ticks.
Referenced by handle_interrupt().
schedule_next()
cpu_status_t * Scheduler::schedule_next (system::cpu_status_t * status)
Schedules the next thread to run.
Parameters
status The current CPU status of the thread
Returns
The next CPU status
Definition at line 90 of file scheduler.cpp.
                                                              {
    // Get the thread that is executing right now
    Thread* current_thread = m_threads[m_current_thread_index];
    // Save its state
    current_thread->execution_state = cpu_state;
    current_thread->save_sse_state();
    if (current_thread->thread_state == ThreadState::RUNNING)
        current_thread->thread_state = ThreadState::READY;
    // Switch to the thread that will now run
    m_current_thread_index++;
    m_current_thread_index %= m_threads.size();
    current_thread = m_threads[m_current_thread_index];
    Process* owner_process = current_process();
    // Handle state changes
    switch (current_thread->thread_state) {
        case ThreadState::NEW:
            current_thread->thread_state = ThreadState::RUNNING;
            break;
        case ThreadState::SLEEPING:
            // If the wake-up time hasn't occurred yet, run the next thread
            if (current_thread->wakeup_time > m_ticks)
                return schedule_next(current_thread->execution_state);
            break;
        case ThreadState::STOPPED:
            // Find the process that has the thread and remove it
            for (auto thread: owner_process->threads()) {
                if (thread == current_thread) {
                    owner_process->remove_thread(m_current_thread_index);
                    break;
                }
            }
            // Remove the thread
            m_threads.erase(m_threads.begin() + m_current_thread_index);
            // Run the next thread
            return schedule_next(cpu_state);
        default:
            break;
    }
    // Prepare the next thread to run
    current_thread->thread_state = ThreadState::RUNNING;
    current_thread->restore_sse_state();
    // Load the thread's memory manager and task state
    MemoryManager::switch_active_memory_manager(owner_process->memory_manager);
    CPU::tss.rsp0 = current_thread->tss_pointer();
    return current_thread->execution_state;
}
References current_process(), current_thread(), MaxOS::processes::Thread::execution_state, MaxOS::processes::Process::memory_manager, MaxOS::processes::NEW, MaxOS::processes::READY, MaxOS::processes::Process::remove_thread(), MaxOS::processes::Thread::restore_sse_state(), MaxOS::processes::RUNNING, MaxOS::processes::Thread::save_sse_state(), schedule_next(), MaxOS::processes::SLEEPING, MaxOS::processes::STOPPED, MaxOS::memory::MemoryManager::switch_active_memory_manager(), MaxOS::processes::Thread::thread_state, MaxOS::processes::Process::threads(), MaxOS::system::CPU::tss, MaxOS::processes::Thread::tss_pointer(), and MaxOS::processes::Thread::wakeup_time.
Referenced by force_remove_process(), schedule(), schedule_next(), and yield().
system_scheduler()
Scheduler * Scheduler::system_scheduler () [static]
Gets the system scheduler.
Returns
The system scheduler or nullptr if not found
Definition at line 198 of file scheduler.cpp.
                                       {
    return s_instance;
}
Referenced by MaxOS::common::Spinlock::acquire(), MaxOS::system::CPU::PANIC(), MaxOS::system::CPU::prepare_for_panic(), MaxOS::processes::Process::Process(), MaxOS::processes::Process::remove_thread(), MaxOS::processes::Thread::sleep(), MaxOS::system::SyscallManager::syscall_close_process(), MaxOS::system::SyscallManager::syscall_thread_close(), MaxOS::system::SyscallManager::syscall_thread_yield(), and MaxOS::processes::Thread::Thread().
ticks()
uint64_t Scheduler::ticks () const
Gets how long the system has been running for.
Returns
The number of ticks
Definition at line 208 of file scheduler.cpp.
                                {
    return m_ticks;
}
Referenced by MaxOS::system::CPU::PANIC().
yield()
cpu_status_t * Scheduler::yield ()
Pass execution to the next thread.
Definition at line 216 of file scheduler.cpp.
                               {
    // If this is the only thread, can't yield
    if (m_threads.size() <= 1)
        return current_thread()->execution_state;
    // Set the current thread to waiting if running
    if (m_threads[m_current_thread_index]->thread_state == ThreadState::RUNNING)
        m_threads[m_current_thread_index]->thread_state = ThreadState::READY;
    // Schedule the next thread
    return schedule_next(current_thread()->execution_state);
}
References current_thread(), MaxOS::processes::Thread::execution_state, MaxOS::processes::READY, MaxOS::processes::RUNNING, and schedule_next().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/processes/scheduler.h
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/scheduler.cpp