MaxOS::filesystem::DirectoryResource Class Reference
A wrapper for a Directory which exposes Directory operations as Resource operations.
#include <vfsresource.h>
Public Member Functions
DirectoryResource (const string &name, size_t flags, processes::resource_type_t type)
Construct a new Directory Resource object.
int read (void *buffer, size_t size, size_t flags) final
Read from a directory resource.
int write (const void *buffer, size_t size, size_t flags) final
Write to a directory resource.
Public Member Functions inherited from MaxOS::processes::Resource
Resource (const string &name, size_t flags, resource_type_t type)
Constructs a new Resource object.
string name ()
Gets the name of this resource.
resource_type_t type ()
Gets the type of this resource.
virtual void open (size_t flags)
Opens the resource.
virtual void close (size_t flags)
Closes the resource.
Public Attributes
Directory * directory
The directory that this resource handles & exposes.
Detailed Description
A wrapper for a Directory which exposes Directory operations as Resource operations.
Definition at line 49 of file vfsresource.h.
Constructor & Destructor Documentation
DirectoryResource()
DirectoryResource::DirectoryResource (const string & name, size_t flags, processes::resource_type_t type)
Construct a new Directory Resource object.
Parameters
name The name of the resource
flags The flags for the resource when opened
type The type of the resource
Definition at line 134 of file vfsresource.cpp.
: Resource(name, flags, type),
  directory(nullptr)
{
}
Member Function Documentation
read()
int DirectoryResource::read (void * buffer, size_t size, size_t flags) [final], [virtual]
Read from a directory resource.
Parameters
buffer The buffer to read into
size The number of bytes to read
flags The flags to pass to the reading
Returns
The number of bytes successfully read or -1 on error
Reimplemented from MaxOS::processes::Resource.
Definition at line 230 of file vfsresource.cpp.
                                                                   {
    // Directory not found
    if(!directory)
        return -1;
    switch ((DirectoryFlags)flags){
        case DirectoryFlags::READ_ENTRIES:{
            write_entries(buffer, size);
            break;
        }
        case DirectoryFlags::READ_ENTRIES_SIZE:{
            return entries_size();
        }
        default:
            return -1;
    }
    return size;
}
References directory, flags, and size.
write()
int DirectoryResource::write (const void * buffer, size_t size, size_t flags) [final], [virtual]
Write to a directory resource.
Parameters
buffer The buffer to write from
size The number of bytes to write
flags The flags to pass to the writing
Returns
The number of bytes successfully written or -1 on error
Reimplemented from MaxOS::processes::Resource.
Definition at line 262 of file vfsresource.cpp.
                                                                          {
    // Directory not found
    if(!directory)
        return -1;
    auto registry = GlobalResourceRegistry::get_registry(resource_type_t::FILESYSTEM);
    switch ((DirectoryFlags)flags){
        case DirectoryFlags::WRITE_NAME : {
            // Open the parent
            Resource* parent = registry->get_resource(Path::parent_directory(name()));
            auto parent_directory = ((DirectoryResource*)parent)->directory;
            // Rename
            string new_name = string((uint8_t*)buffer, size);
            parent_directory->rename_subdirectory(directory, new_name);
            break;
        }
        case DirectoryFlags::WRITE_NEW_FILE:{
            string new_name = string((uint8_t*)buffer, size);
            directory->create_file(new_name);
            break;
        }
        case DirectoryFlags::WRITE_NEW_DIR:{
            string new_name = string((uint8_t*)buffer, size);
            directory->create_subdirectory(new_name);
            break;
        }
        case DirectoryFlags::WRITE_REMOVE_FILE:{
            string new_name = string((uint8_t*)buffer, size);
            directory->remove_file(new_name);
            break;
        }
        case DirectoryFlags::WRITE_REMOVE_DIR:{
            string new_name = string((uint8_t*)buffer, size);
            directory->remove_subdirectory(new_name);
            break;
        }
        default:
            return -1;
    }
    return size;
}
References MaxOS::filesystem::Directory::create_file(), MaxOS::filesystem::Directory::create_subdirectory(), directory, flags, MaxOS::processes::GlobalResourceRegistry::get_registry(), MaxOS::processes::Resource::name(), MaxOS::filesystem::Path::parent_directory(), MaxOS::filesystem::Directory::remove_file(), MaxOS::filesystem::Directory::remove_subdirectory(), and size.
Member Data Documentation
directory
Directory* MaxOS::filesystem::DirectoryResource::directory
The directory that this resource handles & exposes.
Definition at line 61 of file vfsresource.h.
Referenced by read(), and write().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/vfsresource.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/vfsresource.cpp