maxOS::hardwarecommunication::PeripheralComponentInterconnectController Class Reference
Handles the selecting and loading of drivers for PCI devices.
#include <pci.h>
Public Member Functions
PeripheralComponentInterconnectController (common::OutputStream *)
__CONTROLLER___
~PeripheralComponentInterconnectController ()
void select_drivers (drivers::DriverSelectorEventHandler *handler, hardwarecommunication::InterruptManager *interrupt_manager, common::OutputStream *error_message_stream)
Select the driver for the device.
drivers::Driver * get_driver (PeripheralComponentInterconnectDeviceDescriptor dev, InterruptManager *interrupt_manager)
Get the driver for the device.
void list_known_deivce (PeripheralComponentInterconnectDeviceDescriptor dev)
Detailed Description
Handles the selecting and loading of drivers for PCI devices.
Definition at line 77 of file pci.h.
Constructor & Destructor Documentation
PeripheralComponentInterconnectController()
PeripheralComponentInterconnectController::PeripheralComponentInterconnectController (common::OutputStream * stream)
__CONTROLLER___
Definition at line 80 of file pci.cpp.
: m_data_port(0xCFC),
  m_command_port(0xCF8),
  m_debug_messages_stream(stream)
{
}
 PeripheralComponentInterconnectController()
PeripheralComponentInterconnectController::~PeripheralComponentInterconnectController ()
Definition at line 88 of file pci.cpp.
                                                                                      {
}
Member Function Documentation
get_driver()
Driver * PeripheralComponentInterconnectController::get_driver (PeripheralComponentInterconnectDeviceDescriptor dev, InterruptManager * interrupt_manager)
Get the driver for the device.
Parameters
dev Device descriptor
interrupt_manager Interrupt manager
Returns
Driver for the device, 0 if there is no driver
Definition at line 238 of file pci.cpp.
                                                                                                                                                     {
    // Dont use new here, manually allocate memory instead
    Driver* driver = 0;
    switch (dev.vendor_id)
    {
        case 0x1022: //AMD
        {
            switch (dev.device_id)
            {
                case 0x2000: //am79c971
                {
                    amd_am79c973* result = (amd_am79c973*)MemoryManager::s_active_memory_manager
                          ->malloc(sizeof(amd_am79c973));
                    new (result) amd_am79c973(&dev, interrupt_manager);
                    return result;
                }
                default:
                    break;
            }
            break;
        }
        case 0x8086: //Intel
        {
            switch (dev.device_id)
            {
                case 0x100E: //i217 (Ethernet Controller)
                {
                    intel_i217* result = (intel_i217*)MemoryManager::s_active_memory_manager
                          ->malloc(sizeof(intel_i217));
                    new (result) intel_i217(&dev, interrupt_manager);
                    return result;
                }
                default:
                    break;
            }
            break;
        }//End Intel
    }
    //If there is no driver for the particular device, go into generic devices
    switch (dev.class_id)
    {
        case 0x03: //Graphics
        {
            switch (dev.subclass_id)
            {
                case 0x00: //VGA
                {
                    VideoGraphicsArray* result = (VideoGraphicsArray*)MemoryManager::s_active_memory_manager->malloc(sizeof(VideoGraphicsArray));
                    new (result) VideoGraphicsArray();
                    return result;
                }
            }
            break;
        }
    }
    return driver;
}
References maxOS::hardwarecommunication::PeripheralComponentInterconnectDeviceDescriptor::class_id, maxOS::hardwarecommunication::PeripheralComponentInterconnectDeviceDescriptor::device_id, maxOS::hardwarecommunication::PeripheralComponentInterconnectDeviceDescriptor::subclass_id, and maxOS::hardwarecommunication::PeripheralComponentInterconnectDeviceDescriptor::vendor_id.
Referenced by select_drivers().
list_known_deivce()
void PeripheralComponentInterconnectController::list_known_deivce (PeripheralComponentInterconnectDeviceDescriptor dev)
Definition at line 303 of file pci.cpp.
                                                                                                                     {
    switch (dev.vendor_id)
    {
        case 0x1022:
        {
            // The vendor is AMD
            m_debug_messages_stream->write("AMD ");
            // List the device
            switch (dev.device_id)
            {
                default:
                  m_debug_messages_stream->write_hex(dev.device_id);
                  break;
            }
            break;
        }
        case 0x106B:
        {
            // The vendor is Apple
            m_debug_messages_stream->write("Apple ");
            // List the device
            switch (dev.device_id)
            {
                case 0x003F:
                {
                  m_debug_messages_stream->write("KeyLargo/Intrepid USB");
                  break;
                }
                default:
                  m_debug_messages_stream->write_hex(dev.device_id);
                    break;
            }
            break;
        }
        case 1234:
        {
            // The vendor is QEMU
            m_debug_messages_stream->write("QEMU ");
            // List the device
            switch (dev.device_id)
            {
                case 0x1111:
                {
                  m_debug_messages_stream->write("Virtual Video Controller");
                    break;
                }
            }
            break;
        }
        case 0x8086:
        {
            // The vendor is Intel
            m_debug_messages_stream->write("Intel ");
            // List the device
            switch (dev.device_id)
            {
                case 0x1237:
                {
                  m_debug_messages_stream->write("440FX");
                    break;
                }
                case 0x2415:
                {
                  m_debug_messages_stream->write("AC'97");
                    break;
                }
                case 0x7000:
                {
                  m_debug_messages_stream->write("PIIX3");
                    break;
                }
                case 0x7010:
                {
                  m_debug_messages_stream->write("PIIX4");
                    break;
                }
                case 0x7111:
                {
                  m_debug_messages_stream->write("PIIX3");
                    break;
                }
                case 0x7113:
                {
                  m_debug_messages_stream->write("PIIX4 ACPI");
                    break;
                }
                default:
                    break;
            }
            break;
        }
        case 0x80EE: {
            // The vendor is VirtualBox
            m_debug_messages_stream->write("VirtualBox ");
            // List the device
            switch (dev.device_id) {
                case 0xBEEF: {
                  m_debug_messages_stream->write("Graphics Adapter");
                    break;
                }
                case 0xCAFE: {
                  m_debug_messages_stream->write("Guest Service");
                    break;
                }
            }
            break;
        }
        default: // Unknown
          m_debug_messages_stream->write_hex(dev.vendor_id);
          m_debug_messages_stream->write(" ");
          m_debug_messages_stream->write_hex(dev.device_id);
          break;
    }
}
References maxOS::hardwarecommunication::PeripheralComponentInterconnectDeviceDescriptor::device_id, maxOS::hardwarecommunication::PeripheralComponentInterconnectDeviceDescriptor::vendor_id, maxOS::common::OutputStream::write(), and maxOS::common::OutputStream::write_hex().
Referenced by select_drivers().
select_drivers()
void PeripheralComponentInterconnectController::select_drivers (drivers::DriverSelectorEventHandler * handler, hardwarecommunication::InterruptManager * interrupt_manager, common::OutputStream * error_message_stream) [virtual]
Select the driver for the device.
Parameters
driverManager device driver manager
interrupt_manager Interrupt manager
Returns
Driver for the device
Reimplemented from maxOS::drivers::DriverSelector.
Definition at line 159 of file pci.cpp.
{
    for (int bus = 0; bus < 8; ++bus) {
        for (int device = 0; device < 32; ++device) {
            int numFunctions = (device_has_functions(bus, device)) ? 8 : 1;
            for (int function = 0; function < numFunctions; ++function) {
                // Get the device descriptor, if the vendor id is 0x0000 or 0xFFFF, the device is not present/ready
                PeripheralComponentInterconnectDeviceDescriptor deviceDescriptor = get_device_descriptor(bus, device, function);
                if(deviceDescriptor.vendor_id == 0x0000 || deviceDescriptor.vendor_id == 0x0001 || deviceDescriptor.vendor_id == 0xFFFF)
                    continue;
                // Get port number
                for(int barNum = 5; barNum >= 0; barNum--){
                    BaseAddressRegister bar = get_base_address_register(bus, device, function, barNum);
                    if(bar.address && (bar.type == InputOutput))
                        deviceDescriptor.port_base = (uint32_t)bar.address;
                }
                // write to the debug stream
                m_debug_messages_stream->write(deviceDescriptor.get_type());
                m_debug_messages_stream->write(": ");
                // Select the driver and print information about the device
                Driver* driver = get_driver(deviceDescriptor, interrupt_manager);
                if(driver != 0){
                  handler->on_driver_selected(driver);
                  m_debug_messages_stream->write(driver->get_vendor_name());
                  m_debug_messages_stream->write(" ");
                  m_debug_messages_stream->write(driver->get_device_name());
                }else{
                  list_known_deivce(deviceDescriptor);
                }
                // New line
                m_debug_messages_stream->write("\n");
            }
        }
    }
}
References maxOS::hardwarecommunication::BaseAddressRegister::address, maxOS::drivers::Driver::get_device_name(), get_driver(), maxOS::hardwarecommunication::PeripheralComponentInterconnectDeviceDescriptor::get_type(), maxOS::drivers::Driver::get_vendor_name(), maxOS::hardwarecommunication::InputOutput, list_known_deivce(), maxOS::drivers::DriverSelectorEventHandler::on_driver_selected(), maxOS::hardwarecommunication::PeripheralComponentInterconnectDeviceDescriptor::port_base, maxOS::hardwarecommunication::BaseAddressRegister::type, maxOS::hardwarecommunication::PeripheralComponentInterconnectDeviceDescriptor::vendor_id, and maxOS::common::OutputStream::write().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/pci.h
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/pci.cpp