maxOS::system::SegmentDescriptor Class Reference
Stores data for the segment descriptors in the GDT.
#include <gdt.h>
Public Member Functions
SegmentDescriptor (uint32_t base, uint32_t limit, uint8_t type)
Constructor for Segment Selector.
uint32_t base ()
Look up the pointer.
uint32_t limit ()
Look up the limit.
Detailed Description
Stores data for the segment descriptors in the GDT.
Definition at line 18 of file gdt.h.
Constructor & Destructor Documentation
SegmentDescriptor()
SegmentDescriptor::SegmentDescriptor (uint32_t base, uint32_t limit, uint8_t type)
Constructor for Segment Selector.
Parameters
base base address
limit limit
flags Flags
Definition at line 18 of file gdt.cpp.
{
  uint8_t* target = (uint8_t*)this; //segment entry in GDT.
  if (limit <= 65536)
  {
    // 16-bit address space
    target[6] = 0x40;
  }
  else
  {
    // 32-bit address space
    if((limit & 0xFFF) != 0xFFF)
      limit = (limit >> 12)-1;
    else
      limit = limit >> 12;
    target[6] = 0xC0;
  }
  // Encode the limit
  target[0] = limit & 0xFF;
  target[1] = (limit >> 8) & 0xFF;
  target[6] |= (limit >> 16) & 0xF;
  // Encode the base
  target[2] = base & 0xFF;
  target[3] = (base >> 8) & 0xFF;
  target[4] = (base >> 16) & 0xFF;
  target[7] = (base >> 24) & 0xFF;
  // Type / Access Rights
  target[5] = type;
}
References base(), limit(), and type.
Member Function Documentation
base()
uint32_t SegmentDescriptor::base ()
Look up the pointer.
Returns
The pointer
Definition at line 57 of file gdt.cpp.
{
  uint8_t* target = (uint8_t*)this;
  uint32_t result = target[7];
  result = (result << 8) + target[4];
  result = (result << 8) + target[3];
  result = (result << 8) + target[2];
  return result;
}
Referenced by SegmentDescriptor().
limit()
uint32_t SegmentDescriptor::limit ()
Look up the limit.
Returns
The limit
Definition at line 74 of file gdt.cpp.
{
  uint8_t* target = (uint8_t*)this;
  uint32_t result = target[6] & 0xF;
  result = (result << 8) + target[1];
  result = (result << 8) + target[0];
  if((target[6] & 0xC0) == 0xC0)
    result = (result << 12) | 0xFFF;
  return result;
}
Referenced by SegmentDescriptor().
The documentation for this class was generated from the following files:
/home/runner/work/max-os/max-os/kernel/include/system/gdt.h
/home/runner/work/max-os/max-os/kernel/src/system/gdt.cpp