MaxOS::processes::GlobalResourceRegistry Class Reference
Manages all the resource registries for each resource type.
#include <resource.h>
Public Member Functions
GlobalResourceRegistry ()
Constructs a new GlobalResourceRegistry and sets it as the current global registry.
~GlobalResourceRegistry ()
Destructor for GlobalResourceRegistry, unsets it as the current global registry if it is.
Static Public Member Functions
static BaseResourceRegistry * get_registry (resource_type_t type)
Gets a registry of a type.
static void add_registry (resource_type_t type, BaseResourceRegistry *registry)
Adds a registry to the global list if there is not already one for that type.
static void remove_registry (BaseResourceRegistry *registry)
Adds a registry to the global list if there is not already one for that type.
Detailed Description
Manages all the resource registries for each resource type.
Definition at line 121 of file resource.h.
Constructor & Destructor Documentation
GlobalResourceRegistry()
GlobalResourceRegistry::GlobalResourceRegistry ()
Constructs a new GlobalResourceRegistry and sets it as the current global registry.
Definition at line 197 of file resource.cpp.
                                               {
    s_current = this;
}
~GlobalResourceRegistry()
GlobalResourceRegistry::~GlobalResourceRegistry ()
Destructor for GlobalResourceRegistry, unsets it as the current global registry if it is.
Definition at line 205 of file resource.cpp.
                                                {
    if(s_current == this)
        s_current = nullptr;
}
Member Function Documentation
add_registry()
void GlobalResourceRegistry::add_registry (resource_type_t type, BaseResourceRegistry * registry) [static]
Adds a registry to the global list if there is not already one for that type.
Parameters
type The type of registry being added
registry The registry to add
Definition at line 232 of file resource.cpp.
                                                                                              {
    // Does it already exist?
    if(s_current->m_registries.find(type) != s_current->m_registries.end())
        return;
    s_current->m_registries.insert(type, registry);
}
Referenced by MaxOS::processes::BaseResourceRegistry::BaseResourceRegistry().
get_registry()
BaseResourceRegistry * GlobalResourceRegistry::get_registry (resource_type_t type) [static]
Gets a registry of a type.
Parameters
type The type of registry to get
Returns
The registry or nullptr if not found
Definition at line 217 of file resource.cpp.
                                                                               {
    auto registry = s_current->m_registries.find(type);
    if(registry == s_current->m_registries.end())
        return nullptr;
    return registry->second;
}
Referenced by MaxOS::processes::ResourceManager::close_resource(), MaxOS::processes::ResourceManager::open_resource(), MaxOS::system::SyscallManager::syscall_resource_create(), MaxOS::filesystem::FileResource::write(), and MaxOS::filesystem::DirectoryResource::write().
remove_registry()
void GlobalResourceRegistry::remove_registry (BaseResourceRegistry * registry) [static]
Adds a registry to the global list if there is not already one for that type.
Parameters
registry The registry to add
Definition at line 246 of file resource.cpp.
                                                                           {
    // Does it already exist?
    if(s_current->m_registries.find(registry->type()) == s_current->m_registries.end())
        return;
    s_current->m_registries.erase(registry->type());
}
References MaxOS::processes::BaseResourceRegistry::type().
Referenced by MaxOS::processes::BaseResourceRegistry::~BaseResourceRegistry().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/processes/resource.h
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/resource.cpp