MaxOS::filesystem::FileSystem Class Reference
Handles the disk operations and file system information.
#include <filesystem.h>
Public Member Functions
virtual ~FileSystem ()
Destructor for FileSystem, frees the root directory (Which in turn frees all files and subdirectories)
Directory * root_directory ()
Get the directory at "/".
Directory * get_directory (const string &path)
Get the directory at a given path.
bool exists (const string &path)
Check if a path exists on the filesystem.
Protected Attributes
Directory * m_root_directory = nullptr
The fist directory in the file system (not be confused with the system root)
Detailed Description
Handles the disk operations and file system information.
Definition at line 96 of file filesystem.h.
Constructor & Destructor Documentation
~FileSystem()
FileSystem::~FileSystem () [virtual]
Destructor for FileSystem, frees the root directory (Which in turn frees all files and subdirectories)
Definition at line 285 of file filesystem.cpp.
                        {
    // Free the root directory
    delete m_root_directory;
}
References m_root_directory.
Member Function Documentation
exists()
bool FileSystem::exists (const string & path)
Check if a path exists on the filesystem.
Parameters
path The path to check
Returns
True if the path exists, false otherwise
Definition at line 342 of file filesystem.cpp.
                                          {
    // Get the directory at the path
    string directory_path = Path::file_path(path);
    Directory* directory = get_directory(directory_path);
    // Check if the directory exists
    if (!directory)
        return false;
    // Check if the file exists
    const string file_name = Path::file_name(path);
    return directory->open_file(file_name) != nullptr;
}
References MaxOS::filesystem::Path::file_name(), MaxOS::filesystem::Path::file_path(), get_directory(), and MaxOS::filesystem::Directory::open_file().
get_directory()
Directory * FileSystem::get_directory (const string & path)
Get the directory at a given path.
Parameters
path The path to the directory
Returns
The directory object or null if it could not be opened
Definition at line 307 of file filesystem.cpp.
                                                       {
    // Check if the path is the root
    if (path == "/")
        return root_directory();
    // Recursively open the directory
    Directory* directory = root_directory();
    string directory_path = path;
    while (directory_path.length() > 0) {
        // Get the name of the directory
        string directory_name = Path::top_directory(directory_path);
        // Open the directory
        Directory* subdirectory = directory->open_subdirectory(directory_name);
        if (!subdirectory)
            return nullptr;
        // Set the new directory
        directory = subdirectory;
        // Get the path to the next directory
        directory_path = directory_path.substring(directory_name.length() + 1, directory_path.length() - directory_name.length() - 1);
    }
    return directory;
}
References MaxOS::filesystem::Directory::open_subdirectory(), root_directory(), and MaxOS::filesystem::Path::top_directory().
Referenced by exists().
root_directory()
Directory * FileSystem::root_directory ()
Get the directory at "/".
Returns
The root directory of the filesystem
Definition at line 297 of file filesystem.cpp.
                                      {
    return m_root_directory;
}
References m_root_directory.
Referenced by get_directory().
Member Data Documentation
m_root_directory
Directory* MaxOS::filesystem::FileSystem::m_root_directory = nullptr [protected]
The fist directory in the file system (not be confused with the system root)
Definition at line 98 of file filesystem.h.
Referenced by MaxOS::filesystem::format::ext2::Ext2FileSystem::Ext2FileSystem(), MaxOS::filesystem::format::Fat32FileSystem::Fat32FileSystem(), root_directory(), MaxOS::filesystem::format::ext2::Ext2FileSystem::~Ext2FileSystem(), and ~FileSystem().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/filesystem.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/filesystem.cpp