MaxOS::drivers::ethernet::IntelI217 Class Reference
Driver for the Intel I217 Ethernet Controller.
#include <intel_i217.h>
Public Member Functions
IntelI217 (hardwarecommunication::PCIDeviceDescriptor *device_descriptor)
Constructs a new Intel I217 Ethernet driver. Gets the MAC address and clears the receive descriptor array.
uint32_t reset () final
Reset the driver.
void activate () final
Activate the driver.
void deactivate () final
Deactivate the driver.
void handle_interrupt () final
Handles an interrupt.
string vendor_name () final
Get who created the device.
string device_name () final
Get the device name of the driver.
void do_send (uint8_t *buffer, uint32_t size) final
(Device Side) send the data
uint64_t get_media_access_control_address () final
Get the MAC address.
Public Member Functions inherited from MaxOS::drivers::ethernet::EthernetDriver
void send (uint8_t *buffer, uint32_t size)
send data to the network via the driver backend
Public Member Functions inherited from MaxOS::drivers::Driver
virtual void initialise ()
Initialise the driver.
Public Member Functions inherited from MaxOS::common::EventManager< EthernetDriverEvents >
void connect_event_handler (EventHandler< EthernetDriverEvents > *handler)
connect an event handler to the event manager if it is not already connected
void disconnect_event_handler (EventHandler< EthernetDriverEvents > *handler)
disconnect an event handler from the event manager if it is connected
Vector< Event< EthernetDriverEvents > * > raise_event (Event< EthernetDriverEvents > *event)
Calls the on_event function of all the event m_handlers connected to the event manager and returns a list of the results.
Public Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
virtual system::cpu_status_t * handle_interrupt (system::cpu_status_t *status)
Handles an interrupt and returns the status.
Additional Inherited Members
Static Public Member Functions inherited from MaxOS::drivers::ethernet::EthernetDriver
static MediaAccessControlAddress create_media_access_control_address (uint8_t digit1, uint8_t digit2, uint8_t digit3, uint8_t digit4, uint8_t digit5, uint8_t digit6)
Create a Media Access Control Address.
Protected Member Functions inherited from MaxOS::drivers::ethernet::EthernetDriver
void fire_data_received (uint8_t *buffer, uint32_t size)
Handle the recieved data.
void fire_data_sent (uint8_t *buffer, uint32_t size)
send data
Protected Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
InterruptHandler (uint8_t interrupt_number, int64_t redirect=-1, uint64_t redirect_index=0)
Creates a new interrupt handler and registers it with the interrupt manager.
~InterruptHandler ()
Destroys the interrupt handler and unregisters it from the interrupt manager.
Protected Attributes inherited from MaxOS::common::EventManager< EthernetDriverEvents >
Vector< EventHandler< EthernetDriverEvents > * > m_handlers
Protected Attributes inherited from MaxOS::hardwarecommunication::InterruptHandler
uint8_t m_interrupt_number
The interrupt number this handler handles.
Detailed Description
Driver for the Intel I217 Ethernet Controller.
Definition at line 64 of file intel_i217.h.
Constructor & Destructor Documentation
IntelI217()
IntelI217::IntelI217 (hardwarecommunication::PCIDeviceDescriptor * device_descriptor) [explicit]
Constructs a new Intel I217 Ethernet driver. Gets the MAC address and clears the receive descriptor array.
Parameters
device_descriptor The PCI device descriptor for this device
Definition at line 33 of file intel_i217.cpp.
        : InterruptHandler(0x20 + device_descriptor->interrupt) {
    //Set the registers
    control_register = 0x0000;
    status_register = 0x0008;
    eprom_register = 0x0014;
    control_ext_register = 0x0018;
    interrupt_mask_register = 0x00D0;
    receive_control_register = 0x0100;
    receive_descriptor_low_register = 0x2800;
    receive_descriptor_high_register = 0x2804;
    receive_descriptor_length_register = 0x2808;
    receive_descriptor_head_register = 0x2810;
    receive_descriptor_tail_register = 0x2818;
    send_control_register = 0x0400;
    send_descriptor_low_register = 0x3800;
    send_descriptor_high_register = 0x3804;
    send_descriptor_length_register = 0x3808;
    send_descriptor_head_register = 0x3810;
    send_descriptor_tail_register = 0x3818;
    // Get BAR0 type, io_base address and MMIO base address
    bar_type = 1; // deviceDescriptor -> has_memory_base ? 0 : 1; @todo Fix memory mapping from PCI as it is unable to get MAC from memory
    port_base = device_descriptor->port_base;
    //TODO: memBase = deviceDescriptor -> memory_base;
    init_done = false;
    active = false;
    // Clear eprom
    eprom_present = detect_ee_prom();
    if (read_mac_address()) {
        own_mac = create_media_access_control_address(mac_address[0], mac_address[1], mac_address[2], mac_address[3],
                                                      mac_address[4], mac_address[5]);
    } else {
        ASSERT(false, "ERROR, INIT FAILED, MAC ADDRESS NOT FOUND");
    }
    for (int i = 0; i < 0x80; i++) //Loop through all the registers
        write(0x5200 + i * 4, 0); //Clear the receive descriptor array
}
References ASSERT, and MaxOS::drivers::ethernet::EthernetDriver::create_media_access_control_address().
Member Function Documentation
activate()
void IntelI217::activate () [final], [virtual]
Activate the driver.
Reimplemented from MaxOS::drivers::Driver.
Definition at line 298 of file intel_i217.cpp.
                         {
    //Enable interrupts
    write(interrupt_mask_register, 0x1F6DC); //Enable all interrupts
    write(interrupt_mask_register, 0xff & ~4); //Enable all interrupts except link status change
    read(0xc0); //Clear all interrupts
    //while (!initDone); //Wait for the init to be done
    //Initialise the send and receive descriptors
    receive_init();
    send_init();
    active = true; // Set active to true
}
deactivate()
void IntelI217::deactivate () [final], [virtual]
Deactivate the driver.
Reimplemented from MaxOS::drivers::Driver.
Definition at line 391 of file intel_i217.cpp.
                           {
    Driver::deactivate();
}
References MaxOS::drivers::Driver::deactivate().
device_name()
string IntelI217::device_name () [final], [virtual]
Get the device name of the driver.
Returns
The device name of the driver
Reimplemented from MaxOS::drivers::Driver.
Definition at line 399 of file intel_i217.cpp.
                              {
    return "E1000 (i217)";
}
do_send()
void IntelI217::do_send (uint8_t * buffer, uint32_t size) [final], [virtual]
(Device Side) send the data
Parameters
buffer The buffer to handle
size The size of the buffer
Reimplemented from MaxOS::drivers::ethernet::EthernetDriver.
Definition at line 356 of file intel_i217.cpp.
                                                      {
    while (!active);
    //Put params into send buffer
    send_dsrctrs[current_send_buffer]->buffer_address = (uint64_t) buffer;
    send_dsrctrs[current_send_buffer]->length = size;
    //Set the commands
    send_dsrctrs[current_send_buffer]->cmd = (1 << 0) // End of Packet
                                          | (1 << 1) // Insert FCS
                                          | (1 << 3) // Report Status
            ;
    send_dsrctrs[current_send_buffer]->status = 0;
    uint8_t old_cur = current_send_buffer; //Save the current send buffer
    current_send_buffer = (current_send_buffer + 1) % 8; //Increment the current send buffer
    write(send_descriptor_tail_register, current_send_buffer); //write the current send buffer to the tail register
    //Wait for the packet to be sent
    while (!(send_dsrctrs[old_cur]->status & 0xff));
}
get_media_access_control_address()
uint64_t IntelI217::get_media_access_control_address () [final], [virtual]
Get the MAC address.
Returns
the MAC address
Reimplemented from MaxOS::drivers::ethernet::EthernetDriver.
Definition at line 381 of file intel_i217.cpp.
                                                     {
    while (own_mac == 0);
    return own_mac;
}
handle_interrupt()
void IntelI217::handle_interrupt () [final], [virtual]
Handles an interrupt.
Reimplemented from MaxOS::hardwarecommunication::InterruptHandler.
Definition at line 316 of file intel_i217.cpp.
                                 {
    write(interrupt_mask_register, 0x1); //Clear the interrupt or it will hang
    uint32_t temp = read(0xc0); //read the interrupt status register
    // if(temp & 0x04)
    // m_driver_message_stream-> write("INTEL i217 START LINK");//initDone = true;
    //
    // if(temp & 0x10)
    // m_driver_message_stream-> write("INTEL i217 GOOD THRESHOLD");
    if (temp & 0x80) fetch_data_received();
}
reset()
uint32_t IntelI217::reset () [final], [virtual]
Reset the driver.
Returns
How long in milliseconds it took to reset the driver
Reimplemented from MaxOS::drivers::Driver.
Definition at line 387 of file intel_i217.cpp.
                          {
    return Driver::reset();
}
References MaxOS::drivers::Driver::reset().
vendor_name()
string IntelI217::vendor_name () [final], [virtual]
Get who created the device.
Returns
The vendor name of the driver
Reimplemented from MaxOS::drivers::Driver.
Definition at line 395 of file intel_i217.cpp.
                              {
    return "Intel";
}
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/ethernet/intel_i217.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/ethernet/intel_i217.cpp