maxOS::net::UserDatagramProtocolHandler Class Reference
#include <udp.h>
Public Member Functions
UserDatagramProtocolHandler (InternetProtocolHandler *internetProtocolHandler, common::OutputStream *errorMessages)
~UserDatagramProtocolHandler ()
virtual bool handleInternetProtocolPayload (InternetProtocolAddress sourceIP, InternetProtocolAddress destinationIP, uint8_t *payloadData, uint32_t size)
Handle the recivement of an UDP packet.
UserDatagramProtocolSocket * Connect (uint32_t ip, uint16_t port)
UserDatagramProtocolSocket * Connect (string internetProtocolAddressAndPort)
UserDatagramProtocolSocket * Listen (uint16_t port)
Listens for incoming packets on the port.
void Disconnect (UserDatagramProtocolSocket *socket)
Disconnects the socket from the remote IP and port.
void Send (UserDatagramProtocolSocket *socket, uint8_t *data, uint16_t size)
Sends a packet to the remote IP and port.
void Bind (UserDatagramProtocolSocket *socket, UserDatagramProtocolPayloadHandler *userDatagramProtocolPayloadHandler)
Binds a handler to the socket.
Protected Attributes
common::Vector< UserDatagramProtocolSocket * > sockets
common::OutputStream * errorMessages
Static Protected Attributes
static UserDatagramProtocolPort freePorts = 0x8000
Provider
Detailed Description
Definition at line 86 of file udp.h.
Constructor & Destructor Documentation
UserDatagramProtocolHandler()
UserDatagramProtocolHandler::UserDatagramProtocolHandler (InternetProtocolHandler * internetProtocolHandler, common::OutputStream * errorMessages)
Definition at line 74 of file udp.cpp.
: InternetProtocolPayloadHandler(internetProtocolHandler, 0x11) //0x11 is the UDP protocol number
{
    this -> errorMessages = errorMessages;
}
References errorMessages.
 UserDatagramProtocolHandler()
UserDatagramProtocolHandler::~UserDatagramProtocolHandler ()
Definition at line 80 of file udp.cpp.
                                                          {
}
Member Function Documentation
Bind()
void UserDatagramProtocolHandler::Bind (UserDatagramProtocolSocket * socket, UserDatagramProtocolPayloadHandler * userDatagramProtocolPayloadHandler)
Binds a handler to the socket.
Parameters
socket The socket to bind the handler to
userDatagramProtocolHandler The handler to bind
Definition at line 291 of file udp.cpp.
                                                                                                                                                 {
  socket->m_handlers.push_back(
      userDatagramProtocolPayloadHandler); //Set the handler of the socket to the handler that was passed in
}
References maxOS::common::EventManager< EventType >::m_handlers.
Connect() [1/2]
UserDatagramProtocolSocket * UserDatagramProtocolHandler::Connect (string internetProtocolAddressAndPort)
Definition at line 165 of file udp.cpp.
                                                                                                      {
    // Find the colon (:) character in the input string
    string colonPosition = (string)internetProtocolAddressAndPort;
    for (; *colonPosition != '\0'; colonPosition++) {
        if (*colonPosition == ':') {
            // Break the loop if a colon is found
            break;
        }
    }
    // If no colon is found, return 0
    if (*colonPosition != ':') {
        return 0;
    }
    // Parse the InternetProtocolAddress from the input string
    InternetProtocolAddress remoteAddress = InternetProtocolHandler::Parse(internetProtocolAddressAndPort);
    // Initialize the TransmissionControlProtocolPort to 0
    UserDatagramProtocolPort port = 0;
    // Iterate through the string after the colon to extract the port number
    for (colonPosition++; *colonPosition != '\0'; colonPosition++) {
        if ('0' <= *colonPosition && *colonPosition <= '9') {
            // Calculate the port number by converting characters to integers
            port = port * 10 + (*colonPosition - '0');
        }
    }
    // Connect to the remote address and port
    return Connect(remoteAddress, port);
}
References Connect(), maxOS::net::InternetProtocolHandler::Parse(), and maxOS::string.
Connect() [2/2]
UserDatagramProtocolSocket * UserDatagramProtocolHandler::Connect (uint32_t ip, uint16_t port)
Connects the socket to the remote IP and port
Parameters
ip The remote IP address in big endian
port The remote port
Returns
The socket that was connected
Definition at line 143 of file udp.cpp.
                                                                                           {
    UserDatagramProtocolSocket* socket = (UserDatagramProtocolSocket*)MemoryManager::s_active_memory_manager-> malloc(sizeof(UserDatagramProtocolSocket)); //Allocate memory for the socket
    if(socket != 0) //If the socket was created
    {
        new (socket) UserDatagramProtocolSocket(); //Create the socket
        //Configure the socket
        socket -> remotePort = port; //Port to that application wants to connect to
        socket -> remoteIP = ip; //IP to that application wants to connect to
        socket -> localPort = freePorts++; //Port that we will use to connect to the remote application (note, local port doesnt have to be the same as remote)
        socket -> localIP = internetProtocolHandler -> GetInternetProtocolAddress(); //IP that we will use to connect to the remote application
        socket -> userDatagramProtocolHandler = this; //Set the UDP handler
        sockets.push_back(socket); //Add the socket to the list of sockets
    }
    return socket; //Return the socket
}
References freePorts, maxOS::net::InternetProtocolPayloadHandler::internetProtocolHandler, and sockets.
Referenced by Connect().
Disconnect()
void UserDatagramProtocolHandler::Disconnect (UserDatagramProtocolSocket * socket)
Disconnects the socket from the remote IP and port.
Parameters
socket The socket to disconnect
Definition at line 231 of file udp.cpp.
                                                                               {
    for(Vector<UserDatagramProtocolSocket*>::iterator currentSocket = sockets.begin(); currentSocket != sockets.end(); currentSocket++) {
        if((*currentSocket) == socket) //If the socket is the same as the socket that is being checked
        {
            sockets.erase(currentSocket); //Remove the socket from the list of sockets
            MemoryManager::s_active_memory_manager-> free(socket); //Free the socket
            break; //Break out of the loop
        }
    }
}
References sockets.
handleInternetProtocolPayload()
bool UserDatagramProtocolHandler::handleInternetProtocolPayload (InternetProtocolAddress sourceIP, InternetProtocolAddress destinationIP, uint8_t * payloadData, uint32_t size) [virtual]
Handle the recivement of an UDP packet.
Parameters
srcIP_BE The source IP address in big endian
dstIP_BE The destination IP address in big endian
internetprotocolPayload The UDP payload
size The size of the UDP payload
Returns
True if the packet is to be sent back to the sender
Reimplemented from maxOS::net::InternetProtocolPayloadHandler.
Definition at line 92 of file udp.cpp.
                                                                                                                                                                            {
    //Check the size
    if(size < sizeof(UserDatagramProtocolHeader)) {
        return false;
    }
    //Get the header
    UserDatagramProtocolHeader* header = (UserDatagramProtocolHeader*)payloadData;
    //Set the local and remote ports
    uint16_t localPort = header -> destinationPort;
    uint16_t remotePort = header -> sourcePort;
    UserDatagramProtocolSocket* socket = 0; //The socket that will be used
    for(Vector<UserDatagramProtocolSocket*>::iterator currentSocket = sockets.begin(); currentSocket != sockets.end(); currentSocket++) {
        if((*currentSocket)->localPort == localPort //If the local port (header dst, our port) is the same as the local port of the socket
        && (*currentSocket)->localIP == destinationIP //If the local IP (packet dst, our IP) is the same as the local IP of the socket
        && (*currentSocket)->listening) //If the socket is listening
        {
            socket = (*currentSocket); //Set the socket to the socket that is being checked
            socket->listening = false; //Set the socket to not listening, as it is now in use
            socket->remotePort = remotePort; //Set the remote port of the socket to the remote port of the packet
            socket->remoteIP = sourceIP; //Set the remote IP of the socket to the remote IP of the packet
        }else if((*currentSocket)->localPort == localPort //If the local port (header dst, our port) is the same as the local port of the socket
              && (*currentSocket)->localIP == destinationIP //If the local IP (packet dst, our IP) is the same as the local IP of the socket
              && (*currentSocket)->remotePort == remotePort //If the remote port (header src, their port) is the same as the remote port of the socket
              && (*currentSocket)->remoteIP == sourceIP) //If the remote IP (packet src, their IP) is the same as the remote IP of the socket
        {
            socket = (*currentSocket); //Set the socket to the current socket
        }
    }
    if(socket != 0) { //If the socket is not null then pass the data to the socket
        socket->handleUserDatagramProtocolPayload(payloadData + sizeof(UserDatagramProtocolHeader), size - sizeof(UserDatagramProtocolHeader));
    }
    //UDP doesn't send back packets, so always return false
    return false;
}
References destinationIP, destinationPort, maxOS::net::UserDatagramProtocolSocket::handleUserDatagramProtocolPayload(), maxOS::net::UserDatagramProtocolSocket::listening, maxOS::net::UserDatagramProtocolSocket::remoteIP, maxOS::net::UserDatagramProtocolSocket::remotePort, size, sockets, sourceIP, and sourcePort.
Listen()
UserDatagramProtocolSocket * UserDatagramProtocolHandler::Listen (uint16_t port)
Listens for incoming packets on the port.
Parameters
port The port to listen on
Returns
The socket that is listening
Definition at line 205 of file udp.cpp.
                                                                             {
    UserDatagramProtocolSocket* socket = (UserDatagramProtocolSocket*)MemoryManager::s_active_memory_manager-> malloc(sizeof(UserDatagramProtocolSocket)); //Allocate memory for the socket
    if(socket != 0) //If the socket was created
    {
        new (socket) UserDatagramProtocolSocket(); //Create the socket
        //Configure the socket
        socket -> listening = true; //Set the socket to listening
        socket -> localPort = port; //Port that we will use to connect to the remote application (note, local port doesnt have to be the same as remote)
        socket -> localIP = internetProtocolHandler -> GetInternetProtocolAddress(); //IP that we will use to connect to the remote application
        socket -> userDatagramProtocolHandler = this; //Set the UDP handler
        sockets.push_back(socket); //Add the socket to the list of sockets
    }
    return socket; //Return the socket
}
References maxOS::net::InternetProtocolPayloadHandler::internetProtocolHandler, and sockets.
Send()
void UserDatagramProtocolHandler::Send (UserDatagramProtocolSocket * socket, uint8_t * data, uint16_t size)
Sends a packet to the remote IP and port.
Parameters
socket The socket to send the packet from
data The data to send
size The size of the data
Definition at line 252 of file udp.cpp.
                                                                                                       {
    uint16_t totalSize = sizeof(UserDatagramProtocolHeader) + size; //Get the total size of the packet
    uint8_t* buffer = (uint8_t*)MemoryManager::s_active_memory_manager->malloc(totalSize); //Allocate memory for the packet
    uint8_t* buffer2 = buffer + sizeof(UserDatagramProtocolHeader); //Get the buffer that will be used to store the data
    UserDatagramProtocolHeader* header = (UserDatagramProtocolHeader*)buffer; //Create the header of the packet
    //Set the header
    header -> sourcePort = socket -> localPort; //Set the source port to the local port of the socket (this is the port that the packet will be sent from)
    header -> destinationPort = socket -> remotePort; //Set the destination port to the remote port of the socket (this is the port that the packet will be sent to)
    header -> length = ((totalSize & 0x00FF) << 8) | ((totalSize & 0xFF00) >> 8); //Set the length of the packet
    // Convert the ports into big endian
    header -> sourcePort = ((header -> sourcePort & 0x00FF) << 8) | ((header -> sourcePort & 0xFF00) >> 8);
    header -> destinationPort = ((header -> destinationPort & 0x00FF) << 8) | ((header -> destinationPort & 0xFF00) >> 8);
    //Copy the data to the buffer
    for (int i = 0; i < size; ++i) { //Loop through the data
        buffer2[i] = data[i]; //Copy the data to the buffer
    }
    //Set the checksum
    header -> checksum = 0; //Set the checksum to 0, this is becuase UDP doesnt have to have a checksum
    //Send the packet
    InternetProtocolPayloadHandler::Send(socket->remoteIP, buffer, totalSize);
    //Free the buffer
    MemoryManager::s_active_memory_manager->free(buffer);
}
References checksum, data, destinationPort, maxOS::drivers::peripherals::i, length, maxOS::net::UserDatagramProtocolSocket::remoteIP, maxOS::net::InternetProtocolPayloadHandler::Send(), size, and sourcePort.
Member Data Documentation
errorMessages
common::OutputStream* maxOS::net::UserDatagramProtocolHandler::errorMessages [protected]
Definition at line 91 of file udp.h.
Referenced by UserDatagramProtocolHandler().
freePorts
UserDatagramProtocolPort UserDatagramProtocolHandler::freePorts = 0x8000 [static], [protected]
Provider
Definition at line 90 of file udp.h.
Referenced by Connect().
sockets
common::Vector<UserDatagramProtocolSocket*> maxOS::net::UserDatagramProtocolHandler::sockets [protected]
Definition at line 89 of file udp.h.
Referenced by Connect(), Disconnect(), handleInternetProtocolPayload(), and Listen().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/net/udp.h
/home/runner/work/MaxOS/MaxOS/kernel/src/net/udp.cpp