MaxOS::processes::ResourceManager Class Reference
Manages the open resources for a process.
#include <resource.h>
Public Member Functions
~ResourceManager ()
Destructor for ResourceManager, closes all open resources.
common::Map< uint64_t, Resource * > resources ()
Get the resources currently open.
uint64_t open_resource (resource_type_t type, const string &name, size_t flags)
Registers a resource with the resource manager and then opens it.
void close_resource (uint64_t handle, size_t flags)
Un registers the resource and then closes it.
Resource * get_resource (uint64_t handle)
Gets a resource based on the handle id.
Resource * get_resource (const string &name)
Finds a resource by name.
Detailed Description
Manages the open resources for a process.
Definition at line 141 of file resource.h.
Constructor & Destructor Documentation
~ResourceManager()
ResourceManager::~ResourceManager ()
Destructor for ResourceManager, closes all open resources.
Definition at line 261 of file resource.cpp.
                                 {
    // Collect all resources (as closing will break iteration)
    common::Vector<uint64_t> handles;
    for (const auto& kv : m_resources)
        handles.push_back(kv.first);
    // Close the resources
    for (auto h : handles)
        close_resource(h, 0);
}
References close_resource().
Member Function Documentation
close_resource()
void ResourceManager::close_resource (uint64_t handle, size_t flags)
Un registers the resource and then closes it.
Parameters
handle The handle number of the resource
flags Flags to pass to the closing
Definition at line 313 of file resource.cpp.
                                                                  {
    auto it = m_resources.find(handle);
    if(it == m_resources.end())
        return;
    // Remove it
    Resource* resource = it->second;
    m_resources.erase(handle);
    // Close it
    GlobalResourceRegistry::get_registry(resource->type()) -> close_resource(resource, flags);
}
References close_resource(), MaxOS::processes::GlobalResourceRegistry::get_registry(), and MaxOS::processes::Resource::type().
Referenced by close_resource(), and ~ResourceManager().
get_resource() [1/2]
Resource * ResourceManager::get_resource (const string & name)
Finds a resource by name.
Parameters
name The name of the resource
Returns
The resource or nullptr if not found
Definition at line 347 of file resource.cpp.
                                                          {
    for(const auto& resource : m_resources)
        if(resource.second->name() == name)
            return resource.second;
    return nullptr;
}
get_resource() [2/2]
Resource * ResourceManager::get_resource (uint64_t handle)
Gets a resource based on the handle id.
Parameters
handle The handle number of the resource
Returns
The resource or nullptr if not found
Definition at line 333 of file resource.cpp.
                                                       {
    if(m_resources.find(handle) == m_resources.end())
        return nullptr;
    return m_resources[handle];
}
Referenced by open_resource().
open_resource()
uint64_t ResourceManager::open_resource (resource_type_t type, const string & name, size_t flags)
Registers a resource with the resource manager and then opens it.
Parameters
type The type of resource to register
name The name of the resource
flags Per resource flags for opening
Returns
The handle id of the resource or 0 if failed
Definition at line 292 of file resource.cpp.
                                                                                              {
    // Get the resource
    auto resource = GlobalResourceRegistry::get_registry(type) -> get_resource(name);
    if(!resource)
        return 0;
    // Store it
    m_resources.insert(m_next_handle, resource);
    // Open it
    resource->open(flags);
    return m_next_handle++;
}
References MaxOS::processes::GlobalResourceRegistry::get_registry(), and get_resource().
resources()
common::Map< uint64_t, Resource * > ResourceManager::resources ()
Get the resources currently open.
Returns
The resources
Definition at line 279 of file resource.cpp.
                                                          {
    return m_resources;
}
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/processes/resource.h
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/resource.cpp