MaxOS::filesystem::format::Fat32File Class Reference
Handles the file operations on the FAT32 filesystem.
#include <fat32.h>
Public Member Functions
Fat32File (Fat32Volume *volume, Fat32Directory *parent, dir_entry_t *info, const string &name)
Construct a new Fat32 File object.
void write (common::buffer_t *data, size_t amount) final
write data to the file (at the current seek position, updated to be += amount)
void read (common::buffer_t *data, size_t amount) final
read data from the file (at the current seek position, updated to be += amount)
void flush () final
Flush the file to the disk.
uint32_t first_cluster () const
Get the first cluster of the directory.
Public Member Functions inherited from MaxOS::filesystem::File
void seek (SeekType seek_type, size_t offset)
Seek to a position in the file.
uint32_t position () const
Get where the file is currently at (amount read/write/seeked)
size_t size () const
Get the size of the file.
string name ()
Get the name of the file.
Additional Inherited Members
Protected Attributes inherited from MaxOS::filesystem::File
uint32_t m_offset = 0
The current offset in the file.
string m_name
The name of the file.
size_t m_size = 0
The size of the file.
Detailed Description
Handles the file operations on the FAT32 filesystem.
Definition at line 207 of file fat32.h.
Constructor & Destructor Documentation
Fat32File()
Fat32File::Fat32File (Fat32Volume * volume, Fat32Directory * parent, dir_entry_t * info, const string & name)
Construct a new Fat32 File object.
Parameters
volume The helper volume object
parent The directory that contains this file
info The directory entry information that describes this file
name The name of the file
Definition at line 239 of file fat32.cpp.
        : m_volume(volume),
        m_parent_directory(parent),
        m_entry(info),
        m_first_cluster((info->first_cluster_high << 16) | info->first_cluster_low) {
    m_name = name;
    m_size = info->size;
    m_offset = 0;
}
References MaxOS::filesystem::File::m_name, MaxOS::filesystem::File::m_offset, MaxOS::filesystem::File::m_size, and MaxOS::filesystem::File::name().
Member Function Documentation
first_cluster()
uint32_t MaxOS::filesystem::format::Fat32File::first_cluster () const [inline]
Get the first cluster of the directory.
Returns
The first cluster of the directory
Definition at line 228 of file fat32.h.
{ return m_first_cluster; }
flush()
void Fat32File::flush () [final], [virtual]
Flush the file to the disk.
Reimplemented from MaxOS::filesystem::File.
Definition at line 413 of file fat32.cpp.
                      {
    File::flush();
}
References MaxOS::filesystem::File::flush().
read()
void Fat32File::read (common::buffer_t * data, size_t amount) [final], [virtual]
read data from the file (at the current seek position, updated to be += amount)
Parameters
data The byte buffer to read into
amount The amount of data to read
Reimplemented from MaxOS::filesystem::File.
Definition at line 361 of file fat32.cpp.
                                                  {
    size_t buffer_space = m_volume->bpb.bytes_per_sector * m_volume->bpb.sectors_per_cluster;
    buffer_t buffer(buffer_space);
    buffer.clear();
    uint64_t current_offset = 0;
    uint64_t bytes_read = 0;
    // Read the file
    for(uint32_t cluster = m_first_cluster;
        cluster != (uint32_t) ClusterState::END_OF_CHAIN; cluster = m_volume->next_cluster(cluster)) {
        // Skip clusters before the offset
        if((current_offset + buffer_space) < m_offset) {
            current_offset += buffer_space;
            continue;
        }
        // Read each sector in the cluster
        lba_t lba = m_volume->data_lba + (cluster - 2) * m_volume->bpb.sectors_per_cluster;
        for(size_t sector = 0; sector < m_volume->bpb.sectors_per_cluster; sector++)
            m_volume->disk->read(lba + sector, &buffer, m_volume->bpb.bytes_per_sector);
        buffer.set_offset(0);
        // If the offset is in the middle of the cluster
        size_t buffer_offset = 0;
        if(m_offset > current_offset)
            buffer_offset = m_offset - current_offset;
        // Calculate how many bytes are being copied (read from cluster at offset? or read part of cluster?)
        size_t cluster_remaining_bytes = buffer_space - buffer_offset;
        size_t data_remaining_bytes = amount - bytes_read;
        size_t bytes_to_copy = (cluster_remaining_bytes < data_remaining_bytes) ? cluster_remaining_bytes
                                                                                : data_remaining_bytes;
        bytes_to_copy = (bytes_to_copy > buffer_space) ? buffer_space : bytes_to_copy;
        // Read the data
        buffer.copy_from(data, bytes_to_copy, buffer_offset, bytes_read);
        bytes_read += bytes_to_copy;
        current_offset += buffer_space;
        // Dont read more than needed
        if(bytes_read >= amount)
            break;
    }
    m_offset += bytes_read;
}
References MaxOS::filesystem::format::Fat32Volume::bpb, MaxOS::common::Buffer::clear(), MaxOS::common::Buffer::copy_from(), MaxOS::filesystem::format::Fat32Volume::data_lba, MaxOS::filesystem::format::Fat32Volume::disk, MaxOS::filesystem::File::m_offset, MaxOS::filesystem::format::Fat32Volume::next_cluster(), MaxOS::drivers::disk::Disk::read(), and MaxOS::common::Buffer::set_offset().
write()
void Fat32File::write (common::buffer_t * data, size_t amount) [final], [virtual]
write data to the file (at the current seek position, updated to be += amount)
Parameters
data The byte buffer to write
amount The amount of data to write
Todo
Todo When in userspace: save timestamps
Reimplemented from MaxOS::filesystem::File.
Definition at line 260 of file fat32.cpp.
                                                   {
    size_t buffer_space = m_volume->bpb.bytes_per_sector * m_volume->bpb.sectors_per_cluster;
    buffer_t buffer(buffer_space);
    buffer.clear();
    uint64_t current_offset = 0;
    uint64_t bytes_written = 0;
    uint32_t last = m_first_cluster;
    // Read the file
    for(uint32_t cluster = last;
        cluster != (uint32_t) ClusterState::END_OF_CHAIN; cluster = m_volume->next_cluster(cluster)) {
        last = cluster;
        // No cluster to read from (blank file)
        if(cluster == 0)
            break;
        // Skip clusters before the offset
        if((current_offset + buffer_space) < m_offset) {
            current_offset += buffer_space;
            continue;
        }
        // Read each sector in the cluster (prevent overwriting the data)
        lba_t lba = m_volume->data_lba + (cluster - 2) * m_volume->bpb.sectors_per_cluster;
        for(size_t sector = 0; sector < m_volume->bpb.sectors_per_cluster; sector++)
            m_volume->disk->read(lba + sector, &buffer, m_volume->bpb.bytes_per_sector);
        buffer.set_offset(0);
        // If the offset is in the middle of the cluster
        size_t buffer_offset = 0;
        if(m_offset > current_offset)
            buffer_offset = m_offset - current_offset;
        // Calculate how many bytes are being copied (read from cluster at offset?
        // or read part of cluster?)
        size_t cluster_remaining_bytes = buffer_space - buffer_offset;
        size_t data_remaining_bytes = amount - bytes_written;
        size_t bytes_to_copy = (cluster_remaining_bytes < data_remaining_bytes) ? cluster_remaining_bytes
                                                                                : data_remaining_bytes;
        bytes_to_copy = (bytes_to_copy > buffer_space) ? buffer_space : bytes_to_copy;
        // Update the data
        buffer.copy_from(data, bytes_to_copy, buffer_offset, bytes_written);
        bytes_written += bytes_to_copy;
        current_offset += bytes_to_copy;
        buffer.set_offset(0);
        // Write the data back to the disk
        for(size_t sector = 0; sector < m_volume->bpb.sectors_per_cluster; sector++)
            m_volume->disk->write(lba + sector, &buffer, m_volume->bpb.bytes_per_sector);
    }
    // Extend the file
    while(bytes_written < amount) {
        // Allocate a new cluster
        uint32_t new_cluster = m_volume->allocate_cluster(last);
        if(new_cluster == 0)
            break;
        if(last == 0)
            m_first_cluster = new_cluster;
        // Update the data
        size_t bytes_to_copy = (amount - bytes_written) > buffer_space ? buffer_space : (amount - bytes_written);
        buffer.copy_from(data, bytes_to_copy, 0, bytes_written);
        bytes_written += bytes_to_copy;
        current_offset += bytes_to_copy;
        buffer.set_offset(0);
        // Write the data back to the disk
        lba_t lba = m_volume->data_lba + (new_cluster - 2) * m_volume->bpb.sectors_per_cluster;
        for(size_t sector = 0; sector < m_volume->bpb.sectors_per_cluster; sector++)
            m_volume->disk->write(lba + sector, &buffer, m_volume->bpb.bytes_per_sector);
        // Go to the next cluster
        last = new_cluster;
    }
    // Update file size
    m_offset += bytes_written;
    if(m_offset > m_size)
        m_size = m_offset;
    // Update entry info
    m_entry->size = m_size;
    m_entry->first_cluster_high = (m_first_cluster >> 16) & 0xFFFF;
    m_entry->first_cluster_low = m_first_cluster & 0xFFFF;
    m_parent_directory->save_entry_to_disk(m_entry);
}
References MaxOS::filesystem::format::Fat32Volume::allocate_cluster(), MaxOS::filesystem::format::Fat32Volume::bpb, MaxOS::common::Buffer::clear(), MaxOS::common::Buffer::copy_from(), MaxOS::filesystem::format::Fat32Volume::data_lba, MaxOS::filesystem::format::Fat32Volume::disk, MaxOS::filesystem::File::m_offset, MaxOS::filesystem::File::m_size, MaxOS::filesystem::format::Fat32Volume::next_cluster(), MaxOS::drivers::disk::Disk::read(), MaxOS::filesystem::format::Fat32Directory::save_entry_to_disk(), MaxOS::common::Buffer::set_offset(), and MaxOS::drivers::disk::Disk::write().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/format/fat32.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/format/fat32.cpp