MaxOS::filesystem::VFSResourceRegistry Class Reference
A resource registry for both Files & Directories.
#include <vfsresource.h>
Public Member Functions
VFSResourceRegistry (VirtualFileSystem *vfs)
Construct a new VFS Resource Registry object.
processes::Resource * get_resource (const string &name) final
Gets a resource from the registry by name.
processes::Resource * create_resource (const string &name, size_t flags) final
Try to create a new resource with the specified name, will fail if the name is in use.
Detailed Description
A resource registry for both Files & Directories.
Definition at line 72 of file vfsresource.h.
Constructor & Destructor Documentation
VFSResourceRegistry()
VFSResourceRegistry::VFSResourceRegistry (VirtualFileSystem * vfs) [explicit]
Construct a new VFS Resource Registry object.
Parameters
vfs The virtual file system to use
Definition at line 324 of file vfsresource.cpp.
: BaseResourceRegistry(resource_type_t::FILESYSTEM),
  m_vfs(vfs)
{
}
Member Function Documentation
create_resource()
Resource * VFSResourceRegistry::create_resource (const string & name, size_t flags) [final], [virtual]
Try to create a new resource with the specified name, will fail if the name is in use.
Parameters
name The name of the resource to create
flags Optional flags to pass (unused by default but registry type specific)
Returns
The resource created or nullptr if failed to create the resource
Reimplemented from MaxOS::processes::BaseResourceRegistry.
Definition at line 394 of file vfsresource.cpp.
                                                                               {
    string path = Path::absolute_path(name);
    path = Path::join_path(GlobalScheduler::current_process()->working_directory, path);
    // Resource already opened
    auto resource = BaseResourceRegistry::get_resource(path);
    if(resource != nullptr)
        return resource;
    // Open the resource
    bool is_file = Path::is_file(path);
    if(is_file)
        return open_as_resource(path, m_vfs->create_file(path));
    else
        return open_as_resource(path, m_vfs->create_directory(path));
}
References MaxOS::filesystem::Path::absolute_path(), MaxOS::filesystem::VirtualFileSystem::create_directory(), MaxOS::filesystem::VirtualFileSystem::create_file(), MaxOS::processes::GlobalScheduler::current_process(), MaxOS::processes::BaseResourceRegistry::get_resource(), MaxOS::filesystem::Path::is_file(), and MaxOS::filesystem::Path::join_path().
get_resource()
Resource * VFSResourceRegistry::get_resource (const string & name) [final], [virtual]
Gets a resource from the registry by name.
Parameters
name The name of the resource to find
Returns
The resource or nullptr if the resource was not found
Reimplemented from MaxOS::processes::BaseResourceRegistry.
Definition at line 376 of file vfsresource.cpp.
                                                              {
    string path = Path::absolute_path(name);
    path = Path::join_path(GlobalScheduler::current_process()->working_directory, path);
    // Resource already opened
    auto resource = BaseResourceRegistry::get_resource(path);
    if(resource != nullptr)
        return resource;
    // Open the resource
    bool is_file = Path::is_file(path);
    if(is_file)
        return open_as_resource(path, m_vfs->open_file(path));
    else
        return open_as_resource(path, m_vfs->open_directory(path));
}
References MaxOS::filesystem::Path::absolute_path(), MaxOS::processes::GlobalScheduler::current_process(), MaxOS::processes::BaseResourceRegistry::get_resource(), MaxOS::filesystem::Path::is_file(), MaxOS::filesystem::Path::join_path(), MaxOS::filesystem::VirtualFileSystem::open_directory(), and MaxOS::filesystem::VirtualFileSystem::open_file().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/vfsresource.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/vfsresource.cpp