MaxOS::net::InternetProtocolPayloadHandler Class Reference
#include <ipv4.h>
Public Member Functions
InternetProtocolPayloadHandler (InternetProtocolHandler *internetProtocolHandler, uint8_t protocol)
Payload Handler///
~InternetProtocolPayloadHandler ()
virtual bool handleInternetProtocolPayload (InternetProtocolAddress sourceIP, InternetProtocolAddress destinationIP, uint8_t *payloadData, uint32_t size)
Called when an IP packet is received. (Deafult, does nothing, overide for use)
void Send (InternetProtocolAddress destinationIP, uint8_t *payloadData, uint32_t size)
Sends an IP packet.
Protected Attributes
InternetProtocolHandler * internetProtocolHandler
uint8_t ipProtocol
Friends
class InternetProtocolHandler
Detailed Description
Definition at line 46 of file ipv4.h.
Constructor & Destructor Documentation
InternetProtocolPayloadHandler()
InternetProtocolPayloadHandler::InternetProtocolPayloadHandler (InternetProtocolHandler * internetProtocolHandler, uint8_t protocol)
Payload Handler///
Definition at line 39 of file ipv4.cpp.
                                                                                                                                 {
    // Store vars
    this -> internetProtocolHandler = internetProtocolHandler;
    this -> ipProtocol = protocol;
    //Register handler
    internetProtocolHandler ->connectInternetProtocolPayloadHandler(this);
}
References MaxOS::net::InternetProtocolHandler::connectInternetProtocolPayloadHandler(), internetProtocolHandler, ipProtocol, and protocol.
~InternetProtocolPayloadHandler()
InternetProtocolPayloadHandler::~InternetProtocolPayloadHandler () [default]
Member Function Documentation
handleInternetProtocolPayload()
bool InternetProtocolPayloadHandler::handleInternetProtocolPayload (net::InternetProtocolAddress sourceIP, net::InternetProtocolAddress destinationIP, uint8_t * payloadData, uint32_t size) [virtual]
Called when an IP packet is received. (Deafult, does nothing, overide for use)
Parameters
srcIP_BE The source IP address.
dstIP_BE The destination IP address.
internetprotocolPayload The payload of the IP packet.
size The size of the IP packet.
Returns
True if the packet was handled, false otherwise.
Reimplemented in MaxOS::net::InternetControlMessageProtocol, MaxOS::net::TransmissionControlProtocolHandler, and MaxOS::net::UserDatagramProtocolHandler.
Definition at line 61 of file ipv4.cpp.
                                                                             {
    return false;
}
Send()
void InternetProtocolPayloadHandler::Send (InternetProtocolAddress destinationIP, uint8_t * payloadData, uint32_t size)
Sends an IP packet.
Parameters
dstIP_BE The destination IP address.
internetprotocolPayload The payload of the IP packet.
size The size of the IP packet.
Returns
True if the packet was sent, false otherwise.
Definition at line 76 of file ipv4.cpp.
                                                                                                                    {
    //Pass to backend
    internetProtocolHandler -> sendInternetProtocolPacket(destinationIP, ipProtocol, payloadData, size);
}
References destinationIP, internetProtocolHandler, ipProtocol, and size.
Referenced by MaxOS::net::InternetControlMessageProtocol::RequestEchoReply(), MaxOS::net::UserDatagramProtocolHandler::Send(), and MaxOS::net::TransmissionControlProtocolHandler::sendTransmissionControlProtocolPacket().
Friends And Related Symbol Documentation
InternetProtocolHandler
friend class InternetProtocolHandler [friend]
Definition at line 48 of file ipv4.h.
Member Data Documentation
internetProtocolHandler
InternetProtocolHandler* MaxOS::net::InternetProtocolPayloadHandler::internetProtocolHandler [protected]
Definition at line 51 of file ipv4.h.
Referenced by MaxOS::net::TransmissionControlProtocolHandler::Connect(), MaxOS::net::UserDatagramProtocolHandler::Connect(), InternetProtocolPayloadHandler(), MaxOS::net::TransmissionControlProtocolHandler::Listen(), MaxOS::net::UserDatagramProtocolHandler::Listen(), and Send().
ipProtocol
uint8_t MaxOS::net::InternetProtocolPayloadHandler::ipProtocol [protected]
Definition at line 52 of file ipv4.h.
Referenced by InternetProtocolPayloadHandler(), and Send().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/net/ipv4.h
/home/runner/work/MaxOS/MaxOS/kernel/src/net/ipv4.cpp