MaxOS::gui::CompositeWidget Class Reference
A widget that can contain other widgets.
#include <widget.h>
Public Member Functions
CompositeWidget (int32_t left, int32_t top, uint32_t width, uint32_t height)
Construct a new Composite Widget object at a specific position and size.
void draw (common::GraphicsContext *gc, common::Rectangle< int32_t > &area) override
Draws a section of the widget and its m_children.
void add_child (Widget *child) override
Adds a child to the widget.
void on_mouse_enter_widget (uint32_t toX, uint32_t toY) override
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
void on_mouse_leave_widget (uint32_t fromX, uint32_t fromY) override
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
void on_mouse_move_widget (uint32_t fromX, uint32_t fromY, uint32_t toX, uint32_t toY) override
Passes the event to the child that the mouse is over, also generates a leave/enter event for children.
drivers::peripherals::MouseEventHandler * on_mouse_button_pressed (uint32_t x, uint32_t y, uint8_t button) override
Passes the event to the child that the mouse is over.
void on_mouse_button_released (uint32_t x, uint32_t y, uint8_t button) override
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
Public Member Functions inherited from MaxOS::gui::Widget
Widget (int32_t left, int32_t top, uint32_t width, uint32_t height)
Construct a new Widget object at a specific position and size.
void invalidate ()
Invalidates the entire widget. This forces the widget to be redrawn on the next screen update.
virtual void invalidate (common::Rectangle< int32_t > &area)
Invalidates a specific area of the widget. This forces that part of the screen to be redrawn on the next screen update.
virtual common::Coordinates absolute_coordinates (common::Coordinates coordinates)
Get the absolute coordinates of the widget (relative to the screen)
virtual bool contains_coordinate (uint32_t x, uint32_t y)
Check if the widget contains a specific coordinate.
common::Rectangle< int32_t > position ()
Get the position of the widget.
void move (int32_t left, int32_t top)
Set the position of the widget, and invalidate the old and new positions so they are redrawn.
void resize (int32_t width, int32_t height)
Set the size of the widget, and invalidate the old and new positions so they are redrawn.
void focus ()
Set the current focused widget to be this widget.
virtual void on_focus ()
Handles the event when the widget is focussed.
virtual void on_focus_lost ()
Handles the event when the widget is unfocused.
void bring_to_front ()
Brings this widget to the front of the screen.
Public Member Functions inherited from MaxOS::drivers::peripherals::KeyboardEventHandler
common::Event< KeyboardEvents > * on_event (common::Event< KeyboardEvents > *) override
Handle the trigger of an event.
virtual void on_key_down (KeyCode, KeyboardState)
Handle the key down event.
virtual void on_key_up (KeyCode, KeyboardState)
Handle the key up event.
Public Member Functions inherited from MaxOS::common::EventHandler< KeyboardEvents >
virtual Event< KeyboardEvents > * on_event (Event< KeyboardEvents > *event)
This function is called when an event is raised.
Protected Member Functions
void draw (common::GraphicsContext *gc, common::Rectangle< int32_t > &area, common::Vector< Widget * >::iterator start)
Draws a section of the widget and the m_children after a specific child.
virtual void draw_self (common::GraphicsContext *gc, common::Rectangle< int32_t > &area)
Draws the widget itself (should be overridden by the derived class)
Protected Member Functions inherited from MaxOS::gui::Widget
virtual void set_focus (Widget *)
Sets the widget that is currently focussed.
virtual void bring_to_front (Widget *)
Brings a specific widget to the front of the screen.
Protected Attributes
common::Vector< Widget * > m_children
Widgets contained within this composite widget.
Protected Attributes inherited from MaxOS::gui::Widget
common::Rectangle< int32_t > m_position
The position and size of the widget (relative to its parent)
Widget * m_parent { nullptr }
The widget that owns this widget.
bool m_valid { false }
Is the widget drawn to the screen and up to date.
uint32_t m_min_width { 5 }
The smallest m_width the widget can be resized to.
uint32_t m_min_height { 5 }
The smallest m_height the widget can be resized to.
uint32_t m_max_width { 0x8FFFFFFF }
The largest m_width the widget can be resized to.
uint32_t m_max_height { 0x8FFFFFFF }
The largest m_height the widget can be resized to.
Detailed Description
A widget that can contain other widgets.
Definition at line 87 of file widget.h.
Constructor & Destructor Documentation
CompositeWidget()
CompositeWidget::CompositeWidget (int32_t left, int32_t top, uint32_t width, uint32_t height)
Construct a new Composite Widget object at a specific position and size.
Parameters
left The left position of the widget relative to its parent
top The top position of the widget relative to its parent
width How many pixels wide the widget is
height How many pixels tall the widget is
Definition at line 320 of file widget.cpp.
: Widget(left, top, width, height) {
}
Member Function Documentation
add_child()
void CompositeWidget::add_child (Widget * child) [override], [virtual]
Adds a child to the widget.
Parameters
child The child to add
Reimplemented from MaxOS::gui::Widget.
Reimplemented in MaxOS::gui::Desktop, and MaxOS::gui::Window.
Definition at line 401 of file widget.cpp.
                                             {
    // Store the child and parent the child to this widget
    m_children.push_back(child);
    Widget::add_child(child);
}
References MaxOS::gui::Widget::add_child(), and m_children.
Referenced by MaxOS::gui::Desktop::add_child(), and MaxOS::gui::Window::add_child().
draw() [1/2]
void CompositeWidget::draw (common::GraphicsContext * gc, common::Rectangle< int32_t > & area) [override], [virtual]
Draws a section of the widget and its m_children.
Parameters
gc The graphics context to draw to
area The area to draw
Reimplemented from MaxOS::gui::Widget.
Definition at line 333 of file widget.cpp.
                                                                        {
    // Draw the widget with its m_children
    draw(gc, area, m_children.begin());
}
References draw(), and m_children.
draw() [2/2]
void CompositeWidget::draw (common::GraphicsContext * gc, common::Rectangle< int32_t > & area, common::Vector< Widget * >::iterator start) [protected]
Draws a section of the widget and the m_children after a specific child.
Parameters
gc The graphics context to draw to
area The area to draw
start The child to start drawing from
Definition at line 346 of file widget.cpp.
                                                                                                       {
    // Draw the widget
    Widget::draw(gc, area);
    // Get the area of the widget
    Rectangle<int32_t> own_area = position();
    //Note: has to use iterator as the start is not necessarily the m_first_memory_chunk child
    for (Vector<Widget*>::iterator child_widget = start; child_widget != m_children.end(); child_widget++) {
        Rectangle<int32_t> child_area = (*child_widget)->position();
        // Check if the child is in the area that needs to be redrawn
        if (area.intersects(child_area)) {
            // Get the area that needs to be redrawn
            Rectangle<int32_t> rectangle = area.intersection(child_area);
            // Translate the area so that it is relative to the child
            rectangle.left -= child_area.left;
            rectangle.top -= child_area.top;
            // Draw the child
            (*child_widget)->draw(gc, rectangle);
            // Draw what is left of the area that needs to be redrawn
            Vector<Rectangle<int32_t>> rest_draw_area = area.subtract(child_area);
            for (auto& rest_area_part: rest_draw_area)
                draw(gc, rest_area_part, child_widget + 1);
            // Return as the entire area has now been drawn
            return;
        }
    }
    // Now draw the widget itself
    draw_self(gc, area);
}
References MaxOS::gui::Widget::draw(), draw(), draw_self(), MaxOS::common::Rectangle< Type >::intersection(), MaxOS::common::Rectangle< Type >::intersects(), MaxOS::common::Rectangle< Type >::left, m_children, MaxOS::gui::Widget::position(), MaxOS::common::Rectangle< Type >::subtract(), and MaxOS::common::Rectangle< Type >::top.
Referenced by draw(), draw(), and MaxOS::gui::Desktop::on_time().
draw_self()
void CompositeWidget::draw_self (common::GraphicsContext * gc, common::Rectangle< int32_t > & area) [protected], [virtual]
Draws the widget itself (should be overridden by the derived class)
Parameters
gc The graphics context to draw to
area The area to draw
Reimplemented in MaxOS::gui::Desktop, and MaxOS::gui::Window.
Definition at line 392 of file widget.cpp.
                                                                                 {
}
Referenced by draw().
on_mouse_button_pressed()
peripherals::MouseEventHandler * CompositeWidget::on_mouse_button_pressed (uint32_t x, uint32_t y, uint8_t button) [override], [virtual]
Passes the event to the child that the mouse is over.
Parameters
x The x coordinate of the mouse
y The y coordinate of the mouse
button The button that was pressed
Returns
The object that has the mouseEventHandler which handled the event
Reimplemented from MaxOS::gui::Widget.
Reimplemented in MaxOS::gui::Window.
Definition at line 518 of file widget.cpp.
                                                                                                             {
    MouseEventHandler* mouse_event_handler = nullptr;
    for (auto& child_widget: m_children) {
        // Pass the event to the child
        if (child_widget->contains_coordinate(x, y)) {
            mouse_event_handler = child_widget->on_mouse_button_pressed(x - child_widget->m_position.left,
                                                                        y - child_widget->m_position.top, button);
            break;
        }
    }
    return mouse_event_handler;
}
References MaxOS::common::Rectangle< Type >::left, m_children, and MaxOS::common::Rectangle< Type >::top.
Referenced by MaxOS::gui::Window::on_mouse_button_pressed(), and MaxOS::gui::Desktop::on_mouse_down_event().
on_mouse_button_released()
void CompositeWidget::on_mouse_button_released (uint32_t x, uint32_t y, uint8_t button) [override], [virtual]
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
Parameters
x The x coordinate of the mouse
y The y coordinate of the mouse
button The button that was released
Reimplemented from MaxOS::gui::Widget.
Definition at line 542 of file widget.cpp.
                                                                                     {
    // Loop through the m_children
    for (auto& child_widget: m_children) {
        // Pass the event to the child
        if (child_widget->contains_coordinate(x, y)) {
            child_widget->on_mouse_button_released(x - child_widget->m_position.left, y - child_widget->m_position.top,
                                                   button);
            break;
        }
    }
}
References MaxOS::common::Rectangle< Type >::left, m_children, and MaxOS::common::Rectangle< Type >::top.
Referenced by MaxOS::gui::Desktop::on_mouse_up_event().
on_mouse_enter_widget()
void CompositeWidget::on_mouse_enter_widget (uint32_t toX, uint32_t toY) [override], [virtual]
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
Parameters
toX The x coordinate of the mouse
toY The y coordinate of the mouse
Reimplemented from MaxOS::gui::Widget.
Definition at line 414 of file widget.cpp.
                                                                      {
    for (auto& child_widget: m_children) {
        // Check if the mouse is in the child
        Rectangle<int32_t> child_area = child_widget->position();
        if (child_area.contains(toX, toY)) {
            // Get the position of the mouse relative to the child
            uint32_t child_x = toX - child_area.left;
            uint32_t child_y = toY - child_area.top;
            // Call the child's on_mouse_enter_widget function
            child_widget->on_mouse_enter_widget(child_x, child_y);
            // Break as the event has been handled
            break;
        }
    }
}
References MaxOS::common::Rectangle< Type >::contains(), MaxOS::common::Rectangle< Type >::left, m_children, and MaxOS::common::Rectangle< Type >::top.
Referenced by MaxOS::gui::Desktop::add_child().
on_mouse_leave_widget()
void CompositeWidget::on_mouse_leave_widget (uint32_t fromX, uint32_t fromY) [override], [virtual]
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
Parameters
fromX The x coordinate of the mouse
fromY The y coordinate of the mouse
Reimplemented from MaxOS::gui::Widget.
Definition at line 441 of file widget.cpp.
                                                                          {
    for (auto& child_widget: m_children) {
        // Check if the mouse is in the child
        Rectangle<int32_t> child_area = child_widget->position();
        if (child_area.contains(fromX, fromY)) {
            // Get the position of the mouse relative to the child
            uint32_t child_x = fromX - child_area.left;
            uint32_t child_y = fromY - child_area.top;
            // Call the child's on_mouse_leave_widget function
            child_widget->on_mouse_leave_widget(child_x, child_y);
            // Event has been handled
            break;
        }
    }
}
References MaxOS::common::Rectangle< Type >::contains(), MaxOS::common::Rectangle< Type >::left, m_children, and MaxOS::common::Rectangle< Type >::top.
Referenced by MaxOS::gui::Desktop::add_child().
on_mouse_move_widget()
void CompositeWidget::on_mouse_move_widget (uint32_t fromX, uint32_t fromY, uint32_t toX, uint32_t toY) [override], [virtual]
Passes the event to the child that the mouse is over, also generates a leave/enter event for children.
Parameters
fromX The x coordinate of the mouse
fromY The y coordinate of the mouse
toX The x coordinate of the mouse
toY The y coordinate of the mouse
Reimplemented from MaxOS::gui::Widget.
Definition at line 470 of file widget.cpp.
                                                                                                     {
    Widget* left_child = nullptr;
    Widget* entered_child = nullptr;
    for (auto& child_widget: m_children) {
        // Check if the mouse is in the child
        Rectangle<int32_t> child_area = child_widget->position();
        bool mouse_in_from = child_area.contains(fromX, fromY);
        bool mouse_in_to = child_area.contains(toX, toY);
        // If the mouse started in the child
        if (mouse_in_from) {
            // The mouse moved out of the child
            if (!mouse_in_to) {
                left_child = child_widget;
                continue;
            }
            // Mouse still in the child
            child_widget->on_mouse_move_widget(fromX, fromY, toX, toY);
        } else {
            // Mouse moved into the child
            if (mouse_in_to)
                entered_child = child_widget;
        }
        // Pass the events to the child
        if (left_child != nullptr)
            left_child->on_mouse_leave_widget(fromX, fromY);
        if (entered_child != nullptr)
            entered_child->on_mouse_enter_widget(toX, toY);
    }
}
References MaxOS::common::Rectangle< Type >::contains(), and m_children.
Referenced by MaxOS::gui::Desktop::on_mouse_move_event().
Member Data Documentation
m_children
common::Vector<Widget*> MaxOS::gui::CompositeWidget::m_children [protected]
Widgets contained within this composite widget.
Definition at line 91 of file widget.h.
Referenced by add_child(), MaxOS::gui::Desktop::bring_to_front(), draw(), draw(), on_mouse_button_pressed(), on_mouse_button_released(), on_mouse_enter_widget(), on_mouse_leave_widget(), and on_mouse_move_widget().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/widget.h
/home/runner/work/MaxOS/MaxOS/kernel/src/gui/widget.cpp