MaxOS::drivers::clock::PIT Class Reference
Driver for the Programmable Interval Timer.
#include <clock.h>
Public Member Functions
PIT (hardwarecommunication::AdvancedProgrammableInterruptController *apic)
~PIT ()
Public Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
virtual system::cpu_status_t * handle_interrupt (system::cpu_status_t *status)
Handles an interrupt and returns the status.
Protected Member Functions
void handle_interrupt () final
Tick on each interrupt.
uint32_t ticks_per_ms ()
Uses the PIT to calculate how many APIC ticks are in 1 millisecond.
Protected Member Functions inherited from MaxOS::hardwarecommunication::InterruptHandler
InterruptHandler (uint8_t interrupt_number, int64_t redirect=-1, uint64_t redirect_index=0)
~InterruptHandler ()
Protected Attributes
hardwarecommunication::Port8Bit m_data_port
hardwarecommunication::Port8Bit m_command_port
hardwarecommunication::LocalAPIC * m_local_apic
hardwarecommunication::IOAPIC * m_io_apic
Protected Attributes inherited from MaxOS::hardwarecommunication::InterruptHandler
uint8_t m_interrupt_number
Detailed Description
Driver for the Programmable Interval Timer.
Definition at line 96 of file clock.h.
Constructor & Destructor Documentation
PIT()
PIT::PIT (hardwarecommunication::AdvancedProgrammableInterruptController * apic)
Definition at line 236 of file clock.cpp.
: InterruptHandler(0x22),
  m_data_port(0x40),
  m_command_port(0x43),
  m_local_apic(apic->local_apic()),
  m_io_apic(apic->io_apic())
{
}
~PIT()
PIT::~PIT () [default]
Member Function Documentation
handle_interrupt()
void PIT::handle_interrupt () [final], [protected], [virtual]
Tick on each interrupt.
Reimplemented from MaxOS::hardwarecommunication::InterruptHandler.
Definition at line 251 of file clock.cpp.
                           {
    m_ticks++;
}
ticks_per_ms()
uint32_t PIT::ticks_per_ms () [protected]
Uses the PIT to calculate how many APIC ticks are in 1 millisecond.
Returns
The amount of APIC ticks per millisecond
Definition at line 260 of file clock.cpp.
                           {
    // Set the redirect for the timer interrupt
    interrupt_redirect_t redirect = {
            .type = 0x2,
            .index = 0x14,
            .interrupt = 0x22,
            .destination = 0x00,
            .flags = 0x00,
            .mask = true,
    };
    m_io_apic->set_redirect(&redirect);
    // Configure the PIT clock
    pit_command_t command = {
            .bcd_mode = (uint8_t) BCDMode::BINARY,
            .operating_mode = (uint8_t) OperatingMode::RATE_GENERATOR,
            .access_mode = (uint8_t) AccessMode::LOW_HIGH_BYTE,
            .channel = (uint8_t) Channel::INTERRUPT
    };
    m_command_port.write(*(uint8_t *) &command);
    // Set the clock rate to 1 ms;
    uint16_t rate = 1193182 / 1000;
    m_data_port.write(rate & 0xFF);
    m_data_port.write(rate >> 8);
    // Stop the clock
    m_local_apic->write(0x380, 0x00);
    // Set the divisor to 2
    m_local_apic->write(0x3E0, 0x0);
    // Unmask the PIT interrupt
    m_io_apic->set_redirect_mask(redirect.index, false);
    // Calculate the number of ticks in 1 ms
    auto max = (uint32_t) -1;
    m_local_apic->write(0x380, max);
    while (m_ticks < s_calibrate_ticks)
        asm volatile("nop");
    uint32_t elapsed = max - (m_local_apic->read(0x390));
    uint32_t ticks_per_ms = elapsed / s_calibrate_ticks;
    Logger::DEBUG() << "Ticks per ms: " << (int) ticks_per_ms << "\n";
    // Disable the PIT interrupt again
    m_local_apic->write(0x380, 0x00);
    m_io_apic->set_redirect_mask(redirect.index, true);
    return ticks_per_ms;
}
References MaxOS::drivers::clock::BINARY, command, Logger::DEBUG(), MaxOS::drivers::clock::INTERRUPT, MaxOS::drivers::clock::LOW_HIGH_BYTE, m_command_port, m_data_port, m_io_apic, m_local_apic, MaxOS::drivers::clock::RATE_GENERATOR, MaxOS::hardwarecommunication::LocalAPIC::read(), MaxOS::hardwarecommunication::IOAPIC::set_redirect(), MaxOS::hardwarecommunication::IOAPIC::set_redirect_mask(), ticks_per_ms(), MaxOS::hardwarecommunication::LocalAPIC::write(), and MaxOS::hardwarecommunication::Port8Bit::write().
Referenced by ticks_per_ms().
Member Data Documentation
m_command_port
hardwarecommunication::Port8Bit MaxOS::drivers::clock::PIT::m_command_port [protected]
Definition at line 108 of file clock.h.
Referenced by ticks_per_ms().
m_data_port
hardwarecommunication::Port8Bit MaxOS::drivers::clock::PIT::m_data_port [protected]
Definition at line 107 of file clock.h.
Referenced by ticks_per_ms().
m_io_apic
hardwarecommunication::IOAPIC* MaxOS::drivers::clock::PIT::m_io_apic [protected]
Definition at line 112 of file clock.h.
Referenced by ticks_per_ms().
m_local_apic
hardwarecommunication::LocalAPIC* MaxOS::drivers::clock::PIT::m_local_apic [protected]
Definition at line 111 of file clock.h.
Referenced by ticks_per_ms().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/clock/clock.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/clock/clock.cpp