MaxOS::drivers::Driver Class Reference
base class for all drivers, handles the activation, deactivation, initialisation and reset of the driver as well as error messages and identifying the device
#include <driver.h>
Public Member Functions
Driver (common::OutputStream *driverMessageStream=0)
~Driver ()
void error_message (string message)
write a message to the driver message stream if it is not null
void error_message (char char_to_write)
write a character to the driver message stream if it is not null
void error_message (int int_to_write)
write an integer to the driver message stream if it is not null
void error_message (uint32_t hex_to_write)
write a hex to the driver message stream if it is not null
virtual void activate ()
activate the driver
virtual void deactivate ()
deactivate the driver
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
virtual string get_vendor_name ()
Get the vendor name of the driver.
virtual string get_device_name ()
Get the device name of the driver.
Public Attributes
common::OutputStream * m_driver_message_stream
Detailed Description
base class for all drivers, handles the activation, deactivation, initialisation and reset of the driver as well as error messages and identifying the device
Definition at line 24 of file driver.h.
Constructor & Destructor Documentation
Driver()
Driver::Driver (common::OutputStream * driverMessageStream = 0)
Definition at line 11 of file driver.cpp.
: m_driver_message_stream(driverMessageStream) {
};
 Driver()
Driver::~Driver ()
Definition at line 16 of file driver.cpp.
               {
    this ->m_driver_message_stream = 0;
};
Member Function Documentation
activate()
void Driver::activate () [virtual]
activate the driver
Reimplemented in MaxOS::drivers::clock::Clock, MaxOS::drivers::peripherals::KeyboardDriver, MaxOS::drivers::peripherals::MouseDriver, MaxOS::drivers::disk::AdvancedTechnologyAttachment, MaxOS::drivers::ethernet::intel_i217, and MaxOS::drivers::ethernet::amd_am79c973.
Definition at line 23 of file driver.cpp.
                     {
}
Referenced by MaxOS::drivers::disk::AdvancedTechnologyAttachment::activate().
deactivate()
void Driver::deactivate () [virtual]
deactivate the driver
Reimplemented in MaxOS::drivers::ethernet::intel_i217, and MaxOS::drivers::ethernet::amd_am79c973.
Definition at line 30 of file driver.cpp.
                       {
}
Referenced by MaxOS::drivers::ethernet::intel_i217::deactivate().
error_message() [1/4]
void Driver::error_message (char char_to_write)
write a character to the driver message stream if it is not null
Parameters
char_to_write The character to write
Definition at line 68 of file driver.cpp.
                                             {
    // If there is a driver message stream write the character to it
    if(m_driver_message_stream != 0)
      m_driver_message_stream-> write_char(char_to_write);
}
References m_driver_message_stream.
error_message() [2/4]
void Driver::error_message (int int_to_write)
write an integer to the driver message stream if it is not null
Parameters
int_to_write The integer to write
Definition at line 82 of file driver.cpp.
                                           {
    // If there is a driver message stream write the integer to it
    if(m_driver_message_stream != 0)
            m_driver_message_stream-> write_int(int_to_write);
}
References m_driver_message_stream.
error_message() [3/4]
void Driver::error_message (string message)
write a message to the driver message stream if it is not null
Parameters
message The message to write
Definition at line 55 of file driver.cpp.
                                         {
    // If there is a driver message stream write the message to it
    if(m_driver_message_stream != 0)
        m_driver_message_stream-> write(message);
}
References m_driver_message_stream.
Referenced by MaxOS::drivers::ethernet::amd_am79c973::handle_interrupt(), and MaxOS::drivers::ethernet::intel_i217::intel_i217().
error_message() [4/4]
void Driver::error_message (uint32_t hex_to_write)
write a hex to the driver message stream if it is not null
Parameters
hex_to_write The hex to write
Definition at line 94 of file driver.cpp.
                                                {
    // If there is a driver message stream write the hex to it
    if(m_driver_message_stream != 0)
      m_driver_message_stream->write_hex(hex_to_write);
}
References m_driver_message_stream, and MaxOS::common::OutputStream::write_hex().
get_device_name()
string Driver::get_device_name () [virtual]
Get the device name of the driver.
Returns
The device name of the driver
Reimplemented in MaxOS::drivers::peripherals::KeyboardDriver, MaxOS::drivers::peripherals::MouseDriver, MaxOS::drivers::clock::Clock, MaxOS::drivers::disk::AdvancedTechnologyAttachment, MaxOS::drivers::video::VideoElectronicsStandardsAssociation, MaxOS::drivers::video::VideoGraphicsArray, MaxOS::drivers::ethernet::intel_i217, and MaxOS::drivers::ethernet::amd_am79c973.
Definition at line 117 of file driver.cpp.
{
    return "Unknown Driver";
}
Referenced by kernelMain(), and MaxOS::hardwarecommunication::PeripheralComponentInterconnectController::select_drivers().
get_vendor_name()
string Driver::get_vendor_name () [virtual]
Get the vendor name of the driver.
Returns
The vendor name of the driver
Reimplemented in MaxOS::drivers::clock::Clock, MaxOS::drivers::disk::AdvancedTechnologyAttachment, MaxOS::drivers::video::VideoElectronicsStandardsAssociation, MaxOS::drivers::video::VideoGraphicsArray, MaxOS::drivers::ethernet::intel_i217, and MaxOS::drivers::ethernet::amd_am79c973.
Definition at line 107 of file driver.cpp.
{
    return "Generic";
}
Referenced by MaxOS::hardwarecommunication::PeripheralComponentInterconnectController::select_drivers().
initialise()
void Driver::initialise () [virtual]
Initialise the driver.
Definition at line 37 of file driver.cpp.
                        {
}
reset()
uint32_t Driver::reset () [virtual]
Reset the driver.
Returns
How long in milliseconds it took to reset the driver
Reimplemented in MaxOS::drivers::ethernet::intel_i217, and MaxOS::drivers::ethernet::amd_am79c973.
Definition at line 46 of file driver.cpp.
                      {
    return 0;
}
Referenced by MaxOS::drivers::ethernet::intel_i217::reset().
Member Data Documentation
m_driver_message_stream
common::OutputStream* MaxOS::drivers::Driver::m_driver_message_stream
Definition at line 28 of file driver.h.
Referenced by MaxOS::drivers::ethernet::intel_i217::activate(), MaxOS::drivers::ethernet::intel_i217::DoSend(), error_message(), MaxOS::drivers::ethernet::EthernetDriver::FireDataReceived(), MaxOS::drivers::ethernet::intel_i217::GetMediaAccessControlAddress(), MaxOS::drivers::ethernet::intel_i217::handle_interrupt(), kernelMain(), and MaxOS::drivers::ethernet::EthernetDriver::Send().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/driver.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/driver.cpp