MaxOS::processes::SharedMemory Class Reference
#include <ipc.h>
Public Member Functions
SharedMemory (const string &name, size_t size, resource_type_t type)
Creates a new shared memory block.
~SharedMemory () final
void open (size_t flags) final
Map the shared memory into the address space of the owning process.
void close (size_t flags) final
Frees the page containing the shared memory.
int read (void *buffer, size_t size, size_t flags) final
Get the address that the current process has this shared memory mapped to.
uintptr_t physical_address () const
Gets the physical address of the shared memory block.
size_t size () const
Gets the size of the shared memory block.
Public Member Functions inherited from MaxOS::processes::Resource
Resource (const string &name, size_t flags, resource_type_t type)
virtual ~Resource ()
string name ()
Gets the name of this resource.
resource_type_t type ()
Gets the type of this resource.
virtual int write (const void *buffer, size_t size, size_t flags)
Write a certain amount of bytes to a resource.
Public Attributes
string name
uint64_t use_count = 1
Detailed Description
Definition at line 21 of file ipc.h.
Constructor & Destructor Documentation
SharedMemory()
SharedMemory::SharedMemory (const string & name, size_t size, resource_type_t type)
Creates a new shared memory block.
Parameters
name The name of the block
Definition at line 19 of file ipc.cpp.
: Resource(name, size, type),
  m_size(size),
  name(name)
{
    m_physical_address = (uintptr_t) PhysicalMemoryManager::s_current_manager->allocate_area(0, size);
}
References MaxOS::memory::PhysicalMemoryManager::s_current_manager, and size().
~SharedMemory()
SharedMemory::~SharedMemory () [final], [default]
Member Function Documentation
close()
void SharedMemory::close (size_t flags) [final], [virtual]
Frees the page containing the shared memory.
Parameters
flags Not used for this resource
Reimplemented from MaxOS::processes::Resource.
Definition at line 90 of file ipc.cpp.
                                     {
    PhysicalMemoryManager::s_current_manager->free_area(m_physical_address, m_size);
}
References MaxOS::memory::PhysicalMemoryManager::s_current_manager.
open()
void SharedMemory::open (size_t flags) [final], [virtual]
Map the shared memory into the address space of the owning process.
Parameters
flags Not used for this resource
Reimplemented from MaxOS::processes::Resource.
Definition at line 73 of file ipc.cpp.
                                    {
    // Process has already opened this memory
    auto it = m_mappings.find(Scheduler::current_process()->pid());
    if(it != m_mappings.end())
        return;
    auto virtual_address = (uintptr_t)Scheduler::current_process()->memory_manager->vmm()->load_shared_memory(m_physical_address, m_size);
    m_mappings.insert(Scheduler::current_process()->pid(), virtual_address);
}
References MaxOS::processes::Scheduler::current_process(), MaxOS::common::Map< Key, Value >::end(), MaxOS::common::Map< Key, Value >::find(), and MaxOS::common::Map< Key, Value >::insert().
physical_address()
uintptr_t SharedMemory::physical_address () const
Gets the physical address of the shared memory block.
Returns
The physical address
Definition at line 53 of file ipc.cpp.
                                               {
    return m_physical_address;
}
read()
int SharedMemory::read (void * buffer, size_t size, size_t flags) [final], [virtual]
Get the address that the current process has this shared memory mapped to.
Parameters
buffer Not used
size Not used
flags Not used
Returns
The virtual address in the current process's address space or 0 if not found
Reimplemented from MaxOS::processes::Resource.
Definition at line 38 of file ipc.cpp.
                                                              {
    // Process hasn't opened the resource
    auto it = m_mappings.find(Scheduler::current_process()->pid());
    if(it == m_mappings.end())
        return 0;
    return it->second;
}
References MaxOS::processes::Scheduler::current_process(), MaxOS::common::Map< Key, Value >::end(), and MaxOS::common::Map< Key, Value >::find().
size()
size_t SharedMemory::size () const
Gets the size of the shared memory block.
Returns
The size
Definition at line 63 of file ipc.cpp.
                                {
    return m_size;
}
Referenced by SharedMemory().
Member Data Documentation
name
string MaxOS::processes::SharedMemory::name
Definition at line 33 of file ipc.h.
use_count
uint64_t MaxOS::processes::SharedMemory::use_count = 1
Definition at line 34 of file ipc.h.
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/processes/ipc.h
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/ipc.cpp