MaxOS::tests::TestRunner Class Reference
A class to run all tests.
#include <test.h>
Static Public Member Functions
static void test_kernel ()
Setups the TestRunner and runs all kernel tests.
static void run_all_tests ()
Runs all registered tests.
static void run_all_types (TestType type)
Runs all tests of a specific type.
static void add_all_tests ()
Adds all predefined tests to the test runner.
static void add_test (Test *test)
Adds a test to the test runner.
Detailed Description
A class to run all tests.
Todo
Todo Revisit when cbf
Definition at line 133 of file test.h.
Member Function Documentation
add_all_tests()
void TestRunner::add_all_tests () [static]
Adds all predefined tests to the test runner.
Definition at line 145 of file test.cpp.
                               {
    register_tests_common();
}
Referenced by test_kernel().
add_test()
void TestRunner::add_test (Test * test) [static]
Adds a test to the test runner.
Parameters
test The test to add
Definition at line 138 of file test.cpp.
                                    {
    s_tests.push_back(test);
}
Referenced by MaxOS::tests::Test::Test().
run_all_tests()
void TestRunner::run_all_tests () [static]
Runs all registered tests.
Definition at line 116 of file test.cpp.
                               {
    Logger::TEST() << "Running all tests... (" << (int)s_tests.size() << " tests found)\n";
    for (auto& test : s_tests)
        test->run();
}
References MaxOS::Logger::TEST().
Referenced by test_kernel().
run_all_types()
void TestRunner::run_all_types (TestType type) [static]
Runs all tests of a specific type.
Parameters
type The type of tests to run
Definition at line 127 of file test.cpp.
                                            {
    for (auto& test : s_tests)
        if (test->type() == type)
            test->run();
}
test_kernel()
void TestRunner::test_kernel () [static]
Setups the TestRunner and runs all kernel tests.
Definition at line 152 of file test.cpp.
                             {
    // Add all tests
    s_tests = common::Vector<Test*>();
    add_all_tests();
    // Run all system tests
    run_all_tests();
}
References add_all_tests(), and run_all_tests().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/tests/test.h
/home/runner/work/MaxOS/MaxOS/kernel/src/tests/test.cpp