MaxOS::drivers::console::TextModeConsole Class Reference
Driver for the text mode console, handles the printing of characters and strings to the screen using VGA.
#include <textmode.h>
Public Member Functions
TextModeConsole ()
~TextModeConsole ()
uint16_t width () final
Gets the width of the console.
uint16_t height () final
Gets the height of the console.
void put_character (uint16_t x, uint16_t y, char c) final
Places a character at the specified location if it is in bounds.
void set_foreground_color (uint16_t x, uint16_t y, common::ConsoleColour) final
Sets the foreground color at the specified location.
void set_background_color (uint16_t x, uint16_t y, common::ConsoleColour) final
Sets the background color at the specified location.
char get_character (uint16_t x, uint16_t y) final
Gets the character at the specified location.
common::ConsoleColour get_foreground_color (uint16_t x, uint16_t y) final
Gets the foreground color at the specified location.
common::ConsoleColour get_background_color (uint16_t x, uint16_t y) final
Gets the background color at the specified location.
Public Member Functions inherited from MaxOS::drivers::Driver
Driver ()
~Driver ()
virtual void activate ()
activate the driver
virtual void deactivate ()
deactivate the driver
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
virtual string vendor_name ()
Get who created the device.
virtual string device_name ()
Get the device name of the driver.
Public Member Functions inherited from MaxOS::drivers::console::Console
Console ()
~Console ()
virtual void put_character (uint16_t x, uint16_t y, char c, common::ConsoleColour foreground, common::ConsoleColour background)
Put a character on the console with a given foreground and background color.
virtual void put_string (uint16_t x, uint16_t y, string s, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black)
Put a string on the console.
virtual void scroll_up ()
Scroll the entire console up by 1 line.
virtual void scroll_up (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black, char fill=' ')
Scroll an area of the console up by 1 line.
virtual void clear ()
virtual void clear (uint16_t left, uint16_t top, uint16_t width, uint16_t height, common::ConsoleColour foreground=common::ConsoleColour::LightGrey, common::ConsoleColour background=common::ConsoleColour::Black, char fill=' ')
Clear an area of the console.
virtual void invert_colors (uint16_t x, uint16_t y)
Invert the colors of a character on the console.
Protected Attributes
uint16_t * m_video_memory { (uint16_t*)0xB8000 }
Detailed Description
Driver for the text mode console, handles the printing of characters and strings to the screen using VGA.
Definition at line 22 of file textmode.h.
Constructor & Destructor Documentation
TextModeConsole()
TextModeConsole::TextModeConsole () [default]
~TextModeConsole()
TextModeConsole::~TextModeConsole () [default]
Member Function Documentation
get_background_color()
ConsoleColour TextModeConsole::get_background_color (uint16_t x, uint16_t y) [final], [virtual]
Gets the background color at the specified location.
Parameters
x The x coordinate
y The y coordinate
Returns
The background color at the specified location or black if the coordinates are out of bounds
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 141 of file textmode.cpp.
                                                                          {
    // Check bounds
    if (x >= width() || y >= height())
        return ConsoleColour::Black;
    // Calculate the offset
    int offset = (y * width() + x);
    // Return the background color at the offset, by masking the background color with the current background color (bits 12-15)
    return (ConsoleColour) ((m_video_memory[offset] & 0xF000) >> 12);
}
References height(), m_video_memory, and width().
get_character()
char TextModeConsole::get_character (uint16_t x, uint16_t y) [final], [virtual]
Gets the character at the specified location.
Parameters
x The x coordinate
y The y coordinate
Returns
The character at the specified location or a space if the coordinates are out of bounds
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 101 of file textmode.cpp.
                                                          {
    // Check bounds
    if (x >= width() || y >= height())
        return ' ';
    // Calculate the offset
    int offset = (y * width() + x);
    // Return the character at the offset, mask away the colour information
    return (char) (m_video_memory[offset] & 0x00FF);
}
References height(), m_video_memory, and width().
get_foreground_color()
ConsoleColour TextModeConsole::get_foreground_color (uint16_t x, uint16_t y) [final], [virtual]
Gets the foreground color at the specified location.
Parameters
x The x coordinate
y The y coordinate
Returns
The foreground color at the specified location or white if the coordinates are out of bounds
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 121 of file textmode.cpp.
                                                                          {
    // Check bounds
    if (x >= width() || y >= height())
        return ConsoleColour::White;
    // Calculate the offset
    int offset = (y * width() + x);
    // Return the foreground color at the offset, by masking the foreground color with the current foreground color (bits 8-11)
    return (ConsoleColour) ((m_video_memory[offset] & 0x0F00) >> 8);
}
References height(), m_video_memory, and width().
height()
uint16_t TextModeConsole::height () [final], [virtual]
Gets the height of the console.
Returns
The height of the console in characters
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 30 of file textmode.cpp.
                                 {
    return 25;
}
Referenced by get_background_color(), get_character(), get_foreground_color(), put_character(), set_background_color(), and set_foreground_color().
put_character()
void TextModeConsole::put_character (uint16_t x, uint16_t y, char c) [final], [virtual]
Places a character at the specified location if it is in bounds.
Parameters
x The x coordinate
y The y coordinate
c The character to place
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 41 of file textmode.cpp.
                                                                  {
    // Check bounds
    if (x >= width() || y >= height())
        return;
    // Calculate the offset
    int offset = (y * width() + x);
    // Set the character at the offset, mask away the colour information
    m_video_memory[offset] = (m_video_memory[offset] & 0xFF00) | (uint16_t) c;
}
References height(), m_video_memory, and width().
set_background_color()
void TextModeConsole::set_background_color (uint16_t x, uint16_t y, common::ConsoleColour background) [final], [virtual]
Sets the background color at the specified location.
Parameters
x The x coordinate
y The y coordinate
background The background color
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 81 of file textmode.cpp.
                                                                                           {
    // Check bounds
    if (x >= width() || y >= height())
        return;
    // Calculate the offset
    int offset = (y * width() + x);
    // Set the background color at the offset, mask to get the backgroun bits
    m_video_memory[offset] = (m_video_memory[offset] & 0x0FFF) | ((uint16_t) background << 12);
}
References height(), m_video_memory, and width().
set_foreground_color()
void TextModeConsole::set_foreground_color (uint16_t x, uint16_t y, common::ConsoleColour foreground) [final], [virtual]
Sets the foreground color at the specified location.
Parameters
x The x coordinate
y The y coordinate
foreground The foreground color
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 61 of file textmode.cpp.
                                                                                           {
    // Check bounds
    if (x >= width() || y >= height())
        return;
    // Calculate the offset
    int offset = (y * width() + x);
    // Set the foreground color at the offset, mask to get the foreground bits
    m_video_memory[offset] = (m_video_memory[offset] & 0xF0FF) | ((uint16_t) foreground << 8);
}
References height(), m_video_memory, and width().
width()
uint16_t TextModeConsole::width () [final], [virtual]
Gets the width of the console.
Returns
The width of the console in characters
Reimplemented from MaxOS::drivers::console::Console.
Definition at line 21 of file textmode.cpp.
                                {
    return 80;
}
Referenced by get_background_color(), get_character(), get_foreground_color(), put_character(), set_background_color(), and set_foreground_color().
Member Data Documentation
m_video_memory
uint16_t* MaxOS::drivers::console::TextModeConsole::m_video_memory { (uint16_t*)0xB8000 } [protected]
Definition at line 25 of file textmode.h.
{ (uint16_t*)0xB8000 };
Referenced by get_background_color(), get_character(), get_foreground_color(), put_character(), set_background_color(), and set_foreground_color().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/textmode.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/console/textmode.cpp