MaxOS::common::Spinlock Class Reference
Enables a resource to be used by only one instance at a time through locking and unlocking.
#include <spinlock.h>
Public Member Functions
Spinlock (bool should_yield=false)
~Spinlock ()
void lock ()
Lock the spinlock once it is available.
void unlock ()
Unlock the spinlock.
bool is_locked () const
Check if the spinlock is locked.
void acquire ()
Acquire the spinlock: wait until the lock is available, yielding if desired until that happens.
void release ()
Release the spinlock.
Detailed Description
Enables a resource to be used by only one instance at a time through locking and unlocking.
Definition at line 16 of file spinlock.h.
Constructor & Destructor Documentation
Spinlock()
Spinlock::Spinlock (bool should_yield = false)
Definition at line 12 of file spinlock.cpp.
: m_should_yield(should_yield) {
}
~Spinlock()
Spinlock::~Spinlock () [default]
Member Function Documentation
acquire()
void Spinlock::acquire ()
Acquire the spinlock: wait until the lock is available, yielding if desired until that happens.
Definition at line 50 of file spinlock.cpp.
                       {
    while (__atomic_test_and_set(&m_locked, __ATOMIC_ACQUIRE)) {
        // Wait for the lock to be available
        if (m_should_yield)
            Scheduler::system_scheduler()->yield();
    }
}
References MaxOS::processes::Scheduler::system_scheduler().
Referenced by lock().
is_locked()
bool Spinlock::is_locked () const
Check if the spinlock is locked.
Returns
True if the spinlock is locked, false otherwise
Definition at line 42 of file spinlock.cpp.
                               {
    return m_locked;
}
lock()
void Spinlock::lock ()
Lock the spinlock once it is available.
Definition at line 22 of file spinlock.cpp.
                    {
    acquire();
    m_locked = true;
}
References acquire().
Referenced by MaxOS::memory::PhysicalMemoryManager::allocate_area(), MaxOS::memory::PhysicalMemoryManager::allocate_frame(), MaxOS::filesystem::format::ext2::Ext2Volume::create_inode(), MaxOS::filesystem::format::ext2::InodeHandler::free(), MaxOS::memory::PhysicalMemoryManager::free_area(), MaxOS::memory::PhysicalMemoryManager::free_frame(), MaxOS::filesystem::format::ext2::Ext2File::read(), MaxOS::filesystem::format::ext2::Ext2Directory::read_from_disk(), MaxOS::memory::PhysicalMemoryManager::reserve(), MaxOS::filesystem::format::ext2::Ext2File::write(), and MaxOS::processes::SharedMessageEndpoint::write().
release()
void Spinlock::release ()
Release the spinlock.
Definition at line 63 of file spinlock.cpp.
                       {
    __atomic_clear(&m_locked, __ATOMIC_RELEASE);
}
Referenced by unlock().
unlock()
void Spinlock::unlock ()
Unlock the spinlock.
Definition at line 31 of file spinlock.cpp.
                      {
    m_locked = false;
    release();
}
References release().
Referenced by MaxOS::memory::PhysicalMemoryManager::allocate_area(), MaxOS::memory::PhysicalMemoryManager::allocate_frame(), MaxOS::filesystem::format::ext2::Ext2Volume::create_inode(), MaxOS::filesystem::format::ext2::InodeHandler::free(), MaxOS::memory::PhysicalMemoryManager::free_area(), MaxOS::memory::PhysicalMemoryManager::free_frame(), MaxOS::filesystem::format::ext2::Ext2File::read(), MaxOS::filesystem::format::ext2::Ext2Directory::read_from_disk(), MaxOS::memory::PhysicalMemoryManager::reserve(), MaxOS::filesystem::format::ext2::Ext2File::write(), and MaxOS::processes::SharedMessageEndpoint::write().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/common/spinlock.h
/home/runner/work/MaxOS/MaxOS/kernel/src/common/spinlock.cpp