MaxOS::system::SyscallManager Class Reference
Provides an API for userspace applications to interact with the kernel.
#include <syscalls.h>
Public Member Functions
SyscallManager ()
~SyscallManager ()
cpu_status_t * handle_interrupt (cpu_status_t *esp) final
Loads the args from the registers and delegates the syscall to the relevant handler if defined.
void set_syscall_handler (::syscore::SyscallType syscall, syscall_func_t handler)
Loads a syscall handler into the manager.
void remove_syscall_handler (::syscore::SyscallType syscall)
Removes a syscall handler from the manager.
Static Public Member Functions
static syscall_args_t * syscall_close_process (syscall_args_t *args)
System call to close a process.
static syscall_args_t * syscall_klog (syscall_args_t *args)
static syscall_args_t * syscall_allocate_memory (syscall_args_t *args)
System call to free a block of memory.
static syscall_args_t * syscall_free_memory (syscall_args_t *args)
System call to free a block of memory.
static syscall_args_t * syscall_resource_create (syscall_args_t *args)
System call to create a resource.
static syscall_args_t * syscall_resource_open (syscall_args_t *args)
System call to open a resource.
static syscall_args_t * syscall_resource_close (syscall_args_t *args)
System call to close a resource.
static syscall_args_t * syscall_resource_write (syscall_args_t *args)
System call to write to a resource.
static syscall_args_t * syscall_resource_read (syscall_args_t *args)
System call to read from a resource.
static syscall_args_t * syscall_thread_yield (syscall_args_t *args)
System call to yield the current process.
static syscall_args_t * syscall_thread_sleep (syscall_args_t *args)
System call to sleep the current process.
static syscall_args_t * syscall_thread_close (syscall_args_t *args)
System call to close a thread.
Protected Attributes
syscall_func_t m_syscall_handlers [256] = {}
syscall_args_t * m_current_args
Detailed Description
Provides an API for userspace applications to interact with the kernel.
Definition at line 42 of file syscalls.h.
Constructor & Destructor Documentation
SyscallManager()
SyscallManager::SyscallManager ()
Definition at line 17 of file syscalls.cpp.
: InterruptHandler(0x80)
{
    // Clear the args
    Logger::INFO() << "Setting up Syscalls \n";
    m_current_args = new syscall_args_t;
    // Register the handlers
    set_syscall_handler(SyscallType::CLOSE_PROCESS, syscall_close_process);
    set_syscall_handler(SyscallType::KLOG, syscall_klog);
    set_syscall_handler(SyscallType::ALLOCATE_MEMORY, syscall_allocate_memory);
    set_syscall_handler(SyscallType::FREE_MEMORY, syscall_free_memory);
    set_syscall_handler(SyscallType::RESOURCE_CREATE, syscall_resource_create);
    set_syscall_handler(SyscallType::RESOURCE_OPEN, syscall_resource_open);
    set_syscall_handler(SyscallType::RESOURCE_CLOSE, syscall_resource_close);
    set_syscall_handler(SyscallType::RESOURCE_WRITE, syscall_resource_write);
    set_syscall_handler(SyscallType::RESOURCE_READ, syscall_resource_read);
    set_syscall_handler(SyscallType::THREAD_YIELD, syscall_thread_yield);
    set_syscall_handler(SyscallType::THREAD_SLEEP, syscall_thread_sleep);
    set_syscall_handler(SyscallType::THREAD_CLOSE, syscall_thread_close);
}
References Logger::INFO(), m_current_args, set_syscall_handler(), syscall_allocate_memory(), syscall_close_process(), syscall_free_memory(), syscall_klog(), syscall_resource_close(), syscall_resource_create(), syscall_resource_open(), syscall_resource_read(), syscall_resource_write(), syscall_thread_close(), syscall_thread_sleep(), and syscall_thread_yield().
~SyscallManager()
SyscallManager::~SyscallManager () [default]
Member Function Documentation
handle_interrupt()
cpu_status_t * SyscallManager::handle_interrupt (cpu_status_t * status) [final]
Loads the args from the registers and delegates the syscall to the relevant handler if defined.
Parameters
status The cpu state
Returns
The cpu state (may be modified with return value in RAX or a new state by the handler)
Definition at line 49 of file syscalls.cpp.
                                                                   {
    // Get the args from the cpu state
    m_current_args->arg0 = status->rdi;
    m_current_args->arg1 = status->rsi;
    m_current_args->arg2 = status->rdx;
    m_current_args->arg3 = status->r10;
    m_current_args->arg4 = status->r8;
    m_current_args->arg5 = status->r9;
    m_current_args->return_value = 0;
    m_current_args->return_state = status;
    // Call the handler
    uint64_t syscall = status->rax;
    if (m_syscall_handlers[syscall] != nullptr)
        m_current_args = m_syscall_handlers[syscall](m_current_args);
    else
        Logger::ERROR() << "Syscall " << syscall << " not found\n";
    // If there is a specific return state, use that
    if (m_current_args->return_state != status)
        return m_current_args->return_state;
    // Update the cpu state
    status->rdi = m_current_args->arg0;
    status->rsi = m_current_args->arg1;
    status->rdx = m_current_args->arg2;
    status->r10 = m_current_args->arg3;
    status->r8 = m_current_args->arg4;
    status->r9 = m_current_args->arg5;
    status->rax = m_current_args->return_value;
    // Return the status
    return status;
}
References MaxOS::system::SyscallArguments::arg0, MaxOS::system::SyscallArguments::arg1, MaxOS::system::SyscallArguments::arg2, MaxOS::system::SyscallArguments::arg3, MaxOS::system::SyscallArguments::arg4, MaxOS::system::SyscallArguments::arg5, Logger::ERROR(), m_current_args, m_syscall_handlers, MaxOS::system::SyscallArguments::return_state, MaxOS::system::SyscallArguments::return_value, and status.
remove_syscall_handler()
void SyscallManager::remove_syscall_handler (::syscore::SyscallType syscall)
Removes a syscall handler from the manager.
Parameters
syscall The syscall ID number
Definition at line 102 of file syscalls.cpp.
                                                               {
    m_syscall_handlers[(uint8_t) syscall] = nullptr;
}
References m_syscall_handlers.
set_syscall_handler()
void SyscallManager::set_syscall_handler (::syscore::SyscallType syscall, syscall_func_t handler)
Loads a syscall handler into the manager.
Parameters
syscall The syscall ID number
handler The handler to set
Definition at line 92 of file syscalls.cpp.
                                                                                    {
    m_syscall_handlers[(uint8_t) syscall] = handler;
}
References m_syscall_handlers.
Referenced by SyscallManager().
syscall_allocate_memory()
syscall_args_t * SyscallManager::syscall_allocate_memory (syscall_args_t * args) [static]
System call to free a block of memory.
Parameters
args Arg0 = size
Returns
The address of the memory block or null if failed
Definition at line 151 of file syscalls.cpp.
                                                                            {
    // Malloc the memory
    size_t size = args->arg0;
    void* address = MemoryManager::malloc(size);
    // Return the address
    args->return_value = (uint64_t)address;
    return args;
}
References address, MaxOS::memory::MemoryManager::malloc(), and size.
Referenced by SyscallManager().
syscall_close_process()
syscall_args_t * SyscallManager::syscall_close_process (system::syscall_args_t * args) [static]
System call to close a process.
Parameters
args Arg0 = pid Arg1 = exit code
Returns
Nothing
Definition at line 114 of file syscalls.cpp.
                                                                                {
    // Get the args
    uint64_t pid = args->arg0;
    int exit_code = (int) args->arg1;
    // Close the process
    Process* process = pid == 0 ? Scheduler::current_process() : Scheduler::get_process(pid);
    Scheduler::system_scheduler()->remove_process(process);
    // Schedule the next process
    cpu_status_t* next_process = Scheduler::system_scheduler()->schedule_next(args->return_state);
    args->return_state = next_process;
    // Done
    return args;
}
References MaxOS::processes::Scheduler::current_process(), MaxOS::processes::Scheduler::get_process(), and MaxOS::processes::Scheduler::system_scheduler().
Referenced by SyscallManager().
syscall_free_memory()
syscall_args_t * SyscallManager::syscall_free_memory (syscall_args_t * args) [static]
System call to free a block of memory.
Parameters
args Arg0 = address
Returns
Nothing
Definition at line 168 of file syscalls.cpp.
                                                                        {
    // Free the memory
    void* address = (void*) args->arg0;
    MemoryManager::free(address);
    return args;
}
References address, and MaxOS::memory::MemoryManager::free().
Referenced by SyscallManager().
syscall_klog()
syscall_args_t * SyscallManager::syscall_klog (syscall_args_t * args) [static]
Definition at line 132 of file syscalls.cpp.
                                                                 {
    char* message = (char*) args->arg0;
    // If the first two characters are %h then no header
    if (message[0] == '%' && message[1] == 'h')
        Logger::Out() << message + 2;
    else
        Logger::INFO() << ANSI_COLOURS[FG_Blue] << "(" << Scheduler::current_process()->name.c_str() << ":" << Scheduler::current_thread()->tid << "): " << ANSI_COLOURS[Reset] << message;
    return args;
}
References MaxOS::common::ANSI_COLOURS, MaxOS::processes::Scheduler::current_process(), MaxOS::processes::Scheduler::current_thread(), MaxOS::common::FG_Blue, Logger::INFO(), Logger::Out(), and MaxOS::common::Reset.
Referenced by SyscallManager().
syscall_resource_close()
syscall_args_t * SyscallManager::syscall_resource_close (syscall_args_t * args) [static]
System call to close a resource.
Parameters
args Arg0 = Handle Arg1 = Flags
Returns
Nothing
Definition at line 222 of file syscalls.cpp.
                                                                           {
    // Parse params
    auto handle = (uint64_t)args->arg0;
    auto flags = (size_t)args->arg1;
    // Close the resource
    Scheduler::current_process()->resource_manager.close_resource(handle, flags);
    return args;
}
References MaxOS::processes::Scheduler::current_process(), and flags.
Referenced by SyscallManager().
syscall_resource_create()
syscall_args_t * SyscallManager::syscall_resource_create (syscall_args_t * args) [static]
System call to create a resource.
Parameters
args Arg0 = ResourceType Arg1 = Name Arg2 = Flags
Returns
1 if resource was created sucessfully, 0 otherwise
Definition at line 183 of file syscalls.cpp.
                                                                            {
    // Parse params
    auto type = (ResourceType)args->arg0;
    auto name = (char*)args->arg1;
    auto flags = (size_t)args->arg2;
    // Try to create the resource
    auto resource = GlobalResourceRegistry::get_registry(type)->create_resource(name, flags);
    // Handle response
    args->return_value = resource ? 1 : 0;
    return args;
}
References flags, MaxOS::processes::GlobalResourceRegistry::get_registry(), name, and type.
Referenced by SyscallManager().
syscall_resource_open()
syscall_args_t * SyscallManager::syscall_resource_open (syscall_args_t * args) [static]
System call to open a resource.
Parameters
args Arg0 = ResourceType Arg1 = Name Arg2 = Flags
Returns
The handle of the resource or 0 if failed
Definition at line 204 of file syscalls.cpp.
                                                                          {
    // Parse params
    auto type = (ResourceType)args->arg0;
    auto name = (char*)args->arg1;
    auto flags = (size_t)args->arg2;
    // Open the resource
    args->return_value = Scheduler::current_process()->resource_manager.open_resource(type, name, flags);
    return args;
}
References MaxOS::processes::Scheduler::current_process(), flags, name, and type.
Referenced by SyscallManager().
syscall_resource_read()
syscall_args_t * SyscallManager::syscall_resource_read (syscall_args_t * args) [static]
System call to read from a resource.
Parameters
args Arg0 = Handle Arg1 = Buffer Arg2 = Size Arg3 = Flags
Returns
The number of bytes read or 0 if failed
Definition at line 265 of file syscalls.cpp.
                                                                          {
    // Parse params
    auto handle = (uint64_t)args->arg0;
    auto buffer = (void*)args->arg1;
    auto size = (size_t)args->arg2;
    auto flags = (size_t)args->arg3;
    // Open the resource
    auto resource = Scheduler::current_process()->resource_manager.get_resource(handle);
    if(!resource){
        args->return_value = 0;
        return args;
    }
    // Write to the resource
    args->return_value = resource->read(buffer,size,flags);
    return args;
}
References MaxOS::processes::Scheduler::current_process(), flags, and size.
Referenced by SyscallManager().
syscall_resource_write()
syscall_args_t * SyscallManager::syscall_resource_write (syscall_args_t * args) [static]
System call to write to a resource.
Parameters
args Arg0 = Handle Arg1 = Buffer Arg2 = Size Arg3 = Flags
Returns
The number of bytes written or 0 if failed
Definition at line 239 of file syscalls.cpp.
                                                                           {
    // Parse params
    auto handle = (uint64_t)args->arg0;
    auto buffer = (void*)args->arg1;
    auto size = (size_t)args->arg2;
    auto flags = (size_t)args->arg3;
    // Open the resource
    auto resource = Scheduler::current_process()->resource_manager.get_resource(handle);
    if(!resource){
        args->return_value = 0;
        return args;
    }
    // Write to the resource
    args->return_value = resource->write(buffer,size,flags);
    return args;
}
References MaxOS::processes::Scheduler::current_process(), flags, and size.
Referenced by SyscallManager().
syscall_thread_close()
syscall_args_t * SyscallManager::syscall_thread_close (syscall_args_t * args) [static]
System call to close a thread.
Parameters
args Arg0 = tid Arg1 = exit code
Returns
Nothing
Definition at line 329 of file syscalls.cpp.
                                                                         {
    // Get the args
    uint64_t tid = args->arg0;
    int exit_code = (int) args->arg1;
    // Get the thread if it is 0 then it is the current thread
    Thread* thread = tid == 0 ? Scheduler::current_thread() : Scheduler::get_thread(tid);
    // Close the thread
    Scheduler::get_process(thread->parent_pid)->remove_thread(tid);
    // Schedule the next thread
    cpu_status_t* next_thread = Scheduler::system_scheduler()->schedule_next(args->return_state);
    args->return_state = next_thread;
    // Done
    return args;
}
References MaxOS::processes::Scheduler::current_thread(), MaxOS::processes::Scheduler::get_process(), MaxOS::processes::Scheduler::get_thread(), and MaxOS::processes::Scheduler::system_scheduler().
Referenced by SyscallManager().
syscall_thread_sleep()
syscall_args_t * SyscallManager::syscall_thread_sleep (syscall_args_t * args) [static]
System call to sleep the current process.
Parameters
args Arg0 = milliseconds
Returns
Nothing
Definition at line 307 of file syscalls.cpp.
                                                                         {
    // Get the milliseconds
    size_t milliseconds = args->arg0;
    // Store the updated state in the thread as the scheduler will not have the updated state when switching to the next thread
    Scheduler::current_thread()->execution_state = args->return_state;
    // Sleep the thread
    cpu_status_t* next_thread = Scheduler::current_thread()->sleep(milliseconds);
    args->return_state = next_thread;
    // Done
    return args;
}
References MaxOS::processes::Scheduler::current_thread().
Referenced by SyscallManager().
syscall_thread_yield()
syscall_args_t * SyscallManager::syscall_thread_yield (syscall_args_t * args) [static]
System call to yield the current process.
Parameters
args Nothing
Returns
Nothing
Definition at line 291 of file syscalls.cpp.
                                                                         {
    // Yield
    Scheduler::current_thread()->execution_state = args->return_state;
    cpu_status_t* next_process = Scheduler::system_scheduler()->yield();
    args->return_state = next_process;
    return args;
}
References MaxOS::processes::Scheduler::current_thread(), and MaxOS::processes::Scheduler::system_scheduler().
Referenced by SyscallManager().
Member Data Documentation
m_current_args
syscall_args_t* MaxOS::system::SyscallManager::m_current_args [protected]
Definition at line 46 of file syscalls.h.
Referenced by handle_interrupt(), and SyscallManager().
m_syscall_handlers
syscall_func_t MaxOS::system::SyscallManager::m_syscall_handlers[256] = {} [protected]
Definition at line 45 of file syscalls.h.
{};
Referenced by handle_interrupt(), remove_syscall_handler(), and set_syscall_handler().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/system/syscalls.h
/home/runner/work/MaxOS/MaxOS/kernel/src/system/syscalls.cpp