MaxOS::net::TCPPayloadHandler Class Reference
Handler for TCP payloads.
#include <tcp.h>
Public Member Functions
TCPPayloadHandler ()
Handler///
common::Event< TCPPayloadHandlerEvents > * on_event (common::Event< TCPPayloadHandlerEvents > *event) override
Handle an event occurring on the TCP payload handler.
virtual void handle_transmission_control_protocol_payload (TCPSocket *socket, uint8_t *data, uint16_t size)
Handle TCP data received on the socket.
virtual void connected (TCPSocket *socket)
Handle a new TCP connection on the socket.
virtual void disconnected (TCPSocket *socket)
Handle a TCP disconnection on the socket.
Public Member Functions inherited from MaxOS::common::EventHandler< TCPPayloadHandlerEvents >
virtual Event< TCPPayloadHandlerEvents > * on_event (Event< TCPPayloadHandlerEvents > *event)
This function is called when an event is raised.
Detailed Description
Handler for TCP payloads.
Definition at line 158 of file tcp.h.
Member Function Documentation
connected()
void TCPPayloadHandler::connected (TCPSocket * socket) [virtual]
Handle a new TCP connection on the socket.
Parameters
socket The socket that was connected
Definition at line 40 of file tcp.cpp.
                                                   {
}
Referenced by on_event().
disconnected()
void TCPPayloadHandler::disconnected (TCPSocket * socket) [virtual]
Handle a TCP disconnection on the socket.
Parameters
socket The socket that was disconnected
Definition at line 49 of file tcp.cpp.
                                                      {
}
Referenced by on_event().
handle_transmission_control_protocol_payload()
void TCPPayloadHandler::handle_transmission_control_protocol_payload (TCPSocket * socket, uint8_t * data, uint16_t size) [virtual]
Handle TCP data received on the socket.
Parameters
socket The socket the data was received on
data The data received
size The size of the data in bytes
Definition at line 31 of file tcp.cpp.
                                                                                                                    {
}
Referenced by on_event().
on_event()
Event< TCPPayloadHandlerEvents > * TCPPayloadHandler::on_event (common::Event< TCPPayloadHandlerEvents > * event) [override]
Handle an event occurring on the TCP payload handler.
Parameters
event The event to handle
Returns
The handled event
Definition at line 59 of file tcp.cpp.
                                                                                                 {
    switch(event->type) {
        case TCPPayloadHandlerEvents::CONNECTED:
            connected(((ConnectedEvent*) event)->socket);
            break;
        case TCPPayloadHandlerEvents::DISCONNECTED:
            disconnected(((DisconnectedEvent*) event)->socket);
            break;
        case TCPPayloadHandlerEvents::DATA_RECEIVED:
            handle_transmission_control_protocol_payload(((DataReceivedEvent*) event)->socket,
                                                         ((DataReceivedEvent*) event)->data,
                                                         ((DataReceivedEvent*) event)->size);
            break;
    }
    return event;
}
References connected(), disconnected(), and handle_transmission_control_protocol_payload().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/net/tcp.h
/home/runner/work/MaxOS/MaxOS/kernel/src/net/tcp.cpp