MaxOS::gui::Desktop Class Reference
The desktop that contains all the windows, handles the drawing of the screen and the mouse on every tick.
#include <desktop.h>
Public Member Functions
Desktop (common::GraphicsContext *gc)
Creates a new desktop with the given graphics context.
void add_child (Widget *) final
Adds a child widget to the desktop.
void on_time (const common::Time &time)
Redraws the desktop when a time event occurs.
void invalidate (common::Rectangle< int32_t > &area) final
Invalidate the given area of the desktop.
void on_mouse_move_event (int8_t x, int8_t y) final
When the mouse moves on the desktop update the m_position of the mouse and redraw the cursor. Pass the event to the widget that the mouse is over.
void on_mouse_down_event (uint8_t button) final
When the mouse button is pressed pass the event to the widget that the mouse is over.
void on_mouse_up_event (uint8_t button) final
When the mouse button is released pass the event to the widget that the mouse is over.
void on_key_down (drivers::peripherals::KeyCode keyDownCode, drivers::peripherals::KeyboardState keyDownState) final
When a key is pressed pass the event to the widget that is currently focussed.
void on_key_up (drivers::peripherals::KeyCode keyUpCode, drivers::peripherals::KeyboardState keyUpState) final
When a key is pressed pass the event to the widget that is currently focussed.
Public Member Functions inherited from MaxOS::gui::CompositeWidget
CompositeWidget (int32_t left, int32_t top, uint32_t width, uint32_t height)
Construct a new Composite Widget object at a specific position and size.
void draw (common::GraphicsContext *gc, common::Rectangle< int32_t > &area) override
Draws a section of the widget and its m_children.
void on_mouse_enter_widget (uint32_t toX, uint32_t toY) override
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
void on_mouse_leave_widget (uint32_t fromX, uint32_t fromY) override
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
void on_mouse_move_widget (uint32_t fromX, uint32_t fromY, uint32_t toX, uint32_t toY) override
Passes the event to the child that the mouse is over, also generates a leave/enter event for children.
drivers::peripherals::MouseEventHandler * on_mouse_button_pressed (uint32_t x, uint32_t y, uint8_t button) override
Passes the event to the child that the mouse is over.
void on_mouse_button_released (uint32_t x, uint32_t y, uint8_t button) override
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
Public Member Functions inherited from MaxOS::gui::Widget
Widget (int32_t left, int32_t top, uint32_t width, uint32_t height)
Construct a new Widget object at a specific position and size.
void invalidate ()
Invalidates the entire widget. This forces the widget to be redrawn on the next screen update.
virtual common::Coordinates absolute_coordinates (common::Coordinates coordinates)
Get the absolute coordinates of the widget (relative to the screen)
virtual bool contains_coordinate (uint32_t x, uint32_t y)
Check if the widget contains a specific coordinate.
common::Rectangle< int32_t > position ()
Get the position of the widget.
void move (int32_t left, int32_t top)
Set the position of the widget, and invalidate the old and new positions so they are redrawn.
void resize (int32_t width, int32_t height)
Set the size of the widget, and invalidate the old and new positions so they are redrawn.
void focus ()
Set the current focused widget to be this widget.
virtual void on_focus ()
Handles the event when the widget is focussed.
virtual void on_focus_lost ()
Handles the event when the widget is unfocused.
void bring_to_front ()
Brings this widget to the front of the screen.
Public Member Functions inherited from MaxOS::drivers::peripherals::KeyboardEventHandler
common::Event< KeyboardEvents > * on_event (common::Event< KeyboardEvents > *) override
Handle the trigger of an event.
Public Member Functions inherited from MaxOS::common::EventHandler< KeyboardEvents >
virtual Event< KeyboardEvents > * on_event (Event< KeyboardEvents > *event)
This function is called when an event is raised.
Public Member Functions inherited from MaxOS::drivers::peripherals::MouseEventHandler
common::Event< MouseEvents > * on_event (common::Event< MouseEvents > *) override
Handles the triggered event and calls the appropriate function.
Public Member Functions inherited from MaxOS::common::EventHandler< MouseEvents >
virtual Event< MouseEvents > * on_event (Event< MouseEvents > *event)
This function is called when an event is raised.
Public Attributes
common::Colour colour
The background colour of the desktop (.
Protected Member Functions
void set_focus (Widget *) final
Updates the currently focussed widget to be the given widget.
void bring_to_front (Widget *) final
Brings the given widget to the front of the desktop.
void invert_mouse_cursor ()
Draws the mouse cursor at the current mouse m_position by inverting the pixels (mouse is a plus sign)
void internal_invalidate (common::Rectangle< int32_t > &area, common::Vector< common::Rectangle< int32_t > >::iterator start, common::Vector< common::Rectangle< int32_t > >::iterator stop)
Goes through the passed areas and invalidates the areas that are covered by the given area.
void draw_self (common::GraphicsContext *gc, common::Rectangle< int32_t > &area) final
Draws a certain area of the desktop.
Protected Member Functions inherited from MaxOS::gui::CompositeWidget
void draw (common::GraphicsContext *gc, common::Rectangle< int32_t > &area, common::Vector< Widget * >::iterator start)
Draws a section of the widget and the m_children after a specific child.
Protected Attributes
int32_t m_mouse_x
The horizontal position of the mouse cursor.
int32_t m_mouse_y
The vertical position of the mouse cursor.
common::GraphicsContext * m_graphics_context
Where to draw the desktop to.
Widget * m_focussed_widget { nullptr }
The widget that currently is receiving keyboard input and is at the front.
drivers::peripherals::MouseEventHandler * m_dragged_widget { nullptr }
The widget that the mouse is currently dragging.
common::Vector< common::Rectangle< int32_t > > m_invalid_areas
The areas of the desktop that need to be redrawn.
Protected Attributes inherited from MaxOS::gui::CompositeWidget
common::Vector< Widget * > m_children
Widgets contained within this composite widget.
Protected Attributes inherited from MaxOS::gui::Widget
common::Rectangle< int32_t > m_position
The position and size of the widget (relative to its parent)
Widget * m_parent { nullptr }
The widget that owns this widget.
bool m_valid { false }
Is the widget drawn to the screen and up to date.
uint32_t m_min_width { 5 }
The smallest m_width the widget can be resized to.
uint32_t m_min_height { 5 }
The smallest m_height the widget can be resized to.
uint32_t m_max_width { 0x8FFFFFFF }
The largest m_width the widget can be resized to.
uint32_t m_max_height { 0x8FFFFFFF }
The largest m_height the widget can be resized to.
Detailed Description
The desktop that contains all the windows, handles the drawing of the screen and the mouse on every tick.
Todo
Todo It is not a good idea to hardcode the mouse into the desktop as a tablet or touch screen device won't have a mouse cursor
Definition at line 28 of file desktop.h.
Constructor & Destructor Documentation
Desktop()
Desktop::Desktop (common::GraphicsContext * gc)
Creates a new desktop with the given graphics context.
Parameters
gc The graphics context to use
Definition at line 25 of file desktop.cpp.
: CompositeWidget(0, 0, gc->width(), gc->height()),
  MouseEventHandler(),
  m_graphics_context(gc),
  colour(Colour(0xA8, 0xA8, 0xA8))
{
    // Set the mouse m_position to the center of the screen
    m_mouse_x = gc->width() / 2;
    m_mouse_y = gc->height() / 2;
    // Draw the initial mouse cursor
    invert_mouse_cursor();
    // Draw the desktop
    Widget::invalidate();
}
References MaxOS::common::Rectangle< Type >::height, MaxOS::gui::Widget::invalidate(), invert_mouse_cursor(), m_mouse_x, m_mouse_y, and MaxOS::common::Rectangle< Type >::width.
Member Function Documentation
add_child()
void Desktop::add_child (Widget * child_widget) [final], [virtual]
Adds a child widget to the desktop.
Parameters
child_widget The widget to add
Reimplemented from MaxOS::gui::CompositeWidget.
Definition at line 156 of file desktop.cpp.
                                            {
    // Check if the new widget is under the mouse
    bool underMouse = child_widget->contains_coordinate(m_mouse_x, m_mouse_y);
    // If the mouse is over the widget then send a mouse leave event to the child widget as it is no longer under the mouse
    if (underMouse)
        CompositeWidget::on_mouse_leave_widget(m_mouse_x, m_mouse_y);
    // Add the widget to the desktop
    CompositeWidget::add_child(child_widget);
    // If the mouse is over the new widget then send a mouse enter event to the child widget
    if (underMouse)
        CompositeWidget::on_mouse_enter_widget(m_mouse_x, m_mouse_y);
}
References MaxOS::gui::CompositeWidget::add_child(), m_mouse_x, m_mouse_y, MaxOS::gui::CompositeWidget::on_mouse_enter_widget(), and MaxOS::gui::CompositeWidget::on_mouse_leave_widget().
bring_to_front()
void Desktop::bring_to_front (Widget * front_widget) [final], [protected], [virtual]
Brings the given widget to the front of the desktop.
Parameters
front_widget The widget to bring to the front
Reimplemented from MaxOS::gui::Widget.
Definition at line 66 of file desktop.cpp.
                                                 {
    // Remove the widget from where ever it already is
    m_children.erase(front_widget);
    // Add it back in the front
    m_children.push_front(front_widget);
}
References MaxOS::gui::CompositeWidget::m_children.
draw_self()
void Desktop::draw_self (common::GraphicsContext * gc, common::Rectangle< int32_t > & area) [final], [protected], [virtual]
Draws a certain area of the desktop.
Parameters
gc The graphics context to draw with
area The area to draw
Reimplemented from MaxOS::gui::CompositeWidget.
Definition at line 139 of file desktop.cpp.
                                                                                 {
    // Calculate the rectangle
    int32_t topCornerX = area.left;
    int32_t topCornerY = area.top;
    int32_t bottomCornerX = area.left + area.width;
    int32_t bottomCornerY = area.top + area.height;
    // Draw the background, a rectangle the size of the desktop of the given colour
    gc->fill_rectangle(topCornerX, topCornerY, bottomCornerX, bottomCornerY, colour);
}
References colour, MaxOS::common::Rectangle< Type >::height, MaxOS::common::Rectangle< Type >::left, MaxOS::common::Rectangle< Type >::top, and MaxOS::common::Rectangle< Type >::width.
internal_invalidate()
void Desktop::internal_invalidate (common::Rectangle< int32_t > & area, common::Vector< common::Rectangle< int32_t > >::iterator start, common::Vector< common::Rectangle< int32_t > >::iterator stop) [protected]
Goes through the passed areas and invalidates the areas that are covered by the given area.
Parameters
area The area that is now invalid
start The start of the invalid areas
stop The end of the invalid areas
Definition at line 98 of file desktop.cpp.
                                                                           {
    // Loop through the invalid rectangles
    for (Vector<Rectangle<int32_t>>::iterator invaild_rect = start; invaild_rect != stop; invaild_rect++) {
        // Check if the area intersects with the invalid rectangle
        if (!area.intersects(*invaild_rect))
            continue;
        // Get the parts of the area that are covered by the invalid rectangle
        Vector<Rectangle<int32_t>> coveredAreas = area.subtract(*invaild_rect);
        // Invalidate the covered areas
        for (auto& coveredArea: coveredAreas)
            internal_invalidate(coveredArea, invaild_rect + 1, stop);
        // The entire area will be invalidated by now
        return;
    }
    // Add the area to the invalid areas, store where it was added
    Vector<Rectangle<int32_t>>::iterator vectorPosition = m_invalid_areas.push_back(area);
    // If the m_position is the last item then the invalidation buffer is full
    if (vectorPosition == m_invalid_areas.end()) {
        // Invalidate the entire desktop
        m_invalid_areas.clear();
        Widget::invalidate();
    }
}
References internal_invalidate(), MaxOS::common::Rectangle< Type >::intersects(), MaxOS::gui::Widget::invalidate(), m_invalid_areas, and MaxOS::common::Rectangle< Type >::subtract().
Referenced by internal_invalidate(), and invalidate().
invalidate()
void Desktop::invalidate (common::Rectangle< int32_t > & area) [final], [virtual]
Invalidate the given area of the desktop.
Parameters
area The area that is now invalid
Reimplemented from MaxOS::gui::Widget.
Definition at line 207 of file desktop.cpp.
                                                 {
    // Invalidate the area
    internal_invalidate(area, m_invalid_areas.begin(), m_invalid_areas.end());
}
References internal_invalidate(), and m_invalid_areas.
invert_mouse_cursor()
void Desktop::invert_mouse_cursor () [protected]
Draws the mouse cursor at the current mouse m_position by inverting the pixels (mouse is a plus sign)
Definition at line 78 of file desktop.cpp.
                                  {
    // Draw the horizontal line
    for (int32_t x = m_mouse_x - 3; x <= m_mouse_x + 3; ++x) {
        m_graphics_context->invert_pixel(x, m_mouse_y);
    }
    // Draw the vertical line
    for (int32_t y = m_mouse_y - 3; y <= m_mouse_y + 3; ++y) {
        m_graphics_context->invert_pixel(m_mouse_x, y);
    }
}
References MaxOS::common::GraphicsContext::invert_pixel(), m_graphics_context, m_mouse_x, and m_mouse_y.
Referenced by Desktop(), on_mouse_move_event(), and on_time().
on_key_down()
void Desktop::on_key_down (drivers::peripherals::KeyCode keyDownCode, drivers::peripherals::KeyboardState keyDownState) [final], [virtual]
When a key is pressed pass the event to the widget that is currently focussed.
Parameters
keyDownCode The key that was pressed
keyDownState The state of the keyboard
Reimplemented from MaxOS::drivers::peripherals::KeyboardEventHandler.
Definition at line 283 of file desktop.cpp.
                                                                         {
    // Pass the event to the widget that is in focus
    if (m_focussed_widget != nullptr)
        m_focussed_widget->on_key_down(keyDownCode, keyDownState);
}
References m_focussed_widget, and MaxOS::drivers::peripherals::KeyboardEventHandler::on_key_down().
on_key_up()
void Desktop::on_key_up (drivers::peripherals::KeyCode keyUpCode, drivers::peripherals::KeyboardState keyUpState) [final], [virtual]
When a key is pressed pass the event to the widget that is currently focussed.
Parameters
keyUpCode The key that was pressed
keyUpState The state of the keyboard
Reimplemented from MaxOS::drivers::peripherals::KeyboardEventHandler.
Definition at line 295 of file desktop.cpp.
                                                                   {
    // Pass the event to the widget that is in focus
    if (m_focussed_widget != nullptr)
        m_focussed_widget->on_key_up(keyUpCode, keyUpState);
}
References m_focussed_widget, and MaxOS::drivers::peripherals::KeyboardEventHandler::on_key_up().
on_mouse_down_event()
void Desktop::on_mouse_down_event (uint8_t button) [final], [virtual]
When the mouse button is pressed pass the event to the widget that the mouse is over.
Parameters
button The button that was pressed
Reimplemented from MaxOS::drivers::peripherals::MouseEventHandler.
Definition at line 258 of file desktop.cpp.
                                                {
    // The widget that handled the event becomes the widget being dragged
    m_dragged_widget = CompositeWidget::on_mouse_button_pressed(m_mouse_x, m_mouse_y, button);
}
References m_dragged_widget, m_mouse_x, m_mouse_y, and MaxOS::gui::CompositeWidget::on_mouse_button_pressed().
on_mouse_move_event()
void Desktop::on_mouse_move_event (int8_t x, int8_t y) [final], [virtual]
When the mouse moves on the desktop update the m_position of the mouse and redraw the cursor. Pass the event to the widget that the mouse is over.
Parameters
x The x m_position of the mouse
y The y m_position of the mouse
Reimplemented from MaxOS::drivers::peripherals::MouseEventHandler.
Definition at line 221 of file desktop.cpp.
                                                    {
    // Calculate the m_position of the mouse on the desktop
    Rectangle<int32_t> desktopPosition = position();
    int32_t newMouseX = m_mouse_x + x;
    int32_t newMouseY = m_mouse_y + y;
    // Restrain the mouse to the desktop
    if (newMouseX < 0) newMouseX = 0;
    if (newMouseY < 0) newMouseY = 0;
    if (newMouseX > desktopPosition.width) newMouseX = desktopPosition.width - 1;
    if (newMouseY > desktopPosition.height) newMouseY = desktopPosition.height - 1;
    // Remove the old cursor from the screen as it will be redrawn in the new m_position
    invert_mouse_cursor();
    // If a widget is being dragged then pass the event to it
    if (m_dragged_widget != nullptr)
        m_dragged_widget->on_mouse_move_event(newMouseX - m_mouse_x, newMouseY - m_mouse_y);
    // Handle the mouse moving event (pass it to the widget that the mouse is over)
    CompositeWidget::on_mouse_move_widget(m_mouse_x, m_mouse_y, newMouseX,
                                          newMouseY);
    // Update the mouse m_position
    m_mouse_x = newMouseX;
    m_mouse_y = newMouseY;
    // Draw the new cursor
    invert_mouse_cursor();
}
References MaxOS::common::Rectangle< Type >::height, invert_mouse_cursor(), m_dragged_widget, m_mouse_x, m_mouse_y, MaxOS::drivers::peripherals::MouseEventHandler::on_mouse_move_event(), MaxOS::gui::CompositeWidget::on_mouse_move_widget(), MaxOS::gui::Widget::position(), and MaxOS::common::Rectangle< Type >::width.
on_mouse_up_event()
void Desktop::on_mouse_up_event (uint8_t button) [final], [virtual]
When the mouse button is released pass the event to the widget that the mouse is over.
Parameters
button The button that was released
Reimplemented from MaxOS::drivers::peripherals::MouseEventHandler.
Definition at line 269 of file desktop.cpp.
                                              {
    // Pass the event to the widget
    CompositeWidget::on_mouse_button_released(m_mouse_x, m_mouse_y, button);
    // Dragging has stopped
    m_dragged_widget = nullptr;
}
References m_dragged_widget, m_mouse_x, m_mouse_y, and MaxOS::gui::CompositeWidget::on_mouse_button_released().
on_time()
void Desktop::on_time (const common::Time & time)
Redraws the desktop when a time event occurs.
Parameters
time The time when the event occurred
Definition at line 178 of file desktop.cpp.
                                       {
    // Check if anything is invalid and needs to be redrawn
    if (m_invalid_areas.empty())
        return;
    // Erase the mouse cursor
    invert_mouse_cursor();
    // Loop through the invalid areas
    while (!m_invalid_areas.empty()) {
        // Redraw the m_first_memory_chunk area
        Rectangle<int32_t> invalidArea = *(m_invalid_areas.begin());
        m_invalid_areas.pop_front();
        draw(m_graphics_context, invalidArea);
    }
    // Can now draw the mouse cursor
    invert_mouse_cursor();
}
References MaxOS::gui::CompositeWidget::draw(), invert_mouse_cursor(), m_graphics_context, and m_invalid_areas.
set_focus()
void Desktop::set_focus (Widget * widget) [final], [protected], [virtual]
Updates the currently focussed widget to be the given widget.
Parameters
widget The widget that is now in focus
Reimplemented from MaxOS::gui::Widget.
Definition at line 50 of file desktop.cpp.
                                      {
    // If there is a widget in focus then send a focus lost event to it
    if (this->m_focussed_widget != nullptr)
        this->m_focussed_widget->on_focus_lost();
    // Focus the new widget and send a focus event to it
    this->m_focussed_widget = widget;
    this->m_focussed_widget->on_focus();
}
References m_focussed_widget, MaxOS::gui::Widget::on_focus(), and MaxOS::gui::Widget::on_focus_lost().
Member Data Documentation
colour
common::Colour MaxOS::gui::Desktop::colour
The background colour of the desktop (.
Todo
Todo : replace with image, make priv)
Definition at line 48 of file desktop.h.
Referenced by draw_self().
m_dragged_widget
drivers::peripherals::MouseEventHandler* MaxOS::gui::Desktop::m_dragged_widget { nullptr } [protected]
The widget that the mouse is currently dragging.
Definition at line 37 of file desktop.h.
{ nullptr };
Referenced by on_mouse_down_event(), on_mouse_move_event(), and on_mouse_up_event().
m_focussed_widget
Widget* MaxOS::gui::Desktop::m_focussed_widget { nullptr } [protected]
The widget that currently is receiving keyboard input and is at the front.
Definition at line 36 of file desktop.h.
{ nullptr };
Referenced by on_key_down(), on_key_up(), and set_focus().
m_graphics_context
common::GraphicsContext* MaxOS::gui::Desktop::m_graphics_context [protected]
Where to draw the desktop to.
Definition at line 34 of file desktop.h.
Referenced by invert_mouse_cursor(), and on_time().
m_invalid_areas
common::Vector<common::Rectangle<int32_t> > MaxOS::gui::Desktop::m_invalid_areas [protected]
The areas of the desktop that need to be redrawn.
Definition at line 43 of file desktop.h.
Referenced by internal_invalidate(), invalidate(), and on_time().
m_mouse_x
int32_t MaxOS::gui::Desktop::m_mouse_x [protected]
The horizontal position of the mouse cursor.
Definition at line 31 of file desktop.h.
Referenced by add_child(), Desktop(), invert_mouse_cursor(), on_mouse_down_event(), on_mouse_move_event(), and on_mouse_up_event().
m_mouse_y
int32_t MaxOS::gui::Desktop::m_mouse_y [protected]
The vertical position of the mouse cursor.
Definition at line 32 of file desktop.h.
Referenced by add_child(), Desktop(), invert_mouse_cursor(), on_mouse_down_event(), on_mouse_move_event(), and on_mouse_up_event().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/desktop.h
/home/runner/work/MaxOS/MaxOS/kernel/src/gui/desktop.cpp