MaxOS::common::Map< Key, Value > Class Template Reference
A list of key-value pairs.
#include <map.h>
Public Types
typedef Vector< Pair< Key, Value > >::iterator iterator
The iterator type for the map.
Public Member Functions
Value & operator[] (Key)
Overloads the [] operator to return the value of the key.
bool empty ()
Returns whether the map is empty.
int size ()
The number of elements in the map.
iterator begin ()
Returns the beginning of the map.
iterator end ()
Returns the end of the map.
iterator find (Key)
Finds an element in the map based on the key.
iterator push_back (Key, Value)
Adds a new key-value pair to the end of the map.
Pair< Key, Value > pop_back ()
Removes the last key-value pair from the map and returns it.
iterator push_front (Key, Value)
Adds a new key-value pair to the front of the map.
Pair< Key, Value > pop_front ()
Removes the first key-value pair from the map and returns it.
void insert (Key, Value)
Updates the value of an element, or adds a new element if it does not exist.
void erase (Key)
Removes an element from the map.
void erase (iterator position)
Removes an element from the map at the specified position.
void clear ()
Removes all elements from the map.
void reserve (size_t amount)
Reserves space in the map for a certain amount of elements to avoid reallocations.
void increase_size ()
Doubles the size of the map.
void iterate (MapIterationHandler< Key, Value > *handler)
Iterates through the map and calls the handler.
void iterate (void(*callback)(Key &, Value &))
Iterates through the map and calls the callback.
Protected Attributes
Vector< Pair< Key, Value > > m_elements
The internal storage of the map, a vector of key-value pairs.
Detailed Description
template<class Key, class Value>
class MaxOS::common::Map< Key, Value >
A list of key-value pairs.
Template Parameters
Key The key type
Value The value type
Definition at line 43 of file map.h.
Member Typedef Documentation
iterator
template<class Key , class Value >
typedef Vector<Pair<Key,Value>>::iterator MaxOS::common::Map< Key, Value >::iterator
The iterator type for the map.
Definition at line 49 of file map.h.
Member Function Documentation
begin()
template<class Key , class Value >
Map< Key, Value >::iterator MaxOS::common::Map< Key, Value >::begin ()
Returns the beginning of the map.
Template Parameters
Key The key type
Value The value type
Returns
The m_first_memory_chunk element in the map
Definition at line 133 of file map.h.
                                                                                                 {
            return m_elements.begin();
        }
References MaxOS::common::Vector< Type >::begin().
clear()
template<class Key , class Value >
void MaxOS::common::Map< Key, Value >::clear ()
Removes all elements from the map.
Template Parameters
Key The key type
Value The value type
Definition at line 245 of file map.h.
                                                                     {
          m_elements.clear();
        }
References MaxOS::common::Vector< Type >::clear().
empty()
template<class Key , class Value >
bool MaxOS::common::Map< Key, Value >::empty ()
Returns whether the map is empty.
Template Parameters
Key The key type
Value The value type
Returns
Whether the map is empty
Definition at line 223 of file map.h.
                                                                     {
            return m_elements.empty();
        }
References MaxOS::common::Vector< Type >::empty().
end()
template<class Key , class Value >
Map< Key, Value >::iterator MaxOS::common::Map< Key, Value >::end ()
Returns the end of the map.
Template Parameters
Key The key type
Value The value type
Returns
The last element in the map
Definition at line 144 of file map.h.
                                                                                               {
            return m_elements.end();
        }
References MaxOS::common::Vector< Type >::end().
Referenced by MaxOS::processes::SharedMemory::open(), MaxOS::processes::SharedMemory::read(), and MaxOS::net::AddressResolutionProtocol::Resolve().
erase() [1/2]
template<class Key , class Value >
void MaxOS::common::Map< Key, Value >::erase (Map< Key, Value >::iterator position)
Removes an element from the map at the specified position.
Template Parameters
Key The key type
Value The value type
Parameters
position The iterator of the element to remove
Definition at line 297 of file map.h.
                                                                                         {
            m_elements.erase(position);
        }
References MaxOS::common::Vector< Type >::erase().
erase() [2/2]
template<class Key , class Value >
void MaxOS::common::Map< Key, Value >::erase (Key key)
Removes an element from the map.
Template Parameters
Key The key type
Value The value type
Parameters
key The key of the element to remove
Definition at line 278 of file map.h.
                                                                            {
            // Find the element
            iterator it = find(key);
            // If the element is found then remove it
            if (it != end()) {
                m_elements.erase(it);
            }
        }
References MaxOS::common::Vector< Type >::erase().
Referenced by MaxOS::processes::BaseResourceRegistry::close_resource().
find()
template<class Key , class Value >
Map< Key, Value >::iterator MaxOS::common::Map< Key, Value >::find (Key element)
Finds an element in the map based on the key.
Template Parameters
Key The key type
Value The value type
Parameters
element The key to search for
Returns
The iterator of the element, or the end iterator if not found
Definition at line 156 of file map.h.
                                                                                                           {
            // Search for the element
            for (iterator it = begin(); it != end(); it++)
                if (it -> first == element)
                    return it;
            // Item not found
            return end();
        }
Referenced by MaxOS::processes::SharedMemory::open(), MaxOS::processes::SharedMemory::read(), and MaxOS::net::AddressResolutionProtocol::Resolve().
increase_size()
template<class Key , class Value >
void MaxOS::common::Map< Key, Value >::increase_size ()
Doubles the size of the map.
Template Parameters
Key The key type
Value The value type
Definition at line 319 of file map.h.
                                                                             {
            m_elements.increase_size();
        }
References MaxOS::common::Vector< Type >::increase_size().
insert()
template<class Key , class Value >
void MaxOS::common::Map< Key, Value >::insert (Key key, Value value)
Updates the value of an element, or adds a new element if it does not exist.
Template Parameters
Key The key type
Value The value type
Parameters
key The key of the new element
value The value of the new element
Definition at line 257 of file map.h.
                                                                                          {
            // Find the element
            iterator it = find(key);
            // If the element is found then update the value
            if (it != end()) {
                it -> second = value;
            } else {
                // Otherwise, add a new element
                m_elements.push_back(Pair<Key, Value>(key, value));
            }
        }
References MaxOS::common::Vector< Type >::push_back().
Referenced by MaxOS::processes::GlobalScheduler::add_process(), MaxOS::processes::GlobalScheduler::add_thread(), MaxOS::net::AddressResolutionProtocol::handleEthernetframePayload(), MaxOS::processes::SharedMemory::open(), MaxOS::processes::BaseResourceRegistry::register_resource(), and MaxOS::net::AddressResolutionProtocol::Store().
iterate() [1/2]
template<class Key , class Value >
void MaxOS::common::Map< Key, Value >::iterate (MapIterationHandler< Key, Value > * handler)
Iterates through the map and calls the handler.
Template Parameters
Key The key type
Value The value type
Parameters
handler The handler to call
Definition at line 330 of file map.h.
                                                                                                               {
            // Loop through the elements
            for(auto& it : m_elements) {
                // Call the handler
                handler->on_read(it.first, it.second);
            }
            // Call the handler
            handler->on_end_of_stream();
        }
References MaxOS::common::MapIterationHandler< Key, Value >::on_end_of_stream(), and MaxOS::common::MapIterationHandler< Key, Value >::on_read().
iterate() [2/2]
template<class Key , class Value >
void MaxOS::common::Map< Key, Value >::iterate (void(*)(Key &, Value &) callback)
Iterates through the map and calls the callback.
Template Parameters
Key The key type
Value The value type
Parameters
callback The callback to call
Definition at line 351 of file map.h.
                                                                                                       {
            // Call the callback for each element
            for(auto& it : m_elements) {
                    callback(it.first, it.second);
            }
        }
operator[]()
template<class Key , class Value >
Value & MaxOS::common::Map< Key, Value >::operator[] (Key key)
Overloads the [] operator to return the value of the key.
Template Parameters
Key The key type
Value The value type
Parameters
key The key to search for
Returns
The value of the key
Definition at line 120 of file map.h.
                                                                                   {
            // Return the value of the key (second item in the pair)
            return find(key) -> second;
        }
pop_back()
template<class Key , class Value >
Pair< Key, Value > MaxOS::common::Map< Key, Value >::pop_back ()
Removes the last key-value pair from the map and returns it.
Template Parameters
Key The key type
Value The value type
Returns
Definition at line 188 of file map.h.
                                                                                    {
            return m_elements.pop_back();
        }
References MaxOS::common::Vector< Type >::pop_back().
pop_front()
template<class Key , class Value >
Pair< Key, Value > MaxOS::common::Map< Key, Value >::pop_front ()
Removes the first key-value pair from the map and returns it.
Template Parameters
Key The key type
Value The value type
Returns
The removed key-value pair
Definition at line 212 of file map.h.
                                                                                     {
            return m_elements.pop_front();
        }
References MaxOS::common::Vector< Type >::pop_front().
push_back()
template<class Key , class Value >
Map< Key, Value >::iterator MaxOS::common::Map< Key, Value >::push_back (Key key, Value value)
Adds a new key-value pair to the end of the map.
Template Parameters
Key The key type
Value The value type
Parameters
key The key
value The value
Returns
The iterator of the new element
Definition at line 177 of file map.h.
                                                                                                                {
            return m_elements.push_back(Pair<Key, Value>(key, value));
        }
References MaxOS::common::Vector< Type >::push_back().
push_front()
template<class Key , class Value >
Map< Key, Value >::iterator MaxOS::common::Map< Key, Value >::push_front (Key key, Value value)
Adds a new key-value pair to the front of the map.
Template Parameters
Key The key type
Value The value type
Parameters
key The key
value The value
Returns
Definition at line 201 of file map.h.
                                                                                                                 {
            return m_elements.push_front({key, value});
        }
References MaxOS::common::Vector< Type >::push_front().
reserve()
template<class Key , class Value >
void MaxOS::common::Map< Key, Value >::reserve (size_t amount)
Reserves space in the map for a certain amount of elements to avoid reallocations.
Template Parameters
Key The key type
Value The value type
Parameters
amount The amount of elements to reserve space for
Definition at line 309 of file map.h.
                                                                                    {
            m_elements.reserve(amount);
        }
References MaxOS::common::Vector< Type >::reserve().
size()
template<class Key , class Value >
int MaxOS::common::Map< Key, Value >::size ()
The number of elements in the map.
Returns
The number of elements in the Map
Definition at line 232 of file map.h.
        {
            // Return the size of the vector
            return m_elements.size();
        }
References MaxOS::common::Vector< Type >::size().
Member Data Documentation
m_elements
template<class Key , class Value >
Vector<Pair<Key, Value> > MaxOS::common::Map< Key, Value >::m_elements [protected]
The internal storage of the map, a vector of key-value pairs.
Definition at line 46 of file map.h.
The documentation for this class was generated from the following file:
/home/runner/work/MaxOS/MaxOS/kernel/include/common/map.h