MaxOS::net::InternetControlMessageProtocol Class Reference
#include <icmp.h>
Public Member Functions
InternetControlMessageProtocol (InternetProtocolHandler *internetProtocolHandler, common::OutputStream *errorMessages)
~InternetControlMessageProtocol ()
bool handleInternetProtocolPayload (InternetProtocolAddress sourceIP, InternetProtocolAddress destinationIP, uint8_t *payloadData, uint32_t size)
Called by the InternetProtocolProvider when a new packet has arrived.
void RequestEchoReply (InternetProtocolAddress address)
Sends an ICMP echo request to the specified IP address.
Detailed Description
Definition at line 25 of file icmp.h.
Constructor & Destructor Documentation
InternetControlMessageProtocol()
InternetControlMessageProtocol::InternetControlMessageProtocol (InternetProtocolHandler * internetProtocolHandler, common::OutputStream * errorMessages)
Definition at line 12 of file icmp.cpp.
: InternetProtocolPayloadHandler(internetProtocolHandler, 0x01)
{
    this -> errorMessages = errorMessages;
}
 InternetControlMessageProtocol()
InternetControlMessageProtocol::~InternetControlMessageProtocol ()
Definition at line 20 of file icmp.cpp.
                                                                {
}
Member Function Documentation
handleInternetProtocolPayload()
bool InternetControlMessageProtocol::handleInternetProtocolPayload (InternetProtocolAddress sourceIP, InternetProtocolAddress destinationIP, uint8_t * payloadData, uint32_t size) [virtual]
Called by the InternetProtocolProvider when a new packet has arrived.
Parameters
srcIP_BE The source IP address of the packet
dstIP_BE The destination IP address of the packet
internetprotocolPayload The payload of the packet
size The size of the payload
Returns
True if the packet is to be sent back to the sender, false otherwise
Reimplemented from MaxOS::net::InternetProtocolPayloadHandler.
Definition at line 33 of file icmp.cpp.
{
    errorMessages -> write("ICMP received a packet\n");
    // Check if the size is at least the size of the header
    if(size < sizeof(InternetControlMessageProtocolHeader)){
        return false;
    }
    // Cast the payload to the ICMP header
    InternetControlMessageProtocolHeader* icmp = (InternetControlMessageProtocolHeader*)payloadData;
    switch (icmp -> type) {
        case 0: // Echo reply
            // TODO: reply to the ping
            break;
        case 8: // Echo request
            // Create a response
            icmp -> type = 0; // Echo reply
            icmp -> checksum = 0; // Reset the checksum
            icmp -> checksum = InternetProtocolHandler::Checksum((uint16_t *)&icmp, sizeof(InternetControlMessageProtocolHeader)); // Calculate the checksum
            return true; //Send data back
    }
    return false;
    //TODO: Implement the rest of the ICMP messages
}
References checksum, MaxOS::net::InternetProtocolHandler::Checksum(), size, type, and write.
RequestEchoReply()
void InternetControlMessageProtocol::RequestEchoReply (InternetProtocolAddress address)
Sends an ICMP echo request to the specified IP address.
Parameters
ip_be The IP address to send the request to
Definition at line 77 of file icmp.cpp.
                                                                    {
    errorMessages -> write("ICMP: Sending echo request\n");
    InternetControlMessageProtocolHeader icmp;
    icmp.type = 8; // Echo request
    icmp.code = 0; // Code must be 0
    icmp.checksum = 0; // Checksum must be 0 to calculate it
    icmp.data = 0x69420; // Data
    icmp.checksum = InternetProtocolHandler::Checksum((uint16_t *)&icmp, sizeof(InternetControlMessageProtocolHeader));
    Send(ip_be, (uint8_t *)&icmp, sizeof(InternetControlMessageProtocolHeader));
    errorMessages -> write("ICMP: Echo request sent\n");
}
References MaxOS::net::InternetControlMessageProtocolHeader::checksum, MaxOS::net::InternetProtocolHandler::Checksum(), MaxOS::net::InternetControlMessageProtocolHeader::code, MaxOS::net::InternetControlMessageProtocolHeader::data, MaxOS::net::InternetProtocolPayloadHandler::Send(), MaxOS::net::InternetControlMessageProtocolHeader::type, and write.
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/net/icmp.h
/home/runner/work/MaxOS/MaxOS/kernel/src/net/icmp.cpp