MaxOS::hardwarecommunication::InterruptHandler Class Reference
Handles a certain interrupt number.
#include <interrupts.h>
Public Member Functions
virtual void handle_interrupt ()
Handles an interrupt.
virtual system::cpu_status_t * handle_interrupt (system::cpu_status_t *status)
Handles an interrupt and returns the status.
Protected Member Functions
InterruptHandler (uint8_t interrupt_number, int64_t redirect=-1, uint64_t redirect_index=0)
Creates a new interrupt handler and registers it with the interrupt manager.
Protected Attributes
uint8_t m_interrupt_number
The interrupt number this handler handles.
Detailed Description
Handles a certain interrupt number.
Definition at line 32 of file interrupts.h.
Constructor & Destructor Documentation
InterruptHandler()
InterruptHandler::InterruptHandler (uint8_t interrupt_number, int64_t redirect = -1, uint64_t redirect_index = 0) [protected]
Creates a new interrupt handler and registers it with the interrupt manager.
Parameters
interrupt_number The interrupt number to handle
redirect What legacy interrupt to redirect from (-1 for no redirection)
redirect_index Which index of the legacy interrupt to redirect from
Definition at line 24 of file interrupts.cpp.
: m_interrupt_number(interrupt_number)
{
    // Get the interrupt manager
    InterruptManager* interrupt_manager = InterruptManager::s_active_interrupt_manager;
    ASSERT(interrupt_manager != nullptr, "No active interrupt manager");
    // Register the handler
    interrupt_manager->set_interrupt_handler(m_interrupt_number, this);
    // Not all interrupts need redirecting
    if (redirect == -1)
        return;
    // Redirect a legacy interrupt to an interrupt the kernel expects
    IOAPIC* io_apic = interrupt_manager->active_apic()->io_apic();
    interrupt_redirect_t temp = {
            .type = (uint8_t) redirect,
            .index = (uint8_t) redirect_index,
            .interrupt = m_interrupt_number,
            .destination = 0x00,
            .flags = 0x00,
            .mask = false,
    };
    io_apic->set_redirect(&temp);
}
References ASSERT, m_interrupt_number, MaxOS::hardwarecommunication::InterruptManager::s_active_interrupt_manager, and MaxOS::hardwarecommunication::IOAPIC::set_redirect().
~InterruptHandler()
InterruptHandler::~InterruptHandler () [protected]
Definition at line 53 of file interrupts.cpp.
                                    {
    // Get the interrupt manager
    InterruptManager* interrupt_manager = InterruptManager::s_active_interrupt_manager;
    if (interrupt_manager == nullptr) return;
    // Remove the handler
    interrupt_manager->set_interrupt_handler(m_interrupt_number, nullptr);
}
Member Function Documentation
handle_interrupt() [1/2]
void InterruptHandler::handle_interrupt () [virtual]
Handles an interrupt.
Reimplemented in MaxOS::drivers::ethernet::AMD_AM79C973, MaxOS::drivers::ethernet::IntelI217, and MaxOS::drivers::peripherals::KeyboardDriver.
Definition at line 66 of file interrupts.cpp.
                                        {
}
Referenced by handle_interrupt(), and MaxOS::hardwarecommunication::InterruptManager::handle_interrupt_request().
handle_interrupt() [2/2]
system::cpu_status_t * InterruptHandler::handle_interrupt (system::cpu_status_t * status) [virtual]
Handles an interrupt and returns the status.
Parameters
status The status of the CPU
Returns
The status of the CPU
Reimplemented in MaxOS::processes::GlobalScheduler.
Definition at line 76 of file interrupts.cpp.
                                                                                 {
    // For handlers that don't care about the status
    handle_interrupt();
    // Return the default status
    return status;
}
References handle_interrupt().
Member Data Documentation
m_interrupt_number
uint8_t MaxOS::hardwarecommunication::InterruptHandler::m_interrupt_number [protected]
The interrupt number this handler handles.
Definition at line 34 of file interrupts.h.
Referenced by InterruptHandler().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/interrupts.h
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/interrupts.cpp