MaxOS::drivers::disk::AdvancedTechnologyAttachment Class Reference
Driver for the ATA controller, handles the reading and writing of data to the hard drive.
#include <ata.h>
Public Member Functions
AdvancedTechnologyAttachment (uint16_t port_base, bool master)
Constructor for the AdvancedTechnologyAttachment class.
bool identify ()
Identify the ATA device.
void read (uint32_t sector, common::buffer_t *data_buffer, size_t amount) final
read a sector from the ATA device
void write (uint32_t sector, common::buffer_t *data, size_t count) final
write to a sector on the ATA device
void flush () final
Flush the cache of the ATA device.
string device_name () final
Get the device name.
string vendor_name () final
Get the vendor name.
Public Member Functions inherited from MaxOS::drivers::disk::Disk
void read (uint32_t sector, common::buffer_t *data_buffer)
read data from the disk into a buffer (max capacity 512 bytes)
void write (uint32_t sector, common::buffer_t *data)
write data to the disk from a buffer (max capacity 512 bytes)
void activate () override
Activate the disk driver.
string device_name () override
Get the device name.
string vendor_name () override
Get the vendor name.
Public Member Functions inherited from MaxOS::drivers::Driver
virtual void deactivate ()
Deactivate the driver.
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
Detailed Description
Driver for the ATA controller, handles the reading and writing of data to the hard drive.
Definition at line 25 of file ata.h.
Constructor & Destructor Documentation
AdvancedTechnologyAttachment()
AdvancedTechnologyAttachment::AdvancedTechnologyAttachment (uint16_t port_base, bool master)
Constructor for the AdvancedTechnologyAttachment class.
Parameters
port_base The base port for the ATA device
master True if the device is master, false if slave
Definition at line 23 of file ata.cpp.
        : m_data_port(port_base),
        m_error_port(port_base + 1),
        m_sector_count_port(port_base + 2),
        m_LBA_low_port(port_base + 3),
        m_LBA_mid_port(port_base + 4),
        m_LBA_high_Port(port_base + 5),
        m_device_port(port_base + 6),
        m_command_port(port_base + 7),
        m_control_port(port_base + 0x206),
        m_is_master(master) {
}
Member Function Documentation
device_name()
string AdvancedTechnologyAttachment::device_name () [final], [virtual]
Get the device name.
Returns
The name of the device
Reimplemented from MaxOS::drivers::Driver.
Definition at line 248 of file ata.cpp.
                                                 {
    return "Advanced Technology Attachment";
}
flush()
void AdvancedTechnologyAttachment::flush () [final], [virtual]
Flush the cache of the ATA device.
Reimplemented from MaxOS::drivers::disk::Disk.
Definition at line 219 of file ata.cpp.
                                         {
    // Select the device (master or slave)
    m_device_port.write(m_is_master ? 0xE0 : 0xF0);
    // Send the flush command
    m_command_port.write(0xE7);
    // Make sure the device is there
    uint8_t status = m_command_port.read();
    if (status == 0x00)
        return;
    // Wait for the device to be ready or for an error to occur
    while (((status & 0x80) == 0x80) && ((status & 0x01) != 0x01))
        status = m_command_port.read();
    // Check for an error
    if (status & 0x01)
        return;
    // ...
}
References MaxOS::hardwarecommunication::Port8Bit::read(), and MaxOS::hardwarecommunication::Port8Bit::write().
Referenced by write().
identify()
bool AdvancedTechnologyAttachment::identify ()
Identify the ATA device.
Returns
True if the device is present, false otherwise
Definition at line 44 of file ata.cpp.
                                            {
    // Select the device (master or slave)
    m_device_port.write(m_is_master ? 0xA0 : 0xB0);
    // Reset the High Order Byte
    m_control_port.write(0);
    // Check if the master is present
    m_device_port.write(0xA0);
    uint8_t status = m_command_port.read();
    if (status == 0xFF) {
        Logger::WARNING() << "ATA Device: Invalid status";
        return false;
    }
    // Select the device (master or slave)
    m_device_port.write(m_is_master ? 0xA0 : 0xB0);
    // Clear the ports
    m_sector_count_port.write(0);
    m_LBA_low_port.write(0);
    m_LBA_mid_port.write(0);
    m_LBA_high_Port.write(0);
    // Check if the device is present
    m_command_port.write(0x0EC);
    status = m_command_port.read();
    if (status == 0x00)
        return false;
    // Wait for the device to be ready or for an error to occur
    while (((status & 0x80) == 0x80) && ((status & 0x01) != 0x01))
        status = m_command_port.read();
    //Check for any errors
    if (status & 0x01) {
        Logger::WARNING() << "ATA Device: Error reading status\n";
        return false;
    }
    // Read the rest of the data as a whole sector needs to be read (force the compiler to do so)
    for (uint16_t i = 0; i < 256; ++i) {
        volatile uint16_t data = m_data_port.read();
        (void) data;
    }
    // Device is present and ready
    return true;
}
References MaxOS::hardwarecommunication::Port8Bit::read(), MaxOS::hardwarecommunication::Port16Bit::read(), MaxOS::Logger::WARNING(), and MaxOS::hardwarecommunication::Port8Bit::write().
read()
void AdvancedTechnologyAttachment::read (uint32_t sector, common::buffer_t * data_buffer, size_t amount) [final], [virtual]
read a sector from the ATA device
Parameters
sector The sector to read
data_buffer The data to read into
amount The amount of bytes to read from that sector
Reimplemented from MaxOS::drivers::disk::Disk.
Definition at line 103 of file ata.cpp.
                                                                                             {
    // Don't allow reading more than a sector
    if (sector & 0xF0000000 || amount > m_bytes_per_sector)
        return;
    // Select the device (master or slave)
    m_device_port.write((m_is_master ? 0xE0 : 0xF0) | ((sector & 0x0F000000) >> 24));
    // Device is busy @todo yield
    while ((m_command_port.read() & 0x80) != 0);
    // Reset the device
    m_error_port.write(0);
    m_sector_count_port.write(1);
    // Split the sector into the ports
    m_LBA_low_port.write(sector & 0x000000FF);
    m_LBA_mid_port.write((sector & 0x0000FF00) >> 8);
    m_LBA_high_Port.write((sector & 0x00FF0000) >> 16);
    // Tell the device to prepare for reading
    m_command_port.write(0x20);
    // Make sure the device is there
    uint8_t status = m_command_port.read();
    if (status == 0x00)
        return;
    // Wait for the device to be ready or for an error to occur @todo Userspace block here
    while (((status & 0x80) == 0x80) && ((status & 0x01) != 0x01))
        status = m_command_port.read();
    //Check for any errors
    if (status & 0x01)
        return;
    for (size_t i = 0; i < amount; i += 2) {
        // Read from the disk (2 bytes) and store the first byte
        uint16_t read_data = m_data_port.read();
        data_buffer->write(read_data & 0x00FF);
        // Place the second byte in the array if there is one
        if (i + 1 < amount)
            data_buffer->write((read_data >> 8) & 0x00FF);
    }
    // Read the remaining bytes as a full sector has to be read
    for (uint16_t i = amount + (amount % 2); i < m_bytes_per_sector; i += 2)
        m_data_port.read();
}
References MaxOS::hardwarecommunication::Port8Bit::read(), MaxOS::hardwarecommunication::Port16Bit::read(), and MaxOS::hardwarecommunication::Port8Bit::write().
vendor_name()
string AdvancedTechnologyAttachment::vendor_name () [final], [virtual]
Get the vendor name.
Returns
The name of the vendor
Reimplemented from MaxOS::drivers::Driver.
Definition at line 257 of file ata.cpp.
                                                 {
    return "IDE";
}
write()
void AdvancedTechnologyAttachment::write (uint32_t sector, common::buffer_t * data, size_t count) [final], [virtual]
write to a sector on the ATA device
Parameters
sector The sector to write to
data The data to write
count The amount of data to write to that sector
Reimplemented from MaxOS::drivers::disk::Disk.
Definition at line 163 of file ata.cpp.
                                                                                      {
    // Don't allow writing more than a sector
    if (sector > 0x0FFFFFFF || count > m_bytes_per_sector)
        return;
    // Select the device (master or slave)
    m_device_port.write(m_is_master ? 0xE0 : 0xF0 | ((sector & 0x0F000000) >> 24));
    // Device is busy @todo YIELD
    while ((m_command_port.read() & 0x80) != 0);
    // Reset the device
    m_error_port.write(0);
    m_sector_count_port.write(1);
    // Split the sector into the ports
    m_LBA_low_port.write(sector & 0x000000FF);
    m_LBA_mid_port.write((sector & 0x0000FF00) >> 8);
    m_LBA_high_Port.write((sector & 0x00FF0000) >> 16);
    // Send the write command
    m_command_port.write(0x30);
    // Wait for the device be ready writing @todo YIELD
    uint8_t status = m_command_port.read();
    while ((status & 0x80) != 0 || (status & 0x08) == 0)
        status = m_command_port.read();
    // Write the data to the device
    for (size_t i = 0; i < m_bytes_per_sector; i += 2) {
        uint16_t write_data = data->read();
        // Place the next byte in the array if there is one
        if (i + 1 < count)
            write_data |= (uint16_t) (data->read()) << 8;
        m_data_port.write(write_data);
    }
    // Write the remaining bytes as a full sector has to be written
    for (size_t i = count + (count % 2); i < m_bytes_per_sector; i += 2)
        m_data_port.write(0x0000);
    // Wait for the device to finish writing @todo YIELD
    status = m_command_port.read();
    while ((status & 0x80) != 0 || (status & 0x08) != 0)
        status = m_command_port.read();
    flush();
}
References flush(), MaxOS::common::Buffer::read(), MaxOS::hardwarecommunication::Port8Bit::read(), MaxOS::hardwarecommunication::Port16Bit::write(), and MaxOS::hardwarecommunication::Port8Bit::write().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/disk/ata.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/disk/ata.cpp