MaxOS::drivers::video::VideoGraphicsArray Class Reference
Driver for the VGA graphics controller, handles the rendering of pixels to the screen.
#include <vga.h>
Public Member Functions
VideoGraphicsArray ()
~VideoGraphicsArray ()
string vendor_name () final
Gets the name of the vendor.
string device_name () final
Gets the name of the device.
bool supports_mode (uint32_t width, uint32_t height, uint32_t colour_depth) final
Checks if the specified resolution is supported.
Public Member Functions inherited from MaxOS::drivers::video::VideoDriver
VideoDriver ()
~VideoDriver ()
bool set_mode (uint32_t width, uint32_t height, uint32_t colorDepth)
Set the mode of the video driver.
Public Member Functions inherited from MaxOS::drivers::Driver
Driver ()
~Driver ()
virtual void activate ()
activate the driver
virtual void deactivate ()
deactivate the driver
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
Public Member Functions inherited from MaxOS::common::GraphicsContext
GraphicsContext ()
~GraphicsContext ()
uint32_t colour_to_int (const Colour &)
Converts a colour to an integer value based on the current color depth.
Colour int_to_colour (uint32_t)
Converts an integer value to a colour based on the current color depth.
uint32_t width () const
Gets the width of the screen.
uint32_t height () const
Gets the height of the screen.
uint32_t color_depth () const
uint64_t * framebuffer_address ()
Gets the address of the context's framebuffer to draw on.
void put_pixel (int32_t x, int32_t y, const Colour &colour)
Renders a pixel to the screen (automatically converts the colour to an integer)
void putPixel (int32_t x, int32_t y, uint32_t colour)
Renders a pixel to the screen (automatically converts the colour to an integer), will not render the pixel if it is outside the screen.
Colour get_pixel (int32_t x, int32_t y)
Gets the colour of a pixel, or returns black if the pixel is outside the screen.
void invert_pixel (int32_t x, int32_t y)
Inverts a pixel.
void draw_line (int32_t x0, int32_t y0, int32_t x1, int32_t y1, const Colour &colour)
Draws a line on the screen.
void drawLine (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a line on the screen.
void draw_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, const Colour &colour)
Draws a rectangle on the screen.
void draw_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a rectangle on the screen.
void fill_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, const Colour &colour)
Draws a rectangle on the screen, filled with a colour.
void fill_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a rectangle on the screen, filled with a colour.
void draw_circle (int32_t x0, int32_t y0, int32_t radius, const Colour &colour)
Draws a circle on the screen.
void draw_circle (int32_t x0, int32_t y0, int32_t radius, uint32_t colour)
Draws a circle on the screen.
void fill_circle (int32_t x0, int32_t y0, int32_t radius, const Colour &colour)
Draws a circle on the screen, filled with a colour.
void fillCircle (int32_t x0, int32_t y0, int32_t radius, uint32_t colour)
Draws a circle on the screen, filled with a colour.
Protected Member Functions
void write_registers (uint8_t *registers)
This function is used to write to the VGA registers.
uint8_t * get_frame_buffer_segment ()
This function is used to get the framebuffer address.
bool internal_set_mode (uint32_t width, uint32_t height, uint32_t colour_depth) final
Set the resolution of the screen.
void render_pixel_8_bit (uint32_t x, uint32_t y, uint8_t colour) final
Puts a 8 bit pixel on the screen.
uint8_t get_rendered_pixel_8_bit (uint32_t x, uint32_t y) final
Gets a 8 bit pixel from the screen.
Protected Member Functions inherited from MaxOS::common::GraphicsContext
virtual void render_pixel (uint32_t x, uint32_t y, uint32_t colour)
Renders a pixel to the screen based on the current color depth.
virtual void render_pixel_16_bit (uint32_t x, uint32_t y, uint16_t colour)
Renders a pixel to the screen using the 16 bit color depth.
virtual void render_pixel_24_bit (uint32_t x, uint32_t y, uint32_t colour)
Renders a pixel to the screen using the 24 bit color depth.
virtual void render_pixel_32_bit (uint32_t x, uint32_t y, uint32_t colour)
Renders a pixel to the screen using the 32 bit color depth.
virtual uint32_t get_rendered_pixel (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen, automatically uses the correct color depth.
virtual uint16_t get_rendered_pixel_16_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 16 bit color depth.
virtual uint32_t get_rendered_pixel_24_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 24 bit color depth.
virtual uint32_t get_rendered_pixel_32_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 32 bit color depth.
Protected Attributes
hardwarecommunication::Port8Bit m_misc_port
hardwarecommunication::Port8Bit m_crtc_index_port
hardwarecommunication::Port8Bit crtc_data_port
hardwarecommunication::Port8Bit m_sequence_index_port
hardwarecommunication::Port8Bit m_sequence_data_port
hardwarecommunication::Port8Bit m_graphics_controller_index_port
hardwarecommunication::Port8Bit m_graphics_controller_data_port
hardwarecommunication::Port8Bit m_attribute_controller_index_port
hardwarecommunication::Port8Bit m_attribute_controller_read_port
hardwarecommunication::Port8Bit m_attribute_controller_write_port
hardwarecommunication::Port8Bit m_attribute_controller_reset_port
Protected Attributes inherited from MaxOS::common::GraphicsContext
bool mirror_y_axis { false }
int32_t m_width { 0 }
int32_t m_height { 0 }
uint32_t m_color_depth { 0 }
Colour m_colour_pallet [256]
uint64_t * m_framebuffer_address { nullptr }
Detailed Description
Driver for the VGA graphics controller, handles the rendering of pixels to the screen.
Definition at line 24 of file vga.h.
Constructor & Destructor Documentation
VideoGraphicsArray()
VideoGraphicsArray::VideoGraphicsArray ()
Definition at line 14 of file vga.cpp.
: m_misc_port(0x3C2),
  m_crtc_index_port(0x3D4),
  crtc_data_port(0x3D5),
  m_sequence_index_port(0x3C4),
  m_sequence_data_port(0x3C5),
  m_graphics_controller_index_port(0x3CE),
  m_graphics_controller_data_port(0x3CF),
  m_attribute_controller_index_port(0x3C0),
  m_attribute_controller_read_port(0x3C1),
  m_attribute_controller_write_port(0x3C0),
  m_attribute_controller_reset_port(0x3DA)
{
}
~VideoGraphicsArray()
VideoGraphicsArray::~VideoGraphicsArray () [default]
Member Function Documentation
device_name()
string VideoGraphicsArray::device_name () [final], [virtual]
Gets the name of the device.
Returns
The name of the device.
Reimplemented from MaxOS::drivers::Driver.
Definition at line 197 of file vga.cpp.
                                       {
    return "VGA compatible graphics card";
}
get_frame_buffer_segment()
uint8_t * VideoGraphicsArray::get_frame_buffer_segment () [protected]
This function is used to get the framebuffer address.
Returns
The framebuffer address.
Definition at line 132 of file vga.cpp.
                                                      {
    // Optimise so that don't have to read and write to the port every time
    return (uint8_t *) 0xA0000;
    //read data from index number 6
    m_graphics_controller_index_port.write(0x06);
    uint8_t segmentNumber =
            m_graphics_controller_data_port.read() &
            (3 << 2); //Shift by 2 as only interested in bits 3 & 4 (& 3 so all the other bits are removed)
    switch (segmentNumber) {
        default:
        case 0 << 2:
            return (uint8_t *) nullptr;
        case 1 << 2:
            return (uint8_t *) 0xA0000;
        case 2 << 2:
            return (uint8_t *) 0xB0000;
        case 3 << 2:
            return (uint8_t *) 0xB8000;
    }
}
References m_graphics_controller_data_port, m_graphics_controller_index_port, MaxOS::hardwarecommunication::Port8Bit::read(), and MaxOS::hardwarecommunication::Port8Bit::write().
Referenced by get_rendered_pixel_8_bit(), and render_pixel_8_bit().
get_rendered_pixel_8_bit()
uint8_t VideoGraphicsArray::get_rendered_pixel_8_bit (uint32_t x, uint32_t y) [final], [protected], [virtual]
Gets a 8 bit pixel from the screen.
Parameters
x The x coordinate of the pixel.
y The y coordinate of the pixel.
Returns
The colour of the pixel.
Reimplemented from MaxOS::common::GraphicsContext.
Definition at line 175 of file vga.cpp.
                                                                           {
    uint8_t *pixel_address = get_frame_buffer_segment() + 320 * y + x;
    return *pixel_address;
}
References get_frame_buffer_segment().
internal_set_mode()
bool VideoGraphicsArray::internal_set_mode (uint32_t width, uint32_t height, uint32_t colour_depth) [final], [protected], [virtual]
Set the resolution of the screen.
Parameters
width The width of the resolution.
height The height of the resolution.
colour_depth The colour depth of the resolution.
Returns
True if the card was able to set the resolution, otherwise false.
Reimplemented from MaxOS::drivers::video::VideoDriver.
Definition at line 100 of file vga.cpp.
                                                                                                 {
    //Values from osdev / modes.c
    unsigned char g_320x200x256[] =
            {
                    // MISC
                    0x63,
                    // SEQ
                    0x03, 0x01, 0x0F, 0x00, 0x0E,
                    // CRTC
                    0x5F, 0x4F, 0x50, 0x82, 0x54, 0x80, 0xBF, 0x1F,
                    0x00, 0x41, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
                    0x9C, 0x0E, 0x8F, 0x28, 0x40, 0x96, 0xB9, 0xA3,
                    0xFF,
                    // GC
                    0x00, 0x00, 0x00, 0x00, 0x00, 0x40, 0x05, 0x0F,
                    0xFF,
                    // AC
                    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07,
                    0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F,
                    0x41, 0x00, 0x0F, 0x00, 0x00
            };
    write_registers(g_320x200x256);
    return true;
}
References write_registers().
render_pixel_8_bit()
void VideoGraphicsArray::render_pixel_8_bit (uint32_t x, uint32_t y, uint8_t colour) [final], [protected], [virtual]
Puts a 8 bit pixel on the screen.
Parameters
x The x coordinate of the pixel.
y The y coordinate of the pixel.
colour The colour of the pixel.
Reimplemented from MaxOS::common::GraphicsContext.
Definition at line 162 of file vga.cpp.
                                                                                  {
    uint8_t *pixel_address = get_frame_buffer_segment() + 320 * y + x;
    *pixel_address = colour;
}
References get_frame_buffer_segment().
supports_mode()
bool VideoGraphicsArray::supports_mode (uint32_t width, uint32_t height, uint32_t colour_depth) [final], [virtual]
Checks if the specified resolution is supported.
Returns
True if the specified resolution is supported, otherwise false.
Reimplemented from MaxOS::drivers::video::VideoDriver.
Definition at line 87 of file vga.cpp.
                                                                                             {
    return width == 320 && height == 200 && colour_depth == 8;
}
References MaxOS::common::GraphicsContext::height(), and MaxOS::common::GraphicsContext::width().
vendor_name()
string VideoGraphicsArray::vendor_name () [final], [virtual]
Gets the name of the vendor.
Returns
The name of the vendor.
Reimplemented from MaxOS::drivers::Driver.
Definition at line 186 of file vga.cpp.
                                       {
    // VGA was made by IBM
    return "IBM";
}
write_registers()
void VideoGraphicsArray::write_registers (uint8_t * registers) [protected]
This function is used to write to the VGA registers.
Parameters
registers The VGA registers to write to.
Definition at line 36 of file vga.cpp.
                                                           {
    // Move to the next register
    m_misc_port.write(*(registers++));
    // Set the sequencer registers
    for (uint8_t i = 0; i < 5; i++) {
        m_sequence_index_port.write(i);
        m_sequence_data_port.write(*(registers++));
    }
    // Clear protection bit to enable writing to CR0-7
    m_crtc_index_port.write(0x03);
    crtc_data_port.write(crtc_data_port.read() | 0x80);
    m_crtc_index_port.write(0x11);
    crtc_data_port.write(crtc_data_port.read() | ~0x80);
    // Ensure protection bit is set
    registers[0x03] = registers[0x03] | 0x80;
    registers[0x11] = registers[0x11] & ~0x80;
    // Write the CRTC registers
    for (uint8_t i = 0; i < 25; i++) {
        m_crtc_index_port.write(i);
        crtc_data_port.write(*(registers++));
    }
    // Write the graphics controller registers
    for (uint8_t i = 0; i < 9; i++) {
        m_graphics_controller_index_port.write(i);
        m_graphics_controller_data_port.write(*(registers++));
    }
    // Write the attribute controller registers
    for (uint8_t i = 0; i < 21; i++) {
        m_attribute_controller_reset_port.read();
        m_attribute_controller_index_port.write(i);
        m_attribute_controller_write_port.write(*(registers++));
    }
    // Re-Lock CRTC and unblank display
    m_attribute_controller_reset_port.read();
    m_attribute_controller_index_port.write(0x20);
}
References crtc_data_port, m_attribute_controller_index_port, m_attribute_controller_reset_port, m_attribute_controller_write_port, m_crtc_index_port, m_graphics_controller_data_port, m_graphics_controller_index_port, m_misc_port, m_sequence_data_port, m_sequence_index_port, MaxOS::hardwarecommunication::Port8Bit::read(), and MaxOS::hardwarecommunication::Port8Bit::write().
Referenced by internal_set_mode().
Member Data Documentation
crtc_data_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::crtc_data_port [protected]
Definition at line 28 of file vga.h.
Referenced by write_registers().
m_attribute_controller_index_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_attribute_controller_index_port [protected]
Definition at line 33 of file vga.h.
Referenced by write_registers().
m_attribute_controller_read_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_attribute_controller_read_port [protected]
Definition at line 34 of file vga.h.
m_attribute_controller_reset_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_attribute_controller_reset_port [protected]
Definition at line 36 of file vga.h.
Referenced by write_registers().
m_attribute_controller_write_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_attribute_controller_write_port [protected]
Definition at line 35 of file vga.h.
Referenced by write_registers().
m_crtc_index_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_crtc_index_port [protected]
Definition at line 27 of file vga.h.
Referenced by write_registers().
m_graphics_controller_data_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_graphics_controller_data_port [protected]
Definition at line 32 of file vga.h.
Referenced by get_frame_buffer_segment(), and write_registers().
m_graphics_controller_index_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_graphics_controller_index_port [protected]
Definition at line 31 of file vga.h.
Referenced by get_frame_buffer_segment(), and write_registers().
m_misc_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_misc_port [protected]
Definition at line 26 of file vga.h.
Referenced by write_registers().
m_sequence_data_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_sequence_data_port [protected]
Definition at line 30 of file vga.h.
Referenced by write_registers().
m_sequence_index_port
hardwarecommunication::Port8Bit MaxOS::drivers::video::VideoGraphicsArray::m_sequence_index_port [protected]
Definition at line 29 of file vga.h.
Referenced by write_registers().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/video/vga.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/video/vga.cpp