MaxOS::common::InputStreamProcessor< Type, ProcessorType > Class Template Reference
Converts one stream data type into another.
#include <inputStream.h>
Public Member Functions
InputStreamProcessor ()
Creates a new InputStreamProcessor.
InputStreamProcessor (InputStreamEventHandler< ProcessorType > *generic_stream_event_handler)
Creates a new InputStreamProcessor.
~InputStreamProcessor ()
Destroys the InputStreamProcessor.
void on_end_of_stream (GenericInputStream< Type > *stream) override
Called when a stream has finished. Passes the event on to the handlers and then removes the stream from the array of streams.
Public Member Functions inherited from MaxOS::common::InputStreamEventHandler< Type >
InputStreamEventHandler ()
_______________________________________________TEMPLATES_________________________________________________________________///
~InputStreamEventHandler ()
Destroys the InputStreamProcessor and disconnects it from all streams.
virtual void on_stream_read (Type)
Called when data is read from a stream (overridden by subclasses)
Public Member Functions inherited from MaxOS::common::GenericInputStream< ProcessorType >
GenericInputStream ()
Creates a new GenericInputStream.
GenericInputStream (InputStreamEventHandler< ProcessorType > *)
Creates a new GenericInputStream and connects it to the handler.
~GenericInputStream ()
Destroys the GenericInputStream and disconnects all handlers.
void connect_input_stream_event_handler (InputStreamEventHandler< ProcessorType > *)
Adds a inputStreamEventHandler to the list of internetProtocolHandlers.
void disconnect_input_stream_event_handler (InputStreamEventHandler< ProcessorType > *)
Removes a handler from the list of handlers.
Additional Inherited Members
Protected Attributes inherited from MaxOS::common::InputStreamEventHandler< Type >
common::Vector< GenericInputStream< Type > * > m_generic_input_streams
List of streams being observed by this handler.
Protected Attributes inherited from MaxOS::common::GenericInputStream< ProcessorType >
common::Vector< InputStreamEventHandler< ProcessorType > * > m_input_stream_event_handlers
List of streams being observed by this handler.
Detailed Description
template<class Type, class ProcessorType>
class MaxOS::common::InputStreamProcessor< Type, ProcessorType >
Converts one stream data type into another.
Template Parameters
Type
ProcessorType
Definition at line 52 of file inputStream.h.
Constructor & Destructor Documentation
InputStreamProcessor() [1/2]
template<class Type , class ProcessorType >
MaxOS::common::InputStreamProcessor< Type, ProcessorType >::InputStreamProcessor ()
Creates a new InputStreamProcessor.
Template Parameters
Type The type of data the stream is handling
ProcessorType The type of data to convert the data into via the processor
Definition at line 204 of file inputStream.h.
        : InputStreamEventHandler<Type>(),
          GenericInputStream<ProcessorType>()
        {
        }
InputStreamProcessor() [2/2]
template<class Type , class ProcessorType >
MaxOS::common::InputStreamProcessor< Type, ProcessorType >::InputStreamProcessor (InputStreamEventHandler< ProcessorType > * generic_stream_event_handler)
Creates a new InputStreamProcessor.
Template Parameters
Type The type of data the stream is handling
ProcessorType The type of data to convert the data into via the processor
Parameters
generic_stream_event_handler The event handler to handle the data
Definition at line 218 of file inputStream.h.
        : InputStreamEventHandler<Type>(),
          GenericInputStream<ProcessorType>(generic_stream_event_handler)
        {
        }
~InputStreamProcessor()
template<class Type , class ProcessorType >
MaxOS::common::InputStreamProcessor< Type, ProcessorType >::~InputStreamProcessor () [default]
Destroys the InputStreamProcessor.
Template Parameters
Type The type of data the stream is handling
ProcessorType The type of data to convert the data into via the processor
Member Function Documentation
on_end_of_stream()
template<class Type , class ProcessorType >
void MaxOS::common::InputStreamProcessor< Type, ProcessorType >::on_end_of_stream (GenericInputStream< Type > * stream) [override], [virtual]
Called when a stream has finished. Passes the event on to the handlers and then removes the stream from the array of streams.
Template Parameters
Type The type of data the stream is handling
ProcessorType The type of data to convert the data into via the processor
Parameters
stream The stream that has finished
Reimplemented from MaxOS::common::InputStreamEventHandler< Type >.
Definition at line 240 of file inputStream.h.
                                                                                                                                                   {
            // Pass the end of stream event on to the handlers
            for(auto& event_handler : this -> m_input_stream_event_handlers)
              event_handler -> on_end_of_stream(this);
            // Remove the stream
            InputStreamEventHandler<Type>::on_end_of_stream(stream);
        }
References MaxOS::common::InputStreamEventHandler< Type >::on_end_of_stream().
Referenced by MaxOS::common::InputStreamBuffer< Type >::on_end_of_stream(), and MaxOS::common::GenericOutputStream< Type >::on_end_of_stream().
The documentation for this class was generated from the following file:
/home/runner/work/MaxOS/MaxOS/kernel/include/common/inputStream.h