MaxOS::system::UBSanHandler Class Reference
Handles undefined behaviour sanitizer.
#include <ubsan.h>
Public Member Functions
UBSanHandler ()
~UBSanHandler ()
Static Public Member Functions
static void handle (source_location_t location)
static void print_type_mismatch (type_mismatch_info_t *info, uintptr_t ptr)
Prints the type mismatch error for UBSan.
static void print_type_mismatch_v1 (type_mismatch_info_v1_t *info, uintptr_t ptr)
Prints the type mismatch error for UBSan v1.
Detailed Description
Handles undefined behaviour sanitizer.
Definition at line 84 of file ubsan.h.
Constructor & Destructor Documentation
UBSanHandler()
UBSanHandler::UBSanHandler ()
Definition at line 12 of file ubsan.cpp.
                           {
}
 UBSanHandler()
UBSanHandler::~UBSanHandler ()
Definition at line 16 of file ubsan.cpp.
                            {
}
Member Function Documentation
handle()
void UBSanHandler::handle (source_location_t location) [static]
Definition at line 20 of file ubsan.cpp.
                                                    {
  // Print the location
  ASSERT(false, "UBSAN ERROR AT %s:%d:%d\n", location.file, location.line, location.column);
}
References ASSERT, MaxOS::system::source_location::column, MaxOS::system::source_location::file, and MaxOS::system::source_location::line.
Referenced by __ubsan_handle_add_overflow(), __ubsan_handle_builtin_unreachable(), __ubsan_handle_divrem_overflow(), __ubsan_handle_load_invalid_value(), __ubsan_handle_missing_return(), __ubsan_handle_mul_overflow(), __ubsan_handle_negate_overflow(), __ubsan_handle_out_of_bounds(), __ubsan_handle_pointer_overflow(), __ubsan_handle_shift_out_of_bounds(), __ubsan_handle_sub_overflow(), __ubsan_handle_type_mismatch(), __ubsan_handle_type_mismatch_v1(), print_type_mismatch(), and print_type_mismatch_v1().
print_type_mismatch()
void UBSanHandler::print_type_mismatch (type_mismatch_info_t * info, uintptr_t ptr) [static]
Prints the type mismatch error for UBSan.
Parameters
info The type mismatch info
ptr The pointer to the object
Definition at line 33 of file ubsan.cpp.
                                                                                {
  // Print the error
  _kprintf("UBSan: ");
  if(info -> alignment != 0 && ubsan_aligned(ptr, info -> alignment))
    _kprintf("%h misaligned memory access\n");
  else
    _kprintf("%h %s address 0x%x with insufficient space for an object of type %s\n", Type_Check_Kinds[info -> type_check_kind], ptr, info -> type -> name);
  // Print the location
  handle(info -> location);
}
References _kprintf, handle(), name, type, MaxOS::system::Type_Check_Kinds, and ubsan_aligned.
Referenced by __ubsan_handle_type_mismatch().
print_type_mismatch_v1()
void UBSanHandler::print_type_mismatch_v1 (type_mismatch_info_v1_t * info, uintptr_t ptr) [static]
Prints the type mismatch error for UBSan v1.
Parameters
info The type mismatch info
ptr The pointer to the object
Definition at line 51 of file ubsan.cpp.
                                                                                      {
  // Print the error
  _kprintf("UBSan: ");
  if(info -> log_alignment != 0 && ubsan_aligned(ptr, (1 << (info -> log_alignment))))
    _kprintf("%h misaligned memory access\n");
  else
    _kprintf("%h %s address 0x%x with insufficient space for an object of type %s\n", Type_Check_Kinds[info -> type_check_kind], ptr, info -> type -> name);
  // Print the location
  handle(info -> location);
}
References _kprintf, handle(), name, type, MaxOS::system::Type_Check_Kinds, and ubsan_aligned.
Referenced by __ubsan_handle_type_mismatch_v1().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/system/ubsan.h
/home/runner/work/MaxOS/MaxOS/kernel/src/system/ubsan.cpp