MaxOS::String Class Reference
Dynamically sized string with various operations.
#include <string.h>
Public Member Functions
String ()
Construct a String, 0 length and only contains the null terminator.
String (char c)
Constructs a String from a single character.
String (char const *string)
Constructs a String from a pointer to an array of chars.
String (uint8_t const *string, int length)
Constructs a string from a an array of bytes (doesnt have to be null terminated)
String (String const &other)
Copy constructor for the string.
String (int value)
Constructs a string from an integer (must be base 10)
String (uint64_t value)
Constructs a string from a hex value (Excludes 0x)
String (float value)
Constructs a String from a float.
String (bool value)
Constructs a String from a boolean as "true" or "false".
void copy (String const &other)
Copies the other string.
int length (bool count_ansi=true) const
Returns the length of the string.
char * c_str ()
The char pointer representation of the current string.
const char * c_str () const
Returns the string as a c string.
bool starts_with (String const &other)
Checks if the string starts with the other string (must contain the same characters in the same order)
String substring (int start, int length) const
Get a section of the string.
common::Vector< String > split (String const &delimiter) const
Splits the string by the delimiter.
String strip (char strip_char=' ') const
Strips the string of whitespace.
String center (int width, char fill=' ') const
Centers the string in a specified width.
bool equals (String const &other) const
Checks if one string is equal to another.
String & operator= (String const &other)
Sets the string to the other string.
String operator+ (String const &other) const
Adds the other string to the string.
String & operator+= (String const &other)
Adds the other string to the string.
String operator* (int times) const
Returns the string repeated a number of times.
bool operator== (String const &other) const
Checks if one string is equal to another.
bool operator!= (String const &other) const
Checks if one string is not equal to another.
bool operator< (String const &other) const
Checks if the sum of the ascii values of the characters in the string is less than the sum of the ascii values of the characters in the other string.
bool operator> (String const &other) const
Checks if the sum of the ascii values of the characters in the string is greater than the sum of the ascii values of the characters in the other string.
bool operator<= (String const &other) const
Checks if the sum of the ascii values of the characters in the string is less than or equal to the sum of the ascii values of the characters in the other string.
bool operator>= (String const &other) const
Checks if the sum of the ascii values of the characters in the string is greater than or equal to the sum of the ascii values of the characters in the other string.
char & operator[] (int index)
Returns the character at the specified index.
char & operator[] (int index) const
Returns the character at the specified index.
Static Public Member Functions
static String formatted (char const *format,...)
Creates a formated string. s = string, x = hex, d = decimal.
static String formatted (char const *format, va_list parameters)
Creates a formated string. s = string, x = hex, d = decimal.
Detailed Description
Dynamically sized string with various operations.
Definition at line 26 of file string.h.
Constructor & Destructor Documentation
String() [1/9]
String::String ()
Construct a String, 0 length and only contains the null terminator.
Definition at line 16 of file string.cpp.
               {
    // String that only contains the null terminator
    allocate_self();
    m_string[0] = '\0';
    m_length = 0;
}
String() [2/9]
String::String (char c) [explicit]
Constructs a String from a single character.
Parameters
c The character
Definition at line 29 of file string.cpp.
                     {
    // Create the memory
    m_length = 1;
    allocate_self();
    // Store the char
    m_string[0] = c;
    m_string[m_length] = '\0';
}
String() [3/9]
String::String (char const * string)
Constructs a String from a pointer to an array of chars.
Parameters
string An array of chars, must be null terminated and of length less than 10,000
Definition at line 46 of file string.cpp.
                                 {
    // Get the length of the string, prevent longer than 10000 because this should mean something's gone wrong
    m_length = 0;
    while (string[m_length] != '\0' && m_length <= 10000)
        m_length++;
    allocate_self();
    // Copy the string
    for (int i = 0; i < m_length; i++)
        m_string[i] = string[i];
    // If the length is more than 10,000 Replace the end with a warning incase future use actually requires that
    const char *warning = "MAXOS: String length exceeded 10000 - might be a bug";
    if (m_length > 10000)
        for (int i = 0; i < 52; i++)
            m_string[m_length - 52 + i] = warning[i];
    m_string[m_length] = '\0';
}
String() [4/9]
String::String (uint8_t const * string, int length)
Constructs a string from a an array of bytes (doesnt have to be null terminated)
Parameters
string The string bytes
length How large the string byte buffer is
Definition at line 73 of file string.cpp.
                                                {
    // Allocate memory for the string (and null terminator)
    m_length = length;
    allocate_self();
    // Copy the string
    for (int i = 0; i < length; i++)
        m_string[i] = string[i];
    // Write the null terminator
    m_string[length] = '\0';
}
References length.
String() [5/9]
String::String (String const & other)
Copy constructor for the string.
Parameters
other String to copy from
Definition at line 165 of file string.cpp.
                                  {
    copy(other);
}
References copy().
String() [6/9]
String::String (int value) [explicit]
Constructs a string from an integer (must be base 10)
Parameters
value The integer value
Definition at line 91 of file string.cpp.
                        {
    // Convert to a string
    const char *str = itoa(10, value);
    m_length = strlen(str);
    // Create space to store
    allocate_self();
    // Store the string
    for (int i = 0; i < m_length; i++)
        m_string[i] = str[i];
    m_string[m_length] = '\0';
}
References itoa(), and strlen().
String() [7/9]
String::String (uint64_t value) [explicit]
Constructs a string from a hex value (Excludes 0x)
Parameters
value The hex value
Definition at line 112 of file string.cpp.
                             {
    // Convert to a string
    const char *str = htoa(value);
    m_length = strlen(str);
    // Create space to store
    allocate_self();
    // Store the string
    for (int i = 0; i < m_length; i++)
        m_string[i] = str[i];
    m_string[m_length] = '\0';
}
References htoa(), and strlen().
String() [8/9]
String::String (float value) [explicit]
Constructs a String from a float.
Parameters
value The float value
Definition at line 131 of file string.cpp.
                          {
    // Convert to a string
    const char *str = ftoa(value);
    m_length = strlen(str);
    // Create space to store
    allocate_self();
    // Store the string
    for (int i = 0; i < m_length; i++)
        m_string[i] = str[i];
    m_string[m_length] = '\0';
}
References ftoa(), and strlen().
String() [9/9]
String::String (bool value) [explicit]
Constructs a String from a boolean as "true" or "false".
Parameters
value The bool value
Definition at line 151 of file string.cpp.
                         {
    if(value)
        *this = string("true");
    else
        *this = string("false");
}
~String()
String::~String ()
Definition at line 170 of file string.cpp.
                {
    // Free the memory
    if (!m_using_small)
        delete[] m_string;
}
Member Function Documentation
c_str() [1/2]
char * String::c_str ()
The char pointer representation of the current string.
Returns
The char* string
Definition at line 251 of file string.cpp.
                    {
    return m_string;
}
Referenced by strcmp(), strcmp(), strcmp(), strncmp(), strncmp(), and strncmp().
c_str() [2/2]
const char * String::c_str () const
Returns the string as a c string.
Returns
The string as an array of characters
Definition at line 261 of file string.cpp.
                                {
    return m_string;
}
center()
String String::center (int width, char fill = ' ') const
Centers the string in a specified width.
Parameters
width The width of the string
fill The character to fill the string with
Returns
The centered string
Definition at line 580 of file string.cpp.
                                                {
    // The number of characters to add
    int add = (width - m_length) / 2;
    // The centered string
    String centered;
    centered.m_length = width;
    centered.allocate_self();
    // Fill the right side (before)
    for (int i = 0; i < add; i++)
        centered.m_string[i] = fill;
    // Copy the string (middle)
    for (int i = 0; i < m_length; i++)
        centered.m_string[add + i] = m_string[i];
    // Fill the left side (after)
    for (int i = add + m_length; i < width; i++)
        centered.m_string[i] = fill;
    // Write the null terminator
    centered.m_string[width] = '\0';
    return centered;
}
copy()
void String::copy (String const & other)
Copies the other string.
Parameters
other The other string
Definition at line 183 of file string.cpp.
                                     {
    // Allocate memory for the string (and null terminator)
    m_length = other.length();
    allocate_self();
    // Copy the string
    for (int i = 0; i < m_length; i++)
        m_string[i] = other[i];
    // Write the null terminator
    m_string[m_length] = '\0';
}
References length().
Referenced by operator+=(), operator=(), String(), and strip().
equals()
bool String::equals (String const & other) const
Checks if one string is equal to another.
Parameters
other The other string
Returns
True if the strings are equal, false otherwise
Definition at line 392 of file string.cpp.
                                             {
    // Check if the lengths are equal
    if (m_length != other.length())
        return false;
    // Check if the characters are equal
    for (int i = 0; i < m_length; i++)
        if (m_string[i] != other[i])
            return false;
    // The strings are equal
    return true;
}
References length().
Referenced by operator!=(), and operator==().
formatted() [1/2]
String String::formatted (char const * format, va_list parameters) [static]
Creates a formated string. s = string, x = hex, d = decimal.
Parameters
format The string containing the format
parameters The arguments to format into the string
Returns
The string with the arguments formated inside
Definition at line 659 of file string.cpp.
                                                               {
    String out;
    // Loop through the format string
    for (; *format != '\0'; format++) {
        // If it is not a %, print the character
        if (*format != '%') {
            out += (string)(char)(*format);
            continue;
        }
        // Move to the next character
        format++;
        switch (*format) {
            case 'd': {
                // Print a decimal
                int number = va_arg (parameters, int);
                out += (string)(number);
                break;
            }
            case 'x': {
                // Print a hex
                uint64_t number = va_arg (parameters, uint64_t);
                out += (string)(number);
                break;
            }
            case 's': {
                // Print a string
                char *str = va_arg (parameters, char*);
                out += (string)(str);
                break;
            }
        }
    }
    return out;
}
formatted() [2/2]
String String::formatted (char const * format, ...) [static]
Creates a formated string. s = string, x = hex, d = decimal.
Parameters
format The string containing the format
... The arguments to format into the string
Returns
The string with the arguments formated inside
Definition at line 641 of file string.cpp.
                                                {
    // Create a pointer to the data
    va_list parameters;
    va_start(parameters, format);
    return formatted(format, parameters);
}
References formatted().
Referenced by Logger::ASSERT(), formatted(), and Logger::printf().
length()
int String::length (bool count_ansi = true) const
Returns the length of the string.
Parameters
count_ansi Whether to count the ansi characters (default true)
Returns
The length of the string
Definition at line 361 of file string.cpp.
                                        {
    // If ansi characters are not to be counted
    if (count_ansi)
        return m_length;
    // Calculate the length of the string without ansi characters
    int total_length = 0;
    int clean_length = 0;
    while (m_string[total_length] != '\0') {
        // If the character is an ansi character, skip it
        if (m_string[total_length] == '\033')
            while (m_string[total_length] != 'm')
                total_length++;
        // Increment the length
        clean_length++;
        total_length++;
    }
    // Return the length
    return clean_length;
}
Referenced by copy(), equals(), operator+(), split(), and starts_with().
operator!=()
bool String::operator!= (String const & other) const
Checks if one string is not equal to another.
Parameters
other The other string
Returns
True if the strings are not equal, false otherwise
Definition at line 426 of file string.cpp.
                                                   {
    // Self assignment check
    if (*this == other)
        return false;
    return !equals(other);
}
References equals().
operator*()
String String::operator* (int times) const
Returns the string repeated a number of times.
Parameters
times The number of times to repeat the string
Returns
The string repeated a number of times
Definition at line 553 of file string.cpp.
                                        {
    // The repeated string
    String repeated;
    repeated.m_length = m_length * times;
    repeated.allocate_self();
    // Copy the string
    for (int i = 0; i < times; i++)
        for (int j = 0; j < m_length; j++)
            repeated.m_string[i * m_length + j] = m_string[j];
    // Write the null terminator
    repeated.m_string[repeated.m_length] = '\0';
    // Return the repeated string
    return repeated;
}
operator+()
String String::operator+ (String const & other) const
Adds the other string to the string.
Parameters
other The other string
Returns
The concatenated string
Definition at line 489 of file string.cpp.
                                                    {
    // The concatenated string
    String concatenated;
    concatenated.m_length = m_length + other.length();
    concatenated.allocate_self();
    // Copy the first string
    for (int i = 0; i < m_length; i++)
        concatenated.m_string[i] = m_string[i];
    // Copy the second string
    for (int i = 0; i < other.length(); i++)
        concatenated.m_string[m_length + i] = other[i];
    // Write the null terminator
    concatenated.m_string[concatenated.m_length] = '\0';
    // Return the concatenated string
    return concatenated;
}
References length().
operator+=()
String & String::operator+= (String const & other)
Adds the other string to the string.
Parameters
other The other string
Returns
The concatenated string
Definition at line 517 of file string.cpp.
                                              {
    // Add the other string to this string
    String concatenated = *this + other;
    copy(concatenated);
    return *this;
}
References copy().
operator<()
bool String::operator< (String const & other) const
Checks if the sum of the ascii values of the characters in the string is less than the sum of the ascii values of the characters in the other string.
Parameters
other The other string
Returns
True if the string is less than the other, false otherwise
Definition at line 441 of file string.cpp.
                                                  {
    return lex_value(*this) < lex_value(other);
}
operator<=()
bool String::operator<= (String const & other) const
Checks if the sum of the ascii values of the characters in the string is less than or equal to the sum of the ascii values of the characters in the other string.
Parameters
other The other string
Returns
True if the string is less than or equal to the other, false otherwise
Definition at line 465 of file string.cpp.
                                                   {
    return lex_value(*this) <= lex_value(other);
}
operator=()
String & String::operator= (String const & other)
Sets the string to the other string.
Parameters
other The string for this one to be updated to
Returns
String The string
Definition at line 235 of file string.cpp.
                                             {
    // Self assignment check
    if (this == &other)
        return *this;
    // Copy the other string
    copy(other);
    return *this;
}
References copy().
operator==()
bool String::operator== (String const & other) const
Checks if one string is equal to another.
Parameters
other The other string
Returns
True if the strings are equal, false otherwise
Definition at line 414 of file string.cpp.
                                                   {
    // Check if the strings are equal
    return equals(other);
}
References equals().
operator>()
bool String::operator> (String const & other) const
Checks if the sum of the ascii values of the characters in the string is greater than the sum of the ascii values of the characters in the other string.
Parameters
other The other string
Returns
True if the string is greater than the other, false otherwise
Definition at line 453 of file string.cpp.
                                                  {
    return lex_value(*this) > lex_value(other);
}
operator>=()
bool String::operator>= (String const & other) const
Checks if the sum of the ascii values of the characters in the string is greater than or equal to the sum of the ascii values of the characters in the other string.
Parameters
other The other string
Returns
True if the string is greater than or equal to the other, false otherwise
Definition at line 477 of file string.cpp.
                                                   {
    return lex_value(*this) >= lex_value(other);
}
operator[]() [1/2]
char & String::operator[] (int index)
Returns the character at the specified index.
Parameters
index The index of the character
Returns
The character at the specified index
Definition at line 532 of file string.cpp.
                                  {
    return m_string[index];
}
operator[]() [2/2]
char & String::operator[] (int index) const
Returns the character at the specified index.
Parameters
index The index of the character
Returns
The character at the specified index
Definition at line 543 of file string.cpp.
                                        {
    return m_string[index];
}
split()
common::Vector< String > String::split (String const & delimiter) const
Splits the string by the delimiter.
Parameters
delimiter What to split the string by
Returns
A vector of strings that were split by the delimiter
Definition at line 325 of file string.cpp.
                                                                {
    common::Vector<String> strings;
    // Go through the string and split it by the delimiter
    int start = 0;
    for (int i = 0; i <= m_length - delimiter.length(); i++) {
        // Check if matches at this position
        bool matches = true;
        for (int j = 0; j < delimiter.length(); j++)
            if (m_string[i + j] != delimiter[j]) {
                matches = false;
                break;
            }
        if(!matches)
            continue;
        // Add the splice of the string
        strings.push_back(substring(start, i - start));
        start = i + delimiter.length();
        i += delimiter.length() - 1;
    }
    // Add the last string to the vector
    strings.push_back(substring(start, m_length - start));
    return strings;
}
References length(), and substring().
starts_with()
bool String::starts_with (String const & other)
Checks if the string starts with the other string (must contain the same characters in the same order)
Parameters
other The other string
Returns
True if the string starts with the other string, false otherwise
Definition at line 272 of file string.cpp.
                                            {
    // Must at least be able to fit the other string
    if (m_length < other.length())
        return false;
    // Check if the string starts with the other string
    for (int i = 0; i < other.length(); i++)
        if (m_string[i] != other[i])
            return false;
    // No string left over to check so it must contain other
    return true;
}
References length().
strip()
String String::strip (char strip_char = ' ') const
Strips the string of whitespace.
Parameters
strip_char The character to strip (default = ' ')
Returns
The stripped string (new string)
Definition at line 614 of file string.cpp.
                                          {
    // The stripped string
    String stripped;
    stripped.copy(*this);
    // Search from the back for the earliest non-whitespace character
    int end = m_length - 1;
    while (end >= 0 && (m_string[end] == strip_char || m_string[end] == '\n' || m_string[end] == '\t'))
        end--;
    // Make sure there is something to strip
    if (end < 0)
        return stripped;
    // Split the string to remove the end
    return stripped.substring(0, end + 1);
}
References copy(), and substring().
substring()
String String::substring (int start, int length) const
Get a section of the string.
Parameters
start The start of the substring
length The length of the substring
Returns
The substring or empty string if out of bounds
Definition at line 294 of file string.cpp.
                                                    {
    // Ensure the start is within bounds
    if (start < 0 || start >= m_length)
        return {};
    // Ensure the length is within bounds
    if (length < 0 || start + length > m_length)
        return {};
    // Allocate memory for the substring (and null terminator)
    String substring;
    substring.m_length = length;
    substring.allocate_self();
    // Copy the substring
    for (int i = 0; i < length; i++)
        substring.m_string[i] = m_string[start + i];
    // Write the null terminator
    substring.m_string[length] = '\0';
    return substring;
}
References length, and substring().
Referenced by split(), strip(), and substring().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/common/string.h
/home/runner/work/MaxOS/MaxOS/kernel/src/common/string.cpp