MaxOS::hardwarecommunication::InterruptManager Class Reference
Handles all interrupts and passes them to the correct handler.
#include <interrupts.h>
Public Member Functions
InterruptManager (uint16_t hardware_interrupt_offset, system::GlobalDescriptorTable *global_descriptor_table, system::ThreadManager *thread_manager, common::OutputStream *handler)
Manger
~InterruptManager ()
uint16_t hardware_interrupt_offset ()
Returns the offset of the hardware interrupt.
void set_interrupt_handler (uint8_t interrupt, InterruptHandler *handler)
Sets the interrupt handler for the interrupt.
void remove_interrupt_handler (uint8_t interrupt)
Removes the interrupt handler for the interrupt.
void activate ()
Activates the interrupt manager and starts interrupts (also deactivates the current interrupt manager)
void deactivate ()
Deactivates the interrupt manager and stops interrupts.
Protected Member Functions
uint32_t handle_interrupt_request (uint8_t interrupt, uint32_t esp)
Handles the interrupt request and runs the interrupt handler if there is one.
Static Protected Member Functions
static void set_interrupt_descriptor_table_entry (uint8_t interrupt, uint16_t code_segment_selector_offset, void(*handler)(), uint8_t DescriptorPrivilegeLevel, uint8_t descriptor_type)
Sets an entry in the Interrupt Descriptor Table.
static void InterruptIgnore ()
static void HandleInterruptRequest0x00 ()
static void HandleInterruptRequest0x01 ()
static void HandleInterruptRequest0x02 ()
static void HandleInterruptRequest0x03 ()
static void HandleInterruptRequest0x04 ()
static void HandleInterruptRequest0x05 ()
static void HandleInterruptRequest0x06 ()
static void HandleInterruptRequest0x07 ()
static void HandleInterruptRequest0x08 ()
static void HandleInterruptRequest0x09 ()
static void HandleInterruptRequest0x0A ()
static void HandleInterruptRequest0x0B ()
static void HandleInterruptRequest0x0C ()
static void HandleInterruptRequest0x0D ()
static void HandleInterruptRequest0x0E ()
static void HandleInterruptRequest0x80 ()
static void HandleInterruptRequest0x0F ()
static void HandleInterruptRequest0x31 ()
static void HandleException0x00 ()
static void HandleException0x01 ()
static void HandleException0x02 ()
static void HandleException0x03 ()
static void HandleException0x04 ()
static void HandleException0x05 ()
static void HandleException0x06 ()
static void HandleException0x07 ()
static void HandleException0x08 ()
static void HandleException0x09 ()
static void HandleException0x0A ()
static void HandleException0x0B ()
static void HandleException0x0C ()
static void HandleException0x0D ()
static void HandleException0x0E ()
static void HandleException0x0F ()
static void HandleException0x10 ()
static void HandleException0x11 ()
static void HandleException0x12 ()
static void HandleException0x13 ()
static void HandleException0x14 ()
static void HandleException0x15 ()
static void HandleException0x16 ()
static void HandleException0x17 ()
static void HandleException0x18 ()
static void HandleException0x19 ()
static void HandleException0x1A ()
static void HandleException0x1B ()
static void HandleException0x1C ()
static void HandleException0x1D ()
static void HandleException0x1E ()
static void HandleException0x1F ()
static uint32_t HandleInterrupt (uint8_t interrupt, uint32_t esp)
Handles the interrupt request by passing it to the interrupt manager.
static uint32_t HandleInterruptRequest (uint32_t esp)
Protected Attributes
uint16_t m_hardware_interrupt_offset
InterruptHandler * m_interrupt_handlers [256]
system::ThreadManager * m_thread_manager
Port8BitSlow pic_master_command_port
Port8BitSlow pic_master_data_port
Port8BitSlow pic_slave_command_port
Port8BitSlow pic_slave_data_port
Static Protected Attributes
static InterruptManager * s_active_interrupt_manager = 0
static common::OutputStream * s_error_messages = 0
static GateDescriptor s_interrupt_descriptor_table [256]
Friends
class InterruptHandler
Detailed Description
Handles all interrupts and passes them to the correct handler.
Definition at line 63 of file interrupts.h.
Constructor & Destructor Documentation
InterruptManager()
InterruptManager::InterruptManager (uint16_t hardware_interrupt_offset, system::GlobalDescriptorTable * global_descriptor_table, system::ThreadManager * thread_manager, common::OutputStream * handler)
Manger
Definition at line 46 of file interrupts.cpp.
: common::InputStream(handler),
  m_hardware_interrupt_offset(hardware_interrupt_offset),
  m_thread_manager(thread_manager),
  pic_master_command_port(0x20),
  pic_master_data_port(0x21),
  pic_slave_command_port(0xA0),
  pic_slave_data_port(0xA1)
{
    uint32_t code_segment = global_descriptor_table->code_segment_selector();
    // By default ignore all interrupts so any un handled interrupts wont cause a fault
    const uint8_t IDT_INTERRUPT_GATE = 0xE;
    for(uint8_t i = 255; i > 0; --i)
    {
      set_interrupt_descriptor_table_entry(i, code_segment, &InterruptIgnore, 0, IDT_INTERRUPT_GATE);
      m_interrupt_handlers[i] = 0;
    }
    // First is also clear
    set_interrupt_descriptor_table_entry(0, code_segment, &InterruptIgnore, 0,IDT_INTERRUPT_GATE);
    m_interrupt_handlers[0] = 0;
    //Set Up the base interrupts
    set_interrupt_descriptor_table_entry(0x00, code_segment, &HandleException0x00, 0, IDT_INTERRUPT_GATE); //Division by zero
    set_interrupt_descriptor_table_entry(0x01, code_segment, &HandleException0x01, 0, IDT_INTERRUPT_GATE); //Single-step interrupt (see trap flag)
    set_interrupt_descriptor_table_entry(0x02, code_segment, &HandleException0x02, 0, IDT_INTERRUPT_GATE); //NMI
    set_interrupt_descriptor_table_entry(0x03, code_segment, &HandleException0x03, 0, IDT_INTERRUPT_GATE); //Breakpoint (which benefits from the shorter 0xCC encoding of INT 3)
    set_interrupt_descriptor_table_entry(0x04, code_segment, &HandleException0x04, 0, IDT_INTERRUPT_GATE); //Overflow
    set_interrupt_descriptor_table_entry(0x05, code_segment, &HandleException0x05, 0, IDT_INTERRUPT_GATE); //Bound Range Exceeded
    set_interrupt_descriptor_table_entry(0x06, code_segment, &HandleException0x06, 0, IDT_INTERRUPT_GATE); //Invalid Opcode
    set_interrupt_descriptor_table_entry(0x07, code_segment, &HandleException0x07, 0, IDT_INTERRUPT_GATE); //Coprocessor not available
    set_interrupt_descriptor_table_entry(0x08, code_segment, &HandleException0x08, 0, IDT_INTERRUPT_GATE); //Double Fault
    set_interrupt_descriptor_table_entry(0x09, code_segment, &HandleException0x09, 0, IDT_INTERRUPT_GATE); //Coprocessor Segment Overrun (386 or earlier only)
    set_interrupt_descriptor_table_entry(0x0A, code_segment, &HandleException0x0A, 0, IDT_INTERRUPT_GATE); //Invalid Task State Segment
    set_interrupt_descriptor_table_entry(0x0B, code_segment, &HandleException0x0B, 0, IDT_INTERRUPT_GATE); //Segment not present
    set_interrupt_descriptor_table_entry(0x0C, code_segment, &HandleException0x0C, 0, IDT_INTERRUPT_GATE); //Stack Segment Fault
    set_interrupt_descriptor_table_entry(0x0D, code_segment, &HandleException0x0D, 0, IDT_INTERRUPT_GATE); //General Protection Fault
    set_interrupt_descriptor_table_entry(0x0E, code_segment, &HandleException0x0E, 0, IDT_INTERRUPT_GATE); //Page Fault
    set_interrupt_descriptor_table_entry(0x0F, code_segment, &HandleException0x0F, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x10, code_segment, &HandleException0x10, 0, IDT_INTERRUPT_GATE); //x87 Floating Point Exception
    set_interrupt_descriptor_table_entry(0x11, code_segment, &HandleException0x11, 0, IDT_INTERRUPT_GATE); //Alignment Check
    set_interrupt_descriptor_table_entry(0x12, code_segment, &HandleException0x12, 0, IDT_INTERRUPT_GATE); //Machine Check
    set_interrupt_descriptor_table_entry(0x13, code_segment, &HandleException0x13, 0, IDT_INTERRUPT_GATE); //SIMD Floating-Point Exception
    set_interrupt_descriptor_table_entry(0x14, code_segment, &HandleException0x14, 0, IDT_INTERRUPT_GATE); //Virtualization Exception
    set_interrupt_descriptor_table_entry(0x15, code_segment, &HandleException0x15, 0, IDT_INTERRUPT_GATE); //Control Protection Exception
    set_interrupt_descriptor_table_entry(0x16, code_segment, &HandleException0x16, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x17, code_segment, &HandleException0x17, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x18, code_segment, &HandleException0x18, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x19, code_segment, &HandleException0x19, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x1A, code_segment, &HandleException0x1A, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x1B, code_segment, &HandleException0x1B, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x1C, code_segment, &HandleException0x1C, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x1D, code_segment, &HandleException0x1D, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x1E, code_segment, &HandleException0x1E, 0, IDT_INTERRUPT_GATE); //reserved
    set_interrupt_descriptor_table_entry(0x1F, code_segment, &HandleException0x1F, 0, IDT_INTERRUPT_GATE); //reserved
    //Set up the hardware interrupts (offset by 0x20) //Ranges 0x20 - 0x30
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x00, code_segment, &HandleInterruptRequest0x00, 0, IDT_INTERRUPT_GATE); //0x20 - Default PIC interval / Timer
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x01, code_segment, &HandleInterruptRequest0x01, 0, IDT_INTERRUPT_GATE); //0x21 - Keyboard
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x02, code_segment, &HandleInterruptRequest0x02, 0, IDT_INTERRUPT_GATE); //0x22 - Cascade (used internally by the two PICs. never raised)
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x03, code_segment, &HandleInterruptRequest0x03, 0, IDT_INTERRUPT_GATE); //0x23 - COM2, COM4
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x04, code_segment, &HandleInterruptRequest0x04, 0, IDT_INTERRUPT_GATE); //0x24 - COM1, COM3
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x05, code_segment, &HandleInterruptRequest0x05, 0, IDT_INTERRUPT_GATE); //0x25 - LPT2, LPT4
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x06, code_segment, &HandleInterruptRequest0x06, 0, IDT_INTERRUPT_GATE); //0x26 - LPT1
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x07, code_segment, &HandleInterruptRequest0x07, 0, IDT_INTERRUPT_GATE); //0x27 - Floppy Disk
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x08, code_segment, &HandleInterruptRequest0x08, 0, IDT_INTERRUPT_GATE); //0x28 - CMOS Real Time Clock
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x09, code_segment, &HandleInterruptRequest0x09, 0, IDT_INTERRUPT_GATE); //0x29 - Free for peripherals / legacy SCSI / NIC
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x0A, code_segment, &HandleInterruptRequest0x0A, 0, IDT_INTERRUPT_GATE); //0x2A - Free for peripherals / SCSI / NIC
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x0B, code_segment, &HandleInterruptRequest0x0B, 0, IDT_INTERRUPT_GATE); //0x2B - Free for peripherals / SCSI / NIC
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x0C, code_segment, &HandleInterruptRequest0x0C, 0, IDT_INTERRUPT_GATE); //0x0C - Mouse
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x0D, code_segment, &HandleInterruptRequest0x0D, 0, IDT_INTERRUPT_GATE); //0x2D - FPU / Coprocessor / Inter-processor
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x0E, code_segment, &HandleInterruptRequest0x0E, 0, IDT_INTERRUPT_GATE); //0x2E - Primary ATA Hard Disk
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x0F, code_segment, &HandleInterruptRequest0x0F, 0, IDT_INTERRUPT_GATE); //0x2F - Secondary ATA Hard Disk
    set_interrupt_descriptor_table_entry(hardware_interrupt_offset + 0x60, code_segment, &HandleInterruptRequest0x80, 0, IDT_INTERRUPT_GATE); //0x80 - Sys calls
    //Send Initialization Control Words
    pic_master_command_port.write(0x11);
    pic_slave_command_port.write(0x11);
    // Remap the PIC to use the hardware interrupt offset
    pic_master_data_port.write(hardware_interrupt_offset);
    pic_slave_data_port.write(hardware_interrupt_offset + 8);
    //Tell PICs their roles
    pic_master_data_port.write(0x04); //Master
    pic_slave_data_port.write(0x02); //Slave
    //Tell PICS that they are in 8086 mode
    pic_master_data_port.write(0x01);
    pic_slave_data_port.write(0x01);
    // Clear the interrupt mask to enable all interrupts
    pic_master_data_port.write(0x00);
    pic_slave_data_port.write(0x00);
    //Tell the processor to use the IDT
    InterruptDescriptorTablePointer idt_pointer;
    idt_pointer.size = 256*sizeof(GateDescriptor) - 1;
    idt_pointer.base = (uint32_t)s_interrupt_descriptor_table;
    asm volatile("lidt %0" : : "m" (idt_pointer));
};
References MaxOS::hardwarecommunication::InterruptDescriptorTablePointer::base, MaxOS::system::GlobalDescriptorTable::code_segment_selector(), HandleException0x00(), HandleException0x01(), HandleException0x02(), HandleException0x03(), HandleException0x04(), HandleException0x05(), HandleException0x06(), HandleException0x07(), HandleException0x08(), HandleException0x09(), HandleException0x0A(), HandleException0x0B(), HandleException0x0C(), HandleException0x0D(), HandleException0x0E(), HandleException0x0F(), HandleException0x10(), HandleException0x11(), HandleException0x12(), HandleException0x13(), HandleException0x14(), HandleException0x15(), HandleException0x16(), HandleException0x17(), HandleException0x18(), HandleException0x19(), HandleException0x1A(), HandleException0x1B(), HandleException0x1C(), HandleException0x1D(), HandleException0x1E(), HandleException0x1F(), HandleInterruptRequest0x00(), HandleInterruptRequest0x01(), HandleInterruptRequest0x02(), HandleInterruptRequest0x03(), HandleInterruptRequest0x04(), HandleInterruptRequest0x05(), HandleInterruptRequest0x06(), HandleInterruptRequest0x07(), HandleInterruptRequest0x08(), HandleInterruptRequest0x09(), HandleInterruptRequest0x0A(), HandleInterruptRequest0x0B(), HandleInterruptRequest0x0C(), HandleInterruptRequest0x0D(), HandleInterruptRequest0x0E(), HandleInterruptRequest0x0F(), HandleInterruptRequest0x80(), hardware_interrupt_offset(), MaxOS::drivers::peripherals::i, InterruptIgnore(), m_interrupt_handlers, pic_master_command_port, pic_master_data_port, pic_slave_command_port, pic_slave_data_port, s_interrupt_descriptor_table, set_interrupt_descriptor_table_entry(), MaxOS::hardwarecommunication::InterruptDescriptorTablePointer::size, and MaxOS::hardwarecommunication::Port8BitSlow::write().
 InterruptManager()
InterruptManager::~InterruptManager ()
Definition at line 153 of file interrupts.cpp.
{
  deactivate();
}
References deactivate().
Member Function Documentation
activate()
void InterruptManager::activate ()
Activates the interrupt manager and starts interrupts (also deactivates the current interrupt manager)
Definition at line 185 of file interrupts.cpp.
                                {
    // Deactivate the current interrupt manager
    if(s_active_interrupt_manager != 0)
      s_active_interrupt_manager->deactivate();
    // Set the current interrupt manager and start interrupts
    s_active_interrupt_manager = this;
    asm("sti");
}
References deactivate(), and s_active_interrupt_manager.
Referenced by kernelMain().
deactivate()
void InterruptManager::deactivate ()
Deactivates the interrupt manager and stops interrupts.
Definition at line 200 of file interrupts.cpp.
{
    // If this is the active interrupt manager, deactivate it and stop interrupts
    if(s_active_interrupt_manager == this){
      s_active_interrupt_manager = 0;
      asm("cli");
    }
}
References s_active_interrupt_manager.
Referenced by activate(), and ~InterruptManager().
handle_interrupt_request()
uint32_t InterruptManager::handle_interrupt_request (uint8_t interrupt, uint32_t esp) [protected]
Handles the interrupt request and runs the interrupt handler if there is one.
Parameters
interruptNumber The interrupt number
esp The stack pointer
Returns
The stack pointer
Definition at line 235 of file interrupts.cpp.
{
    // If there is an interrupt handler, run it
    if(m_interrupt_handlers[interrupt] != 0){
      m_interrupt_handlers[interrupt]->handle_interrupt();
    }
    else if(interrupt != 0x20){
        switch (interrupt) {
            case 0x00: s_error_messages->write("[ERROR] Divide by zero (int 0x00)"); break;
            case 0x01: s_error_messages->write("[ERROR] Single-step interrupt (int 0x01)"); break;
            case 0x02: s_error_messages->write("[ERROR] Non maskable interrupt (int 0x02)"); break;
            case 0x03: s_error_messages->write("[ERROR] Breakpoint (int 0x03)"); break;
            case 0x04: s_error_messages->write("[ERROR] Overflow (int 0x04)"); break;
            case 0x05: s_error_messages->write("[ERROR] Bounds check (int 0x05)"); break;
            case 0x06: s_error_messages->write("[ERROR] Invalid opcode (int 0x06)"); break;
            case 0x07: s_error_messages->write("[ERROR] Coprocessor not available (int 0x07)"); break;
            case 0x08: s_error_messages->write("[ERROR] Double fault (int 0x08)"); break;
            case 0x09: s_error_messages->write("[ERROR] Coprocessor segment overrun (int 0x09)"); break;
            case 0x0A: s_error_messages->write("[ERROR] Invalid TSS (int 0x0A)"); break;
            case 0x0B: s_error_messages->write("[ERROR] Segment not present (int 0x0B)"); break;
            case 0x0C: s_error_messages->write("[ERROR] Stack segment fault (int 0x0C)"); break;
            case 0x0D: s_error_messages->write("[ERROR] General protection fault (int 0x0D)"); break;
            case 0x0E: s_error_messages->write("[ERROR] Page fault (int 0x0E)"); break;
            case 0x0F: s_error_messages->write("[INFO] Reserved (int 0x0F)"); break;
            case 0x10: s_error_messages->write("[ERROR] x87 FPU floating point error (int 0x10)"); break;
            case 0x11: s_error_messages->write("[INFO] Alignment check (int 0x11)"); break;
            case 0x12: s_error_messages->write("[INFO] Machine check (int 0x12)"); break;
            case 0x13: s_error_messages->write("[ERROR] SIMD floating point exception (int 0x13)"); break;
            case 0x14: s_error_messages->write("[ERROR] Virtualization exception (int 0x14)"); break;
            case 0x15: s_error_messages->write("[INFO] Reserved (int 0x15)"); break;
            case 0x16: s_error_messages->write("[INFO] Reserved (int 0x16)"); break;
            case 0x17: s_error_messages->write("[INFO] Reserved (int 0x17)"); break;
            case 0x18: s_error_messages->write("[INFO] Reserved (int 0x18)"); break;
            case 0x19: s_error_messages->write("[INFO] Reserved (int 0x19)"); break;
            case 0x1A: s_error_messages->write("[INFO] Reserved (int 0x1A)"); break;
            case 0x1B: s_error_messages->write("[INFO] Reserved (int 0x1B)"); break;
            case 0x1C: s_error_messages->write("[INFO] Reserved (int 0x1C)"); break;
            case 0x1D: s_error_messages->write("[INFO] Reserved (int 0x1D)"); break;
            case 0x1E: s_error_messages->write("[INFO] Reserved (int 0x1E)"); break;
            case 0x1F: s_error_messages->write("[INFO] Reserved (int 0x1F)"); break;
            default:
              s_error_messages->write("UNHANDLED INTERRUPT 0x");
              s_error_messages->write_hex(interrupt);
              s_error_messages->write(" ");
                break;
        }
    }
    //Timer interrupt for m_tasks
    if(interrupt == m_hardware_interrupt_offset)
    {
        esp = (uint32_t)m_thread_manager->schedule((CPUState*)esp);
    }
    // Acknowledge the interrupt (if it is a hardware interrupt)
    if(m_hardware_interrupt_offset <= interrupt && interrupt < m_hardware_interrupt_offset +16)
    {
      pic_master_command_port.write(0x20);
        // Answer the slave PIC if it was the one that sent the interrupt
        if(0x28 <= interrupt)
          pic_slave_command_port.write(0x20);
    }
    return esp;
}
References esp, MaxOS::hardwarecommunication::InterruptHandler::handle_interrupt(), m_hardware_interrupt_offset, m_interrupt_handlers, m_thread_manager, pic_master_command_port, pic_slave_command_port, s_error_messages, MaxOS::system::ThreadManager::schedule(), MaxOS::hardwarecommunication::Port8BitSlow::write(), MaxOS::common::OutputStream::write(), and MaxOS::common::OutputStream::write_hex().
Referenced by HandleInterrupt().
HandleException0x00()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x00 () [static], [protected]
Referenced by InterruptManager().
HandleException0x01()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x01 () [static], [protected]
Referenced by InterruptManager().
HandleException0x02()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x02 () [static], [protected]
Referenced by InterruptManager().
HandleException0x03()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x03 () [static], [protected]
Referenced by InterruptManager().
HandleException0x04()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x04 () [static], [protected]
Referenced by InterruptManager().
HandleException0x05()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x05 () [static], [protected]
Referenced by InterruptManager().
HandleException0x06()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x06 () [static], [protected]
Referenced by InterruptManager().
HandleException0x07()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x07 () [static], [protected]
Referenced by InterruptManager().
HandleException0x08()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x08 () [static], [protected]
Referenced by InterruptManager().
HandleException0x09()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x09 () [static], [protected]
Referenced by InterruptManager().
HandleException0x0A()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x0A () [static], [protected]
Referenced by InterruptManager().
HandleException0x0B()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x0B () [static], [protected]
Referenced by InterruptManager().
HandleException0x0C()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x0C () [static], [protected]
Referenced by InterruptManager().
HandleException0x0D()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x0D () [static], [protected]
Referenced by InterruptManager().
HandleException0x0E()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x0E () [static], [protected]
Referenced by InterruptManager().
HandleException0x0F()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x0F () [static], [protected]
Referenced by InterruptManager().
HandleException0x10()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x10 () [static], [protected]
Referenced by InterruptManager().
HandleException0x11()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x11 () [static], [protected]
Referenced by InterruptManager().
HandleException0x12()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x12 () [static], [protected]
Referenced by InterruptManager().
HandleException0x13()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x13 () [static], [protected]
Referenced by InterruptManager().
HandleException0x14()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x14 () [static], [protected]
Referenced by InterruptManager().
HandleException0x15()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x15 () [static], [protected]
Referenced by InterruptManager().
HandleException0x16()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x16 () [static], [protected]
Referenced by InterruptManager().
HandleException0x17()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x17 () [static], [protected]
Referenced by InterruptManager().
HandleException0x18()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x18 () [static], [protected]
Referenced by InterruptManager().
HandleException0x19()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x19 () [static], [protected]
Referenced by InterruptManager().
HandleException0x1A()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x1A () [static], [protected]
Referenced by InterruptManager().
HandleException0x1B()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x1B () [static], [protected]
Referenced by InterruptManager().
HandleException0x1C()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x1C () [static], [protected]
Referenced by InterruptManager().
HandleException0x1D()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x1D () [static], [protected]
Referenced by InterruptManager().
HandleException0x1E()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x1E () [static], [protected]
Referenced by InterruptManager().
HandleException0x1F()
static void MaxOS::hardwarecommunication::InterruptManager::HandleException0x1F () [static], [protected]
Referenced by InterruptManager().
HandleInterrupt()
uint32_t InterruptManager::HandleInterrupt (uint8_t interrupt, uint32_t esp) [static], [protected]
Handles the interrupt request by passing it to the interrupt manager.
Parameters
interruptNumber The interrupt number
esp The stack pointer
Returns
The stack pointer
Definition at line 217 of file interrupts.cpp.
{
    // If there is an active interrupt manager, handle the interrupt
    if(s_active_interrupt_manager != 0)
        return s_active_interrupt_manager->handle_interrupt_request(interrupt, esp);
    // CPU can continue
    return esp;
}
References esp, handle_interrupt_request(), and s_active_interrupt_manager.
HandleInterruptRequest()
static uint32_t MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest (uint32_t esp) [static], [protected]
HandleInterruptRequest0x00()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x00 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x01()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x01 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x02()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x02 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x03()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x03 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x04()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x04 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x05()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x05 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x06()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x06 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x07()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x07 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x08()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x08 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x09()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x09 () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x0A()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x0A () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x0B()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x0B () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x0C()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x0C () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x0D()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x0D () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x0E()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x0E () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x0F()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x0F () [static], [protected]
Referenced by InterruptManager().
HandleInterruptRequest0x31()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x31 () [static], [protected]
HandleInterruptRequest0x80()
static void MaxOS::hardwarecommunication::InterruptManager::HandleInterruptRequest0x80 () [static], [protected]
Referenced by InterruptManager().
hardware_interrupt_offset()
uint16_t InterruptManager::hardware_interrupt_offset ()
Returns the offset of the hardware interrupt.
Returns
The offset of the hardware interrupt
Definition at line 312 of file interrupts.cpp.
                                                     {
    return m_hardware_interrupt_offset;
}
References m_hardware_interrupt_offset.
Referenced by InterruptManager().
InterruptIgnore()
static void MaxOS::hardwarecommunication::InterruptManager::InterruptIgnore () [static], [protected]
Referenced by InterruptManager().
remove_interrupt_handler()
void InterruptManager::remove_interrupt_handler (uint8_t interrupt)
Removes the interrupt handler for the interrupt.
Parameters
interrupt The interrupt number
Definition at line 331 of file interrupts.cpp.
                                                                 {
  m_interrupt_handlers[interrupt] = 0;
}
References m_interrupt_handlers.
Referenced by MaxOS::hardwarecommunication::InterruptHandler::~InterruptHandler().
set_interrupt_descriptor_table_entry()
void InterruptManager::set_interrupt_descriptor_table_entry (uint8_t interrupt, uint16_t code_segment_selector_offset, void(*)() handler, uint8_t DescriptorPrivilegeLevel, uint8_t descriptor_type) [static], [protected]
Sets an entry in the Interrupt Descriptor Table.
Parameters
interrupt Interrupt number
code_segment_selector_offset Code segment
handler Interrupt Handler
DescriptorPrivilegeLevel Descriptor Privilege Level
descriptor_type Descriptor Type
Definition at line 168 of file interrupts.cpp.
{
  // Store the handler function in the IDT
  s_interrupt_descriptor_table[interrupt].handler_address_low_bits = ((uint32_t) handler) & 0xFFFF;
  s_interrupt_descriptor_table[interrupt].handler_address_high_bits = (((uint32_t) handler) >> 16) & 0xFFFF;
  s_interrupt_descriptor_table[interrupt].gdt_code_segment_selector = code_segment_selector_offset;
  // Set the access
  const uint8_t IDT_DESC_PRESENT = 0x80;
  s_interrupt_descriptor_table[interrupt].access = IDT_DESC_PRESENT | ((DescriptorPrivilegeLevel & 3) << 5) | descriptor_type;
  s_interrupt_descriptor_table[interrupt].reserved = 0;
}
References MaxOS::hardwarecommunication::GateDescriptor::access, MaxOS::hardwarecommunication::GateDescriptor::gdt_code_segment_selector, MaxOS::hardwarecommunication::GateDescriptor::handler_address_high_bits, MaxOS::hardwarecommunication::GateDescriptor::handler_address_low_bits, MaxOS::hardwarecommunication::GateDescriptor::reserved, and s_interrupt_descriptor_table.
Referenced by InterruptManager().
set_interrupt_handler()
void InterruptManager::set_interrupt_handler (uint8_t interrupt, InterruptHandler * handler)
Sets the interrupt handler for the interrupt.
Parameters
interrupt The interrupt number
handler The interrupt handler
Definition at line 322 of file interrupts.cpp.
                                                                                         {
  m_interrupt_handlers[interrupt] = handler;
}
References m_interrupt_handlers.
Referenced by MaxOS::hardwarecommunication::InterruptHandler::InterruptHandler().
Friends And Related Function Documentation
InterruptHandler
friend class InterruptHandler [friend]
Definition at line 64 of file interrupts.h.
Member Data Documentation
m_hardware_interrupt_offset
uint16_t MaxOS::hardwarecommunication::InterruptManager::m_hardware_interrupt_offset [protected]
Definition at line 70 of file interrupts.h.
Referenced by handle_interrupt_request(), and hardware_interrupt_offset().
m_interrupt_handlers
InterruptHandler* MaxOS::hardwarecommunication::InterruptManager::m_interrupt_handlers[256] [protected]
Definition at line 71 of file interrupts.h.
Referenced by handle_interrupt_request(), InterruptManager(), remove_interrupt_handler(), and set_interrupt_handler().
m_thread_manager
system::ThreadManager* MaxOS::hardwarecommunication::InterruptManager::m_thread_manager [protected]
Definition at line 72 of file interrupts.h.
Referenced by handle_interrupt_request().
pic_master_command_port
Port8BitSlow MaxOS::hardwarecommunication::InterruptManager::pic_master_command_port [protected]
Definition at line 139 of file interrupts.h.
Referenced by handle_interrupt_request(), and InterruptManager().
pic_master_data_port
Port8BitSlow MaxOS::hardwarecommunication::InterruptManager::pic_master_data_port [protected]
Definition at line 140 of file interrupts.h.
Referenced by InterruptManager().
pic_slave_command_port
Port8BitSlow MaxOS::hardwarecommunication::InterruptManager::pic_slave_command_port [protected]
Definition at line 141 of file interrupts.h.
Referenced by handle_interrupt_request(), and InterruptManager().
pic_slave_data_port
Port8BitSlow MaxOS::hardwarecommunication::InterruptManager::pic_slave_data_port [protected]
Definition at line 142 of file interrupts.h.
Referenced by InterruptManager().
s_active_interrupt_manager
InterruptManager * InterruptManager::s_active_interrupt_manager = 0 [static], [protected]
Definition at line 68 of file interrupts.h.
Referenced by activate(), deactivate(), and HandleInterrupt().
s_error_messages
OutputStream * InterruptManager::s_error_messages = 0 [static], [protected]
Definition at line 69 of file interrupts.h.
Referenced by handle_interrupt_request().
s_interrupt_descriptor_table
GateDescriptor InterruptManager::s_interrupt_descriptor_table [static], [protected]
Definition at line 74 of file interrupts.h.
Referenced by InterruptManager(), and set_interrupt_descriptor_table_entry().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/interrupts.h
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/interrupts.cpp