MaxOS::filesystem::Directory Class Reference
Handles a group of files (directory)
#include <filesystem.h>
Public Member Functions
virtual void read_from_disk ()
Read the directory from the disk.
common::Vector< File * > files ()
Get the files in the directory.
common::Vector< Directory * > subdirectories ()
Get the subdirectories in the directory.
File * open_file (const string &name)
Open a file in the directory.
Directory * open_subdirectory (const string &name)
Open a directory in the directory.
virtual File * create_file (const string &name)
Create a file in the directory.
virtual void remove_file (const string &name)
Delete a file in the directory.
void rename_file (File *file, const string &new_name)
Rename a file in the directory.
virtual void rename_file (const string &old_name, const string &new_name)
Rename a file in the directory.
void rename_subdirectory (Directory *directory, const string &new_name)
Rename a subdirectory in the directory.
virtual void rename_subdirectory (const string &old_name, const string &new_name)
Rename a subdirectory in the directory.
virtual Directory * create_subdirectory (const string &name)
Create a directory in the directory.
virtual void remove_subdirectory (const string &name)
Try to remove a directory in the directory.
string name ()
Get the name of the directory.
size_t size ()
Get the size of the directory.
Protected Attributes
common::Vector< File * > m_files
The files in this directory.
common::Vector< Directory * > m_subdirectories
The subdirectories in this directory.
string m_name
The name of this directory.
Detailed Description
Handles a group of files (directory)
Definition at line 60 of file filesystem.h.
Constructor & Destructor Documentation
~Directory()
Directory::~Directory () [virtual]
Definition at line 97 of file filesystem.cpp.
                      {
    // Free the files
    for (auto &file: m_files)
        delete file;
    // Free the subdirectories
    for (auto &subdirectory: m_subdirectories)
        delete subdirectory;
}
Member Function Documentation
create_file()
File * Directory::create_file (const string & name) [virtual]
Create a file in the directory.
Parameters
name The name of the file to create
Returns
A new file object or null if it could not be created
Reimplemented in MaxOS::filesystem::format::ext2::Ext2Directory, and MaxOS::filesystem::format::Fat32Directory.
Definition at line 148 of file filesystem.cpp.
                                               {
    return nullptr;
}
Referenced by MaxOS::filesystem::DirectoryResource::write().
create_subdirectory()
Directory * Directory::create_subdirectory (const string & name) [virtual]
Create a directory in the directory.
Parameters
name The name of the directory to create
Returns
The new directory object or null if it could not be created
Reimplemented in MaxOS::filesystem::format::ext2::Ext2Directory, and MaxOS::filesystem::format::Fat32Directory.
Definition at line 194 of file filesystem.cpp.
                                                            {
    return nullptr;
}
Referenced by MaxOS::filesystem::DirectoryResource::write().
files()
common::Vector< File * > Directory::files ()
Get the files in the directory.
Returns
A list of all the files in the directory
Definition at line 121 of file filesystem.cpp.
                                     {
    return m_files;
}
References m_files.
name()
string Directory::name ()
Get the name of the directory.
Returns
The name of the directory
Definition at line 211 of file filesystem.cpp.
                       {
    return m_name;
}
References m_name.
Referenced by MaxOS::filesystem::format::ext2::Ext2Directory::create_file(), MaxOS::filesystem::format::Fat32Directory::create_file(), MaxOS::filesystem::format::ext2::Ext2Directory::create_subdirectory(), MaxOS::filesystem::format::Fat32Directory::create_subdirectory(), MaxOS::filesystem::format::ext2::Ext2Directory::Ext2Directory(), MaxOS::filesystem::format::Fat32Directory::Fat32Directory(), open_file(), open_subdirectory(), MaxOS::filesystem::format::Fat32Directory::read_from_disk(), MaxOS::filesystem::format::ext2::Ext2Directory::remove_file(), MaxOS::filesystem::format::Fat32Directory::remove_file(), MaxOS::filesystem::format::ext2::Ext2Directory::remove_subdirectory(), MaxOS::filesystem::format::Fat32Directory::remove_subdirectory(), and rename_subdirectory().
open_file()
File * Directory::open_file (const string & name)
Open a file in the directory.
Parameters
name The name of the file to open
Returns
Definition at line 131 of file filesystem.cpp.
                                             {
    // Try to find the file
    for (auto &file: m_files)
        if (file->name() == name)
            return file;
    // File not found
    return nullptr;
}
References m_files, and name().
Referenced by MaxOS::filesystem::FileSystem::exists().
open_subdirectory()
Directory * Directory::open_subdirectory (const string & name)
Open a directory in the directory.
Parameters
name The name of the directory to open
Returns
The directory object or null if it could not be opened
Definition at line 175 of file filesystem.cpp.
                                                          {
    // Try to find the directory
    for (auto &subdirectory: m_subdirectories)
        if (subdirectory->name() == name) {
            subdirectory->read_from_disk();
            return subdirectory;
        }
    // Directory not found
    return nullptr;
}
References m_subdirectories, and name().
Referenced by MaxOS::filesystem::FileSystem::get_directory().
read_from_disk()
void Directory::read_from_disk () [virtual]
Read the directory from the disk.
Reimplemented in MaxOS::filesystem::format::ext2::Ext2Directory, and MaxOS::filesystem::format::Fat32Directory.
Definition at line 112 of file filesystem.cpp.
                               {
}
Referenced by MaxOS::filesystem::VirtualFileSystem::create_directory(), MaxOS::filesystem::format::ext2::Ext2FileSystem::Ext2FileSystem(), MaxOS::filesystem::format::Fat32FileSystem::Fat32FileSystem(), and MaxOS::filesystem::VirtualFileSystem::open_directory().
remove_file()
void Directory::remove_file (const string & name) [virtual]
Delete a file in the directory.
Parameters
name The name of the file to remove
Reimplemented in MaxOS::filesystem::format::ext2::Ext2Directory, and MaxOS::filesystem::format::Fat32Directory.
Definition at line 157 of file filesystem.cpp.
                                              {
}
Referenced by MaxOS::filesystem::DirectoryResource::write().
remove_subdirectory()
void Directory::remove_subdirectory (const string & name) [virtual]
Try to remove a directory in the directory.
Parameters
name The name of the directory to remove
Reimplemented in MaxOS::filesystem::format::ext2::Ext2Directory, and MaxOS::filesystem::format::Fat32Directory.
Definition at line 202 of file filesystem.cpp.
                                                      {
}
Referenced by MaxOS::filesystem::DirectoryResource::write().
rename_file() [1/2]
void Directory::rename_file (const string & old_name, const string & new_name) [virtual]
Rename a file in the directory.
Parameters
old_name The file to rename
new_name The new name of the file
Reimplemented in MaxOS::filesystem::format::ext2::Ext2Directory.
Definition at line 249 of file filesystem.cpp.
                                                                          {
    ASSERT(false, "not implemented");
}
References ASSERT.
rename_file() [2/2]
void Directory::rename_file (File * file, const string & new_name)
Rename a file in the directory.
Parameters
file The file to rename
new_name The new name of the file
Definition at line 237 of file filesystem.cpp.
                                                              {
    rename_file(file->name(), new_name);
}
References MaxOS::filesystem::File::name(), and rename_file().
Referenced by rename_file().
rename_subdirectory() [1/2]
void Directory::rename_subdirectory (const string & old_name, const string & new_name) [virtual]
Rename a subdirectory in the directory.
Parameters
old_name The directory to rename
new_name The new name of the directory
Reimplemented in MaxOS::filesystem::format::ext2::Ext2Directory.
Definition at line 273 of file filesystem.cpp.
                                                                                  {
    ASSERT(false, "not implemented");
}
References ASSERT.
rename_subdirectory() [2/2]
void Directory::rename_subdirectory (Directory * directory, const string & new_name)
Rename a subdirectory in the directory.
Parameters
directory The directory to rename
new_name The new name of the directory
Definition at line 261 of file filesystem.cpp.
                                                                                {
    rename_subdirectory(directory->name(), new_name);
}
References name(), and rename_subdirectory().
Referenced by rename_subdirectory().
size()
size_t Directory::size ()
Get the size of the directory.
Returns
The size of the directory (sum of all the files in bytes)
Definition at line 220 of file filesystem.cpp.
                       {
    // Sum the size of all the files
    size_t size = 0;
    for (auto &file: m_files)
        size += file->size();
    return size;
}
References m_files, and size().
Referenced by size().
subdirectories()
common::Vector< Directory * > Directory::subdirectories ()
Get the subdirectories in the directory.
Returns
The subdirectories in the directory
Definition at line 165 of file filesystem.cpp.
                                                   {
    return m_subdirectories;
}
References m_subdirectories.
Member Data Documentation
m_files
common::Vector<File*> MaxOS::filesystem::Directory::m_files [protected]
The files in this directory.
Definition at line 63 of file filesystem.h.
Referenced by MaxOS::filesystem::format::ext2::Ext2Directory::create_file(), MaxOS::filesystem::format::Fat32Directory::create_file(), files(), open_file(), MaxOS::filesystem::format::ext2::Ext2Directory::read_from_disk(), MaxOS::filesystem::format::Fat32Directory::read_from_disk(), MaxOS::filesystem::format::Fat32Directory::remove_file(), and size().
m_name
string MaxOS::filesystem::Directory::m_name [protected]
The name of this directory.
Definition at line 66 of file filesystem.h.
Referenced by MaxOS::filesystem::format::ext2::Ext2Directory::Ext2Directory(), MaxOS::filesystem::format::Fat32Directory::Fat32Directory(), and name().
m_subdirectories
common::Vector<Directory*> MaxOS::filesystem::Directory::m_subdirectories [protected]
The subdirectories in this directory.
Definition at line 64 of file filesystem.h.
Referenced by MaxOS::filesystem::format::ext2::Ext2Directory::create_subdirectory(), MaxOS::filesystem::format::Fat32Directory::create_subdirectory(), open_subdirectory(), MaxOS::filesystem::format::ext2::Ext2Directory::read_from_disk(), MaxOS::filesystem::format::Fat32Directory::read_from_disk(), MaxOS::filesystem::format::Fat32Directory::remove_subdirectory(), and subdirectories().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/filesystem.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/filesystem.cpp