MaxOS::memory::MemoryManager Class Reference
Handles memory allocation and deallocation.
#include <memorymanagement.h>
Public Member Functions
MemoryManager (VirtualMemoryManager *virtual_memory_manager)
~MemoryManager ()
void * handle_malloc (size_t size)
Allocates a block of memory.
void handle_free (void *pointer)
Frees a block of memory.
VirtualMemoryManager * get_vmm ()
int memory_used ()
Returns the amount of memory used.
size_t align (size_t size)
Aligns the size to the chunk alignment.
Static Public Member Functions
static void * malloc (size_t size)
Allocates a block of memory using the current memory manager.
static void free (void *pointer)
Frees a block of memory using the current memory manager.
static void * kmalloc (size_t size)
Allocates a block of memory using the kernel memory manager.
static void kfree (void *pointer)
Frees a block of memory using the kernel memory manager.
static void switch_active_memory_manager (MemoryManager *manager)
Switches the active memory manager.
static void * to_higher_region (uintptr_t physical_address)
Converts a physical address to a higher region address if it is in the lower region using the higher half kernel offset.
static void * to_lower_region (uintptr_t virtual_address)
Converts a virtual address to a lower region address if it is in the higher region using the higher half kernel offset.
static void * to_io_region (uintptr_t physical_address)
Converts a physical address to an IO region address if it is in the lower region using the higher half memory offset.
static void * to_dm_region (uintptr_t physical_address)
Converts a physical address to a direct map region address if it is in the lower region using the higher half direct map offset.
static void * from_dm_region (uintptr_t physical_address)
Converts a direct map region address to a physical address if it is in the higher region using the higher half direct map offset.
static bool in_higher_region (uintptr_t virtual_address)
Checks if a virtual address is in the higher region.
Public Attributes
MemoryManager * previous_memory_manager
Static Public Attributes
static MemoryManager * s_current_memory_manager = 0
static MemoryManager * s_kernel_memory_manager = 0
static const uint64_t s_higher_half_kernel_offset { 0xFFFFFFFF80000000 }
static const uint64_t s_higher_half_mem_offset { 0xFFFF800000000000 }
static const uint64_t s_higher_half_mem_reserved { 0x280000000 }
static const uint64_t s_higher_half_offset { s_higher_half_mem_offset + s_higher_half_mem_reserved}
static const uint64_t s_hh_direct_map_offset { s_higher_half_offset + PhysicalMemoryManager::s_page_size }
static const size_t s_chunk_alignment { 0x10 }
Detailed Description
Handles memory allocation and deallocation.
Definition at line 35 of file memorymanagement.h.
Constructor & Destructor Documentation
MemoryManager()
MemoryManager::MemoryManager (VirtualMemoryManager * virtual_memory_manager)
Definition at line 17 of file memorymanagement.cpp.
: m_virtual_memory_manager(vmm)
{
    // Enable the memory manager
    switch_active_memory_manager(this);
    // Get the first chunk of memory
    this -> m_first_memory_chunk = (MemoryChunk*)m_virtual_memory_manager->allocate(PhysicalMemoryManager::s_page_size + sizeof(MemoryChunk), 0);
    // Set the first chunk's properties
    m_first_memory_chunk-> allocated = false;
    m_first_memory_chunk-> prev = 0;
    m_first_memory_chunk-> next = 0;
    m_first_memory_chunk-> size = PhysicalMemoryManager::s_page_size - sizeof(MemoryChunk);
    // Set the last chunk to the first chunk
    m_last_memory_chunk = m_first_memory_chunk;
    // The first chunk is the last chunk
    _kprintf("First memory chunk: 0x%x\n", m_first_memory_chunk);
}
References _kprintf, MaxOS::memory::VirtualMemoryManager::allocate(), next, MaxOS::memory::PhysicalMemoryManager::s_page_size, size, and switch_active_memory_manager().
 MemoryManager()
MemoryManager::~MemoryManager ()
Definition at line 41 of file memorymanagement.cpp.
                              {
    // Check if the current memory manager is this one
    if(s_kernel_memory_manager == this)
      s_kernel_memory_manager = 0;
    // Check if the current memory manager is this one
    if(s_current_memory_manager == this)
       s_current_memory_manager = 0;
}
References s_current_memory_manager, and s_kernel_memory_manager.
Member Function Documentation
align()
size_t MemoryManager::align (size_t size)
Aligns the size to the chunk alignment.
Parameters
size The size to align
Returns
The aligned size
Definition at line 276 of file memorymanagement.cpp.
                                       {
  return (size / s_chunk_alignment + 1) * s_chunk_alignment;
}
References s_chunk_alignment, and size.
Referenced by handle_malloc().
free()
void MemoryManager::free (void * pointer) [static]
Frees a block of memory using the current memory manager.
Parameters
pointer The pointer to the block
Definition at line 148 of file memorymanagement.cpp.
                                      {
    // Make sure there is a memory manager
    if(s_current_memory_manager == 0)
        return;
    s_current_memory_manager->handle_free(pointer);
}
References handle_free(), and s_current_memory_manager.
from_dm_region()
void * MemoryManager::from_dm_region (uintptr_t physical_address) [static]
Converts a direct map region address to a physical address if it is in the higher region using the higher half direct map offset.
Parameters
physical_address The physical address in the direct map region
Returns
The physical address
Definition at line 345 of file memorymanagement.cpp.
                                                              {
  if(physical_address > s_hh_direct_map_offset)
    return (void*)(physical_address - s_hh_direct_map_offset);
  // Must be in the lower half
  return (void*)physical_address;
}
References physical_address, and s_hh_direct_map_offset.
Referenced by MaxOS::memory::PhysicalMemoryManager::PhysicalMemoryManager().
get_vmm()
VirtualMemoryManager * MemoryManager::get_vmm ()
Gets the active virtual memory manager
Returns
The active virtual memory manager
Definition at line 388 of file memorymanagement.cpp.
                                             {
  // Return the virtual memory manager
  return m_virtual_memory_manager;
}
handle_free()
void MemoryManager::handle_free (void * pointer)
Frees a block of memory.
Parameters
pointer A pointer to the block
Definition at line 178 of file memorymanagement.cpp.
                                             {
    // If nothing to free then return
    if(pointer == 0)
          return;
    // If block is not in the memory manager's range then return
    if((uint64_t) pointer < (uint64_t) m_first_memory_chunk || (uint64_t) pointer > (uint64_t) m_last_memory_chunk)
        return;
    // Create a new free chunk
    MemoryChunk* chunk = (MemoryChunk*)((size_t)pointer - sizeof(MemoryChunk));
    chunk -> allocated = false;
    // If there is a free chunk before this chunk then merge them
    if(chunk -> prev != 0 && !chunk -> prev -> allocated){
        // Increase the previous chunk's size and remove the current chunk from the linked list
        chunk->prev->size += chunk->size + sizeof(MemoryChunk);
        chunk -> prev -> next = chunk -> next;
        // If there is a next chunk then ensure this chunk is removed from its linked list
        if(chunk -> next != 0)
            chunk -> next -> prev = chunk->prev;
        // Chunk is now the previous chunk
        chunk = chunk -> prev;
    }
    // If there is a free chunk after this chunk then merge them
    if(chunk -> next != 0 && !chunk -> next -> allocated){
        // Increase the current chunk's size and remove the next chunk from the linked list
        chunk -> size += chunk -> next -> size + sizeof(MemoryChunk);
        chunk -> next = chunk -> next -> next;
        // Remove the just merged chunk from the linked list
        if(chunk -> next != 0)
            chunk -> next -> prev = chunk;
    }
}
References next, MaxOS::memory::MemoryChunk::prev, size, and MaxOS::memory::MemoryChunk::size.
Referenced by free(), and kfree().
handle_malloc()
void * MemoryManager::handle_malloc (size_t size)
Allocates a block of memory.
Parameters
size The size of the block to allocate
Returns
A pointer to the block, or nullptr if no block is available
Definition at line 92 of file memorymanagement.cpp.
                                              {
  MemoryChunk* result = 0;
  // Don't allocate a block of size 0
  if(size == 0)
    return 0;
  // Size must include the size of the chunk and be aligned
  size = align(size + sizeof(MemoryChunk));
  // Find the next free chunk that is big enough
  for (MemoryChunk* chunk = m_first_memory_chunk; chunk != 0 && result == 0; chunk = chunk->next) {
    if(chunk -> size > size && !chunk -> allocated)
      result = chunk;
  }
  // If there is no free chunk then expand the heap
  if(result == 0)
    result = expand_heap(size);
  // If there is not enough space to create a new chunk then just allocate the current chunk
  if(result -> size < size + sizeof(MemoryChunk) + 1) {
    result->allocated = true;
    return (void *)(((size_t)result) + sizeof(MemoryChunk));
  }
  // Create a new chunk after the current one
  MemoryChunk* temp = (MemoryChunk*)((size_t)result + sizeof(MemoryChunk) + size);
  // Set the new chunk's properties and insert it into the linked list
  temp -> allocated = false;
  temp -> size = result->size - size - sizeof(MemoryChunk);
  temp -> prev = result;
  temp -> next = result -> next;
  // If there is a chunk after the current one then set its previous to the new chunk
  if(temp -> next != 0)
    temp -> next -> prev = temp;
  // Current chunk is now allocated and is pointing to the new chunk
  result->size = size;
  result -> allocated = true;
  result->next = temp;
  // Update the last memory chunk if necessary
  if(result == m_last_memory_chunk)
    m_last_memory_chunk = temp;
  return (void*)(((size_t)result) + sizeof(MemoryChunk));
}
References align(), MaxOS::memory::MemoryChunk::allocated, next, MaxOS::memory::MemoryChunk::next, size, and MaxOS::memory::MemoryChunk::size.
Referenced by kmalloc(), and malloc().
in_higher_region()
bool MemoryManager::in_higher_region (uintptr_t virtual_address) [static]
Checks if a virtual address is in the higher region.
Parameters
virtual_address The virtual address
Returns
True if the address is in the higher region, false otherwise
Definition at line 361 of file memorymanagement.cpp.
                                                              {
  return virtual_address & (1l << 62);
}
References MaxOS::drivers::peripherals::l.
Referenced by MaxOS::memory::PhysicalMemoryManager::map(), and MaxOS::system::CPU::prepare_for_panic().
kfree()
void MemoryManager::kfree (void * pointer) [static]
Frees a block of memory using the kernel memory manager.
Parameters
pointer The pointer to the block
Definition at line 163 of file memorymanagement.cpp.
                                       {
    // Make sure there is a kernel memory manager
    if(s_kernel_memory_manager == 0)
        return;
    s_kernel_memory_manager->handle_free(pointer);
}
References handle_free(), and s_kernel_memory_manager.
Referenced by operator delete(), and operator delete[]().
kmalloc()
void * MemoryManager::kmalloc (size_t size) [static]
Allocates a block of memory using the kernel memory manager.
Parameters
size The size of the block
Returns
The pointer to the block, or nullptr if no block is available
Definition at line 76 of file memorymanagement.cpp.
                                        {
  // Make sure there is a kernel memory manager
  if(s_kernel_memory_manager == 0)
    return 0;
  return s_kernel_memory_manager->handle_malloc(size);
}
References handle_malloc(), s_kernel_memory_manager, and size.
Referenced by operator new(), and operator new[]().
malloc()
void * MemoryManager::malloc (size_t size) [static]
Allocates a block of memory using the current memory manager.
Parameters
size size of the block
Returns
a pointer to the block, 0 if no block is available or no memory manager is set
Definition at line 60 of file memorymanagement.cpp.
                                       {
    // Make sure there is somthing to do the allocation
    if(s_current_memory_manager == 0)
            return 0;
    return s_current_memory_manager->handle_malloc(size);
}
References handle_malloc(), s_current_memory_manager, and size.
memory_used()
int MemoryManager::memory_used ()
Returns the amount of memory used.
Returns
The amount of memory used
Definition at line 259 of file memorymanagement.cpp.
                               {
        int result = 0;
        // Loop through all the chunks and add up the size of the allocated chunks
        for (MemoryChunk* chunk = m_first_memory_chunk; chunk != 0; chunk = chunk->next)
            if(chunk -> allocated)
                result += chunk -> size;
        return result;
}
References MaxOS::memory::MemoryChunk::next, and size.
switch_active_memory_manager()
void MemoryManager::switch_active_memory_manager (MemoryManager * manager) [static]
Switches the active memory manager.
Parameters
manager The new memory manager
Definition at line 370 of file memorymanagement.cpp.
                                                                       {
  // Make sure there is a manager
  if(manager == nullptr)
    return;
  // Switch the address space
  asm volatile("mov %0, %%cr3" :: "r"((uint64_t)manager->m_virtual_memory_manager->get_pml4_root_address_physical()) : "memory");
  // Set the active memory manager
  s_current_memory_manager = manager;
}
References MaxOS::memory::VirtualMemoryManager::get_pml4_root_address_physical(), and s_current_memory_manager.
Referenced by MemoryManager().
to_dm_region()
void * MemoryManager::to_dm_region (uintptr_t physical_address) [static]
Converts a physical address to a direct map region address if it is in the lower region using the higher half direct map offset.
Parameters
physical_address The physical address
Returns
The direct map region address
Definition at line 330 of file memorymanagement.cpp.
                                                            {
  if(physical_address < s_higher_half_offset)
    return (void*)(physical_address + s_hh_direct_map_offset);
  // Must be in the higher half
  return (void*)physical_address;
}
References physical_address, s_hh_direct_map_offset, and s_higher_half_offset.
Referenced by MaxOS::memory::VirtualMemoryManager::VirtualMemoryManager().
to_higher_region()
void * MemoryManager::to_higher_region (uintptr_t physical_address) [static]
Converts a physical address to a higher region address if it is in the lower region using the higher half kernel offset.
Parameters
physical_address The physical address
Returns
The higher region address
Definition at line 285 of file memorymanagement.cpp.
                                                                {
  // If it's in the lower half then add the offset
  if(physical_address < s_higher_half_kernel_offset)
    return (void*)(physical_address + s_higher_half_kernel_offset);
  // Must be in the higher half
  return (void*)physical_address;
}
References physical_address, and s_higher_half_kernel_offset.
to_io_region()
void * MemoryManager::to_io_region (uintptr_t physical_address) [static]
Converts a physical address to an IO region address if it is in the lower region using the higher half memory offset.
Parameters
physical_address The physical address
Returns
The IO region address
Definition at line 315 of file memorymanagement.cpp.
                                                            {
  if(physical_address < s_higher_half_mem_offset)
    return (void*)(physical_address + s_higher_half_mem_offset);
  // Must be in the higher half
  return (void*)physical_address;
}
References physical_address, and s_higher_half_mem_offset.
to_lower_region()
void * MemoryManager::to_lower_region (uintptr_t virtual_address) [static]
Converts a virtual address to a lower region address if it is in the higher region using the higher half kernel offset.
Parameters
virtual_address The virtual address
Returns
The lower region address
Definition at line 301 of file memorymanagement.cpp.
                                                              {
  // If it's in the lower half then add the offset
  if(virtual_address > s_higher_half_kernel_offset)
    return (void*)(virtual_address - s_higher_half_kernel_offset);
  // Must be in the lower half
  return (void*)virtual_address;
}
References s_higher_half_kernel_offset.
Referenced by MaxOS::memory::VirtualMemoryManager::VirtualMemoryManager().
Member Data Documentation
previous_memory_manager
MemoryManager* MaxOS::memory::MemoryManager::previous_memory_manager
Definition at line 58 of file memorymanagement.h.
s_chunk_alignment
const size_t MaxOS::memory::MemoryManager::s_chunk_alignment { 0x10 } [static]
Definition at line 56 of file memorymanagement.h.
Referenced by align().
s_current_memory_manager
MemoryManager * MemoryManager::s_current_memory_manager = 0 [static]
Definition at line 46 of file memorymanagement.h.
Referenced by free(), malloc(), switch_active_memory_manager(), and ~MemoryManager().
s_hh_direct_map_offset
const uint64_t MaxOS::memory::MemoryManager::s_hh_direct_map_offset { s_higher_half_offset + PhysicalMemoryManager::s_page_size } [static]
Definition at line 53 of file memorymanagement.h.
Referenced by from_dm_region(), MaxOS::memory::PhysicalMemoryManager::PhysicalMemoryManager(), to_dm_region(), and MaxOS::memory::VirtualMemoryManager::VirtualMemoryManager().
s_higher_half_kernel_offset
const uint64_t MaxOS::memory::MemoryManager::s_higher_half_kernel_offset { 0xFFFFFFFF80000000 } [static]
Definition at line 49 of file memorymanagement.h.
Referenced by to_higher_region(), and to_lower_region().
s_higher_half_mem_offset
const uint64_t MaxOS::memory::MemoryManager::s_higher_half_mem_offset { 0xFFFF800000000000 } [static]
Definition at line 50 of file memorymanagement.h.
Referenced by to_io_region().
s_higher_half_mem_reserved
const uint64_t MaxOS::memory::MemoryManager::s_higher_half_mem_reserved { 0x280000000 } [static]
Definition at line 51 of file memorymanagement.h.
s_higher_half_offset
const uint64_t MaxOS::memory::MemoryManager::s_higher_half_offset { s_higher_half_mem_offset + s_higher_half_mem_reserved} [static]
Definition at line 52 of file memorymanagement.h.
Referenced by to_dm_region().
s_kernel_memory_manager
MemoryManager * MemoryManager::s_kernel_memory_manager = 0 [static]
Definition at line 47 of file memorymanagement.h.
Referenced by kfree(), kmalloc(), and ~MemoryManager().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/memory/memorymanagement.h
/home/runner/work/MaxOS/MaxOS/kernel/src/memory/memorymanagement.cpp