MaxOS::filesystem::partition::MSDOSPartition Class Reference
Handles mounting of partitions documented in an MSDOS partition table.
#include <msdos.h>
Static Public Member Functions
static void mount_partitions (drivers::disk::Disk *disk)
read the partition table of a given hard disk
Detailed Description
Handles mounting of partitions documented in an MSDOS partition table.
Todo
Todo Abstract some of this into a base class and use it for GPT and other partition tables
Definition at line 348 of file msdos.h.
Member Function Documentation
mount_partitions()
void MSDOSPartition::mount_partitions (drivers::disk::Disk * disk) [static]
read the partition table of a given hard disk
Parameters
disk The hard disk to read the partition table from
Definition at line 23 of file msdos.cpp.
                                                {
    // Read the MBR from the hard disk
    MasterBootRecord mbr = {};
    buffer_t mbr_buffer(&mbr, sizeof(MasterBootRecord));
    disk->read(0, &mbr_buffer);
    // Check if the magic number is correct
    if (mbr.magic != 0xAA55) {
        Logger::WARNING() << "Could not find valid MBR on disk 0x" << (uint64_t) disk << "\n";
        return;
    }
    // Get the VFS
    VirtualFileSystem *vfs = VirtualFileSystem::current_file_system();
    // Loop through the primary partitions
    for (auto &entry: mbr.primary_partition) {
        // Empty entry
        if (entry.type == 0)
            continue;
        Logger::DEBUG() << "Partition 0x" << (uint64_t) entry.type << " at 0x" << (uint64_t) entry.start_LBA << ": ";
        // Create a file system for the partition
        switch ((PartitionType) entry.type) {
            case PartitionType::EMPTY:
                Logger::Out() << "Empty partition\n";
                break;
            case PartitionType::FAT32:
                Logger::Out() << "FAT32 partition\n";
                vfs->mount_filesystem(new Fat32FileSystem(disk, entry.start_LBA));
                break;
            case PartitionType::LINUX_EXT2:
                Logger::Out() << "EXT2 partition\n";
                vfs->mount_filesystem(new ext2::Ext2FileSystem(disk, entry.start_LBA));
                break;
            default:
                Logger::Out() << "Unknown or unimplemented partition type: 0x" << (uint64_t) entry.type << "\n";
        }
    }
}
References MaxOS::filesystem::VirtualFileSystem::current_file_system(), Logger::DEBUG(), Logger::Out(), MaxOS::drivers::disk::Disk::read(), and Logger::WARNING().
Referenced by MaxOS::drivers::disk::IntegratedDriveElectronicsController::activate().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/partition/msdos.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/partition/msdos.cpp