MaxOS::gui::Window Class Reference
A window that can be moved and resized and contains a widget.
#include <window.h>
Public Member Functions
Window (int32_t left, int32_t top, uint32_t width, uint32_t height, const string &title_text)
Construct a new Window object at a specific position and size (relative to the screen) with a title.
Window (Widget *contained_widget, const string &title_text)
Construct a new Window object that contains a specific widget with a title. The window sizes itself to fit the widget.
void draw_self (common::GraphicsContext *gc, common::Rectangle< int32_t > &area) override
Draws the window and its children.
void add_child (Widget *child) override
Adds a child to the window.
drivers::peripherals::MouseEventHandler * on_mouse_button_pressed (uint32_t x, uint32_t y, uint8_t button) override
Handles the mouse button being pressed.
Public Member Functions inherited from MaxOS::gui::CompositeWidget
CompositeWidget (int32_t left, int32_t top, uint32_t width, uint32_t height)
Construct a new Composite Widget object at a specific position and size.
void draw (common::GraphicsContext *gc, common::Rectangle< int32_t > &area) override
Draws a section of the widget and its m_children.
void on_mouse_enter_widget (uint32_t to_x, uint32_t to_y) override
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
void on_mouse_leave_widget (uint32_t from_x, uint32_t from_y) override
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
void on_mouse_move_widget (uint32_t from_x, uint32_t from_y, uint32_t to_x, uint32_t to_y) override
Passes the event to the child that the mouse is over, also generates a leave/enter event for children.
void on_mouse_button_released (uint32_t x, uint32_t y, uint8_t button) override
Passes the event to the child that the mouse is over. (Event handling should be done by the derived class)
Public Member Functions inherited from MaxOS::gui::Widget
Widget ()
Construct a new Widget object.
Widget (int32_t left, int32_t top, uint32_t width, uint32_t height)
Construct a new Widget object at a specific position and size.
void invalidate ()
Invalidates the entire widget. This forces the widget to be redrawn on the next screen update.
virtual void invalidate (common::Rectangle< int32_t > &area)
Invalidates a specific area of the widget. This forces that part of the screen to be redrawn on the next screen update.
virtual common::Coordinates absolute_coordinates (common::Coordinates coordinates)
Get the absolute coordinates of the widget (relative to the screen)
virtual bool contains_coordinate (uint32_t x, uint32_t y)
Check if the widget contains a specific coordinate.
common::Rectangle< int32_t > position ()
Get the position of the widget.
void move (int32_t left, int32_t top)
Set the position of the widget, and invalidate the old and new positions so they are redrawn.
void resize (int32_t width, int32_t height)
Set the size of the widget, and invalidate the old and new positions so they are redrawn.
void focus ()
Set the current focused widget to be this widget.
virtual void on_focus ()
Handles the event when the widget is focussed.
virtual void on_focus_lost ()
Handles the event when the widget is unfocused.
void bring_to_front ()
Brings this widget to the front of the screen.
Public Member Functions inherited from MaxOS::drivers::peripherals::KeyboardEventHandler
common::Event< KeyboardEvents > * on_event (common::Event< KeyboardEvents > *) override
Handle the trigger of an event.
virtual void on_key_down (KeyCode, const KeyboardState &)
Handle the key down event.
virtual void on_key_up (KeyCode, const KeyboardState &)
Handle the key up event.
Public Member Functions inherited from MaxOS::common::EventHandler< KeyboardEvents >
virtual Event< KeyboardEvents > * on_event (Event< KeyboardEvents > *event)
This function is called when an event is raised.
Public Attributes
uint8_t frame_thickness { 5 }
How thick the bar around the window is.
uint8_t title_bar_height { 10 }
How large the bar at the top of the window is.
common::Colour area_colour
The background colour of the window inner area.
common::Colour frame_colour
The colour of the bar around the window.
common::Colour frame_border_colour
The colour of the border around the bar around the window.
Additional Inherited Members
Protected Member Functions inherited from MaxOS::gui::CompositeWidget
void draw (common::GraphicsContext *gc, common::Rectangle< int32_t > &area, common::Vector< Widget * >::iterator start)
Draws a section of the widget and the m_children after a specific child.
Protected Member Functions inherited from MaxOS::gui::Widget
virtual void set_focus (Widget *)
Sets the widget that is currently focussed.
virtual void bring_to_front (Widget *)
Brings a specific widget to the front of the screen.
Protected Attributes inherited from MaxOS::gui::CompositeWidget
common::Vector< Widget * > m_children
Widgets contained within this composite widget.
Protected Attributes inherited from MaxOS::gui::Widget
common::Rectangle< int32_t > m_position
The position and size of the widget (relative to its parent)
Widget * m_parent { nullptr }
The widget that owns this widget.
bool m_valid { false }
Is the widget drawn to the screen and up to date.
uint32_t m_min_width { 5 }
The smallest m_width the widget can be resized to.
uint32_t m_min_height { 5 }
The smallest m_height the widget can be resized to.
uint32_t m_max_width { 0x8FFFFFFF }
The largest m_width the widget can be resized to.
uint32_t m_max_height { 0x8FFFFFFF }
The largest m_height the widget can be resized to.
Detailed Description
A window that can be moved and resized and contains a widget.
Definition at line 24 of file window.h.
Constructor & Destructor Documentation
Window() [1/2]
Window::Window (int32_t left, int32_t top, uint32_t width, uint32_t height, const string & title_text)
Construct a new Window object at a specific position and size (relative to the screen) with a title.
Parameters
left How many pixels from the left of the screen the window is
top How many pixels from the top of the screen the window is
width How many pixels wide the window is
height How many pixels tall the window is
title_text The text to display in the title bar of the window
Definition at line 27 of file window.cpp.
: CompositeWidget(left, top, width, height),
  m_title(0, -(10 + 5) + 2, width - 2 * 5, 10 + 5 - 3, title_text),
  m_mover(this),
  m_resizer_top(this),
  m_resizer_bottom(this),
  m_resizer_left(this),
  m_resizer_right(this),
  m_resizer_top_left(this),
  m_resizer_top_right(this),
  m_resizer_bottom_left(this),
  m_resizer_bottom_right(this)
{
    // Set the sizing
    m_min_width = 2 * frame_thickness;
    m_min_height = 2 * frame_thickness + title_bar_height;
    // Set the colours
    area_colour = Colour(0xff, 0xff, 0xff); // White
    frame_border_colour = Colour(0x00, 0x00, 0x00); // Black
    frame_colour = Colour(0x57, 0x57, 0x57); // Davy's Grey
    m_title.foreground_colour = Colour(0xff, 0xff, 0xff); // White
    m_title.background_colour = frame_colour;
    // Add the title to the window
    Window::add_child(&m_title);
}
References add_child(), area_colour, MaxOS::gui::widgets::Text::background_colour, MaxOS::gui::widgets::Text::foreground_colour, frame_border_colour, frame_colour, frame_thickness, MaxOS::gui::Widget::m_min_height, MaxOS::gui::Widget::m_min_width, and title_bar_height.
Window() [2/2]
Window::Window (Widget * contained_widget, const string & title_text)
Construct a new Window object that contains a specific widget with a title. The window sizes itself to fit the widget.
Parameters
contained_widget The widget to contain within the window
title_text The text to display in the title bar of the window
Definition at line 63 of file window.cpp.
: CompositeWidget(0, 0, contained_widget->position().width + 2 * 5 + 2, contained_widget->position().height + 2 * 5 + 10 + 2),
  m_title(0, -(10 + 5) + 2, contained_widget->position().width, 10 + 5 - 3, title_text),
  m_mover(this),
  m_resizer_top(this),
  m_resizer_bottom(this),
  m_resizer_left(this),
  m_resizer_right(this),
  m_resizer_top_left(this),
  m_resizer_top_right(this),
  m_resizer_bottom_left(this),
  m_resizer_bottom_right(this)
{
    // Set the sizing
    m_min_width = 2 * frame_thickness;
    m_min_height = 2 * frame_thickness + title_bar_height;
    // Set the colours
    area_colour = Colour(0xff, 0xff, 0xff); // White
    frame_border_colour = Colour(0x00, 0x00, 0x00); // Black
    frame_colour = Colour(0x57, 0x57, 0x57); // Davy's Grey
    m_title.foreground_colour = Colour(0xff, 0xff, 0xff); // White
    m_title.background_colour = frame_colour;
    // Add the title to the window
    Window::add_child(&m_title);
    Window::add_child(contained_widget);
}
References add_child(), area_colour, MaxOS::gui::widgets::Text::background_colour, MaxOS::gui::widgets::Text::foreground_colour, frame_border_colour, frame_colour, frame_thickness, MaxOS::gui::Widget::m_min_height, MaxOS::gui::Widget::m_min_width, and title_bar_height.
Member Function Documentation
add_child()
void Window::add_child (Widget * child) [override], [virtual]
Adds a child to the window.
Parameters
child The child to add.
Reimplemented from MaxOS::gui::CompositeWidget.
Definition at line 220 of file window.cpp.
                                    {
    // If there is a child to add
    if (child != nullptr) {
        // Change the position of the child to be inside the window contents
        Rectangle<int32_t> child_position = child->position();
        child->move(child_position.left + frame_thickness + 1,
                    child_position.top + frame_thickness + title_bar_height + 1);
    }
    // Add the child to the window
    CompositeWidget::add_child(child);
}
References MaxOS::gui::CompositeWidget::add_child(), frame_thickness, MaxOS::common::Rectangle< Type >::left, title_bar_height, and MaxOS::common::Rectangle< Type >::top.
Referenced by Window(), and Window().
draw_self()
void Window::draw_self (common::GraphicsContext * gc, common::Rectangle< int32_t > & area) [override], [virtual]
Draws the window and its children.
Parameters
gc The graphics context to draw on.
area The area to draw
Reimplemented from MaxOS::gui::CompositeWidget.
Definition at line 154 of file window.cpp.
                                                                                {
    // Get the positioning of the window
    Coordinates window_absolute_position = CompositeWidget::absolute_coordinates(Coordinates(0, 0));
    Rectangle<int32_t> window_position = this->position();
    int32_t window_x = window_absolute_position.first;
    int32_t window_y = window_absolute_position.second;
    // Create an area for the window contents
    Rectangle<int32_t> window_contents_area(frame_thickness, frame_thickness + title_bar_height,
                                            window_position.width - 2 * frame_thickness,
                                            window_position.height - 2 * frame_thickness - title_bar_height);
    // Draw the window contents if they are in the area to draw
    if (window_contents_area.intersects(area)) {
        Rectangle<int32_t> contents_drawable = window_contents_area.intersection(area);
        gc->fill_rectangle(contents_drawable.left + window_x, contents_drawable.top + window_y,
                           contents_drawable.left + contents_drawable.width + window_x,
                           contents_drawable.top + contents_drawable.height + window_y, area_colour);
    }
    // Draw the frame if it is in the area to draw
    Rectangle<int32_t> window_frame_top_area(frame_thickness, 0, window_position.width - 2 * frame_thickness,
                                             frame_thickness + title_bar_height);
    if (window_frame_top_area.intersects(area)) {
        Rectangle<int32_t> frame_drawable = window_frame_top_area.intersection(area);
        gc->fill_rectangle(frame_drawable.left + window_x, frame_drawable.top + window_y,
                           frame_drawable.left + frame_drawable.width + window_x,
                           frame_drawable.top + frame_drawable.height + window_y, frame_colour);
    }
    // Draw the bottom of the window frame
    Rectangle<int32_t> window_frame_bottom_area(frame_thickness, window_position.height - frame_thickness,
                                                window_position.width - 2 * frame_thickness, frame_thickness);
    if (window_frame_bottom_area.intersects(area)) {
        Rectangle<int32_t> bottom_drawable = window_frame_bottom_area.intersection(area);
        gc->fill_rectangle(window_x + bottom_drawable.left, window_y + bottom_drawable.top,
                           window_x + bottom_drawable.left + bottom_drawable.width,
                           window_y + bottom_drawable.top + bottom_drawable.height, frame_colour);
    }
    // Draw the left of the window frame
    Rectangle<int32_t> window_frame_left_area(0, 0, frame_thickness, window_position.height);
    if (window_frame_left_area.intersects(area)) {
        Rectangle<int32_t> left_drawable = window_frame_left_area.intersection(area);
        gc->fill_rectangle(window_x + left_drawable.left, window_y + left_drawable.top,
                           window_x + left_drawable.left + left_drawable.width,
                           window_y + left_drawable.top + left_drawable.height, frame_colour);
    }
    // Draw the right of the window frame
    Rectangle<int32_t> window_frame_right_area(window_position.width - frame_thickness, 0, frame_thickness,
                                               window_position.height);
    if (window_frame_right_area.intersects(area)) {
        Rectangle<int32_t> right_drawable = window_frame_right_area.intersection(area);
        gc->fill_rectangle(window_x + right_drawable.left, window_y + right_drawable.top,
                           window_x + right_drawable.left + right_drawable.width,
                           window_y + right_drawable.top + right_drawable.height, frame_colour);
    }
}
References MaxOS::gui::Widget::absolute_coordinates(), area_colour, frame_colour, frame_thickness, MaxOS::common::Rectangle< Type >::height, MaxOS::common::Rectangle< Type >::intersection(), MaxOS::common::Rectangle< Type >::intersects(), MaxOS::common::Rectangle< Type >::left, MaxOS::gui::Widget::position(), title_bar_height, MaxOS::common::Rectangle< Type >::top, and MaxOS::common::Rectangle< Type >::width.
on_mouse_button_pressed()
MouseEventHandler * Window::on_mouse_button_pressed (uint32_t mouse_x, uint32_t mouse_y, uint8_t button) [override], [virtual]
Handles the mouse button being pressed.
Parameters
mouse_x The x coordinate of the mouse.
mouse_y The y coordinate of the mouse.
button The button that is pressed.
Returns
The MouseEventHandler of the widget that will handle the event, nullptr otherwise.
Reimplemented from MaxOS::gui::CompositeWidget.
Definition at line 103 of file window.cpp.
                                                                                                     {
    // Pass the mouse event to the children
    drivers::peripherals::MouseEventHandler* child_result = CompositeWidget::on_mouse_button_pressed(mouse_x, mouse_y, button);
    Rectangle<int32_t> window_position = position();
    // Bring the window to the front
    bring_to_front();
    // Convert the mouse coordinates to an int32_t
    auto x = (int32_t) mouse_x;
    auto y = (int32_t) mouse_y;
    if (x <= frame_thickness) {
        if (y <= frame_thickness)
            return &m_resizer_top_left;
        else if (y < window_position.height - frame_thickness)
            return &m_resizer_left;
        else
            return &m_resizer_bottom_left;
    } else if (x < window_position.width - frame_thickness) {
        if (y <= frame_thickness)
            return &m_resizer_top;
        else if (y < frame_thickness + title_bar_height)
            return &m_mover;
        else if (y >= window_position.height - frame_thickness)
            return &m_resizer_bottom;
    } else {
        if (y <= frame_thickness)
            return &m_resizer_top_right;
        else if (y < window_position.height - frame_thickness)
            return &m_resizer_right;
        else
            return &m_resizer_bottom_right;
    }
    return child_result;
}
References MaxOS::gui::Widget::bring_to_front(), frame_thickness, MaxOS::common::Rectangle< Type >::height, MaxOS::gui::CompositeWidget::on_mouse_button_pressed(), MaxOS::gui::Widget::position(), title_bar_height, and MaxOS::common::Rectangle< Type >::width.
Member Data Documentation
area_colour
common::Colour MaxOS::gui::Window::area_colour
The background colour of the window inner area.
Definition at line 46 of file window.h.
Referenced by draw_self(), Window(), and Window().
frame_border_colour
common::Colour MaxOS::gui::Window::frame_border_colour
The colour of the border around the bar around the window.
Definition at line 48 of file window.h.
Referenced by Window(), and Window().
frame_colour
common::Colour MaxOS::gui::Window::frame_colour
The colour of the bar around the window.
Definition at line 47 of file window.h.
Referenced by draw_self(), Window(), and Window().
frame_thickness
uint8_t MaxOS::gui::Window::frame_thickness { 5 }
How thick the bar around the window is.
Definition at line 43 of file window.h.
{ 5 };
Referenced by add_child(), draw_self(), on_mouse_button_pressed(), Window(), and Window().
title_bar_height
uint8_t MaxOS::gui::Window::title_bar_height { 10 }
How large the bar at the top of the window is.
Definition at line 44 of file window.h.
{ 10 };
Referenced by add_child(), draw_self(), on_mouse_button_pressed(), Window(), and Window().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/window.h
/home/runner/work/MaxOS/MaxOS/kernel/src/gui/window.cpp