MaxOS::filesystem::format::ext2::InodeHandler Class Reference
Simplfies the management of an inode & its blocks.
#include <ext2.h>
Public Member Functions
InodeHandler (Ext2Volume *volume, uint32_t inode)
Construct a new Inode Handler object. Reads the inode and caches the block pointers.
size_t size () const
read the size upper and lower into a single size_t
void set_size (size_t size)
store the size of the inode data. (does not write to disk)
size_t grow (size_t amount, bool flush=true)
Increase the size of the inode's storage capacity by allocating new blocks.
void save ()
Writes the inode meta data to disk.
void free ()
Marks this inode's blocks as free and then the inode as free.
Public Attributes
uint32_t inode_number
The index of the inode.
inode_t inode
The inode metadata for this file/directory.
common::Vector< uint32_t > block_cache
All the blocks used by this inode.
Detailed Description
Simplfies the management of an inode & its blocks.
Definition at line 372 of file ext2.h.
Constructor & Destructor Documentation
InodeHandler()
InodeHandler::InodeHandler (Ext2Volume * volume, uint32_t inode_index)
Construct a new Inode Handler object. Reads the inode and caches the block pointers.
Parameters
volume The volume the inode belongs to
inode_index The inode index
Definition at line 509 of file ext2.cpp.
        : m_volume(volume),
        inode_number(inode_index),
        inode(m_volume->read_inode(inode_number)) {
    // Read the block pointers
    for(uint32_t direct_pointer = 0; direct_pointer < 12; ++direct_pointer)
        if(inode.block_pointers[direct_pointer])
            block_cache.push_back(inode.block_pointers[direct_pointer]);
    buffer_t buffer(m_volume->block_size);
    parse_indirect(1, inode.l1_indirect, &buffer);
    parse_indirect(2, inode.l2_indirect, &buffer);
    parse_indirect(3, inode.l3_indirect, &buffer);
}
References block_cache, MaxOS::filesystem::format::ext2::Ext2Volume::block_size, inode, and MaxOS::common::Vector< Type >::push_back().
Member Function Documentation
free()
void InodeHandler::free ()
Marks this inode's blocks as free and then the inode as free.
Definition at line 705 of file ext2.cpp.
                        {
    m_volume->ext2_lock.lock();
    // Free the inode
    m_volume->free_blocks(block_cache);
    m_volume->free_inode(inode_number);
    m_volume->ext2_lock.unlock();
}
References block_cache, MaxOS::filesystem::format::ext2::Ext2Volume::ext2_lock, MaxOS::filesystem::format::ext2::Ext2Volume::free_blocks(), MaxOS::filesystem::format::ext2::Ext2Volume::free_inode(), inode_number, MaxOS::common::Spinlock::lock(), and MaxOS::common::Spinlock::unlock().
grow()
size_t InodeHandler::grow (size_t amount, bool flush = true)
Increase the size of the inode's storage capacity by allocating new blocks.
Parameters
amount The amount to grow to in bytes
flush Save the newly allocated chunks to disk, defaults to true
Returns
The new toatal size of the file (size() + amount)
Todo
Todo Should this return size() instead?
Definition at line 675 of file ext2.cpp.
                                                   {
    // Nothing to grow
    if(amount <= 0)
        return size();
    // Allocate new blocks
    auto blocks = m_volume->allocate_blocks(m_volume->bytes_to_blocks(amount));
    ASSERT(blocks[0] != 0, "Failed to allocate new blocks for file");
    // Save the changes
    store_blocks(blocks);
    set_size(size() + amount);
    if(flush)
        save();
    return size() + amount;
}
References MaxOS::filesystem::format::ext2::Ext2Volume::allocate_blocks(), ASSERT, MaxOS::filesystem::format::ext2::Ext2Volume::bytes_to_blocks(), save(), set_size(), and size().
Referenced by MaxOS::filesystem::format::ext2::Ext2File::write().
save()
void InodeHandler::save ()
Writes the inode meta data to disk.
Definition at line 697 of file ext2.cpp.
                        {
    m_volume->write_inode(inode_number, &inode);
}
References inode, inode_number, and MaxOS::filesystem::format::ext2::Ext2Volume::write_inode().
Referenced by grow(), and MaxOS::filesystem::format::ext2::Ext2File::write().
set_size()
void InodeHandler::set_size (size_t size)
store the size of the inode data. (does not write to disk)
Parameters
size The new size
Definition at line 537 of file ext2.cpp.
                                       {
    inode.size_lower = (uint32_t) (size & 0xFFFFFFFFULL);
    inode.size_upper = (uint32_t) (size >> 32);
}
References inode, and size().
Referenced by grow().
size()
size_t InodeHandler::size () const
read the size upper and lower into a single size_t
Returns
The size of the inode data (not the inode itself)
Definition at line 529 of file ext2.cpp.
                                {
    return ((size_t) inode.size_upper << 32) | (size_t) inode.size_lower;
}
References inode.
Referenced by MaxOS::filesystem::format::ext2::Ext2File::Ext2File(), grow(), and set_size().
Member Data Documentation
block_cache
common::Vector<uint32_t> MaxOS::filesystem::format::ext2::InodeHandler::block_cache
All the blocks used by this inode.
Definition at line 387 of file ext2.h.
Referenced by free(), InodeHandler(), MaxOS::filesystem::format::ext2::Ext2File::read(), MaxOS::filesystem::format::ext2::Ext2Directory::read_from_disk(), and MaxOS::filesystem::format::ext2::Ext2File::write().
inode
inode_t MaxOS::filesystem::format::ext2::InodeHandler::inode
The inode metadata for this file/directory.
Definition at line 386 of file ext2.h.
Referenced by InodeHandler(), save(), set_size(), size(), and MaxOS::filesystem::format::ext2::Ext2File::write().
inode_number
uint32_t MaxOS::filesystem::format::ext2::InodeHandler::inode_number
The index of the inode.
Definition at line 385 of file ext2.h.
Referenced by MaxOS::filesystem::format::ext2::Ext2Directory::create_subdirectory(), free(), and save().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/format/ext2.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/format/ext2.cpp