MaxOS::gui::widgets::ButtonEventHandler Class Reference
Handles button events.
#include <button.h>
Public Member Functions
ButtonEventHandler ()
~ButtonEventHandler ()
common::Event< ButtonEvents > * on_event (common::Event< ButtonEvents > *) override
Handles the button events.
virtual void on_button_pressed (Button *source)
Handles the button pressed event.
virtual void on_button_released (Button *source)
Handles the button released event.
Public Member Functions inherited from MaxOS::common::EventHandler< ButtonEvents >
EventHandler ()
~EventHandler ()
virtual Event< ButtonEvents > * on_event (Event< ButtonEvents > *event)
This function is called when an event is raised.
Detailed Description
Handles button events.
Definition at line 56 of file button.h.
Constructor & Destructor Documentation
ButtonEventHandler()
ButtonEventHandler::ButtonEventHandler () [default]
~ButtonEventHandler()
ButtonEventHandler::~ButtonEventHandler () [default]
Member Function Documentation
on_button_pressed()
void ButtonEventHandler::on_button_pressed (Button * source) [virtual]
Handles the button pressed event.
Parameters
source The source of the event
Definition at line 44 of file button.cpp.
                                                  {
}
Referenced by on_event().
on_button_released()
void ButtonEventHandler::on_button_released (Button * source) [virtual]
Handles the button released event.
Parameters
source The source of the event
Definition at line 53 of file button.cpp.
                                                   {
}
Referenced by on_event().
on_event()
Event< ButtonEvents > * ButtonEventHandler::on_event (common::Event< ButtonEvents > * event) [override]
Handles the button events.
Parameters
event The event to handle
Definition at line 23 of file button.cpp.
                                                                            {
    switch (event->type) {
        case ButtonEvents::PRESSED:
            on_button_pressed(((ButtonPressedEvent*) event)->source);
            break;
        case ButtonEvents::RELEASED:
            on_button_released(((ButtonReleasedEvent*) event)->source);
            break;
    }
    return event;
}
References on_button_pressed(), on_button_released(), MaxOS::gui::widgets::PRESSED, MaxOS::gui::widgets::RELEASED, and source.
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/widgets/button.h
/home/runner/work/MaxOS/MaxOS/kernel/src/gui/widgets/button.cpp