MaxOS::common::EventManager< EventType > Class Template Reference
Manages the m_handlers for a type of event, raises events and calls the m_handlers.
#include <eventHandler.h>
Public Member Functions
EventManager ()
~EventManager ()
void connect_event_handler (EventHandler< EventType > *handler)
Connect an event handler to the event manager if it is not already connected.
void disconnect_event_handler (EventHandler< EventType > *handler)
Disconnect an event handler from the event manager if it is connected.
Vector< Event< EventType > * > raise_event (Event< EventType > *event)
Calls the on_event function of all the event m_handlers connected to the event manager and returns a list of the results.
Protected Attributes
Vector< EventHandler< EventType > * > m_handlers
Detailed Description
template<typename EventType>
class MaxOS::common::EventManager< EventType >
Manages the m_handlers for a type of event, raises events and calls the m_handlers.
Template Parameters
EventType The type of event
Definition at line 56 of file eventHandler.h.
Constructor & Destructor Documentation
EventManager()
template<typename EventType >
MaxOS::common::EventManager< EventType >::EventManager
Definition at line 99 of file eventHandler.h.
                                                                           {
        }
 EventManager()
template<typename EventType >
MaxOS::common::EventManager< EventType >::~EventManager
Definition at line 103 of file eventHandler.h.
                                                                            {
        }
Member Function Documentation
connect_event_handler()
template<typename EventType >
void MaxOS::common::EventManager< EventType >::connect_event_handler (EventHandler< EventType > * handler)
Connect an event handler to the event manager if it is not already connected.
Template Parameters
EventType The type of event
Parameters
handler The event handler to connect
Definition at line 114 of file eventHandler.h.
                                                                                                                         {
            // If the handler is already connected, return
            if(m_handlers.find(handler) != m_handlers.end()) {
                return;
            }
            m_handlers.push_back(handler);
        }
Referenced by MaxOS::net::TransmissionControlProtocolHandler::Bind(), MaxOS::net::EthernetFrameHandler::EthernetFrameHandler(), and kernelMain().
disconnect_event_handler()
template<typename EventType >
void MaxOS::common::EventManager< EventType >::disconnect_event_handler (EventHandler< EventType > * handler)
Disconnect an event handler from the event manager if it is connected.
Template Parameters
EventType The type of event
Parameters
handler The event handler to disconnect
Definition at line 130 of file eventHandler.h.
                                                                                                                            {
            // If the handler is not connected, return
            if(m_handlers.find(handler) == m_handlers.end()) {
                return;
            }
            m_handlers.erase(handler);
        }
raise_event()
template<typename EventType >
Vector< Event< EventType > * > MaxOS::common::EventManager< EventType >::raise_event (Event< EventType > * event)
Calls the on_event function of all the event m_handlers connected to the event manager and returns a list of the results.
Template Parameters
EventType The type of event
Parameters
event The event to raise
Returns
A list of the results of the event m_handlers
Definition at line 146 of file eventHandler.h.
                                                                                                                            {
            // Store a list of the results of the event handlers
            Vector<Event<EventType>*> results;
            for(auto& handler : m_handlers) {
                results.push_back(handler->on_event(event));
            }
            // Free the memory used by the event
            delete event;
            return results;
        }
Member Data Documentation
m_handlers
template<typename EventType >
Vector<EventHandler<EventType>*> MaxOS::common::EventManager< EventType >::m_handlers [protected]
Definition at line 59 of file eventHandler.h.
Referenced by MaxOS::net::UserDatagramProtocolHandler::Bind().
The documentation for this class was generated from the following file:
/home/runner/work/MaxOS/MaxOS/kernel/include/common/eventHandler.h