MaxOS::hardwarecommunication::LocalAPIC Class Reference
Handles the local APIC for the current core.
#include <apic.h>
Public Member Functions
LocalAPIC ()
Construct a new Local APIC object and map the APIC base address to the higher half if needed as well as enabling the APIC.
uint32_t read (uint32_t reg) const
read a value from the apic register using the MSR or memory I/O depending on the local apic version
void write (uint32_t reg, uint32_t value) const
write a value to the apic register using the MSR or memory I/O depending on the local apic version
uint32_t id () const
Get the id of the local apic.
void send_eoi () const
Acknowledge that the interrupt has been handled, allowing the PIC to process the next interrupt.
void send_init (uint8_t apic_id, bool assert) const
send the init IPI to another apic
void send_startup (uint8_t apic_id, uint8_t vector) const
send the start up IPI to another apic
Detailed Description
Handles the local APIC for the current core.
Definition at line 24 of file apic.h.
Constructor & Destructor Documentation
LocalAPIC()
LocalAPIC::LocalAPIC ()
Construct a new Local APIC object and map the APIC base address to the higher half if needed as well as enabling the APIC.
Definition at line 21 of file apic.cpp.
                     {
    // Get the APIC base address
    uint64_t msr_info = CPU::read_msr(0x1B);
    m_apic_base = msr_info & 0xFFFFF000;
    // Reserve the base address once
    static bool bsp_setup = false;
    if(!bsp_setup)
        PhysicalMemoryManager::s_current_manager->reserve(m_apic_base);
    // Check if the APIC supports x2APIC
    uint32_t ignored, xleaf, x2leaf;
    CPU::cpuid(0x01, &ignored, &ignored, &x2leaf, &xleaf);
    if (x2leaf & (1 << 21)) {
        // Enable x2APIC
        m_x2apic = true;
        msr_info |= (1 << 10);
        CPU::write_msr(0x1B, msr_info);
        Logger::DEBUG() << "CPU supports x2APIC\n";
    } else if (xleaf & (1 << 9)) {
        m_x2apic = false;
        Logger::DEBUG() << "CPU supports xAPIC\n";
        // Map the APIC base address to the higher half
        m_apic_base_high = (uint64_t) PhysicalMemoryManager::to_io_region(m_apic_base);
        PhysicalMemoryManager::s_current_manager->map((physical_address_t*) m_apic_base, (virtual_address_t*) m_apic_base_high, PRESENT | WRITE);
        Logger::DEBUG() << "APIC Base: phy=0x" << m_apic_base << ", virt=0x" << m_apic_base_high << "\n";
    } else {
        ASSERT(false, "CPU does not support xAPIC");
    }
    if (!(msr_info & (1 << 11))) {
        Logger::WARNING() << "APIC is not enabled\n";
        return;
    }
    // Enable the APIC
    write(0xF0, (1 << 8) | 0x100);
    bsp_setup = true;
    Logger::DEBUG() << "APIC Enabled\n";
}
References ASSERT, MaxOS::system::CPU::cpuid(), MaxOS::Logger::DEBUG(), MaxOS::memory::PhysicalMemoryManager::map(), MaxOS::memory::PRESENT, MaxOS::system::CPU::read_msr(), MaxOS::memory::PhysicalMemoryManager::reserve(), MaxOS::memory::PhysicalMemoryManager::s_current_manager, MaxOS::memory::PhysicalMemoryManager::to_io_region(), MaxOS::Logger::WARNING(), write(), MaxOS::memory::WRITE, and MaxOS::system::CPU::write_msr().
Member Function Documentation
id()
uint32_t LocalAPIC::id () const
Get the id of the local apic.
Returns
The id of the local apic
Definition at line 108 of file apic.cpp.
                             {
    // Read the id
    uint32_t id = read(0x20);
    // Return the id
    return m_x2apic ? id : (id >> 24);
}
References id(), and read().
Referenced by id().
read()
uint32_t LocalAPIC::read (uint32_t reg) const
read a value from the apic register using the MSR or memory I/O depending on the local apic version
Parameters
reg The register to read
Returns
The value of the register
Definition at line 76 of file apic.cpp.
                                           {
    // If x2APIC is enabled I/O is done through the MSR
    if (m_x2apic)
        return (uint32_t) CPU::read_msr((reg >> 4) + 0x800);
    return *(volatile uint32_t*) ((uintptr_t) m_apic_base_high + reg);
}
References MaxOS::system::CPU::read_msr().
Referenced by id(), send_init(), and send_startup().
send_eoi()
void LocalAPIC::send_eoi () const
Acknowledge that the interrupt has been handled, allowing the PIC to process the next interrupt.
Definition at line 120 of file apic.cpp.
                               {
    write(0xB0, 0);
}
References write().
send_init()
void LocalAPIC::send_init (uint8_t apic_id, bool assert) const
send the init IPI to another apic
Parameters
apic_id The id of the apic to send to
assert Is this an assert code (drive / release the signal)
Definition at line 131 of file apic.cpp.
                                                            {
    uint32_t icr_low = 0;
    // Delivery mode = INIT (101b at bits 8-10)
    icr_low |= (0b101 << 8);
    // Level (bit 14): 1 = assert, 0 = de-assert
    if (assert)
        icr_low |= (1 << 14);
    // Trigger mode: Level = 1
    icr_low |= (1 << 15);
    if (!m_x2apic) {
        // Select target core
        write(0x310, apic_id << 24);
        // Send INIT (Delivery mode = INIT, Level = 1)
        write(0x300, icr_low);
        // Wait for delivery
        while (read(0x300) & (1 << 12))
            asm volatile("pause");
    } else {
        // x2APIC
        CPU::write_msr(0x830, (uint64_t)apic_id << 32 | icr_low);
    }
}
References read(), write(), and MaxOS::system::CPU::write_msr().
send_startup()
void LocalAPIC::send_startup (uint8_t apic_id, uint8_t vector) const
send the start up IPI to another apic
Parameters
apic_id The apic to send it to
vector Where to start executing
Definition at line 170 of file apic.cpp.
                                                                  {
    if (!m_x2apic) {
        // Select target core
        write(0x310, apic_id << 24);
        // Send SIPI (Delivery mode = STARTUP)
        write(0x300, 0x4600 | vector);
        // Wait for delivery
        while (read(0x300) & (1 << 12))
            asm volatile("pause");
    } else {
        // x2APIC
        CPU::write_msr(0x831, (uint64_t)apic_id << 32 | 0x4600 | vector);
    }
}
References read(), write(), and MaxOS::system::CPU::write_msr().
write()
void LocalAPIC::write (uint32_t reg, uint32_t value) const
write a value to the apic register using the MSR or memory I/O depending on the local apic version
Parameters
reg The register to write to
value The value to write
Definition at line 91 of file apic.cpp.
                                                        {
    // If x2APIC is enabled I/O is done through the MSR
    if (m_x2apic){
        CPU::write_msr((reg >> 4) + 0x800, value);
        return;
    }
    // Default to memory I/O
    *(volatile uint32_t*) ((uintptr_t) m_apic_base_high + reg) = value;
}
References MaxOS::system::CPU::write_msr().
Referenced by LocalAPIC(), send_eoi(), send_init(), send_startup(), and MaxOS::drivers::clock::Clock::setup_apic_clock().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/apic.h
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/apic.cpp