MaxOS::system::GlobalDescriptorTable Class Reference
Sets up the GDT in the CPU.
#include <gdt.h>
Public Member Functions
GlobalDescriptorTable ()
Construct a new Global Descriptor Table object and set up the GDT entries and load it into the CPU, reloading segment registers.
void load ()
Loads the GDT into the CPU.
Public Attributes
uint64_t table [7]
The GDT entries.
gdtr_t gdtr = { }
The GDTR structure.
Detailed Description
Sets up the GDT in the CPU.
Definition at line 53 of file gdt.h.
Constructor & Destructor Documentation
GlobalDescriptorTable()
GlobalDescriptorTable::GlobalDescriptorTable ()
Construct a new Global Descriptor Table object and set up the GDT entries and load it into the CPU, reloading segment registers.
Definition at line 18 of file gdt.cpp.
{
    // Null descriptor
    table[0] = 0;
    // Kernel Code Segment descriptor
    uint64_t kernel_cs = 0;
    kernel_cs |= (uint64_t) DescriptorFlags::Write;
    kernel_cs |= (uint64_t) DescriptorFlags::Execute;
    kernel_cs |= (uint64_t) DescriptorFlags::CodeOrDataSegment;
    kernel_cs |= (uint64_t) DescriptorFlags::Present;
    kernel_cs |= (uint64_t) DescriptorFlags::LongMode;
    table[1] = kernel_cs;
    // Kernel Data Segment descriptor
    uint64_t kernel_ds = 0;
    kernel_ds |= (uint64_t) DescriptorFlags::Write;
    kernel_ds |= (uint64_t) DescriptorFlags::CodeOrDataSegment;
    kernel_ds |= (uint64_t) DescriptorFlags::Present;
    table[2] = kernel_ds;
    // User code segment descriptor (Change the privilege level to 3)
    uint64_t user_cs = 0;
    user_cs |= (uint64_t) DescriptorFlags::Write;
    user_cs |= (uint64_t) DescriptorFlags::Execute;
    user_cs |= (uint64_t) DescriptorFlags::CodeOrDataSegment;
    user_cs |= (uint64_t) DescriptorFlags::Present;
    user_cs |= (uint64_t) DescriptorFlags::LongMode;
    user_cs |= (3ULL << 45);
    table[3] = user_cs;
    // User data segment descriptor (Change the privilege level to 3)
    uint64_t user_ds = 0;
    user_ds |= (uint64_t) DescriptorFlags::Write;
    user_ds |= (uint64_t) DescriptorFlags::CodeOrDataSegment;
    user_ds |= (uint64_t) DescriptorFlags::Present;
    user_ds |= (3ULL << 45);
    table[4] = user_ds;
    // Reserve space for the TSS
    table[5] = 0;
    table[6] = 0;
    // Load the GDT
    load();
    // Reload the segment registers
    asm volatile("mov %0, %%ds" : : "r"(0x10));
    asm volatile("mov %0, %%es" : : "r"(0x10));
    asm volatile("mov %0, %%fs" : : "r"(0x10));
    asm volatile("mov %0, %%gs" : : "r"(0x10));
    asm volatile("mov %0, %%ss" : : "r"(0x10));
    Logger::DEBUG() << "Reloaded segment registers\n";
}
References MaxOS::Logger::DEBUG(), load(), and table.
Member Function Documentation
load()
void GlobalDescriptorTable::load ()
Loads the GDT into the CPU.
Definition at line 77 of file gdt.cpp.
                                 {
    gdtr = {
            .size = sizeof(table) - 1,
            .address = (uint64_t) table,
    };
    asm volatile("lgdt %0" : : "m"(gdtr));
    Logger::DEBUG() << "Loaded GDT of limit 0x" << (uint64_t) gdtr.size << " and address 0x" << (uint64_t) gdtr.address << "\n";
}
References MaxOS::Logger::DEBUG(), gdtr, and table.
Referenced by GlobalDescriptorTable().
Member Data Documentation
gdtr
gdtr_t MaxOS::system::GlobalDescriptorTable::gdtr = { }
The GDTR structure.
Definition at line 61 of file gdt.h.
{ };
Referenced by load().
table
uint64_t MaxOS::system::GlobalDescriptorTable::table[7]
The GDT entries.
Definition at line 59 of file gdt.h.
Referenced by GlobalDescriptorTable(), and load().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/system/gdt.h
/home/runner/work/MaxOS/MaxOS/kernel/src/system/gdt.cpp