MaxOS::common::InputStreamEventHandler< Type > Class Template Reference
Handles read and end of stream events from a set of streams.
#include <inputStream.h>
Public Member Functions
InputStreamEventHandler ()
_______________________________________________TEMPLATES_________________________________________________________________///
~InputStreamEventHandler ()
Destroys the InputStreamProcessor and disconnects it from all streams.
virtual void on_stream_read (Type)
Called when data is read from a stream (overridden by subclasses)
virtual void on_end_of_stream (GenericInputStream< Type > *)
Called when a stream has finished. Removes the stream from the array of streams.
Protected Attributes
common::Vector< GenericInputStream< Type > * > m_generic_input_streams
List of streams being observed by this handler.
Friends
class GenericInputStream< Type >
Detailed Description
template<class Type>
class MaxOS::common::InputStreamEventHandler< Type >
Handles read and end of stream events from a set of streams.
Template Parameters
Type The type of data the stream is handling
Definition at line 31 of file inputStream.h.
Constructor & Destructor Documentation
InputStreamEventHandler()
template<class Type >
MaxOS::common::InputStreamEventHandler< Type >::InputStreamEventHandler () [default]
_______________________________________________TEMPLATES_________________________________________________________________///
Creates a new InputStreamProcessor
Template Parameters
Type the type of data the stream is handling
~InputStreamEventHandler()
template<class Type >
MaxOS::common::InputStreamEventHandler< Type >::~InputStreamEventHandler ()
Destroys the InputStreamProcessor and disconnects it from all streams.
Template Parameters
Type the type of data the stream is handling
Definition at line 168 of file inputStream.h.
                                                                                     {
            // Disconnect the handler from all streams
            while(!m_generic_input_streams.empty())
              (*m_generic_input_streams.begin()) -> disconnect_input_stream_event_handler(this);
        }
Member Function Documentation
on_end_of_stream()
template<class Type >
void MaxOS::common::InputStreamEventHandler< Type >::on_end_of_stream (GenericInputStream< Type > * stream) [virtual]
Called when a stream has finished. Removes the stream from the array of streams.
Template Parameters
Type The type of data the stream is handling
Parameters
stream The stream that has finished
Reimplemented in MaxOS::common::GenericOutputStream< string >, MaxOS::common::InputStreamProcessor< string, string >, MaxOS::common::InputStreamBuffer< Type >, MaxOS::common::GenericOutputStream< Type >, MaxOS::common::InputStreamProcessor< Type, ProcessorType >, MaxOS::common::InputStreamProcessor< Type, Type * >, and MaxOS::common::InputStreamProcessor< Type, Type >.
Definition at line 191 of file inputStream.h.
                                                                                                                  {
            // Remove the stream
            m_generic_input_streams.erase(stream);
        }
Referenced by MaxOS::common::GenericInputStream< Type >::disconnect_input_stream_event_handler(), and MaxOS::common::InputStreamProcessor< Type, ProcessorType >::on_end_of_stream().
on_stream_read()
template<class Type >
void MaxOS::common::InputStreamEventHandler< Type >::on_stream_read (Type) [virtual]
Called when data is read from a stream (overridden by subclasses)
Template Parameters
Type the type of data the stream is handling
Reimplemented in MaxOS::common::GenericOutputStream< string >, MaxOS::common::InputStreamSocket< Type >, MaxOS::common::InputStreamBuffer< Type >, and MaxOS::common::GenericOutputStream< Type >.
Definition at line 181 of file inputStream.h.
                                                                                    {
        }
Referenced by MaxOS::common::InputStreamBuffer< Type >::flush().
Friends And Related Symbol Documentation
GenericInputStream< Type >
template<class Type >
friend class GenericInputStream< Type > [friend]
Definition at line 427 of file inputStream.h.
Member Data Documentation
m_generic_input_streams
template<class Type >
common::Vector<GenericInputStream<Type>*> MaxOS::common::InputStreamEventHandler< Type >::m_generic_input_streams [protected]
List of streams being observed by this handler.
Definition at line 36 of file inputStream.h.
The documentation for this class was generated from the following file:
/home/runner/work/MaxOS/MaxOS/kernel/include/common/inputStream.h