MaxOS::net::UserDatagramProtocolSocket Class Reference
#include <udp.h>
Public Member Functions
UserDatagramProtocolSocket ()
Socket
~UserDatagramProtocolSocket ()
virtual void handleUserDatagramProtocolPayload (uint8_t *data, uint16_t size)
virtual void Send (uint8_t *data, uint16_t size)
virtual void Disconnect ()
Public Member Functions inherited from MaxOS::common::EventManager< UserDatagramProtocolEvents >
EventManager ()
~EventManager ()
void connect_event_handler (EventHandler< UserDatagramProtocolEvents > *handler)
Connect an event handler to the event manager if it is not already connected.
void disconnect_event_handler (EventHandler< UserDatagramProtocolEvents > *handler)
Disconnect an event handler from the event manager if it is connected.
Vector< Event< UserDatagramProtocolEvents > * > raise_event (Event< UserDatagramProtocolEvents > *event)
Calls the on_event function of all the event m_handlers connected to the event manager and returns a list of the results.
Protected Attributes
bool listening
uint16_t localPort = 0
uint16_t remotePort = 0
uint32_t localIP = 0
uint32_t remoteIP = 0
UserDatagramProtocolHandler * userDatagramProtocolHandler
Protected Attributes inherited from MaxOS::common::EventManager< UserDatagramProtocolEvents >
Vector< EventHandler< UserDatagramProtocolEvents > * > m_handlers
Friends
class UserDatagramProtocolHandler
Detailed Description
Definition at line 62 of file udp.h.
Constructor & Destructor Documentation
UserDatagramProtocolSocket()
UserDatagramProtocolSocket::UserDatagramProtocolSocket ()
Socket
Definition at line 34 of file udp.cpp.
                                                       {
    //Set the instance variables
    listening = false;
}
References listening.
~UserDatagramProtocolSocket()
UserDatagramProtocolSocket::~UserDatagramProtocolSocket () [default]
Member Function Documentation
Disconnect()
void UserDatagramProtocolSocket::Disconnect () [virtual]
Definition at line 58 of file udp.cpp.
                                            {
    userDatagramProtocolHandler ->Disconnect(this);
}
References MaxOS::net::UserDatagramProtocolHandler::Disconnect(), and userDatagramProtocolHandler.
handleUserDatagramProtocolPayload()
void UserDatagramProtocolSocket::handleUserDatagramProtocolPayload (uint8_t * data, uint16_t size) [virtual]
Definition at line 43 of file udp.cpp.
                                                                                               {
    // Create the event
    auto* event = new UDPDataReceivedEvent(this, data, size);
    raise_event(event);
    MemoryManager::kfree(event);
}
References data, MaxOS::memory::MemoryManager::kfree(), MaxOS::common::EventManager< UserDatagramProtocolEvents >::raise_event(), and size.
Referenced by MaxOS::net::UserDatagramProtocolHandler::handleInternetProtocolPayload().
Send()
void UserDatagramProtocolSocket::Send (uint8_t * data, uint16_t size) [virtual]
Definition at line 52 of file udp.cpp.
                                                                  {
    userDatagramProtocolHandler -> Send(this, data, size);
}
References data, Send(), size, and userDatagramProtocolHandler.
Referenced by Send().
Friends And Related Symbol Documentation
UserDatagramProtocolHandler
friend class UserDatagramProtocolHandler [friend]
Definition at line 64 of file udp.h.
Member Data Documentation
listening
bool MaxOS::net::UserDatagramProtocolSocket::listening [protected]
Definition at line 66 of file udp.h.
Referenced by MaxOS::net::UserDatagramProtocolHandler::handleInternetProtocolPayload(), and UserDatagramProtocolSocket().
localIP
uint32_t MaxOS::net::UserDatagramProtocolSocket::localIP = 0 [protected]
Definition at line 71 of file udp.h.
localPort
uint16_t MaxOS::net::UserDatagramProtocolSocket::localPort = 0 [protected]
Definition at line 68 of file udp.h.
remoteIP
uint32_t MaxOS::net::UserDatagramProtocolSocket::remoteIP = 0 [protected]
Definition at line 72 of file udp.h.
Referenced by MaxOS::net::UserDatagramProtocolHandler::handleInternetProtocolPayload(), and MaxOS::net::UserDatagramProtocolHandler::Send().
remotePort
uint16_t MaxOS::net::UserDatagramProtocolSocket::remotePort = 0 [protected]
Definition at line 69 of file udp.h.
Referenced by MaxOS::net::UserDatagramProtocolHandler::handleInternetProtocolPayload().
userDatagramProtocolHandler
UserDatagramProtocolHandler* MaxOS::net::UserDatagramProtocolSocket::userDatagramProtocolHandler [protected]
Definition at line 74 of file udp.h.
Referenced by Disconnect(), and Send().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/net/udp.h
/home/runner/work/MaxOS/MaxOS/kernel/src/net/udp.cpp