MaxOS::drivers::peripherals::MouseEventHandler Class Reference
Handles events that are triggered by the mouse driver.
#include <mouse.h>
Public Member Functions
MouseEventHandler ()
~MouseEventHandler ()
common::Event< MouseEvents > * on_event (common::Event< MouseEvents > *) override
Handles the triggered event and calls the appropriate function.
virtual void on_mouse_down_event (uint8_t button)
Called when the mouse is pressed.
virtual void on_mouse_up_event (uint8_t button)
Called when the mouse is released.
virtual void on_mouse_move_event (int8_t x, int8_t y)
Called when the mouse is moved.
Public Member Functions inherited from MaxOS::common::EventHandler< MouseEvents >
EventHandler ()
~EventHandler ()
virtual Event< MouseEvents > * on_event (Event< MouseEvents > *event)
This function is called when an event is raised.
Detailed Description
Handles events that are triggered by the mouse driver.
Definition at line 65 of file mouse.h.
Constructor & Destructor Documentation
MouseEventHandler()
MouseEventHandler::MouseEventHandler () [default]
~MouseEventHandler()
MouseEventHandler::~MouseEventHandler () [default]
Member Function Documentation
on_event()
Event< MouseEvents > * MouseEventHandler::on_event (common::Event< MouseEvents > * event) [override]
Handles the triggered event and calls the appropriate function.
Parameters
event The event that was triggered
Returns
The event that was triggered with the modified data
Definition at line 21 of file mouse.cpp.
                                                                         {
    switch (event->type) {
        case MouseEvents::MOVE:
            this->on_mouse_move_event(((MouseMoveEvent *) event)->x,
                                      ((MouseMoveEvent *) event)->y);
            break;
        case MouseEvents::DOWN:
            this->on_mouse_down_event(((MouseDownEvent *) event)->button);
            break;
        case MouseEvents::UP:
            this->on_mouse_up_event(((MouseUpEvent *) event)->button);
            break;
    }
    return event;
}
References MaxOS::drivers::peripherals::DOWN, MaxOS::drivers::peripherals::MOVE, on_mouse_down_event(), on_mouse_move_event(), on_mouse_up_event(), MaxOS::drivers::peripherals::UP, MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y.
on_mouse_down_event()
void MouseEventHandler::on_mouse_down_event (uint8_t button) [virtual]
Called when the mouse is pressed.
Parameters
button The button that was pressed
Reimplemented in MaxOS::gui::Desktop.
Definition at line 47 of file mouse.cpp.
                                                   {
}
Referenced by on_event().
on_mouse_move_event()
void MouseEventHandler::on_mouse_move_event (int8_t x, int8_t y) [virtual]
Called when the mouse is moved.
Parameters
x How much the mouse moved in the x direction
y How much the mouse moved in the y direction
Reimplemented in MaxOS::gui::Desktop, MaxOS::gui::WidgetMoverResizer< Left, Top, Width, Height >, MaxOS::gui::WidgetMoverResizer< 0, 0, 0, 1 >, MaxOS::gui::WidgetMoverResizer< 0, 0, 1, 0 >, MaxOS::gui::WidgetMoverResizer< 0, 0, 1, 1 >, MaxOS::gui::WidgetMoverResizer< 0, 1, 0, -1 >, MaxOS::gui::WidgetMoverResizer< 0, 1, 1, -1 >, MaxOS::gui::WidgetMoverResizer< 1, 0, -1, 0 >, MaxOS::gui::WidgetMoverResizer< 1, 0, -1, 1 >, MaxOS::gui::WidgetMoverResizer< 1, 1, -1, -1 >, and MaxOS::gui::WidgetMoverResizer< 1, 1, 0, 0 >.
Definition at line 66 of file mouse.cpp.
                                                          {
}
Referenced by on_event(), and MaxOS::gui::Desktop::on_mouse_move_event().
on_mouse_up_event()
void MouseEventHandler::on_mouse_up_event (uint8_t button) [virtual]
Called when the mouse is released.
Parameters
button The button that was released
Reimplemented in MaxOS::gui::Desktop.
Definition at line 56 of file mouse.cpp.
                                                 {
}
Referenced by on_event().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/peripherals/mouse.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/peripherals/mouse.cpp