MaxOS::filesystem::File Class Reference
Handles file operations and information.
#include <filesystem.h>
Public Member Functions
File ()
virtual ~File ()
virtual void write (const common::buffer_t *data, size_t size)
Write data to the file.
virtual void read (common::buffer_t *data, size_t size)
Read data from the file.
virtual void flush ()
Flush the file to the disk.
void seek (SeekType seek_type, size_t offset)
Seek to a position in the file.
uint32_t position ()
Get where the file is currently at (amount read/write/seeked)
size_t size ()
Get the size of the file.
string name ()
Get the name of the file.
Protected Attributes
uint32_t m_offset
string m_name
size_t m_size
Detailed Description
Handles file operations and information.
Definition at line 28 of file filesystem.h.
Constructor & Destructor Documentation
File()
File::File () [default]
~File()
File::~File () [virtual], [default]
Member Function Documentation
flush()
void File::flush () [virtual]
Flush the file to the disk.
Reimplemented in MaxOS::filesystem::format::ext2::Ext2File, and MaxOS::filesystem::format::Fat32File.
Definition at line 37 of file filesystem.cpp.
                 {
}
Referenced by MaxOS::filesystem::format::ext2::Ext2File::flush(), and MaxOS::filesystem::format::Fat32File::flush().
name()
string File::name ()
Get the name of the file.
Returns
The name of the file
Definition at line 78 of file filesystem.cpp.
                  {
    return m_name;
}
References m_name.
Referenced by MaxOS::filesystem::format::ext2::Ext2File::Ext2File(), MaxOS::filesystem::format::Fat32File::Fat32File(), and MaxOS::filesystem::Directory::rename_file().
position()
uint32_t File::position ()
Get where the file is currently at (amount read/write/seeked)
Returns
The current position in the file
Definition at line 69 of file filesystem.cpp.
                        {
    return m_offset;
}
References m_offset.
Referenced by MaxOS::filesystem::FileResource::read().
read()
void File::read (common::buffer_t * data, size_t amount) [virtual]
Read data from the file.
Parameters
data The byte buffer to read into
size The amount of data to read
Reimplemented in MaxOS::filesystem::format::ext2::Ext2File, and MaxOS::filesystem::format::Fat32File.
Definition at line 31 of file filesystem.cpp.
                                                   {
}
Referenced by MaxOS::filesystem::FileResource::read().
seek()
void File::seek (SeekType seek_type, size_t offset)
Seek to a position in the file.
Parameters
seek_type The type of seek to perform (where to seek to)
offset The amount to seek
Definition at line 46 of file filesystem.cpp.
                                                 {
    // Seek based on the type
    switch (seek_type) {
        case SeekType::SET:
            m_offset = offset;
            break;
        case SeekType::CURRENT:
            m_offset += offset;
            break;
        case SeekType::END:
            m_offset = size() - offset;
            break;
    }
}
References m_offset, and size().
Referenced by MaxOS::filesystem::FileResource::write().
size()
size_t File::size ()
Get the size of the file.
Returns
The size of the file (in bytes)
Definition at line 87 of file filesystem.cpp.
                  {
    return m_size;
}
References m_size.
Referenced by MaxOS::filesystem::FileResource::read(), and seek().
write()
void File::write (const common::buffer_t * data, size_t amount) [virtual]
Write data to the file.
Parameters
data The byte buffer to write
size The amount of data to write
Reimplemented in MaxOS::filesystem::format::ext2::Ext2File, and MaxOS::filesystem::format::Fat32File.
Definition at line 22 of file filesystem.cpp.
                                                          {
}
Referenced by MaxOS::filesystem::FileResource::write().
Member Data Documentation
m_name
string MaxOS::filesystem::File::m_name [protected]
Definition at line 33 of file filesystem.h.
Referenced by MaxOS::filesystem::format::ext2::Ext2File::Ext2File(), MaxOS::filesystem::format::Fat32File::Fat32File(), and name().
m_offset
uint32_t MaxOS::filesystem::File::m_offset [protected]
Definition at line 32 of file filesystem.h.
Referenced by MaxOS::filesystem::format::Fat32File::Fat32File(), position(), MaxOS::filesystem::format::ext2::Ext2File::read(), MaxOS::filesystem::format::Fat32File::read(), seek(), MaxOS::filesystem::format::ext2::Ext2File::write(), and MaxOS::filesystem::format::Fat32File::write().
m_size
size_t MaxOS::filesystem::File::m_size [protected]
Definition at line 34 of file filesystem.h.
Referenced by MaxOS::filesystem::format::ext2::Ext2File::Ext2File(), MaxOS::filesystem::format::Fat32File::Fat32File(), MaxOS::filesystem::format::ext2::Ext2File::read(), size(), MaxOS::filesystem::format::ext2::Ext2File::write(), and MaxOS::filesystem::format::Fat32File::write().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/filesystem.h
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/filesystem.cpp