MaxOS::drivers::ethernet::EthernetDriver Class Reference
Driver for the Ethernet Controller, manages the sending and receiving of data, the mac address, and the events.
#include <ethernet.h>
Public Member Functions
virtual MediaAccessControlAddress get_media_access_control_address ()
Get the MAC address.
void send (uint8_t *buffer, uint32_t size)
send data to the network via the driver backend
Public Member Functions inherited from MaxOS::drivers::Driver
virtual void activate ()
Activate the driver.
virtual void deactivate ()
Deactivate the driver.
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
virtual string vendor_name ()
Get who created the device.
virtual string device_name ()
Get the device name of the driver.
Public Member Functions inherited from MaxOS::common::EventManager< EthernetDriverEvents >
void connect_event_handler (EventHandler< EthernetDriverEvents > *handler)
connect an event handler to the event manager if it is not already connected
void disconnect_event_handler (EventHandler< EthernetDriverEvents > *handler)
disconnect an event handler from the event manager if it is connected
Vector< Event< EthernetDriverEvents > * > raise_event (Event< EthernetDriverEvents > *event)
Calls the on_event function of all the event m_handlers connected to the event manager and returns a list of the results.
Static Public Member Functions
static MediaAccessControlAddress create_media_access_control_address (uint8_t digit1, uint8_t digit2, uint8_t digit3, uint8_t digit4, uint8_t digit5, uint8_t digit6)
Create a Media Access Control Address.
Protected Member Functions
virtual void do_send (uint8_t *buffer, uint32_t size)
(Device Side) send the data
void fire_data_received (uint8_t *buffer, uint32_t size)
Handle the recieved data.
void fire_data_sent (uint8_t *buffer, uint32_t size)
send data
Additional Inherited Members
Protected Attributes inherited from MaxOS::common::EventManager< EthernetDriverEvents >
Vector< EventHandler< EthernetDriverEvents > * > m_handlers
Detailed Description
Driver for the Ethernet Controller, manages the sending and receiving of data, the mac address, and the events.
Definition at line 89 of file ethernet.h.
Member Function Documentation
create_media_access_control_address()
MediaAccessControlAddress EthernetDriver::create_media_access_control_address (uint8_t digit1, uint8_t digit2, uint8_t digit3, uint8_t digit4, uint8_t digit5, uint8_t digit6) [static]
Create a Media Access Control Address.
Parameters
digit1 The m_first_memory_chunk digit
digit2 The second digit
digit3 The third digit
digit4 The fourth digit
digit5 The fifth digit
digit6 The last digit
Returns
The MAC address
Definition at line 165 of file ethernet.cpp.
                                                                                                                                                                            {
    return // digit6 is the most significant byte
            (uint64_t) digit6 << 40
            | (uint64_t) digit5 << 32
            | (uint64_t) digit4 << 24
            | (uint64_t) digit3 << 16
            | (uint64_t) digit2 << 8
            | (uint64_t) digit1;
}
Referenced by MaxOS::drivers::ethernet::IntelI217::IntelI217().
do_send()
void EthernetDriver::do_send (uint8_t * buffer, uint32_t size) [protected], [virtual]
(Device Side) send the data
Parameters
buffer The buffer to handle
size The size of the buffer
Reimplemented in MaxOS::drivers::ethernet::AMD_AM79C973, and MaxOS::drivers::ethernet::IntelI217.
Definition at line 113 of file ethernet.cpp.
                                                           {
}
Referenced by send().
fire_data_received()
void EthernetDriver::fire_data_received (uint8_t * buffer, uint32_t size) [protected]
Handle the recieved data.
Parameters
buffer The buffer to handle
size The size of the buffer
Definition at line 122 of file ethernet.cpp.
                                                                      {
    // Raise the event
    Vector<Event<EthernetDriverEvents>*> values =
            raise_event(new DataReceivedEvent(buffer, size));
    // Loop through the events
    for (auto &value : values) {
        switch (value->type) {
            case EthernetDriverEvents::DATA_RECEIVED:
                if (value->return_value.bool_value)
                    send(buffer, size);
                break;
            default:
                break;
        }
    }
}
References MaxOS::common::EventManager< EthernetDriverEvents >::raise_event(), and send().
fire_data_sent()
void EthernetDriver::fire_data_sent (uint8_t * buffer, uint32_t size) [protected]
send data
Parameters
buffer The buffer to send
size The size of the buffer
Definition at line 148 of file ethernet.cpp.
                                                                  {
    raise_event(new DataSentEvent(buffer, size));
}
References MaxOS::common::EventManager< EthernetDriverEvents >::raise_event().
get_media_access_control_address()
MediaAccessControlAddress EthernetDriver::get_media_access_control_address () [virtual]
Get the MAC address.
Returns
the MAC address
Reimplemented in MaxOS::drivers::ethernet::AMD_AM79C973, and MaxOS::drivers::ethernet::IntelI217.
Definition at line 89 of file ethernet.cpp.
                                                                           {
    return 0;
}
Referenced by MaxOS::net::EthernetFrameHandler::data_received(), MaxOS::net::EthernetFrameHandler::get_mac(), and MaxOS::net::EthernetFrameHandler::send_ethernet_frame().
send()
void EthernetDriver::send (uint8_t * buffer, uint32_t size)
send data to the network via the driver backend
Parameters
buffer The buffer to send
size The size of the buffer
Definition at line 99 of file ethernet.cpp.
                                                        {
    // Raise the event
    raise_event(new BeforeSendEvent(buffer, size));
    do_send(buffer, size);
}
References do_send(), and MaxOS::common::EventManager< EthernetDriverEvents >::raise_event().
Referenced by fire_data_received(), and MaxOS::net::EthernetFrameHandler::send_ethernet_frame().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/ethernet/ethernet.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/ethernet/ethernet.cpp