MaxOS::gui::Widget Class Reference
A graphical object that can be drawn on the screen.
#include <widget.h>
Public Member Functions
Widget ()
Construct a new Widget object.
Widget (int32_t left, int32_t top, uint32_t width, uint32_t height)
Construct a new Widget object at a specific position and size.
virtual void draw (common::GraphicsContext *gc, common::Rectangle< int32_t > &area)
Draw the widget on the screen.
void invalidate ()
Invalidates the entire widget. This forces the widget to be redrawn on the next screen update.
virtual void invalidate (common::Rectangle< int32_t > &area)
Invalidates a specific area of the widget. This forces that part of the screen to be redrawn on the next screen update.
virtual void add_child (Widget *child)
Set the parent of a widget to this widget, making it into a child.
virtual common::Coordinates absolute_coordinates (common::Coordinates coordinates)
Get the absolute coordinates of the widget (relative to the screen)
virtual bool contains_coordinate (uint32_t x, uint32_t y)
Check if the widget contains a specific coordinate.
common::Rectangle< int32_t > position ()
Get the position of the widget.
void move (int32_t left, int32_t top)
Set the position of the widget, and invalidate the old and new positions so they are redrawn.
void resize (int32_t width, int32_t height)
Set the size of the widget, and invalidate the old and new positions so they are redrawn.
void focus ()
Set the current focused widget to be this widget.
virtual void on_focus ()
Handles the event when the widget is focussed.
virtual void on_focus_lost ()
Handles the event when the widget is unfocused.
void bring_to_front ()
Brings this widget to the front of the screen.
virtual void on_mouse_enter_widget (uint32_t to_x, uint32_t to_y)
Handles the event when the mouse is moved on to the widget.
virtual void on_mouse_leave_widget (uint32_t from_x, uint32_t from_y)
Handles the event when the mouse is moved out of the widget.
virtual void on_mouse_move_widget (uint32_t from_x, uint32_t from_y, uint32_t to_x, uint32_t to_y)
Handles the event when the mouse is moved over the widget.
virtual drivers::peripherals::MouseEventHandler * on_mouse_button_pressed (uint32_t x, uint32_t y, uint8_t button)
Handles the event when the mouse is pressed on the widget.
virtual void on_mouse_button_released (uint32_t x, uint32_t y, uint8_t button)
Handles the event when the mouse is released on the widget.
Public Member Functions inherited from MaxOS::drivers::peripherals::KeyboardEventHandler
common::Event< KeyboardEvents > * on_event (common::Event< KeyboardEvents > *) override
Handle the trigger of an event.
virtual void on_key_down (KeyCode, const KeyboardState &)
Handle the key down event.
virtual void on_key_up (KeyCode, const KeyboardState &)
Handle the key up event.
Public Member Functions inherited from MaxOS::common::EventHandler< KeyboardEvents >
virtual Event< KeyboardEvents > * on_event (Event< KeyboardEvents > *event)
This function is called when an event is raised.
Protected Member Functions
virtual void set_focus (Widget *)
Sets the widget that is currently focussed.
virtual void bring_to_front (Widget *)
Brings a specific widget to the front of the screen.
Protected Attributes
common::Rectangle< int32_t > m_position
The position and size of the widget (relative to its parent)
Widget * m_parent { nullptr }
The widget that owns this widget.
bool m_valid { false }
Is the widget drawn to the screen and up to date.
uint32_t m_min_width { 5 }
The smallest m_width the widget can be resized to.
uint32_t m_min_height { 5 }
The smallest m_height the widget can be resized to.
uint32_t m_max_width { 0x8FFFFFFF }
The largest m_width the widget can be resized to.
uint32_t m_max_height { 0x8FFFFFFF }
The largest m_height the widget can be resized to.
Friends
template<int Left, int Top, int Width, int Height>
class WidgetMoverResizer
class CompositeWidget
Detailed Description
A graphical object that can be drawn on the screen.
Definition at line 29 of file widget.h.
Constructor & Destructor Documentation
Widget() [1/2]
Widget::Widget ()
Construct a new Widget object.
Definition at line 19 of file widget.cpp.
: KeyboardEventHandler()
{
}
Widget() [2/2]
Widget::Widget (int32_t left, int32_t top, uint32_t width, uint32_t height)
Construct a new Widget object at a specific position and size.
Parameters
left The left position of the widget relative to its parent
top The top position of the widget relative to its parent
width The width of the widget
height The height of the widget
Definition at line 33 of file widget.cpp.
: KeyboardEventHandler(),
  m_position(left, top, width, height)
{
}
Member Function Documentation
absolute_coordinates()
Coordinates Widget::absolute_coordinates (common::Coordinates coordinates) [virtual]
Get the absolute coordinates of the widget (relative to the screen)
Parameters
coordinates The coordinates within the widget to convert
Returns
The absolute coordinates of the widget
Definition at line 98 of file widget.cpp.
                                                                      {
    // Return the parents absolute coordinates
    if (m_parent != nullptr)
        return m_parent->absolute_coordinates(Coordinates(coordinates.first + m_position.left, coordinates.second + m_position.top));
    // If the widget has no m_parent, return the coordinates of the widget
    return {coordinates.first + m_position.left, coordinates.second + m_position.top};
}
References absolute_coordinates(), MaxOS::common::Rectangle< Type >::left, m_parent, m_position, and MaxOS::common::Rectangle< Type >::top.
Referenced by absolute_coordinates(), MaxOS::gui::widgets::Button::draw(), MaxOS::gui::widgets::InputBox::draw(), MaxOS::gui::widgets::Text::draw(), MaxOS::gui::Window::draw_self(), and invalidate().
add_child()
void Widget::add_child (Widget * child) [virtual]
Set the parent of a widget to this widget, making it into a child.
Parameters
child The child to add
Reimplemented in MaxOS::gui::Desktop, MaxOS::gui::CompositeWidget, and MaxOS::gui::Window.
Definition at line 85 of file widget.cpp.
                                    {
    // Parent the child to this widget
    child->m_parent = this;
}
Referenced by MaxOS::gui::CompositeWidget::add_child().
bring_to_front() [1/2]
void Widget::bring_to_front ()
Brings this widget to the front of the screen.
Definition at line 230 of file widget.cpp.
                            {
    // Bring this widget to the front of the screen
    bring_to_front(this);
}
References bring_to_front().
Referenced by bring_to_front(), on_mouse_button_pressed(), and MaxOS::gui::Window::on_mouse_button_pressed().
bring_to_front() [2/2]
void Widget::bring_to_front (Widget * widget) [protected], [virtual]
Brings a specific widget to the front of the screen.
Parameters
widget The widget to bring to the front
Reimplemented in MaxOS::gui::Desktop.
Definition at line 241 of file widget.cpp.
                                          {
    // Bring the parent to the front of the screen
    if (m_parent != nullptr)
        m_parent->bring_to_front(widget);
}
References bring_to_front(), and m_parent.
Referenced by bring_to_front().
contains_coordinate()
bool Widget::contains_coordinate (uint32_t x, uint32_t y) [virtual]
Check if the widget contains a specific coordinate.
Parameters
x The x coordinate
y The y coordinate
Returns
True if the widget contains the coordinate, false if it does not
Definition at line 116 of file widget.cpp.
                                                       {
    // Check if the coordinates are within the bounds of the widget
    return m_position.contains(x, y);
}
References MaxOS::common::Rectangle< Type >::contains(), and m_position.
draw()
void Widget::draw (common::GraphicsContext * gc, common::Rectangle< int32_t > & area) [virtual]
Draw the widget on the screen.
Parameters
gc The graphics context to draw the widgets pixels on
area The area of the widget to draw
Reimplemented in MaxOS::gui::CompositeWidget, MaxOS::gui::widgets::Button, MaxOS::gui::widgets::InputBox, and MaxOS::gui::widgets::Text.
Definition at line 48 of file widget.cpp.
                                                       {
}
Referenced by MaxOS::gui::widgets::Button::draw(), MaxOS::gui::widgets::InputBox::draw(), MaxOS::gui::widgets::Text::draw(), and MaxOS::gui::CompositeWidget::draw().
focus()
void Widget::focus ()
Set the current focused widget to be this widget.
Definition at line 195 of file widget.cpp.
                   {
    // Set the focus the widget to this widget
    set_focus(this);
}
References set_focus().
Referenced by on_mouse_button_pressed().
invalidate() [1/2]
void Widget::invalidate ()
Invalidates the entire widget. This forces the widget to be redrawn on the next screen update.
Definition at line 55 of file widget.cpp.
                        {
    // Convert the relative coordinates to absolute coordinates
    Coordinates coordinates = absolute_coordinates(Coordinates(0, 0));
    // Create a rectangle with the absolute coordinates and the size of the widget
    Rectangle<int32_t> invalid_area = Rectangle<int32_t>(coordinates.first, coordinates.second, m_position.width, m_position.height);
    // Invalidate the area
    invalidate(invalid_area);
}
References absolute_coordinates(), MaxOS::common::Rectangle< Type >::height, invalidate(), m_position, and MaxOS::common::Rectangle< Type >::width.
Referenced by MaxOS::gui::Desktop::Desktop(), MaxOS::gui::Desktop::internal_invalidate(), invalidate(), invalidate(), move(), MaxOS::gui::widgets::InputBox::on_focus(), MaxOS::gui::widgets::InputBox::on_focus_lost(), MaxOS::gui::widgets::InputBox::on_key_down(), MaxOS::gui::widgets::Button::on_mouse_button_pressed(), MaxOS::gui::widgets::Button::on_mouse_button_released(), resize(), MaxOS::gui::widgets::InputBox::update_text(), and MaxOS::gui::widgets::Text::update_text().
invalidate() [2/2]
void Widget::invalidate (common::Rectangle< int32_t > & area) [virtual]
Invalidates a specific area of the widget. This forces that part of the screen to be redrawn on the next screen update.
Parameters
area The area of the widget to invalidate
Reimplemented in MaxOS::gui::Desktop.
Definition at line 73 of file widget.cpp.
                                                {
    // If the widget has a parent, invalidate the area of the parent
    if (m_parent != nullptr)
        m_parent->invalidate(area);
}
References invalidate(), and m_parent.
move()
void Widget::move (int32_t left, int32_t top)
Set the position of the widget, and invalidate the old and new positions so they are redrawn.
Parameters
left The new left position of the rectangle
top The new top position of the rectangle
Definition at line 138 of file widget.cpp.
                                           {
    // Invalidate the old position
    invalidate();
    // Set the new position
    m_position.left = left;
    m_position.top = top;
    // Re draw the widget in the new position
    invalidate();
}
References invalidate(), MaxOS::common::Rectangle< Type >::left, m_position, and MaxOS::common::Rectangle< Type >::top.
Referenced by MaxOS::gui::WidgetMoverResizer< Left, Top, Width, Height >::on_mouse_move_event().
on_focus()
void Widget::on_focus () [virtual]
Handles the event when the widget is focussed.
Reimplemented in MaxOS::gui::widgets::InputBox.
Definition at line 216 of file widget.cpp.
                      {
}
Referenced by MaxOS::gui::Desktop::set_focus().
on_focus_lost()
void Widget::on_focus_lost () [virtual]
Handles the event when the widget is unfocused.
Reimplemented in MaxOS::gui::widgets::InputBox.
Definition at line 223 of file widget.cpp.
                           {
}
Referenced by MaxOS::gui::Desktop::set_focus().
on_mouse_button_pressed()
peripherals::MouseEventHandler * Widget::on_mouse_button_pressed (uint32_t x, uint32_t y, uint8_t button) [virtual]
Handles the event when the mouse is pressed on the widget.
Parameters
x The x coordinate of the mouse when it was pressed
y The y coordinate of the mouse when it was pressed
button The button that was pressed
Returns
nullptr
Reimplemented in MaxOS::gui::CompositeWidget, MaxOS::gui::widgets::Button, and MaxOS::gui::Window.
Definition at line 289 of file widget.cpp.
                                                                                         {
    // Bring the widget to the front of the screen
    bring_to_front();
    // Focus the widget
    focus();
    // Return 0 as the event has been handled
    return nullptr;
}
References bring_to_front(), and focus().
Referenced by MaxOS::gui::widgets::Button::on_mouse_button_pressed().
on_mouse_button_released()
void Widget::on_mouse_button_released (uint32_t x, uint32_t y, uint8_t button) [virtual]
Handles the event when the mouse is released on the widget.
Parameters
x The x coordinate of the mouse when it was released
y The y coordinate of the mouse when it was released
button The button that was released
Reimplemented in MaxOS::gui::CompositeWidget, and MaxOS::gui::widgets::Button.
Definition at line 308 of file widget.cpp.
                                                                 {
}
Referenced by MaxOS::gui::widgets::Button::on_mouse_button_released().
on_mouse_enter_widget()
void Widget::on_mouse_enter_widget (uint32_t to_x, uint32_t to_y) [virtual]
Handles the event when the mouse is moved on to the widget.
Parameters
to_x The x coordinate of the mouse
to_y The y coordinate of the mouse
Reimplemented in MaxOS::gui::CompositeWidget.
Definition at line 255 of file widget.cpp.
                                                               {
}
on_mouse_leave_widget()
void Widget::on_mouse_leave_widget (uint32_t from_x, uint32_t from_y) [virtual]
Handles the event when the mouse is moved out of the widget.
Parameters
from_x The x coordinate of the mouse
from_y The y coordinate of the mouse
Reimplemented in MaxOS::gui::CompositeWidget.
Definition at line 265 of file widget.cpp.
                                                                   {
}
on_mouse_move_widget()
void Widget::on_mouse_move_widget (uint32_t from_x, uint32_t from_y, uint32_t to_x, uint32_t to_y) [virtual]
Handles the event when the mouse is moved over the widget.
Parameters
from_x The x original coordinate of the mouse
from_y The y original coordinate of the mouse
to_x The x new coordinate of the mouse
to_y The y new coordinate of the mouse
Reimplemented in MaxOS::gui::CompositeWidget.
Definition at line 277 of file widget.cpp.
                                                                                                {
}
position()
Rectangle< int32_t > Widget::position ()
Get the position of the widget.
Returns
The position of the widget
Definition at line 127 of file widget.cpp.
                                    {
    return m_position;
}
References m_position.
Referenced by MaxOS::gui::widgets::Button::draw(), MaxOS::gui::widgets::InputBox::draw(), MaxOS::gui::widgets::Text::draw(), MaxOS::gui::CompositeWidget::draw(), MaxOS::gui::Window::draw_self(), MaxOS::gui::Window::on_mouse_button_pressed(), and MaxOS::gui::Desktop::on_mouse_move_event().
resize()
void Widget::resize (int32_t width, int32_t height)
Set the size of the widget, and invalidate the old and new positions so they are redrawn.
Parameters
width The new m_width of the rectangle
height The new m_height of the rectangle
Todo
Todo Fix the invalidation so it only redraws the areas that need to be redrawn (right and bottom are always fully redrawn currently)
Definition at line 159 of file widget.cpp.
                                                 {
    // Restrict the width and height to the minimum and maximum values
    if (width < (int) m_min_width) width = m_min_width;
    if (height < (int) m_min_height) height = m_min_height;
    if (width > (int) m_max_width) width = m_max_width;
    if (height > (int) m_max_height) height = m_max_height;
    // Store the old position, set the new position
    Rectangle<int32_t> old_position = m_position;
    m_position.width = width;
    m_position.height = height;
    // Find the areas that need to be redrawn by subtracting the old position from the new position, and vice versa
    Vector<Rectangle<int32_t>> invalid_areas_old = old_position.subtract(m_position);
    Vector<Rectangle<int32_t>> invalid_areas_new = m_position.subtract(old_position);
    // Right and Bottom require to be fully invalidated
    if (m_position.width > old_position.width || m_position.height > old_position.height ||
        old_position.width > m_position.width || old_position.height > m_position.height) {
        invalidate();
        return;
    }
    //Loop through the areas that need to be redrawn and invalidate them
    for (auto& area: invalid_areas_old)
        invalidate(area);
    for (auto& area: invalid_areas_new)
        invalidate(area);
}
References MaxOS::common::Rectangle< Type >::height, invalidate(), m_max_height, m_max_width, m_min_height, m_min_width, m_position, MaxOS::common::Rectangle< Type >::subtract(), and MaxOS::common::Rectangle< Type >::width.
Referenced by MaxOS::gui::WidgetMoverResizer< Left, Top, Width, Height >::on_mouse_move_event().
set_focus()
void Widget::set_focus (Widget * widget) [protected], [virtual]
Sets the widget that is currently focussed.
Parameters
widget The widget to set as focussed
Reimplemented in MaxOS::gui::Desktop.
Definition at line 206 of file widget.cpp.
                                     {
    // Focus the parent to this widget
    if (m_parent != nullptr)
        m_parent->set_focus(widget);
}
References m_parent, and set_focus().
Referenced by focus(), and set_focus().
Friends And Related Symbol Documentation
CompositeWidget
friend class CompositeWidget [friend]
Definition at line 32 of file widget.h.
WidgetMoverResizer
template<int Left, int Top, int Width, int Height>
friend class WidgetMoverResizer [friend]
Definition at line 30 of file widget.h.
Member Data Documentation
m_max_height
uint32_t MaxOS::gui::Widget::m_max_height { 0x8FFFFFFF } [protected]
The largest m_height the widget can be resized to.
Definition at line 44 of file widget.h.
{ 0x8FFFFFFF };
Referenced by resize().
m_max_width
uint32_t MaxOS::gui::Widget::m_max_width { 0x8FFFFFFF } [protected]
The largest m_width the widget can be resized to.
Definition at line 43 of file widget.h.
{ 0x8FFFFFFF };
Referenced by resize().
m_min_height
uint32_t MaxOS::gui::Widget::m_min_height { 5 } [protected]
The smallest m_height the widget can be resized to.
Definition at line 41 of file widget.h.
{ 5 };
Referenced by resize(), MaxOS::gui::Window::Window(), and MaxOS::gui::Window::Window().
m_min_width
uint32_t MaxOS::gui::Widget::m_min_width { 5 } [protected]
The smallest m_width the widget can be resized to.
Definition at line 40 of file widget.h.
{ 5 };
Referenced by resize(), MaxOS::gui::Window::Window(), and MaxOS::gui::Window::Window().
m_parent
Widget* MaxOS::gui::Widget::m_parent { nullptr } [protected]
The widget that owns this widget.
Definition at line 37 of file widget.h.
{ nullptr };
Referenced by absolute_coordinates(), bring_to_front(), invalidate(), and set_focus().
m_position
common::Rectangle<int32_t> MaxOS::gui::Widget::m_position [protected]
The position and size of the widget (relative to its parent)
Definition at line 35 of file widget.h.
Referenced by absolute_coordinates(), contains_coordinate(), invalidate(), move(), MaxOS::gui::WidgetMoverResizer< Left, Top, Width, Height >::on_mouse_move_event(), position(), and resize().
m_valid
bool MaxOS::gui::Widget::m_valid { false } [protected]
Is the widget drawn to the screen and up to date.
Definition at line 38 of file widget.h.
{ false };
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/widget.h
/home/runner/work/MaxOS/MaxOS/kernel/src/gui/widget.cpp