MaxOS::drivers::video::VideoElectronicsStandardsAssociation Class Reference
Driver for the VESA video controller, handles the rendering of pixels to the screen using VESA.
#include <vesa.h>
Public Member Functions
VideoElectronicsStandardsAssociation (multiboot_tag_framebuffer *framebuffer_info)
~VideoElectronicsStandardsAssociation ()
bool supports_mode (uint32_t width, uint32_t height, uint32_t) final
Checks if the VESA driver supports the given mode.
string vendor_name () final
The name of the vendor of the VESA standard.
string device_name () final
The name of the device.
Public Member Functions inherited from MaxOS::drivers::video::VideoDriver
VideoDriver ()
~VideoDriver ()
bool set_mode (uint32_t width, uint32_t height, uint32_t colorDepth)
Set the mode of the video driver.
Public Member Functions inherited from MaxOS::drivers::Driver
Driver ()
~Driver ()
virtual void activate ()
activate the driver
virtual void deactivate ()
deactivate the driver
virtual void initialise ()
Initialise the driver.
virtual uint32_t reset ()
Reset the driver.
Public Member Functions inherited from MaxOS::common::GraphicsContext
GraphicsContext ()
~GraphicsContext ()
uint32_t colour_to_int (const Colour &)
Converts a colour to an integer value based on the current color depth.
Colour int_to_colour (uint32_t)
Converts an integer value to a colour based on the current color depth.
uint32_t width () const
Gets the width of the screen.
uint32_t height () const
Gets the height of the screen.
uint32_t color_depth () const
uint64_t * framebuffer_address ()
Gets the address of the context's framebuffer to draw on.
void put_pixel (int32_t x, int32_t y, const Colour &colour)
Renders a pixel to the screen (automatically converts the colour to an integer)
void putPixel (int32_t x, int32_t y, uint32_t colour)
Renders a pixel to the screen (automatically converts the colour to an integer), will not render the pixel if it is outside the screen.
Colour get_pixel (int32_t x, int32_t y)
Gets the colour of a pixel, or returns black if the pixel is outside the screen.
void invert_pixel (int32_t x, int32_t y)
Inverts a pixel.
void draw_line (int32_t x0, int32_t y0, int32_t x1, int32_t y1, const Colour &colour)
Draws a line on the screen.
void drawLine (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a line on the screen.
void draw_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, const Colour &colour)
Draws a rectangle on the screen.
void draw_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a rectangle on the screen.
void fill_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, const Colour &colour)
Draws a rectangle on the screen, filled with a colour.
void fill_rectangle (int32_t x0, int32_t y0, int32_t x1, int32_t y1, uint32_t colour)
Draws a rectangle on the screen, filled with a colour.
void draw_circle (int32_t x0, int32_t y0, int32_t radius, const Colour &colour)
Draws a circle on the screen.
void draw_circle (int32_t x0, int32_t y0, int32_t radius, uint32_t colour)
Draws a circle on the screen.
void fill_circle (int32_t x0, int32_t y0, int32_t radius, const Colour &colour)
Draws a circle on the screen, filled with a colour.
void fillCircle (int32_t x0, int32_t y0, int32_t radius, uint32_t colour)
Draws a circle on the screen, filled with a colour.
Protected Member Functions
bool internal_set_mode (uint32_t width, uint32_t height, uint32_t) final
Sets the mode of the VESA driver.
void render_pixel_32_bit (uint32_t x, uint32_t y, uint32_t colour) final
Renders a pixel on the screen in 32 bit mode.
uint32_t get_rendered_pixel_32_bit (uint32_t x, uint32_t y) final
Gets the colour of a pixel on the screen in 32 bit mode.
Protected Member Functions inherited from MaxOS::common::GraphicsContext
virtual void render_pixel (uint32_t x, uint32_t y, uint32_t colour)
Renders a pixel to the screen based on the current color depth.
virtual void render_pixel_8_bit (uint32_t x, uint32_t y, uint8_t colour)
Renders a pixel to the screen using the 8 bit color depth.
virtual void render_pixel_16_bit (uint32_t x, uint32_t y, uint16_t colour)
Renders a pixel to the screen using the 16 bit color depth.
virtual void render_pixel_24_bit (uint32_t x, uint32_t y, uint32_t colour)
Renders a pixel to the screen using the 24 bit color depth.
virtual uint32_t get_rendered_pixel (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen, automatically uses the correct color depth.
virtual uint8_t get_rendered_pixel_8_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 8 bit color depth.
virtual uint16_t get_rendered_pixel_16_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 16 bit color depth.
virtual uint32_t get_rendered_pixel_24_bit (uint32_t x, uint32_t y)
Gets the colour of a pixel on the screen using the 24 bit color depth.
Protected Attributes
size_t m_framebuffer_size
multiboot_tag_framebuffer * m_framebuffer_info
uint8_t m_bpp
uint16_t m_pitch
Protected Attributes inherited from MaxOS::common::GraphicsContext
bool mirror_y_axis { false }
int32_t m_width { 0 }
int32_t m_height { 0 }
uint32_t m_color_depth { 0 }
Colour m_colour_pallet [256]
uint64_t * m_framebuffer_address { nullptr }
Detailed Description
Driver for the VESA video controller, handles the rendering of pixels to the screen using VESA.
Definition at line 26 of file vesa.h.
Constructor & Destructor Documentation
VideoElectronicsStandardsAssociation()
VideoElectronicsStandardsAssociation::VideoElectronicsStandardsAssociation (multiboot_tag_framebuffer * framebuffer_info)
Definition at line 15 of file vesa.cpp.
: m_framebuffer_info(framebuffer_info)
{
    Logger::INFO() << "Setting up VESA driver\n";
    // Save the framebuffer info
    m_bpp = m_framebuffer_info->common.framebuffer_bpp;
    m_pitch = m_framebuffer_info->common.framebuffer_pitch;
    m_framebuffer_size = m_framebuffer_info->common.framebuffer_height * m_pitch;
    this->set_mode(framebuffer_info->common.framebuffer_width, framebuffer_info->common.framebuffer_height,
                   framebuffer_info->common.framebuffer_bpp);
    Logger::DEBUG() << "Framebuffer: bpp=" << m_bpp << ", pitch=" << m_pitch << ", size=" << m_framebuffer_size << "\n";
    // Map the frame buffer into the higher half
    auto physical_address = (uint64_t) m_framebuffer_info->common.framebuffer_addr;
    m_framebuffer_address = (uint64_t *) PhysicalMemoryManager::to_dm_region(physical_address);
    PhysicalMemoryManager::s_current_manager->map_area((physical_address_t *) physical_address, m_framebuffer_address, m_framebuffer_size, Write | Present);
    // Reserve the physical memory
    size_t pages = PhysicalMemoryManager::size_to_frames(m_framebuffer_size);
    PhysicalMemoryManager::s_current_manager->reserve(m_framebuffer_info->common.framebuffer_addr, pages);
    // Log info
    Logger::DEBUG() << "Framebuffer address: physical=0x" << (uint64_t) physical_address << ", virtual=0x" << (uint64_t) m_framebuffer_address << "\n";
    Logger::DEBUG() << "Framebuffer mapped: 0x" << (uint64_t) m_framebuffer_address << " - 0x" << (uint64_t) (m_framebuffer_address + m_framebuffer_size) << " (pages: " << pages << ")\n";
}
References multiboot_tag_framebuffer::common, Logger::DEBUG(), Logger::INFO(), m_bpp, MaxOS::common::GraphicsContext::m_framebuffer_address, m_framebuffer_info, m_framebuffer_size, m_pitch, physical_address, MaxOS::memory::Present, MaxOS::memory::PhysicalMemoryManager::s_current_manager, MaxOS::drivers::video::VideoDriver::set_mode(), MaxOS::memory::PhysicalMemoryManager::size_to_frames(), MaxOS::memory::PhysicalMemoryManager::to_dm_region(), and MaxOS::memory::Write.
~VideoElectronicsStandardsAssociation()
VideoElectronicsStandardsAssociation::~VideoElectronicsStandardsAssociation () [default]
Member Function Documentation
device_name()
string VideoElectronicsStandardsAssociation::device_name () [final], [virtual]
The name of the device.
Returns
The name of the device
Reimplemented from MaxOS::drivers::Driver.
Definition at line 122 of file vesa.cpp.
                                                         {
    return "VESA compatible graphics card";
}
get_rendered_pixel_32_bit()
uint32_t VideoElectronicsStandardsAssociation::get_rendered_pixel_32_bit (uint32_t x, uint32_t y) [final], [protected], [virtual]
Gets the colour of a pixel on the screen in 32 bit mode.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
Returns
The 32bit colour of the pixel
Reimplemented from MaxOS::common::GraphicsContext.
Definition at line 100 of file vesa.cpp.
                                                                                               {
    auto *pixel_address = (uint32_t *) ((uint8_t *) m_framebuffer_address + m_pitch * (y) + m_bpp * (x) / 8);
    return *pixel_address;
}
References m_bpp, MaxOS::common::GraphicsContext::m_framebuffer_address, and m_pitch.
internal_set_mode()
bool VideoElectronicsStandardsAssociation::internal_set_mode (uint32_t width, uint32_t height, uint32_t color_depth) [final], [protected], [virtual]
Sets the mode of the VESA driver.
Parameters
width Width of the screen
height Height of the screen
color_depth Color depth of the screen
Returns
True if the mode was set successfully, false otherwise
Reimplemented from MaxOS::drivers::video::VideoDriver.
Definition at line 54 of file vesa.cpp.
                                                                                                                  {
    // Can only use the mode set up already by grub
    return width == m_framebuffer_info->common.framebuffer_width
           && height == m_framebuffer_info->common.framebuffer_height
           && color_depth == m_framebuffer_info->common.framebuffer_bpp;
}
References MaxOS::common::GraphicsContext::color_depth(), multiboot_tag_framebuffer::common, MaxOS::common::GraphicsContext::height(), m_framebuffer_info, and MaxOS::common::GraphicsContext::width().
render_pixel_32_bit()
void VideoElectronicsStandardsAssociation::render_pixel_32_bit (uint32_t x, uint32_t y, uint32_t colour) [final], [protected], [virtual]
Renders a pixel on the screen in 32 bit mode.
Parameters
x The x coordinate of the pixel
y The y coordinate of the pixel
colour The 32bit colour of the pixel
Reimplemented from MaxOS::common::GraphicsContext.
Definition at line 86 of file vesa.cpp.
                                                                                                      {
    auto *pixel_address = (uint32_t *) ((uint8_t *) m_framebuffer_address + (m_pitch * y) + (m_bpp * x) / 8);
    *pixel_address = colour;
}
References m_bpp, MaxOS::common::GraphicsContext::m_framebuffer_address, and m_pitch.
supports_mode()
bool VideoElectronicsStandardsAssociation::supports_mode (uint32_t width, uint32_t height, uint32_t color_depth) [final], [virtual]
Checks if the VESA driver supports the given mode.
Parameters
width The m_width of the screen
height The m_height of the screen
color_depth The color depth of the screen
Returns
Reimplemented from MaxOS::drivers::video::VideoDriver.
Definition at line 71 of file vesa.cpp.
                                                                                                              {
    // Check if the mode is supported
    return width == m_framebuffer_info->common.framebuffer_width
           && height == m_framebuffer_info->common.framebuffer_height
           && color_depth == m_framebuffer_info->common.framebuffer_bpp;
}
References MaxOS::common::GraphicsContext::color_depth(), multiboot_tag_framebuffer::common, MaxOS::common::GraphicsContext::height(), m_framebuffer_info, and MaxOS::common::GraphicsContext::width().
vendor_name()
string VideoElectronicsStandardsAssociation::vendor_name () [final], [virtual]
The name of the vendor of the VESA standard.
Returns
The name of the vendor
Reimplemented from MaxOS::drivers::Driver.
Definition at line 111 of file vesa.cpp.
                                                         {
    // Creator of the VESA standard
    return "NEC Home Electronics";
}
Member Data Documentation
m_bpp
uint8_t MaxOS::drivers::video::VideoElectronicsStandardsAssociation::m_bpp [protected]
Definition at line 39 of file vesa.h.
Referenced by get_rendered_pixel_32_bit(), render_pixel_32_bit(), and VideoElectronicsStandardsAssociation().
m_framebuffer_info
multiboot_tag_framebuffer* MaxOS::drivers::video::VideoElectronicsStandardsAssociation::m_framebuffer_info [protected]
Definition at line 38 of file vesa.h.
Referenced by internal_set_mode(), supports_mode(), and VideoElectronicsStandardsAssociation().
m_framebuffer_size
size_t MaxOS::drivers::video::VideoElectronicsStandardsAssociation::m_framebuffer_size [protected]
Definition at line 35 of file vesa.h.
Referenced by VideoElectronicsStandardsAssociation().
m_pitch
uint16_t MaxOS::drivers::video::VideoElectronicsStandardsAssociation::m_pitch [protected]
Definition at line 40 of file vesa.h.
Referenced by get_rendered_pixel_32_bit(), render_pixel_32_bit(), and VideoElectronicsStandardsAssociation().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/video/vesa.h
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/video/vesa.cpp