MaxOS::hardwarecommunication::Port8Bit Class Reference
Handles 8 bit ports.
#include <port.h>
Public Member Functions
Port8Bit (uint16_t port_number)
~Port8Bit ()
virtual void write (uint8_t data)
write a byte to the port
virtual uint8_t read ()
read a byte from the port
Additional Inherited Members
Protected Member Functions inherited from MaxOS::hardwarecommunication::Port
Port (uint16_t port_number)
~Port ()
Protected Attributes inherited from MaxOS::hardwarecommunication::Port
uint16_t m_port_number
Detailed Description
Handles 8 bit ports.
Definition at line 28 of file port.h.
Constructor & Destructor Documentation
Port8Bit()
Port8Bit::Port8Bit (uint16_t port_number)
Definition at line 16 of file port.cpp.
: Port(port_number) {
}
~Port8Bit()
Port8Bit::~Port8Bit () [default]
Member Function Documentation
read()
uint8_t Port8Bit::read () [virtual]
read a byte from the port
Returns
the byte read
Definition at line 37 of file port.cpp.
                       {
    uint8_t result;
    asm volatile("inb %1, %0" : "=a" (result) : "Nd" (m_port_number));
    return result;
}
References MaxOS::hardwarecommunication::Port::m_port_number.
Referenced by MaxOS::drivers::peripherals::KeyboardDriver::activate(), MaxOS::drivers::peripherals::MouseDriver::activate(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::flush(), MaxOS::drivers::video::VideoGraphicsArray::get_frame_buffer_segment(), MaxOS::drivers::peripherals::KeyboardDriver::handle_interrupt(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::identify(), MaxOS::drivers::SerialConsole::put_character(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::read(), MaxOS::drivers::clock::Clock::read_hardware_clock(), MaxOS::drivers::SerialConsole::SerialConsole(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::write(), and MaxOS::drivers::video::VideoGraphicsArray::write_registers().
write()
void Port8Bit::write (uint8_t data) [virtual]
write a byte to the port
Parameters
data the byte to write
Reimplemented in MaxOS::hardwarecommunication::Port8BitSlow.
Definition at line 27 of file port.cpp.
                                 {
    asm volatile("outb %0, %1" : : "a" (data), "Nd" (m_port_number));
}
References data, and MaxOS::hardwarecommunication::Port::m_port_number.
Referenced by MaxOS::drivers::peripherals::KeyboardDriver::activate(), MaxOS::drivers::peripherals::MouseDriver::activate(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::flush(), MaxOS::drivers::video::VideoGraphicsArray::get_frame_buffer_segment(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::identify(), MaxOS::drivers::SerialConsole::put_character(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::read(), MaxOS::drivers::clock::Clock::read_hardware_clock(), MaxOS::drivers::SerialConsole::SerialConsole(), MaxOS::drivers::clock::PIT::ticks_per_ms(), MaxOS::drivers::disk::AdvancedTechnologyAttachment::write(), and MaxOS::drivers::video::VideoGraphicsArray::write_registers().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/port.h
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/port.cpp