MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface Class Reference
#include <acpi.h>
Public Member Functions
AdvancedConfigurationAndPowerInterface (system::Multiboot *multiboot)
~AdvancedConfigurationAndPowerInterface ()
ACPISDTHeader * find (const char *signature)
Finds a table with the given signature.
Protected Member Functions
void map_tables (uint8_t size_of_table)
Maps the tables into the higher half.
bool valid_checksum ()
Checks if the checksum is valid.
Static Protected Member Functions
static bool validate (const char *descriptor, size_t length)
Validates the checksum of a descriptor.
Protected Attributes
bool m_using_new_acpi = false
ACPISDTHeader * m_header
XSDT * m_xsdt
RSDT * m_rsdt
RSDPDescriptor * m_rsdp
RSDPDescriptor2 * m_rsdp2
Detailed Description
Definition at line 56 of file acpi.h.
Constructor & Destructor Documentation
AdvancedConfigurationAndPowerInterface()
AdvancedConfigurationAndPowerInterface::AdvancedConfigurationAndPowerInterface (system::Multiboot * multiboot)
Definition at line 13 of file acpi.cpp.
                                                                                                         {
    Logger::INFO() << "Setting up ACPI\n";
    // If the new ACPI is not supported, panic
    ASSERT(multiboot->new_acpi() != nullptr || multiboot->old_acpi() != nullptr, "No ACPI found!");
    // Check if the new ACPI is supported
    m_using_new_acpi = multiboot->old_acpi() == nullptr;
    Logger::DEBUG() << "CPU Supports " << (m_using_new_acpi ? "New" : "Old") << " ACPI\n";
    if (m_using_new_acpi) {
        // Get the RSDP & XSDT
        m_rsdp2 = (RSDPDescriptor2*) (multiboot->new_acpi() + 1);
        m_xsdt = (XSDT*) PhysicalMemoryManager::to_higher_region((uint64_t) m_rsdp2->xsdt_address);
    } else {
        // Get the RSDP & RSDT
        m_rsdp = (RSDPDescriptor*) (multiboot->old_acpi() + 1);
        m_rsdt = (RSDT*) PhysicalMemoryManager::to_higher_region((uint64_t) m_rsdp->rsdt_address);
    }
    // Map the XSDT/RSDT
    uint64_t physical_address = m_using_new_acpi ? m_rsdp2->xsdt_address : m_rsdp->rsdt_address;
    auto virtual_address = (uint64_t) PhysicalMemoryManager::to_higher_region(physical_address);
    PhysicalMemoryManager::s_current_manager->map((physical_address_t*) PhysicalMemoryManager::align_direct_to_page(physical_address), (virtual_address_t*) virtual_address, Present | Write);
    Logger::DEBUG() << "XSDT/RSDT: physical: 0x" << physical_address << ", virtual: 0x" << virtual_address << "\n";
    // Reserve the XSDT/RSDT
    PhysicalMemoryManager::s_current_manager->reserve(m_using_new_acpi ? (uint64_t) m_rsdp2->xsdt_address : (uint64_t) m_rsdp->rsdt_address);
    // Load the header
    m_header = m_using_new_acpi ? &m_xsdt->header : &m_rsdt->header;
    // Map the Tables
    Logger::DEBUG() << "Mapping ACPI Tables\n";
    map_tables(m_using_new_acpi ? sizeof(uint64_t) : sizeof(uint32_t));
    // Check if the checksum is valid
    ASSERT(valid_checksum(), "ACPI: Invalid checksum!");
}
References MaxOS::memory::PhysicalMemoryManager::align_direct_to_page(), ASSERT, Logger::DEBUG(), MaxOS::hardwarecommunication::RSDT::header, MaxOS::hardwarecommunication::XSDT::header, Logger::INFO(), m_header, m_rsdp, m_rsdp2, m_rsdt, m_using_new_acpi, m_xsdt, map_tables(), physical_address, MaxOS::memory::Present, MaxOS::hardwarecommunication::RSDPDescriptor::rsdt_address, MaxOS::memory::PhysicalMemoryManager::s_current_manager, MaxOS::memory::PhysicalMemoryManager::to_higher_region(), valid_checksum(), MaxOS::memory::Write, and MaxOS::hardwarecommunication::RSDPDescriptor2::xsdt_address.
~AdvancedConfigurationAndPowerInterface()
AdvancedConfigurationAndPowerInterface::~AdvancedConfigurationAndPowerInterface () [default]
Member Function Documentation
find()
ACPISDTHeader * AdvancedConfigurationAndPowerInterface::find (const char * signature)
Finds a table with the given signature.
Parameters
signature The signature to search for
Returns
The table with the given signature, or nullptr if not found
Definition at line 106 of file acpi.cpp.
                                                                                 {
    // Get the number of entries
    size_t entries = (m_header->length - sizeof(ACPISDTHeader)) / sizeof(uint32_t);
    if (m_using_new_acpi) entries = (m_header->length - sizeof(ACPISDTHeader)) / sizeof(uint64_t);
    // Loop through all the entries
    for (size_t i = 0; i < entries; ++i) {
        // Get the entry
        auto* header = (ACPISDTHeader*) (m_using_new_acpi ? m_xsdt->pointers[i] : m_rsdt->pointers[i]);
        // Move the header to the higher half
        header = (ACPISDTHeader*) PhysicalMemoryManager::to_io_region((uint64_t) header);
        // Check if the signature matches
        if (strncmp(header->signature, signature, 4) != 0)
            return header;
    }
    // Return null if no entry was found
    return nullptr;
}
References entries, header, MaxOS::hardwarecommunication::ACPISDTHeader::length, m_header, m_rsdt, m_using_new_acpi, m_xsdt, MaxOS::hardwarecommunication::RSDT::pointers, MaxOS::hardwarecommunication::XSDT::pointers, signature, MaxOS::hardwarecommunication::ACPISDTHeader::signature, strncmp(), and MaxOS::memory::PhysicalMemoryManager::to_io_region().
Referenced by MaxOS::hardwarecommunication::IOAPIC::IOAPIC().
map_tables()
void AdvancedConfigurationAndPowerInterface::map_tables (uint8_t size_of_tables) [protected]
Maps the tables into the higher half.
Parameters
size_of_header The size of the tables
Definition at line 63 of file acpi.cpp.
                                                                              {
    for (uint32_t i = 0; i < (m_header->length - sizeof(ACPISDTHeader)) / size_of_tables; i++) {
        // Get the address (aligned to page)
        auto address = (uint64_t) (m_using_new_acpi ? m_xsdt->pointers[i] : m_rsdt->pointers[i]);
        address = PhysicalMemoryManager::align_direct_to_page((size_t) address);
        // Map to the higher half
        PhysicalMemoryManager::s_current_manager->map((physical_address_t*) address, (void*) PhysicalMemoryManager::to_io_region(address), Present | Write);
        // Reserve the memory
        PhysicalMemoryManager::s_current_manager->reserve(address);
    }
}
References address, MaxOS::memory::PhysicalMemoryManager::align_direct_to_page(), MaxOS::hardwarecommunication::ACPISDTHeader::length, m_header, m_rsdt, m_using_new_acpi, m_xsdt, MaxOS::hardwarecommunication::RSDT::pointers, MaxOS::hardwarecommunication::XSDT::pointers, MaxOS::memory::Present, MaxOS::memory::PhysicalMemoryManager::s_current_manager, MaxOS::memory::PhysicalMemoryManager::to_io_region(), and MaxOS::memory::Write.
Referenced by AdvancedConfigurationAndPowerInterface().
valid_checksum()
bool AdvancedConfigurationAndPowerInterface::valid_checksum () [protected]
Checks if the checksum is valid.
Returns
True if the checksum is valid
Definition at line 135 of file acpi.cpp.
                                                            {
    // Get the information about the ACPI
    char* check = m_using_new_acpi ? (char*) m_rsdp2 : (char*) m_rsdp;
    uint32_t length = m_using_new_acpi ? sizeof(RSDPDescriptor2) : sizeof(RSDPDescriptor);
    // Calculate the checksum
    uint8_t sum = 0;
    for (uint32_t i = 0; i < length; i++)
        sum += check[i];
    return sum == 0;
}
References length, m_rsdp, m_rsdp2, and m_using_new_acpi.
Referenced by AdvancedConfigurationAndPowerInterface().
validate()
bool AdvancedConfigurationAndPowerInterface::validate (const char * descriptor, size_t length) [static], [protected]
Validates the checksum of a descriptor.
Parameters
descriptor The descriptor to validate
length The length of the descriptor
Returns
True if the checksum is valid, false otherwise
Definition at line 87 of file acpi.cpp.
                                                                                           {
    // Checksum
    uint32_t sum = 0;
    // Calculate the checksum
    for (uint32_t i = 0; i < length; i++)
        sum += ((char*) descriptor)[i];
    // Check if the checksum is valid
    return ((sum & 0xFF) == 0);
}
References length.
Member Data Documentation
m_header
ACPISDTHeader* MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::m_header [protected]
Definition at line 59 of file acpi.h.
Referenced by AdvancedConfigurationAndPowerInterface(), find(), and map_tables().
m_rsdp
RSDPDescriptor* MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::m_rsdp [protected]
Definition at line 64 of file acpi.h.
Referenced by AdvancedConfigurationAndPowerInterface(), and valid_checksum().
m_rsdp2
RSDPDescriptor2* MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::m_rsdp2 [protected]
Definition at line 65 of file acpi.h.
Referenced by AdvancedConfigurationAndPowerInterface(), and valid_checksum().
m_rsdt
RSDT* MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::m_rsdt [protected]
Definition at line 62 of file acpi.h.
Referenced by AdvancedConfigurationAndPowerInterface(), find(), and map_tables().
m_using_new_acpi
bool MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::m_using_new_acpi = false [protected]
Definition at line 58 of file acpi.h.
Referenced by AdvancedConfigurationAndPowerInterface(), find(), map_tables(), and valid_checksum().
m_xsdt
XSDT* MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::m_xsdt [protected]
Definition at line 61 of file acpi.h.
Referenced by AdvancedConfigurationAndPowerInterface(), find(), and map_tables().
The documentation for this class was generated from the following files:
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/acpi.h
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/acpi.cpp