/home/runner/work/MaxOS/MaxOS/kernel/src/runtime/kasan.cpp File Reference
Implementation of the Kernel Address Sanitizer (KASan) handler.
#include <runtime/kasan.h>
#include <common/logger.h>
Functions
void __asan_load1_noabort (uintptr_t address)
Triggered when a memory load access violation of 1 byte is detected.
void __asan_load2_noabort (uintptr_t address)
Triggered when a memory load access violation of 2 bytes is detected.
void __asan_load4_noabort (uintptr_t address)
Triggered when a memory load access violation of 4 bytes is detected.
void __asan_load8_noabort (uintptr_t address)
Triggered when a memory load access violation of 8 bytes is detected.
void __asan_load16_noabort (uintptr_t address)
Triggered when a memory load access violation of 16 bytes is detected.
void __asan_loadN_noabort (uintptr_t address, size_t size)
Triggered when a memory load access violation of arbitrary size is detected.
void __asan_store1_noabort (uintptr_t address)
Triggered when a memory store access violation of 1 byte is detected.
void __asan_store2_noabort (uintptr_t address)
Triggered when a memory store access violation of 2 bytes is detected.
void __asan_store4_noabort (uintptr_t address)
Triggered when a memory store access violation of 4 bytes is detected.
void __asan_store8_noabort (uintptr_t address)
Triggered when a memory store access violation of 8 bytes is detected.
void __asan_store16_noabort (uintptr_t address)
Triggered when a memory store access violation of 16 bytes is detected.
void __asan_storeN_noabort (uintptr_t address, size_t size)
Triggered when a memory store access violation of arbitrary size is detected.
void __asan_handle_no_return ()
Triggered when a function that is expected to not return does return.
void __asan_alloca_poison (uintptr_t address, size_t size)
Poisons a region of stack memory allocated with alloca.
void __asan_alloca_unpoison (void *stack_top, void *stack_bottom)
Unpoisons a region of stack memory allocated with alloca.
void __asan_set_shadow_00 (void *pointer, size_t size)
Unpoisons a region of memory, marking it as accessible.
void __asan_set_shadow_f8 (void *pointer, size_t size)
Poisons a region of memory, marking it as inaccessible.
void __asan_before_dynamic_init (const void *module_name)
Called before dynamic initialization of a module.
void __asan_after_dynamic_init (const void *module_name)
Called after dynamic initialization of a module.
Detailed Description
Implementation of the Kernel Address Sanitizer (KASan) handler.
Date
22nd November 2025
Author
Max Tyson
Definition in file kasan.cpp.
Function Documentation
__asan_after_dynamic_init()
void __asan_after_dynamic_init (const void * module_name)
Called after dynamic initialization of a module.
Parameters
module_name The name of the module that was initialized
Definition at line 239 of file kasan.cpp.
                                                                    {
    // Nothing to do
 }
__asan_alloca_poison()
void __asan_alloca_poison (uintptr_t address, size_t size)
Poisons a region of stack memory allocated with alloca.
Parameters
address The starting address of the allocated memory
size The size of the allocated memory in bytes
Definition at line 181 of file kasan.cpp.
                                                                     {
    //TODO: Implement stack poisoning
    ASSERT(false, "KASAN ERROR: Stack poisoning not implemented for address 0x%lx of size %zu", address, size);
}
References ASSERT.
__asan_alloca_unpoison()
void __asan_alloca_unpoison (void * stack_top, void * stack_bottom)
Unpoisons a region of stack memory allocated with alloca.
Parameters
stack_top The top address of the allocated memory
stack_bottom The bottom address of the allocated memory
Definition at line 192 of file kasan.cpp.
                                                                            {
    //TODO: Implement stack unpoisoning
    ASSERT(false, "KASAN ERROR: Stack unpoisoning not implemented for range 0x%p - 0x%p", stack_bottom, stack_top);
}
References ASSERT.
__asan_before_dynamic_init()
void __asan_before_dynamic_init (const void * module_name)
Called before dynamic initialization of a module.
Parameters
module_name The name of the module being initialized
Definition at line 230 of file kasan.cpp.
                                                                    {
    // Nothing to do
}
__asan_handle_no_return()
void __asan_handle_no_return ()
Triggered when a function that is expected to not return does return.
Definition at line 171 of file kasan.cpp.
                                          {
    ASSERT(false, "KASAN ERROR: Function marked 'noreturn' has returned");
}
References ASSERT.
__asan_load16_noabort()
void __asan_load16_noabort (uintptr_t address)
Triggered when a memory load access violation of 16 bytes is detected.
Parameters
address The address that was accessed
Definition at line 99 of file kasan.cpp.
                                                         {
    KASanHandler::handle(false, address, 16, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_load1_noabort()
void __asan_load1_noabort (uintptr_t address)
Triggered when a memory load access violation of 1 byte is detected.
Parameters
address The address that was accessed
Definition at line 63 of file kasan.cpp.
                                                        {
    KASanHandler::handle(false, address, 1, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_load2_noabort()
void __asan_load2_noabort (uintptr_t address)
Triggered when a memory load access violation of 2 bytes is detected.
Parameters
address The address that was accessed
Definition at line 72 of file kasan.cpp.
                                                        {
    KASanHandler::handle(false, address, 2, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_load4_noabort()
void __asan_load4_noabort (uintptr_t address)
Triggered when a memory load access violation of 4 bytes is detected.
Parameters
address The address that was accessed
Definition at line 81 of file kasan.cpp.
                                                        {
    KASanHandler::handle(false, address, 4, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_load8_noabort()
void __asan_load8_noabort (uintptr_t address)
Triggered when a memory load access violation of 8 bytes is detected.
Parameters
address The address that was accessed
Definition at line 90 of file kasan.cpp.
                                                        {
    KASanHandler::handle(false, address, 8, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_loadN_noabort()
void __asan_loadN_noabort (uintptr_t address, size_t size)
Triggered when a memory load access violation of arbitrary size is detected.
Parameters
address The address that was accessed
size The size of the access in bytes
Definition at line 109 of file kasan.cpp.
                                                                     {
    KASanHandler::handle(false, address, size, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_set_shadow_00()
void __asan_set_shadow_00 (void * pointer, size_t size)
Unpoisons a region of memory, marking it as accessible.
Parameters
pointer The starting address of the memory
size The size of the memory region in bytes
Definition at line 203 of file kasan.cpp.
                                                                 {
    // Clear the memory to mark it as unpoisoned
    for(int i = 0; i < size; ++i)
        ((int8_t*)pointer)[i] = 0;
}
__asan_set_shadow_f8()
void __asan_set_shadow_f8 (void * pointer, size_t size)
Poisons a region of memory, marking it as inaccessible.
Parameters
pointer The starting address of the memory
size The size of the memory region in bytes
Definition at line 217 of file kasan.cpp.
                                                                {
    // Fill the memory to mark it as poisoned
    for(int i = 0; i < size; ++i)
        ((int8_t*)pointer)[i] = 0xF8;
}
__asan_store16_noabort()
void __asan_store16_noabort (uintptr_t address)
Triggered when a memory store access violation of 16 bytes is detected.
Parameters
address The address that was accessed
Definition at line 154 of file kasan.cpp.
                                                          {
    KASanHandler::handle(true, address, 16, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_store1_noabort()
void __asan_store1_noabort (uintptr_t address)
Triggered when a memory store access violation of 1 byte is detected.
Parameters
address The address that was accessed
Definition at line 118 of file kasan.cpp.
                                                         {
    KASanHandler::handle(true, address, 1, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_store2_noabort()
void __asan_store2_noabort (uintptr_t address)
Triggered when a memory store access violation of 2 bytes is detected.
Parameters
address The address that was accessed
Definition at line 127 of file kasan.cpp.
                                                         {
    KASanHandler::handle(true, address, 2, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_store4_noabort()
void __asan_store4_noabort (uintptr_t address)
Triggered when a memory store access violation of 4 bytes is detected.
Parameters
address The address that was accessed
Definition at line 136 of file kasan.cpp.
                                                         {
    KASanHandler::handle(true, address, 4, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_store8_noabort()
void __asan_store8_noabort (uintptr_t address)
Triggered when a memory store access violation of 8 bytes is detected.
Parameters
address The address that was accessed
Definition at line 145 of file kasan.cpp.
                                                         {
    KASanHandler::handle(true, address, 8, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().
__asan_storeN_noabort()
void __asan_storeN_noabort (uintptr_t address, size_t size)
Triggered when a memory store access violation of arbitrary size is detected.
Parameters
address The address that was accessed
size The size of the access in bytes
Definition at line 164 of file kasan.cpp.
                                                                      {
    KASanHandler::handle(false, address, size, __builtin_return_address(0));
}
References MaxOS::runtime::KASanHandler::handle().