/home/runner/work/MaxOS/MaxOS/kernel/include/memory/memorymanagement.h File Reference
Defines a MemoryManager class for handling memory allocation and deallocation.
#include <cstddef>
#include <cstdint>
#include <system/multiboot.h>
#include <memory/virtual.h>
Classes
struct MaxOS::memory::MemoryChunk
A span of memory in the heap, can be allocated or free. Used as a node in a doubly linked list.
class MaxOS::memory::MemoryManager
Handles memory allocation and deallocation.
Functions
void * operator new (size_t size) throw ()
Overloaded new operator, allocates memory using the KERNEL memory manager.
void * operator new[] (size_t size) throw ()
Overloaded new operator, allocates memory using the KERNEL memory manager.
void * operator new (size_t size, void *pointer)
Overloaded new operator, allocates memory using the KERNEL memory manager.
void * operator new[] (size_t size, void *pointer)
Overloaded new operator, allocates memory using the KERNEL memory manager.
void operator delete (void *pointer)
Overloaded delete operator, frees memory using the KERNEL memory manager.
void operator delete[] (void *pointer)
Overloaded delete operator, frees memory using the KERNEL memory manager.
void operator delete (void *pointer, size_t size)
Overloaded delete operator, frees memory using the KERNEL memory manager.
void operator delete[] (void *pointer, size_t size)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Variables
constexpr size_t MaxOS::memory::CHUNK_ALIGNMENT = 0x10
How many bytes the chunks should be a multiple of (round up to this)
Detailed Description
Defines a MemoryManager class for handling memory allocation and deallocation.
Date
20th October 2022
Author
Max Tyson
Definition in file memorymanagement.h.
Function Documentation
operator delete() [1/2]
void operator delete (void * pointer)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to free
Definition at line 379 of file memorymanagement.cpp.
                                    {
    // Handle the memory freeing
    return MaxOS::memory::MemoryManager::kfree(pointer);
}
References MaxOS::memory::MemoryManager::kfree().
operator delete() [2/2]
void operator delete (void * pointer, size_t size)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to free
size The size of the memory to free - ignored in this implementation
Definition at line 402 of file memorymanagement.cpp.
                                            {
    // Handle the memory freeing
    return MaxOS::memory::MemoryManager::kfree(pointer);
}
References MaxOS::memory::MemoryManager::kfree().
operator delete[]() [1/2]
void operator delete[] (void * pointer)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to free
Definition at line 390 of file memorymanagement.cpp.
                                      {
    // Handle the memory freeing
    return MaxOS::memory::MemoryManager::kfree(pointer);
}
References MaxOS::memory::MemoryManager::kfree().
operator delete[]() [2/2]
void operator delete[] (void * pointer, size_t size)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to free
size The size of the memory to free - ignored in this implementation
Definition at line 414 of file memorymanagement.cpp.
                                                   {
    // Handle the memory freeing
    return MaxOS::memory::MemoryManager::kfree(pointer);
}
References MaxOS::memory::MemoryManager::kfree().
operator new() [1/2]
void * operator new (size_t size) throw ()
Overloaded new operator, allocates memory using the KERNEL memory manager.
Parameters
size The size of the memory to allocate
Returns
The pointer to the allocated memory
Definition at line 331 of file memorymanagement.cpp.
                                        {
    // Handle the memory allocation
    return MaxOS::memory::MemoryManager::kmalloc(size);
}
References MaxOS::memory::MemoryManager::kmalloc().
operator new() [2/2]
void * operator new (size_t size, void * pointer)
Overloaded new operator, allocates memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to allocate
size The size of the memory to free - ignored in this implementation
Returns
The pointer to the memory
Definition at line 356 of file memorymanagement.cpp.
                                               {
    return pointer;
}
operator new[]() [1/2]
void * operator new[] (size_t size) throw ()
Overloaded new operator, allocates memory using the KERNEL memory manager.
Parameters
size The size of the memory to allocate
Returns
The pointer to the allocated memory
Definition at line 343 of file memorymanagement.cpp.
                                          {
    // Handle the memory allocation
    return MaxOS::memory::MemoryManager::kmalloc(size);
}
References MaxOS::memory::MemoryManager::kmalloc().
operator new[]() [2/2]
void * operator new[] (size_t size, void * pointer)
Overloaded new operator, allocates memory using the KERNEL memory manager.
Parameters
size The size of the memory to free - ignored in this implementation
pointer The pointer to the memory to allocate
Returns
The pointer to the memory
Definition at line 368 of file memorymanagement.cpp.
                                                 {
    return pointer;
}
Variable Documentation
CHUNK_ALIGNMENT
constexpr size_t MaxOS::memory::CHUNK_ALIGNMENT = 0x10 [constexpr]
How many bytes the chunks should be a multiple of (round up to this)
Definition at line 34 of file memorymanagement.h.
Referenced by MaxOS::memory::MemoryManager::align().