/home/runner/work/MaxOS/MaxOS/kernel/src/memory/memorymanagement.cpp File Reference
Implementation of a Memory Manager for dynamic memory allocation.
#include <memory/memorymanagement.h>
#include <common/logger.h>
Functions
void * operator new (size_t size) throw ()
Overloaded new operator, allocates memory using the KERNEL memory manager.
void * operator new[] (size_t size) throw ()
Overloaded new operator, allocates memory using the KERNEL memory manager.
void * operator new (size_t size, void *pointer)
Overloaded new operator, allocates memory using the KERNEL memory manager.
void * operator new[] (size_t size, void *pointer)
Overloaded new operator, allocates memory using the KERNEL memory manager.
void operator delete (void *pointer)
Overloaded delete operator, frees memory using the KERNEL memory manager.
void operator delete[] (void *pointer)
Overloaded delete operator, frees memory using the KERNEL memory manager.
void operator delete (void *pointer, size_t)
Overloaded delete operator, frees memory using the KERNEL memory manager.
void operator delete[] (void *pointer, size_t size)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Detailed Description
Implementation of a Memory Manager for dynamic memory allocation.
Date
20th October 2022
Author
Max Tyson
Definition in file memorymanagement.cpp.
Function Documentation
operator delete() [1/2]
void operator delete (void * pointer)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to free
Definition at line 377 of file memorymanagement.cpp.
                                    {
    // Handle the memory freeing
    return MaxOS::memory::MemoryManager::kfree(pointer);
}
References MaxOS::memory::MemoryManager::kfree().
operator delete() [2/2]
void operator delete (void * pointer, size_t size)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to free
size The size of the memory to free - ignored in this implementation
Definition at line 400 of file memorymanagement.cpp.
                                            {
    // Handle the memory freeing
    return MaxOS::memory::MemoryManager::kfree(pointer);
}
References MaxOS::memory::MemoryManager::kfree().
operator delete[]() [1/2]
void operator delete[] (void * pointer)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to free
Definition at line 388 of file memorymanagement.cpp.
                                      {
    // Handle the memory freeing
    return MaxOS::memory::MemoryManager::kfree(pointer);
}
References MaxOS::memory::MemoryManager::kfree().
operator delete[]() [2/2]
void operator delete[] (void * pointer, size_t size)
Overloaded delete operator, frees memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to free
size The size of the memory to free - ignored in this implementation
Definition at line 412 of file memorymanagement.cpp.
                                                   {
    // Handle the memory freeing
    return MaxOS::memory::MemoryManager::kfree(pointer);
}
References MaxOS::memory::MemoryManager::kfree().
operator new() [1/2]
void * operator new (size_t size) throw ()
Overloaded new operator, allocates memory using the KERNEL memory manager.
Parameters
size The size of the memory to allocate
Returns
The pointer to the allocated memory
Definition at line 329 of file memorymanagement.cpp.
                                        {
    // Handle the memory allocation
    return MaxOS::memory::MemoryManager::kmalloc(size);
}
References MaxOS::memory::MemoryManager::kmalloc(), and size.
operator new() [2/2]
void * operator new (size_t size, void * pointer)
Overloaded new operator, allocates memory using the KERNEL memory manager.
Parameters
pointer The pointer to the memory to allocate
size The size of the memory to free - ignored in this implementation
Returns
The pointer to the memory
Definition at line 354 of file memorymanagement.cpp.
                                               {
    return pointer;
}
operator new[]() [1/2]
void * operator new[] (size_t size) throw ()
Overloaded new operator, allocates memory using the KERNEL memory manager.
Parameters
size The size of the memory to allocate
Returns
The pointer to the allocated memory
Definition at line 341 of file memorymanagement.cpp.
                                          {
    // Handle the memory allocation
    return MaxOS::memory::MemoryManager::kmalloc(size);
}
References MaxOS::memory::MemoryManager::kmalloc(), and size.
operator new[]() [2/2]
void * operator new[] (size_t size, void * pointer)
Overloaded new operator, allocates memory using the KERNEL memory manager.
Parameters
size The size of the memory to free - ignored in this implementation
pointer The pointer to the memory to allocate
Returns
The pointer to the memory
Definition at line 366 of file memorymanagement.cpp.
                                                 {
    return pointer;
}