/home/runner/work/MaxOS/MaxOS/kernel/include/memory/memoryIO.h File Reference
Defines classes for memory input and output operations of various bit widths (8, 16, 32, 64 bits).
#include <stdint.h>
#include <stddef.h>
Classes
class MaxOS::memory::MemIO
base class for all memory IO
class MaxOS::memory::MemIO8Bit
Handles 8 bit memory IO.
class MaxOS::memory::MemIO16Bit
Handles 16 bit memory IO.
class MaxOS::memory::MemIO32Bit
Handles 32 bit memory IO.
class MaxOS::memory::MemIO64Bit
Handles 64 bit memory IO.
Functions
void * memcpy (void *destination, const void *source, uint64_t num)
Copies a block of memory from one location to another.
void * memset (void *ptr, uint32_t value, uint64_t num)
Fills a block of memory with a specified value.
void * memmove (void *destination, const void *source, uint64_t num)
Copies a block of memory from one location to another.
int memcmp (const void *ptr1, const void *ptr2, uint64_t num)
Compares two blocks of memory.
Detailed Description
Defines classes for memory input and output operations of various bit widths (8, 16, 32, 64 bits).
Date
29th November 2022
Author
Max Tyson
Definition in file memoryIO.h.
Function Documentation
memcmp()
int memcmp (const void * ptr1, const void * ptr2, uint64_t num)
Compares two blocks of memory.
Parameters
ptr1 The m_first_memory_chunk block of memory
ptr2 The second block of memory
num The number of bytes to compare
Returns
0 if the blocks of memory are equal, -1 if ptr1 < ptr2, 1 if ptr1 > ptr2
Definition at line 265 of file memoryIO.cpp.
                                                             {
    // Make sure the pointers exist
    if (ptr1 == nullptr || ptr2 == nullptr)
        return 0;
    const auto* p1 = (const unsigned char*) ptr1;
    const auto* p2 = (const unsigned char*) ptr2;
    for (size_t i = 0; i < num; i++) {
        if (p1[i] < p2[i])
            return -1;
        if (p1[i] > p2[i])
            return 1;
    }
    return 0;
}
memcpy()
void * memcpy (void * destination, const void * source, uint64_t num)
Copies a block of memory from one location to another.
See also
 https://wiki.osdev.org/Meaty_Skeleton#memcpy.28.29
Parameters
destination The destination to copy to
source The source to copy from
num The number of bytes to copy
Returns
The destination
Definition at line 165 of file memoryIO.cpp.
                                                                  {
    // Make sure the source and destination are not the same
    if (destination == source)
        return destination;
    // Make sure they exist
    if (destination == nullptr || source == nullptr)
        return destination;
    // Get the source and destination
    auto* dst = (unsigned char*) destination;
    const auto* src = (const unsigned char*) source;
    // Copy the data
    for (size_t i = 0; i < num; i++)
        dst[i] = src[i];
    // Usefully for easier code writing
    return destination;
}
References destination, and source.
Referenced by MaxOS::common::Buffer::copy_from(), MaxOS::common::Buffer::copy_from(), MaxOS::common::Buffer::copy_to(), MaxOS::common::Buffer::copy_to(), MaxOS::filesystem::format::ext2::Ext2Volume::Ext2Volume(), MaxOS::processes::SharedMessageEndpoint::read(), MaxOS::common::Buffer::resize(), and MaxOS::processes::Thread::Thread().
memmove()
void * memmove (void * destination, const void * source, uint64_t num)
Copies a block of memory from one location to another.
Parameters
destination The destination to copy to
source The source to copy from
num The number of bytes to copy
Returns
The destination
Definition at line 235 of file memoryIO.cpp.
                                                                   {
    // Make sure the source and destination are not the same
    if (destination == source)
        return destination;
    // Make sure they exist
    if (destination == nullptr || source == nullptr)
        return destination;
    auto* dst = (unsigned char*) destination;
    const auto* src = (const unsigned char*) source;
    if (dst < src) {
        for (size_t i = 0; i < num; i++)
            dst[i] = src[i];
    } else {
        for (size_t i = num; i != 0; i--)
            dst[i - 1] = src[i - 1];
    }
    return destination;
}
References destination, and source.
Referenced by MaxOS::drivers::console::VESABootConsole::scroll_up().
memset()
void * memset (void * ptr, uint32_t value, uint64_t num)
Fills a block of memory with a specified value.
Parameters
ptr The pointer to the block of memory
value The value to fill the block of memory with
num The number of bytes to fill
Returns
The pointer to the block of memory
Definition at line 215 of file memoryIO.cpp.
                                                      {
    // Make sure the pointer exists
    if (ptr == nullptr)
        return ptr;
    auto* dst = (uint32_t*) ptr;
    for (size_t i = 0; i < num; i++)
        dst[i] = value;
    return ptr;
}
Referenced by MaxOS::common::Buffer::clear(), MaxOS::common::Buffer::full(), and MaxOS::drivers::console::VESABootConsole::print_logo().