/home/runner/work/MaxOS/MaxOS/kernel/include/common/string.h File Reference
Defines a String class for dynamically sized strings with various operations.
#include <stdint.h>
#include <common/vector.h>
#include <stdarg.h>
Classes
class MaxOS::String
Dynamically sized string with various operations.
class MaxOS::StringBuilder
Creates a string using a using a combination of parts with the '<<' operator. Simmilar to the logger.
Typedefs
typedef class MaxOS::String MaxOS::string
Typedef for String.
Functions
int strlen (const char *str)
Gets the length of a string.
char * itoa (int base, int64_t number)
Converts integer to string.
char * htoa (uint64_t number)
Converts hex to string.
char * ftoa (float number)
Converts a float to a string.
bool strcmp (char const *str1, char const *str2)
Checks if one string pointer is equal to another string pointer.
bool strcmp (char const *str1, MaxOS::String const &str2)
Checks if one string pointer is equal to a String.
bool strcmp (MaxOS::String const &str1, char const *str2)
Checks if one String is equal to a string pointer.
bool strcmp (MaxOS::String const &str1, MaxOS::String const &str2)
Checks if one String is equal to another String (better use is of "==")
bool strncmp (char const *str1, char const *str2, int length)
Checks if one string pointer is equal to another string pointer up to a specified length (each must be >= this length)
bool strncmp (char const *str1, MaxOS::String const &str2, int length)
Checks if one string pointer is equal to another String up to a specified length (each must be >= this length)
bool strncmp (MaxOS::String const &str1, char const *str2, int length)
Checks if one String is equal to another string pointer up to a specified length (each must be >= this length)
bool strncmp (MaxOS::String const &str1, MaxOS::String const &str2, int length)
Checks if one String is equal to another String up to a specified length (each must be >= this length)
Variables
constexpr int MaxOS::MAX_STRING_SMALL_STORAGE = 0x99
How many characters can be stored in the small string optimization array.
Detailed Description
Defines a String class for dynamically sized strings with various operations.
Date
12th April 2023
Author
Max Tyson
Definition in file string.h.
Function Documentation
ftoa()
char * ftoa (float number)
Converts a float to a string.
Parameters
number The number to convert
Returns
The converted string
Definition at line 773 of file string.cpp.
                         {
    static char buffer[50];
    char *ptr = buffer;
    // Handle negative numbers.
    if (number < 0) {
        *ptr++ = '-';
        number = -number;
    }
    // Separate integer and fractional parts.
    int64_t intPart = (int64_t) number;
    float fraction = number - (float) intPart;
    // Convert integer part to string using itoa.
    char *intStr = itoa(10, intPart);
    while (*intStr) {
        *ptr++ = *intStr++;
    }
    // Add the decimal point.
    *ptr++ = '.';
    // Define the desired precision for the fractional part.
    const int precision = 6;
    // Multiply the fraction to shift the decimal digits into integer range.
    float fracValue = fraction;
    for (int i = 0; i < precision; i++) {
        fracValue *= 10.0f;
    }
    // Optionally, round the value.
    auto fracInt = (int64_t) (fracValue + 0.5f);
    // Convert the fractional part to string.
    char fracBuffer[50];
    char *fracStr = itoa(10, fracInt);
    // Ensure we have leading zeros if the fractional part doesn't produce enough digits.
    // Calculate length of the converted fractional string.
    int len = 0;
    for (char *p = fracStr; *p; p++) {
        len++;
    }
    for (int i = 0; i < precision - len; i++) {
        *ptr++ = '0';
    }
    // Copy the fractional digits.
    while (*fracStr) {
        *ptr++ = *fracStr++;
    }
    // Null-terminate the string.
    *ptr = '\0';
    return buffer;
}
References itoa().
Referenced by MaxOS::String::String().
htoa()
char * htoa (uint64_t number)
Converts hex to string.
Parameters
number The number to convert
Returns
The converted string
Definition at line 751 of file string.cpp.
                            {
    // If there is no buffer use a default buffer
    static char buffer[50] = {0};
    int i = 49;
    if (number == 0) {
        buffer[i] = '0';
        return &buffer[i];
    }
    for (; number && i; --i, number /= 16)
        buffer[i] = "0123456789ABCDEF"[number % 16];
    return &buffer[i + 1];
}
Referenced by MaxOS::String::String(), and MaxOS::common::OutputStream::write_hex().
itoa()
char * itoa (int base, int64_t number)
Converts integer to string.
Parameters
base The base of the number (10 for decimal, 16 for hex)
number The number to convert
Returns
The converted string
Definition at line 720 of file string.cpp.
                                     {
    // If there is no buffer use a default buffer
    static char buffer[50] = {0};
    int i = 49;
    bool isNegative = number < 0;
    if (number == 0) {
        buffer[i] = '0';
        return &buffer[i];
    }
    for (; number && i; --i, number /= base)
        buffer[i] = "0123456789ABCDEF"[number % base];
    if (isNegative) {
        buffer[i] = '-';
        return &buffer[i];
    }
    return &buffer[i + 1];
}
References base.
Referenced by ftoa(), MaxOS::String::String(), and MaxOS::common::OutputStream::write_int().
strcmp() [1/4]
bool strcmp (char const * str1, char const * str2)
Checks if one string pointer is equal to another string pointer.
Parameters
str1 The first string
str2 The second string
Returns
True if the strings are equal, false otherwise
Definition at line 841 of file string.cpp.
                                                {
    // Check if the strings are equal
    for (int i = 0; str1[i] != '\0' || str2[i] != '\0'; i++)
        if (str1[i] != str2[i])
            return false;
    // The strings are equal
    return true;
}
Referenced by MaxOS::drivers::console::VESABootConsole::put_character(), strcmp(), strcmp(), and strcmp().
strcmp() [2/4]
bool strcmp (char const * str1, String const & str2)
Checks if one string pointer is equal to a String.
Parameters
str1 The first string
str2 The second string
Returns
True if the strings are equal, false otherwise
Definition at line 860 of file string.cpp.
                                                  {
    // Use the other strcmp function
    return strcmp(str1, str2.c_str());
}
References MaxOS::String::c_str(), and strcmp().
strcmp() [3/4]
bool strcmp (String const & str1, char const * str2)
Checks if one String is equal to a string pointer.
Parameters
str1 The first string
str2 The second string
Returns
True if the strings are equal, false otherwise
Definition at line 874 of file string.cpp.
                                                  {
    // Use the other strcmp function
    return strcmp(str1.c_str(), str2);
}
References MaxOS::String::c_str(), and strcmp().
strcmp() [4/4]
bool strcmp (String const & str1, String const & str2)
Checks if one String is equal to another String (better use is of "==")
Parameters
str1 The first string
str2 The second string
Returns
True if the strings are equal, false otherwise
Definition at line 887 of file string.cpp.
                                                    {
    // Use the other strcmp function
    return strcmp(str1.c_str(), str2.c_str());
}
References MaxOS::String::c_str(), and strcmp().
strlen()
int strlen (const char * str)
Gets the length of a string.
Parameters
str The string to get the length of
Returns
The length of the string
Definition at line 706 of file string.cpp.
                            {
    int len = 0;
    for (; str[len] != '\0'; len++);
    return len;
}
Referenced by MaxOS::String::String(), MaxOS::String::String(), and MaxOS::String::String().
strncmp() [1/4]
bool strncmp (char const * str1, char const * str2, int length)
Checks if one string pointer is equal to another string pointer up to a specified length (each must be >= this length)
Parameters
str1 The first string
str2 The second string
length The length of the string to compare
Returns
True if the strings are equal, false otherwise
Definition at line 902 of file string.cpp.
                                                             {
    // Check if the strings are equal
    for (int i = 0; i < length; i++)
        if (str1[i] != str2[i])
            return false;
    // Strings are equal
    return true;
}
References length.
Referenced by MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::find(), strncmp(), strncmp(), and strncmp().
strncmp() [2/4]
bool strncmp (char const * str1, String const & str2, int length)
Checks if one string pointer is equal to another String up to a specified length (each must be >= this length)
Parameters
str1 The first string
str2 The second string
length The length of the string to compare
Returns
True if the strings are equal, false otherwise
Definition at line 922 of file string.cpp.
                                                               {
    // Use the other strncmp function
    return strncmp(str1, str2.c_str(), length);
}
References MaxOS::String::c_str(), length, and strncmp().
strncmp() [3/4]
bool strncmp (String const & str1, char const * str2, int length)
Checks if one String is equal to another string pointer up to a specified length (each must be >= this length)
Parameters
str1 The first string
str2 The second string
length The length of the string to compare
Returns
True if the strings are equal, false otherwise
Definition at line 937 of file string.cpp.
                                                               {
    // Use the other strncmp function
    return strncmp(str1.c_str(), str2, length);
}
References MaxOS::String::c_str(), length, and strncmp().
strncmp() [4/4]
bool strncmp (String const & str1, String const & str2, int length)
Checks if one String is equal to another String up to a specified length (each must be >= this length)
Parameters
str1 The first string
str2 The second string
length The length of the string to compare
Returns
True if the strings are equal, false otherwise
Definition at line 952 of file string.cpp.
                                                                 {
    // Use the other strncmp function
    return strncmp(str1.c_str(), str2.c_str(), length);
}
References MaxOS::String::c_str(), length, and strncmp().
Variable Documentation
MAX_STRING_SMALL_STORAGE
constexpr int MaxOS::MAX_STRING_SMALL_STORAGE = 0x99 [constexpr]
How many characters can be stored in the small string optimization array.
Definition at line 20 of file string.h.