/home/runner/work/MaxOS/MaxOS/kernel/src/common/symbols.cpp File Reference
Implementation of symbol resolution for instruction pointers.
#include <common/symbols.h>
Functions
const char * MaxOS::common::resolve_symbol (uintptr_t rip, uintptr_t link_base, uintptr_t load_base)
Resolve an instruction pointer (rip) to a symbol name and optional offset.
Detailed Description
Implementation of symbol resolution for instruction pointers.
Date
10th September 2025
Author
Max Tyson
Definition in file symbols.cpp.
Function Documentation
resolve_symbol()
const char * MaxOS::common::resolve_symbol (uintptr_t rip, uintptr_t link_base, uintptr_t load_base)
Resolve an instruction pointer (rip) to a symbol name and optional offset.
Parameters
rip Instruction pointer
link_base Where the kernel is linked at
load_base Where the kernel is loaded at
Returns
The symbol name
Definition at line 24 of file symbols.cpp.
        {
            // No symbols
            if (KERNEL_SYMBOLS_COUNT == 0)
                return nullptr;
            // Convert load to linked
            uintptr_t offset = 0;
            if (load_base >= link_base)
                offset = load_base - link_base;
            // Get the adjusted address
            uintptr_t adjusted_address = rip;
            if (rip >= offset)
                adjusted_address = rip - offset;
            // Binary Search for symbol
            size_t left = 0;
            size_t right = KERNEL_SYMBOLS_COUNT;
            while (left < right) {
                size_t middle = (left + right) >> 1;
                if (kernel_symbols[middle].address <= adjusted_address)
                    left = middle + 1;
                else
                    right = middle;
            }
            return left == 0 ? nullptr : kernel_symbols[left - 1].name;
        }
References MaxOS::common::resolve_symbol(), and rip.
Referenced by MaxOS::common::resolve_symbol(), and MaxOS::system::CPU::stack_trace().