/home/runner/work/MaxOS/MaxOS/kernel/src/net/tcp.cpp File Reference
Implementation of Transmission Control Protocol (TCP) classes and handlers.
#include <net/tcp.h>
#include "net/udp.h"
Functions
uint32_t big_endian_32 (uint32_t x)
Convert a 32-bit integer to big-endian format.
uint32_t big_endian_16 (uint16_t x)
Convert a 16-bit integer to big-endian format.
Detailed Description
Implementation of Transmission Control Protocol (TCP) classes and handlers.
Date
26th March 2024
Author
Max Tyson
Definition in file tcp.cpp.
Function Documentation
big_endian_16()
uint32_t big_endian_16 (uint16_t x)
Convert a 16-bit integer to big-endian format.
Parameters
x The 16-bit integer to convert
Returns
The big-endian formatted integer
Definition at line 187 of file tcp.cpp.
                                   {
    return ((x & 0xFF00) >> 8)
           | ((x & 0x00FF) << 8);
}
Referenced by MaxOS::net::TransmissionControlProtocolHandler::handle_internet_protocol_payload(), and MaxOS::net::TransmissionControlProtocolHandler::send_transmission_control_protocol_packet().
big_endian_32()
uint32_t big_endian_32 (uint32_t x)
Convert a 32-bit integer to big-endian format.
Parameters
x The 32-bit integer to convert
Returns
The big-endian formatted integer
Definition at line 174 of file tcp.cpp.
                                   {
    return ((x & 0xFF000000) >> 24)
           | ((x & 0x00FF0000) >> 8)
           | ((x & 0x0000FF00) << 8)
           | ((x & 0x000000FF) << 24);
}
Referenced by MaxOS::net::TransmissionControlProtocolHandler::handle_internet_protocol_payload(), and MaxOS::net::TransmissionControlProtocolHandler::send_transmission_control_protocol_packet().