/home/runner/work/MaxOS/MaxOS/kernel/include/tests/test.h File Reference
Defines a basic test class for MaxOS.
#include <common/string.h>
#include <common/logger.h>
#include <common/macros.h>
Classes
class MaxOS::tests::Test
A basic test class.
class MaxOS::tests::ConditionalTest
A test that only checks a condition to determine pass/fail.
class MaxOS::tests::TestRunner
A class to run all tests.
Macros
#define MAXOS_CONDITIONAL_TEST(name, type) auto CONCATENATE(test_, __COUNTER__) = new ConditionalTest(#name, type, []()
Simplified macro to define a conditional test.
Enumerations
enum class MaxOS::tests::TestStatus { PASS
, FAIL
, SKIP
 }
The possible outcomes of a test.
enum class MaxOS::tests::TestType {
COMMON
, DRIVER
, FILESYSTEM
, GUI
,
HARDWARE_COMMUNICATION
, MEMORY
, NETWORK
, PROCESSES
,
RUNTIME
, SYSTEM
, MAX_TEST_TYPES
 }
The different types of tests.
Functions
template<typename T1 , typename T2 >
bool MaxOS::tests::compare (T1 const &actual, T2 const &expected)
Compares two values and logs a warning if they are not equal.
Variables
constexpr const char * MaxOS::tests::TEST_TYPE_STRINGS []
String representations of the TestType enum.
Detailed Description
Defines a basic test class for MaxOS.
Date
23rd November 2025
Author
Max Tyson
Definition in file test.h.
Macro Definition Documentation
MAXOS_CONDITIONAL_TEST
#define MAXOS_CONDITIONAL_TEST(name, type) auto CONCATENATE(test_, __COUNTER__) = new ConditionalTest(#name, type, []()
Simplified macro to define a conditional test.
Definition at line 17 of file test.h.
                     {
    enum class TestStatus {
        PASS,
        FAIL,
        SKIP
    };
    enum class TestType {
        COMMON,
        DRIVER,
        FILESYSTEM,
        GUI,
        HARDWARE_COMMUNICATION,
        MEMORY,
        NETWORK,
        PROCESSES,
        RUNTIME,
        SYSTEM,
        MAX_TEST_TYPES
    };
    constexpr const char* TEST_TYPE_STRINGS[] = {
        "COMMON",
        "DRIVER",
        "FILESYSTEM",
        "GUI",
        "HARDWARE_COMMUNICATION",
        "MEMORY",
        "NETWORK",
        "PROCESSES",
        "RUNTIME",
        "SYSTEM",
        "UNKNOWN"
    };
    class Test {
        private:
            string m_name;
            TestType m_type;
        public:
            Test(const string& name, TestType type);
            virtual ~Test();
            TestStatus run();
            virtual TestStatus execute() = 0;
            const string& name() const;
            TestType type() const;
    };
    template<typename T1, typename T2> bool compare(T1 const& actual, T2 const& expected) {
        // Direct comparison
        if (actual == expected)
            return true;
        // Report what failed
        Logger::WARNING() << "Test failed comparison: expected [" << expected << "], got [" << actual << "]\n";
        return false;
    }
    class ConditionalTest : public Test {
        private:
            bool (*m_condition)();
        public:
            ConditionalTest(const string& name, TestType type, bool (*condition)());
            ~ConditionalTest() override;
            TestStatus execute() override;
    };
    class TestRunner {
        private:
            inline static common::Vector<Test*> s_tests = common::Vector<Test*>();
        public:
            static void test_kernel();
            static void run_all_tests();
            static void run_all_types(TestType type);
            static void add_all_tests();
            static void add_test(Test* test);
    };
}
#endif //MAXOS_TESTS_TEST_H
Enumeration Type Documentation
TestStatus
enum class MaxOS::tests::TestStatus [strong]
The possible outcomes of a test.
Definition at line 26 of file test.h.
                          {
        PASS,
        FAIL,
        SKIP
    };
TestType
enum class MaxOS::tests::TestType [strong]
The different types of tests.
Definition at line 36 of file test.h.
                        {
        COMMON,
        DRIVER,
        FILESYSTEM,
        GUI,
        HARDWARE_COMMUNICATION,
        MEMORY,
        NETWORK,
        PROCESSES,
        RUNTIME,
        SYSTEM,
        MAX_TEST_TYPES
    };
Function Documentation
compare()
template<typename T1 , typename T2 >
bool MaxOS::tests::compare (T1 const & actual, T2 const & expected)
Compares two values and logs a warning if they are not equal.
Template Parameters
T1 The type of the actual value
T2 The type of the expected value
Parameters
actual The actual value
expected The expected value
Returns
True if the values are equal, false otherwise
Definition at line 101 of file test.h.
                                                                                          {
        // Direct comparison
        if (actual == expected)
            return true;
        // Report what failed
        Logger::WARNING() << "Test failed comparison: expected [" << expected << "], got [" << actual << "]\n";
        return false;
    }
References MaxOS::tests::compare(), and MaxOS::Logger::WARNING().
Referenced by MaxOS::tests::compare().
Variable Documentation
TEST_TYPE_STRINGS
constexpr const char* MaxOS::tests::TEST_TYPE_STRINGS[] [constexpr]
Initial value:
= {
        "COMMON",
        "DRIVER",
        "FILESYSTEM",
        "GUI",
        "HARDWARE_COMMUNICATION",
        "MEMORY",
        "NETWORK",
        "PROCESSES",
        "RUNTIME",
        "SYSTEM",
        "UNKNOWN"
    }
String representations of the TestType enum.
Definition at line 51 of file test.h.
                                                {
        "COMMON",
        "DRIVER",
        "FILESYSTEM",
        "GUI",
        "HARDWARE_COMMUNICATION",
        "MEMORY",
        "NETWORK",
        "PROCESSES",
        "RUNTIME",
        "SYSTEM",
        "UNKNOWN"
    };