.TH "/home/runner/work/MaxOS/MaxOS/kernel/src Directory Reference" 3 "Mon Jan 15 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBcommon\fP"
.br
.ti -1c
.RI "directory \fBdrivers\fP"
.br
.ti -1c
.RI "directory \fBfilesystem\fP"
.br
.ti -1c
.RI "directory \fBgui\fP"
.br
.ti -1c
.RI "directory \fBhardwarecommunication\fP"
.br
.ti -1c
.RI "directory \fBmemory\fP"
.br
.ti -1c
.RI "directory \fBnet\fP"
.br
.ti -1c
.RI "directory \fBsystem\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkernel\&.cpp\fP"
.br
.in -1c
