.TH "/home/runner/work/max-os/max-os/kernel/src/drivers/peripherals Directory Reference" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/max-os/max-os/kernel/src/drivers/peripherals Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBkeyboard\&.cpp\fP"
.br
.ti -1c
.RI "file \fBmouse\&.cpp\fP"
.br
.in -1c
