.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication Directory Reference" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBinterrupts\&.h\fP"
.br
.ti -1c
.RI "file \fBpci\&.h\fP"
.br
.ti -1c
.RI "file \fBport\&.h\fP"
.br
.in -1c
