.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/ethernet Directory Reference" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/ethernet Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBamd_am79c973\&.cpp\fP"
.br
.ti -1c
.RI "file \fBethernet\&.cpp\fP"
.br
.ti -1c
.RI "file \fBintel_i217\&.cpp\fP"
.br
.ti -1c
.RI "file \fBrawdatahandler\&.cpp\fP"
.br
.in -1c
