.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/acpi.h" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/acpi.h \- Defines an Advanced Configuration And Power Interface (ACPI class for handling ACPI table parsing and retrieval\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <system/multiboot\&.h>\fP
.br
\fC#include <common/string\&.h>\fP
.br
\fC#include <memory/memorymanagement\&.h>\fP
.br
\fC#include <memory/memoryIO\&.h>\fP
.br
\fC#include <memory/physical\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::RSDPDescriptor\fP"
.br
.RI "Root System Description Pointer (RSDP) structure for ACPI 1\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::RSDPDescriptor2\fP"
.br
.RI "Root System Description Pointer (RSDP) structure for ACPI 2 and above\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::ACPISDTHeader\fP"
.br
.RI "Common header for all ACPI System Description Tables (SDTs) "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::RSDT\fP"
.br
.RI "Root System Description Table (\fBRSDT\fP) structure for ACPI 1\&. Contains the header and an array of pointers to other SDTs\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::XSDT\fP"
.br
.RI "Extended System Description Table (\fBXSDT\fP) structure for ACPI 2 and above\&. Contains the header and an array of pointers to other SDTs\&. "
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface\fP"
.br
.RI "Handles ACPI table parsing and retrieval\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::hardwarecommunication::RSDPDescriptor\fP \fBMaxOS::hardwarecommunication::rsdp_descriptor_t\fP"
.br
.RI "Alias for \fBRSDPDescriptor\fP struct\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::hardwarecommunication::RSDPDescriptor2\fP \fBMaxOS::hardwarecommunication::rsdp_descriptor2_t\fP"
.br
.RI "Alias for \fBRSDPDescriptor2\fP struct\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::hardwarecommunication::ACPISDTHeader\fP \fBMaxOS::hardwarecommunication::acpi_sdt_header_t\fP"
.br
.RI "Alias for \fBACPISDTHeader\fP struct\&. "
.ti -1c
.RI "typedef struct \fBMaxOS::hardwarecommunication::RSDT\fP \fBMaxOS::hardwarecommunication::rsdt_t\fP"
.br
.RI "Alias for \fBRSDT\fP struct\&. "
.ti -1c
.RI "typedef struct \fBMaxOS::hardwarecommunication::XSDT\fP \fBMaxOS::hardwarecommunication::xsdt_t\fP"
.br
.RI "Alias for \fBXSDT\fP struct\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines an Advanced Configuration And Power Interface (ACPI class for handling ACPI table parsing and retrieval\&. 


.PP
\fBDate\fP
.RS 4
18th January 2024 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBacpi\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
