.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/acpi.cpp" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/hardwarecommunication/acpi.cpp \- Implementation of the Advanced Configuration and Power Interface (ACPI) class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <hardwarecommunication/acpi\&.h>\fP
.br
\fC#include <common/logger\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the Advanced Configuration and Power Interface (ACPI) class\&. 


.PP
\fBDate\fP
.RS 4
26th February 2024 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBacpi\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
