.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/ethernet/amd_am79c973.cpp" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/ethernet/amd_am79c973.cpp \- Implementation of the AMD AM79C973 Ethernet Driver\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <drivers/ethernet/amd_am79c973\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the AMD AM79C973 Ethernet Driver\&. 


.PP
\fBDate\fP
.RS 4
22nd October 2022 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBamd_am79c973\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
