.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/gui/font/amiga_font.h" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/font/amiga_font.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
