.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/apic.h" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/apic.h
.SH SYNOPSIS
.br
.PP
\fC#include <hardwarecommunication/port\&.h>\fP
.br
\fC#include <hardwarecommunication/acpi\&.h>\fP
.br
\fC#include <memory/physical\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::LocalAPIC\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::MADT\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::MADT_Item\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::MADT_IOAPIC\fP"
.br
.ti -1c
.RI "union \fBMaxOS::hardwarecommunication::RedirectionEntry\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::InterruptRedirect\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::Override\fP"
.br
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::IOAPIC\fP"
.br
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::AdvancedProgrammableInterruptController\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMaxOS\fP"
.br
.ti -1c
.RI "namespace \fBMaxOS::hardwarecommunication\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBMaxOS::hardwarecommunication::InterruptRedirect\fP \fBMaxOS::hardwarecommunication::interrupt_redirect_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::RSDPDescriptor\fP \fBMaxOS::hardwarecommunication::__attribute__\fP ((packed))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "ACPISDTHeader \fBheader\fP"
.br
.ti -1c
.RI "uint32_t \fBlocal_apic_address\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint8_t \fBlength\fP"
.br
.ti -1c
.RI "uint8_t \fBio_apic_id\fP"
.br
.ti -1c
.RI "uint8_t \fBreserved\fP"
.br
.ti -1c
.RI "uint32_t \fBio_apic_address\fP"
.br
.ti -1c
.RI "uint32_t \fBglobal_system_interrupt_base\fP"
.br
.ti -1c
.RI "uint64_t \fBvector\fP"
.br
.ti -1c
.RI "uint64_t \fBdelivery_mode\fP"
.br
.ti -1c
.RI "uint64_t \fBdestination_mode\fP"
.br
.ti -1c
.RI "uint64_t \fBdelivery_status\fP"
.br
.ti -1c
.RI "uint64_t \fBpin_polarity\fP"
.br
.ti -1c
.RI "uint64_t \fBremote_irr\fP"
.br
.ti -1c
.RI "uint64_t \fBtrigger_mode\fP"
.br
.ti -1c
.RI "uint64_t \fBmask\fP"
.br
.ti -1c
.RI "uint64_t \fBdestination\fP"
.br
.ti -1c
.RI "uint8_t \fBbus\fP"
.br
.ti -1c
.RI "uint8_t \fBsource\fP"
.br
.ti -1c
.RI "uint32_t \fBglobal_system_interrupt\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "uint8_t bus"

.PP
Definition at line \fB0\fP of file \fBapic\&.h\fP\&.
.PP
Referenced by \fBMaxOS::hardwarecommunication::PeripheralComponentInterconnectController::select_drivers()\fP\&.
.SS "uint64_t delivery_mode"

.PP
Definition at line \fB1\fP of file \fBapic\&.h\fP\&.
.SS "uint64_t delivery_status"

.PP
Definition at line \fB3\fP of file \fBapic\&.h\fP\&.
.SS "uint64_t destination"

.PP
Definition at line \fB9\fP of file \fBapic\&.h\fP\&.
.PP
Referenced by \fBMaxOS::common::Buffer::copy_to()\fP, \fBMaxOS::common::Buffer::copy_to()\fP, \fBmemcpy()\fP, \fBmemmove()\fP, and \fBMaxOS::net::EthernetFramePayloadHandler::Send()\fP\&.
.SS "uint64_t destination_mode"

.PP
Definition at line \fB2\fP of file \fBapic\&.h\fP\&.
.SS "uint16_t flags"

.PP
Definition at line \fB2\fP of file \fBapic\&.h\fP\&.
.SS "uint32_t global_system_interrupt"

.PP
Definition at line \fB2\fP of file \fBapic\&.h\fP\&.
.SS "uint32_t global_system_interrupt_base"

.PP
Definition at line \fB3\fP of file \fBapic\&.h\fP\&.
.SS "ACPISDTHeader header"

.PP
Definition at line \fB0\fP of file \fBapic\&.h\fP\&.
.PP
Referenced by \fBMaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::find()\fP, \fBMaxOS::net::UserDatagramProtocolHandler::handleInternetProtocolPayload()\fP, \fBMaxOS::hardwarecommunication::IOAPIC::IOAPIC()\fP, and \fBMaxOS::net::UserDatagramProtocolHandler::Send()\fP\&.
.SS "uint32_t io_apic_address"

.PP
Definition at line \fB2\fP of file \fBapic\&.h\fP\&.
.SS "uint8_t io_apic_id"

.PP
Definition at line \fB0\fP of file \fBapic\&.h\fP\&.
.SS "uint8_t length"

.PP
Definition at line \fB1\fP of file \fBapic\&.h\fP\&.
.SS "uint32_t local_apic_address"

.PP
Definition at line \fB1\fP of file \fBapic\&.h\fP\&.
.SS "uint64_t mask"

.PP
Definition at line \fB7\fP of file \fBapic\&.h\fP\&.
.PP
Referenced by \fBMaxOS::hardwarecommunication::IOAPIC::set_redirect_mask()\fP\&.
.SS "uint64_t pin_polarity"

.PP
Definition at line \fB4\fP of file \fBapic\&.h\fP\&.
.SS "uint64_t remote_irr"

.PP
Definition at line \fB5\fP of file \fBapic\&.h\fP\&.
.SS "uint64_t reserved"

.PP
Definition at line \fB1\fP of file \fBapic\&.h\fP\&.
.SS "uint8_t source"

.PP
Definition at line \fB1\fP of file \fBapic\&.h\fP\&.
.PP
Referenced by \fBMaxOS::common::Buffer::Buffer()\fP, \fBMaxOS::common::Buffer::copy_from()\fP, \fBMaxOS::common::Buffer::copy_from()\fP, \fBmemcpy()\fP, \fBmemmove()\fP, \fBMaxOS::gui::widgets::ButtonEventHandler::on_event()\fP, and \fBMaxOS::hardwarecommunication::IOAPIC::set_redirect()\fP\&.
.SS "uint64_t trigger_mode"

.PP
Definition at line \fB6\fP of file \fBapic\&.h\fP\&.
.SS "uint8_t type"

.PP
Definition at line \fB0\fP of file \fBapic\&.h\fP\&.
.SS "uint64_t vector"

.PP
Definition at line \fB0\fP of file \fBapic\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
