.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/apic.h" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/apic.h \- Defines classes and structures for handling the Advanced Programmable Interrupt Controller (APIC) in a multiprocessor system\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <common/macros\&.h>\fP
.br
\fC#include <hardwarecommunication/port\&.h>\fP
.br
\fC#include <hardwarecommunication/acpi\&.h>\fP
.br
\fC#include <memory/physical\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::LocalAPIC\fP"
.br
.RI "Handles the local APIC for the current core\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::MADT\fP"
.br
.RI "Multiple APIC Description Table (\fBMADT\fP) (ACPI 2 or higher)\&. Provides information about the APICs in the system\&. Following this header are multiple entries describing the APICs (see \fBMADTEntry\fP)\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::MADTEntry\fP"
.br
.RI "An item in the \fBMADT\fP table\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::MADT_IO_APIC\fP"
.br
.RI "An entry in the \fBMADT\fP table describing an IO APIC\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::MADT_PROCESSOR_APIC\fP"
.br
.RI "An entry in the \fBMADT\fP table describing a processor local APIC\&. "
.ti -1c
.RI "union \fBMaxOS::hardwarecommunication::RedirectionEntry\fP"
.br
.RI "An IO APIC redirection entry\&. Describes how an interrupt is routed\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::RedirectionEntry::PACKED\fP"
.br
.RI "Packed because the bitfields should be one uint64_t together\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::InterruptRedirect\fP"
.br
.RI "Defines how an interrupt input is redirected to a specific processor via the I/O APIC\&. "
.ti -1c
.RI "struct \fBMaxOS::hardwarecommunication::Override\fP"
.br
.RI "Specifies how a specific interrupt source is mapped to a global system interrupt\&. "
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::IOAPIC\fP"
.br
.RI "Handles the IO APIC in the system (one per system) "
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::AdvancedProgrammableInterruptController\fP"
.br
.RI "Handles both the Local APIC (boot core) and IO APIC\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::hardwarecommunication::MADT\fP \fBMaxOS::hardwarecommunication::madt_t\fP"
.br
.RI "Alias for \fBMADT\fP struct\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::hardwarecommunication::MADTEntry\fP \fBMaxOS::hardwarecommunication::madt_entry_t\fP"
.br
.RI "Alias for \fBMADTEntry\fP struct\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::hardwarecommunication::MADT_IO_APIC\fP \fBMaxOS::hardwarecommunication::madt_io_apic_t\fP"
.br
.RI "Alias for \fBMADT_IO_APIC\fP struct\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::hardwarecommunication::MADT_PROCESSOR_APIC\fP \fBMaxOS::hardwarecommunication::madt_processor_apic_t\fP"
.br
.RI "Alias for \fBMADT_PROCESSOR_APIC\fP struct\&. "
.ti -1c
.RI "typedef union \fBMaxOS::hardwarecommunication::RedirectionEntry\fP \fBMaxOS::hardwarecommunication::redirection_entry_t\fP"
.br
.RI "Alias for \fBRedirectionEntry\fP union\&. "
.ti -1c
.RI "typedef struct \fBMaxOS::hardwarecommunication::InterruptRedirect\fP \fBMaxOS::hardwarecommunication::interrupt_redirect_t\fP"
.br
.RI "Alias for \fBInterruptRedirect\fP struct\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::hardwarecommunication::Override\fP \fBMaxOS::hardwarecommunication::override_t\fP"
.br
.RI "Alias for \fBOverride\fP struct\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBMaxOS::hardwarecommunication::MADT_TYPE\fP { \fBPROCESSOR_APIC\fP, \fBIO_APIC\fP, \fBINTERRUPT_SOURCE_OVERRIDE\fP, \fBNMI_SOURCE\fP, \fBAPIC_NMIS\fP, \fBAPIC_ADDRESS_OVERRIDE\fP, \fBPROCESSOR_X2APIC\fP }"
.br
.RI "The types of MADT entries\&. "
.ti -1c
.RI "enum \fBMaxOS::hardwarecommunication::DeliveryMode\fP { \fBFIXED\fP = 0, \fBLOWEST_PRIORITY\fP = 1, \fBSMI\fP = 2, \fBNMI\fP = 4, \fBINIT\fP = 5, \fBEXTINT\fP = 7 }"
.br
.RI "How the interrupt should be delivered (can it override others etc)\&. Set fixed/lowest priority for normal interrupts\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines classes and structures for handling the Advanced Programmable Interrupt Controller (APIC) in a multiprocessor system\&. 


.PP
\fBDate\fP
.RS 4
18th January 2024 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBapic\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "\fBMaxOS::hardwarecommunication::madt_io_apic_t\fP"

.PP
Alias for MADT_IO_APIC struct\&. 
.PP
\fBTodo\fP
.RS 4
Rename for consistency 
.RE
.PP

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMaxOS::hardwarecommunication::DeliveryMode\fP"

.PP
How the interrupt should be delivered (can it override others etc)\&. Set fixed/lowest priority for normal interrupts\&. 
.PP
\fBTodo\fP
.RS 4
use this 
.RE
.PP

.PP
Definition at line \fB146\fP of file \fBapic\&.h\fP\&..PP
.nf
146                       {
147         FIXED = 0,
148         LOWEST_PRIORITY = 1,
149         SMI = 2,
150         NMI = 4,
151         INIT = 5,
152         EXTINT = 7,
153     };
.fi

.SS "enum class \fBMaxOS::hardwarecommunication::MADT_TYPE\fP\fC [strong]\fP"

.PP
The types of MADT entries\&. 
.PP
Definition at line \fB77\fP of file \fBapic\&.h\fP\&..PP
.nf
77                          {
78         PROCESSOR_APIC,
79         IO_APIC,
80         INTERRUPT_SOURCE_OVERRIDE,
81         NMI_SOURCE,
82         APIC_NMIS,
83         APIC_ADDRESS_OVERRIDE,
84         PROCESSOR_X2APIC,
85     };
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
