.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/disk/ata.cpp" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/disk/ata.cpp \- Implementation of the Advanced Technology Attachment (ATA) driver for disk communication\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <drivers/disk/ata\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of the Advanced Technology Attachment (ATA) driver for disk communication\&. 


.PP
\fBDate\fP
.RS 4
24th October 2022 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBata\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
