.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/gui/widgets/button.h" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/widgets/button.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <common/eventHandler\&.h>\fP
.br
\fC#include <gui/widget\&.h>\fP
.br
\fC#include <gui/font\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaxOS::gui::widgets::ButtonPressedEvent\fP"
.br
.RI "Event that is triggered when a button is pressed\&. "
.ti -1c
.RI "class \fBmaxOS::gui::widgets::ButtonReleasedEvent\fP"
.br
.RI "Event that is triggered when a button is released\&. "
.ti -1c
.RI "class \fBmaxOS::gui::widgets::ButtonEventHandler\fP"
.br
.RI "Handles button events\&. "
.ti -1c
.RI "class \fBmaxOS::gui::widgets::Button\fP"
.br
.RI "A button widget, can be clicked\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmaxOS\fP"
.br
.ti -1c
.RI " \fBmaxOS::gui\fP"
.br
.ti -1c
.RI " \fBmaxOS::gui::widgets\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmaxOS::gui::widgets::ButtonEvents\fP { \fBmaxOS::gui::widgets::BUTTON_PRESSED\fP, \fBmaxOS::gui::widgets::BUTTON_RELEASED\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
