.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/common/colour.h" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/common/colour.h \- Defines a Colour class for representing colours in RGBA format, along with ANSI and console colour enumerations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <common/string\&.h>\fP
.br
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::common::Colour\fP"
.br
.RI "Stores the red, green, blue and alpha values of a colour\&. Can be parsed from a hex string, an ANSI string or a ConsoleColour\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMaxOS::common::ANSIColour\fP { \fBFG_Black\fP, \fBFG_Red\fP, \fBFG_Green\fP, \fBFG_Yellow\fP, \fBFG_Blue\fP, \fBFG_Magenta\fP, \fBFG_Cyan\fP, \fBFG_White\fP, \fBBG_Black\fP, \fBBG_Red\fP, \fBBG_Green\fP, \fBBG_Yellow\fP, \fBBG_Blue\fP, \fBBG_Magenta\fP, \fBBG_Cyan\fP, \fBBG_White\fP, \fBReset\fP }"
.br
.RI "Enumeration of ANSI colour codes for foreground and background colours\&. "
.ti -1c
.RI "enum class \fBMaxOS::common::ConsoleColour\fP { \fBUninitialised\fP = 0xFF, \fBBlack\fP = 0x00, \fBBlue\fP = 0x01, \fBGreen\fP = 0x02, \fBCyan\fP = 0x03, \fBRed\fP = 0x04, \fBMagenta\fP = 0x05, \fBBrown\fP = 0x06, \fBLightGrey\fP = 0x07, \fBDarkGrey\fP = 0x08, \fBLightBlue\fP = 0x09, \fBLightGreen\fP = 0x0A, \fBLightCyan\fP = 0x0B, \fBLightRed\fP = 0x0C, \fBLightMagenta\fP = 0x0D, \fBYellow\fP = 0x0E, \fBWhite\fP = 0x0F }"
.br
.RI "Enumeration of console colour codes\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconst\fP \fBchar\fP *\fBconst\fP \fBMaxOS::common::ANSI_COLOURS\fP []"
.br
.RI "ANSI \fBColour\fP Codes\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a Colour class for representing colours in RGBA format, along with ANSI and console colour enumerations\&. 


.PP
\fBDate\fP
.RS 4
30th March 2023 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBcolour\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMaxOS::common::ANSIColour\fP"

.PP
Enumeration of ANSI colour codes for foreground and background colours\&. 
.PP
Definition at line \fB44\fP of file \fBcolour\&.h\fP\&..PP
.nf
44                         {
45             FG_Black,
46             FG_Red,
47             FG_Green,
48             FG_Yellow,
49             FG_Blue,
50             FG_Magenta,
51             FG_Cyan,
52             FG_White,
53             BG_Black,
54             BG_Red,
55             BG_Green,
56             BG_Yellow,
57             BG_Blue,
58             BG_Magenta,
59             BG_Cyan,
60             BG_White,
61             Reset,
62         };
.fi

.SS "enum class \fBMaxOS::common::ConsoleColour\fP\fC [strong]\fP"

.PP
Enumeration of console colour codes\&. 
.PP
Definition at line \fB68\fP of file \fBcolour\&.h\fP\&..PP
.nf
68                                  {
69             Uninitialised = 0xFF,
70             Black = 0x00,
71             Blue = 0x01,
72             Green = 0x02,
73             Cyan = 0x03,
74             Red = 0x04,
75             Magenta = 0x05,
76             Brown = 0x06,
77             LightGrey = 0x07,
78             DarkGrey = 0x08,
79             LightBlue = 0x09,
80             LightGreen = 0x0A,
81             LightCyan = 0x0B,
82             LightRed = 0x0C,
83             LightMagenta = 0x0D,
84             Yellow = 0x0E,
85             White = 0x0F
86         };
.fi

.SH "Variable Documentation"
.PP 
.SS "const char* const MaxOS::common::ANSI_COLOURS[]"
\fBInitial value:\fP.PP
.nf
= {
                "\\033[0;30m", 
                "\\033[0;31m", 
                "\\033[0;32m", 
                "\\033[0;33m", 
                "\\033[0;34m", 
                "\\033[0;35m", 
                "\\033[0;36m", 
                "\\033[0;37m", 
                "\\033[0;40m", 
                "\\033[0;41m", 
                "\\033[0;42m", 
                "\\033[0;43m", 
                "\\033[0;44m", 
                "\\033[0;45m", 
                "\\033[0;46m", 
                "\\033[0;47m",  
                "\\033[0m"     
        }
.fi

.PP
ANSI Colour Codes\&. 
.PP
Definition at line \fB20\fP of file \fBcolour\&.h\fP\&..PP
.nf
20                                            {
21                 "\\033[0;30m", // FG Black
22                 "\\033[0;31m", // FG Red
23                 "\\033[0;32m", // FG Green
24                 "\\033[0;33m", // FG Yellow
25                 "\\033[0;34m", // FG Blue
26                 "\\033[0;35m", // FG Magenta
27                 "\\033[0;36m", // FG Cyan
28                 "\\033[0;37m", // FG White
29                 "\\033[0;40m", // BG Black
30                 "\\033[0;41m", // BG Red
31                 "\\033[0;42m", // BG Green
32                 "\\033[0;43m", // BG Yellow
33                 "\\033[0;44m", // BG Blue
34                 "\\033[0;45m", // BG Magenta
35                 "\\033[0;46m", // BG Cyan
36                 "\\033[0;47m",  // BG White
37                 "\\033[0m"     // Reset
38         };
.fi

.PP
Referenced by \fBMaxOS::drivers::console::VESABootConsole::finish()\fP, and \fBLogger::set_log_level()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
