.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/console.h" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/console.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <common/outputStream\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaxOS::drivers::console::Console\fP"
.br
.RI "Abstract class for a console, allows for the printing of characters and strings with colours\&. "
.ti -1c
.RI "class \fBmaxOS::drivers::console::ConsoleArea\fP"
.br
.RI "A console that is a subsection of another console, limited by a width and height\&. "
.ti -1c
.RI "class \fBmaxOS::drivers::console::ConsoleStream\fP"
.br
.RI "A stream that can be used to write to a console\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmaxOS\fP"
.br
.ti -1c
.RI " \fBmaxOS::drivers\fP"
.br
.ti -1c
.RI " \fBmaxOS::drivers::console\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmaxOS::drivers::console::ConsoleColour\fP { \fBmaxOS::drivers::console::Black\fP = 0x00, \fBmaxOS::drivers::console::Blue\fP = 0x01, \fBmaxOS::drivers::console::Green\fP = 0x02, \fBmaxOS::drivers::console::Cyan\fP = 0x03, \fBmaxOS::drivers::console::Red\fP = 0x04, \fBmaxOS::drivers::console::Magenta\fP = 0x05, \fBmaxOS::drivers::console::Brown\fP = 0x06, \fBmaxOS::drivers::console::LightGrey\fP = 0x07, \fBmaxOS::drivers::console::DarkGrey\fP = 0x08, \fBmaxOS::drivers::console::LightBlue\fP = 0x09, \fBmaxOS::drivers::console::LightGreen\fP = 0x0A, \fBmaxOS::drivers::console::LightCyan\fP = 0x0B, \fBmaxOS::drivers::console::LightRed\fP = 0x0C, \fBmaxOS::drivers::console::LightMagenta\fP = 0x0D, \fBmaxOS::drivers::console::Yellow\fP = 0x0E, \fBmaxOS::drivers::console::White\fP = 0x0F }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
