.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/runtime/cplusplus.h" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/runtime/cplusplus.h
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::runtime::atexit_func_entry_t\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMaxOS\fP"
.br
.ti -1c
.RI "namespace \fBMaxOS::runtime\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBMaxOS::runtime::constructor\fP) ()"
.br
.ti -1c
.RI "typedef unsigned \fBMaxOS::runtime::uarch_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBMaxOS::runtime::__cxa_atexit\fP (void(*f)(void *), void *objptr, void *dso)"
.br
.ti -1c
.RI "void \fBMaxOS::runtime::__cxa_finalize\fP (void *f)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
