.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/system/cpu.cpp" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/system/cpu.cpp \- Implementation of the Central Processing Unit (CPU) and its cores\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <system/cpu\&.h>\fP
.br
\fC#include <common/logger\&.h>\fP
.br
\fC#include <processes/scheduler\&.h>\fP
.br
\fC#include <drivers/console/vesaboot\&.h>\fP
.br
\fC#include <memory/memorymanagement\&.h>\fP
.br
\fC#include <drivers/clock/clock\&.h>\fP
.br
\fC#include <common/symbols\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBcore_start\fP ()"
.br
.RI "The entry point for the core startup assembly code\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "uint64_t \fBstack\fP []"
.br
.RI "The stack setup for the core in loader\&.s\&. "
.ti -1c
.RI "volatile PAGE_ALIGNED unsigned char \fBp4_table\fP []"
.br
.RI "The PML4 table setup in loader\&.s\&. "
.ti -1c
.RI "\fBuint8_t\fP \fBcore_boot_info\fP []"
.br
.RI "The info passed between the bsp c++ and booting core assembly code\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of the Central Processing Unit (CPU) and its cores\&. 


.PP
\fBDate\fP
.RS 4
18th January 2024 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBcpu\&.cpp\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBuint8_t\fP core_boot_info[]"

.PP
The info passed between the bsp c++ and booting core assembly code\&. 
.PP
Definition at line \fB30\fP of file \fBcpu\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
