.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/system/cpu.h" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/system/cpu.h \- Defines Central Processing Unit (CPU) structures and functions for managing CPU state and features\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cpuid\&.h>\fP
.br
\fC#include <cstddef>\fP
.br
\fC#include <cstdint>\fP
.br
\fC#include <system/gdt\&.h>\fP
.br
\fC#include <hardwarecommunication/acpi\&.h>\fP
.br
\fC#include <hardwarecommunication/apic\&.h>\fP
.br
\fC#include <memory/physical\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::system::CPUStatus\fP"
.br
.RI "Structure representing the \fBCPU\fP state during an interrupt\&. "
.ti -1c
.RI "struct \fBMaxOS::system::TaskStateSegment\fP"
.br
.RI "Structure representing the Task State Segment (TSS) "
.ti -1c
.RI "struct \fBMaxOS::system::StackFrame\fP"
.br
.RI "A snapshot of the a frame in the call stack\&. "
.ti -1c
.RI "struct \fBMaxOS::system::CoreBootInfo\fP"
.br
.RI "Information needed when booting a core\&. "
.ti -1c
.RI "class \fBMaxOS::system::Core\fP"
.br
.RI "Represents a \fBCPU\fP core in the system\&. "
.ti -1c
.RI "class \fBMaxOS::system::CPU\fP"
.br
.RI "Manages the \fBCPU\fP and its cores\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::system::CPUStatus\fP \fBMaxOS::system::cpu_status_t\fP"
.br
.RI "Alias for \fBCPUStatus\fP struct\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::system::TaskStateSegment\fP \fBMaxOS::system::tss_t\fP"
.br
.RI "Alias for \fBTaskStateSegment\fP struct\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::system::StackFrame\fP \fBMaxOS::system::stack_frame_t\fP"
.br
.RI "Alias for \fBStackFrame\fP struct\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::system::CoreBootInfo\fP \fBMaxOS::system::core_boot_info_t\fP"
.br
.RI "Alias for \fBCoreBootInfo\fP struct\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBMaxOS::system::CPU_FEATURE_ECX\fP : int32_t { \fBSSE3\fP = 1 << 0, \fBPCLMUL\fP = 1 << 1, \fBDTES64\fP = 1 << 2, \fBMONITOR\fP = 1 << 3, \fBDS_CPL\fP = 1 << 4, \fBVMX\fP = 1 << 5, \fBSMX\fP = 1 << 6, \fBEST\fP = 1 << 7, \fBTM2\fP = 1 << 8, \fBSSSE3\fP = 1 << 9, \fBCID\fP = 1 << 10, \fBSDBG\fP = 1 << 11, \fBFMA\fP = 1 << 12, \fBCX16\fP = 1 << 13, \fBXTPR\fP = 1 << 14, \fBPDCM\fP = 1 << 15, \fBPCID\fP = 1 << 17, \fBDCA\fP = 1 << 18, \fBSSE4_1\fP = 1 << 19, \fBSSE4_2\fP = 1 << 20, \fBX2APIC\fP = 1 << 21, \fBMOVBE\fP = 1 << 22, \fBPOPCNT\fP = 1 << 23, \fBTSC\fP = 1 << 24, \fBAES\fP = 1 << 25, \fBXSAVE\fP = 1 << 26, \fBOSXSAVE\fP = 1 << 27, \fBAVX\fP = 1 << 28, \fBF16C\fP = 1 << 29, \fBRDRAND\fP = 1 << 30, \fBHYPERVISOR\fP = 1 << 31 }"
.br
.RI "CPU features indicated by the ECX register after calling CPUID with EAX = 1\&. "
.ti -1c
.RI "enum class \fBMaxOS::system::CPU_FEATURE_EDX\fP : int32_t { \fBFPU\fP = 1 << 0, \fBVME\fP = 1 << 1, \fBDE\fP = 1 << 2, \fBPSE\fP = 1 << 3, \fBTSC\fP = 1 << 4, \fBMSR\fP = 1 << 5, \fBPAE\fP = 1 << 6, \fBMCE\fP = 1 << 7, \fBCX8\fP = 1 << 8, \fBAPIC\fP = 1 << 9, \fBSEP\fP = 1 << 11, \fBMTRR\fP = 1 << 12, \fBPGE\fP = 1 << 13, \fBMCA\fP = 1 << 14, \fBCMOV\fP = 1 << 15, \fBPAT\fP = 1 << 16, \fBPSE36\fP = 1 << 17, \fBPSN\fP = 1 << 18, \fBCLFLUSH\fP = 1 << 19, \fBDS\fP = 1 << 21, \fBACPI\fP = 1 << 22, \fBMMX\fP = 1 << 23, \fBFXSR\fP = 1 << 24, \fBSSE\fP = 1 << 25, \fBSSE2\fP = 1 << 26, \fBSS\fP = 1 << 27, \fBHTT\fP = 1 << 28, \fBTM\fP = 1 << 29, \fBIA64\fP = 1 << 30, \fBPBE\fP = 1 << 31 }"
.br
.RI "CPU features indicated by the EDX register after calling CPUID with EAX = 1\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr size_t \fBMaxOS::system::BOOT_STACK_SIZE\fP = 16384"
.br
.RI "The size of the stack allocated for booting a core (should align with the startup assembly code for the kernel) "
.in -1c
.SH "Detailed Description"
.PP 
Defines Central Processing Unit (CPU) structures and functions for managing CPU state and features\&. 


.PP
\fBDate\fP
.RS 4
17th January 2024 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBcpu\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBMaxOS::system::CPU_FEATURE_ECX\fP : int32_t\fC [strong]\fP"

.PP
CPU features indicated by the ECX register after calling CPUID with EAX = 1\&. 
.PP
\fBSee also\fP
.RS 4
https://wiki.osdev.org/CPUID as the original author 
.RE
.PP

.PP
Definition at line \fB100\fP of file \fBcpu\&.h\fP\&..PP
.nf
100                                : int32_t {
101         SSE3 = 1 << 0,
102         PCLMUL = 1 << 1,
103         DTES64 = 1 << 2,
104         MONITOR = 1 << 3,
105         DS_CPL = 1 << 4,
106         VMX = 1 << 5,
107         SMX = 1 << 6,
108         EST = 1 << 7,
109         TM2 = 1 << 8,
110         SSSE3 = 1 << 9,
111         CID = 1 << 10,
112         SDBG = 1 << 11,
113         FMA = 1 << 12,
114         CX16 = 1 << 13,
115         XTPR = 1 << 14,
116         PDCM = 1 << 15,
117         PCID = 1 << 17,
118         DCA = 1 << 18,
119         SSE4_1 = 1 << 19,
120         SSE4_2 = 1 << 20,
121         X2APIC = 1 << 21,
122         MOVBE = 1 << 22,
123         POPCNT = 1 << 23,
124         TSC = 1 << 24,
125         AES = 1 << 25,
126         XSAVE = 1 << 26,
127         OSXSAVE = 1 << 27,
128         AVX = 1 << 28,
129         F16C = 1 << 29,
130         RDRAND = 1 << 30,
131         HYPERVISOR = 1 << 31,
132     };
.fi

.SS "enum class \fBMaxOS::system::CPU_FEATURE_EDX\fP : int32_t\fC [strong]\fP"

.PP
CPU features indicated by the EDX register after calling CPUID with EAX = 1\&. 
.PP
\fBSee also\fP
.RS 4
https://wiki.osdev.org/CPUID as the original author 
.RE
.PP

.PP
Definition at line \fB140\fP of file \fBcpu\&.h\fP\&..PP
.nf
140                                : int32_t {
141         FPU = 1 << 0,
142         VME = 1 << 1,
143         DE = 1 << 2,
144         PSE = 1 << 3,
145         TSC = 1 << 4,
146         MSR = 1 << 5,
147         PAE = 1 << 6,
148         MCE = 1 << 7,
149         CX8 = 1 << 8,
150         APIC = 1 << 9,
151         SEP = 1 << 11,
152         MTRR = 1 << 12,
153         PGE = 1 << 13,
154         MCA = 1 << 14,
155         CMOV = 1 << 15,
156         PAT = 1 << 16,
157         PSE36 = 1 << 17,
158         PSN = 1 << 18,
159         CLFLUSH = 1 << 19,
160         DS = 1 << 21,
161         ACPI = 1 << 22,
162         MMX = 1 << 23,
163         FXSR = 1 << 24,
164         SSE = 1 << 25,
165         SSE2 = 1 << 26,
166         SS = 1 << 27,
167         HTT = 1 << 28,
168         TM = 1 << 29,
169         IA64 = 1 << 30,
170         PBE = 1 << 31
171     };
.fi

.SH "Variable Documentation"
.PP 
.SS "constexpr size_t MaxOS::system::BOOT_STACK_SIZE = 16384\fC [constexpr]\fP"

.PP
The size of the stack allocated for booting a core (should align with the startup assembly code for the kernel) 
.PP
Definition at line \fB205\fP of file \fBcpu\&.h\fP\&.
.PP
Referenced by \fBMaxOS::system::Core::init_tss()\fP, and \fBMaxOS::system::Core::wake_up()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
