.TH "deprecated" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
deprecated \- Deprecated List 
.PP

.IP "\fBClass \fBMaxOS::common::Event< EventType >\fP \fP" 1c
Will Remove Soon  
.IP "\fBMember \fBMaxOS::common::Event< EventType >::bool_value\fP \fP" 1c
WRS  
.IP "\fBMember \fBMaxOS::common::Event< EventType >::buffer_value\fP \fP" 1c
WRS  
.IP "\fBMember \fBMaxOS::common::Event< EventType >::int_value\fP \fP" 1c
WRS  
.IP "\fBMember \fBMaxOS::common::Event< EventType >::return_value\fP \fP" 1c
WRS  
.IP "\fBMember \fBMaxOS::common::Event< EventType >::type\fP \fP" 1c
WRS  
.IP "\fBClass \fBMaxOS::common::EventManager< EventType >\fP \fP" 1c
Will Remove Soon 
.IP "\fBMember \fBMaxOS::common::EventManager< EventType >::m_handlers\fP \fP" 1c
WRS  
.IP "\fBMember \fBMaxOS::drivers::ethernet::DataReceivedEvent::buffer\fP \fP" 1c
WRS  
.IP "\fBMember \fBMaxOS::drivers::ethernet::DataReceivedEvent::size\fP \fP" 1c
WRS  
.IP "\fBMember \fBMaxOS::hardwarecommunication::RSDPDescriptor::rsdt_address\fP \fP" 1c
in ACPI 2 and above) 
.PP

