.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/disk/disk.cpp" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/disk/disk.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <drivers/disk/disk\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
