.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/processes/elf.cpp" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/processes/elf.cpp \- Implementation of an Executable and Linkable Format (ELF) loader for 64-bit binaries\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <processes/elf\&.h>\fP
.br
\fC#include <common/logger\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of an Executable and Linkable Format (ELF) loader for 64-bit binaries\&. 


.PP
\fBDate\fP
.RS 4
21st March 2025 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBelf\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
