.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/net/ethernetframe.cpp" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/net/ethernetframe.cpp \- Implementation of Ethernet Frame Handler and Payload Handler\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <net/ethernetframe\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of Ethernet Frame Handler and Payload Handler\&. 


.PP
\fBDate\fP
.RS 4
11th May 2022 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBethernetframe\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
