.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/common/eventHandler.h" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/common/eventHandler.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <common/vector\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaxOS::common::Event< EventType >\fP"
.br
.RI "Used to store information about an event, has a type and a return value\&. "
.ti -1c
.RI "class \fBmaxOS::common::EventHandler< EventType >\fP"
.br
.RI "Used to handle an event\&. "
.ti -1c
.RI "class \fBmaxOS::common::EventManager< EventType >\fP"
.br
.RI "Manages the m_handlers for a type of event, raises events and calls the m_handlers\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmaxOS\fP"
.br
.ti -1c
.RI " \fBmaxOS::common\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
