.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/filesystem.h" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/filesystem/filesystem.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <common/string\&.h>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMaxOS\fP"
.br
.ti -1c
.RI " \fBMaxOS::filesystem\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMaxOS::filesystem::SeekType\fP { \fBMaxOS::filesystem::SEEK_SET\fP, \fBMaxOS::filesystem::SEEK_CUR\fP, \fBMaxOS::filesystem::SEEK_END\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "enum \fBMaxOS::filesystem::SeekType\fP \fBMaxOS::filesystem::__attribute__\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
