.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/gui/font.h" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/font.h \- Defines a Font class for drawing text onto a graphics context\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <common/graphicsContext\&.h>\fP
.br
\fC#include <common/rectangle\&.h>\fP
.br
\fC#include <common/string\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::gui::Font\fP"
.br
.RI "A class that can be used to draw text\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "constexpr uint8_t \fBMaxOS::gui::FONT_PADDING\fP = 3"
.br
.RI "How many vertical pixels to add to the top and bottom of the font to prevent squishing\&. "
.ti -1c
.RI "constexpr uint8_t \fBMaxOS::gui::FONT_HEIGHT\fP = 8 + (2 * \fBFONT_PADDING\fP)"
.br
.RI "How many pixels tall the font is\&. "
.ti -1c
.RI "constexpr uint8_t \fBMaxOS::gui::FONT_WIDTH\fP = 8"
.br
.RI "How many pixels wide the font is\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a Font class for drawing text onto a graphics context\&. 


.PP
\fBDate\fP
.RS 4
15th April 2023 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBfont\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "constexpr uint8_t MaxOS::gui::FONT_HEIGHT = 8 + (2 * FONT_PADDING)\fC [constexpr]\fP"

.PP
How many pixels tall the font is\&. 
.PP
Definition at line \fB20\fP of file \fBfont\&.h\fP\&.
.PP
Referenced by \fBMaxOS::drivers::console::VESABootConsole::height()\fP, \fBMaxOS::drivers::console::VESABootConsole::put_character()\fP, and \fBMaxOS::drivers::console::VESABootConsole::scroll_up()\fP\&.
.SS "constexpr uint8_t MaxOS::gui::FONT_PADDING = 3\fC [constexpr]\fP"

.PP
How many vertical pixels to add to the top and bottom of the font to prevent squishing\&. 
.PP
Definition at line \fB19\fP of file \fBfont\&.h\fP\&.
.SS "constexpr uint8_t MaxOS::gui::FONT_WIDTH = 8\fC [constexpr]\fP"

.PP
How many pixels wide the font is\&. 
.PP
Definition at line \fB21\fP of file \fBfont\&.h\fP\&.
.PP
Referenced by \fBMaxOS::drivers::console::VESABootConsole::scroll_up()\fP, and \fBMaxOS::drivers::console::VESABootConsole::width()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
