.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/common/inputStream.h" 3 "Sun Oct 13 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/common/inputStream.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <common/vector\&.h>\fP
.br
\fC#include <common/string\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::common::GenericInputStream\fP"
.br
.RI "Manages the connection of a stream to handlers\&. "
.ti -1c
.RI "class \fBMaxOS::common::InputStreamEventHandler< Type >\fP"
.br
.RI "Handles read and end of stream events from a set of streams\&. "
.ti -1c
.RI "class \fBMaxOS::common::InputStreamProcessor< Type, ProcessorType >\fP"
.br
.RI "Converts one stream data type into another\&. "
.ti -1c
.RI "class \fBMaxOS::common::InputStreamSocket< Type >\fP"
.br
.RI "Passes read events on to the handlers\&. "
.ti -1c
.RI "class \fBMaxOS::common::InputStreamBuffer< Type >\fP"
.br
.RI "Buffers data from a stream and fires an event when a certain element is read\&. "
.ti -1c
.RI "class \fBMaxOS::common::GenericInputStream\fP"
.br
.RI "Manages the connection of a stream to handlers\&. "
.ti -1c
.RI "class \fBMaxOS::common::InputStream\fP"
.br
.RI "A stream that handles strings\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMaxOS\fP"
.br
.ti -1c
.RI " \fBMaxOS::common\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Type > void \fBMaxOS::common::operator>>\fP (GenericInputStream< Type > &\fBsource\fP, InputStreamEventHandler< Type > &inputStreamEventHandler)"
.br
.ti -1c
.RI "template<class Type , class ProcessorType > GenericInputStream< ProcessorType > & \fBMaxOS::common::operator>>\fP (GenericInputStream< Type > &\fBsource\fP, InputStreamProcessor< Type, ProcessorType > &processor)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
