.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/gui/widgets/inputbox.h" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/widgets/inputbox.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <gui/widget\&.h>\fP
.br
\fC#include <gui/font\&.h>\fP
.br
\fC#include <common/string\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaxOS::gui::widgets::InputBoxTextChangedEvent\fP"
.br
.RI "Event that is triggered when the text in an input box is changed\&. "
.ti -1c
.RI "class \fBmaxOS::gui::widgets::InputBoxEventHandler\fP"
.br
.RI "Handles input box events\&. "
.ti -1c
.RI "class \fBmaxOS::gui::widgets::InputBox\fP"
.br
.RI "A box that can be used to input text\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmaxOS\fP"
.br
.ti -1c
.RI " \fBmaxOS::gui\fP"
.br
.ti -1c
.RI " \fBmaxOS::gui::widgets\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmaxOS::gui::widgets::InputBoxEvents\fP { \fBmaxOS::gui::widgets::INPUTBOX_TEXT_CHANGED\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
