.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/net/ipv4.h" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/net/ipv4.h \- Defines classes and structures for handling Internet Protocol version 4 (IPv4) packets\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <net/ethernetframe\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::net::IPV4Header\fP"
.br
.RI "The header of an IPv4 packet\&. "
.ti -1c
.RI "class \fBMaxOS::net::IPV4AddressResolver\fP"
.br
.RI "Resolves IP addresses to MAC addresses\&. "
.ti -1c
.RI "class \fBMaxOS::net::IPV4PayloadHandler\fP"
.br
.RI "Handles the payload of a specific IP protocol\&. "
.ti -1c
.RI "class \fBMaxOS::net::InternetProtocolHandler\fP"
.br
.RI "Handles IPv4 packets over Ethernet frames\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint32_t \fBMaxOS::net::InternetProtocolAddress\fP"
.br
.RI "An IPv4 address\&. "
.ti -1c
.RI "typedef uint32_t \fBMaxOS::net::SubnetMask\fP"
.br
.RI "A subnet mask\&. "
.ti -1c
.RI "typedef struct PACKED \fBMaxOS::net::IPV4Header\fP \fBMaxOS::net::ipv4_header_t\fP"
.br
.RI "Alias for \fBIPV4Header\fP struct\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines classes and structures for handling Internet Protocol version 4 (IPv4) packets\&. 


.PP
\fBDate\fP
.RS 4
22nd November 2022 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBipv4\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef uint32_t \fBMaxOS::net::InternetProtocolAddress\fP"

.PP
An IPv4 address\&. 
.PP
\fBTodo\fP
.RS 4
: Make IPv4Address class and do ip_t 
.RE
.PP

.PP
Definition at line \fB18\fP of file \fBipv4\&.h\fP\&.
.SS "typedef uint32_t \fBMaxOS::net::SubnetMask\fP"

.PP
A subnet mask\&. 
.PP
\fBTodo\fP
.RS 4
: Make SubnetMask class and do subnetmask_t 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBipv4\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
