.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/kernel.cpp" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/kernel.cpp \- The main kernel entry point for the bsp and other cores\&. Handles initialisation of all core systems\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <common/logger\&.h>\fP
.br
\fC#include <hardwarecommunication/interrupts\&.h>\fP
.br
\fC#include <drivers/console/serial\&.h>\fP
.br
\fC#include <drivers/console/vesaboot\&.h>\fP
.br
\fC#include <drivers/driver\&.h>\fP
.br
\fC#include <drivers/video/vesa\&.h>\fP
.br
\fC#include <gui/desktop\&.h>\fP
.br
\fC#include <processes/scheduler\&.h>\fP
.br
\fC#include <system/cpu\&.h>\fP
.br
\fC#include <system/syscalls\&.h>\fP
.br
\fC#include <memory/memorymanagement\&.h>\fP
.br
\fC#include <memory/physical\&.h>\fP
.br
\fC#include <memory/virtual\&.h>\fP
.br
\fC#include <filesystem/vfs\&.h>\fP
.br
\fC#include <filesystem/vfsresource\&.h>\fP
.br
\fC#include <tests/test\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBcall_constructors\fP ()"
.br
.RI "Calls the C++ static constructors\&. "
.ti -1c
.RI "\fBvoid\fP \fBcore_main\fP ()"
.br
.RI "The main entry point for secondary cores\&. Sets up the core and waits to be scheduled\&. "
.ti -1c
.RI "\fBvoid\fP \fBkernel_main\fP (\fBunsigned\fP \fBlong\fP addr, \fBunsigned\fP \fBlong\fP magic)"
.br
.RI "The main kernel entry point\&. Initialises all core systems and starts the scheduler\&. "
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBuint8_t\fP \fBcore_boot_info\fP []"
.br
.RI "The boot info structure for the core being started\&. "
.in -1c
.SH "Detailed Description"
.PP 
The main kernel entry point for the bsp and other cores\&. Handles initialisation of all core systems\&. 


.PP
\fBDate\fP
.RS 4
2022 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBkernel\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "void call_constructors ()"

.PP
Calls the C++ static constructors\&. Calls the C++ static constructors\&. 
.PP
Definition at line \fB39\fP of file \fBcplusplus\&.cpp\fP\&..PP
.nf
39                                     {
40     // Loop through and initialise all the global constructorsu
41     for (constructor* i = &start_ctors; i != &end_ctors; i++)
42         (*i)();
43 }
.fi

.PP
References \fBend_ctors\fP, and \fBstart_ctors\fP\&.
.PP
Referenced by \fBkernel_main()\fP\&.
.SS "\fBvoid\fP core_main ()"

.PP
The main entry point for secondary cores\&. Sets up the core and waits to be scheduled\&. 
.PP
Definition at line \fB48\fP of file \fBkernel\&.cpp\fP\&..PP
.nf
48                                          {
49 
50     auto info = (core_boot_info_t*) (core_boot_info);
51     info\->activated = true;
52     auto core = CPU::executing_core();
53 
54     // Make sure the correct core is being setup
55     ASSERT(info\->id == core\->id, "Current setup core isn't the core expected");
56     Logger::DEBUG() << "Core " << core\->id << " now in higher half \\n";
57 
58     // Set up the core
59     core\->init();
60     asm("sti");
61 
62     // Wait to be scheduled
63     while(true)
64         asm("nop");
65 }
.fi

.PP
References \fBASSERT\fP, \fBcore_boot_info\fP, \fBMaxOS::Logger::DEBUG()\fP, and \fBMaxOS::system::CPU::executing_core()\fP\&.
.SS "\fBvoid\fP kernel_main (\fBunsigned\fP \fBlong\fP addr, \fBunsigned\fP \fBlong\fP magic)"

.PP
The main kernel entry point\&. Initialises all core systems and starts the scheduler\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddr\fP The address of the multiboot info struct 
.br
\fImagic\fP The multiboot magic number 
.RE
.PP

.PP
Definition at line \fB73\fP of file \fBkernel\&.cpp\fP\&..PP
.nf
73                                                                                   {
74 
75     call_constructors();
76 
77     Logger logger;
78     SerialConsole serial_console(&logger);
79     Logger::INFO() << "MaxOS Booted Successfully\\n";
80 
81     Logger::HEADER() << "Stage {1}: System Initialisation\\n";
82     Multiboot multiboot(addr, magic);
83     GlobalDescriptorTable gdt;
84     InterruptManager interrupts;
85 
86     Logger::HEADER() << "Stage {1\&.1}: Memory Initialisation\\n";
87     PhysicalMemoryManager pmm(&multiboot);
88     VirtualMemoryManager vmm;
89     MemoryManager memory_manager(&vmm);
90 
91     Logger::HEADER() << "Stage {1\&.2}: Console Initialisation\\n";
92     VideoElectronicsStandardsAssociation vesa(multiboot\&.framebuffer());
93     VESABootConsole console(&vesa);
94 
95     Logger::HEADER() << "Stage {2}: Hardware Initialisation\\n";
96     VirtualFileSystem vfs;
97     CPU cpu(&gdt, &multiboot);
98     Clock kernel_clock(&cpu\&.apic, 1);
99     DriverManager driver_manager;
100     driver_manager\&.add_driver(&kernel_clock);
101     driver_manager\&.find_drivers();
102     uint32_t reset_wait_time = driver_manager\&.reset_devices();
103 
104     Logger::HEADER() << "Stage {3}: Device Finalisation\\n";
105     interrupts\&.activate();
106     kernel_clock\&.calibrate();
107     kernel_clock\&.delay(reset_wait_time);
108     driver_manager\&.initialise_drivers();
109     driver_manager\&.activate_drivers();
110     cpu\&.init_cores();
111 
112     Logger::HEADER() << "Stage {4}: System Finalisation\\n";
113     GlobalScheduler scheduler(multiboot);
114     VFSResourceRegistry vfs_registry(&vfs);
115     SyscallManager syscalls;
116     console\&.finish();
117     GlobalScheduler::activate();
118 
119     // Idle loop  (read Idle\&.md)
120     while(true)
121         asm("hlt");
122 
123 }
.fi

.PP
References \fBMaxOS::processes::GlobalScheduler::activate()\fP, \fBcall_constructors()\fP, \fBMaxOS::drivers::console::VESABootConsole::finish()\fP, \fBMaxOS::Logger::HEADER()\fP, and \fBMaxOS::Logger::INFO()\fP\&.
.SH "Variable Documentation"
.PP 
.SS "\fBuint8_t\fP core_boot_info[]"

.PP
The boot info structure for the core being started\&. 
.PP
Definition at line \fB43\fP of file \fBkernel\&.cpp\fP\&.
.PP
Referenced by \fBcore_main()\fP, \fBMaxOS::system::CPU::init_cores()\fP, and \fBMaxOS::system::Core::wake_up()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
