.TH "MaxOS::net::EthernetFrameFooter" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::EthernetFrameFooter \- Structure the raw data\&. This is the footer of an Ethernet Frame\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethernetframe\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBchecksum\fP"
.br
.RI "checksum of the payload "
.in -1c
.SH "Detailed Description"
.PP 
Structure the raw data\&. This is the footer of an Ethernet Frame\&. 
.PP
Definition at line \fB45\fP of file \fBethernetframe\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t MaxOS::net::EthernetFrameFooter::checksum"

.PP
checksum of the payload 
.PP
Definition at line \fB47\fP of file \fBethernetframe\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
