.TH "MaxOS::net::ConnectedEvent" 3 "Mon Jan 15 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::ConnectedEvent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< TransmissionControlProtocolPayloadHandlerEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectedEvent\fP (\fBTransmissionControlProtocolSocket\fP *\fBsocket\fP)"
.br
.ti -1c
.RI "\fB~ConnectedEvent\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransmissionControlProtocolSocket\fP * \fBsocket\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 99 of file tcp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConnectedEvent::ConnectedEvent (\fBTransmissionControlProtocolSocket\fP * socket)"

.PP
Definition at line 567 of file tcp\&.cpp\&.
.PP
.nf
568 : Event(CONNECTED)
569 {
570     this -> socket = socket;
571 }
.fi
.PP
References socket\&.
.SS "ConnectedEvent::~ConnectedEvent ()"

.PP
Definition at line 572 of file tcp\&.cpp\&.
.PP
.nf
573 {
574 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBTransmissionControlProtocolSocket\fP* MaxOS::net::ConnectedEvent::socket"

.PP
Definition at line 102 of file tcp\&.h\&.
.PP
Referenced by ConnectedEvent()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
