.TH "MaxOS::runtime::InvaildValueInfo" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::runtime::InvaildValueInfo \- Information about an invalid value error\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ubsan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsource_location_t\fP \fBlocation\fP"
.br
.RI "The location of the invalid value\&. "
.ti -1c
.RI "\fBtype_descriptor_t\fP * \fBtype\fP"
.br
.RI "The type of the invalid value\&. "
.in -1c
.SH "Detailed Description"
.PP 
Information about an invalid value error\&. 
.PP
Definition at line \fB102\fP of file \fBubsan\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBsource_location_t\fP MaxOS::runtime::InvaildValueInfo::location"

.PP
The location of the invalid value\&. 
.PP
Definition at line \fB103\fP of file \fBubsan\&.h\fP\&.
.SS "\fBtype_descriptor_t\fP* MaxOS::runtime::InvaildValueInfo::type"

.PP
The type of the invalid value\&. 
.PP
Definition at line \fB104\fP of file \fBubsan\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
