.TH "MaxOS::processes::elf_64_header_t" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::processes::elf_64_header_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <elf\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBidentification\fP [16]"
.br
.ti -1c
.RI "uint16_t \fBtype\fP"
.br
.ti -1c
.RI "uint16_t \fBmachine\fP"
.br
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.ti -1c
.RI "uint64_t \fBentry\fP"
.br
.ti -1c
.RI "uint64_t \fBprogram_header_offset\fP"
.br
.ti -1c
.RI "uint64_t \fBsection_header_offset\fP"
.br
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.ti -1c
.RI "uint16_t \fBelf_header_size\fP"
.br
.ti -1c
.RI "uint16_t \fBprogram_header_size\fP"
.br
.ti -1c
.RI "uint16_t \fBprogram_header_count\fP"
.br
.ti -1c
.RI "uint16_t \fBsection_header_size\fP"
.br
.ti -1c
.RI "uint16_t \fBsection_header_count\fP"
.br
.ti -1c
.RI "uint16_t \fBsection_header_string_table_index\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 74 of file elf\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t MaxOS::processes::elf_64_header_t::elf_header_size"

.PP
Definition at line 83 of file elf\&.h\&.
.SS "uint64_t MaxOS::processes::elf_64_header_t::entry"

.PP
Definition at line 79 of file elf\&.h\&.
.SS "uint32_t MaxOS::processes::elf_64_header_t::flags"

.PP
Definition at line 82 of file elf\&.h\&.
.SS "unsigned char MaxOS::processes::elf_64_header_t::identification[16]"

.PP
Definition at line 75 of file elf\&.h\&.
.SS "uint16_t MaxOS::processes::elf_64_header_t::machine"

.PP
Definition at line 77 of file elf\&.h\&.
.SS "uint16_t MaxOS::processes::elf_64_header_t::program_header_count"

.PP
Definition at line 85 of file elf\&.h\&.
.SS "uint64_t MaxOS::processes::elf_64_header_t::program_header_offset"

.PP
Definition at line 80 of file elf\&.h\&.
.SS "uint16_t MaxOS::processes::elf_64_header_t::program_header_size"

.PP
Definition at line 84 of file elf\&.h\&.
.SS "uint16_t MaxOS::processes::elf_64_header_t::section_header_count"

.PP
Definition at line 87 of file elf\&.h\&.
.SS "uint64_t MaxOS::processes::elf_64_header_t::section_header_offset"

.PP
Definition at line 81 of file elf\&.h\&.
.SS "uint16_t MaxOS::processes::elf_64_header_t::section_header_size"

.PP
Definition at line 86 of file elf\&.h\&.
.SS "uint16_t MaxOS::processes::elf_64_header_t::section_header_string_table_index"

.PP
Definition at line 88 of file elf\&.h\&.
.SS "uint16_t MaxOS::processes::elf_64_header_t::type"

.PP
Definition at line 76 of file elf\&.h\&.
.SS "uint32_t MaxOS::processes::elf_64_header_t::version"

.PP
Definition at line 78 of file elf\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
