.TH "MaxOS::drivers::ethernet::DataReceivedEvent" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::ethernet::DataReceivedEvent \- Event that is triggered when data is received, holds the buffer and size of the data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethernet\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< EthernetDriverEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataReceivedEvent\fP (\fBuint8_t\fP *\fBbuffer\fP, \fBuint32_t\fP \fBsize\fP)"
.br
.RI "Construct a new Data Received Event object\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::Event< EthernetDriverEvents >\fP
.in +1c
.ti -1c
.RI "\fBEvent\fP (EthernetDriverEvents type)"
.br
.RI "Constructs a new \fBEvent\fP object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t * \fBbuffer\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.in -1c

Public Attributes inherited from \fBMaxOS::common::Event< EthernetDriverEvents >\fP
.in +1c
.ti -1c
.RI "EthernetDriverEvents \fBtype\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbuffer_value\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBint_value\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBbool_value\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBuint8_t\fP * \fBbuffer_value\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBint_value\fP"
.br
.ti -1c
.RI "   \fBbool\fP \fBbool_value\fP"
.br
.ti -1c
.RI "} \fBreturn_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event that is triggered when data is received, holds the buffer and size of the data\&. 
.PP
Definition at line \fB61\fP of file \fBethernet\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataReceivedEvent::DataReceivedEvent (\fBuint8_t\fP * buffer, \fBuint32_t\fP size)"

.PP
Construct a new Data Received Event object\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The buffer that was received 
.br
\fIsize\fP The size of the buffer 
.RE
.PP

.PP
Definition at line \fB196\fP of file \fBethernet\&.cpp\fP\&..PP
.nf
197         : Event(EthernetDriverEvents::DATA_RECEIVED) {
198     this\->buffer = buffer;
199     this\->size = size;
200 }
.fi

.PP
References \fBbuffer\fP, and \fBsize\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t* MaxOS::drivers::ethernet::DataReceivedEvent::buffer"

.PP
\fBDeprecated\fP
.RS 4
WRS 
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBethernet\&.h\fP\&.
.PP
Referenced by \fBDataReceivedEvent()\fP\&.
.SS "uint32_t MaxOS::drivers::ethernet::DataReceivedEvent::size"

.PP
\fBDeprecated\fP
.RS 4
WRS 
.RE
.PP

.PP
Definition at line \fB64\fP of file \fBethernet\&.h\fP\&.
.PP
Referenced by \fBDataReceivedEvent()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
