.TH "MaxOS::processes::ResourceManager" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::processes::ResourceManager \- Manages the open resources for a process\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <resource\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fB~ResourceManager\fP ()"
.br
.RI "Destructor for \fBResourceManager\fP, closes all open resources\&. "
.ti -1c
.RI "\fBcommon::Map\fP< uint64_t, \fBResource\fP * > \fBresources\fP ()"
.br
.RI "Get the resources currently open\&. "
.ti -1c
.RI "uint64_t \fBopen_resource\fP (\fBresource_type_t\fP type, const \fBstring\fP &name, size_t flags)"
.br
.RI "Registers a resource with the resource manager and then opens it\&. "
.ti -1c
.RI "void \fBclose_resource\fP (uint64_t handle, size_t flags)"
.br
.RI "Un registers the resource and then closes it\&. "
.ti -1c
.RI "\fBResource\fP * \fBget_resource\fP (uint64_t handle)"
.br
.RI "Gets a resource based on the handle id\&. "
.ti -1c
.RI "\fBResource\fP * \fBget_resource\fP (const \fBstring\fP &name)"
.br
.RI "Finds a resource by name\&. "
.in -1c
.SH "Detailed Description"
.PP 
Manages the open resources for a process\&. 
.PP
Definition at line \fB141\fP of file \fBresource\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ResourceManager::~ResourceManager ()"

.PP
Destructor for \fBResourceManager\fP, closes all open resources\&. 
.PP
Definition at line \fB261\fP of file \fBresource\&.cpp\fP\&..PP
.nf
261                                  {
262 
263     // Collect all resources (as closing will break iteration)
264     common::Vector<uint64_t> handles;
265     for (const auto& kv : m_resources)
266         handles\&.push_back(kv\&.first);
267 
268     // Close the resources
269     for (auto h : handles)
270         close_resource(h, 0);
271 
272 }
.fi

.PP
References \fBclose_resource()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void ResourceManager::close_resource (uint64_t handle, size_t flags)"

.PP
Un registers the resource and then closes it\&. 
.PP
\fBParameters\fP
.RS 4
\fIhandle\fP The handle number of the resource 
.br
\fIflags\fP Flags to pass to the closing 
.RE
.PP

.PP
Definition at line \fB313\fP of file \fBresource\&.cpp\fP\&..PP
.nf
313                                                                   {
314 
315     auto it = m_resources\&.find(handle);
316     if(it == m_resources\&.end())
317         return;
318 
319     // Remove it
320     Resource* resource = it\->second;
321     m_resources\&.erase(handle);
322 
323     // Close it
324     GlobalResourceRegistry::get_registry(resource\->type()) \-> close_resource(resource, flags);
325 }
.fi

.PP
References \fBclose_resource()\fP, \fBMaxOS::processes::GlobalResourceRegistry::get_registry()\fP, and \fBMaxOS::processes::Resource::type()\fP\&.
.PP
Referenced by \fBclose_resource()\fP, and \fB~ResourceManager()\fP\&.
.SS "\fBResource\fP * ResourceManager::get_resource (const \fBstring\fP & name)"

.PP
Finds a resource by name\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the resource 
.RE
.PP
\fBReturns\fP
.RS 4
The resource or nullptr if not found 
.RE
.PP

.PP
Definition at line \fB347\fP of file \fBresource\&.cpp\fP\&..PP
.nf
347                                                           {
348 
349     for(const auto& resource : m_resources)
350         if(resource\&.second\->name() == name)
351             return resource\&.second;
352 
353     return nullptr;
354 }
.fi

.SS "\fBResource\fP * ResourceManager::get_resource (uint64_t handle)"

.PP
Gets a resource based on the handle id\&. 
.PP
\fBParameters\fP
.RS 4
\fIhandle\fP The handle number of the resource 
.RE
.PP
\fBReturns\fP
.RS 4
The resource or nullptr if not found 
.RE
.PP

.PP
Definition at line \fB333\fP of file \fBresource\&.cpp\fP\&..PP
.nf
333                                                        {
334 
335     if(m_resources\&.find(handle) == m_resources\&.end())
336         return nullptr;
337 
338     return m_resources[handle];
339 }
.fi

.PP
Referenced by \fBopen_resource()\fP\&.
.SS "uint64_t ResourceManager::open_resource (\fBresource_type_t\fP type, const \fBstring\fP & name, size_t flags)"

.PP
Registers a resource with the resource manager and then opens it\&. 
.PP
\fBParameters\fP
.RS 4
\fItype\fP The type of resource to register 
.br
\fIname\fP The name of the resource 
.br
\fIflags\fP Per resource flags for opening 
.RE
.PP
\fBReturns\fP
.RS 4
The handle id of the resource or 0 if failed 
.RE
.PP

.PP
Definition at line \fB292\fP of file \fBresource\&.cpp\fP\&..PP
.nf
292                                                                                               {
293 
294     // Get the resource
295     auto resource = GlobalResourceRegistry::get_registry(type) \-> get_resource(name);
296     if(!resource)
297         return 0;
298 
299     // Store it
300     m_resources\&.insert(m_next_handle, resource);
301 
302     // Open it
303     resource\->open(flags);
304     return m_next_handle++;
305 }
.fi

.PP
References \fBMaxOS::processes::GlobalResourceRegistry::get_registry()\fP, and \fBget_resource()\fP\&.
.SS "\fBcommon::Map\fP< uint64_t, \fBResource\fP * > ResourceManager::resources ()"

.PP
Get the resources currently open\&. 
.PP
\fBReturns\fP
.RS 4
The resources 
.RE
.PP

.PP
Definition at line \fB279\fP of file \fBresource\&.cpp\fP\&..PP
.nf
279                                                           {
280 
281     return m_resources;
282 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
