.TH "MaxOS::net::DisconnectedEvent" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::DisconnectedEvent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< TransmissionControlProtocolPayloadHandlerEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDisconnectedEvent\fP (\fBTransmissionControlProtocolSocket\fP *\fBsocket\fP)"
.br
.ti -1c
.RI "\fB~DisconnectedEvent\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransmissionControlProtocolSocket\fP * \fBsocket\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 107 of file tcp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DisconnectedEvent::DisconnectedEvent (\fBTransmissionControlProtocolSocket\fP * socket)"

.PP
Definition at line 576 of file tcp\&.cpp\&.
.PP
.nf
577 : Event(DISCONNECTED)
578 {
579     this -> socket = socket;
580 }
.fi
.PP
References socket\&.
.SS "DisconnectedEvent::~DisconnectedEvent ()"

.PP
Definition at line 581 of file tcp\&.cpp\&.
.PP
.nf
582 {
583 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBTransmissionControlProtocolSocket\fP* MaxOS::net::DisconnectedEvent::socket"

.PP
Definition at line 110 of file tcp\&.h\&.
.PP
Referenced by DisconnectedEvent()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
