.TH "MaxOS::processes::IPCMessage" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::processes::IPCMessage
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ipc\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "void * \fBmessage_buffer\fP"
.br
.ti -1c
.RI "size_t \fBmessage_size\fP"
.br
.ti -1c
.RI "uintptr_t \fBnext_message\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 32 of file ipc\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "void* MaxOS::processes::IPCMessage::message_buffer"

.PP
Definition at line 33 of file ipc\&.h\&.
.SS "size_t MaxOS::processes::IPCMessage::message_size"

.PP
Definition at line 34 of file ipc\&.h\&.
.SS "uintptr_t MaxOS::processes::IPCMessage::next_message"

.PP
Definition at line 35 of file ipc\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
