.TH "MaxOS::drivers::peripherals::MouseDriver" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::peripherals::MouseDriver \- \fBDriver\fP for the PS/2 mouse, manages the mouse and triggers events when the mouse moves or a button is pressed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mouse\&.h>\fP
.PP
Inherits \fBMaxOS::hardwarecommunication::InterruptHandler\fP, \fBMaxOS::drivers::Driver\fP, and \fBMaxOS::common::EventManager< MouseEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBactivate\fP () \fBfinal\fP"
.br
.RI "activate the mouse "
.ti -1c
.RI "\fBstring\fP \fBdevice_name\fP () \fBfinal\fP"
.br
.RI "Get the name of the device\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::hardwarecommunication::InterruptHandler\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP system::cpu_status_t * \fBhandle_interrupt\fP (system::cpu_status_t *status)"
.br
.RI "Handles an interrupt and returns the status\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::Driver\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdeactivate\fP ()"
.br
.RI "deactivate the driver "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBinitialise\fP ()"
.br
.RI "Initialise the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBuint32_t\fP \fBreset\fP ()"
.br
.RI "Reset the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBstring\fP \fBvendor_name\fP ()"
.br
.RI "Get who created the device\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::EventManager< MouseEvents >\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBconnect_event_handler\fP (\fBEventHandler\fP< MouseEvents > *\fBhandler\fP)"
.br
.RI "Connect an event handler to the event manager if it is not already connected\&. "
.ti -1c
.RI "\fBvoid\fP \fBdisconnect_event_handler\fP (\fBEventHandler\fP< MouseEvents > *\fBhandler\fP)"
.br
.RI "Disconnect an event handler from the event manager if it is connected\&. "
.ti -1c
.RI "\fBVector\fP< \fBEvent\fP< MouseEvents > * > \fBraise_event\fP (\fBEvent\fP< MouseEvents > *\fBevent\fP)"
.br
.RI "Calls the on_event function of all the event m_handlers connected to the event manager and returns a list of the results\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::hardwarecommunication::InterruptHandler\fP
.in +1c
.ti -1c
.RI "\fBInterruptHandler\fP (\fBuint8_t\fP interrupt_number, \fBint64_t\fP \fBredirect\fP=\-1, \fBuint64_t\fP \fBredirect_index\fP=0)"
.br
.RI "Creates a new interrupt handler and registers it with the interrupt manager\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::hardwarecommunication::InterruptHandler\fP
.in +1c
.ti -1c
.RI "uint8_t \fBm_interrupt_number\fP"
.br
.RI "The interrupt number this handler handles\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::common::EventManager< MouseEvents >\fP
.in +1c
.ti -1c
.RI "\fBVector\fP< \fBEventHandler\fP< MouseEvents > * > \fBm_handlers\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDriver\fP for the PS/2 mouse, manages the mouse and triggers events when the mouse moves or a button is pressed\&. 
.PP
Definition at line \fB91\fP of file \fBmouse\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MouseDriver::MouseDriver ()"

.PP
Definition at line \fB76\fP of file \fBmouse\&.cpp\fP\&..PP
.nf
77 : InterruptHandler(0x2C, 0xC, 0x28),
78   data_port(0x60),
79   command_port(0x64)
80 {
81 
82 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP MouseDriver::activate ()\fC [final]\fP, \fC [virtual]\fP"

.PP
activate the mouse 
.PP
Reimplemented from \fBMaxOS::drivers::Driver\fP\&.
.PP
Definition at line \fB89\fP of file \fBmouse\&.cpp\fP\&..PP
.nf
89                            {
90 
91     //  Get the current state of the mouse
92     command_port\&.write(0x20);
93     uint8_t status = (data_port\&.read() | 2);
94 
95     // Write the new state
96     command_port\&.write(0x60);
97     data_port\&.write(status);
98 
99     // Tell the PIC to start listening to the mouse
100     command_port\&.write(0xAB);
101 
102     // Activate the mouse
103     command_port\&.write(0xD4);
104     data_port\&.write(0xF4);
105     data_port\&.read();
106 }
.fi

.PP
References \fBMaxOS::hardwarecommunication::Port8Bit::read()\fP, and \fBMaxOS::hardwarecommunication::Port8Bit::write()\fP\&.
.SS "\fBstring\fP MouseDriver::device_name ()\fC [final]\fP, \fC [virtual]\fP"

.PP
Get the name of the device\&. 
.PP
\fBReturns\fP
.RS 4
The name of the device 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::Driver\fP\&.
.PP
Definition at line \fB153\fP of file \fBmouse\&.cpp\fP\&..PP
.nf
153                                 {
154     return "Mouse";
155 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
