.TH "maxOS::drivers::peripherals::MouseUpEvent" 3 "Sat Jan 6 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::drivers::peripherals::MouseUpEvent \- Event that is triggered when a mouse button is released, holds the button that was released\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <mouse\&.h>\fP
.PP
Inherits \fBmaxOS::common::Event< MouseEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMouseUpEvent\fP (uint8_t)"
.br
.RI "\fBEvents\fP "
.ti -1c
.RI "\fB~MouseUpEvent\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbutton\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event that is triggered when a mouse button is released, holds the button that was released\&. 
.PP
Definition at line 54 of file mouse\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MouseUpEvent::MouseUpEvent (uint8_t button)"

.PP
\fBEvents\fP 
.PP
Definition at line 168 of file mouse\&.cpp\&.
.PP
.nf
169 : Event<MouseEvents>(MouseEvents::MOUSE_UP),
170   button(button)
171 {
172 
173 }
.fi
.SS "MouseUpEvent::~MouseUpEvent ()"

.PP
Definition at line 175 of file mouse\&.cpp\&.
.PP
.nf
175                             {
176 
177 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "uint8_t maxOS::drivers::peripherals::MouseUpEvent::button"

.PP
Definition at line 56 of file mouse\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
