.TH "MaxOS::net::EthernetFrameHandler" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::EthernetFrameHandler \- Handles incoming Ethernet Frames and routes them to the appropriate payload handlers\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethernetframe\&.h>\fP
.PP
Inherits \fBMaxOS::drivers::ethernet::EthernetDriverEventHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEthernetFrameHandler\fP (\fBdrivers::ethernet::EthernetDriver\fP *\fBdriver\fP, \fBcommon::OutputStream\fP *\fBerrorMessages\fP)"
.br
.RI "Construct a new Ether Frame Handler object\&. "
.ti -1c
.RI "\fBdrivers::ethernet::MediaAccessControlAddress\fP \fBgetMAC\fP ()"
.br
.RI "Get the MAC address of this device\&. "
.ti -1c
.RI "\fBbool\fP \fBDataReceived\fP (\fBuint8_t\fP *\fBdata\fP, \fBuint32_t\fP \fBsize\fP) \fBoverride\fP"
.br
.RI "Handle the received packet\&. "
.ti -1c
.RI "\fBvoid\fP \fBconnectHandler\fP (\fBEthernetFramePayloadHandler\fP *\fBhandler\fP)"
.br
.RI "Connect a handler to the frame handler\&. "
.ti -1c
.RI "\fBvoid\fP \fBsendEthernetFrame\fP (\fBuint64_t\fP \fBdestinationMAC\fP, \fBuint16_t\fP \fBframeType\fP, \fBuint8_t\fP *\fBdata\fP, \fBuint32_t\fP \fBsize\fP)"
.br
.RI "Send an packet via the backend driver\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::ethernet::EthernetDriverEventHandler\fP
.in +1c
.ti -1c
.RI "\fBEthernetDriverEventHandler\fP ()"
.br
.RI "__EVENT HANDLER___ "
.ti -1c
.RI "\fBvirtual\fP \fBcommon::Event\fP< \fBEthernetDriverEvents\fP > * \fBon_event\fP (\fBcommon::Event\fP< \fBEthernetDriverEvents\fP > *\fBevent\fP) \fBoverride\fP"
.br
.RI "Handle an event\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBBeforeSend\fP (\fBuint8_t\fP *buffer, \fBuint32_t\fP \fBsize\fP)"
.br
.RI "Handle before send event\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBDataSent\fP (\fBuint8_t\fP *buffer, \fBuint32_t\fP \fBsize\fP)"
.br
.RI "Handle data sent event\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::EventHandler< EthernetDriverEvents >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBEvent\fP< EthernetDriverEvents > * \fBon_event\fP (\fBEvent\fP< EthernetDriverEvents > *\fBevent\fP)"
.br
.RI "This function is called when an event is raised\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBcommon::Map\fP< uint16_t, \fBEthernetFramePayloadHandler\fP * > \fBframeHandlers\fP"
.br
.RI "The map of frame handlers by type\&. "
.ti -1c
.RI "\fBdrivers::ethernet::EthernetDriver\fP * \fBethernetDriver\fP"
.br
.RI "The driver this frame handler is using\&. "
.ti -1c
.RI "\fBcommon::OutputStream\fP * \fBerrorMessages\fP"
.br
.RI "The output stream for error messages\&. "
.in -1c
.SH "Detailed Description"
.PP 
Handles incoming Ethernet Frames and routes them to the appropriate payload handlers\&. 
.PP
Definition at line \fB69\fP of file \fBethernetframe\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EthernetFrameHandler::EthernetFrameHandler (\fBdrivers::ethernet::EthernetDriver\fP * driver, \fBcommon::OutputStream\fP * errorMessages)"

.PP
Construct a new Ether Frame Handler object\&. 
.PP
\fBParameters\fP
.RS 4
\fIdriver\fP The backend ethernet driver 
.br
\fIerrorMessages\fP The output stream for error messages 
.RE
.PP

.PP
Definition at line \fB73\fP of file \fBethernetframe\&.cpp\fP\&..PP
.nf
74 : EthernetDriverEventHandler()
75 {
76 
77     this \-> ethernetDriver = driver;
78     this \-> errorMessages = errorMessages;
79 
80     driver\->connect_event_handler(this);
81 
82 }
.fi

.PP
References \fBerrorMessages\fP, and \fBethernetDriver\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP EthernetFrameHandler::connectHandler (\fBEthernetFramePayloadHandler\fP * handler)"

.PP
Connect a handler to the frame handler\&. 
.PP
\fBParameters\fP
.RS 4
\fIhandler\fP The handler to connect 
.RE
.PP

.PP
Definition at line \fB163\fP of file \fBethernetframe\&.cpp\fP\&..PP
.nf
163                                                                               {
164 
165     // Convert the protocol type to big endian
166     uint16_t frameType_BE = ((handler\->handledType >> 8) & 0xFF) | ((handler\->handledType << 8) & 0xFF00);
167 
168     // Add the handler to the list
169     frameHandlers\&.insert(frameType_BE, handler);
170 
171 }
.fi

.PP
References \fBframeHandlers\fP\&.
.PP
Referenced by \fBMaxOS::net::EthernetFramePayloadHandler::EthernetFramePayloadHandler()\fP\&.
.SS "\fBbool\fP EthernetFrameHandler::DataReceived (\fBuint8_t\fP * buffer, \fBuint32_t\fP size)\fC [override]\fP, \fC [virtual]\fP"

.PP
Handle the received packet\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP the buffer with the received data 
.br
\fIsize\fP the size of the received data
.RE
.PP
\fBTodo\fP
.RS 4
Future debugging me: the override is not being called in derived classes 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::ethernet::EthernetDriverEventHandler\fP\&.
.PP
Definition at line \fB104\fP of file \fBethernetframe\&.cpp\fP\&..PP
.nf
104                                                                       {
105 
106     errorMessages \-> write("EFH: Data received\\n");
107 
108 
109     //Check if the size is big enough to contain an ethernet frame
110     if(size < sizeof(EthernetFrameHeader))
111         return false;
112 
113     //Convert to struct for easier use
114     auto* frame = (EthernetFrameHeader*)buffer;
115     bool sendBack = false;
116 
117     //Only handle if it is for this device
118     if(frame\->destinationMAC == 0xFFFFFFFFFFFF                                          //If it is a broadcast
119     || frame\->destinationMAC == ethernetDriver \-> GetMediaAccessControlAddress())      //If it is for this device
120     {
121 
122         // Find the handler for the protocol
123         Map<uint16_t , EthernetFramePayloadHandler*>::iterator handlerIterator = frameHandlers\&.find(frame\->type);
124 
125         // If the handler is found
126         if(handlerIterator != frameHandlers\&.end()) {
127 
128             //Handle the data
129             errorMessages \-> write("EFH: Handling ethernet frame payload\\n");
130             sendBack = handlerIterator\->second\->handleEthernetframePayload(buffer + sizeof(EthernetFrameHeader), size \- sizeof(EthernetFrameHeader));
131             errorMessages \-> write("\&.\&.DONE\\n");
132 
133         } else {
134 
135             //If the handler is not found, print an error message
136             errorMessages \-> write("EFH: Unhandled ethernet frame type 0x");
137             errorMessages\->write_hex(frame\->type);
138             errorMessages \-> write("\\n");
139 
140         }
141     }
142 
143     //If the data is to be sent back again
144     if(sendBack){
145 
146         errorMessages \-> write("EFH: Sending back\\n");
147 
148         frame \-> destinationMAC = frame \-> sourceMAC;                             //Set the new destination to be the device the data was received from
149         frame \-> sourceMAC = ethernetDriver\->GetMediaAccessControlAddress();      //Set the new source to be this device's MAC address
150 
151     }
152 
153     //Return if the data is to be sent back
154     return sendBack;
155 
156 }
.fi

.PP
References \fBdestinationMAC\fP, \fBerrorMessages\fP, \fBethernetDriver\fP, \fBframeHandlers\fP, \fBMaxOS::drivers::ethernet::EthernetDriver::GetMediaAccessControlAddress()\fP, \fBsize\fP, \fBsourceMAC\fP, \fBwrite\fP, and \fBMaxOS::common::OutputStream::write_hex()\fP\&.
.SS "\fBdrivers::ethernet::MediaAccessControlAddress\fP EthernetFrameHandler::getMAC ()"

.PP
Get the MAC address of this device\&. 
.PP
\fBReturns\fP
.RS 4
MediaAccessControlAddress The MAC address 
.RE
.PP

.PP
Definition at line \fB91\fP of file \fBethernetframe\&.cpp\fP\&..PP
.nf
91                                                                       {
92     return ethernetDriver \-> GetMediaAccessControlAddress();
93 }
.fi

.PP
References \fBethernetDriver\fP\&.
.SS "\fBvoid\fP EthernetFrameHandler::sendEthernetFrame (\fBuint64_t\fP destinationMAC, \fBuint16_t\fP frameType, \fBuint8_t\fP * data, \fBuint32_t\fP size)"

.PP
Send an packet via the backend driver\&. 
.PP
\fBParameters\fP
.RS 4
\fIdestinationMAC\fP the destination MAC address 
.br
\fIframeType\fP the type of the protocol 
.br
\fIdata\fP the data to send 
.br
\fIsize\fP the size of the payload 
.RE
.PP

.PP
Definition at line \fB181\fP of file \fBethernetframe\&.cpp\fP\&..PP
.nf
181                                                                                                                       {
182 
183     errorMessages\->write("EFH: Sending frame\&.\&.\&.");
184 
185     //Allocate memory for the buffer
186     auto* buffer = (uint8_t*)MemoryManager::kmalloc(size + sizeof(EthernetFrameHeader));
187     auto* frame = (EthernetFrameHeader*)buffer;
188 
189     //Put data in the header
190     frame \-> destinationMAC = destinationMAC;
191     frame \-> sourceMAC = ethernetDriver \-> GetMediaAccessControlAddress();
192     frame \-> type = (frameType >> 8) | (frameType << 8);                        //Convert to big endian
193 
194     //Copy the data
195     for(uint8_t *src = data + size \- 1, *dst = buffer+sizeof(EthernetFrameHeader)+size\-1; src >= data; \-\-src, \-\-dst)
196         *dst = *src;
197 
198     //Send the data
199     ethernetDriver \-> Send(buffer, size + sizeof(EthernetFrameHeader));
200 
201     errorMessages\->write("Done\\n");
202 
203 
204     //Free the buffer
205     MemoryManager::kfree(buffer);
206 }
.fi

.PP
References \fBdata\fP, \fBdestinationMAC\fP, \fBerrorMessages\fP, \fBethernetDriver\fP, \fBMaxOS::memory::MemoryManager::kfree()\fP, \fBMaxOS::memory::MemoryManager::kmalloc()\fP, \fBsize\fP, \fBsourceMAC\fP, \fBtype\fP, and \fBMaxOS::common::OutputStream::write()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBcommon::OutputStream\fP* MaxOS::net::EthernetFrameHandler::errorMessages\fC [protected]\fP"

.PP
The output stream for error messages\&. 
.PP
Definition at line \fB75\fP of file \fBethernetframe\&.h\fP\&.
.PP
Referenced by \fBDataReceived()\fP, \fBEthernetFrameHandler()\fP, and \fBsendEthernetFrame()\fP\&.
.SS "\fBdrivers::ethernet::EthernetDriver\fP* MaxOS::net::EthernetFrameHandler::ethernetDriver\fC [protected]\fP"

.PP
The driver this frame handler is using\&. 
.PP
Definition at line \fB74\fP of file \fBethernetframe\&.h\fP\&.
.PP
Referenced by \fBDataReceived()\fP, \fBEthernetFrameHandler()\fP, \fBgetMAC()\fP, and \fBsendEthernetFrame()\fP\&.
.SS "\fBcommon::Map\fP<uint16_t, \fBEthernetFramePayloadHandler\fP*> MaxOS::net::EthernetFrameHandler::frameHandlers\fC [protected]\fP"

.PP
The map of frame handlers by type\&. 
.PP
Definition at line \fB72\fP of file \fBethernetframe\&.h\fP\&.
.PP
Referenced by \fBconnectHandler()\fP, and \fBDataReceived()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
