.TH "maxOS::memory::MemIO" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::memory::MemIO \- base class for all memory IO  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memoryIO\&.h>\fP
.PP
Inherited by \fBmaxOS::memory::MemIO16Bit\fP, \fBmaxOS::memory::MemIO32Bit\fP, \fBmaxOS::memory::MemIO64Bit\fP, and \fBmaxOS::memory::MemIO8Bit\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBMemIO\fP (uint32_t \fBaddress\fP)"
.br
.ti -1c
.RI "\fB~MemIO\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBm_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
base class for all memory IO 
.PP
Definition at line 18 of file memoryIO\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MemIO::MemIO (uint32_t address)\fC [protected]\fP"

.PP
Definition at line 9 of file memoryIO\&.cpp\&.
.PP
.nf
10 : m_address(address)
11 {
12 
13 }
.fi
.SS "MemIO::~MemIO ()\fC [protected]\fP"

.PP
Definition at line 15 of file memoryIO\&.cpp\&.
.PP
.nf
15               {
16 
17 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "uint32_t maxOS::memory::MemIO::m_address\fC [protected]\fP"

.PP
Definition at line 20 of file memoryIO\&.h\&.
.PP
Referenced by maxOS::memory::MemIO8Bit::read(), maxOS::memory::MemIO16Bit::read(), maxOS::memory::MemIO32Bit::read(), maxOS::memory::MemIO64Bit::read(), maxOS::memory::MemIO8Bit::write(), maxOS::memory::MemIO16Bit::write(), maxOS::memory::MemIO32Bit::write(), and maxOS::memory::MemIO64Bit::write()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
