.TH "MaxOS::gui" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::gui
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBwidgets\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompositeWidget\fP"
.br
.RI "A widget that can contain other widgets\&. "
.ti -1c
.RI "class \fBDesktop\fP"
.br
.RI "The desktop that contains all the windows, handles the drawing of the screen and the mouse on every tick\&. "
.ti -1c
.RI "class \fBFont\fP"
.br
.RI "A class that can be used to draw text\&. "
.ti -1c
.RI "class \fBWidget\fP"
.br
.RI "A graphical object that can be drawn on the screen\&. "
.ti -1c
.RI "class \fBWidgetMoverResizer\fP"
.br
.RI "A template class that allows you to move and resize a widget\&. "
.ti -1c
.RI "class \fBWindow\fP"
.br
.RI "A window that can be moved and resized and contains a widget\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 1, 1, 0, 0 > \fBWidgetMover\fP"
.br
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 1, 0, \-1 > \fBWidgetMoverResizerTop\fP"
.br
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 0, 0, 1 > \fBWidgetMoverResizerBottom\fP"
.br
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 1, 0, \-1, 0 > \fBWidgetMoverResizerLeft\fP"
.br
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 0, 1, 0 > \fBWidgetMoverResizerRight\fP"
.br
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 1, 1, \-1, \-1 > \fBWidgetMoverResizerTopLeft\fP"
.br
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 1, 1, \-1 > \fBWidgetMoverResizerTopRight\fP"
.br
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 1, 0, \-1, 1 > \fBWidgetMoverResizerBottomLeft\fP"
.br
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 0, 1, 1 > \fBWidgetMoverResizerBottomRight\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBWidgetMoverResizer\fP<1, 1, 0, 0> \fBMaxOS::gui::WidgetMover\fP"

.PP
Definition at line 134 of file widget\&.h\&.
.SS "typedef \fBWidgetMoverResizer\fP<0, 0, 0, 1> \fBMaxOS::gui::WidgetMoverResizerBottom\fP"

.PP
Definition at line 137 of file widget\&.h\&.
.SS "typedef \fBWidgetMoverResizer\fP<1, 0, \-1, 1> \fBMaxOS::gui::WidgetMoverResizerBottomLeft\fP"

.PP
Definition at line 143 of file widget\&.h\&.
.SS "typedef \fBWidgetMoverResizer\fP<0, 0, 1, 1> \fBMaxOS::gui::WidgetMoverResizerBottomRight\fP"

.PP
Definition at line 144 of file widget\&.h\&.
.SS "typedef \fBWidgetMoverResizer\fP<1, 0, \-1, 0> \fBMaxOS::gui::WidgetMoverResizerLeft\fP"

.PP
Definition at line 138 of file widget\&.h\&.
.SS "typedef \fBWidgetMoverResizer\fP<0, 0, 1, 0> \fBMaxOS::gui::WidgetMoverResizerRight\fP"

.PP
Definition at line 139 of file widget\&.h\&.
.SS "typedef \fBWidgetMoverResizer\fP<0, 1, 0, \-1> \fBMaxOS::gui::WidgetMoverResizerTop\fP"

.PP
Definition at line 136 of file widget\&.h\&.
.SS "typedef \fBWidgetMoverResizer\fP<1, 1, \-1, \-1> \fBMaxOS::gui::WidgetMoverResizerTopLeft\fP"

.PP
Definition at line 141 of file widget\&.h\&.
.SS "typedef \fBWidgetMoverResizer\fP<0, 1, 1, \-1> \fBMaxOS::gui::WidgetMoverResizerTopRight\fP"

.PP
Definition at line 142 of file widget\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
