.TH "MaxOS::drivers::peripherals::KeyUpEvent" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::peripherals::KeyUpEvent \- Event that is triggered when a key is released\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyboard\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< KeyboardEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyUpEvent\fP (\fBKeyCode\fP, \fBconst\fP \fBKeyboardState\fP &)"
.br
.RI "Constructor for the \fBKeyUpEvent\fP class\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::Event< KeyboardEvents >\fP
.in +1c
.ti -1c
.RI "\fBEvent\fP (KeyboardEvents type)"
.br
.RI "Constructs a new \fBEvent\fP object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBKeyCode\fP \fBkey_code\fP"
.br
.RI "The key code of the key that was released\&. "
.ti -1c
.RI "\fBKeyboardState\fP \fBkeyboard_state\fP"
.br
.RI "The state of the keyboard when the key was released\&. "
.in -1c

Public Attributes inherited from \fBMaxOS::common::Event< KeyboardEvents >\fP
.in +1c
.ti -1c
.RI "KeyboardEvents \fBtype\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbuffer_value\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBint_value\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBbool_value\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBuint8_t\fP * \fBbuffer_value\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBint_value\fP"
.br
.ti -1c
.RI "   \fBbool\fP \fBbool_value\fP"
.br
.ti -1c
.RI "} \fBreturn_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event that is triggered when a key is released\&. 
.PP
Definition at line \fB248\fP of file \fBkeyboard\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KeyUpEvent::KeyUpEvent (\fBKeyCode\fP key_code, \fBconst\fP \fBKeyboardState\fP & keyboard_state)"

.PP
Constructor for the \fBKeyUpEvent\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIkey_code\fP The keycode of the key that was released 
.br
\fIkeyboard_state\fP The state of the keyboard when the key was released 
.RE
.PP

.PP
Definition at line \fB677\fP of file \fBkeyboard\&.cpp\fP\&..PP
.nf
678 : Event<KeyboardEvents>(KeyboardEvents::KEYUP),
679   key_code(key_code),
680   keyboard_state(keyboard_state)
681 {
682 }
.fi

.SH "Member Data Documentation"
.PP 
.SS "\fBKeyCode\fP MaxOS::drivers::peripherals::KeyUpEvent::key_code"

.PP
The key code of the key that was released\&. 
.PP
Definition at line \fB253\fP of file \fBkeyboard\&.h\fP\&.
.SS "\fBKeyboardState\fP MaxOS::drivers::peripherals::KeyUpEvent::keyboard_state"

.PP
The state of the keyboard when the key was released\&. 
.PP
Definition at line \fB254\fP of file \fBkeyboard\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
