.TH "MaxOS::StringBuilder" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::StringBuilder \- Creates a string using a using a combination of parts with the '<<' operator\&. Simmilar to the logger\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <string\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBoperator String\fP () const"
.br
.RI "Convert to string\&. "
.ti -1c
.RI "\fBStringBuilder\fP & \fBoperator<<\fP (char const *str)"
.br
.RI "Append C-string to the \fBStringBuilder\fP\&. "
.ti -1c
.RI "\fBStringBuilder\fP & \fBoperator<<\fP (\fBString\fP const &other)"
.br
.RI "Append \fBString\fP to the \fBStringBuilder\fP\&. "
.ti -1c
.RI "\fBStringBuilder\fP & \fBoperator<<\fP (int value)"
.br
.RI "Append int to the \fBStringBuilder\fP\&. "
.ti -1c
.RI "\fBStringBuilder\fP & \fBoperator<<\fP (uint64_t value)"
.br
.RI "Append a hex to the \fBStringBuilder\fP\&. "
.ti -1c
.RI "\fBStringBuilder\fP & \fBoperator<<\fP (bool value)"
.br
.RI "Append bool to the \fBStringBuilder\fP\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBout\fP"
.br
.RI "The output string\&. "
.in -1c
.SH "Detailed Description"
.PP 
Creates a string using a using a combination of parts with the '<<' operator\&. Simmilar to the logger\&. 


.PP
\fBSee also\fP
.RS 4
\fBLogger\fP 
.RE
.PP

.PP
Definition at line \fB97\fP of file \fBstring\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "MaxOS::StringBuilder::operator \fBString\fP () const\fC [inline]\fP"

.PP
Convert to string\&. 
.PP
Definition at line \fB100\fP of file \fBstring\&.h\fP\&.
.PP
References \fBout\fP\&.
.SS "\fBStringBuilder\fP & StringBuilder::operator<< (bool value)"

.PP
Append bool to the \fBStringBuilder\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The bool value to append 
.RE
.PP
\fBReturns\fP
.RS 4
The \fBStringBuilder\fP reference 
.RE
.PP

.PP
Definition at line \fB932\fP of file \fBstring\&.cpp\fP\&..PP
.nf
932                                                     {
933     out += string(value);
934     return *this;
935 }
.fi

.PP
References \fBout\fP\&.
.SS "\fBStringBuilder\fP & StringBuilder::operator<< (char const * str)"

.PP
Append C-string to the \fBStringBuilder\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr\fP The C-string to append 
.RE
.PP
\fBReturns\fP
.RS 4
The \fBStringBuilder\fP reference 
.RE
.PP

.PP
Definition at line \fB888\fP of file \fBstring\&.cpp\fP\&..PP
.nf
888                                                          {
889     out += string(str);
890     return *this;
891 }
.fi

.PP
References \fBout\fP\&.
.SS "\fBStringBuilder\fP & StringBuilder::operator<< (int value)"

.PP
Append int to the \fBStringBuilder\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The int value to append 
.RE
.PP
\fBReturns\fP
.RS 4
The \fBStringBuilder\fP reference 
.RE
.PP

.PP
Definition at line \fB910\fP of file \fBstring\&.cpp\fP\&..PP
.nf
910                                                    {
911     out += string(value);
912     return *this;
913 }
.fi

.PP
References \fBout\fP\&.
.SS "\fBStringBuilder\fP & StringBuilder::operator<< (\fBString\fP const & other)"

.PP
Append \fBString\fP to the \fBStringBuilder\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIother\fP The \fBString\fP to append 
.RE
.PP
\fBReturns\fP
.RS 4
The \fBStringBuilder\fP reference 
.RE
.PP

.PP
Definition at line \fB899\fP of file \fBstring\&.cpp\fP\&..PP
.nf
899                                                              {
900     out += other;
901     return *this;
902 }
.fi

.PP
References \fBout\fP\&.
.SS "\fBStringBuilder\fP & StringBuilder::operator<< (uint64_t value)"

.PP
Append a hex to the \fBStringBuilder\fP\&. 
.PP
\fBParameters\fP
.RS 4
\fIvalue\fP The hex value to append 
.RE
.PP
\fBReturns\fP
.RS 4
The \fBStringBuilder\fP reference 
.RE
.PP

.PP
Definition at line \fB921\fP of file \fBstring\&.cpp\fP\&..PP
.nf
921                                                         {
922     out += string(value);
923     return *this;
924 }
.fi

.PP
References \fBout\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBString\fP MaxOS::StringBuilder::out"

.PP
The output string\&. 
.PP
Definition at line \fB99\fP of file \fBstring\&.h\fP\&.
.PP
Referenced by \fBoperator String()\fP, \fBoperator<<()\fP, \fBoperator<<()\fP, \fBoperator<<()\fP, \fBoperator<<()\fP, \fBoperator<<()\fP, and \fBMaxOS::tests::Test::run()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
