.TH "MaxOS::net::TCPHeader" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::TCPHeader \- The header of a TCP packet\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBsrcPort\fP"
.br
.RI "The port of the sender\&. "
.ti -1c
.RI "uint16_t \fBdstPort\fP"
.br
.RI "The port of the receiver\&. "
.ti -1c
.RI "uint32_t \fBsequenceNumber\fP"
.br
.RI "Where this packet's data fits in the overall order of the data stream\&. "
.ti -1c
.RI "uint32_t \fBacknowledgementNumber\fP"
.br
.RI "The next expected sequence number from the sender (used by the receiver to request the next data) "
.ti -1c
.RI "uint8_t \fBreserved\fP: 4"
.br
.RI "Unused, must be 0\&. "
.ti -1c
.RI "uint8_t \fBheaderSize32\fP: 4"
.br
.RI "The size of the header in 32-bit words\&. "
.ti -1c
.RI "uint8_t \fBflags\fP"
.br
.RI "The flags of the TCP packet (see TCPFlag enum) "
.ti -1c
.RI "uint16_t \fBwindowSize\fP"
.br
.RI "How many bytes the sender is willing to receive\&. "
.ti -1c
.RI "uint16_t \fBchecksum\fP"
.br
.RI "The checksum of the header\&. "
.ti -1c
.RI "uint16_t \fBurgentPtr\fP"
.br
.RI "Where in the data the urgent data \fIends\fP (if the URG flag is set) "
.ti -1c
.RI "uint32_t \fBoptions\fP"
.br
.RI "The options for the TCP packet (MSS, Window Scale, SACK Permitted) "
.in -1c
.SH "Detailed Description"
.PP 
The header of a TCP packet\&. 
.PP
Definition at line \fB63\fP of file \fBtcp\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t MaxOS::net::TCPHeader::acknowledgementNumber"

.PP
The next expected sequence number from the sender (used by the receiver to request the next data) 
.PP
Definition at line \fB67\fP of file \fBtcp\&.h\fP\&.
.SS "uint16_t MaxOS::net::TCPHeader::checksum"

.PP
The checksum of the header\&. 
.PP
Definition at line \fB74\fP of file \fBtcp\&.h\fP\&.
.SS "uint16_t MaxOS::net::TCPHeader::dstPort"

.PP
The port of the receiver\&. 
.PP
Definition at line \fB65\fP of file \fBtcp\&.h\fP\&.
.SS "uint8_t MaxOS::net::TCPHeader::flags"

.PP
The flags of the TCP packet (see TCPFlag enum) 
.PP
Definition at line \fB71\fP of file \fBtcp\&.h\fP\&.
.SS "uint8_t MaxOS::net::TCPHeader::headerSize32"

.PP
The size of the header in 32-bit words\&. 
.PP
Definition at line \fB70\fP of file \fBtcp\&.h\fP\&.
.SS "uint32_t MaxOS::net::TCPHeader::options"

.PP
The options for the TCP packet (MSS, Window Scale, SACK Permitted) 
.PP
\fBTodo\fP
.RS 4
: make this a struct 
.RE
.PP

.PP
Definition at line \fB77\fP of file \fBtcp\&.h\fP\&.
.SS "uint8_t MaxOS::net::TCPHeader::reserved"

.PP
Unused, must be 0\&. 
.PP
Definition at line \fB69\fP of file \fBtcp\&.h\fP\&.
.SS "uint32_t MaxOS::net::TCPHeader::sequenceNumber"

.PP
Where this packet's data fits in the overall order of the data stream\&. 
.PP
Definition at line \fB66\fP of file \fBtcp\&.h\fP\&.
.SS "uint16_t MaxOS::net::TCPHeader::srcPort"

.PP
The port of the sender\&. 
.PP
Definition at line \fB64\fP of file \fBtcp\&.h\fP\&.
.SS "uint16_t MaxOS::net::TCPHeader::urgentPtr"

.PP
Where in the data the urgent data \fIends\fP (if the URG flag is set) 
.PP
Definition at line \fB75\fP of file \fBtcp\&.h\fP\&.
.SS "uint16_t MaxOS::net::TCPHeader::windowSize"

.PP
How many bytes the sender is willing to receive\&. 
.PP
Definition at line \fB73\fP of file \fBtcp\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
