.TH "MaxOS::drivers::ethernet" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::ethernet
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBamd_am79c973\fP"
.br
.ti -1c
.RI "class \fBBeforeSendEvent\fP"
.br
.RI "Event that is triggered before data is sent, holds the buffer and size of the data\&. "
.ti -1c
.RI "class \fBDataReceivedEvent\fP"
.br
.RI "Event that is triggered when data is received, holds the buffer and size of the data\&. "
.ti -1c
.RI "class \fBDataSentEvent\fP"
.br
.RI "Event that is triggered when data is sent, holds the buffer and size of the data\&. "
.ti -1c
.RI "class \fBEthernetDriver\fP"
.br
.RI "\fBDriver\fP for the Ethernet Controller, manages the sending and receiving of data, the mac address, and the events\&. "
.ti -1c
.RI "class \fBEthernetDriverEventHandler\fP"
.br
.RI "Handles the events that are triggered by the Ethernet \fBDriver\fP\&. "
.ti -1c
.RI "class \fBintel_i217\fP"
.br
.ti -1c
.RI "class \fBRawDataHandler\fP"
.br
.RI "Handles raw data received from the ethernet controller\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef uint64_t \fBMediaAccessControlAddress\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBEthernetDriverEvents\fP { \fBBEFORE_SEND\fP, \fBDATA_SENT\fP, \fBDATA_RECEIVED\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "enum \fBMaxOS::drivers::ethernet::EthernetDriverEvents\fP \fB__attribute__\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef uint64_t \fBMaxOS::drivers::ethernet::MediaAccessControlAddress\fP"

.PP
Definition at line 19 of file ethernet\&.h\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMaxOS::drivers::ethernet::EthernetDriverEvents\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIBEFORE_SEND \fP\fP
.TP
\fB\fIDATA_SENT \fP\fP
.TP
\fB\fIDATA_RECEIVED \fP\fP
.PP
Definition at line 21 of file ethernet\&.h\&.
.PP
.nf
21                                      {
22                 BEFORE_SEND,
23                 DATA_SENT,
24                 DATA_RECEIVED
25             };
.fi
.SH "Variable Documentation"
.PP 
.SS "class \fBMaxOS::drivers::ethernet::RawDataHandler\fP MaxOS::drivers::ethernet::__attribute__"

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
