.TH "MaxOS::net::TCPPseudoHeader" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::TCPPseudoHeader \- The pseudo header used for TCP checksum calculation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBsrcIP\fP"
.br
.RI "The IP address of the sender\&. "
.ti -1c
.RI "uint32_t \fBdstIP\fP"
.br
.RI "The IP address of the receiver\&. "
.ti -1c
.RI "uint16_t \fBprotocol\fP"
.br
.RI "The protocol (set to 6 for TCP) "
.ti -1c
.RI "uint16_t \fBtotalLength\fP"
.br
.RI "The total length of the TCP header and data\&. "
.in -1c
.SH "Detailed Description"
.PP 
The pseudo header used for TCP checksum calculation\&. 

The pseudo header is used to calculate the checksum of the TCP header\&. It is a copy of the IP header, but with the protocol field set to 6 (TCP) and the length field set to the length of the TCP header\&. 
.PP
Definition at line \fB87\fP of file \fBtcp\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t MaxOS::net::TCPPseudoHeader::dstIP"

.PP
The IP address of the receiver\&. 
.PP
Definition at line \fB89\fP of file \fBtcp\&.h\fP\&.
.SS "uint16_t MaxOS::net::TCPPseudoHeader::protocol"

.PP
The protocol (set to 6 for TCP) 
.PP
Definition at line \fB90\fP of file \fBtcp\&.h\fP\&.
.SS "uint32_t MaxOS::net::TCPPseudoHeader::srcIP"

.PP
The IP address of the sender\&. 
.PP
Definition at line \fB88\fP of file \fBtcp\&.h\fP\&.
.SS "uint16_t MaxOS::net::TCPPseudoHeader::totalLength"

.PP
The total length of the TCP header and data\&. 
.PP
Definition at line \fB91\fP of file \fBtcp\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
