.TH "MaxOS::filesystem::MasterBootRecord" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::MasterBootRecord \- Stores information about the master boot record\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msdospart\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbootloader\fP [440]"
.br
.ti -1c
.RI "uint32_t \fBdiskSignature\fP"
.br
.ti -1c
.RI "uint16_t \fBunused\fP"
.br
.ti -1c
.RI "\fBPartitionTableEntry\fP \fBprimaryPartition\fP [4]"
.br
.ti -1c
.RI "uint16_t \fBmagicNumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores information about the master boot record\&. 
.PP
Definition at line 43 of file msdospart\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::filesystem::MasterBootRecord::bootloader[440]"

.PP
Definition at line 45 of file msdospart\&.h\&.
.SS "uint32_t MaxOS::filesystem::MasterBootRecord::diskSignature"

.PP
Definition at line 46 of file msdospart\&.h\&.
.SS "uint16_t MaxOS::filesystem::MasterBootRecord::magicNumber"

.PP
Definition at line 51 of file msdospart\&.h\&.
.SS "\fBPartitionTableEntry\fP MaxOS::filesystem::MasterBootRecord::primaryPartition[4]"

.PP
Definition at line 49 of file msdospart\&.h\&.
.SS "uint16_t MaxOS::filesystem::MasterBootRecord::unused"

.PP
Definition at line 47 of file msdospart\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
