.TH "MaxOS::hardwarecommunication::Port32Bit" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::Port32Bit \- Handles 32 bit ports\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <port\&.h>\fP
.PP
Inherits \fBMaxOS::hardwarecommunication::Port\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPort32Bit\fP (uint16_t port_number)"
.br
.ti -1c
.RI "\fB~Port32Bit\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (uint32_t \fBdata\fP)"
.br
.RI "write a double word to the port (32Bit) "
.ti -1c
.RI "virtual uint32_t \fBread\fP ()"
.br
.RI "read a double word from the port (32Bit) "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::hardwarecommunication::Port\fP
.in +1c
.ti -1c
.RI "\fBPort\fP (uint16_t port_number)"
.br
.ti -1c
.RI "\fB~Port\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBMaxOS::hardwarecommunication::Port\fP
.in +1c
.ti -1c
.RI "uint16_t \fBm_port_number\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles 32 bit ports\&. 
.PP
Definition at line \fB66\fP of file \fBport\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Port32Bit::Port32Bit (uint16_t port_number)"

.PP
Definition at line \fB90\fP of file \fBport\&.cpp\fP\&..PP
.nf
91 : Port(port_number) {
92 }
.fi

.SS "Port32Bit::~Port32Bit ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "uint32_t Port32Bit::read ()\fC [virtual]\fP"

.PP
read a double word from the port (32Bit) 
.PP
\fBReturns\fP
.RS 4
the double word read 
.RE
.PP

.PP
Definition at line \fB111\fP of file \fBport\&.cpp\fP\&..PP
.nf
111                          {
112 
113     uint32_t result;
114     asm volatile("inl %1, %0" : "=a" (result) : "Nd" (m_port_number));
115     return result;
116 }
.fi

.PP
References \fBMaxOS::hardwarecommunication::Port::m_port_number\fP\&.
.SS "void Port32Bit::write (uint32_t data)\fC [virtual]\fP"

.PP
write a double word to the port (32Bit) 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP the double word to write 
.RE
.PP

.PP
Definition at line \fB101\fP of file \fBport\&.cpp\fP\&..PP
.nf
101                                    {
102 
103     asm volatile("outl %0, %1" : : "a" (data), "Nd" (m_port_number));
104 }
.fi

.PP
References \fBdata\fP, and \fBMaxOS::hardwarecommunication::Port::m_port_number\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
