.TH "MaxOS::common::Spinlock" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::common::Spinlock \- Enables a resource to be used by only one instance at a time through locking and unlocking\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <spinlock\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSpinlock\fP (\fBbool\fP \fBshould_yield\fP=\fBfalse\fP)"
.br
.ti -1c
.RI "\fB~Spinlock\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBlock\fP ()"
.br
.RI "Lock the spinlock once it is available\&. "
.ti -1c
.RI "\fBvoid\fP \fBunlock\fP ()"
.br
.RI "Unlock the spinlock\&. "
.ti -1c
.RI "\fBbool\fP \fBis_locked\fP () \fBconst\fP"
.br
.RI "Check if the spinlock is locked\&. "
.ti -1c
.RI "\fBvoid\fP \fBacquire\fP ()"
.br
.RI "Acquire the spinlock: wait until the lock is available, yielding if desired until that happens\&. "
.ti -1c
.RI "\fBvoid\fP \fBrelease\fP ()"
.br
.RI "Release the spinlock\&. "
.in -1c
.SH "Detailed Description"
.PP 
Enables a resource to be used by only one instance at a time through locking and unlocking\&. 
.PP
Definition at line \fB16\fP of file \fBspinlock\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Spinlock::Spinlock (\fBbool\fP should_yield = \fC\fBfalse\fP\fP)"

.PP
Definition at line \fB12\fP of file \fBspinlock\&.cpp\fP\&..PP
.nf
13 : m_should_yield(should_yield) {
14 
15 }
.fi

.SS "Spinlock::~Spinlock ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Spinlock::acquire ()"

.PP
Acquire the spinlock: wait until the lock is available, yielding if desired until that happens\&. 
.PP
Definition at line \fB50\fP of file \fBspinlock\&.cpp\fP\&..PP
.nf
50                        {
51     while (__atomic_test_and_set(&m_locked, __ATOMIC_ACQUIRE)) {
52 
53         // Wait for the lock to be available
54         if (m_should_yield)
55             Scheduler::system_scheduler()\->yield();
56 
57     }
58 }
.fi

.PP
References \fBMaxOS::processes::Scheduler::system_scheduler()\fP\&.
.PP
Referenced by \fBlock()\fP\&.
.SS "\fBbool\fP Spinlock::is_locked () const"

.PP
Check if the spinlock is locked\&. 
.PP
\fBReturns\fP
.RS 4
True if the spinlock is locked, false otherwise 
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBspinlock\&.cpp\fP\&..PP
.nf
42                                {
43     return m_locked;
44 }
.fi

.SS "\fBvoid\fP Spinlock::lock ()"

.PP
Lock the spinlock once it is available\&. 
.PP
Definition at line \fB22\fP of file \fBspinlock\&.cpp\fP\&..PP
.nf
22                     {
23 
24     acquire();
25     m_locked = true;
26 }
.fi

.PP
References \fBacquire()\fP\&.
.PP
Referenced by \fBMaxOS::memory::PhysicalMemoryManager::allocate_area()\fP, \fBMaxOS::memory::PhysicalMemoryManager::allocate_frame()\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::create_inode()\fP, \fBMaxOS::filesystem::format::ext2::InodeHandler::free()\fP, \fBMaxOS::memory::PhysicalMemoryManager::free_area()\fP, \fBMaxOS::memory::PhysicalMemoryManager::free_frame()\fP, \fBMaxOS::filesystem::format::ext2::Ext2File::read()\fP, \fBMaxOS::filesystem::format::ext2::Ext2Directory::read_from_disk()\fP, \fBMaxOS::memory::PhysicalMemoryManager::reserve()\fP, \fBMaxOS::filesystem::format::ext2::Ext2File::write()\fP, and \fBMaxOS::processes::SharedMessageEndpoint::write()\fP\&.
.SS "\fBvoid\fP Spinlock::release ()"

.PP
Release the spinlock\&. 
.PP
Definition at line \fB63\fP of file \fBspinlock\&.cpp\fP\&..PP
.nf
63                        {
64     __atomic_clear(&m_locked, __ATOMIC_RELEASE);
65 }
.fi

.PP
Referenced by \fBunlock()\fP\&.
.SS "\fBvoid\fP Spinlock::unlock ()"

.PP
Unlock the spinlock\&. 
.PP
Definition at line \fB31\fP of file \fBspinlock\&.cpp\fP\&..PP
.nf
31                       {
32 
33     m_locked = false;
34     release();
35 }
.fi

.PP
References \fBrelease()\fP\&.
.PP
Referenced by \fBMaxOS::memory::PhysicalMemoryManager::allocate_area()\fP, \fBMaxOS::memory::PhysicalMemoryManager::allocate_frame()\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::create_inode()\fP, \fBMaxOS::filesystem::format::ext2::InodeHandler::free()\fP, \fBMaxOS::memory::PhysicalMemoryManager::free_area()\fP, \fBMaxOS::memory::PhysicalMemoryManager::free_frame()\fP, \fBMaxOS::filesystem::format::ext2::Ext2File::read()\fP, \fBMaxOS::filesystem::format::ext2::Ext2Directory::read_from_disk()\fP, \fBMaxOS::memory::PhysicalMemoryManager::reserve()\fP, \fBMaxOS::filesystem::format::ext2::Ext2File::write()\fP, and \fBMaxOS::processes::SharedMessageEndpoint::write()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
