.TH "MaxOS::filesystem::FileSystem" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::FileSystem \- Handles the disk operations and file system information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filesystem\&.h>\fP
.PP
Inherited by \fBMaxOS::filesystem::format::Fat32FileSystem\fP, and \fBMaxOS::filesystem::format::ext2::Ext2FileSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fB~FileSystem\fP ()"
.br
.RI "Destructor for \fBFileSystem\fP, frees the root directory (Which in turn frees all files and subdirectories) "
.ti -1c
.RI "\fBDirectory\fP * \fBroot_directory\fP ()"
.br
.RI "Get the directory at '/'\&. "
.ti -1c
.RI "\fBDirectory\fP * \fBget_directory\fP (\fBconst\fP \fBstring\fP &\fBpath\fP)"
.br
.RI "Get the directory at a given path\&. "
.ti -1c
.RI "\fBbool\fP \fBexists\fP (\fBconst\fP \fBstring\fP &\fBpath\fP)"
.br
.RI "Check if a path exists on the filesystem\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBDirectory\fP * \fBm_root_directory\fP = nullptr"
.br
.RI "The fist directory in the file system (not be confused with the system root) "
.in -1c
.SH "Detailed Description"
.PP 
Handles the disk operations and file system information\&. 
.PP
Definition at line \fB96\fP of file \fBfilesystem\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileSystem::~FileSystem ()\fC [virtual]\fP"

.PP
Destructor for \fBFileSystem\fP, frees the root directory (Which in turn frees all files and subdirectories) 
.PP
Definition at line \fB285\fP of file \fBfilesystem\&.cpp\fP\&..PP
.nf
285                         {
286 
287     // Free the root directory
288     delete m_root_directory;
289 
290 }
.fi

.PP
References \fBm_root_directory\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP FileSystem::exists (\fBconst\fP \fBstring\fP & path)"

.PP
Check if a path exists on the filesystem\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP The path to check 
.RE
.PP
\fBReturns\fP
.RS 4
True if the path exists, false otherwise 
.RE
.PP

.PP
Definition at line \fB342\fP of file \fBfilesystem\&.cpp\fP\&..PP
.nf
342                                           {
343 
344     // Get the directory at the path
345     string directory_path = Path::file_path(path);
346     Directory* directory = get_directory(directory_path);
347 
348     // Check if the directory exists
349     if (!directory)
350         return false;
351 
352     // Check if the file exists
353     const string file_name = Path::file_name(path);
354     return directory\->open_file(file_name) != nullptr;
355 }
.fi

.PP
References \fBMaxOS::filesystem::Path::file_name()\fP, \fBMaxOS::filesystem::Path::file_path()\fP, \fBget_directory()\fP, and \fBMaxOS::filesystem::Directory::open_file()\fP\&.
.SS "\fBDirectory\fP * FileSystem::get_directory (\fBconst\fP \fBstring\fP & path)"

.PP
Get the directory at a given path\&. 
.PP
\fBParameters\fP
.RS 4
\fIpath\fP The path to the directory 
.RE
.PP
\fBReturns\fP
.RS 4
The directory object or null if it could not be opened 
.RE
.PP

.PP
Definition at line \fB307\fP of file \fBfilesystem\&.cpp\fP\&..PP
.nf
307                                                        {
308 
309     // Check if the path is the root
310     if (path == "/")
311         return root_directory();
312 
313     // Recursively open the directory
314     Directory* directory = root_directory();
315     string directory_path = path;
316     while (directory_path\&.length() > 0) {
317 
318         // Get the name of the directory
319         string directory_name = Path::top_directory(directory_path);
320 
321         // Open the directory
322         Directory* subdirectory = directory\->open_subdirectory(directory_name);
323         if (!subdirectory)
324             return nullptr;
325 
326         // Set the new directory
327         directory = subdirectory;
328 
329         // Get the path to the next directory
330         directory_path = directory_path\&.substring(directory_name\&.length() + 1, directory_path\&.length() \- directory_name\&.length() \- 1);
331     }
332 
333     return directory;
334 }
.fi

.PP
References \fBMaxOS::filesystem::Directory::open_subdirectory()\fP, \fBroot_directory()\fP, and \fBMaxOS::filesystem::Path::top_directory()\fP\&.
.PP
Referenced by \fBexists()\fP\&.
.SS "\fBDirectory\fP * FileSystem::root_directory ()"

.PP
Get the directory at '/'\&. 
.PP
\fBReturns\fP
.RS 4
The root directory of the filesystem 
.RE
.PP

.PP
Definition at line \fB297\fP of file \fBfilesystem\&.cpp\fP\&..PP
.nf
297                                       {
298     return m_root_directory;
299 }
.fi

.PP
References \fBm_root_directory\fP\&.
.PP
Referenced by \fBget_directory()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDirectory\fP* MaxOS::filesystem::FileSystem::m_root_directory = nullptr\fC [protected]\fP"

.PP
The fist directory in the file system (not be confused with the system root) 
.PP
Definition at line \fB98\fP of file \fBfilesystem\&.h\fP\&.
.PP
Referenced by \fBMaxOS::filesystem::format::ext2::Ext2FileSystem::Ext2FileSystem()\fP, \fBMaxOS::filesystem::format::Fat32FileSystem::Fat32FileSystem()\fP, \fBroot_directory()\fP, \fBMaxOS::filesystem::format::ext2::Ext2FileSystem::~Ext2FileSystem()\fP, and \fB~FileSystem()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
