.TH "MaxOS::net::DataReceivedEvent" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::DataReceivedEvent \- Event for when data is received on a TCP socket\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< TCPPayloadHandlerEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataReceivedEvent\fP (\fBTCPSocket\fP *\fBsocket\fP, \fBuint8_t\fP *\fBdata\fP, \fBuint16_t\fP \fBsize\fP)"
.br
.RI "___ EVENTS ___ /// "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::Event< TCPPayloadHandlerEvents >\fP
.in +1c
.ti -1c
.RI "\fBEvent\fP (TCPPayloadHandlerEvents \fBtype\fP)"
.br
.RI "___________________________ Template Implementation ___________________________ "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTCPSocket\fP * \fBsocket\fP"
.br
.RI "The socket that received the data\&. "
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.RI "The data received\&. "
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.RI "The size of the data received\&. "
.in -1c

Public Attributes inherited from \fBMaxOS::common::Event< TCPPayloadHandlerEvents >\fP
.in +1c
.ti -1c
.RI "TCPPayloadHandlerEvents \fBtype\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbufferValue\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBintValue\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBboolValue\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBuint8_t\fP * \fBbufferValue\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBintValue\fP"
.br
.ti -1c
.RI "   \fBbool\fP \fBboolValue\fP"
.br
.ti -1c
.RI "} \fBreturn_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event for when data is received on a TCP socket\&. 
.PP
Definition at line \fB113\fP of file \fBtcp\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataReceivedEvent::DataReceivedEvent (\fBTCPSocket\fP * socket, \fBuint8_t\fP * data, \fBuint16_t\fP size)"

.PP
___ EVENTS ___ /// 
.PP
Definition at line \fB553\fP of file \fBtcp\&.cpp\fP\&..PP
.nf
554         : Event(TCPPayloadHandlerEvents::DATA_RECEIVED) {
555     this\->socket = socket;
556     this\->data = data;
557     this\->size = size;
558 }
.fi

.PP
References \fBdata\fP, \fBsize\fP, and \fBsocket\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t* MaxOS::net::DataReceivedEvent::data"

.PP
The data received\&. 
.PP
Definition at line \fB116\fP of file \fBtcp\&.h\fP\&.
.PP
Referenced by \fBDataReceivedEvent()\fP\&.
.SS "uint16_t MaxOS::net::DataReceivedEvent::size"

.PP
The size of the data received\&. 
.PP
Definition at line \fB117\fP of file \fBtcp\&.h\fP\&.
.PP
Referenced by \fBDataReceivedEvent()\fP\&.
.SS "\fBTCPSocket\fP* MaxOS::net::DataReceivedEvent::socket"

.PP
The socket that received the data\&. 
.PP
Definition at line \fB115\fP of file \fBtcp\&.h\fP\&.
.PP
Referenced by \fBDataReceivedEvent()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
