.TH "MaxOS::common::Pair< First, Second >" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::common::Pair< First, Second > \- A pair of two objects\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <pair\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPair\fP ()"
.br
.RI "_____________________________Implementation___________________________________________/// "
.ti -1c
.RI "\fBPair\fP (\fBFirst\fP, \fBSecond\fP)"
.br
.RI "Creates a new pair\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFirst\fP \fBfirst\fP"
.br
.RI "The first object (often the key) "
.ti -1c
.RI "\fBSecond\fP \fBsecond\fP"
.br
.RI "The second object (often the value) "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBclass\fP \fBFirst\fP, \fBclass\fP \fBSecond\fP>
.br
class MaxOS::common::Pair< First, Second >"A pair of two objects\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIFirst\fP The type of the first object 
.br
\fISecond\fP The type of the second object 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBpair\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBFirst\fP , \fBclass\fP \fBSecond\fP > \fBMaxOS::common::Pair\fP< \fBFirst\fP, \fBSecond\fP >::Pair (\fBFirst\fP first, \fBSecond\fP second)"

.PP
Creates a new pair\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIFirst\fP The type of the first object 
.br
\fISecond\fP The type of the second object 
.RE
.PP
\fBParameters\fP
.RS 4
\fIfirst\fP The first object 
.br
\fIsecond\fP The second object 
.RE
.PP

.PP
Definition at line \fB44\fP of file \fBpair\&.h\fP\&..PP
.nf
45             : first(first),
46             second(second) {
47 
48     }
.fi

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBFirst\fP , \fBclass\fP \fBSecond\fP > \fBFirst\fP \fBMaxOS::common::Pair\fP< \fBFirst\fP, \fBSecond\fP >::first"

.PP
The first object (often the key) 
.PP
Definition at line \fB25\fP of file \fBpair\&.h\fP\&.
.SS "template<\fBclass\fP \fBFirst\fP , \fBclass\fP \fBSecond\fP > \fBSecond\fP \fBMaxOS::common::Pair\fP< \fBFirst\fP, \fBSecond\fP >::second"

.PP
The second object (often the value) 
.PP
Definition at line \fB26\fP of file \fBpair\&.h\fP\&.
.PP
Referenced by \fBMaxOS::common::Map< Key, Value >::insert()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
