.TH "maxOS::common::Colour" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::common::Colour \- Stores the red, green, blue and alpha values of a colour\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <colour\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColour\fP ()"
.br
.ti -1c
.RI "\fBColour\fP (uint8_t \fBred\fP, uint8_t \fBgreen\fP, uint8_t \fBblue\fP)"
.br
.ti -1c
.RI "\fBColour\fP (uint8_t \fBred\fP, uint8_t \fBgreen\fP, uint8_t \fBblue\fP, uint8_t \fBalpha\fP)"
.br
.ti -1c
.RI "\fB~Colour\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBred\fP { 0 }"
.br
.ti -1c
.RI "uint8_t \fBgreen\fP { 0 }"
.br
.ti -1c
.RI "uint8_t \fBblue\fP { 0 }"
.br
.ti -1c
.RI "uint8_t \fBalpha\fP { 0 }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores the red, green, blue and alpha values of a colour\&. 
.PP
Definition at line 19 of file colour\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Colour::Colour ()"

.PP
Definition at line 9 of file colour\&.cpp\&.
.PP
.nf
9                {
10 
11 }
.fi
.SS "Colour::Colour (uint8_t red, uint8_t green, uint8_t blue)"

.PP
Definition at line 13 of file colour\&.cpp\&.
.PP
.nf
14 : red(red),
15   green(green),
16   blue(blue)
17 {
18 
19 }
.fi
.SS "Colour::Colour (uint8_t red, uint8_t green, uint8_t blue, uint8_t alpha)"

.PP
Definition at line 21 of file colour\&.cpp\&.
.PP
.nf
22 : red(red),
23   green(green),
24   blue(blue),
25   alpha(alpha)
26 {
27 
28 }
.fi
.SS "Colour::~Colour ()"

.PP
Definition at line 30 of file colour\&.cpp\&.
.PP
.nf
30                 {
31 
32 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "uint8_t maxOS::common::Colour::alpha { 0 }"

.PP
Definition at line 25 of file colour\&.h\&.
.PP
Referenced by maxOS::common::GraphicsContext::colour_to_int(), and maxOS::common::GraphicsContext::int_to_colour()\&.
.SS "uint8_t maxOS::common::Colour::blue { 0 }"

.PP
Definition at line 24 of file colour\&.h\&.
.PP
Referenced by maxOS::common::GraphicsContext::colour_to_int(), maxOS::common::GraphicsContext::int_to_colour(), and maxOS::common::GraphicsContext::invert_pixel()\&.
.SS "uint8_t maxOS::common::Colour::green { 0 }"

.PP
Definition at line 23 of file colour\&.h\&.
.PP
Referenced by maxOS::common::GraphicsContext::colour_to_int(), maxOS::common::GraphicsContext::int_to_colour(), and maxOS::common::GraphicsContext::invert_pixel()\&.
.SS "uint8_t maxOS::common::Colour::red { 0 }"

.PP
Definition at line 22 of file colour\&.h\&.
.PP
Referenced by maxOS::common::GraphicsContext::colour_to_int(), maxOS::common::GraphicsContext::int_to_colour(), and maxOS::common::GraphicsContext::invert_pixel()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
