.TH "MaxOS::filesystem::format::ext2::BlockGroupDescriptor" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::format::ext2::BlockGroupDescriptor \- The metadata for a block group in ext2\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ext2\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBblock_usage_bitmap\fP"
.br
.RI "The block address of the block usage bitmap\&. "
.ti -1c
.RI "uint32_t \fBblock_inode_bitmap\fP"
.br
.RI "The block address of the inode usage bitmap\&. "
.ti -1c
.RI "uint32_t \fBinode_table_address\fP"
.br
.RI "The starting block address of the inode table\&. "
.ti -1c
.RI "uint16_t \fBfree_blocks\fP"
.br
.RI "How many free blocks are in this block group\&. "
.ti -1c
.RI "uint16_t \fBfree_inodes\fP"
.br
.RI "How many free inodes are in this block group\&. "
.ti -1c
.RI "uint16_t \fBdirectory_count\fP"
.br
.RI "How many directories are in this block group\&. "
.ti -1c
.RI "uint8_t \fBfree\fP [14]"
.br
.RI "Reserved for future expansion\&. "
.in -1c
.SH "Detailed Description"
.PP 
The metadata for a block group in ext2\&. 
.PP
Definition at line \fB155\fP of file \fBext2\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t MaxOS::filesystem::format::ext2::BlockGroupDescriptor::block_inode_bitmap"

.PP
The block address of the inode usage bitmap\&. 
.PP
Definition at line \fB157\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::BlockGroupDescriptor::block_usage_bitmap"

.PP
The block address of the block usage bitmap\&. 
.PP
Definition at line \fB156\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::BlockGroupDescriptor::directory_count"

.PP
How many directories are in this block group\&. 
.PP
Definition at line \fB161\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::BlockGroupDescriptor::free[14]"

.PP
Reserved for future expansion\&. 
.PP
Definition at line \fB162\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::BlockGroupDescriptor::free_blocks"

.PP
How many free blocks are in this block group\&. 
.PP
Definition at line \fB159\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::BlockGroupDescriptor::free_inodes"

.PP
How many free inodes are in this block group\&. 
.PP
Definition at line \fB160\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::BlockGroupDescriptor::inode_table_address"

.PP
The starting block address of the inode table\&. 
.PP
Definition at line \fB158\fP of file \fBext2\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
