.TH "MaxOS::drivers::disk::Disk" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::disk::Disk \- Generic \fBDisk\fP, handles the reading and writing of data to the hard drive\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <disk\&.h>\fP
.PP
Inherits \fBMaxOS::drivers::Driver\fP\&.
.PP
Inherited by \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBread\fP (\fBuint32_t\fP \fBsector\fP, \fBcommon::buffer_t\fP *\fBdata_buffer\fP)"
.br
.RI "read data from the disk into a buffer (max capacity 512 bytes) "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBread\fP (\fBuint32_t\fP \fBsector\fP, \fBcommon::buffer_t\fP *\fBdata_buffer\fP, \fBsize_t\fP \fBamount\fP)"
.br
.RI "read data from the disk "
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBuint32_t\fP \fBsector\fP, \fBcommon::buffer_t\fP *data)"
.br
.RI "write data to the disk from a buffer (max capacity 512 bytes) "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBwrite\fP (\fBuint32_t\fP \fBsector\fP, \fBcommon::buffer_t\fP *data, \fBsize_t\fP \fBcount\fP)"
.br
.RI "write data to the disk "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBflush\fP ()"
.br
.RI "Flush the disk cache\&. "
.ti -1c
.RI "\fBvoid\fP \fBactivate\fP () \fBoverride\fP"
.br
.RI "Activate the disk driver\&. "
.ti -1c
.RI "\fBstring\fP \fBdevice_name\fP () \fBoverride\fP"
.br
.RI "Get the device name\&. "
.ti -1c
.RI "\fBstring\fP \fBvendor_name\fP () \fBoverride\fP"
.br
.RI "Get the vendor name\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::Driver\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdeactivate\fP ()"
.br
.RI "Deactivate the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBinitialise\fP ()"
.br
.RI "Initialise the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBuint32_t\fP \fBreset\fP ()"
.br
.RI "Reset the driver\&. "
.in -1c
.SH "Detailed Description"
.PP 
Generic \fBDisk\fP, handles the reading and writing of data to the hard drive\&. 
.PP
Definition at line \fB24\fP of file \fBdisk\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Disk::activate ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Activate the disk driver\&. 
.PP
Reimplemented from \fBMaxOS::drivers::Driver\fP\&.
.PP
Definition at line \fB78\fP of file \fBdisk\&.cpp\fP\&..PP
.nf
78                     {
79     Driver::activate();
80 }
.fi

.PP
References \fBMaxOS::drivers::Driver::activate()\fP\&.
.SS "\fBstring\fP Disk::device_name ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Get the device name\&. 
.PP
\fBReturns\fP
.RS 4
The name of the device 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::Driver\fP\&.
.PP
Definition at line \fB87\fP of file \fBdisk\&.cpp\fP\&..PP
.nf
87                          {
88     return "Disk";
89 }
.fi

.SS "\fBvoid\fP Disk::flush ()\fC [virtual]\fP"

.PP
Flush the disk cache\&. This function is used to flush the disk cache to ensure that all data is written to the disk\&. 
.PP
Reimplemented in \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment\fP\&.
.PP
Definition at line \fB72\fP of file \fBdisk\&.cpp\fP\&..PP
.nf
72                  {
73 }
.fi

.SS "\fBvoid\fP Disk::read (\fBuint32_t\fP sector, \fBcommon::buffer_t\fP * data_buffer)"

.PP
read data from the disk into a buffer (max capacity 512 bytes) 
.PP
\fBParameters\fP
.RS 4
\fIsector\fP The sector to read from 
.br
\fIdata_buffer\fP The buffer to read the data into 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBdisk\&.cpp\fP\&..PP
.nf
26                                                             {
27 
28     size_t amount = (data_buffer\->capacity() > 512) ? 512 : data_buffer\->capacity();
29     read(sector, data_buffer, amount);
30 
31 }
.fi

.PP
References \fBread()\fP\&.
.PP
Referenced by \fBMaxOS::filesystem::format::Fat32Volume::Fat32Volume()\fP, \fBMaxOS::filesystem::partition::MSDOSPartition::mount_partitions()\fP, \fBMaxOS::filesystem::format::Fat32Volume::next_cluster()\fP, \fBMaxOS::filesystem::format::Fat32File::read()\fP, \fBread()\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::read_block()\fP, \fBMaxOS::filesystem::format::Fat32Volume::set_next_cluster()\fP, \fBMaxOS::filesystem::format::Fat32Directory::update_entry_on_disk()\fP, and \fBMaxOS::filesystem::format::Fat32File::write()\fP\&.
.SS "\fBvoid\fP Disk::read (\fBuint32_t\fP sector, \fBcommon::buffer_t\fP * data_buffer, \fBsize_t\fP amount)\fC [virtual]\fP"

.PP
read data from the disk 
.PP
\fBParameters\fP
.RS 4
\fIsector\fP The sector to read from 
.br
\fIdata_buffer\fP The buffer to read the data into 
.br
\fIamount\fP The amount of data to read 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment\fP\&.
.PP
Definition at line \fB40\fP of file \fBdisk\&.cpp\fP\&..PP
.nf
40                                                                      {
41 
42 }
.fi

.SS "\fBstring\fP Disk::vendor_name ()\fC [override]\fP, \fC [virtual]\fP"

.PP
Get the vendor name\&. 
.PP
\fBReturns\fP
.RS 4
The name of the vendor 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::Driver\fP\&.
.PP
Definition at line \fB96\fP of file \fBdisk\&.cpp\fP\&..PP
.nf
96                          {
97     return "Generic";
98 }
.fi

.SS "\fBvoid\fP Disk::write (\fBuint32_t\fP sector, \fBcommon::buffer_t\fP * data)"

.PP
write data to the disk from a buffer (max capacity 512 bytes) 
.PP
\fBParameters\fP
.RS 4
\fIsector\fP The sector to write to 
.br
\fIdata\fP The buffer to write the data from 
.RE
.PP

.PP
Definition at line \fB50\fP of file \fBdisk\&.cpp\fP\&..PP
.nf
50                                                       {
51 
52     size_t amount = (data\->capacity() > 512) ? 512 : data\->capacity();
53     write(sector, data, amount);
54 
55 }
.fi

.PP
References \fBMaxOS::common::Buffer::capacity()\fP, and \fBwrite()\fP\&.
.PP
Referenced by \fBMaxOS::filesystem::format::Fat32Volume::allocate_cluster()\fP, \fBMaxOS::filesystem::format::Fat32Volume::free_cluster()\fP, \fBMaxOS::filesystem::format::Fat32Volume::set_next_cluster()\fP, \fBMaxOS::filesystem::format::Fat32Directory::update_entry_on_disk()\fP, \fBMaxOS::filesystem::format::Fat32File::write()\fP, \fBwrite()\fP, and \fBMaxOS::filesystem::format::ext2::Ext2Volume::write_block()\fP\&.
.SS "\fBvoid\fP Disk::write (\fBuint32_t\fP sector, \fBcommon::buffer_t\fP * data, \fBsize_t\fP count)\fC [virtual]\fP"

.PP
write data to the disk 
.PP
\fBParameters\fP
.RS 4
\fIsector\fP The sector to write to 
.br
\fIdata\fP The buffer to write the data into 
.br
\fIcount\fP The amount of data to write 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment\fP\&.
.PP
Definition at line \fB64\fP of file \fBdisk\&.cpp\fP\&..PP
.nf
64                                                               {
65 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
