.TH "MaxOS::drivers::console::ConsoleStream" 3 "Mon Jan 15 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::console::ConsoleStream \- A stream that can be used to write to a console\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <console\&.h>\fP
.PP
Inherits \fBMaxOS::common::OutputStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConsoleStream\fP (\fBConsole\fP *)"
.br
.RI "____ \fBConsole\fP Stream ____/// "
.ti -1c
.RI "\fB~ConsoleStream\fP ()"
.br
.ti -1c
.RI "void \fBwrite_char\fP (char c) override"
.br
.RI "write a character to the console stream "
.ti -1c
.RI "void \fBset_cursor\fP (uint16_t x, uint16_t y)"
.br
.RI "Set the m_position of the cursor\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBm_cursor_x\fP { 0 }"
.br
.ti -1c
.RI "uint16_t \fBm_cursor_y\fP { 0 }"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBConsole\fP * \fBm_console\fP"
.br
.ti -1c
.RI "\fBConsoleColour\fP \fBm_foreground\fP"
.br
.ti -1c
.RI "\fBConsoleColour\fP \fBm_background\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A stream that can be used to write to a console\&. 
.PP
Definition at line 106 of file console\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConsoleStream::ConsoleStream (\fBConsole\fP * console)"

.PP
____ \fBConsole\fP Stream ____/// 
.PP
Definition at line 395 of file console\&.cpp\&.
.PP
.nf
396 : m_console(console)
397 {
398 
399 }
.fi
.SS "ConsoleStream::~ConsoleStream ()"

.PP
Definition at line 401 of file console\&.cpp\&.
.PP
.nf
401                               {
402 
403 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "void ConsoleStream::set_cursor (uint16_t x, uint16_t y)"

.PP
Set the m_position of the cursor\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The x coordinate of the cursor 
.br
\fIy\fP The y coordinate of the cursor 
.RE
.PP

.PP
Definition at line 480 of file console\&.cpp\&.
.PP
.nf
480                                                      {
481 
482     // Set the x and y coordinates
483     m_cursor_x = x;
484     m_cursor_y = y;
485 }
.fi
.PP
References m_cursor_x, m_cursor_y, MaxOS::drivers::peripherals::x, and MaxOS::drivers::peripherals::y\&.
.PP
Referenced by kernelMain()\&.
.SS "void ConsoleStream::write_char (char c)\fC [override]\fP, \fC [virtual]\fP"

.PP
write a character to the console stream 
.PP
\fBParameters\fP
.RS 4
\fIc\fP The character to write 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::common::OutputStream\fP\&.
.PP
Definition at line 410 of file console\&.cpp\&.
.PP
.nf
410                                      {
411 
412     // If the character placement is more than the width of the console go on a new line
413     if(m_cursor_x >= m_console->width()) {
414 
415         // Go to the start of the next line
416         m_cursor_x = 0;
417 
418         // Increment the y coordinate but if it is more than the height of the console scroll the console
419         if(++m_cursor_y >= m_console->height()){
420 
421             // Scroll the console
422             m_console->scroll_up();
423 
424             // Decrement the y coordinate
425             m_cursor_y = m_console->height()-1;
426         }
427     }
428 
429     // Handle the character
430     switch (c) {
431         // New line
432         case '\n':
433             // Increment the y coordinate but if it is more than the height of the console scroll the console
434             if(++m_cursor_y >= m_console->height()){
435 
436                 // Scroll the console
437                 m_console->scroll_up();
438 
439                 // Decrement the y coordinate
440                 m_cursor_y = m_console->height()-1;
441             }
442 
443             // don't break here, we want to go to the next case because of the \r
444             [[fallthrough]];
445 
446         // Carriage return
447         case '\r':
448             // Go to the start of the next line
449             m_cursor_x = 0;
450             break;
451 
452         // Null Terminator
453         case '\0':
454             break;
455 
456         // Backspace
457         case '\b':
458             // Decrement the x coordinate
459             m_cursor_x--;
460             break;
461 
462         default:
463             // Put the character on the console
464             m_console->put_character(m_cursor_x, m_cursor_y, c);
465 
466             // Increment the x coordinate
467             m_cursor_x++;
468             break;
469 
470     }
471 
472 }
.fi
.PP
References MaxOS::drivers::peripherals::c, MaxOS::drivers::console::Console::height(), m_console, m_cursor_x, m_cursor_y, MaxOS::drivers::console::Console::put_character(), MaxOS::drivers::console::Console::scroll_up(), and MaxOS::drivers::console::Console::width()\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBConsoleColour\fP MaxOS::drivers::console::ConsoleStream::m_background\fC [protected]\fP"

.PP
Definition at line 112 of file console\&.h\&.
.SS "\fBConsole\fP* MaxOS::drivers::console::ConsoleStream::m_console\fC [protected]\fP"

.PP
Definition at line 109 of file console\&.h\&.
.PP
Referenced by write_char()\&.
.SS "uint16_t MaxOS::drivers::console::ConsoleStream::m_cursor_x { 0 }"

.PP
Definition at line 115 of file console\&.h\&.
.PP
Referenced by kernelMain(), set_cursor(), and write_char()\&.
.SS "uint16_t MaxOS::drivers::console::ConsoleStream::m_cursor_y { 0 }"

.PP
Definition at line 116 of file console\&.h\&.
.PP
Referenced by kernelMain(), set_cursor(), and write_char()\&.
.SS "\fBConsoleColour\fP MaxOS::drivers::console::ConsoleStream::m_foreground\fC [protected]\fP"

.PP
Definition at line 111 of file console\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
