.TH "MaxOS::memory::MemoryChunk" 3 "Mon Jan 29 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::memory::MemoryChunk \- Stores information about a memory chunk in the memory manager linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memorymanagement\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMemoryChunk\fP * \fBnext\fP"
.br
.ti -1c
.RI "\fBMemoryChunk\fP * \fBprev\fP"
.br
.ti -1c
.RI "bool \fBallocated\fP"
.br
.ti -1c
.RI "size_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores information about a memory chunk in the memory manager linked list\&. 
.PP
Definition at line 20 of file memorymanagement\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "bool MaxOS::memory::MemoryChunk::allocated"

.PP
Definition at line 25 of file memorymanagement\&.h\&.
.PP
Referenced by MaxOS::memory::MemoryManager::malloc()\&.
.SS "\fBMemoryChunk\fP* MaxOS::memory::MemoryChunk::next"

.PP
Definition at line 22 of file memorymanagement\&.h\&.
.PP
Referenced by MaxOS::memory::MemoryManager::malloc(), and MaxOS::memory::MemoryManager::memory_used()\&.
.SS "\fBMemoryChunk\fP* MaxOS::memory::MemoryChunk::prev"

.PP
Definition at line 23 of file memorymanagement\&.h\&.
.PP
Referenced by MaxOS::memory::MemoryManager::free()\&.
.SS "size_t MaxOS::memory::MemoryChunk::size"

.PP
Definition at line 26 of file memorymanagement\&.h\&.
.PP
Referenced by MaxOS::memory::MemoryManager::free(), and MaxOS::memory::MemoryManager::malloc()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
