.TH "maxOS::common" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::common
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColour\fP"
.br
.RI "Stores the red, green, blue and alpha values of a colour\&. "
.ti -1c
.RI "class \fBEvent\fP"
.br
.RI "Used to store information about an event, has a type and a return value\&. "
.ti -1c
.RI "class \fBEventHandler\fP"
.br
.RI "Used to handle an event\&. "
.ti -1c
.RI "class \fBEventManager\fP"
.br
.RI "Manages the m_handlers for a type of event, raises events and calls the m_handlers\&. "
.ti -1c
.RI "class \fBGenericInputStream\fP"
.br
.RI "Manages the connection of a stream to handlers\&. "
.ti -1c
.RI "class \fBGenericOutputStream\fP"
.br
.RI "A stream that can be written to\&. "
.ti -1c
.RI "class \fBGraphicsContext\fP"
.br
.RI "Draws pixels to the screen, and handles drawing lines, rectangles and circles\&. "
.ti -1c
.RI "class \fBInputStream\fP"
.br
.RI "A stream that handles strings\&. "
.ti -1c
.RI "class \fBInputStreamBuffer\fP"
.br
.RI "Buffers data from a stream and fires an event when a certain element is read\&. "
.ti -1c
.RI "class \fBInputStreamEventHandler\fP"
.br
.RI "Handles read and end of stream events from a set of streams\&. "
.ti -1c
.RI "class \fBInputStreamProcessor\fP"
.br
.RI "Converts one stream data type into another\&. "
.ti -1c
.RI "class \fBInputStreamSocket\fP"
.br
.RI "Passes read events on to the handlers\&. "
.ti -1c
.RI "class \fBMap\fP"
.br
.RI "A list of key-value pairs\&. "
.ti -1c
.RI "class \fBMapIterationHandler\fP"
.br
.RI "Handles iteration of a map\&. "
.ti -1c
.RI "class \fBOutputStream\fP"
.br
.RI "A stream that strings can be written to\&. "
.ti -1c
.RI "class \fBPair\fP"
.br
.RI "A pair of two objects\&. "
.ti -1c
.RI "class \fBRectangle\fP"
.br
.RI "Stores the left, top, width and height of a rectangle\&. "
.ti -1c
.RI "struct \fBTime\fP"
.br
.RI "Stores the year, month, day, hour, minute and second of a time\&. "
.ti -1c
.RI "class \fBVector\fP"
.br
.RI "Dynamically stores an array of elements\&. "
.ti -1c
.RI "class \fBVectorIterationHandler\fP"
.br
.RI "Handles the iteration of a \fBVector\fP providing read and end of stream functions\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBPair\fP< int32_t, int32_t > \fBCoordinates\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<class Type > void \fBoperator>>\fP (\fBGenericInputStream\fP< Type > &source, \fBInputStreamEventHandler\fP< Type > &inputStreamEventHandler)"
.br
.ti -1c
.RI "template<class Type , class ProcessorType > \fBGenericInputStream\fP< ProcessorType > & \fBoperator>>\fP (\fBGenericInputStream\fP< Type > &source, \fBInputStreamProcessor\fP< Type, ProcessorType > &processor)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBPair\fP<int32_t, int32_t> \fBmaxOS::common::Coordinates\fP"

.PP
Definition at line 15 of file coordinates\&.h\&.
.SH "Function Documentation"
.PP 
.SS "template<class Type > void maxOS::common::operator>> (\fBGenericInputStream\fP< Type > & source, \fBInputStreamEventHandler\fP< Type > & inputStreamEventHandler)"

.SS "template<class Type , class ProcessorType > \fBGenericInputStream\fP<ProcessorType>& maxOS::common::operator>> (\fBGenericInputStream\fP< Type > & source, \fBInputStreamProcessor\fP< Type, ProcessorType > & processor)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
