.TH "MaxOS::drivers::clock::TimeEvent" 3 "Mon Jan 15 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::clock::TimeEvent \- Event that is triggered when the clock ticks, holds the current time\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clock\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< ClockEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTimeEvent\fP (\fBcommon::Time\fP *)"
.br
.ti -1c
.RI "\fB~TimeEvent\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcommon::Time\fP * \fBtime\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event that is triggered when the clock ticks, holds the current time\&. 
.PP
Definition at line 29 of file clock\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TimeEvent::TimeEvent (\fBcommon::Time\fP * time)"

.PP
Definition at line 196 of file clock\&.cpp\&.
.PP
.nf
197 :Event(ClockEvents::TIME),
198 time(time)
199 {
200 
201 }
.fi
.SS "TimeEvent::~TimeEvent ()"

.PP
Definition at line 203 of file clock\&.cpp\&.
.PP
.nf
203                       {
204 
205 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBcommon::Time\fP* MaxOS::drivers::clock::TimeEvent::time"

.PP
Definition at line 31 of file clock\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
