.TH "MaxOS::drivers::ethernet::BeforeSendEvent" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::ethernet::BeforeSendEvent \- Event that is triggered before data is sent, holds the buffer and size of the data\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethernet\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< EthernetDriverEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBeforeSendEvent\fP (uint8_t *\fBbuffer\fP, uint32_t \fBsize\fP)"
.br
.ti -1c
.RI "\fB~BeforeSendEvent\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t * \fBbuffer\fP"
.br
.ti -1c
.RI "uint32_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event that is triggered before data is sent, holds the buffer and size of the data\&. 
.PP
Definition at line 31 of file ethernet\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "BeforeSendEvent::BeforeSendEvent (uint8_t * buffer, uint32_t size)"

.PP
Definition at line 213 of file ethernet\&.cpp\&.
.PP
.nf
214 : Event(EthernetDriverEvents::BEFORE_SEND)
215 {
216     this -> buffer = buffer;
217     this -> size = size;
218 }
.fi
.PP
References buffer, and size\&.
.SS "BeforeSendEvent::~BeforeSendEvent ()"

.PP
Definition at line 220 of file ethernet\&.cpp\&.
.PP
.nf
221 {
222 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "uint8_t* MaxOS::drivers::ethernet::BeforeSendEvent::buffer"

.PP
Definition at line 33 of file ethernet\&.h\&.
.PP
Referenced by BeforeSendEvent()\&.
.SS "uint32_t MaxOS::drivers::ethernet::BeforeSendEvent::size"

.PP
Definition at line 34 of file ethernet\&.h\&.
.PP
Referenced by BeforeSendEvent()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
