.TH "MaxOS::filesystem::DirectoryResource" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::DirectoryResource
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vfsresource\&.h>\fP
.PP
Inherits \fBMaxOS::processes::Resource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDirectoryResource\fP (\fBconst\fP \fBstring\fP &\fBname\fP, \fBsize_t\fP \fBflags\fP, \fBprocesses::resource_type_t\fP \fBtype\fP)"
.br
.ti -1c
.RI "\fB~DirectoryResource\fP () final"
.br
.ti -1c
.RI "\fBint\fP \fBread\fP (\fBvoid\fP *buffer, \fBsize_t\fP \fBsize\fP, \fBsize_t\fP \fBflags\fP) \fBfinal\fP"
.br
.RI "Read from a directory resource\&. "
.ti -1c
.RI "\fBint\fP \fBwrite\fP (\fBconst\fP \fBvoid\fP *buffer, \fBsize_t\fP \fBsize\fP, \fBsize_t\fP \fBflags\fP) \fBfinal\fP"
.br
.RI "Write to a directory resource\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::processes::Resource\fP
.in +1c
.ti -1c
.RI "\fBResource\fP (const \fBstring\fP &\fBname\fP, size_t \fBflags\fP, \fBresource_type_t\fP \fBtype\fP)"
.br
.ti -1c
.RI "virtual \fB~Resource\fP ()"
.br
.ti -1c
.RI "\fBstring\fP \fBname\fP ()"
.br
.RI "Gets the name of this resource\&. "
.ti -1c
.RI "\fBresource_type_t\fP \fBtype\fP ()"
.br
.RI "Gets the type of this resource\&. "
.ti -1c
.RI "virtual void \fBopen\fP (size_t \fBflags\fP)"
.br
.RI "Opens the resource\&. "
.ti -1c
.RI "virtual void \fBclose\fP (size_t \fBflags\fP)"
.br
.RI "Closes the resource\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBDirectory\fP * \fBdirectory\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB32\fP of file \fBvfsresource\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DirectoryResource::DirectoryResource (\fBconst\fP \fBstring\fP & name, \fBsize_t\fP flags, \fBprocesses::resource_type_t\fP type)"

.PP
Definition at line \fB115\fP of file \fBvfsresource\&.cpp\fP\&..PP
.nf
116 : Resource(name, flags, type),
117   directory(nullptr)
118 {
119 
120 }
.fi

.SS "DirectoryResource::~DirectoryResource ()\fC [final]\fP, \fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBint\fP DirectoryResource::read (\fBvoid\fP * buffer, \fBsize_t\fP size, \fBsize_t\fP flags)\fC [final]\fP, \fC [virtual]\fP"

.PP
Read from a directory resource\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The buffer to read into 
.br
\fIsize\fP The number of bytes to read 
.br
\fIflags\fP The flags to pass to the reading 
.RE
.PP
\fBReturns\fP
.RS 4
The number of bytes successfully read or -1 on error 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::processes::Resource\fP\&.
.PP
Definition at line \fB211\fP of file \fBvfsresource\&.cpp\fP\&..PP
.nf
211                                                                    {
212 
213     // Directory not found
214     if(!directory)
215         return \-1;
216 
217     switch ((DirectoryFlags)flags){
218         case DirectoryFlags::READ_ENTRIES:{
219             write_entries(buffer, size);
220             break;
221         }
222 
223         case DirectoryFlags::READ_ENTRIES_SIZE:{
224             return entries_size();
225         }
226 
227         default:
228             return \-1;
229     }
230 
231     return size;
232 
233 }
.fi

.PP
References \fBdirectory\fP, \fBflags\fP, and \fBsize\fP\&.
.SS "\fBint\fP DirectoryResource::write (\fBconst\fP \fBvoid\fP * buffer, \fBsize_t\fP size, \fBsize_t\fP flags)\fC [final]\fP, \fC [virtual]\fP"

.PP
Write to a directory resource\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The buffer to write from 
.br
\fIsize\fP The number of bytes to write 
.br
\fIflags\fP The flags to pass to the writing 
.RE
.PP
\fBReturns\fP
.RS 4
The number of bytes successfully written or -1 on error 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::processes::Resource\fP\&.
.PP
Definition at line \fB243\fP of file \fBvfsresource\&.cpp\fP\&..PP
.nf
243                                                                           {
244 
245     // Directory not found
246     if(!directory)
247         return \-1;
248 
249     auto registry = GlobalResourceRegistry::get_registry(resource_type_t::FILESYSTEM);
250 
251     switch ((DirectoryFlags)flags){
252 
253         case DirectoryFlags::WRITE_NAME : {
254 
255             // Open the parent
256             Resource* parent = registry\->get_resource(Path::parent_directory(name()));
257             auto parent_directory = ((DirectoryResource*)parent)\->directory;
258 
259             // Rename
260             string new_name = string((uint8_t*)buffer, size);
261             parent_directory\->rename_subdirectory(directory, new_name);
262             break;
263         }
264 
265         case DirectoryFlags::WRITE_NEW_FILE:{
266 
267             string new_name = string((uint8_t*)buffer, size);
268             directory\->create_file(new_name);
269             break;
270         }
271 
272 
273         case DirectoryFlags::WRITE_NEW_DIR:{
274 
275             string new_name = string((uint8_t*)buffer, size);
276             directory\->create_subdirectory(new_name);
277             break;
278         }
279 
280         case DirectoryFlags::WRITE_REMOVE_FILE:{
281 
282             string new_name = string((uint8_t*)buffer, size);
283             directory\->remove_file(new_name);
284             break;
285         }
286         case DirectoryFlags::WRITE_REMOVE_DIR:{
287 
288             string new_name = string((uint8_t*)buffer, size);
289             directory\->remove_subdirectory(new_name);
290             break;
291         }
292 
293         default:
294             return \-1;
295     }
296 
297     return size;
298 }
.fi

.PP
References \fBMaxOS::filesystem::Directory::create_file()\fP, \fBMaxOS::filesystem::Directory::create_subdirectory()\fP, \fBdirectory\fP, \fBflags\fP, \fBMaxOS::processes::GlobalResourceRegistry::get_registry()\fP, \fBMaxOS::processes::Resource::name()\fP, \fBMaxOS::filesystem::Path::parent_directory()\fP, \fBMaxOS::filesystem::Directory::remove_file()\fP, \fBMaxOS::filesystem::Directory::remove_subdirectory()\fP, and \fBsize\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBDirectory\fP* MaxOS::filesystem::DirectoryResource::directory"

.PP
Definition at line \fB44\fP of file \fBvfsresource\&.h\fP\&.
.PP
Referenced by \fBread()\fP, and \fBwrite()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
