.TH "MaxOS::system" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP"
.br
.RI "Style Guide Note: \fBCPU\fP abbreviation is preferred over Central Processing Unit\&. "
.ti -1c
.RI "class \fBCPU\fP"
.br
.ti -1c
.RI "class \fBGlobalDescriptorTable\fP"
.br
.RI "Sets up the GDT in the \fBCPU\fP\&. "
.ti -1c
.RI "struct \fBGlobalDescriptorTableRegister\fP"
.br
.RI "How the \fBCPU\fP stores the GDT\&. "
.ti -1c
.RI "class \fBMultiboot\fP"
.br
.ti -1c
.RI "struct \fBStackFrame\fP"
.br
.ti -1c
.RI "struct \fBSyscallArguments\fP"
.br
.ti -1c
.RI "class \fBSyscallManager\fP"
.br
.RI "Provides an API for userspace applications to interact with the kernel\&. "
.ti -1c
.RI "struct \fBtss\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBMaxOS::system::SyscallArguments\fP \fBsyscall_args_t\fP"
.br
.ti -1c
.RI "typedef \fBsyscall_args_t\fP *(* \fBsyscall_func_t\fP) (\fBsyscall_args_t\fP *args)"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBCPU_FEATURE_ECX\fP : int32_t { \fBSSE3\fP = 1 << 0, \fBPCLMUL\fP = 1 << 1, \fBDTES64\fP = 1 << 2, \fBMONITOR\fP = 1 << 3, \fBDS_CPL\fP = 1 << 4, \fBVMX\fP = 1 << 5, \fBSMX\fP = 1 << 6, \fBEST\fP = 1 << 7, \fBTM2\fP = 1 << 8, \fBSSSE3\fP = 1 << 9, \fBCID\fP = 1 << 10, \fBSDBG\fP = 1 << 11, \fBFMA\fP = 1 << 12, \fBCX16\fP = 1 << 13, \fBXTPR\fP = 1 << 14, \fBPDCM\fP = 1 << 15, \fBPCID\fP = 1 << 17, \fBDCA\fP = 1 << 18, \fBSSE4_1\fP = 1 << 19, \fBSSE4_2\fP = 1 << 20, \fBX2APIC\fP = 1 << 21, \fBMOVBE\fP = 1 << 22, \fBPOPCNT\fP = 1 << 23, \fBTSC\fP = 1 << 24, \fBAES\fP = 1 << 25, \fBXSAVE\fP = 1 << 26, \fBOSXSAVE\fP = 1 << 27, \fBAVX\fP = 1 << 28, \fBF16C\fP = 1 << 29, \fBRDRAND\fP = 1 << 30, \fBHYPERVISOR\fP = 1 << 31 }"
.br
.ti -1c
.RI "enum class \fBCPU_FEATURE_EDX\fP : int32_t { \fBFPU\fP = 1 << 0, \fBVME\fP = 1 << 1, \fBDE\fP = 1 << 2, \fBPSE\fP = 1 << 3, \fBTSC\fP = 1 << 4, \fBMSR\fP = 1 << 5, \fBPAE\fP = 1 << 6, \fBMCE\fP = 1 << 7, \fBCX8\fP = 1 << 8, \fBAPIC\fP = 1 << 9, \fBSEP\fP = 1 << 11, \fBMTRR\fP = 1 << 12, \fBPGE\fP = 1 << 13, \fBMCA\fP = 1 << 14, \fBCMOV\fP = 1 << 15, \fBPAT\fP = 1 << 16, \fBPSE36\fP = 1 << 17, \fBPSN\fP = 1 << 18, \fBCLFLUSH\fP = 1 << 19, \fBDS\fP = 1 << 21, \fBACPI\fP = 1 << 22, \fBMMX\fP = 1 << 23, \fBFXSR\fP = 1 << 24, \fBSSE\fP = 1 << 25, \fBSSE2\fP = 1 << 26, \fBSS\fP = 1 << 27, \fBHTT\fP = 1 << 28, \fBTM\fP = 1 << 29, \fBIA64\fP = 1 << 30, \fBPBE\fP = 1 << 31 }"
.br
.ti -1c
.RI "enum class \fBDescriptorFlags\fP : uint64_t { \fBWrite\fP = (1ULL << 41), \fBExecute\fP = (1ULL << 43), \fBCodeOrDataSegment\fP = (1ULL << 44), \fBGrowDown\fP = (1ULL << 45), \fBConformFromLower\fP = (1ULL << 46), \fBPresent\fP = (1ULL << 47), \fBLongMode\fP = (1ULL << 53) }"
.br
.RI "Flags for the GDT entries\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::system::tss\fP \fB__attribute__\fP ((__packed__)) tss_t"
.br
.ti -1c
.RI "struct \fBMaxOS::system::GlobalDescriptorTableRegister\fP \fB__attribute__\fP ((packed)) gdtr_t"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "enum \fBMaxOS::system::CPU_FEATURE_ECX\fP \fB__attribute__\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBMaxOS::system::SyscallArguments\fP \fBMaxOS::system::syscall_args_t\fP"

.SS "typedef \fBsyscall_args_t\fP *(* MaxOS::system::syscall_func_t) (\fBsyscall_args_t\fP *args)"

.PP
Definition at line \fB36\fP of file \fBsyscalls\&.h\fP\&.
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBMaxOS::system::CPU_FEATURE_ECX\fP : int32_t\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISSE3 \fP\fP
.TP
\fB\fIPCLMUL \fP\fP
.TP
\fB\fIDTES64 \fP\fP
.TP
\fB\fIMONITOR \fP\fP
.TP
\fB\fIDS_CPL \fP\fP
.TP
\fB\fIVMX \fP\fP
.TP
\fB\fISMX \fP\fP
.TP
\fB\fIEST \fP\fP
.TP
\fB\fITM2 \fP\fP
.TP
\fB\fISSSE3 \fP\fP
.TP
\fB\fICID \fP\fP
.TP
\fB\fISDBG \fP\fP
.TP
\fB\fIFMA \fP\fP
.TP
\fB\fICX16 \fP\fP
.TP
\fB\fIXTPR \fP\fP
.TP
\fB\fIPDCM \fP\fP
.TP
\fB\fIPCID \fP\fP
.TP
\fB\fIDCA \fP\fP
.TP
\fB\fISSE4_1 \fP\fP
.TP
\fB\fISSE4_2 \fP\fP
.TP
\fB\fIX2APIC \fP\fP
.TP
\fB\fIMOVBE \fP\fP
.TP
\fB\fIPOPCNT \fP\fP
.TP
\fB\fITSC \fP\fP
.TP
\fB\fIAES \fP\fP
.TP
\fB\fIXSAVE \fP\fP
.TP
\fB\fIOSXSAVE \fP\fP
.TP
\fB\fIAVX \fP\fP
.TP
\fB\fIF16C \fP\fP
.TP
\fB\fIRDRAND \fP\fP
.TP
\fB\fIHYPERVISOR \fP\fP
.PP
Definition at line \fB69\fP of file \fBcpu\&.h\fP\&..PP
.nf
69                                : int32_t {
70         SSE3         = 1 << 0,
71         PCLMUL       = 1 << 1,
72         DTES64       = 1 << 2,
73         MONITOR      = 1 << 3,
74         DS_CPL       = 1 << 4,
75         VMX          = 1 << 5,
76         SMX          = 1 << 6,
77         EST          = 1 << 7,
78         TM2          = 1 << 8,
79         SSSE3        = 1 << 9,
80         CID          = 1 << 10,
81         SDBG         = 1 << 11,
82         FMA          = 1 << 12,
83         CX16         = 1 << 13,
84         XTPR         = 1 << 14,
85         PDCM         = 1 << 15,
86         PCID         = 1 << 17,
87         DCA          = 1 << 18,
88         SSE4_1       = 1 << 19,
89         SSE4_2       = 1 << 20,
90         X2APIC       = 1 << 21,
91         MOVBE        = 1 << 22,
92         POPCNT       = 1 << 23,
93         TSC          = 1 << 24,
94         AES          = 1 << 25,
95         XSAVE        = 1 << 26,
96         OSXSAVE      = 1 << 27,
97         AVX          = 1 << 28,
98         F16C         = 1 << 29,
99         RDRAND       = 1 << 30,
100         HYPERVISOR   = 1 << 31,
101     };
.fi

.SS "enum class \fBMaxOS::system::CPU_FEATURE_EDX\fP : int32_t\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFPU \fP\fP
.TP
\fB\fIVME \fP\fP
.TP
\fB\fIDE \fP\fP
.TP
\fB\fIPSE \fP\fP
.TP
\fB\fITSC \fP\fP
.TP
\fB\fIMSR \fP\fP
.TP
\fB\fIPAE \fP\fP
.TP
\fB\fIMCE \fP\fP
.TP
\fB\fICX8 \fP\fP
.TP
\fB\fIAPIC \fP\fP
.TP
\fB\fISEP \fP\fP
.TP
\fB\fIMTRR \fP\fP
.TP
\fB\fIPGE \fP\fP
.TP
\fB\fIMCA \fP\fP
.TP
\fB\fICMOV \fP\fP
.TP
\fB\fIPAT \fP\fP
.TP
\fB\fIPSE36 \fP\fP
.TP
\fB\fIPSN \fP\fP
.TP
\fB\fICLFLUSH \fP\fP
.TP
\fB\fIDS \fP\fP
.TP
\fB\fIACPI \fP\fP
.TP
\fB\fIMMX \fP\fP
.TP
\fB\fIFXSR \fP\fP
.TP
\fB\fISSE \fP\fP
.TP
\fB\fISSE2 \fP\fP
.TP
\fB\fISS \fP\fP
.TP
\fB\fIHTT \fP\fP
.TP
\fB\fITM \fP\fP
.TP
\fB\fIIA64 \fP\fP
.TP
\fB\fIPBE \fP\fP
.PP
Definition at line \fB103\fP of file \fBcpu\&.h\fP\&..PP
.nf
103                                : int32_t {
104         FPU          = 1 << 0,
105         VME          = 1 << 1,
106         DE           = 1 << 2,
107         PSE          = 1 << 3,
108         TSC          = 1 << 4,
109         MSR          = 1 << 5,
110         PAE          = 1 << 6,
111         MCE          = 1 << 7,
112         CX8          = 1 << 8,
113         APIC         = 1 << 9,
114         SEP          = 1 << 11,
115         MTRR         = 1 << 12,
116         PGE          = 1 << 13,
117         MCA          = 1 << 14,
118         CMOV         = 1 << 15,
119         PAT          = 1 << 16,
120         PSE36        = 1 << 17,
121         PSN          = 1 << 18,
122         CLFLUSH      = 1 << 19,
123         DS           = 1 << 21,
124         ACPI         = 1 << 22,
125         MMX          = 1 << 23,
126         FXSR         = 1 << 24,
127         SSE          = 1 << 25,
128         SSE2         = 1 << 26,
129         SS           = 1 << 27,
130         HTT          = 1 << 28,
131         TM           = 1 << 29,
132         IA64         = 1 << 30,
133         PBE          = 1 << 31
134     };
.fi

.SS "enum class \fBMaxOS::system::DescriptorFlags\fP : uint64_t\fC [strong]\fP"

.PP
Flags for the GDT entries\&. DescriptorFlags 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIWrite \fP\fP
.TP
\fB\fIExecute \fP\fP
.TP
\fB\fICodeOrDataSegment \fP\fP
.TP
\fB\fIGrowDown \fP\fP
.TP
\fB\fIConformFromLower \fP\fP
.TP
\fB\fIPresent \fP\fP
.TP
\fB\fILongMode \fP\fP
.PP
Definition at line \fB19\fP of file \fBgdt\&.h\fP\&..PP
.nf
19                                     : uint64_t {
20              Write               = (1ULL << 41),
21              Execute             = (1ULL << 43),
22              CodeOrDataSegment   = (1ULL << 44),
23              GrowDown            = (1ULL << 45),
24              ConformFromLower    = (1ULL << 46),
25              Present             = (1ULL << 47),
26              LongMode            = (1ULL << 53),
27          };
.fi

.SH "Function Documentation"
.PP 
.SS "struct \fBMaxOS::system::tss\fP \fBMaxOS::system::__attribute__\fP ((__packed__))"

.SS "struct \fBMaxOS::system::GlobalDescriptorTableRegister\fP \fBMaxOS::system::__attribute__\fP ((packed))"

.SH "Variable Documentation"
.PP 
.SS "class \fBMaxOS::system::GlobalDescriptorTable\fP \fBMaxOS::system::__attribute__\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
