.TH "MaxOS::hardwarecommunication::RedirectionEntry" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::RedirectionEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <apic\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "struct {"
.br
.ti -1c
.RI "   uint64_t \fBvector\fP: 8"
.br
.ti -1c
.RI "   uint64_t \fBdelivery_mode\fP: 3"
.br
.ti -1c
.RI "   uint64_t \fBdestination_mode\fP: 1"
.br
.ti -1c
.RI "   uint64_t \fBdelivery_status\fP: 1"
.br
.ti -1c
.RI "   uint64_t \fBpin_polarity\fP: 1"
.br
.ti -1c
.RI "   uint64_t \fBremote_irr\fP: 1"
.br
.ti -1c
.RI "   uint64_t \fBtrigger_mode\fP: 1"
.br
.ti -1c
.RI "   uint64_t \fBmask\fP: 1"
.br
.ti -1c
.RI "   uint64_t \fBreserved\fP: 39"
.br
.ti -1c
.RI "   uint64_t \fBdestination\fP: 8"
.br
.ti -1c
.RI "} \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBraw\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 57 of file apic\&.h\&.
.SH "Member Function Documentation"
.PP 
.SS "struct MaxOS::hardwarecommunication::RedirectionEntry::@1 MaxOS::hardwarecommunication::RedirectionEntry::__attribute__ ((packed))"

.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::delivery_mode"

.PP
Definition at line 60 of file apic\&.h\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::delivery_status"

.PP
Definition at line 62 of file apic\&.h\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::destination"

.PP
Definition at line 68 of file apic\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::set_redirect()\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::destination_mode"

.PP
Definition at line 61 of file apic\&.h\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::mask"

.PP
Definition at line 66 of file apic\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::set_redirect(), and MaxOS::hardwarecommunication::IOAPIC::set_redirect_mask()\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::pin_polarity"

.PP
Definition at line 63 of file apic\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::set_redirect()\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::raw"

.PP
Definition at line 71 of file apic\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::set_redirect()\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::remote_irr"

.PP
Definition at line 64 of file apic\&.h\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::reserved"

.PP
Definition at line 67 of file apic\&.h\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::trigger_mode"

.PP
Definition at line 65 of file apic\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::set_redirect()\&.
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::vector"

.PP
Definition at line 59 of file apic\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
