.TH "MaxOS::gui::Window" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::gui::Window \- A window that can be moved and resized and contains a widget\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window\&.h>\fP
.PP
Inherits \fBMaxOS::gui::CompositeWidget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height, \fBconst\fP \fBstring\fP &\fBtitle_text\fP)"
.br
.RI "Construct a new \fBWindow\fP object at a specific position and size (relative to the screen) with a title\&. "
.ti -1c
.RI "\fBWindow\fP (\fBWidget\fP *\fBcontained_widget\fP, \fBconst\fP \fBstring\fP &\fBtitle_text\fP)"
.br
.RI "Construct a new \fBWindow\fP object that contains a specific widget with a title\&. The window sizes itself to fit the widget\&. "
.ti -1c
.RI "\fBvoid\fP \fBdraw_self\fP (\fBcommon::GraphicsContext\fP *\fBgc\fP, \fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP) \fBoverride\fP"
.br
.RI "Draws the window and its children\&. "
.ti -1c
.RI "\fBvoid\fP \fBadd_child\fP (\fBWidget\fP *\fBchild\fP) \fBoverride\fP"
.br
.RI "Adds a child to the window\&. "
.ti -1c
.RI "\fBdrivers::peripherals::MouseEventHandler\fP * \fBon_mouse_button_pressed\fP (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button) \fBoverride\fP"
.br
.RI "Handles the mouse button being pressed\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::gui::CompositeWidget\fP
.in +1c
.ti -1c
.RI "\fBCompositeWidget\fP (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height)"
.br
.RI "Construct a new Composite \fBWidget\fP object at a specific position and size\&. "
.ti -1c
.RI "\fBvoid\fP \fBdraw\fP (\fBcommon::GraphicsContext\fP *\fBgc\fP, \fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP) \fBoverride\fP"
.br
.RI "Draws a section of the widget and its m_children\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_enter_widget\fP (\fBuint32_t\fP \fBto_x\fP, \fBuint32_t\fP \fBto_y\fP) \fBoverride\fP"
.br
.RI "Passes the event to the child that the mouse is over\&. (Event handling should be done by the derived class) "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_leave_widget\fP (\fBuint32_t\fP \fBfrom_x\fP, \fBuint32_t\fP \fBfrom_y\fP) \fBoverride\fP"
.br
.RI "Passes the event to the child that the mouse is over\&. (Event handling should be done by the derived class) "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_move_widget\fP (\fBuint32_t\fP \fBfrom_x\fP, \fBuint32_t\fP \fBfrom_y\fP, \fBuint32_t\fP \fBto_x\fP, \fBuint32_t\fP \fBto_y\fP) \fBoverride\fP"
.br
.RI "Passes the event to the child that the mouse is over, also generates a leave/enter event for children\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_button_released\fP (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button) \fBoverride\fP"
.br
.RI "Passes the event to the child that the mouse is over\&. (Event handling should be done by the derived class) "
.in -1c

Public Member Functions inherited from \fBMaxOS::gui::Widget\fP
.in +1c
.ti -1c
.RI "\fBWidget\fP ()"
.br
.RI "Construct a new \fBWidget\fP object\&. "
.ti -1c
.RI "\fBWidget\fP (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height)"
.br
.RI "Construct a new \fBWidget\fP object at a specific position and size\&. "
.ti -1c
.RI "\fBvoid\fP \fBinvalidate\fP ()"
.br
.RI "Invalidates the entire widget\&. This forces the widget to be redrawn on the next screen update\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBinvalidate\fP (\fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP)"
.br
.RI "Invalidates a specific area of the widget\&. This forces that part of the screen to be redrawn on the next screen update\&. "
.ti -1c
.RI "\fBvirtual\fP \fBcommon::Coordinates\fP \fBabsolute_coordinates\fP (\fBcommon::Coordinates\fP \fBcoordinates\fP)"
.br
.RI "Get the absolute coordinates of the widget (relative to the screen) "
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBcontains_coordinate\fP (\fBuint32_t\fP x, \fBuint32_t\fP y)"
.br
.RI "Check if the widget contains a specific coordinate\&. "
.ti -1c
.RI "\fBcommon::Rectangle\fP< \fBint32_t\fP > \fBposition\fP ()"
.br
.RI "Get the position of the widget\&. "
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBint32_t\fP left, \fBint32_t\fP top)"
.br
.RI "Set the position of the widget, and invalidate the old and new positions so they are redrawn\&. "
.ti -1c
.RI "\fBvoid\fP \fBresize\fP (\fBint32_t\fP width, \fBint32_t\fP height)"
.br
.RI "Set the size of the widget, and invalidate the old and new positions so they are redrawn\&. "
.ti -1c
.RI "\fBvoid\fP \fBfocus\fP ()"
.br
.RI "Set the current focused widget to be this widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_focus\fP ()"
.br
.RI "Handles the event when the widget is focussed\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_focus_lost\fP ()"
.br
.RI "Handles the event when the widget is unfocused\&. "
.ti -1c
.RI "\fBvoid\fP \fBbring_to_front\fP ()"
.br
.RI "Brings this widget to the front of the screen\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::peripherals::KeyboardEventHandler\fP
.in +1c
.ti -1c
.RI "\fBcommon::Event\fP< \fBKeyboardEvents\fP > * \fBon_event\fP (\fBcommon::Event\fP< \fBKeyboardEvents\fP > *) \fBoverride\fP"
.br
.RI "Handle the trigger of an event\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_key_down\fP (\fBKeyCode\fP, \fBconst\fP \fBKeyboardState\fP &)"
.br
.RI "Handle the key down event\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_key_up\fP (\fBKeyCode\fP, \fBconst\fP \fBKeyboardState\fP &)"
.br
.RI "Handle the key up event\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::EventHandler< KeyboardEvents >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBEvent\fP< KeyboardEvents > * \fBon_event\fP (\fBEvent\fP< KeyboardEvents > *\fBevent\fP)"
.br
.RI "This function is called when an event is raised\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBframe_thickness\fP { 5 }"
.br
.RI "How thick the bar around the window is\&. "
.ti -1c
.RI "uint8_t \fBtitle_bar_height\fP { 10 }"
.br
.RI "How large the bar at the top of the window is\&. "
.ti -1c
.RI "\fBcommon::Colour\fP \fBarea_colour\fP"
.br
.RI "The background colour of the window inner area\&. "
.ti -1c
.RI "\fBcommon::Colour\fP \fBframe_colour\fP"
.br
.RI "The colour of the bar around the window\&. "
.ti -1c
.RI "\fBcommon::Colour\fP \fBframe_border_colour\fP"
.br
.RI "The colour of the border around the bar around the window\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::gui::CompositeWidget\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBdraw\fP (\fBcommon::GraphicsContext\fP *\fBgc\fP, \fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP, \fBcommon::Vector\fP< \fBWidget\fP * >::iterator \fBstart\fP)"
.br
.RI "Draws a section of the widget and the m_children after a specific child\&. "
.in -1c

Protected Member Functions inherited from \fBMaxOS::gui::Widget\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBset_focus\fP (\fBWidget\fP *)"
.br
.RI "Sets the widget that is currently focussed\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBbring_to_front\fP (\fBWidget\fP *)"
.br
.RI "Brings a specific widget to the front of the screen\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::gui::CompositeWidget\fP
.in +1c
.ti -1c
.RI "\fBcommon::Vector\fP< \fBWidget\fP * > \fBm_children\fP"
.br
.RI "Widgets contained within this composite widget\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::gui::Widget\fP
.in +1c
.ti -1c
.RI "\fBcommon::Rectangle\fP< int32_t > \fBm_position\fP"
.br
.RI "The position and size of the widget (relative to its parent) "
.ti -1c
.RI "\fBWidget\fP * \fBm_parent\fP { nullptr }"
.br
.RI "The widget that owns this widget\&. "
.ti -1c
.RI "bool \fBm_valid\fP { false }"
.br
.RI "Is the widget drawn to the screen and up to date\&. "
.ti -1c
.RI "uint32_t \fBm_min_width\fP { 5 }"
.br
.RI "The smallest m_width the widget can be resized to\&. "
.ti -1c
.RI "uint32_t \fBm_min_height\fP { 5 }"
.br
.RI "The smallest m_height the widget can be resized to\&. "
.ti -1c
.RI "uint32_t \fBm_max_width\fP { 0x8FFFFFFF }"
.br
.RI "The largest m_width the widget can be resized to\&. "
.ti -1c
.RI "uint32_t \fBm_max_height\fP { 0x8FFFFFFF }"
.br
.RI "The largest m_height the widget can be resized to\&. "
.in -1c
.SH "Detailed Description"
.PP 
A window that can be moved and resized and contains a widget\&. 
.PP
Definition at line \fB24\fP of file \fBwindow\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Window::Window (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height, \fBconst\fP \fBstring\fP & title_text)"

.PP
Construct a new \fBWindow\fP object at a specific position and size (relative to the screen) with a title\&. 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP How many pixels from the left of the screen the window is 
.br
\fItop\fP How many pixels from the top of the screen the window is 
.br
\fIwidth\fP How many pixels wide the window is 
.br
\fIheight\fP How many pixels tall the window is 
.br
\fItitle_text\fP The text to display in the title bar of the window 
.RE
.PP

.PP
Definition at line \fB27\fP of file \fBwindow\&.cpp\fP\&..PP
.nf
28 : CompositeWidget(left, top, width, height),
29   m_title(0, \-(10 + 5) + 2, width \- 2 * 5, 10 + 5 \- 3, title_text),
30   m_mover(this),
31   m_resizer_top(this),
32   m_resizer_bottom(this),
33   m_resizer_left(this),
34   m_resizer_right(this),
35   m_resizer_top_left(this),
36   m_resizer_top_right(this),
37   m_resizer_bottom_left(this),
38   m_resizer_bottom_right(this)
39 {
40 
41     // Set the sizing
42     m_min_width = 2 * frame_thickness;
43     m_min_height = 2 * frame_thickness + title_bar_height;
44 
45     // Set the colours
46     area_colour = Colour(0xff, 0xff, 0xff);    // White
47     frame_border_colour = Colour(0x00, 0x00, 0x00);    // Black
48     frame_colour = Colour(0x57, 0x57, 0x57);      // Davy's Grey
49     m_title\&.foreground_colour = Colour(0xff, 0xff, 0xff);    // White
50     m_title\&.background_colour = frame_colour;
51 
52     // Add the title to the window
53     Window::add_child(&m_title);
54 
55 }
.fi

.PP
References \fBadd_child()\fP, \fBarea_colour\fP, \fBMaxOS::gui::widgets::Text::background_colour\fP, \fBMaxOS::gui::widgets::Text::foreground_colour\fP, \fBframe_border_colour\fP, \fBframe_colour\fP, \fBframe_thickness\fP, \fBMaxOS::gui::Widget::m_min_height\fP, \fBMaxOS::gui::Widget::m_min_width\fP, and \fBtitle_bar_height\fP\&.
.SS "Window::Window (\fBWidget\fP * contained_widget, \fBconst\fP \fBstring\fP & title_text)"

.PP
Construct a new \fBWindow\fP object that contains a specific widget with a title\&. The window sizes itself to fit the widget\&. 
.PP
\fBParameters\fP
.RS 4
\fIcontained_widget\fP The widget to contain within the window 
.br
\fItitle_text\fP The text to display in the title bar of the window 
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBwindow\&.cpp\fP\&..PP
.nf
64 : CompositeWidget(0, 0, contained_widget\->position()\&.width + 2 * 5 + 2, contained_widget\->position()\&.height + 2 * 5 + 10 + 2),
65   m_title(0, \-(10 + 5) + 2, contained_widget\->position()\&.width, 10 + 5 \- 3, title_text),
66   m_mover(this),
67   m_resizer_top(this),
68   m_resizer_bottom(this),
69   m_resizer_left(this),
70   m_resizer_right(this),
71   m_resizer_top_left(this),
72   m_resizer_top_right(this),
73   m_resizer_bottom_left(this),
74   m_resizer_bottom_right(this)
75 {
76 
77     // Set the sizing
78     m_min_width = 2 * frame_thickness;
79     m_min_height = 2 * frame_thickness + title_bar_height;
80 
81     // Set the colours
82     area_colour = Colour(0xff, 0xff, 0xff);    // White
83     frame_border_colour = Colour(0x00, 0x00, 0x00);    // Black
84     frame_colour = Colour(0x57, 0x57, 0x57);      // Davy's Grey
85     m_title\&.foreground_colour = Colour(0xff, 0xff, 0xff);    // White
86     m_title\&.background_colour = frame_colour;
87 
88     // Add the title to the window
89     Window::add_child(&m_title);
90     Window::add_child(contained_widget);
91 }
.fi

.PP
References \fBadd_child()\fP, \fBarea_colour\fP, \fBMaxOS::gui::widgets::Text::background_colour\fP, \fBMaxOS::gui::widgets::Text::foreground_colour\fP, \fBframe_border_colour\fP, \fBframe_colour\fP, \fBframe_thickness\fP, \fBMaxOS::gui::Widget::m_min_height\fP, \fBMaxOS::gui::Widget::m_min_width\fP, and \fBtitle_bar_height\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Window::add_child (\fBWidget\fP * child)\fC [override]\fP, \fC [virtual]\fP"

.PP
Adds a child to the window\&. 
.PP
\fBParameters\fP
.RS 4
\fIchild\fP The child to add\&. 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::gui::CompositeWidget\fP\&.
.PP
Definition at line \fB220\fP of file \fBwindow\&.cpp\fP\&..PP
.nf
220                                     {
221 
222     // If there is a child to add
223     if (child != nullptr) {
224 
225         // Change the position of the child to be inside the window contents
226         Rectangle<int32_t> child_position = child\->position();
227         child\->move(child_position\&.left + frame_thickness + 1,
228                     child_position\&.top + frame_thickness + title_bar_height + 1);
229 
230     }
231 
232     // Add the child to the window
233     CompositeWidget::add_child(child);
234 }
.fi

.PP
References \fBMaxOS::gui::CompositeWidget::add_child()\fP, \fBframe_thickness\fP, \fBMaxOS::common::Rectangle< Type >::left\fP, \fBtitle_bar_height\fP, and \fBMaxOS::common::Rectangle< Type >::top\fP\&.
.PP
Referenced by \fBWindow()\fP, and \fBWindow()\fP\&.
.SS "\fBvoid\fP Window::draw_self (\fBcommon::GraphicsContext\fP * gc, \fBcommon::Rectangle\fP< \fBint32_t\fP > & area)\fC [override]\fP, \fC [virtual]\fP"

.PP
Draws the window and its children\&. 
.PP
\fBParameters\fP
.RS 4
\fIgc\fP The graphics context to draw on\&. 
.br
\fIarea\fP The area to draw 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::gui::CompositeWidget\fP\&.
.PP
Definition at line \fB154\fP of file \fBwindow\&.cpp\fP\&..PP
.nf
154                                                                                 {
155 
156     // Get the positioning of the window
157     Coordinates window_absolute_position = CompositeWidget::absolute_coordinates(Coordinates(0, 0));
158     Rectangle<int32_t> window_position = this\->position();
159     int32_t window_x = window_absolute_position\&.first;
160     int32_t window_y = window_absolute_position\&.second;
161 
162     // Create an area for the window contents
163     Rectangle<int32_t> window_contents_area(frame_thickness, frame_thickness + title_bar_height,
164                                             window_position\&.width \- 2 * frame_thickness,
165                                             window_position\&.height \- 2 * frame_thickness \- title_bar_height);
166 
167     // Draw the window contents if they are in the area to draw
168     if (window_contents_area\&.intersects(area)) {
169         Rectangle<int32_t> contents_drawable = window_contents_area\&.intersection(area);
170         gc\->fill_rectangle(contents_drawable\&.left + window_x, contents_drawable\&.top + window_y,
171                            contents_drawable\&.left + contents_drawable\&.width + window_x,
172                            contents_drawable\&.top + contents_drawable\&.height + window_y, area_colour);
173     }
174 
175     // Draw the frame if it is in the area to draw
176     Rectangle<int32_t> window_frame_top_area(frame_thickness, 0, window_position\&.width \- 2 * frame_thickness,
177                                              frame_thickness + title_bar_height);
178     if (window_frame_top_area\&.intersects(area)) {
179         Rectangle<int32_t> frame_drawable = window_frame_top_area\&.intersection(area);
180         gc\->fill_rectangle(frame_drawable\&.left + window_x, frame_drawable\&.top + window_y,
181                            frame_drawable\&.left + frame_drawable\&.width + window_x,
182                            frame_drawable\&.top + frame_drawable\&.height + window_y, frame_colour);
183     }
184 
185     // Draw the bottom of the window frame
186     Rectangle<int32_t> window_frame_bottom_area(frame_thickness, window_position\&.height \- frame_thickness,
187                                                 window_position\&.width \- 2 * frame_thickness, frame_thickness);
188     if (window_frame_bottom_area\&.intersects(area)) {
189         Rectangle<int32_t> bottom_drawable = window_frame_bottom_area\&.intersection(area);
190         gc\->fill_rectangle(window_x + bottom_drawable\&.left, window_y + bottom_drawable\&.top,
191                            window_x + bottom_drawable\&.left + bottom_drawable\&.width,
192                            window_y + bottom_drawable\&.top + bottom_drawable\&.height, frame_colour);
193     }
194 
195     // Draw the left of the window frame
196     Rectangle<int32_t> window_frame_left_area(0, 0, frame_thickness, window_position\&.height);
197     if (window_frame_left_area\&.intersects(area)) {
198         Rectangle<int32_t> left_drawable = window_frame_left_area\&.intersection(area);
199         gc\->fill_rectangle(window_x + left_drawable\&.left, window_y + left_drawable\&.top,
200                            window_x + left_drawable\&.left + left_drawable\&.width,
201                            window_y + left_drawable\&.top + left_drawable\&.height, frame_colour);
202     }
203 
204     // Draw the right of the window frame
205     Rectangle<int32_t> window_frame_right_area(window_position\&.width \- frame_thickness, 0, frame_thickness,
206                                                window_position\&.height);
207     if (window_frame_right_area\&.intersects(area)) {
208         Rectangle<int32_t> right_drawable = window_frame_right_area\&.intersection(area);
209         gc\->fill_rectangle(window_x + right_drawable\&.left, window_y + right_drawable\&.top,
210                            window_x + right_drawable\&.left + right_drawable\&.width,
211                            window_y + right_drawable\&.top + right_drawable\&.height, frame_colour);
212     }
213 }
.fi

.PP
References \fBMaxOS::gui::Widget::absolute_coordinates()\fP, \fBarea_colour\fP, \fBframe_colour\fP, \fBframe_thickness\fP, \fBMaxOS::common::Rectangle< Type >::height\fP, \fBMaxOS::common::Rectangle< Type >::intersection()\fP, \fBMaxOS::common::Rectangle< Type >::intersects()\fP, \fBMaxOS::common::Rectangle< Type >::left\fP, \fBMaxOS::gui::Widget::position()\fP, \fBtitle_bar_height\fP, \fBMaxOS::common::Rectangle< Type >::top\fP, and \fBMaxOS::common::Rectangle< Type >::width\fP\&.
.SS "\fBMouseEventHandler\fP * Window::on_mouse_button_pressed (\fBuint32_t\fP mouse_x, \fBuint32_t\fP mouse_y, \fBuint8_t\fP button)\fC [override]\fP, \fC [virtual]\fP"

.PP
Handles the mouse button being pressed\&. 
.PP
\fBParameters\fP
.RS 4
\fImouse_x\fP The x coordinate of the mouse\&. 
.br
\fImouse_y\fP The y coordinate of the mouse\&. 
.br
\fIbutton\fP The button that is pressed\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The MouseEventHandler of the widget that will handle the event, nullptr otherwise\&. 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::gui::CompositeWidget\fP\&.
.PP
Definition at line \fB103\fP of file \fBwindow\&.cpp\fP\&..PP
.nf
103                                                                                                      {
104 
105     // Pass the mouse event to the children
106     drivers::peripherals::MouseEventHandler* child_result = CompositeWidget::on_mouse_button_pressed(mouse_x, mouse_y, button);
107     Rectangle<int32_t> window_position = position();
108 
109     // Bring the window to the front
110     bring_to_front();
111 
112     // Convert the mouse coordinates to an int32_t
113     auto x = (int32_t) mouse_x;
114     auto y = (int32_t) mouse_y;
115 
116     if (x <= frame_thickness) {
117         if (y <= frame_thickness)
118             return &m_resizer_top_left;
119 
120         else if (y < window_position\&.height \- frame_thickness)
121             return &m_resizer_left;
122 
123         else
124             return &m_resizer_bottom_left;
125     } else if (x < window_position\&.width \- frame_thickness) {
126         if (y <= frame_thickness)
127             return &m_resizer_top;
128 
129         else if (y < frame_thickness + title_bar_height)
130             return &m_mover;
131 
132         else if (y >= window_position\&.height \- frame_thickness)
133             return &m_resizer_bottom;
134     } else {
135         if (y <= frame_thickness)
136             return &m_resizer_top_right;
137 
138         else if (y < window_position\&.height \- frame_thickness)
139             return &m_resizer_right;
140 
141         else
142             return &m_resizer_bottom_right;
143     }
144 
145     return child_result;
146 }
.fi

.PP
References \fBMaxOS::gui::Widget::bring_to_front()\fP, \fBframe_thickness\fP, \fBMaxOS::common::Rectangle< Type >::height\fP, \fBMaxOS::gui::CompositeWidget::on_mouse_button_pressed()\fP, \fBMaxOS::gui::Widget::position()\fP, \fBtitle_bar_height\fP, and \fBMaxOS::common::Rectangle< Type >::width\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBcommon::Colour\fP MaxOS::gui::Window::area_colour"

.PP
The background colour of the window inner area\&. 
.PP
Definition at line \fB46\fP of file \fBwindow\&.h\fP\&.
.PP
Referenced by \fBdraw_self()\fP, \fBWindow()\fP, and \fBWindow()\fP\&.
.SS "\fBcommon::Colour\fP MaxOS::gui::Window::frame_border_colour"

.PP
The colour of the border around the bar around the window\&. 
.PP
Definition at line \fB48\fP of file \fBwindow\&.h\fP\&.
.PP
Referenced by \fBWindow()\fP, and \fBWindow()\fP\&.
.SS "\fBcommon::Colour\fP MaxOS::gui::Window::frame_colour"

.PP
The colour of the bar around the window\&. 
.PP
Definition at line \fB47\fP of file \fBwindow\&.h\fP\&.
.PP
Referenced by \fBdraw_self()\fP, \fBWindow()\fP, and \fBWindow()\fP\&.
.SS "uint8_t MaxOS::gui::Window::frame_thickness { 5 }"

.PP
How thick the bar around the window is\&. 
.PP
Definition at line \fB43\fP of file \fBwindow\&.h\fP\&..PP
.nf
43 { 5 };              
.fi

.PP
Referenced by \fBadd_child()\fP, \fBdraw_self()\fP, \fBon_mouse_button_pressed()\fP, \fBWindow()\fP, and \fBWindow()\fP\&.
.SS "uint8_t MaxOS::gui::Window::title_bar_height { 10 }"

.PP
How large the bar at the top of the window is\&. 
.PP
Definition at line \fB44\fP of file \fBwindow\&.h\fP\&..PP
.nf
44 { 10 };            
.fi

.PP
Referenced by \fBadd_child()\fP, \fBdraw_self()\fP, \fBon_mouse_button_pressed()\fP, \fBWindow()\fP, and \fBWindow()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
