.TH "maxOS::system::multiboot_header" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::system::multiboot_header
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmagic\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBchecksum\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBheader_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBload_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBload_end_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBbss_end_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBentry_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmode_type\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBwidth\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBheight\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBdepth\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 104 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::bss_end_addr"

.PP
Definition at line 119 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::checksum"

.PP
Definition at line 113 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::depth"

.PP
Definition at line 126 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::entry_addr"

.PP
Definition at line 120 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::flags"

.PP
Definition at line 110 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::header_addr"

.PP
Definition at line 116 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::height"

.PP
Definition at line 125 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::load_addr"

.PP
Definition at line 117 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::load_end_addr"

.PP
Definition at line 118 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::magic"

.PP
Definition at line 107 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::mode_type"

.PP
Definition at line 123 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_header::width"

.PP
Definition at line 124 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
