.TH "MaxOS::processes::ELFHeader64" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::processes::ELFHeader64 \- The header of a 64-bit ELF file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <elf\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "unsigned char \fBidentification\fP [16]"
.br
.RI "Identifies the file as an ELF file and contains metadata about the file (class, data encoding, version, OS ABI, etc\&.) "
.ti -1c
.RI "uint16_t \fBtype\fP"
.br
.RI "The type of the ELF file (see ELFType) "
.ti -1c
.RI "uint16_t \fBmachine\fP"
.br
.RI "The target architecture of the ELF file (see ELFMachine) "
.ti -1c
.RI "uint32_t \fBversion\fP"
.br
.RI "The version of the ELF file (see ELFVersion) "
.ti -1c
.RI "uint64_t \fBentry\fP"
.br
.RI "The starting RIP address where the program begins execution\&. "
.ti -1c
.RI "uint64_t \fBprogram_header_offset\fP"
.br
.RI "The offset in the file where the program header table starts\&. "
.ti -1c
.RI "uint64_t \fBsection_header_offset\fP"
.br
.RI "The offset in the file where the section header table starts\&. "
.ti -1c
.RI "uint32_t \fBflags\fP"
.br
.RI "Architecture-specific flags\&. "
.ti -1c
.RI "uint16_t \fBelf_header_size\fP"
.br
.RI "The size of this ELF header\&. "
.ti -1c
.RI "uint16_t \fBprogram_header_size\fP"
.br
.RI "The size of each entry in the program header table\&. "
.ti -1c
.RI "uint16_t \fBprogram_header_count\fP"
.br
.RI "The number of entries in the program header table\&. "
.ti -1c
.RI "uint16_t \fBsection_header_size\fP"
.br
.RI "The size of each entry in the section header table\&. "
.ti -1c
.RI "uint16_t \fBsection_header_count\fP"
.br
.RI "The number of entries in the section header table\&. "
.ti -1c
.RI "uint16_t \fBsection_header_string_table_index\fP"
.br
.RI "Where the section header string table is located (index into the section header table) "
.in -1c
.SH "Detailed Description"
.PP 
The header of a 64-bit ELF file\&. 
.PP
Definition at line \fB107\fP of file \fBelf\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t MaxOS::processes::ELFHeader64::elf_header_size"

.PP
The size of this ELF header\&. 
.PP
Definition at line \fB116\fP of file \fBelf\&.h\fP\&.
.SS "uint64_t MaxOS::processes::ELFHeader64::entry"

.PP
The starting RIP address where the program begins execution\&. 
.PP
Definition at line \fB112\fP of file \fBelf\&.h\fP\&.
.SS "uint32_t MaxOS::processes::ELFHeader64::flags"

.PP
Architecture-specific flags\&. 
.PP
Definition at line \fB115\fP of file \fBelf\&.h\fP\&.
.SS "unsigned char MaxOS::processes::ELFHeader64::identification[16]"

.PP
Identifies the file as an ELF file and contains metadata about the file (class, data encoding, version, OS ABI, etc\&.) 
.PP
Definition at line \fB108\fP of file \fBelf\&.h\fP\&.
.SS "uint16_t MaxOS::processes::ELFHeader64::machine"

.PP
The target architecture of the ELF file (see ELFMachine) 
.PP
Definition at line \fB110\fP of file \fBelf\&.h\fP\&.
.SS "uint16_t MaxOS::processes::ELFHeader64::program_header_count"

.PP
The number of entries in the program header table\&. 
.PP
Definition at line \fB118\fP of file \fBelf\&.h\fP\&.
.SS "uint64_t MaxOS::processes::ELFHeader64::program_header_offset"

.PP
The offset in the file where the program header table starts\&. 
.PP
Definition at line \fB113\fP of file \fBelf\&.h\fP\&.
.PP
Referenced by \fBMaxOS::processes::ELF64::get_program_header()\fP\&.
.SS "uint16_t MaxOS::processes::ELFHeader64::program_header_size"

.PP
The size of each entry in the program header table\&. 
.PP
Definition at line \fB117\fP of file \fBelf\&.h\fP\&.
.SS "uint16_t MaxOS::processes::ELFHeader64::section_header_count"

.PP
The number of entries in the section header table\&. 
.PP
Definition at line \fB120\fP of file \fBelf\&.h\fP\&.
.SS "uint64_t MaxOS::processes::ELFHeader64::section_header_offset"

.PP
The offset in the file where the section header table starts\&. 
.PP
Definition at line \fB114\fP of file \fBelf\&.h\fP\&.
.PP
Referenced by \fBMaxOS::processes::ELF64::get_section_header()\fP\&.
.SS "uint16_t MaxOS::processes::ELFHeader64::section_header_size"

.PP
The size of each entry in the section header table\&. 
.PP
Definition at line \fB119\fP of file \fBelf\&.h\fP\&.
.SS "uint16_t MaxOS::processes::ELFHeader64::section_header_string_table_index"

.PP
Where the section header string table is located (index into the section header table) 
.PP
Definition at line \fB121\fP of file \fBelf\&.h\fP\&.
.SS "uint16_t MaxOS::processes::ELFHeader64::type"

.PP
The type of the ELF file (see ELFType) 
.PP
Definition at line \fB109\fP of file \fBelf\&.h\fP\&.
.SS "uint32_t MaxOS::processes::ELFHeader64::version"

.PP
The version of the ELF file (see ELFVersion) 
.PP
Definition at line \fB111\fP of file \fBelf\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
