.TH "MaxOS::system::shift_out_of_bounds_info" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system::shift_out_of_bounds_info
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ubsan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBsource_location_t\fP \fBlocation\fP"
.br
.ti -1c
.RI "\fBtype_descriptor_t\fP * \fBleft_type\fP"
.br
.ti -1c
.RI "\fBtype_descriptor_t\fP * \fBright_type\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file ubsan\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBtype_descriptor_t\fP* MaxOS::system::shift_out_of_bounds_info::left_type"

.PP
Definition at line 48 of file ubsan\&.h\&.
.SS "\fBsource_location_t\fP MaxOS::system::shift_out_of_bounds_info::location"

.PP
Definition at line 47 of file ubsan\&.h\&.
.SS "\fBtype_descriptor_t\fP* MaxOS::system::shift_out_of_bounds_info::right_type"

.PP
Definition at line 49 of file ubsan\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
