.TH "MaxOS::filesystem::format::ext2" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::format::ext2
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBBlockGroupDescriptor\fP"
.br
.ti -1c
.RI "struct \fBDirectoryEntry\fP"
.br
.ti -1c
.RI "class \fBExt2Directory\fP"
.br
.RI "Handles the directory operations on the \fBext2\fP filesystem\&. "
.ti -1c
.RI "class \fBExt2File\fP"
.br
.RI "Handles the file operations on the \fBext2\fP filesystem\&. "
.ti -1c
.RI "class \fBExt2FileSystem\fP"
.br
.RI "Handles the \fBext2\fP filesystem operations\&. "
.ti -1c
.RI "class \fBExt2Volume\fP"
.br
.ti -1c
.RI "struct \fBInode\fP"
.br
.ti -1c
.RI "class \fBInodeHandler\fP"
.br
.RI "Simplfies the management of an inode & its blocks\&. "
.ti -1c
.RI "struct \fBInodeOS2Linux\fP"
.br
.ti -1c
.RI "struct \fBSuperBlock\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBFileSystemState\fP { \fBCLEAN\fP = 1, \fBERROR\fP = 2 }"
.br
.ti -1c
.RI "enum class \fBErrorOperation\fP { \fBIGNORE\fP = 1, \fBREMOUNT\fP = 2, \fBPANIC\fP = 3 }"
.br
.ti -1c
.RI "enum class \fBCreatorOS\fP { \fBLINUX\fP, \fBGNU_HURD\fP, \fBMASIX\fP, \fBFREE_BSD\fP, \fBOTHER_LITES\fP }"
.br
.ti -1c
.RI "enum class \fBOptionalFeatures\fP { \fBPREALLOCATE_DIRECTORY\fP = 0x1, \fBAFS_SERVER_INODES\fP = 0x2, \fBJOURNAL_ENABLED\fP = 0x4, \fBATTRIBUTES_EXTENDED\fP = 0x8, \fBRESIZEABLE\fP = 0x10, \fBHASH_INDEXING\fP = 0x20 }"
.br
.ti -1c
.RI "enum class \fBRequiredFeatures\fP { \fBCOMPRESSION\fP = 0x1, \fBDIRECTORY_HAS_TYPE\fP = 0x2, \fBMUST_REPLAY_JOURNAL\fP = 0x4, \fBJOURNAL_DEVICE\fP = 0x8 }"
.br
.ti -1c
.RI "enum class \fBReadOnlyFeatures\fP { \fBSPARSE_SUPER_BLOCKS\fP = 0x1, \fBFILES_64_BIT\fP = 0x2, \fBBINARY_TREE_DIRECTORIES\fP = 0x4 }"
.br
.ti -1c
.RI "enum class \fBInodeType\fP { \fBUNKNOWN\fP, \fBFIFO\fP = 0x1000, \fBCHARACTER_DEVICE\fP = 0x2000, \fBDIRECTORY\fP = 0x4000, \fBBLOCK_DEVICE\fP = 0x6000, \fBFILE\fP = 0x8000, \fBSYMBOLIC_LINK\fP = 0xA000, \fBSOCKET\fP = 0xC000 }"
.br
.ti -1c
.RI "enum class \fBInodePermissions\fP { \fBOTHER_EXECUTE\fP = 0x1, \fBOTHER_WRITE\fP = 0x2, \fBOTHER_READ\fP = 0x4, \fBGROUP_EXECUTE\fP = 0x8, \fBGROUP_WRITE\fP = 0x10, \fBGROUP_READ\fP = 0x20, \fBUSER_EXECUTE\fP = 0x40, \fBUSER_WRITE\fP = 0x80, \fBUSER_READ\fP = 0x100, \fBSTICKY\fP = 0x200, \fBGROUP_ID\fP = 0x400, \fBUSER_ID\fP = 0x800 }"
.br
.ti -1c
.RI "enum class \fBInodePermissionsDefaults\fP { \fBFILE\fP = 0x1A4, \fBDIRECTORY\fP = 0x1ED }"
.br
.ti -1c
.RI "enum class \fBInodeFlags\fP { \fBSECURE_DELETE\fP = 0x1, \fBKEEP_DATA\fP = 0x2, \fBFILE_COMPRESSION\fP = 0x4, \fBSYNC_UPDATES\fP = 0x8, \fBFILE_IMMUTABLE\fP = 0x10, \fBAPPEND_ONLY\fP = 0x20, \fBDONT_DUMP\fP = 0x40, \fBNO_LAST_ACCESS\fP = 0x80, \fBHASH_INDEXED\fP = 0x10000, \fBAFS_DIRECTORY\fP = 0x20000, \fBJOURNAL_FILE_DATA\fP = 0x40000 }"
.br
.ti -1c
.RI "enum class \fBEntryType\fP { \fBUNKNOWN\fP, \fBFILE\fP, \fBDIRECTORY\fP, \fBCHARACTER_DEVICE\fP, \fBBLOCK_DEVICE\fP, \fBFIFO\fP, \fBSOCKET\fP, \fBSYMBOLIC_LINK\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::filesystem::format::ext2::SuperBlock\fP \fB__attribute__\fP ((packed)) superblock_t"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "enum \fBMaxOS::filesystem::format::ext2::FileSystemState\fP \fB__attribute__\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum class \fBMaxOS::filesystem::format::ext2::CreatorOS\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fILINUX \fP\fP
.TP
\fB\fIGNU_HURD \fP\fP
.TP
\fB\fIMASIX \fP\fP
.TP
\fB\fIFREE_BSD \fP\fP
.TP
\fB\fIOTHER_LITES \fP\fP
.PP
Definition at line \fB82\fP of file \fBext2\&.h\fP\&..PP
.nf
82                                   {
83                   LINUX,
84                   GNU_HURD,
85                   MASIX,
86                   FREE_BSD,
87                   OTHER_LITES,
88               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::EntryType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUNKNOWN \fP\fP
.TP
\fB\fIFILE \fP\fP
.TP
\fB\fIDIRECTORY \fP\fP
.TP
\fB\fICHARACTER_DEVICE \fP\fP
.TP
\fB\fIBLOCK_DEVICE \fP\fP
.TP
\fB\fIFIFO \fP\fP
.TP
\fB\fISOCKET \fP\fP
.TP
\fB\fISYMBOLIC_LINK \fP\fP
.PP
Definition at line \fB216\fP of file \fBext2\&.h\fP\&..PP
.nf
216                                    {
217                   UNKNOWN,
218                   FILE,
219                   DIRECTORY,
220                   CHARACTER_DEVICE,
221                   BLOCK_DEVICE,
222                   FIFO,
223                   SOCKET,
224                   SYMBOLIC_LINK
225               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::ErrorOperation\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIIGNORE \fP\fP
.TP
\fB\fIREMOUNT \fP\fP
.TP
\fB\fIPANIC \fP\fP
.PP
Definition at line \fB76\fP of file \fBext2\&.h\fP\&..PP
.nf
76                                        {
77                   IGNORE    = 1,
78                   REMOUNT   = 2,
79                   PANIC     = 3,
80               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::FileSystemState\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICLEAN \fP\fP
.TP
\fB\fIERROR \fP\fP
.PP
Definition at line \fB71\fP of file \fBext2\&.h\fP\&..PP
.nf
71                                         {
72                   CLEAN = 1,
73                   ERROR = 2,
74               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::InodeFlags\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISECURE_DELETE \fP\fP
.TP
\fB\fIKEEP_DATA \fP\fP
.TP
\fB\fIFILE_COMPRESSION \fP\fP
.TP
\fB\fISYNC_UPDATES \fP\fP
.TP
\fB\fIFILE_IMMUTABLE \fP\fP
.TP
\fB\fIAPPEND_ONLY \fP\fP
.TP
\fB\fIDONT_DUMP \fP\fP
.TP
\fB\fINO_LAST_ACCESS \fP\fP
.TP
\fB\fIHASH_INDEXED \fP\fP
.TP
\fB\fIAFS_DIRECTORY \fP\fP
.TP
\fB\fIJOURNAL_FILE_DATA \fP\fP
.PP
Definition at line \fB184\fP of file \fBext2\&.h\fP\&..PP
.nf
184                                    {
185                   SECURE_DELETE     = 0x1,  // Zero out data on deletion
186                   KEEP_DATA         = 0x2,
187                   FILE_COMPRESSION  = 0x4,
188                   SYNC_UPDATES      = 0x8,
189                   FILE_IMMUTABLE    = 0x10,
190                   APPEND_ONLY       = 0x20,
191                   DONT_DUMP         = 0x40,
192                   NO_LAST_ACCESS    = 0x80,
193                   HASH_INDEXED      = 0x10000,
194                   AFS_DIRECTORY     = 0x20000,
195                   JOURNAL_FILE_DATA = 0x40000,
196               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::InodePermissions\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIOTHER_EXECUTE \fP\fP
.TP
\fB\fIOTHER_WRITE \fP\fP
.TP
\fB\fIOTHER_READ \fP\fP
.TP
\fB\fIGROUP_EXECUTE \fP\fP
.TP
\fB\fIGROUP_WRITE \fP\fP
.TP
\fB\fIGROUP_READ \fP\fP
.TP
\fB\fIUSER_EXECUTE \fP\fP
.TP
\fB\fIUSER_WRITE \fP\fP
.TP
\fB\fIUSER_READ \fP\fP
.TP
\fB\fISTICKY \fP\fP
.TP
\fB\fIGROUP_ID \fP\fP
.TP
\fB\fIUSER_ID \fP\fP
.PP
Definition at line \fB163\fP of file \fBext2\&.h\fP\&..PP
.nf
163                                          {
164                   OTHER_EXECUTE = 0x1,
165                   OTHER_WRITE   = 0x2,
166                   OTHER_READ    = 0x4,
167                   GROUP_EXECUTE = 0x8,
168                   GROUP_WRITE   = 0x10,
169                   GROUP_READ    = 0x20,
170                   USER_EXECUTE  = 0x40,
171                   USER_WRITE    = 0x80,
172                   USER_READ     = 0x100,
173                   STICKY        = 0x200,
174                   GROUP_ID      = 0x400,
175                   USER_ID       = 0x800,
176               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::InodePermissionsDefaults\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIFILE \fP\fP
.TP
\fB\fIDIRECTORY \fP\fP
.PP
Definition at line \fB178\fP of file \fBext2\&.h\fP\&..PP
.nf
178                                                  {
179                   FILE      = 0x1A4,
180                   DIRECTORY = 0x1ED,
181 
182               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::InodeType\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIUNKNOWN \fP\fP
.TP
\fB\fIFIFO \fP\fP
.TP
\fB\fICHARACTER_DEVICE \fP\fP
.TP
\fB\fIDIRECTORY \fP\fP
.TP
\fB\fIBLOCK_DEVICE \fP\fP
.TP
\fB\fIFILE \fP\fP
.TP
\fB\fISYMBOLIC_LINK \fP\fP
.TP
\fB\fISOCKET \fP\fP
.PP
Definition at line \fB152\fP of file \fBext2\&.h\fP\&..PP
.nf
152                                    {
153                   UNKNOWN,
154                   FIFO              = 0x1000,
155                   CHARACTER_DEVICE  = 0x2000,
156                   DIRECTORY         = 0x4000,
157                   BLOCK_DEVICE      = 0x6000,
158                   FILE              = 0x8000,
159                   SYMBOLIC_LINK     = 0xA000,
160                   SOCKET            = 0xC000,
161               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::OptionalFeatures\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIPREALLOCATE_DIRECTORY \fP\fP
.TP
\fB\fIAFS_SERVER_INODES \fP\fP
.TP
\fB\fIJOURNAL_ENABLED \fP\fP
.TP
\fB\fIATTRIBUTES_EXTENDED \fP\fP
.TP
\fB\fIRESIZEABLE \fP\fP
.TP
\fB\fIHASH_INDEXING \fP\fP
.PP
Definition at line \fB90\fP of file \fBext2\&.h\fP\&..PP
.nf
90                                          {
91                   PREALLOCATE_DIRECTORY = 0x1,
92                   AFS_SERVER_INODES     = 0x2,
93                   JOURNAL_ENABLED       = 0x4,
94                   ATTRIBUTES_EXTENDED   = 0x8,
95                   RESIZEABLE            = 0x10,
96                   HASH_INDEXING         = 0x20,
97               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::ReadOnlyFeatures\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fISPARSE_SUPER_BLOCKS \fP\fP
.TP
\fB\fIFILES_64_BIT \fP\fP
.TP
\fB\fIBINARY_TREE_DIRECTORIES \fP\fP
.PP
Definition at line \fB106\fP of file \fBext2\&.h\fP\&..PP
.nf
106                                           {
107                   SPARSE_SUPER_BLOCKS       = 0x1,
108                   FILES_64_BIT              = 0x2,
109                   BINARY_TREE_DIRECTORIES   = 0x4,
110               };
.fi

.SS "enum class \fBMaxOS::filesystem::format::ext2::RequiredFeatures\fP\fC [strong]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICOMPRESSION \fP\fP
.TP
\fB\fIDIRECTORY_HAS_TYPE \fP\fP
.TP
\fB\fIMUST_REPLAY_JOURNAL \fP\fP
.TP
\fB\fIJOURNAL_DEVICE \fP\fP
.PP
Definition at line \fB99\fP of file \fBext2\&.h\fP\&..PP
.nf
99                                           {
100                   COMPRESSION           = 0x1,
101                   DIRECTORY_HAS_TYPE    = 0x2,
102                   MUST_REPLAY_JOURNAL   = 0x4,
103                   JOURNAL_DEVICE        = 0x8,
104               };
.fi

.SH "Function Documentation"
.PP 
.SS "struct \fBMaxOS::filesystem::format::ext2::SuperBlock\fP MaxOS::filesystem::format::ext2::__attribute__ ((packed))"

.SH "Variable Documentation"
.PP 
.SS "enum \fBMaxOS::filesystem::format::ext2::EntryType\fP MaxOS::filesystem::format::ext2::__attribute__"

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
