.TH "MaxOS::gui::widgets::InputBoxTextChangedEvent" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::gui::widgets::InputBoxTextChangedEvent \- Event that is triggered when the text in an input box is changed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inputbox\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< InputBoxEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputBoxTextChangedEvent\fP (\fBconst\fP \fBstring\fP &)"
.br
.ti -1c
.RI "\fB~InputBoxTextChangedEvent\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBMaxOS::common::Event< InputBoxEvents >\fP
.in +1c
.ti -1c
.RI "\fBEvent\fP (InputBoxEvents \fBtype\fP)"
.br
.RI "___________________________ Template Implementation ___________________________ "
.ti -1c
.RI "\fB~Event\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBnew_text\fP"
.br
.in -1c

Public Attributes inherited from \fBMaxOS::common::Event< InputBoxEvents >\fP
.in +1c
.ti -1c
.RI "InputBoxEvents \fBtype\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbufferValue\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBintValue\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBboolValue\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBuint8_t\fP * \fBbufferValue\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBintValue\fP"
.br
.ti -1c
.RI "   \fBbool\fP \fBboolValue\fP"
.br
.ti -1c
.RI "} \fBreturn_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event that is triggered when the text in an input box is changed\&. 
.PP
Definition at line \fB27\fP of file \fBinputbox\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InputBoxTextChangedEvent::InputBoxTextChangedEvent (\fBconst\fP \fBstring\fP & new_text)"

.PP
Definition at line \fB263\fP of file \fBinputbox\&.cpp\fP\&..PP
.nf
264 : Event(InputBoxEvents::TEXT_CHANGED),
265   new_text(new_text)
266 {
267 
268 }
.fi

.SS "InputBoxTextChangedEvent::~InputBoxTextChangedEvent ()\fC [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBstring\fP MaxOS::gui::widgets::InputBoxTextChangedEvent::new_text"

.PP
Definition at line \fB32\fP of file \fBinputbox\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
