.TH "maxOS::hardwarecommunication::InterruptDescriptorTablePointer" 3 "Sat Jan 6 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::hardwarecommunication::InterruptDescriptorTablePointer \- Describes the Interrupt Descriptor Table\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interrupts\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.ti -1c
.RI "uint32_t \fBbase\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes the Interrupt Descriptor Table\&. 
.PP
Definition at line 54 of file interrupts\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t maxOS::hardwarecommunication::InterruptDescriptorTablePointer::base"

.PP
Definition at line 56 of file interrupts\&.h\&.
.PP
Referenced by maxOS::hardwarecommunication::InterruptManager::InterruptManager()\&.
.SS "uint16_t maxOS::hardwarecommunication::InterruptDescriptorTablePointer::size"

.PP
Definition at line 55 of file interrupts\&.h\&.
.PP
Referenced by maxOS::hardwarecommunication::InterruptManager::InterruptManager()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
