.TH "MaxOS::net::EthernetFrameHeader" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::EthernetFrameHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethernetframe\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBdestinationMAC\fP: 48"
.br
.ti -1c
.RI "uint64_t \fBsourceMAC\fP: 48"
.br
.ti -1c
.RI "uint16_t \fBtype\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBethernetframe\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::net::EthernetFrameHeader::destinationMAC"

.PP
Definition at line \fB20\fP of file \fBethernetframe\&.h\fP\&.
.SS "uint64_t MaxOS::net::EthernetFrameHeader::sourceMAC"

.PP
Definition at line \fB21\fP of file \fBethernetframe\&.h\fP\&.
.SS "uint16_t MaxOS::net::EthernetFrameHeader::type"

.PP
Definition at line \fB23\fP of file \fBethernetframe\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
