.TH "MaxOS::system" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP"
.br
.ti -1c
.RI "class \fBCPU\fP"
.br
.ti -1c
.RI "struct \fBGDTR\fP"
.br
.RI "A struct used to store information for the GDT Register\&. "
.ti -1c
.RI "class \fBGlobalDescriptorTable\fP"
.br
.RI "Sets up the GDT in the \fBCPU\fP\&. "
.ti -1c
.RI "struct \fBinvalid_value_info\fP"
.br
.ti -1c
.RI "struct \fBlocation_only_info\fP"
.br
.ti -1c
.RI "class \fBMultiboot\fP"
.br
.ti -1c
.RI "struct \fBout_of_bounds_info\fP"
.br
.ti -1c
.RI "struct \fBoverflow_info\fP"
.br
.ti -1c
.RI "struct \fBshift_out_of_bounds_info\fP"
.br
.ti -1c
.RI "struct \fBsource_location\fP"
.br
.ti -1c
.RI "struct \fBStackFrame\fP"
.br
.ti -1c
.RI "struct \fBSyscallArguments\fP"
.br
.ti -1c
.RI "class \fBSyscallManager\fP"
.br
.RI "Handles system calls\&. "
.ti -1c
.RI "struct \fBtss\fP"
.br
.ti -1c
.RI "struct \fBtype_descriptor\fP"
.br
.ti -1c
.RI "struct \fBtype_mismatch_info\fP"
.br
.ti -1c
.RI "struct \fBtype_mismatch_info_v1\fP"
.br
.ti -1c
.RI "class \fBUBSanHandler\fP"
.br
.RI "Handles undefined behaviour sanitizer\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBMaxOS::system::SyscallArguments\fP \fBsyscall_args_t\fP"
.br
.ti -1c
.RI "typedef \fBsyscall_args_t\fP *(* \fBsyscall_func_t\fP) (\fBsyscall_args_t\fP *args)"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::source_location\fP \fBsource_location_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::type_descriptor\fP \fBtype_descriptor_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::type_mismatch_info\fP \fBtype_mismatch_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::type_mismatch_info_v1\fP \fBtype_mismatch_info_v1_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::overflow_info\fP \fBoverflow_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::shift_out_of_bounds_info\fP \fBshift_out_of_bounds_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::out_of_bounds_info\fP \fBout_of_bounds_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::location_only_info\fP \fBlocation_only_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::invalid_value_info\fP \fBinvalid_value_info_t\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBSyscallType\fP { \fBCLOSE_PROCESS\fP, \fBKLOG\fP, \fBCREATE_SHARED_MEMORY\fP, \fBOPEN_SHARED_MEMORY\fP, \fBALLOCATE_MEMORY\fP, \fBFREE_MEMORY\fP, \fBCREATE_IPC_ENDPOINT\fP, \fBSEND_IPC_MESSAGE\fP, \fBREMOVE_IPC_ENDPOINT\fP, \fBTHREAD_YIELD\fP, \fBTHREAD_SLEEP\fP, \fBTHREAD_CLOSE\fP }"
.br
.RI "DO NOT REARRANGE ONLY APPEND TO\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::system::tss\fP \fB__attribute__\fP ((__packed__)) tss_t"
.br
.ti -1c
.RI "struct \fBMaxOS::system::GDTR\fP \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class \fBMaxOS::system::CPU\fP \fB__attribute__\fP"
.br
.ti -1c
.RI "const char * \fBType_Check_Kinds\fP []"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBMaxOS::system::invalid_value_info\fP \fBMaxOS::system::invalid_value_info_t\fP"

.SS "typedef struct \fBMaxOS::system::location_only_info\fP \fBMaxOS::system::location_only_info_t\fP"

.SS "typedef struct \fBMaxOS::system::out_of_bounds_info\fP \fBMaxOS::system::out_of_bounds_info_t\fP"

.SS "typedef struct \fBMaxOS::system::overflow_info\fP \fBMaxOS::system::overflow_info_t\fP"

.SS "typedef struct \fBMaxOS::system::shift_out_of_bounds_info\fP \fBMaxOS::system::shift_out_of_bounds_info_t\fP"

.SS "typedef struct \fBMaxOS::system::source_location\fP \fBMaxOS::system::source_location_t\fP"

.SS "typedef struct \fBMaxOS::system::SyscallArguments\fP \fBMaxOS::system::syscall_args_t\fP"

.SS "typedef \fBsyscall_args_t\fP*(* MaxOS::system::syscall_func_t) (\fBsyscall_args_t\fP *args)"

.PP
Definition at line 52 of file syscalls\&.h\&.
.SS "typedef struct \fBMaxOS::system::type_descriptor\fP \fBMaxOS::system::type_descriptor_t\fP"

.SS "typedef struct \fBMaxOS::system::type_mismatch_info\fP \fBMaxOS::system::type_mismatch_info_t\fP"

.SS "typedef struct \fBMaxOS::system::type_mismatch_info_v1\fP \fBMaxOS::system::type_mismatch_info_v1_t\fP"

.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBMaxOS::system::SyscallType\fP"

.PP
DO NOT REARRANGE ONLY APPEND TO\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fICLOSE_PROCESS \fP\fP
.TP
\fB\fIKLOG \fP\fP
.TP
\fB\fICREATE_SHARED_MEMORY \fP\fP
.TP
\fB\fIOPEN_SHARED_MEMORY \fP\fP
.TP
\fB\fIALLOCATE_MEMORY \fP\fP
.TP
\fB\fIFREE_MEMORY \fP\fP
.TP
\fB\fICREATE_IPC_ENDPOINT \fP\fP
.TP
\fB\fISEND_IPC_MESSAGE \fP\fP
.TP
\fB\fIREMOVE_IPC_ENDPOINT \fP\fP
.TP
\fB\fITHREAD_YIELD \fP\fP
.TP
\fB\fITHREAD_SLEEP \fP\fP
.TP
\fB\fITHREAD_CLOSE \fP\fP
.PP
Definition at line 25 of file syscalls\&.h\&.
.PP
.nf
25                         {
26             CLOSE_PROCESS,
27             KLOG,
28             CREATE_SHARED_MEMORY,
29             OPEN_SHARED_MEMORY,
30             ALLOCATE_MEMORY,
31             FREE_MEMORY,
32             CREATE_IPC_ENDPOINT,
33             SEND_IPC_MESSAGE,
34             REMOVE_IPC_ENDPOINT,
35             THREAD_YIELD,
36             THREAD_SLEEP,
37             THREAD_CLOSE,
38         };
.fi
.SH "Function Documentation"
.PP 
.SS "struct \fBMaxOS::system::tss\fP \fBMaxOS::system::__attribute__\fP ((__packed__))"

.SS "struct \fBMaxOS::system::GDTR\fP \fBMaxOS::system::__attribute__\fP ((packed))"

.SH "Variable Documentation"
.PP 
.SS "class \fBMaxOS::system::GlobalDescriptorTable\fP \fBMaxOS::system::__attribute__\fP"

.SS "const char* MaxOS::system::Type_Check_Kinds[]"
\fBInitial value:\fP
.PP
.nf
= {
            "load of",
            "store to",
            "reference binding to",
            "member access within",
            "member call on",
            "constructor call on",
            "downcast of",
            "downcast of",
            "upcast of",
            "cast to virtual base of",
        }
.fi
.PP
Definition at line 67 of file ubsan\&.h\&.
.PP
Referenced by MaxOS::system::UBSanHandler::print_type_mismatch(), and MaxOS::system::UBSanHandler::print_type_mismatch_v1()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
