.TH "maxOS::system" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::system
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBCPUState\fP"
.br
.RI "Stores the state of the CPU registers\&. "
.ti -1c
.RI "class \fBGlobalDescriptorTable\fP"
.br
.RI "Sets up the GDT in the CPU\&. "
.ti -1c
.RI "struct \fBmultiboot_aout_symbol_table\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_apm_info\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_color\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_elf_section_header_table\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_header\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_info\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_mmap_entry\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_mod_list\fP"
.br
.ti -1c
.RI "class \fBProcess\fP"
.br
.ti -1c
.RI "class \fBSegmentDescriptor\fP"
.br
.RI "Stores data for the segment descriptors in the GDT\&. "
.ti -1c
.RI "class \fBSyscallHandler\fP"
.br
.RI "Handles system calls\&. "
.ti -1c
.RI "class \fBTask\fP"
.br
.RI "A task that can be scheduled by the \fBTaskManager\fP\&. "
.ti -1c
.RI "class \fBTaskManager\fP"
.br
.RI "Manages the scheduling of m_tasks\&. "
.ti -1c
.RI "class \fBThread\fP"
.br
.RI "A execution thread that can be scheduled by the \fBThreadManager\fP\&. "
.ti -1c
.RI "class \fBThreadManager\fP"
.br
.RI "Manages the scheduling of threads\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBmultiboot_uint8_t\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBmultiboot_uint16_t\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBmultiboot_uint32_t\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBmultiboot_uint64_t\fP"
.br
.ti -1c
.RI "typedef struct \fBmultiboot_aout_symbol_table\fP \fBmultiboot_aout_symbol_table_t\fP"
.br
.ti -1c
.RI "typedef struct \fBmultiboot_elf_section_header_table\fP \fBmultiboot_elf_section_header_table_t\fP"
.br
.ti -1c
.RI "typedef struct \fBmultiboot_info\fP \fBmultiboot_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBmultiboot_mmap_entry\fP \fBmultiboot_memory_map_t\fP"
.br
.ti -1c
.RI "typedef struct \fBmultiboot_mod_list\fP \fBmultiboot_module_t\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "class \fBmaxOS::system::SegmentDescriptor\fP \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class \fBmaxOS::system::GlobalDescriptorTable\fP \fB__attribute__\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef struct \fBmultiboot_aout_symbol_table\fP \fBmaxOS::system::multiboot_aout_symbol_table_t\fP"

.PP
Definition at line 136 of file multiboot\&.h\&.
.SS "typedef struct \fBmultiboot_elf_section_header_table\fP \fBmaxOS::system::multiboot_elf_section_header_table_t\fP"

.PP
Definition at line 146 of file multiboot\&.h\&.
.SS "typedef struct \fBmultiboot_info\fP \fBmaxOS::system::multiboot_info_t\fP"

.PP
Definition at line 226 of file multiboot\&.h\&.
.SS "typedef struct \fBmultiboot_mmap_entry\fP \fBmaxOS::system::multiboot_memory_map_t\fP"

.PP
Definition at line 247 of file multiboot\&.h\&.
.SS "typedef struct \fBmultiboot_mod_list\fP \fBmaxOS::system::multiboot_module_t\fP"

.PP
Definition at line 261 of file multiboot\&.h\&.
.SS "typedef unsigned short \fBmaxOS::system::multiboot_uint16_t\fP"

.PP
Definition at line 99 of file multiboot\&.h\&.
.SS "typedef unsigned int \fBmaxOS::system::multiboot_uint32_t\fP"

.PP
Definition at line 100 of file multiboot\&.h\&.
.SS "typedef unsigned long long \fBmaxOS::system::multiboot_uint64_t\fP"

.PP
Definition at line 101 of file multiboot\&.h\&.
.SS "typedef unsigned char \fBmaxOS::system::multiboot_uint8_t\fP"

.PP
Definition at line 98 of file multiboot\&.h\&.
.SH "Function Documentation"
.PP 
.SS "class \fBmaxOS::system::SegmentDescriptor\fP maxOS::system::__attribute__ ((packed))"

.SH "Variable Documentation"
.PP 
.SS "class \fBmaxOS::system::Task\fP maxOS::system::__attribute__"

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
