.TH "MaxOS::hardwarecommunication::RSDPDescriptor" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::RSDPDescriptor
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <acpi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBsignature\fP [8]"
.br
.ti -1c
.RI "uint8_t \fBchecksum\fP"
.br
.ti -1c
.RI "char \fBOEMID\fP [6]"
.br
.ti -1c
.RI "uint8_t \fBrevision\fP"
.br
.ti -1c
.RI "uint32_t \fBrsdt_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBacpi\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::hardwarecommunication::RSDPDescriptor::checksum"

.PP
Definition at line \fB20\fP of file \fBacpi\&.h\fP\&.
.SS "char MaxOS::hardwarecommunication::RSDPDescriptor::OEMID[6]"

.PP
Definition at line \fB21\fP of file \fBacpi\&.h\fP\&.
.SS "uint8_t MaxOS::hardwarecommunication::RSDPDescriptor::revision"

.PP
Definition at line \fB22\fP of file \fBacpi\&.h\fP\&.
.SS "uint32_t MaxOS::hardwarecommunication::RSDPDescriptor::rsdt_address"

.PP
Definition at line \fB23\fP of file \fBacpi\&.h\fP\&.
.PP
Referenced by \fBMaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::AdvancedConfigurationAndPowerInterface()\fP\&.
.SS "char MaxOS::hardwarecommunication::RSDPDescriptor::signature[8]"

.PP
Definition at line \fB19\fP of file \fBacpi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
