.TH "MaxOS::net::UserDatagramProtocolPayloadHandler" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::UserDatagramProtocolPayloadHandler
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <udp\&.h>\fP
.PP
Inherits \fBMaxOS::common::EventHandler< UserDatagramProtocolEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBUserDatagramProtocolPayloadHandler\fP ()"
.br
.RI "\fBHandler\fP "
.ti -1c
.RI "\fB~UserDatagramProtocolPayloadHandler\fP ()"
.br
.ti -1c
.RI "\fBcommon::Event\fP< \fBUserDatagramProtocolEvents\fP > * \fBon_event\fP (\fBcommon::Event\fP< \fBUserDatagramProtocolEvents\fP > *\fBevent\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBhandleUserDatagramProtocolMessage\fP (\fBUserDatagramProtocolSocket\fP *socket, \fBuint8_t\fP *\fBdata\fP, \fBuint16_t\fP \fBsize\fP)"
.br
.in -1c

Public Member Functions inherited from \fBMaxOS::common::EventHandler< UserDatagramProtocolEvents >\fP
.in +1c
.ti -1c
.RI "\fBEventHandler\fP ()"
.br
.ti -1c
.RI "\fB~EventHandler\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBEvent\fP< UserDatagramProtocolEvents > * \fBon_event\fP (\fBEvent\fP< UserDatagramProtocolEvents > *\fBevent\fP)"
.br
.RI "This function is called when an event is raised\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB49\fP of file \fBudp\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "UserDatagramProtocolPayloadHandler::UserDatagramProtocolPayloadHandler ()\fC [default]\fP"

.PP
\fBHandler\fP 
.SS "UserDatagramProtocolPayloadHandler::~UserDatagramProtocolPayloadHandler ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP UserDatagramProtocolPayloadHandler::handleUserDatagramProtocolMessage (\fBUserDatagramProtocolSocket\fP * socket, \fBuint8_t\fP * data, \fBuint16_t\fP size)\fC [virtual]\fP"

.PP
Definition at line \fB14\fP of file \fBudp\&.cpp\fP\&..PP
.nf
14                                                                                                                            {
15 
16 }
.fi

.PP
Referenced by \fBon_event()\fP\&.
.SS "\fBEvent\fP< \fBUserDatagramProtocolEvents\fP > * UserDatagramProtocolPayloadHandler::on_event (\fBcommon::Event\fP< \fBUserDatagramProtocolEvents\fP > * event)\fC [override]\fP"

.PP
Definition at line \fB18\fP of file \fBudp\&.cpp\fP\&..PP
.nf
18                                                                                                                         {
19 
20     switch (event \-> type) {
21         case UserDatagramProtocolEvents::DATA_RECEIVED:
22             handleUserDatagramProtocolMessage(((UDPDataReceivedEvent*)event) \-> socket, ((UDPDataReceivedEvent*)event) \-> data, ((UDPDataReceivedEvent*)event) \-> size);
23             break;
24         default:
25             break;
26     }
27 
28     return event;
29 }
.fi

.PP
References \fBdata\fP, \fBMaxOS::net::DATA_RECEIVED\fP, \fBhandleUserDatagramProtocolMessage()\fP, \fBsize\fP, and \fBtype\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
