.TH "MaxOS::net::IPV4AddressResolver" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::IPV4AddressResolver \- Resolves IP addresses to MAC addresses\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ipv4\&.h>\fP
.PP
Inherited by \fBMaxOS::net::AddressResolutionProtocol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIPV4AddressResolver\fP (\fBInternetProtocolHandler\fP *internet_protocol_handler)"
.br
.RI "Construct a new IPV4 Address Resolver object and register it with the Internet Protocol Handler\&. "
.ti -1c
.RI "\fBvirtual\fP \fBdrivers::ethernet::MediaAccessControlAddress\fP \fBresolve\fP (\fBInternetProtocolAddress\fP address)"
.br
.RI "Resolves an IP address to a MAC address\&. (Default, returns broadcast address, override for use) "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBstore\fP (\fBInternetProtocolAddress\fP \fBinternet_protocol_address\fP, \fBdrivers::ethernet::MediaAccessControlAddress\fP \fBmedia_access_control_address\fP)"
.br
.RI "Stores an IP address to MAC address mapping\&. (Default, does nothing, override for use) "
.in -1c
.SH "Detailed Description"
.PP 
Resolves IP addresses to MAC addresses\&. 
.PP
Definition at line \fB53\fP of file \fBipv4\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "IPV4AddressResolver::IPV4AddressResolver (\fBInternetProtocolHandler\fP * internet_protocol_handler)\fC [explicit]\fP"

.PP
Construct a new IPV4 Address Resolver object and register it with the Internet Protocol Handler\&. 
.PP
\fBParameters\fP
.RS 4
\fIinternet_protocol_handler\fP The Internet Protocol Handler to register with 
.RE
.PP

.PP
Definition at line \fB22\fP of file \fBipv4\&.cpp\fP\&..PP
.nf
22                                                                                            {
23 
24     internet_protocol_handler\->register_ipv_4_address_resolver(this);
25 
26 }
.fi

.PP
References \fBMaxOS::net::InternetProtocolHandler::register_ipv_4_address_resolver()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMediaAccessControlAddress\fP IPV4AddressResolver::resolve (\fBInternetProtocolAddress\fP address)\fC [virtual]\fP"

.PP
Resolves an IP address to a MAC address\&. (Default, returns broadcast address, override for use) 
.PP
\fBParameters\fP
.RS 4
\fIaddress\fP The IP address to turn into a MAC address\&. 
.RE
.PP
\fBReturns\fP
.RS 4
The MAC address\&. 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::net::AddressResolutionProtocol\fP\&.
.PP
Definition at line \fB37\fP of file \fBipv4\&.cpp\fP\&..PP
.nf
37                                                                                       {
38     return 0xFFFFFFFFFFFF;
39 }
.fi

.PP
Referenced by \fBMaxOS::net::InternetProtocolHandler::send_internet_protocol_packet()\fP\&.
.SS "\fBvoid\fP IPV4AddressResolver::store (\fBInternetProtocolAddress\fP internet_protocol_address, \fBdrivers::ethernet::MediaAccessControlAddress\fP media_access_control_address)\fC [virtual]\fP"

.PP
Stores an IP address to MAC address mapping\&. (Default, does nothing, override for use) 
.PP
\fBParameters\fP
.RS 4
\fIinternet_protocol_address\fP The IP address\&. 
.br
\fImedia_access_control_address\fP The MAC address\&. 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::net::AddressResolutionProtocol\fP\&.
.PP
Definition at line \fB47\fP of file \fBipv4\&.cpp\fP\&..PP
.nf
47                                                                                                                                          {
48 
49 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
