.TH "maxOS::system::multiboot_mod_list" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::system::multiboot_mod_list
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmod_start\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmod_end\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBcmdline\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBpad\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 249 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_mod_list::cmdline"

.PP
Definition at line 256 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_mod_list::mod_end"

.PP
Definition at line 253 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_mod_list::mod_start"

.PP
Definition at line 252 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_mod_list::pad"

.PP
Definition at line 259 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
