.TH "MaxOS::drivers::clock::ClockEventHandler" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::clock::ClockEventHandler \- Handles the events triggered by the clock\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clock\&.h>\fP
.PP
Inherits \fBMaxOS::common::EventHandler< ClockEvents >\fP\&.
.PP
Inherited by \fBMaxOS::gui::Desktop\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClockEventHandler\fP ()"
.br
.RI "\fBHandler\fP "
.ti -1c
.RI "\fB~ClockEventHandler\fP ()"
.br
.ti -1c
.RI "\fBcommon::Event\fP< \fBClockEvents\fP > * \fBon_event\fP (\fBcommon::Event\fP< \fBClockEvents\fP > *event) override"
.br
.ti -1c
.RI "virtual void \fBon_time\fP (const \fBcommon::Time\fP &time)"
.br
.RI "Called when the clock ticks\&. "
.in -1c
.SH "Detailed Description"
.PP 
Handles the events triggered by the clock\&. 
.PP
Definition at line 41 of file clock\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ClockEventHandler::ClockEventHandler ()"

.PP
\fBHandler\fP 
.PP
Definition at line 15 of file clock\&.cpp\&.
.PP
.nf
15                                      {
16 
17 }
.fi
.SS "ClockEventHandler::~ClockEventHandler ()"

.PP
Definition at line 19 of file clock\&.cpp\&.
.PP
.nf
19                                       {
20 
21 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBEvent\fP< \fBClockEvents\fP > * ClockEventHandler::on_event (\fBcommon::Event\fP< \fBClockEvents\fP > * event)\fC [override]\fP"

.PP
Definition at line 32 of file clock\&.cpp\&.
.PP
.nf
32                                                                          {
33 
34     switch (event -> type) {
35         case TIME:
36           on_time(*((TimeEvent *)event)->time);
37             break;
38             
39         default:
40             break;
41     }
42 
43     // Return the event
44     return event;
45 }
.fi
.PP
References MaxOS::drivers::clock::TIME, and type\&.
.SS "void ClockEventHandler::on_time (const \fBcommon::Time\fP & time)\fC [virtual]\fP"

.PP
Called when the clock ticks\&. 
.PP
\fBParameters\fP
.RS 4
\fItime\fP The current time 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::Desktop\fP\&.
.PP
Definition at line 28 of file clock\&.cpp\&.
.PP
.nf
28                                                   {
29 
30 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
