.TH "MaxOS::filesystem::format::ext2::SuperBlock" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::format::ext2::SuperBlock
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ext2\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBtotal_inodes\fP"
.br
.ti -1c
.RI "uint32_t \fBtotal_blocks\fP"
.br
.ti -1c
.RI "uint32_t \fBreserved_blocks\fP"
.br
.ti -1c
.RI "uint32_t \fBunallocated_blocks\fP"
.br
.ti -1c
.RI "uint32_t \fBunallocated_inodes\fP"
.br
.ti -1c
.RI "uint32_t \fBstarting_block\fP"
.br
.ti -1c
.RI "uint32_t \fBblock_size\fP"
.br
.ti -1c
.RI "uint32_t \fBfragment_size\fP"
.br
.ti -1c
.RI "uint32_t \fBblocks_per_group\fP"
.br
.ti -1c
.RI "uint32_t \fBfragments_per_group\fP"
.br
.ti -1c
.RI "uint32_t \fBinodes_per_group\fP"
.br
.ti -1c
.RI "uint32_t \fBlast_mount_time\fP"
.br
.ti -1c
.RI "uint32_t \fBlate_write_time\fP"
.br
.ti -1c
.RI "uint16_t \fBmounts_since_check\fP"
.br
.ti -1c
.RI "uint16_t \fBmounts_until_check\fP"
.br
.ti -1c
.RI "uint16_t \fBsignature\fP"
.br
.ti -1c
.RI "uint16_t \fBstate\fP"
.br
.ti -1c
.RI "uint16_t \fBerror_operation\fP"
.br
.ti -1c
.RI "uint16_t \fBversion_minor\fP"
.br
.ti -1c
.RI "uint32_t \fBlast_check_time\fP"
.br
.ti -1c
.RI "uint32_t \fBtime_until_check\fP"
.br
.ti -1c
.RI "uint32_t \fBos_id\fP"
.br
.ti -1c
.RI "uint32_t \fBversion_major\fP"
.br
.ti -1c
.RI "uint16_t \fBreserved_user\fP"
.br
.ti -1c
.RI "uint16_t \fBreserved_group\fP"
.br
.ti -1c
.RI "uint32_t \fBfirst_inode\fP"
.br
.ti -1c
.RI "uint16_t \fBinode_size\fP"
.br
.ti -1c
.RI "uint16_t \fBsuperblock_group\fP"
.br
.ti -1c
.RI "uint32_t \fBoptional_features\fP"
.br
.ti -1c
.RI "uint32_t \fBrequired_features\fP"
.br
.ti -1c
.RI "uint16_t \fBread_only_features\fP"
.br
.ti -1c
.RI "uint8_t \fBfilesystem_id\fP [16]"
.br
.ti -1c
.RI "uint8_t \fBvolume_name\fP [16]"
.br
.ti -1c
.RI "uint8_t \fBlast_mount_path\fP [64]"
.br
.ti -1c
.RI "uint32_t \fBcompression\fP"
.br
.ti -1c
.RI "uint8_t \fBfile_preallocation_blocks\fP"
.br
.ti -1c
.RI "uint8_t \fBdirectory_preallocation_blocks\fP"
.br
.ti -1c
.RI "uint16_t \fBunused\fP"
.br
.ti -1c
.RI "uint8_t \fBjournal_id\fP [16]"
.br
.ti -1c
.RI "uint32_t \fBjournal_inode\fP"
.br
.ti -1c
.RI "uint32_t \fBjournal_device\fP"
.br
.ti -1c
.RI "uint32_t \fBorphan_inodes_start\fP"
.br
.ti -1c
.RI "uint8_t \fBfree\fP [276]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBext2\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::block_size"

.PP
Definition at line \fB28\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::blocks_per_group"

.PP
Definition at line \fB30\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::compression"

.PP
Definition at line \fB58\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::SuperBlock::directory_preallocation_blocks"

.PP
Definition at line \fB60\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::error_operation"

.PP
Definition at line \fB39\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::SuperBlock::file_preallocation_blocks"

.PP
Definition at line \fB59\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::SuperBlock::filesystem_id[16]"

.PP
Definition at line \fB55\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::first_inode"

.PP
Definition at line \fB49\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::fragment_size"

.PP
Definition at line \fB29\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::fragments_per_group"

.PP
Definition at line \fB31\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::SuperBlock::free[276]"

.PP
Definition at line \fB66\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::inode_size"

.PP
Definition at line \fB50\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::inodes_per_group"

.PP
Definition at line \fB32\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::journal_device"

.PP
Definition at line \fB64\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::SuperBlock::journal_id[16]"

.PP
Definition at line \fB62\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::journal_inode"

.PP
Definition at line \fB63\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::last_check_time"

.PP
Definition at line \fB41\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::SuperBlock::last_mount_path[64]"

.PP
Definition at line \fB57\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::last_mount_time"

.PP
Definition at line \fB33\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::late_write_time"

.PP
Definition at line \fB34\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::mounts_since_check"

.PP
Definition at line \fB35\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::mounts_until_check"

.PP
Definition at line \fB36\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::optional_features"

.PP
Definition at line \fB52\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::orphan_inodes_start"

.PP
Definition at line \fB65\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::os_id"

.PP
Definition at line \fB43\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::read_only_features"

.PP
Definition at line \fB54\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::required_features"

.PP
Definition at line \fB53\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::reserved_blocks"

.PP
Definition at line \fB24\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::reserved_group"

.PP
Definition at line \fB46\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::reserved_user"

.PP
Definition at line \fB45\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::signature"

.PP
Definition at line \fB37\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::starting_block"

.PP
Definition at line \fB27\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::state"

.PP
Definition at line \fB38\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::superblock_group"

.PP
Definition at line \fB51\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::time_until_check"

.PP
Definition at line \fB42\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::total_blocks"

.PP
Definition at line \fB23\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::total_inodes"

.PP
Definition at line \fB22\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::unallocated_blocks"

.PP
Definition at line \fB25\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::unallocated_inodes"

.PP
Definition at line \fB26\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::unused"

.PP
Definition at line \fB61\fP of file \fBext2\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::ext2::SuperBlock::version_major"

.PP
Definition at line \fB44\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::SuperBlock::version_minor"

.PP
Definition at line \fB40\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::SuperBlock::volume_name[16]"

.PP
Definition at line \fB56\fP of file \fBext2\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
