.TH "MaxOS::system" 3 "Sun Oct 13 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fB__attribute__\fP"
.br
.ti -1c
.RI "class \fBCPU\fP"
.br
.ti -1c
.RI "struct \fBCPUState\fP"
.br
.RI "Stores the state of the \fBCPU\fP registers\&. "
.ti -1c
.RI "struct \fBGDTR\fP"
.br
.RI "A struct used to store information for the GDT Register\&. "
.ti -1c
.RI "class \fBGlobalDescriptorTable\fP"
.br
.RI "Sets up the GDT in the \fBCPU\fP\&. "
.ti -1c
.RI "class \fBMultiboot\fP"
.br
.ti -1c
.RI "class \fBProcess\fP"
.br
.ti -1c
.RI "struct \fBStackFrame\fP"
.br
.ti -1c
.RI "class \fBSyscallHandler\fP"
.br
.RI "Handles system calls\&. "
.ti -1c
.RI "class \fBTask\fP"
.br
.RI "A task that can be scheduled by the \fBTaskManager\fP\&. "
.ti -1c
.RI "class \fBTaskManager\fP"
.br
.RI "Manages the scheduling of m_tasks\&. "
.ti -1c
.RI "class \fBThread\fP"
.br
.RI "A execution thread that can be scheduled by the \fBThreadManager\fP\&. "
.ti -1c
.RI "class \fBThreadManager\fP"
.br
.RI "Manages the scheduling of threads\&. "
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::system::GDTR\fP \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "class \fBMaxOS::system::GlobalDescriptorTable\fP \fB__attribute__\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "struct \fBMaxOS::system::GDTR\fP \fBMaxOS::system::__attribute__\fP ((packed))"

.SH "Variable Documentation"
.PP 
.SS "class \fBMaxOS::system::Task\fP \fBMaxOS::system::__attribute__\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
