.TH "MaxOS::filesystem::FileResource" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::FileResource \- A wrapper for a \fBFile\fP which exposes \fBFile\fP operations as Resource operations\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vfsresource\&.h>\fP
.PP
Inherits \fBMaxOS::processes::Resource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileResource\fP (\fBconst\fP \fBstring\fP &\fBname\fP, \fBsize_t\fP flags, \fBprocesses::resource_type_t\fP \fBtype\fP)"
.br
.RI "Construct a new \fBFile\fP Resource object\&. "
.ti -1c
.RI "\fBint\fP \fBread\fP (\fBvoid\fP *buffer, \fBsize_t\fP size, \fBsize_t\fP flags) \fBfinal\fP"
.br
.RI "read from a file resource "
.ti -1c
.RI "\fBint\fP \fBwrite\fP (\fBconst\fP \fBvoid\fP *buffer, \fBsize_t\fP size, \fBsize_t\fP flags) \fBfinal\fP"
.br
.RI "write to a file resource "
.in -1c

Public Member Functions inherited from \fBMaxOS::processes::Resource\fP
.in +1c
.ti -1c
.RI "\fBResource\fP (const \fBstring\fP &\fBname\fP, size_t flags, \fBresource_type_t\fP \fBtype\fP)"
.br
.RI "Constructs a new \fBResource\fP object\&. "
.ti -1c
.RI "\fBstring\fP \fBname\fP ()"
.br
.RI "Gets the name of this resource\&. "
.ti -1c
.RI "\fBresource_type_t\fP \fBtype\fP ()"
.br
.RI "Gets the type of this resource\&. "
.ti -1c
.RI "virtual void \fBopen\fP (size_t flags)"
.br
.RI "Opens the resource\&. "
.ti -1c
.RI "virtual void \fBclose\fP (size_t flags)"
.br
.RI "Closes the resource\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBFile\fP * \fBfile\fP"
.br
.RI "The file that this resource handles & exposes\&. "
.in -1c
.SH "Detailed Description"
.PP 
A wrapper for a \fBFile\fP which exposes \fBFile\fP operations as Resource operations\&. 


.PP
\fBSee also\fP
.RS 4
\fBFile\fP 
.PP
\fBResource\fP 
.RE
.PP
\fBTodo\fP
.RS 4
Should this free the memory of the file when the resource is done?? 
.RE
.PP

.PP
Definition at line \fB32\fP of file \fBvfsresource\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileResource::FileResource (\fBconst\fP \fBstring\fP & name, \fBsize_t\fP flags, \fBprocesses::resource_type_t\fP type)"

.PP
Construct a new \fBFile\fP Resource object\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the resource 
.br
\fIflags\fP The flags for the resource when opened 
.br
\fItype\fP The type of the resource 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBvfsresource\&.cpp\fP\&..PP
.nf
25 : Resource(name, flags, type),
26   file(nullptr) // Initialised by the registry
27 {
28 
29 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "\fBint\fP FileResource::read (\fBvoid\fP * buffer, \fBsize_t\fP size, \fBsize_t\fP flags)\fC [final]\fP, \fC [virtual]\fP"

.PP
read from a file resource 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The buffer to read into 
.br
\fIsize\fP The number of bytes to read 
.br
\fIflags\fP The flags to pass to the reading 
.RE
.PP
\fBReturns\fP
.RS 4
The number of bytes successfully read or -1 on error 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::processes::Resource\fP\&.
.PP
Definition at line \fB41\fP of file \fBvfsresource\&.cpp\fP\&..PP
.nf
41                                                               {
42 
43     // File not found
44     if(!file)
45         return \-1;
46 
47     // Handle the operation
48     switch ((FileFlags)flags) {
49 
50         case FileFlags::DEFAULT:{
51 
52             buffer_t file_buffer(buffer, size);
53             file\->read(&file_buffer, size);
54             break;
55         }
56 
57         case FileFlags::READ_SIZE:{
58             return file\->size();
59         }
60 
61         case FileFlags::READ_OFFSET:{
62 
63             return file\->position();
64         }
65 
66         default:
67             return \-1;
68     }
69     return size;
70 }
.fi

.PP
References \fBfile\fP, \fBMaxOS::filesystem::File::position()\fP, \fBMaxOS::filesystem::File::read()\fP, and \fBMaxOS::filesystem::File::size()\fP\&.
.SS "\fBint\fP FileResource::write (\fBconst\fP \fBvoid\fP * buffer, \fBsize_t\fP size, \fBsize_t\fP flags)\fC [final]\fP, \fC [virtual]\fP"

.PP
write to a file resource 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The buffer to write from 
.br
\fIsize\fP The number of bytes to write 
.br
\fIflags\fP The flags to pass to the writing 
.RE
.PP
\fBReturns\fP
.RS 4
The number of bytes successfully written or -1 on error 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::processes::Resource\fP\&.
.PP
Definition at line \fB80\fP of file \fBvfsresource\&.cpp\fP\&..PP
.nf
80                                                                      {
81 
82     // File not found
83     if(!file)
84         return \-1;
85 
86     // Handle the operation
87     switch ((FileFlags)flags) {
88         case FileFlags::DEFAULT:{
89 
90             buffer_t file_buffer((void*)buffer, size);
91             file\->write(&file_buffer, size);
92             break;
93         }
94 
95         case FileFlags::WRITE_SEEK_SET:
96             file\->seek(SeekType::SET, size);
97             break;
98 
99         case FileFlags::WRITE_SEEK_CUR:
100             file\->seek(SeekType::CURRENT, size);
101             break;
102 
103         case FileFlags::WRITE_SEEK_END:
104             file\->seek(SeekType::END, size);
105             break;
106 
107         case FileFlags::WRITE_NAME:{
108 
109             // Open the parent
110             Resource* parent = GlobalResourceRegistry::get_registry(resource_type_t::FILESYSTEM)\->get_resource(Path::parent_directory(name()));
111             auto parent_directory = ((DirectoryResource*)parent)\->directory;
112 
113             // Rename
114             string new_name = string((uint8_t*)buffer, size);
115             parent_directory\->rename_file(file, new_name);
116             break;
117         }
118 
119         default:
120             return \-1;
121 
122     }
123 
124     return size;
125 }
.fi

.PP
References \fBfile\fP, \fBMaxOS::processes::GlobalResourceRegistry::get_registry()\fP, \fBMaxOS::processes::Resource::name()\fP, \fBMaxOS::filesystem::Path::parent_directory()\fP, \fBMaxOS::filesystem::File::seek()\fP, and \fBMaxOS::filesystem::File::write()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBFile\fP* MaxOS::filesystem::FileResource::file"

.PP
The file that this resource handles & exposes\&. 
.PP
Definition at line \fB38\fP of file \fBvfsresource\&.h\fP\&.
.PP
Referenced by \fBread()\fP, and \fBwrite()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
