.TH "MaxOS::memory::PageTableEntry" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::memory::PageTableEntry \- Struct for a page table entry\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <physical\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBpresent\fP: 1"
.br
.RI "*copydoc \fBPageFlags::PRESENT\fP "
.ti -1c
.RI "bool \fBwrite\fP: 1"
.br
.RI "*copydoc \fBPageFlags::WRITE\fP "
.ti -1c
.RI "bool \fBuser\fP: 1"
.br
.RI "*copydoc \fBPageFlags::USER\fP "
.ti -1c
.RI "bool \fBwrite_through\fP: 1"
.br
.RI "*copydoc \fBPageFlags::WRITE_THROUGH\fP "
.ti -1c
.RI "bool \fBcache_disabled\fP: 1"
.br
.RI "*copydoc \fBPageFlags::CACHE_DISABLED\fP "
.ti -1c
.RI "bool \fBaccessed\fP: 1"
.br
.RI "*copydoc \fBPageFlags::ACCESSED\fP "
.ti -1c
.RI "bool \fBdirty\fP: 1"
.br
.RI "*copydoc \fBPageFlags::DIRTY\fP "
.ti -1c
.RI "bool \fBhuge_page\fP: 1"
.br
.RI "*copydoc \fBPageFlags::HUGE_PAGE\fP "
.ti -1c
.RI "bool \fBglobal\fP: 1"
.br
.RI "*copydoc \fBPageFlags::GLOBAL\fP "
.ti -1c
.RI "uint8_t \fBavailable\fP: 3"
.br
.RI "Extra metadata bytes available for OS use\&. "
.ti -1c
.RI "uint64_t \fBphysical_address\fP: 52"
.br
.RI "The address the page represents in memory\&. "
.in -1c
.SH "Detailed Description"
.PP 
Struct for a page table entry\&. 
.PP
Definition at line \fB62\fP of file \fBphysical\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool MaxOS::memory::PageTableEntry::accessed"

.PP
*copydoc \fBPageFlags::ACCESSED\fP 
.PP
Definition at line \fB69\fP of file \fBphysical\&.h\fP\&.
.SS "uint8_t MaxOS::memory::PageTableEntry::available"

.PP
Extra metadata bytes available for OS use\&. 
.PP
Definition at line \fB73\fP of file \fBphysical\&.h\fP\&.
.SS "bool MaxOS::memory::PageTableEntry::cache_disabled"

.PP
*copydoc \fBPageFlags::CACHE_DISABLED\fP 
.PP
Definition at line \fB68\fP of file \fBphysical\&.h\fP\&.
.SS "bool MaxOS::memory::PageTableEntry::dirty"

.PP
*copydoc \fBPageFlags::DIRTY\fP 
.PP
Definition at line \fB70\fP of file \fBphysical\&.h\fP\&.
.SS "bool MaxOS::memory::PageTableEntry::global"

.PP
*copydoc \fBPageFlags::GLOBAL\fP 
.PP
Definition at line \fB72\fP of file \fBphysical\&.h\fP\&.
.SS "bool MaxOS::memory::PageTableEntry::huge_page"

.PP
*copydoc \fBPageFlags::HUGE_PAGE\fP 
.PP
Definition at line \fB71\fP of file \fBphysical\&.h\fP\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::physical_address"

.PP
The address the page represents in memory\&. 
.PP
Definition at line \fB74\fP of file \fBphysical\&.h\fP\&.
.SS "bool MaxOS::memory::PageTableEntry::present"

.PP
*copydoc \fBPageFlags::PRESENT\fP 
.PP
Definition at line \fB64\fP of file \fBphysical\&.h\fP\&.
.SS "bool MaxOS::memory::PageTableEntry::user"

.PP
*copydoc \fBPageFlags::USER\fP 
.PP
Definition at line \fB66\fP of file \fBphysical\&.h\fP\&.
.SS "bool MaxOS::memory::PageTableEntry::write"

.PP
*copydoc \fBPageFlags::WRITE\fP 
.PP
Definition at line \fB65\fP of file \fBphysical\&.h\fP\&.
.SS "bool MaxOS::memory::PageTableEntry::write_through"

.PP
*copydoc \fBPageFlags::WRITE_THROUGH\fP 
.PP
Definition at line \fB67\fP of file \fBphysical\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
