.TH "MaxOS::filesystem::partition::MasterBootRecord" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::partition::MasterBootRecord \- Stores information about the master boot record\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msdos\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbootloader\fP [440]"
.br
.RI "The assembly bytes that make up the bootloader software\&. "
.ti -1c
.RI "uint32_t \fBdisk_signature\fP"
.br
.RI "Unique disk signature (optional) "
.ti -1c
.RI "uint16_t \fBunused\fP"
.br
.RI "Reserved (usually zero) "
.ti -1c
.RI "\fBPartitionTableEntry\fP \fBprimary_partition\fP [4]"
.br
.RI "The partition table entries\&. "
.ti -1c
.RI "uint16_t \fBmagic\fP"
.br
.RI "The magic number that identifies this as a valid MBR (0xAA55) "
.in -1c
.SH "Detailed Description"
.PP 
Stores information about the master boot record\&. 
.PP
Definition at line \fB329\fP of file \fBmsdos\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::filesystem::partition::MasterBootRecord::bootloader[440]"

.PP
The assembly bytes that make up the bootloader software\&. 
.PP
Definition at line \fB331\fP of file \fBmsdos\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::partition::MasterBootRecord::disk_signature"

.PP
Unique disk signature (optional) 
.PP
Definition at line \fB332\fP of file \fBmsdos\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::partition::MasterBootRecord::magic"

.PP
The magic number that identifies this as a valid MBR (0xAA55) 
.PP
Definition at line \fB337\fP of file \fBmsdos\&.h\fP\&.
.SS "\fBPartitionTableEntry\fP MaxOS::filesystem::partition::MasterBootRecord::primary_partition[4]"

.PP
The partition table entries\&. 
.PP
Definition at line \fB335\fP of file \fBmsdos\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::partition::MasterBootRecord::unused"

.PP
Reserved (usually zero) 
.PP
Definition at line \fB333\fP of file \fBmsdos\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
