.TH "MaxOS::net::InternetProtocolAddressResolver" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::InternetProtocolAddressResolver
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ipv4\&.h>\fP
.PP
Inherited by \fBMaxOS::net::AddressResolutionProtocol\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInternetProtocolAddressResolver\fP (\fBInternetProtocolHandler\fP *internetProtocolHandler)"
.br
.RI "\fBRESOLVER\fP/// "
.ti -1c
.RI "\fB~InternetProtocolAddressResolver\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBdrivers::ethernet::MediaAccessControlAddress\fP \fBResolve\fP (\fBInternetProtocolAddress\fP \fBaddress\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBStore\fP (\fBInternetProtocolAddress\fP \fBinternetProtocolAddress\fP, \fBdrivers::ethernet::MediaAccessControlAddress\fP \fBmediaAccessControlAddress\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB37\fP of file \fBipv4\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InternetProtocolAddressResolver::InternetProtocolAddressResolver (\fBInternetProtocolHandler\fP * internetProtocolHandler)"

.PP
\fBRESOLVER\fP/// 
.PP
Definition at line \fB18\fP of file \fBipv4\&.cpp\fP\&..PP
.nf
19 {
20 
21     internetProtocolHandler \-> RegisterInternetProtocolAddressResolver(this);
22 
23 }
.fi

.SS "InternetProtocolAddressResolver::~InternetProtocolAddressResolver ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBMediaAccessControlAddress\fP InternetProtocolAddressResolver::Resolve (\fBInternetProtocolAddress\fP address)\fC [virtual]\fP"

.PP
Reimplemented in \fBMaxOS::net::AddressResolutionProtocol\fP\&.
.PP
Definition at line \fB29\fP of file \fBipv4\&.cpp\fP\&..PP
.nf
29                                                                                           {
30     return 0xFFFFFFFFFFFF; // the broadcast address
31 }
.fi

.PP
Referenced by \fBMaxOS::net::InternetProtocolHandler::sendInternetProtocolPacket()\fP\&.
.SS "\fBvoid\fP InternetProtocolAddressResolver::Store (\fBInternetProtocolAddress\fP internetProtocolAddress, \fBdrivers::ethernet::MediaAccessControlAddress\fP mediaAccessControlAddress)\fC [virtual]\fP"

.PP
Reimplemented in \fBMaxOS::net::AddressResolutionProtocol\fP\&.
.PP
Definition at line \fB33\fP of file \fBipv4\&.cpp\fP\&..PP
.nf
33                                                                                               {
34 
35 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
