.TH "MaxOS::processes::Resource" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::processes::Resource \- Represents a generic resource that can be opened, closed, read from and written to\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <resource\&.h>\fP
.PP
Inherited by \fBMaxOS::filesystem::DirectoryResource\fP, \fBMaxOS::filesystem::FileResource\fP, \fBMaxOS::processes::SharedMemory\fP, and \fBMaxOS::processes::SharedMessageEndpoint\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResource\fP (const \fBstring\fP &\fBname\fP, size_t \fBflags\fP, resource_type_t \fBtype\fP)"
.br
.RI "Constructs a new \fBResource\fP object\&. "
.ti -1c
.RI "\fBstring\fP \fBname\fP ()"
.br
.RI "Gets the name of this resource\&. "
.ti -1c
.RI "resource_type_t \fBtype\fP ()"
.br
.RI "Gets the type of this resource\&. "
.ti -1c
.RI "virtual void \fBopen\fP (size_t \fBflags\fP)"
.br
.RI "Opens the resource\&. "
.ti -1c
.RI "virtual void \fBclose\fP (size_t \fBflags\fP)"
.br
.RI "Closes the resource\&. "
.ti -1c
.RI "virtual int \fBread\fP (void *buffer, size_t \fBsize\fP, size_t \fBflags\fP)"
.br
.RI "Read a certain amount of bytes from a resource\&. "
.ti -1c
.RI "virtual int \fBwrite\fP (const void *buffer, size_t \fBsize\fP, size_t \fBflags\fP)"
.br
.RI "Write a certain amount of bytes to a resource\&. "
.in -1c
.SH "Detailed Description"
.PP 
Represents a generic resource that can be opened, closed, read from and written to\&. 
.PP
Definition at line \fB29\fP of file \fBresource\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Resource::Resource (const \fBstring\fP & name, size_t flags, resource_type_t type)"

.PP
Constructs a new \fBResource\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIname\fP The name of the resource 
.br
\fIflags\fP The flags for the resource (unused by default but resource type specific) 
.br
\fItype\fP The type of the resource 
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBresource\&.cpp\fP\&..PP
.nf
22 : m_name(name),
23   m_type(type)
24 {
25 
26 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "void Resource::close (size_t flags)\fC [virtual]\fP"

.PP
Closes the resource\&. 
.PP
\fBParameters\fP
.RS 4
\fIflags\fP Optional flags to pass (unused by default but resource type specific) 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::processes::SharedMemory\fP\&.
.PP
Definition at line \fB45\fP of file \fBresource\&.cpp\fP\&..PP
.nf
45                                  {
46 
47 }
.fi

.PP
Referenced by \fBMaxOS::processes::BaseResourceRegistry::close_resource()\fP\&.
.SS "\fBstring\fP Resource::name ()"

.PP
Gets the name of this resource\&. 
.PP
\fBReturns\fP
.RS 4
The name 
.RE
.PP

.PP
Definition at line \fB79\fP of file \fBresource\&.cpp\fP\&..PP
.nf
79                       {
80     return m_name;
81 }
.fi

.PP
Referenced by \fBMaxOS::processes::BaseResourceRegistry::close_resource()\fP, \fBMaxOS::processes::BaseResourceRegistry::register_resource()\fP, \fBMaxOS::filesystem::FileResource::write()\fP, and \fBMaxOS::filesystem::DirectoryResource::write()\fP\&.
.SS "void Resource::open (size_t flags)\fC [virtual]\fP"

.PP
Opens the resource\&. 
.PP
\fBParameters\fP
.RS 4
\fIflags\fP Optional flags to pass (unused by default but resource type specific) 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::processes::SharedMemory\fP\&.
.PP
Definition at line \fB35\fP of file \fBresource\&.cpp\fP\&..PP
.nf
35                                 {
36 
37 }
.fi

.SS "int Resource::read (void * buffer, size_t size, size_t flags)\fC [virtual]\fP"

.PP
Read a certain amount of bytes from a resource\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The buffer to read into 
.br
\fIsize\fP How many bytes to read 
.br
\fIflags\fP Optional flags to pass (unused by default but resource type specific) 
.RE
.PP
\fBReturns\fP
.RS 4
How many bytes were successfully read (negative can be used as errors) 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::filesystem::FileResource\fP, \fBMaxOS::filesystem::DirectoryResource\fP, \fBMaxOS::processes::SharedMemory\fP, and \fBMaxOS::processes::SharedMessageEndpoint\fP\&.
.PP
Definition at line \fB57\fP of file \fBresource\&.cpp\fP\&..PP
.nf
57                                                           {
58     return 0;
59 }
.fi

.SS "resource_type_t Resource::type ()"

.PP
Gets the type of this resource\&. 
.PP
\fBReturns\fP
.RS 4
The type 
.RE
.PP

.PP
Definition at line \fB88\fP of file \fBresource\&.cpp\fP\&..PP
.nf
88                                {
89 
90     return m_type;
91 }
.fi

.PP
Referenced by \fBMaxOS::processes::ResourceManager::close_resource()\fP\&.
.SS "int Resource::write (const void * buffer, size_t size, size_t flags)\fC [virtual]\fP"

.PP
Write a certain amount of bytes to a resource\&. 
.PP
\fBParameters\fP
.RS 4
\fIbuffer\fP The buffer to read from 
.br
\fIsize\fP How many bytes to write 
.br
\fIflags\fP Optional flags to pass (unused by default but resource type specific) 
.RE
.PP
\fBReturns\fP
.RS 4
How many bytes were successfully written 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::filesystem::FileResource\fP, \fBMaxOS::filesystem::DirectoryResource\fP, and \fBMaxOS::processes::SharedMessageEndpoint\fP\&.
.PP
Definition at line \fB69\fP of file \fBresource\&.cpp\fP\&..PP
.nf
69                                                                  {
70 
71     return 0;
72 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
