.TH "maxOS::system::multiboot_info" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::system::multiboot_info
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmem_lower\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmem_upper\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBboot_device\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBcmdline\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmods_count\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmods_addr\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBmultiboot_aout_symbol_table_t\fP \fBaout_sym\fP"
.br
.ti -1c
.RI "   \fBmultiboot_elf_section_header_table_t\fP \fBelf_sec\fP"
.br
.ti -1c
.RI "} \fBu\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmmap_length\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmmap_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBdrives_length\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBdrives_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBconfig_table\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBboot_loader_name\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBapm_table\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBvbe_control_info\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBvbe_mode_info\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_mode\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_interface_seg\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_interface_off\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_interface_len\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint64_t\fP \fBframebuffer_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBframebuffer_pitch\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBframebuffer_width\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBframebuffer_height\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint8_t\fP \fBframebuffer_bpp\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint8_t\fP \fBframebuffer_type\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBmultiboot_uint32_t\fP \fBframebuffer_palette_addr\fP"
.br
.ti -1c
.RI "      \fBmultiboot_uint16_t\fP \fBframebuffer_palette_num_colors\fP"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "   struct {"
.br
.ti -1c
.RI "      \fBmultiboot_uint8_t\fP \fBframebuffer_red_field_position\fP"
.br
.ti -1c
.RI "      \fBmultiboot_uint8_t\fP \fBframebuffer_red_mask_size\fP"
.br
.ti -1c
.RI "      \fBmultiboot_uint8_t\fP \fBframebuffer_green_field_position\fP"
.br
.ti -1c
.RI "      \fBmultiboot_uint8_t\fP \fBframebuffer_green_mask_size\fP"
.br
.ti -1c
.RI "      \fBmultiboot_uint8_t\fP \fBframebuffer_blue_field_position\fP"
.br
.ti -1c
.RI "      \fBmultiboot_uint8_t\fP \fBframebuffer_blue_mask_size\fP"
.br
.ti -1c
.RI "   } "
.br
.ti -1c
.RI "}; "
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 149 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "union { \&.\&.\&. } "

.SS "\fBmultiboot_aout_symbol_table_t\fP maxOS::system::multiboot_info::aout_sym"

.PP
Definition at line 170 of file multiboot\&.h\&.
.PP
Referenced by maxOS::system::Multiboot::check_flags()\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::apm_table"

.PP
Definition at line 189 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::boot_device"

.PP
Definition at line 159 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::boot_loader_name"

.PP
Definition at line 186 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::cmdline"

.PP
Definition at line 162 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::config_table"

.PP
Definition at line 183 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::drives_addr"

.PP
Definition at line 180 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::drives_length"

.PP
Definition at line 179 of file multiboot\&.h\&.
.SS "\fBmultiboot_elf_section_header_table_t\fP maxOS::system::multiboot_info::elf_sec"

.PP
Definition at line 171 of file multiboot\&.h\&.
.PP
Referenced by maxOS::system::Multiboot::check_flags()\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::flags"

.PP
Definition at line 152 of file multiboot\&.h\&.
.PP
Referenced by maxOS::system::Multiboot::check_flags()\&.
.SS "\fBmultiboot_uint64_t\fP maxOS::system::multiboot_info::framebuffer_addr"

.PP
Definition at line 199 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint8_t\fP maxOS::system::multiboot_info::framebuffer_blue_field_position"

.PP
Definition at line 222 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint8_t\fP maxOS::system::multiboot_info::framebuffer_blue_mask_size"

.PP
Definition at line 223 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint8_t\fP maxOS::system::multiboot_info::framebuffer_bpp"

.PP
Definition at line 203 of file multiboot\&.h\&.
.PP
Referenced by maxOS::drivers::video::VideoElectronicsStandardsAssociation::supports_mode()\&.
.SS "\fBmultiboot_uint8_t\fP maxOS::system::multiboot_info::framebuffer_green_field_position"

.PP
Definition at line 220 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint8_t\fP maxOS::system::multiboot_info::framebuffer_green_mask_size"

.PP
Definition at line 221 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::framebuffer_height"

.PP
Definition at line 202 of file multiboot\&.h\&.
.PP
Referenced by maxOS::drivers::video::VideoElectronicsStandardsAssociation::supports_mode()\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::framebuffer_palette_addr"

.PP
Definition at line 213 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP maxOS::system::multiboot_info::framebuffer_palette_num_colors"

.PP
Definition at line 214 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::framebuffer_pitch"

.PP
Definition at line 200 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint8_t\fP maxOS::system::multiboot_info::framebuffer_red_field_position"

.PP
Definition at line 218 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint8_t\fP maxOS::system::multiboot_info::framebuffer_red_mask_size"

.PP
Definition at line 219 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint8_t\fP maxOS::system::multiboot_info::framebuffer_type"

.PP
Definition at line 208 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::framebuffer_width"

.PP
Definition at line 201 of file multiboot\&.h\&.
.PP
Referenced by maxOS::drivers::video::VideoElectronicsStandardsAssociation::supports_mode()\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::mem_lower"

.PP
Definition at line 155 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::mem_upper"

.PP
Definition at line 156 of file multiboot\&.h\&.
.PP
Referenced by maxOS::memory::MemoryManager::MemoryManager()\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::mmap_addr"

.PP
Definition at line 176 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::mmap_length"

.PP
Definition at line 175 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::mods_addr"

.PP
Definition at line 166 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::mods_count"

.PP
Definition at line 165 of file multiboot\&.h\&.
.SS "union { \&.\&.\&. }  maxOS::system::multiboot_info::u"

.PP
Referenced by maxOS::system::Multiboot::check_flags()\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::vbe_control_info"

.PP
Definition at line 192 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP maxOS::system::multiboot_info::vbe_interface_len"

.PP
Definition at line 197 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP maxOS::system::multiboot_info::vbe_interface_off"

.PP
Definition at line 196 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP maxOS::system::multiboot_info::vbe_interface_seg"

.PP
Definition at line 195 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP maxOS::system::multiboot_info::vbe_mode"

.PP
Definition at line 194 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_info::vbe_mode_info"

.PP
Definition at line 193 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
