.TH "MaxOS::drivers::ethernet::ReceiveDescriptor" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::ethernet::ReceiveDescriptor \- The receive descriptor for the Intel I217 Ethernet Controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <intel_i217\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBbuffer_address\fP"
.br
.RI "The address of the receive buffer\&. "
.ti -1c
.RI "uint16_t \fBlength\fP"
.br
.RI "The length of the received frame\&. "
.ti -1c
.RI "uint16_t \fBchecksum\fP"
.br
.RI "The checksum of the received frame\&. "
.ti -1c
.RI "uint8_t \fBstatus\fP"
.br
.RI "The status of the received frame\&. "
.ti -1c
.RI "uint8_t \fBerrors\fP"
.br
.RI "Any errors that occurred\&. "
.ti -1c
.RI "uint16_t \fBspecial\fP"
.br
.RI "Special\&. "
.in -1c
.SH "Detailed Description"
.PP 
The receive descriptor for the Intel I217 Ethernet Controller\&. 
.PP
Definition at line \fB33\fP of file \fBintel_i217\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::drivers::ethernet::ReceiveDescriptor::buffer_address"

.PP
The address of the receive buffer\&. 
.PP
Definition at line \fB34\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint16_t MaxOS::drivers::ethernet::ReceiveDescriptor::checksum"

.PP
The checksum of the received frame\&. 
.PP
Definition at line \fB36\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint8_t MaxOS::drivers::ethernet::ReceiveDescriptor::errors"

.PP
Any errors that occurred\&. 
.PP
Definition at line \fB38\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint16_t MaxOS::drivers::ethernet::ReceiveDescriptor::length"

.PP
The length of the received frame\&. 
.PP
Definition at line \fB35\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint16_t MaxOS::drivers::ethernet::ReceiveDescriptor::special"

.PP
Special\&. 
.PP
Definition at line \fB39\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint8_t MaxOS::drivers::ethernet::ReceiveDescriptor::status"

.PP
The status of the received frame\&. 
.PP
Definition at line \fB37\fP of file \fBintel_i217\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
