.TH "MaxOS::net::ConnectedEvent" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::ConnectedEvent \- Event for when a TCP socket is connected\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< TCPPayloadHandlerEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConnectedEvent\fP (\fBTCPSocket\fP *\fBsocket\fP)"
.br
.RI "Construct a new connected Event object\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::Event< TCPPayloadHandlerEvents >\fP
.in +1c
.ti -1c
.RI "\fBEvent\fP (TCPPayloadHandlerEvents type)"
.br
.RI "Constructs a new \fBEvent\fP object\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTCPSocket\fP * \fBsocket\fP"
.br
.RI "The socket that is connected\&. "
.in -1c

Public Attributes inherited from \fBMaxOS::common::Event< TCPPayloadHandlerEvents >\fP
.in +1c
.ti -1c
.RI "TCPPayloadHandlerEvents \fBtype\fP"
.br
.ti -1c
.RI "\fBuint8_t\fP * \fBbuffer_value\fP"
.br
.ti -1c
.RI "\fBuint32_t\fP \fBint_value\fP"
.br
.ti -1c
.RI "\fBbool\fP \fBbool_value\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBuint8_t\fP * \fBbuffer_value\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBint_value\fP"
.br
.ti -1c
.RI "   \fBbool\fP \fBbool_value\fP"
.br
.ti -1c
.RI "} \fBreturn_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event for when a TCP socket is connected\&. 
.PP
Definition at line \fB136\fP of file \fBtcp\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "ConnectedEvent::ConnectedEvent (\fBTCPSocket\fP * socket)\fC [explicit]\fP"

.PP
Construct a new connected Event object\&. 
.PP
\fBParameters\fP
.RS 4
\fIsocket\fP The socket that is connected 
.RE
.PP

.PP
Definition at line \fB608\fP of file \fBtcp\&.cpp\fP\&..PP
.nf
609         : Event(TCPPayloadHandlerEvents::CONNECTED) {
610     this\->socket = socket;
611 }
.fi

.PP
References \fBsocket\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTCPSocket\fP* MaxOS::net::ConnectedEvent::socket"

.PP
The socket that is connected\&. 
.PP
Definition at line \fB138\fP of file \fBtcp\&.h\fP\&.
.PP
Referenced by \fBConnectedEvent()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
