.TH "MaxOS::common::InputStream" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::common::InputStream \- A stream that handles strings\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inputStream\&.h>\fP
.PP
Inherits \fBMaxOS::common::GenericInputStream< string >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputStream\fP (\fBInputStreamEventHandler\fP< \fBstring\fP > *)"
.br
.RI "Creates a new \fBInputStream\fP that handles strings\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::GenericInputStream< string >\fP
.in +1c
.ti -1c
.RI "\fBGenericInputStream\fP ()"
.br
.RI "Creates a new \fBGenericInputStream\fP\&. "
.ti -1c
.RI "\fBGenericInputStream\fP (\fBInputStreamEventHandler\fP< \fBstring\fP > *)"
.br
.RI "Creates a new \fBGenericInputStream\fP and connects it to the handler\&. "
.ti -1c
.RI "\fB~GenericInputStream\fP ()"
.br
.RI "Destroys the \fBGenericInputStream\fP and disconnects all handlers\&. "
.ti -1c
.RI "\fBvoid\fP \fBconnect_input_stream_event_handler\fP (\fBInputStreamEventHandler\fP< \fBstring\fP > *)"
.br
.RI "Adds a inputStreamEventHandler to the list of internetProtocolHandlers\&. "
.ti -1c
.RI "\fBvoid\fP \fBdisconnect_input_stream_event_handler\fP (\fBInputStreamEventHandler\fP< \fBstring\fP > *)"
.br
.RI "Removes a handler from the list of handlers\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBMaxOS::common::GenericInputStream< string >\fP
.in +1c
.ti -1c
.RI "\fBcommon::Vector\fP< \fBInputStreamEventHandler\fP< \fBstring\fP > * > \fBm_input_stream_event_handlers\fP"
.br
.RI "List of streams being observed by this handler\&. "
.in -1c
.SH "Detailed Description"
.PP 
A stream that handles strings\&. 
.PP
Definition at line \fB147\fP of file \fBinputStream\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InputStream::InputStream (\fBInputStreamEventHandler\fP< \fBstring\fP > * input_stream_event_handler)"

.PP
Creates a new \fBInputStream\fP that handles strings\&. 
.PP
\fBParameters\fP
.RS 4
\fIinput_stream_event_handler\fP The event handler to handle the data 
.RE
.PP

.PP
Definition at line \fB19\fP of file \fBinputStream\&.cpp\fP\&..PP
.nf
20 : GenericInputStream<string>::GenericInputStream( input_stream_event_handler)
21 {
22 
23 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
