.TH "MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::AdvancedProgrammableInterruptController \- Handles both the Local APIC (boot core) and IO APIC\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <apic\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdvancedProgrammableInterruptController\fP (\fBAdvancedConfigurationAndPowerInterface\fP *acpi)"
.br
.RI "Construct a new Advanced Programmable Interrupt Controller object and initialises the Local APIC and IO APIC, disabling the legacy PIC\&. "
.ti -1c
.RI "\fB~AdvancedProgrammableInterruptController\fP ()"
.br
.RI "Destroy the Advanced Programmable Interrupt Controller object and frees the Local APIC and IO APIC\&. "
.ti -1c
.RI "\fBLocalAPIC\fP * \fBlocal_apic\fP () const"
.br
.RI "Get the local apic\&. "
.ti -1c
.RI "\fBIOAPIC\fP * \fBio_apic\fP () const"
.br
.RI "Get the io apic\&. "
.in -1c
.SH "Detailed Description"
.PP 
Handles both the Local APIC (boot core) and IO APIC\&. 


.PP
\fBTodo\fP
.RS 4
Should either handle all Local APICs or none (only boot core right now, others accessed per core directly which is inconsistent) 
.RE
.PP

.PP
Definition at line \fB228\fP of file \fBapic\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AdvancedProgrammableInterruptController::AdvancedProgrammableInterruptController (\fBAdvancedConfigurationAndPowerInterface\fP * acpi)\fC [explicit]\fP"

.PP
Construct a new Advanced Programmable Interrupt Controller object and initialises the Local APIC and IO APIC, disabling the legacy PIC\&. 
.PP
\fBParameters\fP
.RS 4
\fIacpi\fP The ACPI interface to get the \fBMADT\fP from 
.RE
.PP

.PP
Definition at line \fB415\fP of file \fBapic\&.cpp\fP\&..PP
.nf
416 : m_pic_master_command_port(0x20),
417   m_pic_master_data_port(0x21),
418   m_pic_slave_command_port(0xA0),
419   m_pic_slave_data_port(0xA1)
420 {
421 
422     // Register this APIC
423     Logger::INFO() << "Setting up APIC\\n";
424     InterruptManager::active_interrupt_manager()\->set_apic(this);
425 
426     // Init the Local APIC
427     Logger::DEBUG() << "Initialising Local APIC\\n";
428     m_local_apic = new LocalAPIC();
429 
430     // Disable the legacy mode PIC
431     Logger::DEBUG() << "Disabling PIC\\n";
432     disable_pic();
433 
434     // Init the IO APIC
435     Logger::DEBUG() << "Initialising IO APIC\\n";
436     m_io_apic = new IOAPIC(acpi);
437 }
.fi

.PP
References \fBMaxOS::hardwarecommunication::InterruptManager::active_interrupt_manager()\fP, \fBMaxOS::Logger::DEBUG()\fP, \fBMaxOS::Logger::INFO()\fP, and \fBMaxOS::hardwarecommunication::InterruptManager::set_apic()\fP\&.
.SS "AdvancedProgrammableInterruptController::~AdvancedProgrammableInterruptController ()"

.PP
Destroy the Advanced Programmable Interrupt Controller object and frees the Local APIC and IO APIC\&. 
.PP
Definition at line \fB442\fP of file \fBapic\&.cpp\fP\&..PP
.nf
442                                                                                   {
443 
444     // Free the memory
445     delete m_local_apic;
446     delete m_io_apic;
447 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "\fBIOAPIC\fP * AdvancedProgrammableInterruptController::io_apic () const"

.PP
Get the io apic\&. 
.PP
\fBReturns\fP
.RS 4
The io apic 
.RE
.PP

.PP
Definition at line \fB490\fP of file \fBapic\&.cpp\fP\&..PP
.nf
490                                                                {
491 
492     return m_io_apic;
493 }
.fi

.PP
Referenced by \fBMaxOS::system::CPU::find_cores()\fP\&.
.SS "\fBLocalAPIC\fP * AdvancedProgrammableInterruptController::local_apic () const"

.PP
Get the local apic\&. 
.PP
\fBReturns\fP
.RS 4
The local apic 
.RE
.PP

.PP
Definition at line \fB480\fP of file \fBapic\&.cpp\fP\&..PP
.nf
480                                                                      {
481 
482     return m_local_apic;
483 }
.fi

.PP
Referenced by \fBMaxOS::drivers::clock::Clock::calibrate()\fP, and \fBMaxOS::system::CPU::CPU()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
