.TH "MaxOS::memory::PageMapLevel" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::memory::PageMapLevel
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <physical\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "pte_t \fBentries\fP [512]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 60 of file physical\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "pte_t MaxOS::memory::PageMapLevel::entries[512]"

.PP
Definition at line 61 of file physical\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
