.TH "maxOS::drivers::ethernet::RawDataHandler" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::drivers::ethernet::RawDataHandler \- Handles raw data received from the ethernet controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <rawdatahandler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRawDataHandler\fP ()"
.br
.ti -1c
.RI "\fB~RawDataHandler\fP ()"
.br
.ti -1c
.RI "virtual bool \fBHandleRawData\fP (uint8_t *buffer, uint32_t \fBsize\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles raw data received from the ethernet controller\&. 
.PP
Definition at line 20 of file rawdatahandler\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "RawDataHandler::RawDataHandler ()"

.PP
Definition at line 11 of file rawdatahandler\&.cpp\&.
.PP
.nf
12 {
13 }
.fi
.SS "RawDataHandler::~RawDataHandler ()"

.PP
Definition at line 15 of file rawdatahandler\&.cpp\&.
.PP
.nf
16 {
17 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "bool RawDataHandler::HandleRawData (uint8_t * buffer, uint32_t size)\fC [virtual]\fP"

.PP
Definition at line 19 of file rawdatahandler\&.cpp\&.
.PP
.nf
20 {
21     return false;
22 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
