.TH "MaxOS::gui::Widget" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::gui::Widget \- A graphical object that can be drawn on the screen\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <widget\&.h>\fP
.PP
Inherits \fBMaxOS::drivers::peripherals::KeyboardEventHandler\fP\&.
.PP
Inherited by \fBMaxOS::gui::CompositeWidget\fP, \fBMaxOS::gui::widgets::Button\fP, \fBMaxOS::gui::widgets::InputBox\fP, and \fBMaxOS::gui::widgets::Text\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWidget\fP ()"
.br
.RI "Construct a new \fBWidget\fP object\&. "
.ti -1c
.RI "\fBWidget\fP (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height)"
.br
.RI "Construct a new \fBWidget\fP object at a specific position and size\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdraw\fP (\fBcommon::GraphicsContext\fP *\fBgc\fP, \fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP)"
.br
.RI "Draw the widget on the screen\&. "
.ti -1c
.RI "\fBvoid\fP \fBinvalidate\fP ()"
.br
.RI "Invalidates the entire widget\&. This forces the widget to be redrawn on the next screen update\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBinvalidate\fP (\fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP)"
.br
.RI "Invalidates a specific area of the widget\&. This forces that part of the screen to be redrawn on the next screen update\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBadd_child\fP (\fBWidget\fP *\fBchild\fP)"
.br
.RI "Set the parent of a widget to this widget, making it into a child\&. "
.ti -1c
.RI "\fBvirtual\fP \fBcommon::Coordinates\fP \fBabsolute_coordinates\fP (\fBcommon::Coordinates\fP \fBcoordinates\fP)"
.br
.RI "Get the absolute coordinates of the widget (relative to the screen) "
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBcontains_coordinate\fP (\fBuint32_t\fP x, \fBuint32_t\fP y)"
.br
.RI "Check if the widget contains a specific coordinate\&. "
.ti -1c
.RI "\fBcommon::Rectangle\fP< \fBint32_t\fP > \fBposition\fP ()"
.br
.RI "Get the position of the widget\&. "
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBint32_t\fP left, \fBint32_t\fP top)"
.br
.RI "Set the position of the widget, and invalidate the old and new positions so they are redrawn\&. "
.ti -1c
.RI "\fBvoid\fP \fBresize\fP (\fBint32_t\fP width, \fBint32_t\fP height)"
.br
.RI "Set the size of the widget, and invalidate the old and new positions so they are redrawn\&. "
.ti -1c
.RI "\fBvoid\fP \fBfocus\fP ()"
.br
.RI "Set the current focused widget to be this widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_focus\fP ()"
.br
.RI "Handles the event when the widget is focussed\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_focus_lost\fP ()"
.br
.RI "Handles the event when the widget is unfocused\&. "
.ti -1c
.RI "\fBvoid\fP \fBbring_to_front\fP ()"
.br
.RI "Brings this widget to the front of the screen\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_mouse_enter_widget\fP (\fBuint32_t\fP \fBto_x\fP, \fBuint32_t\fP \fBto_y\fP)"
.br
.RI "Handles the event when the mouse is moved on to the widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_mouse_leave_widget\fP (\fBuint32_t\fP \fBfrom_x\fP, \fBuint32_t\fP \fBfrom_y\fP)"
.br
.RI "Handles the event when the mouse is moved out of the widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_mouse_move_widget\fP (\fBuint32_t\fP \fBfrom_x\fP, \fBuint32_t\fP \fBfrom_y\fP, \fBuint32_t\fP \fBto_x\fP, \fBuint32_t\fP \fBto_y\fP)"
.br
.RI "Handles the event when the mouse is moved over the widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBdrivers::peripherals::MouseEventHandler\fP * \fBon_mouse_button_pressed\fP (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button)"
.br
.RI "Handles the event when the mouse is pressed on the widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_mouse_button_released\fP (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button)"
.br
.RI "Handles the event when the mouse is released on the widget\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::peripherals::KeyboardEventHandler\fP
.in +1c
.ti -1c
.RI "\fBcommon::Event\fP< \fBKeyboardEvents\fP > * \fBon_event\fP (\fBcommon::Event\fP< \fBKeyboardEvents\fP > *) \fBoverride\fP"
.br
.RI "Handle the trigger of an event\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_key_down\fP (\fBKeyCode\fP, \fBconst\fP \fBKeyboardState\fP &)"
.br
.RI "Handle the key down event\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_key_up\fP (\fBKeyCode\fP, \fBconst\fP \fBKeyboardState\fP &)"
.br
.RI "Handle the key up event\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::EventHandler< KeyboardEvents >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBEvent\fP< KeyboardEvents > * \fBon_event\fP (\fBEvent\fP< KeyboardEvents > *\fBevent\fP)"
.br
.RI "This function is called when an event is raised\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBset_focus\fP (\fBWidget\fP *)"
.br
.RI "Sets the widget that is currently focussed\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBbring_to_front\fP (\fBWidget\fP *)"
.br
.RI "Brings a specific widget to the front of the screen\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBcommon::Rectangle\fP< int32_t > \fBm_position\fP"
.br
.RI "The position and size of the widget (relative to its parent) "
.ti -1c
.RI "\fBWidget\fP * \fBm_parent\fP { nullptr }"
.br
.RI "The widget that owns this widget\&. "
.ti -1c
.RI "bool \fBm_valid\fP { false }"
.br
.RI "Is the widget drawn to the screen and up to date\&. "
.ti -1c
.RI "uint32_t \fBm_min_width\fP { 5 }"
.br
.RI "The smallest m_width the widget can be resized to\&. "
.ti -1c
.RI "uint32_t \fBm_min_height\fP { 5 }"
.br
.RI "The smallest m_height the widget can be resized to\&. "
.ti -1c
.RI "uint32_t \fBm_max_width\fP { 0x8FFFFFFF }"
.br
.RI "The largest m_width the widget can be resized to\&. "
.ti -1c
.RI "uint32_t \fBm_max_height\fP { 0x8FFFFFFF }"
.br
.RI "The largest m_height the widget can be resized to\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<int Left, int Top, int Width, int Height> class \fBWidgetMoverResizer\fP"
.br
.ti -1c
.RI "class \fBCompositeWidget\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A graphical object that can be drawn on the screen\&. 
.PP
Definition at line \fB29\fP of file \fBwidget\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Widget::Widget ()"

.PP
Construct a new \fBWidget\fP object\&. 
.PP
Definition at line \fB19\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
20 : KeyboardEventHandler()
21 {
22 
23 }
.fi

.SS "Widget::Widget (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height)"

.PP
Construct a new \fBWidget\fP object at a specific position and size\&. 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP The left position of the widget relative to its parent 
.br
\fItop\fP The top position of the widget relative to its parent 
.br
\fIwidth\fP The width of the widget 
.br
\fIheight\fP The height of the widget 
.RE
.PP

.PP
Definition at line \fB33\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
34 : KeyboardEventHandler(),
35   m_position(left, top, width, height)
36 {
37 
38 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "\fBCoordinates\fP Widget::absolute_coordinates (\fBcommon::Coordinates\fP coordinates)\fC [virtual]\fP"

.PP
Get the absolute coordinates of the widget (relative to the screen) 
.PP
\fBParameters\fP
.RS 4
\fIcoordinates\fP The coordinates within the widget to convert 
.RE
.PP
\fBReturns\fP
.RS 4
The absolute coordinates of the widget 
.RE
.PP

.PP
Definition at line \fB98\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
98                                                                       {
99 
100     // Return the parents absolute coordinates
101     if (m_parent != nullptr)
102         return m_parent\->absolute_coordinates( Coordinates(coordinates\&.first + m_position\&.left, coordinates\&.second + m_position\&.top));
103 
104     // If the widget has no m_parent, return the coordinates of the widget
105     return {coordinates\&.first + m_position\&.left, coordinates\&.second + m_position\&.top};
106 
107 }
.fi

.PP
References \fBabsolute_coordinates()\fP, \fBMaxOS::common::Rectangle< Type >::left\fP, \fBm_parent\fP, \fBm_position\fP, and \fBMaxOS::common::Rectangle< Type >::top\fP\&.
.PP
Referenced by \fBabsolute_coordinates()\fP, \fBMaxOS::gui::widgets::Button::draw()\fP, \fBMaxOS::gui::widgets::InputBox::draw()\fP, \fBMaxOS::gui::widgets::Text::draw()\fP, \fBMaxOS::gui::Window::draw_self()\fP, and \fBinvalidate()\fP\&.
.SS "\fBvoid\fP Widget::add_child (\fBWidget\fP * child)\fC [virtual]\fP"

.PP
Set the parent of a widget to this widget, making it into a child\&. 
.PP
\fBParameters\fP
.RS 4
\fIchild\fP The child to add 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::Desktop\fP, \fBMaxOS::gui::CompositeWidget\fP, and \fBMaxOS::gui::Window\fP\&.
.PP
Definition at line \fB85\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
85                                     {
86 
87     // Parent the child to this widget
88     child\->m_parent = this;
89 
90 }
.fi

.PP
Referenced by \fBMaxOS::gui::CompositeWidget::add_child()\fP\&.
.SS "\fBvoid\fP Widget::bring_to_front ()"

.PP
Brings this widget to the front of the screen\&. 
.PP
Definition at line \fB230\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
230                             {
231 
232     // Bring this widget to the front of the screen
233     bring_to_front(this);
234 }
.fi

.PP
References \fBbring_to_front()\fP\&.
.PP
Referenced by \fBbring_to_front()\fP, \fBon_mouse_button_pressed()\fP, and \fBMaxOS::gui::Window::on_mouse_button_pressed()\fP\&.
.SS "\fBvoid\fP Widget::bring_to_front (\fBWidget\fP * widget)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Brings a specific widget to the front of the screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidget\fP The widget to bring to the front 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::Desktop\fP\&.
.PP
Definition at line \fB241\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
241                                           {
242 
243     // Bring the parent to the front of the screen
244     if (m_parent != nullptr)
245         m_parent\->bring_to_front(widget);
246 
247 }
.fi

.PP
References \fBbring_to_front()\fP, and \fBm_parent\fP\&.
.PP
Referenced by \fBbring_to_front()\fP\&.
.SS "\fBbool\fP Widget::contains_coordinate (\fBuint32_t\fP x, \fBuint32_t\fP y)\fC [virtual]\fP"

.PP
Check if the widget contains a specific coordinate\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The x coordinate 
.br
\fIy\fP The y coordinate 
.RE
.PP
\fBReturns\fP
.RS 4
True if the widget contains the coordinate, false if it does not 
.RE
.PP

.PP
Definition at line \fB116\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
116                                                        {
117 
118     // Check if the coordinates are within the bounds of the widget
119     return m_position\&.contains(x, y);
120 }
.fi

.PP
References \fBMaxOS::common::Rectangle< Type >::contains()\fP, and \fBm_position\fP\&.
.SS "\fBvoid\fP Widget::draw (\fBcommon::GraphicsContext\fP * gc, \fBcommon::Rectangle\fP< \fBint32_t\fP > & area)\fC [virtual]\fP"

.PP
Draw the widget on the screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIgc\fP The graphics context to draw the widgets pixels on 
.br
\fIarea\fP The area of the widget to draw 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::CompositeWidget\fP, \fBMaxOS::gui::widgets::Button\fP, \fBMaxOS::gui::widgets::InputBox\fP, and \fBMaxOS::gui::widgets::Text\fP\&.
.PP
Definition at line \fB48\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
48                                                        {
49 
50 }
.fi

.PP
Referenced by \fBMaxOS::gui::widgets::Button::draw()\fP, \fBMaxOS::gui::widgets::InputBox::draw()\fP, \fBMaxOS::gui::widgets::Text::draw()\fP, and \fBMaxOS::gui::CompositeWidget::draw()\fP\&.
.SS "\fBvoid\fP Widget::focus ()"

.PP
Set the current focused widget to be this widget\&. 
.PP
Definition at line \fB195\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
195                    {
196 
197     // Set the focus the widget to this widget
198     set_focus(this);
199 }
.fi

.PP
References \fBset_focus()\fP\&.
.PP
Referenced by \fBon_mouse_button_pressed()\fP\&.
.SS "\fBvoid\fP Widget::invalidate ()"

.PP
Invalidates the entire widget\&. This forces the widget to be redrawn on the next screen update\&. 
.PP
Definition at line \fB55\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
55                         {
56 
57     // Convert the relative coordinates to absolute coordinates
58     Coordinates coordinates = absolute_coordinates(Coordinates(0, 0));
59 
60     // Create a rectangle with the absolute coordinates and the size of the widget
61     Rectangle<int32_t> invalid_area = Rectangle<int32_t>(coordinates\&.first, coordinates\&.second, m_position\&.width, m_position\&.height);
62 
63     // Invalidate the area
64     invalidate(invalid_area);
65 
66 }
.fi

.PP
References \fBabsolute_coordinates()\fP, \fBMaxOS::common::Rectangle< Type >::height\fP, \fBinvalidate()\fP, \fBm_position\fP, and \fBMaxOS::common::Rectangle< Type >::width\fP\&.
.PP
Referenced by \fBMaxOS::gui::Desktop::Desktop()\fP, \fBMaxOS::gui::Desktop::internal_invalidate()\fP, \fBinvalidate()\fP, \fBinvalidate()\fP, \fBmove()\fP, \fBMaxOS::gui::widgets::InputBox::on_focus()\fP, \fBMaxOS::gui::widgets::InputBox::on_focus_lost()\fP, \fBMaxOS::gui::widgets::InputBox::on_key_down()\fP, \fBMaxOS::gui::widgets::Button::on_mouse_button_pressed()\fP, \fBMaxOS::gui::widgets::Button::on_mouse_button_released()\fP, \fBresize()\fP, \fBMaxOS::gui::widgets::InputBox::update_text()\fP, and \fBMaxOS::gui::widgets::Text::update_text()\fP\&.
.SS "\fBvoid\fP Widget::invalidate (\fBcommon::Rectangle\fP< \fBint32_t\fP > & area)\fC [virtual]\fP"

.PP
Invalidates a specific area of the widget\&. This forces that part of the screen to be redrawn on the next screen update\&. 
.PP
\fBParameters\fP
.RS 4
\fIarea\fP The area of the widget to invalidate 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::Desktop\fP\&.
.PP
Definition at line \fB73\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
73                                                 {
74 
75     // If the widget has a parent, invalidate the area of the parent
76     if (m_parent != nullptr)
77         m_parent\->invalidate(area);
78 }
.fi

.PP
References \fBinvalidate()\fP, and \fBm_parent\fP\&.
.SS "\fBvoid\fP Widget::move (\fBint32_t\fP left, \fBint32_t\fP top)"

.PP
Set the position of the widget, and invalidate the old and new positions so they are redrawn\&. 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP The new left position of the rectangle 
.br
\fItop\fP The new top position of the rectangle 
.RE
.PP

.PP
Definition at line \fB138\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
138                                            {
139 
140     // Invalidate the old position
141     invalidate();
142 
143     // Set the new position
144     m_position\&.left = left;
145     m_position\&.top = top;
146 
147     // Re draw the widget in the new position
148     invalidate();
149 }
.fi

.PP
References \fBinvalidate()\fP, \fBMaxOS::common::Rectangle< Type >::left\fP, \fBm_position\fP, and \fBMaxOS::common::Rectangle< Type >::top\fP\&.
.PP
Referenced by \fBMaxOS::gui::WidgetMoverResizer< Left, Top, Width, Height >::on_mouse_move_event()\fP\&.
.SS "\fBvoid\fP Widget::on_focus ()\fC [virtual]\fP"

.PP
Handles the event when the widget is focussed\&. 
.PP
Reimplemented in \fBMaxOS::gui::widgets::InputBox\fP\&.
.PP
Definition at line \fB216\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
216                       {
217 
218 }
.fi

.PP
Referenced by \fBMaxOS::gui::Desktop::set_focus()\fP\&.
.SS "\fBvoid\fP Widget::on_focus_lost ()\fC [virtual]\fP"

.PP
Handles the event when the widget is unfocused\&. 
.PP
Reimplemented in \fBMaxOS::gui::widgets::InputBox\fP\&.
.PP
Definition at line \fB223\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
223                            {
224 
225 }
.fi

.PP
Referenced by \fBMaxOS::gui::Desktop::set_focus()\fP\&.
.SS "\fBperipherals::MouseEventHandler\fP * Widget::on_mouse_button_pressed (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button)\fC [virtual]\fP"

.PP
Handles the event when the mouse is pressed on the widget\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The x coordinate of the mouse when it was pressed 
.br
\fIy\fP The y coordinate of the mouse when it was pressed 
.br
\fIbutton\fP The button that was pressed 
.RE
.PP
\fBReturns\fP
.RS 4
nullptr 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::CompositeWidget\fP, \fBMaxOS::gui::widgets::Button\fP, and \fBMaxOS::gui::Window\fP\&.
.PP
Definition at line \fB289\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
289                                                                                          {
290 
291     // Bring the widget to the front of the screen
292     bring_to_front();
293 
294     // Focus the widget
295     focus();
296 
297     // Return 0 as the event has been handled
298     return nullptr;
299 }
.fi

.PP
References \fBbring_to_front()\fP, and \fBfocus()\fP\&.
.PP
Referenced by \fBMaxOS::gui::widgets::Button::on_mouse_button_pressed()\fP\&.
.SS "\fBvoid\fP Widget::on_mouse_button_released (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button)\fC [virtual]\fP"

.PP
Handles the event when the mouse is released on the widget\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The x coordinate of the mouse when it was released 
.br
\fIy\fP The y coordinate of the mouse when it was released 
.br
\fIbutton\fP The button that was released 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::CompositeWidget\fP, and \fBMaxOS::gui::widgets::Button\fP\&.
.PP
Definition at line \fB308\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
308                                                                  {
309 
310 }
.fi

.PP
Referenced by \fBMaxOS::gui::widgets::Button::on_mouse_button_released()\fP\&.
.SS "\fBvoid\fP Widget::on_mouse_enter_widget (\fBuint32_t\fP to_x, \fBuint32_t\fP to_y)\fC [virtual]\fP"

.PP
Handles the event when the mouse is moved on to the widget\&. 
.PP
\fBParameters\fP
.RS 4
\fIto_x\fP The x coordinate of the mouse 
.br
\fIto_y\fP The y coordinate of the mouse 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::CompositeWidget\fP\&.
.PP
Definition at line \fB255\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
255                                                                {
256 
257 }
.fi

.SS "\fBvoid\fP Widget::on_mouse_leave_widget (\fBuint32_t\fP from_x, \fBuint32_t\fP from_y)\fC [virtual]\fP"

.PP
Handles the event when the mouse is moved out of the widget\&. 
.PP
\fBParameters\fP
.RS 4
\fIfrom_x\fP The x coordinate of the mouse 
.br
\fIfrom_y\fP The y coordinate of the mouse 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::CompositeWidget\fP\&.
.PP
Definition at line \fB265\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
265                                                                    {
266 
267 }
.fi

.SS "\fBvoid\fP Widget::on_mouse_move_widget (\fBuint32_t\fP from_x, \fBuint32_t\fP from_y, \fBuint32_t\fP to_x, \fBuint32_t\fP to_y)\fC [virtual]\fP"

.PP
Handles the event when the mouse is moved over the widget\&. 
.PP
\fBParameters\fP
.RS 4
\fIfrom_x\fP The x original coordinate of the mouse 
.br
\fIfrom_y\fP The y original coordinate of the mouse 
.br
\fIto_x\fP The x new coordinate of the mouse 
.br
\fIto_y\fP The y new coordinate of the mouse 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::CompositeWidget\fP\&.
.PP
Definition at line \fB277\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
277                                                                                                 {
278 
279 }
.fi

.SS "\fBRectangle\fP< \fBint32_t\fP > Widget::position ()"

.PP
Get the position of the widget\&. 
.PP
\fBReturns\fP
.RS 4
The position of the widget 
.RE
.PP

.PP
Definition at line \fB127\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
127                                     {
128 
129     return m_position;
130 }
.fi

.PP
References \fBm_position\fP\&.
.PP
Referenced by \fBMaxOS::gui::widgets::Button::draw()\fP, \fBMaxOS::gui::widgets::InputBox::draw()\fP, \fBMaxOS::gui::widgets::Text::draw()\fP, \fBMaxOS::gui::CompositeWidget::draw()\fP, \fBMaxOS::gui::Window::draw_self()\fP, \fBMaxOS::gui::Window::on_mouse_button_pressed()\fP, and \fBMaxOS::gui::Desktop::on_mouse_move_event()\fP\&.
.SS "\fBvoid\fP Widget::resize (\fBint32_t\fP width, \fBint32_t\fP height)"

.PP
Set the size of the widget, and invalidate the old and new positions so they are redrawn\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidth\fP The new m_width of the rectangle 
.br
\fIheight\fP The new m_height of the rectangle
.RE
.PP
\fBTodo\fP
.RS 4
Fix the invalidation so it only redraws the areas that need to be redrawn (right and bottom are always fully redrawn currently) 
.RE
.PP

.PP
Definition at line \fB159\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
159                                                  {
160 
161     // Restrict the width and height to the minimum and maximum values
162     if (width < (int) m_min_width) width = m_min_width;
163     if (height < (int) m_min_height) height = m_min_height;
164     if (width > (int) m_max_width) width = m_max_width;
165     if (height > (int) m_max_height) height = m_max_height;
166 
167     // Store the old position, set the new position
168     Rectangle<int32_t> old_position = m_position;
169     m_position\&.width = width;
170     m_position\&.height = height;
171 
172     // Find the areas that need to be redrawn by subtracting the old position from the new position, and vice versa
173     Vector<Rectangle<int32_t>> invalid_areas_old = old_position\&.subtract(m_position);
174     Vector<Rectangle<int32_t>> invalid_areas_new = m_position\&.subtract(old_position);
175 
176     // Right and Bottom require to be fully invalidated
177     if (m_position\&.width > old_position\&.width || m_position\&.height > old_position\&.height ||
178         old_position\&.width > m_position\&.width || old_position\&.height > m_position\&.height) {
179         invalidate();
180         return;
181     }
182 
183     //Loop through the areas that need to be redrawn and invalidate them
184     for (auto& area: invalid_areas_old)
185         invalidate(area);
186 
187     for (auto& area: invalid_areas_new)
188         invalidate(area);
189 
190 }
.fi

.PP
References \fBMaxOS::common::Rectangle< Type >::height\fP, \fBinvalidate()\fP, \fBm_max_height\fP, \fBm_max_width\fP, \fBm_min_height\fP, \fBm_min_width\fP, \fBm_position\fP, \fBMaxOS::common::Rectangle< Type >::subtract()\fP, and \fBMaxOS::common::Rectangle< Type >::width\fP\&.
.PP
Referenced by \fBMaxOS::gui::WidgetMoverResizer< Left, Top, Width, Height >::on_mouse_move_event()\fP\&.
.SS "\fBvoid\fP Widget::set_focus (\fBWidget\fP * widget)\fC [protected]\fP, \fC [virtual]\fP"

.PP
Sets the widget that is currently focussed\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidget\fP The widget to set as focussed 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::gui::Desktop\fP\&.
.PP
Definition at line \fB206\fP of file \fBwidget\&.cpp\fP\&..PP
.nf
206                                      {
207 
208     // Focus the parent to this widget
209     if (m_parent != nullptr)
210         m_parent\->set_focus(widget);
211 }
.fi

.PP
References \fBm_parent\fP, and \fBset_focus()\fP\&.
.PP
Referenced by \fBfocus()\fP, and \fBset_focus()\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBCompositeWidget\fP\fC [friend]\fP"

.PP
Definition at line \fB32\fP of file \fBwidget\&.h\fP\&.
.SS "template<int Left, int Top, int Width, int Height> friend class \fBWidgetMoverResizer\fP\fC [friend]\fP"

.PP
Definition at line \fB30\fP of file \fBwidget\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t MaxOS::gui::Widget::m_max_height { 0x8FFFFFFF }\fC [protected]\fP"

.PP
The largest m_height the widget can be resized to\&. 
.PP
Definition at line \fB44\fP of file \fBwidget\&.h\fP\&..PP
.nf
44 { 0x8FFFFFFF };           
.fi

.PP
Referenced by \fBresize()\fP\&.
.SS "uint32_t MaxOS::gui::Widget::m_max_width { 0x8FFFFFFF }\fC [protected]\fP"

.PP
The largest m_width the widget can be resized to\&. 
.PP
Definition at line \fB43\fP of file \fBwidget\&.h\fP\&..PP
.nf
43 { 0x8FFFFFFF };            
.fi

.PP
Referenced by \fBresize()\fP\&.
.SS "uint32_t MaxOS::gui::Widget::m_min_height { 5 }\fC [protected]\fP"

.PP
The smallest m_height the widget can be resized to\&. 
.PP
Definition at line \fB41\fP of file \fBwidget\&.h\fP\&..PP
.nf
41 { 5 };                    
.fi

.PP
Referenced by \fBresize()\fP, \fBMaxOS::gui::Window::Window()\fP, and \fBMaxOS::gui::Window::Window()\fP\&.
.SS "uint32_t MaxOS::gui::Widget::m_min_width { 5 }\fC [protected]\fP"

.PP
The smallest m_width the widget can be resized to\&. 
.PP
Definition at line \fB40\fP of file \fBwidget\&.h\fP\&..PP
.nf
40 { 5 };                     
.fi

.PP
Referenced by \fBresize()\fP, \fBMaxOS::gui::Window::Window()\fP, and \fBMaxOS::gui::Window::Window()\fP\&.
.SS "\fBWidget\fP* MaxOS::gui::Widget::m_parent { nullptr }\fC [protected]\fP"

.PP
The widget that owns this widget\&. 
.PP
Definition at line \fB37\fP of file \fBwidget\&.h\fP\&..PP
.nf
37 { nullptr };                   
.fi

.PP
Referenced by \fBabsolute_coordinates()\fP, \fBbring_to_front()\fP, \fBinvalidate()\fP, and \fBset_focus()\fP\&.
.SS "\fBcommon::Rectangle\fP<int32_t> MaxOS::gui::Widget::m_position\fC [protected]\fP"

.PP
The position and size of the widget (relative to its parent) 
.PP
Definition at line \fB35\fP of file \fBwidget\&.h\fP\&.
.PP
Referenced by \fBabsolute_coordinates()\fP, \fBcontains_coordinate()\fP, \fBinvalidate()\fP, \fBmove()\fP, \fBMaxOS::gui::WidgetMoverResizer< Left, Top, Width, Height >::on_mouse_move_event()\fP, \fBposition()\fP, and \fBresize()\fP\&.
.SS "bool MaxOS::gui::Widget::m_valid { false }\fC [protected]\fP"

.PP
Is the widget drawn to the screen and up to date\&. 
.PP
Definition at line \fB38\fP of file \fBwidget\&.h\fP\&..PP
.nf
38 { false };                         
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
