.TH "maxOS::drivers::clock" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::drivers::clock
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClock\fP"
.br
.RI "\fBDriver\fP for the CMOS Real Time \fBClock\fP\&. "
.ti -1c
.RI "class \fBClockEventHandler\fP"
.br
.RI "Handles the events triggered by the clock\&. "
.ti -1c
.RI "class \fBTimeEvent\fP"
.br
.RI "Event that is triggered when the clock ticks, holds the current time\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBClockEvents\fP { \fBTIME\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBmaxOS::drivers::clock::ClockEvents\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fITIME \fP\fP
.PP
Definition at line 21 of file clock\&.h\&.
.PP
.nf
21                             {
22                 TIME
23             };
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
