.TH "MaxOS::system::Process" 3 "Sun Oct 13 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system::Process
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <process\&.h>\fP
.SH "Detailed Description"
.PP 
@breif not done 
.PP
Definition at line 20 of file process\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
