.TH "MaxOS::drivers::peripherals::KeyboardDriver" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::peripherals::KeyboardDriver \- \fBDriver\fP for the Keyboard Controller, manages the events and the keyboard state\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyboard\&.h>\fP
.PP
Inherits \fBMaxOS::hardwarecommunication::InterruptHandler\fP, \fBMaxOS::drivers::Driver\fP, and \fBMaxOS::common::GenericInputStream< uint8_t >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyboardDriver\fP ()"
.br
.ti -1c
.RI "\fB~KeyboardDriver\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBhandle_interrupt\fP () \fBfinal\fP"
.br
.RI "deactivate the keyboard driver "
.ti -1c
.RI "\fBvoid\fP \fBactivate\fP () \fBfinal\fP"
.br
.RI "activate the keyboard driver "
.ti -1c
.RI "\fBstring\fP \fBdevice_name\fP () \fBfinal\fP"
.br
.RI "Get the device name\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::hardwarecommunication::InterruptHandler\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP system::cpu_status_t * \fBhandle_interrupt\fP (system::cpu_status_t *\fBstatus\fP)"
.br
.RI "Handles an interrupt and returns the status\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::Driver\fP
.in +1c
.ti -1c
.RI "\fBDriver\fP ()"
.br
.ti -1c
.RI "\fB~Driver\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdeactivate\fP ()"
.br
.RI "deactivate the driver "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBinitialise\fP ()"
.br
.RI "Initialise the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBuint32_t\fP \fBreset\fP ()"
.br
.RI "Reset the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBstring\fP \fBvendor_name\fP ()"
.br
.RI "Get who created the device\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::GenericInputStream< uint8_t >\fP
.in +1c
.ti -1c
.RI "\fBGenericInputStream\fP ()"
.br
.ti -1c
.RI "\fBGenericInputStream\fP (\fBInputStreamEventHandler\fP< \fBuint8_t\fP > *)"
.br
.ti -1c
.RI "\fB~GenericInputStream\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBconnect_input_stream_event_handler\fP (\fBInputStreamEventHandler\fP< \fBuint8_t\fP > *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdisconnect_input_stream_event_handler\fP (\fBInputStreamEventHandler\fP< \fBuint8_t\fP > *)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBhardwarecommunication::Port8Bit\fP \fBm_data_port\fP"
.br
.ti -1c
.RI "\fBhardwarecommunication::Port8Bit\fP \fBm_command_port\fP"
.br
.in -1c

Protected Attributes inherited from \fBMaxOS::hardwarecommunication::InterruptHandler\fP
.in +1c
.ti -1c
.RI "uint8_t \fBm_interrupt_number\fP"
.br
.in -1c

Protected Attributes inherited from \fBMaxOS::common::GenericInputStream< uint8_t >\fP
.in +1c
.ti -1c
.RI "\fBcommon::Vector\fP< \fBInputStreamEventHandler\fP< \fBuint8_t\fP > * > \fBm_input_stream_event_handlers\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::hardwarecommunication::InterruptHandler\fP
.in +1c
.ti -1c
.RI "\fBInterruptHandler\fP (\fBuint8_t\fP interrupt_number, \fBint64_t\fP \fBredirect\fP=\-1, \fBuint64_t\fP \fBredirect_index\fP=0)"
.br
.ti -1c
.RI "\fB~InterruptHandler\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBDriver\fP for the Keyboard Controller, manages the events and the keyboard state\&. 
.PP
Definition at line \fB427\fP of file \fBkeyboard\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KeyboardDriver::KeyboardDriver ()"

.PP
Definition at line \fB60\fP of file \fBkeyboard\&.cpp\fP\&..PP
.nf
61 : InterruptHandler(0x21, 0x1, 0x12),
62   m_data_port(0x60),
63   m_command_port(0x64)
64 {
65 
66 
67 }
.fi

.SS "KeyboardDriver::~KeyboardDriver ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP KeyboardDriver::activate ()\fC [final]\fP, \fC [virtual]\fP"

.PP
activate the keyboard driver 
.PP
Reimplemented from \fBMaxOS::drivers::Driver\fP\&.
.PP
Definition at line \fB74\fP of file \fBkeyboard\&.cpp\fP\&..PP
.nf
74                               {
75 
76     // Wait for user to stop pressing key (this is for the start\-up key e\&.g\&. hold 'F12' for boot menu or hold 'del' for bios )
77     while (m_command_port\&.read() & 0x1)
78         m_data_port\&.read();
79 
80     // Enable keyboard interrupts
81     m_command_port\&.write(0xAE);
82 
83     // Get the current state of the keyboard
84     m_command_port\&.write(0x20);
85     uint8_t status = (m_data_port\&.read() | 1) & ~0x10;
86 
87     // Reset the keyboard
88     m_command_port\&.write(0x60);
89     m_data_port\&.write(status);
90 
91     // Activate the keyboard
92     m_data_port\&.write(0xF4);
93 }
.fi

.PP
References \fBm_command_port\fP, \fBm_data_port\fP, \fBMaxOS::hardwarecommunication::Port8Bit::read()\fP, \fBstatus\fP, and \fBMaxOS::hardwarecommunication::Port8Bit::write()\fP\&.
.SS "\fBstring\fP KeyboardDriver::device_name ()\fC [final]\fP, \fC [virtual]\fP"

.PP
Get the device name\&. 
.PP
\fBReturns\fP
.RS 4
The device name 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::Driver\fP\&.
.PP
Definition at line \fB110\fP of file \fBkeyboard\&.cpp\fP\&..PP
.nf
110                                    {
111     return "Keyboard";
112 }
.fi

.SS "\fBvoid\fP KeyboardDriver::handle_interrupt ()\fC [final]\fP, \fC [virtual]\fP"

.PP
deactivate the keyboard driver 
.PP
Reimplemented from \fBMaxOS::hardwarecommunication::InterruptHandler\fP\&.
.PP
Definition at line \fB98\fP of file \fBkeyboard\&.cpp\fP\&..PP
.nf
98                                       {
99 
100     // Pass the scan code to the m_handlers
101     uint8_t key = m_data_port\&.read();
102     for (auto &handler: m_input_stream_event_handlers)
103         handler\->on_stream_read(key);
104 }
.fi

.PP
References \fBm_data_port\fP, \fBMaxOS::common::GenericInputStream< uint8_t >::m_input_stream_event_handlers\fP, and \fBMaxOS::hardwarecommunication::Port8Bit::read()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBhardwarecommunication::Port8Bit\fP MaxOS::drivers::peripherals::KeyboardDriver::m_command_port\fC [protected]\fP"

.PP
Definition at line \fB431\fP of file \fBkeyboard\&.h\fP\&.
.PP
Referenced by \fBactivate()\fP\&.
.SS "\fBhardwarecommunication::Port8Bit\fP MaxOS::drivers::peripherals::KeyboardDriver::m_data_port\fC [protected]\fP"

.PP
Definition at line \fB430\fP of file \fBkeyboard\&.h\fP\&.
.PP
Referenced by \fBactivate()\fP, and \fBhandle_interrupt()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
