.TH "MaxOS::net::InternetControlMessageProtocol" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::InternetControlMessageProtocol \- Handles ICMP packets\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <icmp\&.h>\fP
.PP
Inherits \fBMaxOS::net::IPV4PayloadHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInternetControlMessageProtocol\fP (\fBInternetProtocolHandler\fP *\fBinternet_protocol_handler\fP, \fBcommon::OutputStream\fP *error_messages)"
.br
.RI "Constructs an \fBInternetControlMessageProtocol\fP handler\&. "
.ti -1c
.RI "\fBbool\fP \fBhandle_internet_protocol_payload\fP (\fBnet::InternetProtocolAddress\fP \fBsrc_ip_be\fP, \fBnet::InternetProtocolAddress\fP \fBdst_ip_be\fP, \fBuint8_t\fP *\fBpayload_data\fP, \fBuint32_t\fP size) \fBfinal\fP"
.br
.RI "Called by the InternetProtocolProvider when a new packet has arrived\&. "
.ti -1c
.RI "\fBvoid\fP \fBrequest_echo_reply\fP (\fBuint32_t\fP \fBip_be\fP)"
.br
.RI "Sends an ICMP echo request to the specified IP address\&. "
.in -1c
.SH "Detailed Description"
.PP 
Handles ICMP packets\&. 
.PP
Definition at line \fB41\fP of file \fBicmp\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InternetControlMessageProtocol::InternetControlMessageProtocol (\fBInternetProtocolHandler\fP * internet_protocol_handler, \fBcommon::OutputStream\fP * error_messages)"

.PP
Constructs an \fBInternetControlMessageProtocol\fP handler\&. 
.PP
\fBParameters\fP
.RS 4
\fIinternet_protocol_handler\fP The Internet protocol handler to use\&. 
.br
\fIerror_messages\fP The output stream to use for error messages\&. 
.RE
.PP

.PP
Definition at line \fB21\fP of file \fBicmp\&.cpp\fP\&..PP
.nf
22 : IPV4PayloadHandler(internet_protocol_handler, 0x01)
23 {
24     this \-> error_messages = error_messages;
25 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP InternetControlMessageProtocol::handle_internet_protocol_payload (\fBnet::InternetProtocolAddress\fP src_ip_be, \fBnet::InternetProtocolAddress\fP dst_ip_be, \fBuint8_t\fP * payload_data, \fBuint32_t\fP size)\fC [final]\fP, \fC [virtual]\fP"

.PP
Called by the InternetProtocolProvider when a new packet has arrived\&. 
.PP
\fBParameters\fP
.RS 4
\fIsrc_ip_be\fP The source IP address of the packet 
.br
\fIdst_ip_be\fP The destination IP address of the packet 
.br
\fIpayload_data\fP The payload of the packet 
.br
\fIsize\fP The size of the payload
.RE
.PP
\fBReturns\fP
.RS 4
True if the packet is to be sent back to the sender, false otherwise
.RE
.PP
\fBTodo\fP
.RS 4
Reply to ping requests 
.PP
Implement the rest of the ICMP messages 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::net::IPV4PayloadHandler\fP\&.
.PP
Definition at line \fB43\fP of file \fBicmp\&.cpp\fP\&..PP
.nf
47 {
48 
49     error_messages \-> write("ICMP received a packet\\n");
50 
51     // Check if the size is at least the size of the header
52     if(size < sizeof(ICMPHeader)){
53         return false;
54     }
55 
56     // Cast the payload to the ICMP header
57     auto* icmp = (ICMPHeader*)payload_data;
58 
59     switch (icmp \-> type) {
60 
61         case 0: // Echo reply
62             break;
63 
64         case 8: // Echo request
65 
66             // Create a response
67             icmp \-> type = 0;                                                                                                                    // Echo reply
68             icmp \-> checksum = 0;                                                                                                                // Reset the checksum
69             icmp \-> checksum = InternetProtocolHandler::checksum((uint16_t*) &icmp, sizeof(ICMPHeader));             // Calculate the checksum
70 
71             return true;    //Send data back
72 
73     }
74 
75     return false;
76 
77 }
.fi

.PP
References \fBMaxOS::net::InternetProtocolHandler::checksum()\fP\&.
.SS "\fBvoid\fP InternetControlMessageProtocol::request_echo_reply (\fBuint32_t\fP ip_be)"

.PP
Sends an ICMP echo request to the specified IP address\&. 
.PP
\fBParameters\fP
.RS 4
\fIip_be\fP The IP address to send the request to 
.RE
.PP

.PP
Definition at line \fB84\fP of file \fBicmp\&.cpp\fP\&..PP
.nf
84                                                                       {
85 
86     error_messages \-> write("ICMP: Sending echo request\\n");
87 
88     ICMPHeader icmp = {};
89     icmp\&.type = 8;                      // Echo request
90     icmp\&.code = 0;                      // Code must be 0
91     icmp\&.checksum = 0;                  // Checksum must be 0 to calculate it
92     icmp\&.data = 0x69420;        // Data
93 
94     icmp\&.checksum = InternetProtocolHandler::checksum((uint16_t*) &icmp, sizeof(ICMPHeader));
95 
96     send(ip_be, (uint8_t*) &icmp, sizeof(ICMPHeader));
97 
98     error_messages \-> write("ICMP: Echo request sent\\n");
99 }
.fi

.PP
References \fBMaxOS::net::InternetProtocolHandler::checksum()\fP, and \fBMaxOS::net::IPV4PayloadHandler::send()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
