.TH "MaxOS::filesystem::partition::PartitionTableEntry" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::partition::PartitionTableEntry \- Stores information about a partition\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <msdos\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbootable\fP"
.br
.ti -1c
.RI "uint8_t \fBstart_head\fP"
.br
.ti -1c
.RI "uint8_t \fBstart_sector\fP: 6"
.br
.ti -1c
.RI "uint16_t \fBstart_cylinder\fP: 10"
.br
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.ti -1c
.RI "uint8_t \fBend_head\fP"
.br
.ti -1c
.RI "uint8_t \fBend_sector\fP: 6"
.br
.ti -1c
.RI "uint16_t \fBend_cylinder\fP: 10"
.br
.ti -1c
.RI "uint32_t \fBstart_LBA\fP"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Stores information about a partition\&. 
.PP
Definition at line \fB302\fP of file \fBmsdos\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::filesystem::partition::PartitionTableEntry::bootable"

.PP
Definition at line \fB304\fP of file \fBmsdos\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::partition::PartitionTableEntry::end_cylinder"

.PP
Definition at line \fB314\fP of file \fBmsdos\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::partition::PartitionTableEntry::end_head"

.PP
Definition at line \fB312\fP of file \fBmsdos\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::partition::PartitionTableEntry::end_sector"

.PP
Definition at line \fB313\fP of file \fBmsdos\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::partition::PartitionTableEntry::length"

.PP
Definition at line \fB317\fP of file \fBmsdos\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::partition::PartitionTableEntry::start_cylinder"

.PP
Definition at line \fB308\fP of file \fBmsdos\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::partition::PartitionTableEntry::start_head"

.PP
Definition at line \fB306\fP of file \fBmsdos\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::partition::PartitionTableEntry::start_LBA"

.PP
Definition at line \fB316\fP of file \fBmsdos\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::partition::PartitionTableEntry::start_sector"

.PP
Definition at line \fB307\fP of file \fBmsdos\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::partition::PartitionTableEntry::type"

.PP
Definition at line \fB310\fP of file \fBmsdos\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
