.TH "MaxOS::common::Event< EventType >" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::common::Event< EventType > \- Used to store information about an event, has a type and a return value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eventHandler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvent\fP (\fBEventType\fP \fBtype\fP)"
.br
.RI "___________________________ Template Implementation ___________________________ "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEventType\fP \fBtype\fP"
.br
.ti -1c
.RI "union {"
.br
.ti -1c
.RI "   \fBuint8_t\fP * \fBbufferValue\fP"
.br
.ti -1c
.RI "   \fBuint32_t\fP \fBintValue\fP"
.br
.ti -1c
.RI "   \fBbool\fP \fBboolValue\fP"
.br
.ti -1c
.RI "} \fBreturn_value\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP \fBEventType\fP>
.br
class MaxOS::common::Event< EventType >"Used to store information about an event, has a type and a return value\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIEventType\fP The type of event 
.RE
.PP
\fBTodo\fP
.RS 4
deprecate, things that should fire events should have their own event firer class and things that connect to it, dont have a class per event 
.PP
events should be made on stack and passed as references not pointers for better perf 
.RE
.PP
\fBDeprecated\fP
.RS 4
Will Remove Soon 
.RE
.PP

.PP
Definition at line \fB32\fP of file \fBeventHandler\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBEventType\fP > \fBMaxOS::common::Event\fP< \fBEventType\fP >::Event (\fBEventType\fP type)"

.PP
___________________________ Template Implementation ___________________________ 
.PP
Definition at line \fB84\fP of file \fBeventHandler\&.h\fP\&..PP
.nf
84                                                                            {
85             this\->type = type;
86         }
.fi

.PP
References \fBtype\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<\fBtypename\fP \fBEventType\fP > \fBbool\fP \fBMaxOS::common::Event\fP< \fBEventType\fP >::boolValue"

.PP
\fBDeprecated\fP
.RS 4
WRS 
.RE
.PP

.PP
Definition at line \fB43\fP of file \fBeventHandler\&.h\fP\&.
.SS "template<\fBtypename\fP \fBEventType\fP > \fBuint8_t\fP* \fBMaxOS::common::Event\fP< \fBEventType\fP >::bufferValue"

.PP
\fBDeprecated\fP
.RS 4
WRS 
.RE
.PP

.PP
Definition at line \fB41\fP of file \fBeventHandler\&.h\fP\&.
.SS "template<\fBtypename\fP \fBEventType\fP > \fBuint32_t\fP \fBMaxOS::common::Event\fP< \fBEventType\fP >::intValue"

.PP
\fBDeprecated\fP
.RS 4
WRS 
.RE
.PP

.PP
Definition at line \fB42\fP of file \fBeventHandler\&.h\fP\&.
.SS "union  { \&.\&.\&. }  \fBMaxOS::common::Event\fP< \fBEventType\fP >::return_value"

.PP
\fBDeprecated\fP
.RS 4
WRS 
.RE
.PP

.SS "template<\fBtypename\fP \fBEventType\fP > \fBEventType\fP \fBMaxOS::common::Event\fP< \fBEventType\fP >::type"

.PP
\fBDeprecated\fP
.RS 4
WRS 
.RE
.PP

.PP
Definition at line \fB38\fP of file \fBeventHandler\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
