.TH "MaxOS::drivers::clock::PIT" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::clock::PIT \- \fBDriver\fP for the Programmable Interval Timer\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clock\&.h>\fP
.PP
Inherits \fBMaxOS::hardwarecommunication::InterruptHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPIT\fP (\fBhardwarecommunication::AdvancedProgrammableInterruptController\fP *apic)"
.br
.RI "Constructor for the \fBPIT\fP class\&. Registers a handler for interrupt 0x22 and initializes ports\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::hardwarecommunication::InterruptHandler\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP system::cpu_status_t * \fBhandle_interrupt\fP (system::cpu_status_t *status)"
.br
.RI "Handles an interrupt and returns the status\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::hardwarecommunication::InterruptHandler\fP
.in +1c
.ti -1c
.RI "\fBInterruptHandler\fP (\fBuint8_t\fP interrupt_number, \fBint64_t\fP \fBredirect\fP=\-1, \fBuint64_t\fP \fBredirect_index\fP=0)"
.br
.RI "Creates a new interrupt handler and registers it with the interrupt manager\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::hardwarecommunication::InterruptHandler\fP
.in +1c
.ti -1c
.RI "uint8_t \fBm_interrupt_number\fP"
.br
.RI "The interrupt number this handler handles\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDriver\fP for the Programmable Interval Timer\&. 
.PP
Definition at line \fB93\fP of file \fBclock\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "PIT::PIT (\fBhardwarecommunication::AdvancedProgrammableInterruptController\fP * apic)"

.PP
Constructor for the \fBPIT\fP class\&. Registers a handler for interrupt 0x22 and initializes ports\&. 
.PP
\fBParameters\fP
.RS 4
\fIapic\fP The APIC controller for the BSP core 
.RE
.PP

.PP
Definition at line \fB216\fP of file \fBclock\&.cpp\fP\&..PP
.nf
217 : InterruptHandler(0x22),
218   m_data_port(0x40),
219   m_command_port(0x43),
220   m_local_apic(apic\->local_apic()),
221   m_io_apic(apic\->io_apic())
222 {
223 
224 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
