.TH "MaxOS::memory::MemIO64Bit" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::memory::MemIO64Bit \- Handles 64 bit memory IO\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memoryIO\&.h>\fP
.PP
Inherits \fBMaxOS::memory::MemIO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemIO64Bit\fP (uintptr_t address)"
.br
.RI "Construct a new Mem IO object for 64 bit reads/writes\&. "
.ti -1c
.RI "virtual void \fBwrite\fP (uint64_t data)"
.br
.RI "Writes data to the memory address\&. "
.ti -1c
.RI "virtual uint64_t \fBread\fP ()"
.br
.RI "Reads data from the memory address\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::memory::MemIO\fP
.in +1c
.ti -1c
.RI "\fBMemIO\fP (uintptr_t address)"
.br
.RI "Construct a new Mem IO object\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::memory::MemIO\fP
.in +1c
.ti -1c
.RI "uintptr_t \fBm_address\fP"
.br
.RI "The memory address to read from / write to\&. "
.in -1c
.SH "Detailed Description"
.PP 
Handles 64 bit memory IO\&. 
.PP
Definition at line \fB75\fP of file \fBmemoryIO\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MemIO64Bit::MemIO64Bit (uintptr_t address)\fC [explicit]\fP"

.PP
Construct a new Mem IO object for 64 bit reads/writes\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddress\fP The memory address to read from / write to 
.RE
.PP

.PP
Definition at line \fB127\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
128 : MemIO(address)
129 {
130 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "uint64_t MemIO64Bit::read ()\fC [virtual]\fP"

.PP
Reads data from the memory address\&. 
.PP
\fBReturns\fP
.RS 4
the data read 
.RE
.PP

.PP
Definition at line \fB149\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
149                           {
150 
151     return *((volatile uint64_t*) (m_address));
152 }
.fi

.PP
References \fBMaxOS::memory::MemIO::m_address\fP\&.
.SS "void MemIO64Bit::write (uint64_t data)\fC [virtual]\fP"

.PP
Writes data to the memory address\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP the data to write 
.RE
.PP

.PP
Definition at line \fB139\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
139                                     {
140 
141     (*((volatile uint64_t*) (m_address))) = (data);
142 }
.fi

.PP
References \fBMaxOS::memory::MemIO::m_address\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
