.TH "MaxOS::gui::widgets::Text" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::gui::widgets::Text \- A box that can be used to display text\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <text\&.h>\fP
.PP
Inherits \fBMaxOS::gui::Widget\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBText\fP (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height, \fBconst\fP \fBstring\fP &text)"
.br
.RI "Construct a new \fBText\fP object at a specific position and size with text\&. "
.ti -1c
.RI "\fBvoid\fP \fBdraw\fP (\fBcommon::GraphicsContext\fP *\fBgc\fP, \fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP) \fBoverride\fP"
.br
.RI "Draw the text on the screen\&. "
.ti -1c
.RI "\fBvoid\fP \fBupdate_text\fP (\fBconst\fP \fBstring\fP &)"
.br
.RI "Update the text of the widget\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::gui::Widget\fP
.in +1c
.ti -1c
.RI "\fBWidget\fP ()"
.br
.RI "Construct a new \fBWidget\fP object\&. "
.ti -1c
.RI "\fBWidget\fP (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height)"
.br
.RI "Construct a new \fBWidget\fP object at a specific position and size\&. "
.ti -1c
.RI "\fBvoid\fP \fBinvalidate\fP ()"
.br
.RI "Invalidates the entire widget\&. This forces the widget to be redrawn on the next screen update\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBinvalidate\fP (\fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP)"
.br
.RI "Invalidates a specific area of the widget\&. This forces that part of the screen to be redrawn on the next screen update\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBadd_child\fP (\fBWidget\fP *\fBchild\fP)"
.br
.RI "Set the parent of a widget to this widget, making it into a child\&. "
.ti -1c
.RI "\fBvirtual\fP \fBcommon::Coordinates\fP \fBabsolute_coordinates\fP (\fBcommon::Coordinates\fP \fBcoordinates\fP)"
.br
.RI "Get the absolute coordinates of the widget (relative to the screen) "
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBcontains_coordinate\fP (\fBuint32_t\fP x, \fBuint32_t\fP y)"
.br
.RI "Check if the widget contains a specific coordinate\&. "
.ti -1c
.RI "\fBcommon::Rectangle\fP< \fBint32_t\fP > \fBposition\fP ()"
.br
.RI "Get the position of the widget\&. "
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBint32_t\fP left, \fBint32_t\fP top)"
.br
.RI "Set the position of the widget, and invalidate the old and new positions so they are redrawn\&. "
.ti -1c
.RI "\fBvoid\fP \fBresize\fP (\fBint32_t\fP width, \fBint32_t\fP height)"
.br
.RI "Set the size of the widget, and invalidate the old and new positions so they are redrawn\&. "
.ti -1c
.RI "\fBvoid\fP \fBfocus\fP ()"
.br
.RI "Set the current focused widget to be this widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_focus\fP ()"
.br
.RI "Handles the event when the widget is focussed\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_focus_lost\fP ()"
.br
.RI "Handles the event when the widget is unfocused\&. "
.ti -1c
.RI "\fBvoid\fP \fBbring_to_front\fP ()"
.br
.RI "Brings this widget to the front of the screen\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_mouse_enter_widget\fP (\fBuint32_t\fP \fBto_x\fP, \fBuint32_t\fP \fBto_y\fP)"
.br
.RI "Handles the event when the mouse is moved on to the widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_mouse_leave_widget\fP (\fBuint32_t\fP \fBfrom_x\fP, \fBuint32_t\fP \fBfrom_y\fP)"
.br
.RI "Handles the event when the mouse is moved out of the widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_mouse_move_widget\fP (\fBuint32_t\fP \fBfrom_x\fP, \fBuint32_t\fP \fBfrom_y\fP, \fBuint32_t\fP \fBto_x\fP, \fBuint32_t\fP \fBto_y\fP)"
.br
.RI "Handles the event when the mouse is moved over the widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBdrivers::peripherals::MouseEventHandler\fP * \fBon_mouse_button_pressed\fP (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button)"
.br
.RI "Handles the event when the mouse is pressed on the widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_mouse_button_released\fP (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button)"
.br
.RI "Handles the event when the mouse is released on the widget\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::peripherals::KeyboardEventHandler\fP
.in +1c
.ti -1c
.RI "\fBcommon::Event\fP< \fBKeyboardEvents\fP > * \fBon_event\fP (\fBcommon::Event\fP< \fBKeyboardEvents\fP > *) \fBoverride\fP"
.br
.RI "Handle the trigger of an event\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_key_down\fP (\fBKeyCode\fP, \fBconst\fP \fBKeyboardState\fP &)"
.br
.RI "Handle the key down event\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_key_up\fP (\fBKeyCode\fP, \fBconst\fP \fBKeyboardState\fP &)"
.br
.RI "Handle the key up event\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::EventHandler< KeyboardEvents >\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBEvent\fP< KeyboardEvents > * \fBon_event\fP (\fBEvent\fP< KeyboardEvents > *\fBevent\fP)"
.br
.RI "This function is called when an event is raised\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBgui::Font\fP \fBfont\fP"
.br
.RI "The font to use for the text\&. "
.ti -1c
.RI "\fBcommon::Colour\fP \fBforeground_colour\fP"
.br
.RI "The colour of the text characters\&. "
.ti -1c
.RI "\fBcommon::Colour\fP \fBbackground_colour\fP"
.br
.RI "The colour to draw behind the text characters\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::gui::Widget\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBset_focus\fP (\fBWidget\fP *)"
.br
.RI "Sets the widget that is currently focussed\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBbring_to_front\fP (\fBWidget\fP *)"
.br
.RI "Brings a specific widget to the front of the screen\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::gui::Widget\fP
.in +1c
.ti -1c
.RI "\fBcommon::Rectangle\fP< int32_t > \fBm_position\fP"
.br
.RI "The position and size of the widget (relative to its parent) "
.ti -1c
.RI "\fBWidget\fP * \fBm_parent\fP { nullptr }"
.br
.RI "The widget that owns this widget\&. "
.ti -1c
.RI "bool \fBm_valid\fP { false }"
.br
.RI "Is the widget drawn to the screen and up to date\&. "
.ti -1c
.RI "uint32_t \fBm_min_width\fP { 5 }"
.br
.RI "The smallest m_width the widget can be resized to\&. "
.ti -1c
.RI "uint32_t \fBm_min_height\fP { 5 }"
.br
.RI "The smallest m_height the widget can be resized to\&. "
.ti -1c
.RI "uint32_t \fBm_max_width\fP { 0x8FFFFFFF }"
.br
.RI "The largest m_width the widget can be resized to\&. "
.ti -1c
.RI "uint32_t \fBm_max_height\fP { 0x8FFFFFFF }"
.br
.RI "The largest m_height the widget can be resized to\&. "
.in -1c
.SH "Detailed Description"
.PP 
A box that can be used to display text\&. 
.PP
Definition at line \fB24\fP of file \fBtext\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Text::Text (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height, \fBconst\fP \fBstring\fP & text)"

.PP
Construct a new \fBText\fP object at a specific position and size with text\&. 
.PP
\fBParameters\fP
.RS 4
\fIleft\fP How many pixels from the left of the parent widget the text is 
.br
\fItop\fP How many pixels from the top of the parent widget the text is 
.br
\fIwidth\fP How many pixels wide the text area is 
.br
\fIheight\fP How many pixels tall the text area is 
.br
\fItext\fP The text to display 
.RE
.PP

.PP
Definition at line \fB26\fP of file \fBtext\&.cpp\fP\&..PP
.nf
27 : Widget(left, top, width, height),
28   font((uint8_t*) AMIGA_FONT),
29   foreground_colour(Colour(0, 0, 0)),
30   background_colour(Colour(255, 255, 255))
31 {
32 
33     // Set the text
34     update_text(text);
35 }
.fi

.PP
References \fBupdate_text()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Text::draw (\fBcommon::GraphicsContext\fP * gc, \fBcommon::Rectangle\fP< \fBint32_t\fP > & area)\fC [override]\fP, \fC [virtual]\fP"

.PP
Draw the text on the screen\&. 
.PP
\fBParameters\fP
.RS 4
\fIgc\fP The graphics context to draw on 
.br
\fIarea\fP The area of the text to draw 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::gui::Widget\fP\&.
.PP
Definition at line \fB45\fP of file \fBtext\&.cpp\fP\&..PP
.nf
45                                                              {
46 
47     // Default Draw Operation
48     Widget::draw(gc, area);
49 
50     // Get the absolute m_position of the text
51     Coordinates textCoordinates = absolute_coordinates(Coordinates(0, 0));
52     Rectangle<int32_t> text_position = position();
53 
54     // Get the x and y m_position of the text
55     int32_t x = textCoordinates\&.first;
56     int32_t y = textCoordinates\&.second;
57 
58     // Draw the background (as the text might not fill the entire area)
59     gc\->fill_rectangle(x + area\&.left, y + area\&.top, x + area\&.left + area\&.width, y + area\&.top + area\&.height, background_colour);
60 
61     // Draw the text
62     this\->font\&.draw_text(x, y, foreground_colour, background_colour, gc, m_widget_text, area);
63 }
.fi

.PP
References \fBMaxOS::gui::Widget::absolute_coordinates()\fP, \fBbackground_colour\fP, \fBMaxOS::gui::Widget::draw()\fP, \fBMaxOS::gui::Font::draw_text()\fP, \fBfont\fP, \fBforeground_colour\fP, \fBMaxOS::common::Rectangle< Type >::height\fP, \fBMaxOS::common::Rectangle< Type >::left\fP, \fBMaxOS::gui::Widget::position()\fP, \fBMaxOS::common::Rectangle< Type >::top\fP, and \fBMaxOS::common::Rectangle< Type >::width\fP\&.
.SS "\fBvoid\fP Text::update_text (\fBconst\fP \fBstring\fP & new_text)"

.PP
Update the text of the widget\&. 
.PP
\fBParameters\fP
.RS 4
\fInew_text\fP The new text to display 
.RE
.PP

.PP
Definition at line \fB69\fP of file \fBtext\&.cpp\fP\&..PP
.nf
69                                              {
70 
71     // Set the text
72     m_widget_text\&.copy(new_text);
73     invalidate();
74 
75 }
.fi

.PP
References \fBMaxOS::gui::Widget::invalidate()\fP\&.
.PP
Referenced by \fBText()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBcommon::Colour\fP MaxOS::gui::widgets::Text::background_colour"

.PP
The colour to draw behind the text characters\&. 
.PP
Definition at line \fB34\fP of file \fBtext\&.h\fP\&.
.PP
Referenced by \fBdraw()\fP, \fBMaxOS::gui::Window::Window()\fP, and \fBMaxOS::gui::Window::Window()\fP\&.
.SS "\fBgui::Font\fP MaxOS::gui::widgets::Text::font"

.PP
The font to use for the text\&. 
.PP
Definition at line \fB31\fP of file \fBtext\&.h\fP\&.
.PP
Referenced by \fBdraw()\fP\&.
.SS "\fBcommon::Colour\fP MaxOS::gui::widgets::Text::foreground_colour"

.PP
The colour of the text characters\&. 
.PP
Definition at line \fB33\fP of file \fBtext\&.h\fP\&.
.PP
Referenced by \fBdraw()\fP, \fBMaxOS::gui::Window::Window()\fP, and \fBMaxOS::gui::Window::Window()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
