.TH "maxOS::hardwarecommunication" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::hardwarecommunication
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBaseAddressRegister\fP"
.br
.RI "Used to store the base address register\&. "
.ti -1c
.RI "struct \fBGateDescriptor\fP"
.br
.RI "Describes a gate in the Interrupt Descriptor Table\&. "
.ti -1c
.RI "struct \fBInterruptDescriptorTablePointer\fP"
.br
.RI "Describes the Interrupt Descriptor Table\&. "
.ti -1c
.RI "class \fBInterruptHandler\fP"
.br
.RI "Handles a certain interrupt number\&. "
.ti -1c
.RI "class \fBInterruptManager\fP"
.br
.RI "Handles all interrupts and passes them to the correct handler\&. "
.ti -1c
.RI "class \fBPeripheralComponentInterconnectController\fP"
.br
.RI "Handles the selecting and loading of drivers for PCI devices\&. "
.ti -1c
.RI "class \fBPeripheralComponentInterconnectDeviceDescriptor\fP"
.br
.RI "Stores information about a PCI device\&. "
.ti -1c
.RI "class \fBPort\fP"
.br
.RI "base class for all ports "
.ti -1c
.RI "class \fBPort16Bit\fP"
.br
.RI "Handles 16 bit ports\&. "
.ti -1c
.RI "class \fBPort32Bit\fP"
.br
.RI "Handles 32 bit ports\&. "
.ti -1c
.RI "class \fBPort8Bit\fP"
.br
.RI "Handles 8 bit ports\&. "
.ti -1c
.RI "class \fBPort8BitSlow\fP"
.br
.RI "Handles 8 bit ports (slow) "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBBaseAddressRegisterType\fP { \fBMemoryMapping\fP = 0, \fBInputOutput\fP = 1 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "struct \fBmaxOS::hardwarecommunication::GateDescriptor\fP \fB__attribute__\fP ((packed))"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBmaxOS::hardwarecommunication::InterruptManager\fP \fB__attribute__\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBmaxOS::hardwarecommunication::BaseAddressRegisterType\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIMemoryMapping \fP\fP
.TP
\fB\fIInputOutput \fP\fP
.PP
Definition at line 20 of file pci\&.h\&.
.PP
.nf
20                                     {        //Used for the last bit of the address register
21             MemoryMapping = 0,
22             InputOutput = 1
23         };
.fi
.SH "Function Documentation"
.PP 
.SS "struct \fBmaxOS::hardwarecommunication::GateDescriptor\fP maxOS::hardwarecommunication::__attribute__ ((packed))"

.SH "Variable Documentation"
.PP 
.SS "struct \fBmaxOS::hardwarecommunication::InterruptDescriptorTablePointer\fP maxOS::hardwarecommunication::__attribute__"

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
