.TH "MaxOS::drivers::Driver" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::Driver \- base class for all drivers, handles the activation, deactivation, initialisation and reset of the driver as well as error messages and identifying the device  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <driver\&.h>\fP
.PP
Inherited by \fBMaxOS::drivers::SerialConsole\fP, \fBMaxOS::drivers::clock::Clock\fP, \fBMaxOS::drivers::console::TextModeConsole\fP, \fBMaxOS::drivers::console::VESABootConsole\fP, \fBMaxOS::drivers::disk::Disk\fP, \fBMaxOS::drivers::disk::IntegratedDriveElectronicsController\fP, \fBMaxOS::drivers::ethernet::EthernetDriver\fP, \fBMaxOS::drivers::peripherals::KeyboardDriver\fP, \fBMaxOS::drivers::peripherals::MouseDriver\fP, and \fBMaxOS::drivers::video::VideoDriver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBactivate\fP ()"
.br
.RI "Activate the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdeactivate\fP ()"
.br
.RI "Deactivate the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBinitialise\fP ()"
.br
.RI "Initialise the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBuint32_t\fP \fBreset\fP ()"
.br
.RI "Reset the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBstring\fP \fBvendor_name\fP ()"
.br
.RI "Get who created the device\&. "
.ti -1c
.RI "\fBvirtual\fP \fBstring\fP \fBdevice_name\fP ()"
.br
.RI "Get the device name of the driver\&. "
.in -1c
.SH "Detailed Description"
.PP 
base class for all drivers, handles the activation, deactivation, initialisation and reset of the driver as well as error messages and identifying the device 
.PP
Definition at line \fB27\fP of file \fBdriver\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Driver::activate ()\fC [virtual]\fP"

.PP
Activate the driver\&. 
.PP
Reimplemented in \fBMaxOS::drivers::disk::IntegratedDriveElectronicsController\fP, \fBMaxOS::drivers::ethernet::AMD_AM79C973\fP, \fBMaxOS::drivers::ethernet::IntelI217\fP, \fBMaxOS::drivers::peripherals::KeyboardDriver\fP, \fBMaxOS::drivers::peripherals::MouseDriver\fP, \fBMaxOS::drivers::clock::Clock\fP, and \fBMaxOS::drivers::disk::Disk\fP\&.
.PP
Definition at line \fB25\fP of file \fBdriver\&.cpp\fP\&..PP
.nf
25                       {
26 
27 }
.fi

.PP
Referenced by \fBMaxOS::drivers::disk::Disk::activate()\fP\&.
.SS "\fBvoid\fP Driver::deactivate ()\fC [virtual]\fP"

.PP
Deactivate the driver\&. 
.PP
Reimplemented in \fBMaxOS::drivers::ethernet::AMD_AM79C973\fP, and \fBMaxOS::drivers::ethernet::IntelI217\fP\&.
.PP
Definition at line \fB32\fP of file \fBdriver\&.cpp\fP\&..PP
.nf
32                         {
33 
34 }
.fi

.PP
Referenced by \fBMaxOS::drivers::ethernet::IntelI217::deactivate()\fP\&.
.SS "\fBstring\fP Driver::device_name ()\fC [virtual]\fP"

.PP
Get the device name of the driver\&. 
.PP
\fBReturns\fP
.RS 4
The device name of the driver 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::drivers::clock::Clock\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment\fP, \fBMaxOS::drivers::disk::IntegratedDriveElectronicsController\fP, \fBMaxOS::drivers::ethernet::AMD_AM79C973\fP, \fBMaxOS::drivers::ethernet::IntelI217\fP, \fBMaxOS::drivers::peripherals::KeyboardDriver\fP, \fBMaxOS::drivers::peripherals::MouseDriver\fP, \fBMaxOS::drivers::video::VideoElectronicsStandardsAssociation\fP, \fBMaxOS::drivers::video::VideoGraphicsArray\fP, and \fBMaxOS::drivers::disk::Disk\fP\&.
.PP
Definition at line \fB66\fP of file \fBdriver\&.cpp\fP\&..PP
.nf
66                            {
67     return "Unknown Driver";
68 }
.fi

.SS "\fBvoid\fP Driver::initialise ()\fC [virtual]\fP"

.PP
Initialise the driver\&. 
.PP
Reimplemented in \fBMaxOS::drivers::disk::IntegratedDriveElectronicsController\fP\&.
.PP
Definition at line \fB39\fP of file \fBdriver\&.cpp\fP\&..PP
.nf
39                         {
40 
41 }
.fi

.SS "\fBuint32_t\fP Driver::reset ()\fC [virtual]\fP"

.PP
Reset the driver\&. 
.PP
\fBReturns\fP
.RS 4
How long in milliseconds it took to reset the driver 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::drivers::ethernet::AMD_AM79C973\fP, and \fBMaxOS::drivers::ethernet::IntelI217\fP\&.
.PP
Definition at line \fB48\fP of file \fBdriver\&.cpp\fP\&..PP
.nf
48                        {
49     return 0;
50 }
.fi

.PP
Referenced by \fBMaxOS::drivers::ethernet::IntelI217::reset()\fP\&.
.SS "\fBstring\fP Driver::vendor_name ()\fC [virtual]\fP"

.PP
Get who created the device\&. 
.PP
\fBReturns\fP
.RS 4
The vendor name of the driver 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::drivers::clock::Clock\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment\fP, \fBMaxOS::drivers::disk::IntegratedDriveElectronicsController\fP, \fBMaxOS::drivers::ethernet::AMD_AM79C973\fP, \fBMaxOS::drivers::ethernet::IntelI217\fP, \fBMaxOS::drivers::video::VideoElectronicsStandardsAssociation\fP, \fBMaxOS::drivers::video::VideoGraphicsArray\fP, and \fBMaxOS::drivers::disk::Disk\fP\&.
.PP
Definition at line \fB57\fP of file \fBdriver\&.cpp\fP\&..PP
.nf
57                            {
58     return "Generic";
59 }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
