.TH "MaxOS::net::DataReceivedEvent" 3 "Mon Jan 29 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::DataReceivedEvent
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <tcp\&.h>\fP
.PP
Inherits \fBMaxOS::common::Event< TransmissionControlProtocolPayloadHandlerEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDataReceivedEvent\fP (\fBTransmissionControlProtocolSocket\fP *\fBsocket\fP, uint8_t *\fBdata\fP, uint16_t \fBsize\fP)"
.br
.RI "___ EVENTS ___ /// "
.ti -1c
.RI "\fB~DataReceivedEvent\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTransmissionControlProtocolSocket\fP * \fBsocket\fP"
.br
.ti -1c
.RI "uint8_t * \fBdata\fP"
.br
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 89 of file tcp\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "DataReceivedEvent::DataReceivedEvent (\fBTransmissionControlProtocolSocket\fP * socket, uint8_t * data, uint16_t size)"

.PP
___ EVENTS ___ /// 
.PP
Definition at line 555 of file tcp\&.cpp\&.
.PP
.nf
556 : Event(DATA_RECEIVED)
557 {
558     this -> socket = socket;
559     this -> data = data;
560     this -> size = size;
561 }
.fi
.PP
References data, size, and socket\&.
.SS "DataReceivedEvent::~DataReceivedEvent ()"

.PP
Definition at line 563 of file tcp\&.cpp\&.
.PP
.nf
564 {
565 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "uint8_t* MaxOS::net::DataReceivedEvent::data"

.PP
Definition at line 93 of file tcp\&.h\&.
.PP
Referenced by DataReceivedEvent()\&.
.SS "uint16_t MaxOS::net::DataReceivedEvent::size"

.PP
Definition at line 94 of file tcp\&.h\&.
.PP
Referenced by DataReceivedEvent()\&.
.SS "\fBTransmissionControlProtocolSocket\fP* MaxOS::net::DataReceivedEvent::socket"

.PP
Definition at line 92 of file tcp\&.h\&.
.PP
Referenced by DataReceivedEvent()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
