.TH "MaxOS::drivers::ethernet::SendDescriptor" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::ethernet::SendDescriptor \- The send descriptor for the Intel I217 Ethernet Controller\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <intel_i217\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBbuffer_address\fP"
.br
.RI "The address of the send buffer\&. "
.ti -1c
.RI "uint16_t \fBlength\fP"
.br
.RI "The length of the send frame\&. "
.ti -1c
.RI "uint8_t \fBcso\fP"
.br
.RI "The checksum offset\&. "
.ti -1c
.RI "uint8_t \fBcmd\fP"
.br
.RI "The command\&. "
.ti -1c
.RI "uint8_t \fBstatus\fP"
.br
.RI "The status\&. "
.ti -1c
.RI "uint8_t \fBcss\fP"
.br
.RI "The checksum start\&. "
.ti -1c
.RI "uint16_t \fBspecial\fP"
.br
.RI "Special\&. "
.in -1c
.SH "Detailed Description"
.PP 
The send descriptor for the Intel I217 Ethernet Controller\&. 
.PP
Definition at line \fB49\fP of file \fBintel_i217\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::drivers::ethernet::SendDescriptor::buffer_address"

.PP
The address of the send buffer\&. 
.PP
Definition at line \fB50\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint8_t MaxOS::drivers::ethernet::SendDescriptor::cmd"

.PP
The command\&. 
.PP
Definition at line \fB53\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint8_t MaxOS::drivers::ethernet::SendDescriptor::cso"

.PP
The checksum offset\&. 
.PP
Definition at line \fB52\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint8_t MaxOS::drivers::ethernet::SendDescriptor::css"

.PP
The checksum start\&. 
.PP
Definition at line \fB55\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint16_t MaxOS::drivers::ethernet::SendDescriptor::length"

.PP
The length of the send frame\&. 
.PP
Definition at line \fB51\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint16_t MaxOS::drivers::ethernet::SendDescriptor::special"

.PP
Special\&. 
.PP
Definition at line \fB56\fP of file \fBintel_i217\&.h\fP\&.
.SS "uint8_t MaxOS::drivers::ethernet::SendDescriptor::status"

.PP
The status\&. 
.PP
Definition at line \fB54\fP of file \fBintel_i217\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
