.TH "MaxOS::drivers::clock::PITCommand" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::clock::PITCommand
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <clock\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbcd_mode\fP: 1"
.br
.ti -1c
.RI "uint8_t \fBoperating_mode\fP: 3"
.br
.ti -1c
.RI "uint8_t \fBaccess_mode\fP: 2"
.br
.ti -1c
.RI "uint8_t \fBchannel\fP: 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB81\fP of file \fBclock\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::drivers::clock::PITCommand::access_mode"

.PP
Definition at line \fB84\fP of file \fBclock\&.h\fP\&.
.SS "uint8_t MaxOS::drivers::clock::PITCommand::bcd_mode"

.PP
Definition at line \fB82\fP of file \fBclock\&.h\fP\&.
.SS "uint8_t MaxOS::drivers::clock::PITCommand::channel"

.PP
Definition at line \fB85\fP of file \fBclock\&.h\fP\&.
.SS "uint8_t MaxOS::drivers::clock::PITCommand::operating_mode"

.PP
Definition at line \fB83\fP of file \fBclock\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
