.TH "MaxOS::hardwarecommunication::RSDPDescriptor" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::RSDPDescriptor \- Root System Description Pointer (RSDP) structure for ACPI 1\&. Ide\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <acpi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBsignature\fP [8]"
.br
.RI "Indicates a valid RSDP structure if it contains 'RSD PTR ' (null-terminated) "
.ti -1c
.RI "uint8_t \fBchecksum\fP"
.br
.RI "This byte added to all bytes in the table must equal zero for the table to be valid\&. "
.ti -1c
.RI "char \fBOEMID\fP [6]"
.br
.RI "A string supplied by the OEM to identify the OEM\&. "
.ti -1c
.RI "uint8_t \fBrevision\fP"
.br
.RI "The version of the ACPI specification that is supported (higher means more features and is backwards compatible) "
.ti -1c
.RI "uint32_t \fBrsdt_address\fP"
.br
.RI "The physical address of the \fBRSDT\fP (\&. "
.in -1c
.SH "Detailed Description"
.PP 
Root System Description Pointer (RSDP) structure for ACPI 1\&. Ide\&. 
.PP
Definition at line \fB27\fP of file \fBacpi\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::hardwarecommunication::RSDPDescriptor::checksum"

.PP
This byte added to all bytes in the table must equal zero for the table to be valid\&. 
.PP
Definition at line \fB29\fP of file \fBacpi\&.h\fP\&.
.SS "char MaxOS::hardwarecommunication::RSDPDescriptor::OEMID[6]"

.PP
A string supplied by the OEM to identify the OEM\&. 
.PP
Definition at line \fB30\fP of file \fBacpi\&.h\fP\&.
.SS "uint8_t MaxOS::hardwarecommunication::RSDPDescriptor::revision"

.PP
The version of the ACPI specification that is supported (higher means more features and is backwards compatible) 
.PP
Definition at line \fB31\fP of file \fBacpi\&.h\fP\&.
.SS "uint32_t MaxOS::hardwarecommunication::RSDPDescriptor::rsdt_address"

.PP
The physical address of the \fBRSDT\fP (\&. 
.PP
\fBDeprecated\fP
.RS 4
in ACPI 2 and above) 
.RE
.PP

.PP
Definition at line \fB32\fP of file \fBacpi\&.h\fP\&.
.SS "char MaxOS::hardwarecommunication::RSDPDescriptor::signature[8]"

.PP
Indicates a valid RSDP structure if it contains 'RSD PTR ' (null-terminated) 
.PP
Definition at line \fB28\fP of file \fBacpi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
