.TH "MaxOS::hardwarecommunication::Override" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::Override
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <apic\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint8_t \fBbus\fP"
.br
.ti -1c
.RI "uint8_t \fBsource\fP"
.br
.ti -1c
.RI "uint32_t \fBglobal_system_interrupt\fP"
.br
.ti -1c
.RI "uint16_t \fBflags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 84 of file apic\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::hardwarecommunication::Override::bus"

.PP
Definition at line 85 of file apic\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::init()\&.
.SS "uint16_t MaxOS::hardwarecommunication::Override::flags"

.PP
Definition at line 88 of file apic\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::init(), and MaxOS::hardwarecommunication::IOAPIC::set_redirect()\&.
.SS "uint32_t MaxOS::hardwarecommunication::Override::global_system_interrupt"

.PP
Definition at line 87 of file apic\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::init()\&.
.SS "uint8_t MaxOS::hardwarecommunication::Override::source"

.PP
Definition at line 86 of file apic\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::init()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
