.TH "MaxOS::net::UserDatagramProtocolHeader" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::UserDatagramProtocolHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <udp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBsourcePort\fP"
.br
.ti -1c
.RI "uint16_t \fBdestinationPort\fP"
.br
.ti -1c
.RI "uint16_t \fBlength\fP"
.br
.ti -1c
.RI "uint16_t \fBchecksum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBudp\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t MaxOS::net::UserDatagramProtocolHeader::checksum"

.PP
Definition at line \fB25\fP of file \fBudp\&.h\fP\&.
.SS "uint16_t MaxOS::net::UserDatagramProtocolHeader::destinationPort"

.PP
Definition at line \fB23\fP of file \fBudp\&.h\fP\&.
.SS "uint16_t MaxOS::net::UserDatagramProtocolHeader::length"

.PP
Definition at line \fB24\fP of file \fBudp\&.h\fP\&.
.SS "uint16_t MaxOS::net::UserDatagramProtocolHeader::sourcePort"

.PP
Definition at line \fB22\fP of file \fBudp\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
