.TH "MaxOS::gui::Desktop" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::gui::Desktop \- The desktop that contains all the windows, handles the drawing of the screen and the mouse on every tick\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <desktop\&.h>\fP
.PP
Inherits \fBMaxOS::gui::CompositeWidget\fP, \fBMaxOS::drivers::peripherals::MouseEventHandler\fP, and \fBMaxOS::drivers::clock::ClockEventHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDesktop\fP (\fBcommon::GraphicsContext\fP *\fBgc\fP)"
.br
.RI "Creates a new desktop with the given graphics context\&. "
.ti -1c
.RI "\fB~Desktop\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBadd_child\fP (\fBWidget\fP *) \fBfinal\fP"
.br
.RI "Adds a child widget to the desktop\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_time\fP (\fBconst\fP \fBcommon::Time\fP &time) \fBfinal\fP"
.br
.RI "Redraws the desktop when a time event occurs\&. "
.ti -1c
.RI "\fBvoid\fP \fBinvalidate\fP (\fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP) \fBfinal\fP"
.br
.RI "Invalidate the given area of the desktop\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_move_event\fP (\fBint8_t\fP x, \fBint8_t\fP y) \fBfinal\fP"
.br
.RI "When the mouse moves on the desktop update the m_position of the mouse and redraw the cursor\&. Pass the event to the widget that the mouse is over\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_down_event\fP (\fBuint8_t\fP button) \fBfinal\fP"
.br
.RI "When the mouse button is pressed pass the event to the widget that the mouse is over\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_up_event\fP (\fBuint8_t\fP button) \fBfinal\fP"
.br
.RI "When the mouse button is released pass the event to the widget that the mouse is over\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_key_down\fP (\fBdrivers::peripherals::KeyCode\fP \fBkeyDownCode\fP, \fBdrivers::peripherals::KeyboardState\fP \fBkeyDownState\fP) \fBfinal\fP"
.br
.RI "When a key is pressed pass the event to the widget that is currently focussed\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_key_up\fP (\fBdrivers::peripherals::KeyCode\fP \fBkeyUpCode\fP, \fBdrivers::peripherals::KeyboardState\fP \fBkeyUpState\fP) \fBfinal\fP"
.br
.RI "When a key is pressed pass the event to the widget that is currently focussed\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::gui::CompositeWidget\fP
.in +1c
.ti -1c
.RI "\fBCompositeWidget\fP ()"
.br
.ti -1c
.RI "\fBCompositeWidget\fP (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height)"
.br
.ti -1c
.RI "\fB~CompositeWidget\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBdraw\fP (\fBcommon::GraphicsContext\fP *\fBgc\fP, \fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP) \fBoverride\fP"
.br
.RI "Draws a section of the widget and its m_children\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_enter_widget\fP (\fBuint32_t\fP \fBtoX\fP, \fBuint32_t\fP \fBtoY\fP) \fBoverride\fP"
.br
.RI "Passes the event to the child that the mouse is over\&. (Event handling should be done by the derived class) "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_leave_widget\fP (\fBuint32_t\fP \fBfromX\fP, \fBuint32_t\fP \fBfromY\fP) \fBoverride\fP"
.br
.RI "Passes the event to the child that the mouse is over\&. (Event handling should be done by the derived class) "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_move_widget\fP (\fBuint32_t\fP \fBfromX\fP, \fBuint32_t\fP \fBfromY\fP, \fBuint32_t\fP \fBtoX\fP, \fBuint32_t\fP \fBtoY\fP) \fBoverride\fP"
.br
.RI "Passes the event to the child that the mouse is over, also generates a leave/enter event for children\&. "
.ti -1c
.RI "\fBdrivers::peripherals::MouseEventHandler\fP * \fBon_mouse_button_pressed\fP (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button) \fBoverride\fP"
.br
.RI "Passes the event to the child that the mouse is over\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_mouse_button_released\fP (\fBuint32_t\fP x, \fBuint32_t\fP y, \fBuint8_t\fP button) \fBoverride\fP"
.br
.RI "Passes the event to the child that the mouse is over\&. (Event handling should be done by the derived class) "
.in -1c

Public Member Functions inherited from \fBMaxOS::gui::Widget\fP
.in +1c
.ti -1c
.RI "\fBWidget\fP ()"
.br
.ti -1c
.RI "\fBWidget\fP (\fBint32_t\fP left, \fBint32_t\fP top, \fBuint32_t\fP width, \fBuint32_t\fP height)"
.br
.ti -1c
.RI "\fB~Widget\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBinvalidate\fP ()"
.br
.RI "Invalidates the entire widget\&. This forces the widget to be redrawn on the next screen update\&. "
.ti -1c
.RI "\fBvirtual\fP \fBcommon::Coordinates\fP \fBabsolute_coordinates\fP (\fBcommon::Coordinates\fP \fBcoordinates\fP)"
.br
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBcontains_coordinate\fP (\fBuint32_t\fP x, \fBuint32_t\fP y)"
.br
.RI "Check if the widget contains a specific coordinate\&. "
.ti -1c
.RI "\fBcommon::Rectangle\fP< \fBint32_t\fP > \fBposition\fP ()"
.br
.RI "Get the position of the widget\&. "
.ti -1c
.RI "\fBvoid\fP \fBmove\fP (\fBint32_t\fP left, \fBint32_t\fP top)"
.br
.RI "Set the position of the widget, and invalidate the old and new positions so they are redrawn\&. "
.ti -1c
.RI "\fBvoid\fP \fBresize\fP (\fBint32_t\fP width, \fBint32_t\fP height)"
.br
.RI "Set the size of the widget, and invalidate the old and new positions so they are redrawn\&. "
.ti -1c
.RI "\fBvoid\fP \fBfocus\fP ()"
.br
.RI "Set the current focused widget to be this widget\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_focus\fP ()"
.br
.RI "Handles the event when the widget is focussed\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBon_focus_lost\fP ()"
.br
.RI "Handles the event when the widget is unfocused\&. "
.ti -1c
.RI "\fBvoid\fP \fBbring_to_front\fP ()"
.br
.RI "Brings this widget to the front of the screen\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::peripherals::KeyboardEventHandler\fP
.in +1c
.ti -1c
.RI "\fBKeyboardEventHandler\fP ()"
.br
.ti -1c
.RI "\fB~KeyboardEventHandler\fP ()"
.br
.ti -1c
.RI "\fBcommon::Event\fP< \fBKeyboardEvents\fP > * \fBon_event\fP (\fBcommon::Event\fP< \fBKeyboardEvents\fP > *) \fBoverride\fP"
.br
.RI "Handle the trigger of an event\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::EventHandler< KeyboardEvents >\fP
.in +1c
.ti -1c
.RI "\fBEventHandler\fP ()"
.br
.ti -1c
.RI "\fB~EventHandler\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBEvent\fP< KeyboardEvents > * \fBon_event\fP (\fBEvent\fP< KeyboardEvents > *\fBevent\fP)"
.br
.RI "This function is called when an event is raised\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::peripherals::MouseEventHandler\fP
.in +1c
.ti -1c
.RI "\fBMouseEventHandler\fP ()"
.br
.ti -1c
.RI "\fB~MouseEventHandler\fP ()"
.br
.ti -1c
.RI "\fBcommon::Event\fP< \fBMouseEvents\fP > * \fBon_event\fP (\fBcommon::Event\fP< \fBMouseEvents\fP > *) \fBoverride\fP"
.br
.RI "Handles the triggered event and calls the appropriate function\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::EventHandler< MouseEvents >\fP
.in +1c
.ti -1c
.RI "\fBEventHandler\fP ()"
.br
.ti -1c
.RI "\fB~EventHandler\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBEvent\fP< MouseEvents > * \fBon_event\fP (\fBEvent\fP< MouseEvents > *\fBevent\fP)"
.br
.RI "This function is called when an event is raised\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::clock::ClockEventHandler\fP
.in +1c
.ti -1c
.RI "\fBClockEventHandler\fP ()"
.br
.ti -1c
.RI "\fB~ClockEventHandler\fP ()"
.br
.ti -1c
.RI "\fBcommon::Event\fP< \fBClockEvents\fP > * \fBon_event\fP (\fBcommon::Event\fP< \fBClockEvents\fP > *\fBevent\fP) \fBoverride\fP"
.br
.RI "Delegates the clock event to the relevant handler\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::EventHandler< ClockEvents >\fP
.in +1c
.ti -1c
.RI "\fBEventHandler\fP ()"
.br
.ti -1c
.RI "\fB~EventHandler\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBEvent\fP< ClockEvents > * \fBon_event\fP (\fBEvent\fP< ClockEvents > *\fBevent\fP)"
.br
.RI "This function is called when an event is raised\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcommon::Colour\fP \fBcolour\fP"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP \fBset_focus\fP (\fBWidget\fP *) \fBfinal\fP"
.br
.RI "Updates the currently focussed widget to be the given widget\&. "
.ti -1c
.RI "\fBvoid\fP \fBbring_to_front\fP (\fBWidget\fP *) \fBfinal\fP"
.br
.RI "Brings the given widget to the front of the desktop\&. "
.ti -1c
.RI "\fBvoid\fP \fBinvert_mouse_cursor\fP ()"
.br
.RI "Draws the mouse cursor at the current mouse m_position by inverting the pixels (mouse is a plus sign) "
.ti -1c
.RI "\fBvoid\fP \fBinternal_invalidate\fP (\fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP, \fBcommon::Vector\fP< \fBcommon::Rectangle\fP< \fBint32_t\fP > >::iterator \fBstart\fP, \fBcommon::Vector\fP< \fBcommon::Rectangle\fP< \fBint32_t\fP > >::iterator \fBstop\fP)"
.br
.RI "Goes through the passed areas and invalidates the areas that are covered by the given area\&. "
.ti -1c
.RI "\fBvoid\fP \fBdraw_self\fP (\fBcommon::GraphicsContext\fP *\fBgc\fP, \fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP) \fBfinal\fP"
.br
.RI "Draws a certain area of the desktop\&. "
.in -1c

Protected Member Functions inherited from \fBMaxOS::gui::CompositeWidget\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBdraw\fP (\fBcommon::GraphicsContext\fP *\fBgc\fP, \fBcommon::Rectangle\fP< \fBint32_t\fP > &\fBarea\fP, \fBcommon::Vector\fP< \fBWidget\fP * >::iterator \fBstart\fP)"
.br
.RI "Draws a section of the widget and the m_children after a specific child\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int32_t \fBm_mouse_x\fP"
.br
.ti -1c
.RI "int32_t \fBm_mouse_y\fP"
.br
.ti -1c
.RI "\fBcommon::GraphicsContext\fP * \fBm_graphics_context\fP"
.br
.ti -1c
.RI "\fBWidget\fP * \fBm_focussed_widget\fP { nullptr }"
.br
.ti -1c
.RI "\fBdrivers::peripherals::MouseEventHandler\fP * \fBm_dragged_widget\fP { nullptr }"
.br
.ti -1c
.RI "\fBcommon::Vector\fP< \fBcommon::Rectangle\fP< int32_t > > \fBm_invalid_areas\fP"
.br
.in -1c

Protected Attributes inherited from \fBMaxOS::gui::CompositeWidget\fP
.in +1c
.ti -1c
.RI "\fBcommon::Vector\fP< \fBWidget\fP * > \fBm_children\fP"
.br
.in -1c

Protected Attributes inherited from \fBMaxOS::gui::Widget\fP
.in +1c
.ti -1c
.RI "\fBWidget\fP * \fBm_parent\fP { nullptr }"
.br
.ti -1c
.RI "bool \fBm_valid\fP { false }"
.br
.ti -1c
.RI "uint32_t \fBm_min_width\fP { 5 }"
.br
.ti -1c
.RI "uint32_t \fBm_min_height\fP { 5 }"
.br
.ti -1c
.RI "uint32_t \fBm_max_width\fP { 0x8FFFFFFF }"
.br
.ti -1c
.RI "uint32_t \fBm_max_height\fP { 0x8FFFFFFF }"
.br
.in -1c
.SH "Detailed Description"
.PP 
The desktop that contains all the windows, handles the drawing of the screen and the mouse on every tick\&. 
.PP
Definition at line \fB22\fP of file \fBdesktop\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Desktop::Desktop (\fBcommon::GraphicsContext\fP * gc)"

.PP
Creates a new desktop with the given graphics context\&. 
.PP
\fBParameters\fP
.RS 4
\fIgc\fP The graphics context to use 
.RE
.PP

.PP
Definition at line \fB17\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
18 : CompositeWidget(0, 0, gc\->width(), gc\->height()),
19   MouseEventHandler(),
20   ClockEventHandler(),
21   m_graphics_context(gc),
22   colour(Colour(0xA8, 0xA8, 0xA8))
23 {
24 
25     // Set the mouse m_position to the center of the screen
26     m_mouse_x = gc\->width() / 2;
27     m_mouse_y = gc\->height() / 2;
28 
29     // Draw the initial mouse cursor
30     invert_mouse_cursor();
31 
32     // Draw the desktop
33     Widget::invalidate();
34 }
.fi

.PP
References \fBMaxOS::common::Rectangle< Type >::height\fP, \fBMaxOS::gui::Widget::invalidate()\fP, \fBinvert_mouse_cursor()\fP, \fBm_mouse_x\fP, \fBm_mouse_y\fP, and \fBMaxOS::common::Rectangle< Type >::width\fP\&.
.SS "Desktop::~Desktop ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Desktop::add_child (\fBWidget\fP * child_widget)\fC [final]\fP, \fC [virtual]\fP"

.PP
Adds a child widget to the desktop\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidget\fP The widget to add 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::gui::CompositeWidget\fP\&.
.PP
Definition at line \fB153\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
153                                             {
154 
155     // Check if the new widget is under the mouse
156     bool underMouse = child_widget\->contains_coordinate(m_mouse_x, m_mouse_y);
157 
158     // If the mouse is over the widget then send a mouse leave event to the child widget as it is no longer under the mouse
159     if (underMouse)
160         CompositeWidget::on_mouse_leave_widget(m_mouse_x, m_mouse_y);
161 
162     // Add the widget to the desktop
163     CompositeWidget::add_child(child_widget);
164 
165     // If the mouse is over the new widget then send a mouse enter event to the child widget
166     if (underMouse)
167         CompositeWidget::on_mouse_enter_widget(m_mouse_x, m_mouse_y);
168 }
.fi

.PP
References \fBMaxOS::gui::CompositeWidget::add_child()\fP, \fBm_mouse_x\fP, \fBm_mouse_y\fP, \fBMaxOS::gui::CompositeWidget::on_mouse_enter_widget()\fP, and \fBMaxOS::gui::CompositeWidget::on_mouse_leave_widget()\fP\&.
.SS "\fBvoid\fP Desktop::bring_to_front (\fBWidget\fP * front_widget)\fC [final]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Brings the given widget to the front of the desktop\&. 
.PP
\fBParameters\fP
.RS 4
\fIfront_widget\fP The widget to bring to the front 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::gui::Widget\fP\&.
.PP
Definition at line \fB59\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
59                                                  {
60 
61     // Remove the widget from where ever it already is
62     m_children\&.erase(front_widget);
63 
64     // Add it back in the front
65     m_children\&.push_front(front_widget);
66 }
.fi

.PP
References \fBMaxOS::gui::CompositeWidget::m_children\fP\&.
.SS "\fBvoid\fP Desktop::draw_self (\fBcommon::GraphicsContext\fP * gc, \fBcommon::Rectangle\fP< \fBint32_t\fP > & area)\fC [final]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Draws a certain area of the desktop\&. 
.PP
\fBParameters\fP
.RS 4
\fIgc\fP The graphics context to draw with 
.br
\fIarea\fP The area to draw 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::gui::CompositeWidget\fP\&.
.PP
Definition at line \fB134\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
134                                                                                  {
135 
136     //TODO: Draw a background image instead
137 
138     // Calculate the rectangle
139     int32_t topCornerX = area\&.left;
140     int32_t topCornerY = area\&.top;
141     int32_t bottomCornerX = area\&.left + area\&.width;
142     int32_t bottomCornerY = area\&.top + area\&.height;
143 
144     // Draw the background, a rectangle the size of the desktop of the given colour
145     gc\->fill_rectangle(topCornerX, topCornerY, bottomCornerX, bottomCornerY, colour);
146 }
.fi

.PP
References \fBcolour\fP, \fBMaxOS::common::Rectangle< Type >::height\fP, \fBMaxOS::common::Rectangle< Type >::left\fP, \fBMaxOS::common::Rectangle< Type >::top\fP, and \fBMaxOS::common::Rectangle< Type >::width\fP\&.
.SS "\fBvoid\fP Desktop::internal_invalidate (\fBcommon::Rectangle\fP< \fBint32_t\fP > & area, \fBcommon::Vector\fP< \fBcommon::Rectangle\fP< \fBint32_t\fP > >::iterator start, \fBcommon::Vector\fP< \fBcommon::Rectangle\fP< \fBint32_t\fP > >::iterator stop)\fC [protected]\fP"

.PP
Goes through the passed areas and invalidates the areas that are covered by the given area\&. 
.PP
\fBParameters\fP
.RS 4
\fIarea\fP The area that is now invalid 
.br
\fIstart\fP The start of the invalid areas 
.br
\fIstop\fP The end of the invalid areas 
.RE
.PP

.PP
Definition at line \fB93\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
94                                                                            {
95 
96     // Loop through the invalid rectangles
97     for (Vector<Rectangle<int32_t>>::iterator invaild_rect = start; invaild_rect != stop; invaild_rect++) {
98 
99         // Check if the area intersects with the invalid rectangle
100         if (!area\&.intersects(*invaild_rect))
101             continue;
102 
103         // Get the parts of the area that are covered by the invalid rectangle
104         Vector<Rectangle<int32_t>> coveredAreas = area\&.subtract(*invaild_rect);
105 
106         // Invalidate the covered areas
107         for (auto& coveredArea: coveredAreas)
108             internal_invalidate(coveredArea, invaild_rect + 1, stop);
109 
110         // The entire area will be invalidated by now
111         return;
112 
113     }
114 
115     // Add the area to the invalid areas, store where it was added
116     Vector<Rectangle<int32_t>>::iterator vectorPosition = m_invalid_areas\&.push_back(area);
117 
118     // If the m_position is the last item then the invalidation buffer is full
119     if (vectorPosition == m_invalid_areas\&.end()) {
120 
121         // Invalidate the entire desktop
122         m_invalid_areas\&.clear();
123         Widget::invalidate();
124 
125     }
126 }
.fi

.PP
References \fBinternal_invalidate()\fP, \fBMaxOS::common::Rectangle< Type >::intersects()\fP, \fBMaxOS::gui::Widget::invalidate()\fP, \fBm_invalid_areas\fP, and \fBMaxOS::common::Rectangle< Type >::subtract()\fP\&.
.PP
Referenced by \fBinternal_invalidate()\fP, and \fBinvalidate()\fP\&.
.SS "\fBvoid\fP Desktop::invalidate (\fBcommon::Rectangle\fP< \fBint32_t\fP > & area)\fC [final]\fP, \fC [virtual]\fP"

.PP
Invalidate the given area of the desktop\&. 
.PP
\fBParameters\fP
.RS 4
\fIarea\fP The area that is now invalid 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::gui::Widget\fP\&.
.PP
Definition at line \fB204\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
204                                                  {
205 
206     // Invalidate the area
207     internal_invalidate(area, m_invalid_areas\&.begin(), m_invalid_areas\&.end());
208 
209 }
.fi

.PP
References \fBinternal_invalidate()\fP, and \fBm_invalid_areas\fP\&.
.SS "\fBvoid\fP Desktop::invert_mouse_cursor ()\fC [protected]\fP"

.PP
Draws the mouse cursor at the current mouse m_position by inverting the pixels (mouse is a plus sign) 
.PP
Definition at line \fB71\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
71                                   {
72 
73     //TODO: Get image drawing going and draw a proper mouse
74 
75     // Draw the horizontal line
76     for (int32_t x = m_mouse_x \- 3; x <= m_mouse_x + 3; ++x) {
77         m_graphics_context\->invert_pixel(x, m_mouse_y);
78     }
79 
80     // Draw the vertical line
81     for (int32_t y = m_mouse_y \- 3; y <= m_mouse_y + 3; ++y) {
82         m_graphics_context\->invert_pixel(m_mouse_x, y);
83     }
84 }
.fi

.PP
References \fBMaxOS::common::GraphicsContext::invert_pixel()\fP, \fBm_graphics_context\fP, \fBm_mouse_x\fP, \fBm_mouse_y\fP, \fBMaxOS::drivers::peripherals::x\fP, and \fBMaxOS::drivers::peripherals::y\fP\&.
.PP
Referenced by \fBDesktop()\fP, \fBon_mouse_move_event()\fP, and \fBon_time()\fP\&.
.SS "\fBvoid\fP Desktop::on_key_down (\fBdrivers::peripherals::KeyCode\fP keyDownCode, \fBdrivers::peripherals::KeyboardState\fP keyDownState)\fC [final]\fP, \fC [virtual]\fP"

.PP
When a key is pressed pass the event to the widget that is currently focussed\&. 
.PP
\fBParameters\fP
.RS 4
\fIkeyDownCode\fP The key that was pressed 
.br
\fIkeyDownState\fP The state of the keyboard 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::peripherals::KeyboardEventHandler\fP\&.
.PP
Definition at line \fB280\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
280                                                                          {
281 
282     // Pass the event to the widget that is  in focus
283     if (m_focussed_widget != nullptr)
284         m_focussed_widget\->on_key_down(keyDownCode, keyDownState);
285 }
.fi

.PP
References \fBm_focussed_widget\fP, and \fBMaxOS::drivers::peripherals::KeyboardEventHandler::on_key_down()\fP\&.
.SS "\fBvoid\fP Desktop::on_key_up (\fBdrivers::peripherals::KeyCode\fP keyUpCode, \fBdrivers::peripherals::KeyboardState\fP keyUpState)\fC [final]\fP, \fC [virtual]\fP"

.PP
When a key is pressed pass the event to the widget that is currently focussed\&. 
.PP
\fBParameters\fP
.RS 4
\fIkeyUpCode\fP The key that was pressed 
.br
\fIkeyUpState\fP The state of the keyboard 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::peripherals::KeyboardEventHandler\fP\&.
.PP
Definition at line \fB292\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
292                                                                    {
293 
294     // Pass the event to the widget that is  in focus
295     if (m_focussed_widget != nullptr)
296         m_focussed_widget\->on_key_up(keyUpCode, keyUpState);
297 }
.fi

.PP
References \fBm_focussed_widget\fP, and \fBMaxOS::drivers::peripherals::KeyboardEventHandler::on_key_up()\fP\&.
.SS "\fBvoid\fP Desktop::on_mouse_down_event (\fBuint8_t\fP button)\fC [final]\fP, \fC [virtual]\fP"

.PP
When the mouse button is pressed pass the event to the widget that the mouse is over\&. 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP The button that was pressed 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::peripherals::MouseEventHandler\fP\&.
.PP
Definition at line \fB255\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
255                                                 {
256 
257     // The widget that handled the event becomes the widget being dragged
258     m_dragged_widget = CompositeWidget::on_mouse_button_pressed(m_mouse_x, m_mouse_y, button);
259 }
.fi

.PP
References \fBm_dragged_widget\fP, \fBm_mouse_x\fP, \fBm_mouse_y\fP, and \fBMaxOS::gui::CompositeWidget::on_mouse_button_pressed()\fP\&.
.SS "\fBvoid\fP Desktop::on_mouse_move_event (\fBint8_t\fP x, \fBint8_t\fP y)\fC [final]\fP, \fC [virtual]\fP"

.PP
When the mouse moves on the desktop update the m_position of the mouse and redraw the cursor\&. Pass the event to the widget that the mouse is over\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The x m_position of the mouse 
.br
\fIy\fP The y m_position of the mouse 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::peripherals::MouseEventHandler\fP\&.
.PP
Definition at line \fB218\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
218                                                     {
219 
220     // Calculate the m_position of the mouse on the desktop
221     Rectangle<int32_t> desktopPosition = position();
222     int32_t newMouseX = m_mouse_x + x;
223     int32_t newMouseY = m_mouse_y + y;
224 
225     // Restrain the mouse to the desktop
226     if (newMouseX < 0) newMouseX = 0;
227     if (newMouseY < 0) newMouseY = 0;
228     if (newMouseX > desktopPosition\&.width) newMouseX = desktopPosition\&.width \- 1;
229     if (newMouseY > desktopPosition\&.height) newMouseY = desktopPosition\&.height \- 1;
230 
231     // Remove the old cursor from the screen as it will be redrawn in the new m_position
232     invert_mouse_cursor();
233 
234     // If a widget is being dragged then pass the event to it
235     if (m_dragged_widget != nullptr)
236         m_dragged_widget\->on_mouse_move_event(newMouseX \- m_mouse_x, newMouseY \- m_mouse_y);
237 
238     // Handle the mouse moving event (pass it to the widget that the mouse is over)
239     CompositeWidget::on_mouse_move_widget(m_mouse_x, m_mouse_y, newMouseX,
240                                           newMouseY);
241 
242     // Update the mouse m_position
243     m_mouse_x = newMouseX;
244     m_mouse_y = newMouseY;
245 
246     // Draw the new cursor
247     invert_mouse_cursor();
248 }
.fi

.PP
References \fBMaxOS::common::Rectangle< Type >::height\fP, \fBinvert_mouse_cursor()\fP, \fBm_dragged_widget\fP, \fBm_mouse_x\fP, \fBm_mouse_y\fP, \fBMaxOS::drivers::peripherals::MouseEventHandler::on_mouse_move_event()\fP, \fBMaxOS::gui::CompositeWidget::on_mouse_move_widget()\fP, \fBMaxOS::gui::Widget::position()\fP, \fBMaxOS::common::Rectangle< Type >::width\fP, \fBMaxOS::drivers::peripherals::x\fP, and \fBMaxOS::drivers::peripherals::y\fP\&.
.SS "\fBvoid\fP Desktop::on_mouse_up_event (\fBuint8_t\fP button)\fC [final]\fP, \fC [virtual]\fP"

.PP
When the mouse button is released pass the event to the widget that the mouse is over\&. 
.PP
\fBParameters\fP
.RS 4
\fIbutton\fP The button that was released 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::peripherals::MouseEventHandler\fP\&.
.PP
Definition at line \fB266\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
266                                               {
267 
268     // Pass the event to the widget
269     CompositeWidget::on_mouse_button_released(m_mouse_x, m_mouse_y, button);
270 
271     // Dragging has stopped
272     m_dragged_widget = nullptr;
273 }
.fi

.PP
References \fBm_dragged_widget\fP, \fBm_mouse_x\fP, \fBm_mouse_y\fP, and \fBMaxOS::gui::CompositeWidget::on_mouse_button_released()\fP\&.
.SS "\fBvoid\fP Desktop::on_time (\fBconst\fP \fBcommon::Time\fP & time)\fC [final]\fP, \fC [virtual]\fP"

.PP
Redraws the desktop when a time event occurs\&. 
.PP
\fBParameters\fP
.RS 4
\fItime\fP The time when the event occurred 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::clock::ClockEventHandler\fP\&.
.PP
Definition at line \fB175\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
175                                        {
176 
177     // Check if anything is invalid and needs to be redrawn
178     if (m_invalid_areas\&.empty())
179         return;
180 
181     // Erase the mouse cursor
182     invert_mouse_cursor();
183 
184     // Loop through the invalid areas
185     while (!m_invalid_areas\&.empty()) {
186 
187         // Redraw the m_first_memory_chunk area
188         Rectangle<int32_t> invalidArea = *(m_invalid_areas\&.begin());
189         m_invalid_areas\&.pop_front();
190         draw(m_graphics_context, invalidArea);
191 
192     }
193 
194     // Can now draw the mouse cursor
195     invert_mouse_cursor();
196 
197 }
.fi

.PP
References \fBMaxOS::gui::CompositeWidget::draw()\fP, \fBinvert_mouse_cursor()\fP, \fBm_graphics_context\fP, and \fBm_invalid_areas\fP\&.
.SS "\fBvoid\fP Desktop::set_focus (\fBWidget\fP * widget)\fC [final]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Updates the currently focussed widget to be the given widget\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidget\fP The widget that is now in focus 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::gui::Widget\fP\&.
.PP
Definition at line \fB43\fP of file \fBdesktop\&.cpp\fP\&..PP
.nf
43                                       {
44 
45     // If there is a widget in focus then send a focus lost event to it
46     if (this\->m_focussed_widget != nullptr)
47         this\->m_focussed_widget\->on_focus_lost();
48 
49     // Focus the new widget and send a focus event to it
50     this\->m_focussed_widget = widget;
51     this\->m_focussed_widget\->on_focus();
52 }
.fi

.PP
References \fBm_focussed_widget\fP, \fBMaxOS::gui::Widget::on_focus()\fP, and \fBMaxOS::gui::Widget::on_focus_lost()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBcommon::Colour\fP MaxOS::gui::Desktop::colour"

.PP
Definition at line \fB42\fP of file \fBdesktop\&.h\fP\&.
.PP
Referenced by \fBdraw_self()\fP\&.
.SS "\fBdrivers::peripherals::MouseEventHandler\fP* MaxOS::gui::Desktop::m_dragged_widget { nullptr }\fC [protected]\fP"

.PP
Definition at line \fB31\fP of file \fBdesktop\&.h\fP\&..PP
.nf
31 { nullptr };
.fi

.PP
Referenced by \fBon_mouse_down_event()\fP, \fBon_mouse_move_event()\fP, and \fBon_mouse_up_event()\fP\&.
.SS "\fBWidget\fP* MaxOS::gui::Desktop::m_focussed_widget { nullptr }\fC [protected]\fP"

.PP
Definition at line \fB30\fP of file \fBdesktop\&.h\fP\&..PP
.nf
30 { nullptr };
.fi

.PP
Referenced by \fBon_key_down()\fP, \fBon_key_up()\fP, and \fBset_focus()\fP\&.
.SS "\fBcommon::GraphicsContext\fP* MaxOS::gui::Desktop::m_graphics_context\fC [protected]\fP"

.PP
Definition at line \fB28\fP of file \fBdesktop\&.h\fP\&.
.PP
Referenced by \fBinvert_mouse_cursor()\fP, and \fBon_time()\fP\&.
.SS "\fBcommon::Vector\fP<\fBcommon::Rectangle\fP<int32_t> > MaxOS::gui::Desktop::m_invalid_areas\fC [protected]\fP"

.PP
Definition at line \fB37\fP of file \fBdesktop\&.h\fP\&.
.PP
Referenced by \fBinternal_invalidate()\fP, \fBinvalidate()\fP, and \fBon_time()\fP\&.
.SS "int32_t MaxOS::gui::Desktop::m_mouse_x\fC [protected]\fP"

.PP
Definition at line \fB25\fP of file \fBdesktop\&.h\fP\&.
.PP
Referenced by \fBadd_child()\fP, \fBDesktop()\fP, \fBinvert_mouse_cursor()\fP, \fBon_mouse_down_event()\fP, \fBon_mouse_move_event()\fP, and \fBon_mouse_up_event()\fP\&.
.SS "int32_t MaxOS::gui::Desktop::m_mouse_y\fC [protected]\fP"

.PP
Definition at line \fB26\fP of file \fBdesktop\&.h\fP\&.
.PP
Referenced by \fBadd_child()\fP, \fBDesktop()\fP, \fBinvert_mouse_cursor()\fP, \fBon_mouse_down_event()\fP, \fBon_mouse_move_event()\fP, and \fBon_mouse_up_event()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
