.TH "MaxOS::memory" 3 "Mon Jan 29 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::memory
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMemIO\fP"
.br
.RI "base class for all memory IO "
.ti -1c
.RI "class \fBMemIO16Bit\fP"
.br
.RI "Handles 16 bit memory IO\&. "
.ti -1c
.RI "class \fBMemIO32Bit\fP"
.br
.RI "Handles 32 bit memory IO\&. "
.ti -1c
.RI "class \fBMemIO64Bit\fP"
.br
.RI "Handles 64 bit memory IO\&. "
.ti -1c
.RI "class \fBMemIO8Bit\fP"
.br
.RI "Handles 8 bit memory IO\&. "
.ti -1c
.RI "struct \fBMemoryChunk\fP"
.br
.RI "Stores information about a memory chunk in the memory manager linked list\&. "
.ti -1c
.RI "class \fBMemoryManager\fP"
.br
.RI "Handles memory allocation and deallocation\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
