.TH "MaxOS::system::GDTR" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system::GDTR \- A struct used to store information for the GDT Register\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gdt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBlimit\fP"
.br
.ti -1c
.RI "uint64_t \fBaddress\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
A struct used to store information for the GDT Register\&. 
.PP
Definition at line 19 of file gdt\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::system::GDTR::address"

.PP
Definition at line 21 of file gdt\&.h\&.
.SS "uint16_t MaxOS::system::GDTR::limit"

.PP
Definition at line 20 of file gdt\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
