.TH "MaxOS::system::GDTRegister" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system::GDTRegister \- How the \fBCPU\fP stores the GDT\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gdt\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.RI "The size of the GDT\&. "
.ti -1c
.RI "uint64_t \fBaddress\fP"
.br
.RI "The address of the GDT\&. "
.in -1c
.SH "Detailed Description"
.PP 
How the \fBCPU\fP stores the GDT\&. 
.PP
Definition at line \fB42\fP of file \fBgdt\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::system::GDTRegister::address"

.PP
The address of the GDT\&. 
.PP
Definition at line \fB45\fP of file \fBgdt\&.h\fP\&.
.SS "uint16_t MaxOS::system::GDTRegister::size"

.PP
The size of the GDT\&. 
.PP
Definition at line \fB44\fP of file \fBgdt\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
