.TH "maxOS::system::multiboot_aout_symbol_table" 3 "Mon Jan 8 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::system::multiboot_aout_symbol_table
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBtabsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBstrsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBaddr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBreserved\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 130 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_aout_symbol_table::addr"

.PP
Definition at line 134 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_aout_symbol_table::reserved"

.PP
Definition at line 135 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_aout_symbol_table::strsize"

.PP
Definition at line 133 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_aout_symbol_table::tabsize"

.PP
Definition at line 132 of file multiboot\&.h\&.
.PP
Referenced by maxOS::system::Multiboot::check_flags()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
