.TH "MaxOS::system::GlobalDescriptorTable" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system::GlobalDescriptorTable \- Sets up the GDT in the \fBCPU\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <gdt\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGlobalDescriptorTable\fP ()"
.br
.ti -1c
.RI "\fB~GlobalDescriptorTable\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBtable\fP [7]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Sets up the GDT in the \fBCPU\fP\&. 
.PP
Definition at line \fB43\fP of file \fBgdt\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "GlobalDescriptorTable::GlobalDescriptorTable ()"

.PP
Definition at line \fB11\fP of file \fBgdt\&.cpp\fP\&..PP
.nf
12 {
13 
14     Logger::INFO() << "Setting up Global Descriptor Table\\n";
15 
16     // Null descriptor
17     table[0] = 0;
18 
19     // Kernel Code Segment descriptor
20     uint64_t kernel_cs = 0;
21     kernel_cs |= (uint64_t) DescriptorFlags::Write;
22     kernel_cs |= (uint64_t) DescriptorFlags::Execute;
23     kernel_cs |= (uint64_t) DescriptorFlags::CodeOrDataSegment;
24     kernel_cs |= (uint64_t) DescriptorFlags::Present;
25     kernel_cs |= (uint64_t) DescriptorFlags::LongMode;
26     table[1] = kernel_cs;
27 
28     // Kernel Data Segment descriptor
29     uint64_t kernel_ds = 0;
30     kernel_ds |= (uint64_t) DescriptorFlags::Write;
31     kernel_ds |= (uint64_t) DescriptorFlags::CodeOrDataSegment;
32     kernel_ds |= (uint64_t) DescriptorFlags::Present;
33     table[2] = kernel_ds;
34 
35     // User code segment descriptor (Change the privilege level to 3)
36     uint64_t user_cs = 0;
37     user_cs |= (uint64_t) DescriptorFlags::Write;
38     user_cs |= (uint64_t) DescriptorFlags::Execute;
39     user_cs |= (uint64_t) DescriptorFlags::CodeOrDataSegment;
40     user_cs |= (uint64_t) DescriptorFlags::Present;
41     user_cs |= (uint64_t) DescriptorFlags::LongMode;
42     user_cs |= (3ULL << 45);
43     table[3] = user_cs;
44 
45     // User data segment descriptor (Change the privilege level to 3)
46     uint64_t user_ds = 0;
47     user_ds |= (uint64_t) DescriptorFlags::Write;
48     user_ds |= (uint64_t) DescriptorFlags::CodeOrDataSegment;
49     user_ds |= (uint64_t) DescriptorFlags::Present;
50     user_ds |= (3ULL << 45);
51     table[4] = user_ds;
52 
53     // Reserve space for the TSS
54     table[5] = 0;
55     table[6] = 0;
56 
57     Logger::DEBUG() << "Created GDT entries\\n";
58 
59     // Load the GDT
60     gdtr_t gdtr = {
61             \&.size    = sizeof(table) \- 1,
62             \&.address = (uint64_t) table,
63     };
64     asm volatile("lgdt %0" : : "m"(gdtr));
65     Logger::DEBUG() << "Loaded GDT of limit 0x" << (uint64_t) gdtr\&.size << " and address 0x" << (uint64_t) gdtr\&.address << "\\n";
66 
67     // Reload the segment registers
68     asm volatile("mov %0, %%ds" : : "r"(0x10));
69     asm volatile("mov %0, %%es" : : "r"(0x10));
70     asm volatile("mov %0, %%fs" : : "r"(0x10));
71     asm volatile("mov %0, %%gs" : : "r"(0x10));
72     asm volatile("mov %0, %%ss" : : "r"(0x10));
73     Logger::DEBUG() << "Reloaded segment registers\\n";
74 }
.fi

.PP
References \fBaddress\fP, \fBMaxOS::system::CodeOrDataSegment\fP, \fBLogger::DEBUG()\fP, \fBMaxOS::system::Execute\fP, \fBLogger::INFO()\fP, \fBMaxOS::system::LongMode\fP, \fBMaxOS::system::Present\fP, \fBtable\fP, and \fBMaxOS::system::Write\fP\&.
.SS "GlobalDescriptorTable::~GlobalDescriptorTable ()\fC [default]\fP"

.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::system::GlobalDescriptorTable::table[7]"

.PP
Definition at line \fB49\fP of file \fBgdt\&.h\fP\&.
.PP
Referenced by \fBGlobalDescriptorTable()\fP, and \fBMaxOS::system::CPU::init_tss()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
