.TH "MaxOS::common::InputStreamBuffer< Type >" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::common::InputStreamBuffer< Type > \- Buffers data from a stream and fires an event when a certain element is read\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inputStream\&.h>\fP
.PP
Inherits \fBMaxOS::common::InputStreamProcessor< Type, Type * >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputStreamBuffer\fP (\fBType\fP \fBevent_fire_element\fP, \fBType\fP \fBtermination_element\fP)"
.br
.ti -1c
.RI "\fB~InputStreamBuffer\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_stream_read\fP (\fBType\fP) \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_end_of_stream\fP (\fBGenericInputStream\fP< \fBType\fP > *) \fBoverride\fP"
.br
.ti -1c
.RI "\fBvoid\fP \fBflush\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBType\fP \fBm_buffer\fP [10240]"
.br
.ti -1c
.RI "\fBint\fP \fBm_offset\fP { 0 }"
.br
.ti -1c
.RI "\fBType\fP \fBm_event_fire_element\fP"
.br
.ti -1c
.RI "\fBType\fP \fBm_termination_element\fP"
.br
.in -1c

Protected Attributes inherited from \fBMaxOS::common::InputStreamEventHandler< Type >\fP
.in +1c
.ti -1c
.RI "\fBcommon::Vector\fP< \fBGenericInputStream\fP< \fBType\fP > * > \fBm_generic_input_streams\fP"
.br
.in -1c

Protected Attributes inherited from \fBMaxOS::common::GenericInputStream< Type >\fP
.in +1c
.ti -1c
.RI "\fBcommon::Vector\fP< \fBInputStreamEventHandler\fP< \fBType\fP > * > \fBm_input_stream_event_handlers\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::common::InputStreamProcessor< Type, Type * >\fP
.in +1c
.ti -1c
.RI "\fBInputStreamProcessor\fP ()"
.br
.ti -1c
.RI "\fBInputStreamProcessor\fP (\fBInputStreamEventHandler\fP< \fBType\fP * > *\fBgeneric_stream_event_handler\fP)"
.br
.ti -1c
.RI "\fB~InputStreamProcessor\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBon_end_of_stream\fP (\fBGenericInputStream\fP< \fBType\fP > *\fBstream\fP) \fBoverride\fP"
.br
.in -1c

Protected Member Functions inherited from \fBMaxOS::common::InputStreamEventHandler< Type >\fP
.in +1c
.ti -1c
.RI "\fBInputStreamEventHandler\fP ()"
.br
.RI "_______________________________________________TEMPLATES_________________________________________________________________/// "
.ti -1c
.RI "\fB~InputStreamEventHandler\fP ()"
.br
.in -1c

Protected Member Functions inherited from \fBMaxOS::common::GenericInputStream< Type >\fP
.in +1c
.ti -1c
.RI "\fBGenericInputStream\fP ()"
.br
.ti -1c
.RI "\fBGenericInputStream\fP (\fBInputStreamEventHandler\fP< \fBType\fP > *)"
.br
.ti -1c
.RI "\fB~GenericInputStream\fP ()"
.br
.ti -1c
.RI "\fBvoid\fP \fBconnect_input_stream_event_handler\fP (\fBInputStreamEventHandler\fP< \fBType\fP > *)"
.br
.ti -1c
.RI "\fBvoid\fP \fBdisconnect_input_stream_event_handler\fP (\fBInputStreamEventHandler\fP< \fBType\fP > *)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBclass\fP \fBType\fP>
.br
class MaxOS::common::InputStreamBuffer< Type >"Buffers data from a stream and fires an event when a certain element is read\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIType\fP The type of data the stream is handling 
.RE
.PP

.PP
Definition at line \fB79\fP of file \fBinputStream\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBclass\fP \fBType\fP > \fBMaxOS::common::InputStreamBuffer\fP< \fBType\fP >::InputStreamBuffer (\fBType\fP event_fire_element, \fBType\fP termination_element)"
@breif Creates a new \fBInputStreamBuffer\fP
.PP
\fBTemplate Parameters\fP
.RS 4
\fIType\fP The type of data the stream is handling 
.RE
.PP
\fBParameters\fP
.RS 4
\fIevent_fire_element\fP The element to fire the event on 
.br
\fItermination_element\fP The element that signifies the end of the part of the stream to be buffered (e\&.g a newline) 
.RE
.PP

.PP
Definition at line \fB279\fP of file \fBinputStream\&.h\fP\&..PP
.nf
280         : m_event_fire_element(event_fire_element),
281           m_termination_element(termination_element)
282         {
283 
284         }
.fi

.SS "template<\fBclass\fP \fBType\fP > \fBMaxOS::common::InputStreamBuffer\fP< \fBType\fP >::~\fBInputStreamBuffer\fP ()\fC [default]\fP"
@breif Destroys the \fBInputStreamBuffer\fP
.PP
\fBTemplate Parameters\fP
.RS 4
\fIType\fP The type of data the stream is handling 
.RE
.PP

.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBType\fP > \fBvoid\fP \fBMaxOS::common::InputStreamBuffer\fP< \fBType\fP >::flush ()"
@breif Flushes the buffer by adding the termination element and firing an on read event (NOTE: The buffer is not cleared after this just overwritten)
.PP
\fBTemplate Parameters\fP
.RS 4
\fIType\fP The type of data the stream is handling 
.RE
.PP

.PP
Definition at line \fB338\fP of file \fBinputStream\&.h\fP\&..PP
.nf
338                                                                  {
339 
340             // Ensure the buffer is not empty
341             if(m_offset == 0)
342                 return;
343 
344             // Add the termination element to the buffer
345             m_buffer[m_offset] = m_termination_element;
346 
347             // Fire the on read event
348             InputStreamProcessor<Type, Type *>::on_stream_read(m_buffer);
349 
350             // Reset the offset
351             m_offset = 0;
352 
353         }
.fi

.PP
References \fBMaxOS::common::InputStreamEventHandler< Type >::on_stream_read()\fP\&.
.SS "template<\fBclass\fP \fBType\fP > \fBvoid\fP \fBMaxOS::common::InputStreamBuffer\fP< \fBType\fP >::on_end_of_stream (\fBGenericInputStream\fP< \fBType\fP > * stream)\fC [override]\fP, \fC [virtual]\fP"
@breif Called when a stream has finished\&. Flushes the buffer if there is any data in it
.PP
\fBTemplate Parameters\fP
.RS 4
\fIType\fP The type of data the stream is handling 
.RE
.PP
\fBParameters\fP
.RS 4
\fIstream\fP The stream that has finished 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::common::InputStreamEventHandler< Type >\fP\&.
.PP
Definition at line \fB323\fP of file \fBinputStream\&.h\fP\&..PP
.nf
323                                                                                                             {
324 
325             // flush the buffer if there is any data in it
326             if(m_offset > 0)
327                 flush();
328 
329             // Pass the event on to the handlers and remove the stream
330             InputStreamProcessor<Type, Type *>::on_end_of_stream(stream);
331         }
.fi

.PP
References \fBMaxOS::common::InputStreamProcessor< Type, ProcessorType >::on_end_of_stream()\fP\&.
.SS "template<\fBclass\fP \fBType\fP > \fBvoid\fP \fBMaxOS::common::InputStreamBuffer\fP< \fBType\fP >::on_stream_read (\fBType\fP read_element)\fC [override]\fP, \fC [virtual]\fP"
@breif Called when data is read from a stream\&. Adds the data to the buffer and checks if the event should be fired
.PP
\fBTemplate Parameters\fP
.RS 4
\fIType\fP 
.RE
.PP
\fBParameters\fP
.RS 4
\fIread_element\fP 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::common::InputStreamEventHandler< Type >\fP\&.
.PP
Definition at line \fB299\fP of file \fBinputStream\&.h\fP\&..PP
.nf
299                                                                                            {
300 
301             // flush the buffer if the event fire element is read
302             if(read_element == m_event_fire_element){
303                 flush();
304                 return;
305             }
306 
307             // Ensure the buffer is not full
308             if(m_offset >= 10238){
309                 flush();
310             }
311 
312             // Add the element
313             m_buffer[m_offset++] = read_element;
314 
315         }
.fi

.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBType\fP > \fBType\fP \fBMaxOS::common::InputStreamBuffer\fP< \fBType\fP >::m_buffer[10240]\fC [protected]\fP"

.PP
Definition at line \fB82\fP of file \fBinputStream\&.h\fP\&.
.SS "template<\fBclass\fP \fBType\fP > \fBType\fP \fBMaxOS::common::InputStreamBuffer\fP< \fBType\fP >::m_event_fire_element\fC [protected]\fP"

.PP
Definition at line \fB84\fP of file \fBinputStream\&.h\fP\&.
.SS "template<\fBclass\fP \fBType\fP > \fBint\fP \fBMaxOS::common::InputStreamBuffer\fP< \fBType\fP >::m_offset { 0 }\fC [protected]\fP"

.PP
Definition at line \fB83\fP of file \fBinputStream\&.h\fP\&..PP
.nf
83 { 0 };
.fi

.SS "template<\fBclass\fP \fBType\fP > \fBType\fP \fBMaxOS::common::InputStreamBuffer\fP< \fBType\fP >::m_termination_element\fC [protected]\fP"

.PP
Definition at line \fB85\fP of file \fBinputStream\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
