.TH "maxOS::system::multiboot_elf_section_header_table" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::system::multiboot_elf_section_header_table
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBnum\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBaddr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBshndx\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 139 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_elf_section_header_table::addr"

.PP
Definition at line 143 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_elf_section_header_table::num"

.PP
Definition at line 141 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_elf_section_header_table::shndx"

.PP
Definition at line 144 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP maxOS::system::multiboot_elf_section_header_table::size"

.PP
Definition at line 142 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
