.TH "MaxOS::hardwarecommunication::Port16Bit" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::Port16Bit \- Handles 16 bit ports\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <port\&.h>\fP
.PP
Inherits \fBMaxOS::hardwarecommunication::Port\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPort16Bit\fP (uint16_t port_number)"
.br
.RI "Construct a new \fBPort\fP object for ports handling 16 bit read/writes\&. "
.ti -1c
.RI "virtual void \fBwrite\fP (uint16_t \fBdata\fP)"
.br
.RI "write a word to the port "
.ti -1c
.RI "virtual uint16_t \fBread\fP ()"
.br
.RI "read a word from the port "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::hardwarecommunication::Port\fP
.in +1c
.ti -1c
.RI "\fBPort\fP (uint16_t port_number)"
.br
.RI "Construct a new \fBPort\fP object\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::hardwarecommunication::Port\fP
.in +1c
.ti -1c
.RI "uint16_t \fBm_port_number\fP"
.br
.RI "The port to write to / read from\&. "
.in -1c
.SH "Detailed Description"
.PP 
Handles 16 bit ports\&. 
.PP
Definition at line \fB57\fP of file \fBport\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Port16Bit::Port16Bit (uint16_t port_number)"

.PP
Construct a new \fBPort\fP object for ports handling 16 bit read/writes\&. 
.PP
\fBParameters\fP
.RS 4
\fIport_number\fP The IO port number 
.RE
.PP

.PP
Definition at line \fB84\fP of file \fBport\&.cpp\fP\&..PP
.nf
85 : Port(port_number) {
86 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "uint16_t Port16Bit::read ()\fC [virtual]\fP"

.PP
read a word from the port 
.PP
\fBReturns\fP
.RS 4
the word read 
.RE
.PP

.PP
Definition at line \fB105\fP of file \fBport\&.cpp\fP\&..PP
.nf
105                          {
106 
107     uint16_t result;
108     asm volatile("inw %1, %0" : "=a" (result) : "Nd" (m_port_number));
109     return result;
110 }
.fi

.PP
References \fBMaxOS::hardwarecommunication::Port::m_port_number\fP\&.
.PP
Referenced by \fBMaxOS::drivers::ethernet::AMD_AM79C973::activate()\fP, \fBMaxOS::drivers::ethernet::AMD_AM79C973::AMD_AM79C973()\fP, \fBMaxOS::drivers::ethernet::AMD_AM79C973::handle_interrupt()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::identify()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::read()\fP, and \fBMaxOS::drivers::ethernet::AMD_AM79C973::reset()\fP\&.
.SS "void Port16Bit::write (uint16_t data)\fC [virtual]\fP"

.PP
write a word to the port 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP the word to write 
.RE
.PP

.PP
Definition at line \fB95\fP of file \fBport\&.cpp\fP\&..PP
.nf
95                                    {
96 
97     asm volatile("outw %0, %1" : : "a" (data), "Nd" (m_port_number));
98 }
.fi

.PP
References \fBdata\fP, and \fBMaxOS::hardwarecommunication::Port::m_port_number\fP\&.
.PP
Referenced by \fBMaxOS::drivers::ethernet::AMD_AM79C973::activate()\fP, \fBMaxOS::drivers::ethernet::AMD_AM79C973::AMD_AM79C973()\fP, \fBMaxOS::drivers::ethernet::AMD_AM79C973::DoSend()\fP, \fBMaxOS::drivers::ethernet::AMD_AM79C973::handle_interrupt()\fP, \fBMaxOS::drivers::ethernet::AMD_AM79C973::reset()\fP, and \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::write()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
