.TH "MaxOS::runtime::SourceLocation" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::runtime::SourceLocation \- The location in the source code where the undefined behaviour occurred\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ubsan\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBfile\fP"
.br
.RI "The name of the source file\&. "
.ti -1c
.RI "uint32_t \fBline\fP"
.br
.RI "The line number in the source file\&. "
.ti -1c
.RI "uint32_t \fBcolumn\fP"
.br
.RI "The column number in the source file\&. "
.in -1c
.SH "Detailed Description"
.PP 
The location in the source code where the undefined behaviour occurred\&. 
.PP
Definition at line \fB23\fP of file \fBubsan\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t MaxOS::runtime::SourceLocation::column"

.PP
The column number in the source file\&. 
.PP
Definition at line \fB26\fP of file \fBubsan\&.h\fP\&.
.PP
Referenced by \fBMaxOS::runtime::UBSanHandler::handle()\fP\&.
.SS "const char* MaxOS::runtime::SourceLocation::file"

.PP
The name of the source file\&. 
.PP
Definition at line \fB24\fP of file \fBubsan\&.h\fP\&.
.PP
Referenced by \fBMaxOS::runtime::UBSanHandler::handle()\fP\&.
.SS "uint32_t MaxOS::runtime::SourceLocation::line"

.PP
The line number in the source file\&. 
.PP
Definition at line \fB25\fP of file \fBubsan\&.h\fP\&.
.PP
Referenced by \fBMaxOS::runtime::UBSanHandler::handle()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
