.TH "MaxOS::filesystem::format::ext2::Ext2File" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::format::ext2::Ext2File \- Handles the file operations on the ext2 filesystem\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ext2\&.h>\fP
.PP
Inherits \fBMaxOS::filesystem::File\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExt2File\fP (\fBExt2Volume\fP *\fBvolume\fP, \fBuint32_t\fP inode, \fBconst\fP \fBstring\fP &\fBname\fP)"
.br
.RI "Construct a new Ext2 \fBFile\fP object\&. "
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBcommon::buffer_t\fP *data, \fBsize_t\fP \fBamount\fP) \fBfinal\fP"
.br
.RI "write data to the file (at the current seek position, updated to be += amount) "
.ti -1c
.RI "\fBvoid\fP \fBread\fP (\fBcommon::buffer_t\fP *data, \fBsize_t\fP \fBamount\fP) \fBfinal\fP"
.br
.RI "read data from the file (at the current seek position, updated to be += amount) "
.ti -1c
.RI "\fBvoid\fP \fBflush\fP () \fBfinal\fP"
.br
.RI "Flush the file to the disk\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::filesystem::File\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBseek\fP (\fBSeekType\fP \fBseek_type\fP, \fBsize_t\fP offset)"
.br
.RI "Seek to a position in the file\&. "
.ti -1c
.RI "\fBuint32_t\fP \fBposition\fP () \fBconst\fP"
.br
.RI "Get where the file is currently at (amount read/write/seeked) "
.ti -1c
.RI "\fBsize_t\fP \fBsize\fP () \fBconst\fP"
.br
.RI "Get the size of the file\&. "
.ti -1c
.RI "\fBstring\fP \fBname\fP ()"
.br
.RI "Get the name of the file\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBMaxOS::filesystem::File\fP
.in +1c
.ti -1c
.RI "uint32_t \fBm_offset\fP = 0"
.br
.RI "The current offset in the file\&. "
.ti -1c
.RI "\fBstring\fP \fBm_name\fP"
.br
.RI "The name of the file\&. "
.ti -1c
.RI "size_t \fBm_size\fP = 0"
.br
.RI "The size of the file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Handles the file operations on the ext2 filesystem\&. 
.PP
Definition at line \fB402\fP of file \fBext2\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Ext2File::Ext2File (\fBExt2Volume\fP * volume, \fBuint32_t\fP inode, \fBconst\fP \fBstring\fP & name)"

.PP
Construct a new Ext2 \fBFile\fP object\&. 
.PP
\fBParameters\fP
.RS 4
\fIvolume\fP The volume the file exists on 
.br
\fIinode\fP The inode number of the file (will be used to setup the internal \fBInodeHandler\fP) 
.br
\fIname\fP The name of the file 
.RE
.PP

.PP
Definition at line \fB725\fP of file \fBext2\&.cpp\fP\&..PP
.nf
726         : m_volume(volume),
727         m_inode(volume, inode) {
728 
729     // Set up the base information
730     m_name = name;
731     m_size = m_inode\&.size();
732 
733 }
.fi

.PP
References \fBMaxOS::filesystem::File::m_name\fP, \fBMaxOS::filesystem::File::m_size\fP, \fBMaxOS::filesystem::File::name()\fP, and \fBMaxOS::filesystem::format::ext2::InodeHandler::size()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBvoid\fP Ext2File::flush ()\fC [final]\fP, \fC [virtual]\fP"

.PP
Flush the file to the disk\&. 
.PP
Reimplemented from \fBMaxOS::filesystem::File\fP\&.
.PP
Definition at line \fB841\fP of file \fBext2\&.cpp\fP\&..PP
.nf
841                      {
842     File::flush();
843 }
.fi

.PP
References \fBMaxOS::filesystem::File::flush()\fP\&.
.SS "\fBvoid\fP Ext2File::read (\fBcommon::buffer_t\fP * data, \fBsize_t\fP amount)\fC [final]\fP, \fC [virtual]\fP"

.PP
read data from the file (at the current seek position, updated to be += amount) 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP The byte buffer to read into 
.br
\fIamount\fP The amount of data to read 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::filesystem::File\fP\&.
.PP
Definition at line \fB795\fP of file \fBext2\&.cpp\fP\&..PP
.nf
795                                                  {
796 
797     // Nothing to read
798     if(m_size == 0 || amount == 0)
799         return;
800 
801     // Prepare for reading
802     m_volume\->ext2_lock\&.lock();
803     const uint32_t block_size = m_volume\->block_size;
804     buffer_t buffer(block_size);
805 
806     // Force bounds
807     if(m_offset + amount > m_size)
808         amount = m_size \- m_offset;
809 
810     // Convert bytes to blocks
811     uint32_t block_start = m_offset / block_size;
812     uint32_t block_offset = m_offset % block_size;
813 
814     // Read each block
815     size_t current_block = block_start;
816     size_t read = 0;
817     while(read < amount) {
818 
819         // Read the block
820         uint32_t block = m_inode\&.block_cache[current_block++];
821         m_volume\->read_block(block, &buffer);
822 
823         // Where in this block to start reading
824         size_t buffer_start = (current_block \- 1 == block_start) ? block_offset : 0;
825         size_t readable = (amount \- read < block_size \- buffer_start) ? (amount \- read) : (block_size \- buffer_start);
826 
827         // Read the block
828         buffer\&.copy_to(data, readable, buffer_start, read);
829         read += readable;
830 
831     }
832 
833     // Clean up
834     m_offset += amount;
835     m_volume\->ext2_lock\&.unlock();
836 }
.fi

.PP
References \fBMaxOS::filesystem::format::ext2::InodeHandler::block_cache\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::block_size\fP, \fBMaxOS::common::Buffer::copy_to()\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::ext2_lock\fP, \fBMaxOS::common::Spinlock::lock()\fP, \fBMaxOS::filesystem::File::m_offset\fP, \fBMaxOS::filesystem::File::m_size\fP, \fBread()\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::read_block()\fP, and \fBMaxOS::common::Spinlock::unlock()\fP\&.
.PP
Referenced by \fBread()\fP\&.
.SS "\fBvoid\fP Ext2File::write (\fBcommon::buffer_t\fP * data, \fBsize_t\fP amount)\fC [final]\fP, \fC [virtual]\fP"

.PP
write data to the file (at the current seek position, updated to be += amount) 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP The byte buffer to write 
.br
\fIamount\fP The amount of data to write 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::filesystem::File\fP\&.
.PP
Definition at line \fB741\fP of file \fBext2\&.cpp\fP\&..PP
.nf
741                                                   {
742 
743     // Nothing to write
744     if(amount == 0)
745         return;
746 
747     // Prepare for writing
748     m_volume\->ext2_lock\&.lock();
749     const uint32_t block_size = m_volume\->block_size;
750     buffer_t buffer(block_size);
751 
752     // Expand the file
753     if(m_offset + amount > m_size)
754         m_size = m_inode\&.grow((m_offset + amount) \- m_size, false);
755 
756     // Save the updated metadata
757     m_inode\&.inode\&.last_modification_time = time_to_epoch(Clock::active_clock()\->get_time());
758     m_inode\&.save();
759 
760     // Convert bytes to blocks
761     uint32_t block_start = m_offset / block_size;
762     uint32_t block_offset = m_offset % block_size;
763 
764     // Write each block
765     size_t current_block = block_start;
766     size_t written = 0;
767     while(written < amount) {
768 
769         // Read the block
770         uint32_t block = m_inode\&.block_cache[current_block++];
771         m_volume\->read_block(block, &buffer);
772 
773         // Where in this block to start writing
774         size_t buffer_start = (current_block \- 1 == block_start) ? block_offset : 0;
775         size_t writable = (amount \- written < block_size \- buffer_start) ? (amount \- written) : (block_size \-
776                                                                                                  buffer_start);
777 
778         // Update the block
779         buffer\&.copy_from(data, writable, buffer_start, written);
780         m_volume\->write_block(block, &buffer);
781         written += writable;
782     }
783 
784     // Clean up
785     m_offset += amount;
786     m_volume\->ext2_lock\&.unlock();
787 }
.fi

.PP
References \fBMaxOS::drivers::clock::Clock::active_clock()\fP, \fBMaxOS::filesystem::format::ext2::InodeHandler::block_cache\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::block_size\fP, \fBMaxOS::common::Buffer::copy_from()\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::ext2_lock\fP, \fBMaxOS::filesystem::format::ext2::InodeHandler::grow()\fP, \fBMaxOS::filesystem::format::ext2::InodeHandler::inode\fP, \fBMaxOS::common::Spinlock::lock()\fP, \fBMaxOS::filesystem::File::m_offset\fP, \fBMaxOS::filesystem::File::m_size\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::read_block()\fP, \fBMaxOS::filesystem::format::ext2::InodeHandler::save()\fP, \fBMaxOS::common::Spinlock::unlock()\fP, and \fBMaxOS::filesystem::format::ext2::Ext2Volume::write_block()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
