.TH "maxOS::gui::widgets::InputBoxTextChangedEvent" 3 "Sat Jan 6 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::gui::widgets::InputBoxTextChangedEvent \- Event that is triggered when the text in an input box is changed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <inputbox\&.h>\fP
.PP
Inherits \fBmaxOS::common::Event< InputBoxEvents >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputBoxTextChangedEvent\fP (\fBstring\fP)"
.br
.RI "___ Events ___ /// "
.ti -1c
.RI "\fB~InputBoxTextChangedEvent\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBstring\fP \fBnew_text\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Event that is triggered when the text in an input box is changed\&. 
.PP
Definition at line 27 of file inputbox\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "InputBoxTextChangedEvent::InputBoxTextChangedEvent (\fBstring\fP new_text)"

.PP
___ Events ___ /// 
.PP
Definition at line 251 of file inputbox\&.cpp\&.
.PP
.nf
252 : Event(INPUTBOX_TEXT_CHANGED),
253   new_text(new_text)
254 {
255 }
.fi
.SS "InputBoxTextChangedEvent::~InputBoxTextChangedEvent ()"

.PP
Definition at line 257 of file inputbox\&.cpp\&.
.PP
.nf
257                                                     {
258 
259 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "\fBstring\fP maxOS::gui::widgets::InputBoxTextChangedEvent::new_text"

.PP
Definition at line 32 of file inputbox\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
