.TH "MaxOS::net::EthernetFrameHeader" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::EthernetFrameHeader \- Structure the raw data\&. This is the header of an Ethernet Frame\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethernetframe\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBdestinationMAC\fP: 48"
.br
.RI "The mac address of the target (Big Endian) "
.ti -1c
.RI "uint64_t \fBsourceMAC\fP: 48"
.br
.RI "The mac address of the sender (Big Endian) "
.ti -1c
.RI "uint16_t \fBtype\fP"
.br
.RI "The type (Big Endian) 0x0800 = IPv4, 0x0806 = ARP, 0x86DD = IPv6\&. "
.in -1c
.SH "Detailed Description"
.PP 
Structure the raw data\&. This is the header of an Ethernet Frame\&. 
.PP
Definition at line \fB27\fP of file \fBethernetframe\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::net::EthernetFrameHeader::destinationMAC"

.PP
The mac address of the target (Big Endian) 
.PP
Definition at line \fB29\fP of file \fBethernetframe\&.h\fP\&.
.SS "uint64_t MaxOS::net::EthernetFrameHeader::sourceMAC"

.PP
The mac address of the sender (Big Endian) 
.PP
Definition at line \fB30\fP of file \fBethernetframe\&.h\fP\&.
.SS "uint16_t MaxOS::net::EthernetFrameHeader::type"

.PP
The type (Big Endian) 0x0800 = IPv4, 0x0806 = ARP, 0x86DD = IPv6\&. 
.PP
Definition at line \fB32\fP of file \fBethernetframe\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
