.TH "MaxOS::hardwarecommunication::RedirectionEntry" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::RedirectionEntry \- An IO APIC redirection entry\&. Describes how an interrupt is routed\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <apic\&.h>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBPACKED\fP"
.br
.RI "Packed because the bitfields should be one uint64_t together\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBraw\fP"
.br
.RI "The raw 64-bit value of the redirection entry\&. "
.in -1c
.SH "Detailed Description"
.PP 
An IO APIC redirection entry\&. Describes how an interrupt is routed\&. 
.PP
Definition at line \fB123\fP of file \fBapic\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::hardwarecommunication::RedirectionEntry::raw"

.PP
The raw 64-bit value of the redirection entry\&. 
.PP
Definition at line \fB137\fP of file \fBapic\&.h\fP\&.
.PP
Referenced by \fBMaxOS::hardwarecommunication::IOAPIC::set_redirect()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
