.TH "MaxOS::processes::ELFSectionHeader64" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::processes::ELFSectionHeader64 \- The header for the sections in a 64-bit ELF file\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <elf\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBname_index\fP"
.br
.RI "The index into the section header string table where the name of this section is located\&. "
.ti -1c
.RI "uint32_t \fBtype\fP"
.br
.RI "The type of the section (see ELFSectionType) "
.ti -1c
.RI "uint64_t \fBsh_flags\fP"
.br
.RI "The flags of the section (see ELFSectionFlags) "
.ti -1c
.RI "uint64_t \fBvirtual_address\fP"
.br
.RI "Where the section is to be loaded in memory\&. "
.ti -1c
.RI "uint64_t \fBoffset\fP"
.br
.RI "The offset in the file where the section is located\&. "
.ti -1c
.RI "uint64_t \fBsize\fP"
.br
.RI "The size of the section in the file\&. "
.ti -1c
.RI "uint32_t \fBlink\fP"
.br
.RI "Section index link (meaning depends on section type) "
.ti -1c
.RI "uint32_t \fBinfo\fP"
.br
.RI "Extra information (meaning depends on section type) "
.ti -1c
.RI "uint64_t \fBaddress_alignment\fP"
.br
.RI "The required alignment of the section in memory (normally 2^n) "
.ti -1c
.RI "uint64_t \fBentry_size\fP"
.br
.RI "The size of each entry in the section if it contains a table of fixed-size entries\&. "
.in -1c
.SH "Detailed Description"
.PP 
The header for the sections in a 64-bit ELF file\&. 
.PP
Definition at line \fB185\fP of file \fBelf\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::processes::ELFSectionHeader64::address_alignment"

.PP
The required alignment of the section in memory (normally 2^n) 
.PP
Definition at line \fB194\fP of file \fBelf\&.h\fP\&.
.SS "uint64_t MaxOS::processes::ELFSectionHeader64::entry_size"

.PP
The size of each entry in the section if it contains a table of fixed-size entries\&. 
.PP
Definition at line \fB195\fP of file \fBelf\&.h\fP\&.
.SS "uint32_t MaxOS::processes::ELFSectionHeader64::info"

.PP
Extra information (meaning depends on section type) 
.PP
Definition at line \fB193\fP of file \fBelf\&.h\fP\&.
.SS "uint32_t MaxOS::processes::ELFSectionHeader64::link"

.PP
Section index link (meaning depends on section type) 
.PP
Definition at line \fB192\fP of file \fBelf\&.h\fP\&.
.SS "uint32_t MaxOS::processes::ELFSectionHeader64::name_index"

.PP
The index into the section header string table where the name of this section is located\&. 
.PP
Definition at line \fB186\fP of file \fBelf\&.h\fP\&.
.SS "uint64_t MaxOS::processes::ELFSectionHeader64::offset"

.PP
The offset in the file where the section is located\&. 
.PP
Definition at line \fB190\fP of file \fBelf\&.h\fP\&.
.SS "uint64_t MaxOS::processes::ELFSectionHeader64::sh_flags"

.PP
The flags of the section (see ELFSectionFlags) 
.PP
Definition at line \fB188\fP of file \fBelf\&.h\fP\&.
.SS "uint64_t MaxOS::processes::ELFSectionHeader64::size"

.PP
The size of the section in the file\&. 
.PP
Definition at line \fB191\fP of file \fBelf\&.h\fP\&.
.SS "uint32_t MaxOS::processes::ELFSectionHeader64::type"

.PP
The type of the section (see ELFSectionType) 
.PP
Definition at line \fB187\fP of file \fBelf\&.h\fP\&.
.SS "uint64_t MaxOS::processes::ELFSectionHeader64::virtual_address"

.PP
Where the section is to be loaded in memory\&. 
.PP
Definition at line \fB189\fP of file \fBelf\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
