.TH "MaxOS::hardwarecommunication::GateDescriptor" 3 "Mon Jan 15 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::GateDescriptor \- Describes a gate in the Interrupt Descriptor Table\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <interrupts\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBhandler_address_low_bits\fP"
.br
.ti -1c
.RI "uint16_t \fBgdt_code_segment_selector\fP"
.br
.ti -1c
.RI "uint8_t \fBreserved\fP"
.br
.ti -1c
.RI "uint8_t \fBaccess\fP"
.br
.ti -1c
.RI "uint16_t \fBhandler_address_high_bits\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Describes a gate in the Interrupt Descriptor Table\&. 
.PP
Definition at line 42 of file interrupts\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::hardwarecommunication::GateDescriptor::access"

.PP
Definition at line 46 of file interrupts\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::InterruptManager::set_interrupt_descriptor_table_entry()\&.
.SS "uint16_t MaxOS::hardwarecommunication::GateDescriptor::gdt_code_segment_selector"

.PP
Definition at line 44 of file interrupts\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::InterruptManager::set_interrupt_descriptor_table_entry()\&.
.SS "uint16_t MaxOS::hardwarecommunication::GateDescriptor::handler_address_high_bits"

.PP
Definition at line 47 of file interrupts\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::InterruptManager::set_interrupt_descriptor_table_entry()\&.
.SS "uint16_t MaxOS::hardwarecommunication::GateDescriptor::handler_address_low_bits"

.PP
Definition at line 43 of file interrupts\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::InterruptManager::set_interrupt_descriptor_table_entry()\&.
.SS "uint8_t MaxOS::hardwarecommunication::GateDescriptor::reserved"

.PP
Definition at line 45 of file interrupts\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::InterruptManager::set_interrupt_descriptor_table_entry()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
