.TH "MaxOS::drivers::peripherals::KeyboardState" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::peripherals::KeyboardState \- Holds the state of the keyboard\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <keyboard\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeyboardState\fP ()"
.br
.RI "___State___ "
.ti -1c
.RI "\fB~KeyboardState\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBleft_shift\fP { false }"
.br
.ti -1c
.RI "bool \fBright_shift\fP { false }"
.br
.ti -1c
.RI "bool \fBleft_control\fP { false }"
.br
.ti -1c
.RI "bool \fBright_control\fP { false }"
.br
.ti -1c
.RI "bool \fBleft_alt\fP { false }"
.br
.ti -1c
.RI "bool \fBright_alt\fP { false }"
.br
.ti -1c
.RI "bool \fBcaps_lock\fP { false }"
.br
.ti -1c
.RI "bool \fBnumber_pad_lock\fP { false }"
.br
.ti -1c
.RI "bool \fBscroll_lock\fP { false }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Holds the state of the keyboard\&. 
.PP
Definition at line 198 of file keyboard\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "KeyboardState::KeyboardState ()"

.PP
___State___ 
.PP
Definition at line 136 of file keyboard\&.cpp\&.
.PP
.nf
136                              {
137 
138 }
.fi
.SS "KeyboardState::~KeyboardState ()"

.PP
Definition at line 140 of file keyboard\&.cpp\&.
.PP
.nf
140                               {
141 
142 }
.fi
.SH "Member Data Documentation"
.PP 
.SS "bool MaxOS::drivers::peripherals::KeyboardState::caps_lock { false }"

.PP
Definition at line 212 of file keyboard\&.h\&.
.SS "bool MaxOS::drivers::peripherals::KeyboardState::left_alt { false }"

.PP
Definition at line 208 of file keyboard\&.h\&.
.SS "bool MaxOS::drivers::peripherals::KeyboardState::left_control { false }"

.PP
Definition at line 206 of file keyboard\&.h\&.
.SS "bool MaxOS::drivers::peripherals::KeyboardState::left_shift { false }"

.PP
Definition at line 204 of file keyboard\&.h\&.
.SS "bool MaxOS::drivers::peripherals::KeyboardState::number_pad_lock { false }"

.PP
Definition at line 213 of file keyboard\&.h\&.
.PP
Referenced by MaxOS::drivers::peripherals::KeyboardInterpreterEN_US::on_stream_read()\&.
.SS "bool MaxOS::drivers::peripherals::KeyboardState::right_alt { false }"

.PP
Definition at line 209 of file keyboard\&.h\&.
.SS "bool MaxOS::drivers::peripherals::KeyboardState::right_control { false }"

.PP
Definition at line 207 of file keyboard\&.h\&.
.SS "bool MaxOS::drivers::peripherals::KeyboardState::right_shift { false }"

.PP
Definition at line 205 of file keyboard\&.h\&.
.SS "bool MaxOS::drivers::peripherals::KeyboardState::scroll_lock { false }"

.PP
Definition at line 214 of file keyboard\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
