.TH "maxOS::drivers::video::VideoElectronicsStandardsAssociation" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::drivers::video::VideoElectronicsStandardsAssociation \- \fBDriver\fP for the VESA video controller, handles the rendering of pixels to the screen using VESA\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <vesa\&.h>\fP
.PP
Inherits \fBmaxOS::drivers::video::VideoDriver\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVideoElectronicsStandardsAssociation\fP (\fBsystem::multiboot_info_t\fP *mb_info)"
.br
.ti -1c
.RI "\fB~VideoElectronicsStandardsAssociation\fP ()"
.br
.ti -1c
.RI "bool \fBsupports_mode\fP (uint32_t width, uint32_t height, uint32_t) final"
.br
.RI "Checks if the VESA driver supports the given mode\&. "
.ti -1c
.RI "\fBstring\fP \fBget_vendor_name\fP () final"
.br
.RI "Renders a pixel on the screen in 16 bit mode\&. "
.ti -1c
.RI "\fBstring\fP \fBget_device_name\fP () final"
.br
.RI "Gets the colour of a pixel on the screen in 16 bit mode\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "bool \fBinternal_set_mode\fP (uint32_t width, uint32_t height, uint32_t) final"
.br
.RI "Sets the mode of the VESA driver (TODO: List of modes) "
.ti -1c
.RI "void \fBrender_pixel_32_bit\fP (uint32_t x, uint32_t y, uint32_t colour) final"
.br
.RI "Renders a pixel on the screen in 32 bit mode\&. "
.ti -1c
.RI "uint32_t \fBget_rendered_pixel_32_bit\fP (uint32_t x, uint32_t y) final"
.br
.RI "Gets the colour of a pixel on the screen in 32 bit mode\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBsystem::multiboot_info_t\fP * \fBm_multiboot_info\fP"
.br
.ti -1c
.RI "uint32_t * \fBm_framebuffer_address\fP"
.br
.ti -1c
.RI "uint8_t \fBm_bpp\fP"
.br
.ti -1c
.RI "uint16_t \fBm_pitch\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
\fBDriver\fP for the VESA video controller, handles the rendering of pixels to the screen using VESA\&. 
.PP
Definition at line 26 of file vesa\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "VideoElectronicsStandardsAssociation::VideoElectronicsStandardsAssociation (\fBsystem::multiboot_info_t\fP * mb_info)"

.PP
Definition at line 13 of file vesa\&.cpp\&.
.PP
.nf
14 : VideoDriver(),
15   m_multiboot_info(mb_info),
16   m_framebuffer_address((uint32_t*)mb_info->framebuffer_addr),
17   m_bpp(mb_info->framebuffer_bpp),
18   m_pitch(mb_info->framebuffer_pitch)
19 {
20 }
.fi
.SS "VideoElectronicsStandardsAssociation::~VideoElectronicsStandardsAssociation ()"

.PP
Definition at line 22 of file vesa\&.cpp\&.
.PP
.nf
22                                                                            {
23 
24 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "\fBstring\fP VideoElectronicsStandardsAssociation::get_device_name ()\fC [final]\fP, \fC [virtual]\fP"

.PP
Gets the colour of a pixel on the screen in 16 bit mode\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The x coordinate of the pixel 
.br
\fIy\fP The y coordinate of the pixel 
.RE
.PP
\fBReturns\fP
.RS 4
The 16bit colour of the pixel 
.RE
.PP

.PP
Reimplemented from \fBmaxOS::drivers::Driver\fP\&.
.PP
Definition at line 128 of file vesa\&.cpp\&.
.PP
.nf
128                                                              {
129     return "VESA compatible graphics card";
130 }
.fi
.SS "uint32_t VideoElectronicsStandardsAssociation::get_rendered_pixel_32_bit (uint32_t x, uint32_t y)\fC [final]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Gets the colour of a pixel on the screen in 32 bit mode\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The x coordinate of the pixel 
.br
\fIy\fP The y coordinate of the pixel 
.RE
.PP
\fBReturns\fP
.RS 4
The 32bit colour of the pixel 
.RE
.PP

.PP
Reimplemented from \fBmaxOS::common::GraphicsContext\fP\&.
.PP
Definition at line 101 of file vesa\&.cpp\&.
.PP
.nf
101                                                                                                {
102 
103     // Get the address of the pixel
104     uint32_t*pixel_address = (uint32_t*)((uint8_t *)m_framebuffer_address + m_pitch * (y) + m_bpp * (x) / 8);
105 
106     // Return the pixel
107     return *pixel_address;
108 }
.fi
.PP
References m_bpp, m_framebuffer_address, m_pitch, maxOS::drivers::peripherals::x, and maxOS::drivers::peripherals::y\&.
.SS "\fBstring\fP VideoElectronicsStandardsAssociation::get_vendor_name ()\fC [final]\fP, \fC [virtual]\fP"

.PP
Renders a pixel on the screen in 16 bit mode\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The x coordinate of the pixel 
.br
\fIy\fP The y coordinate of the pixel 
.br
\fIcolour\fP The 16bit colour of the pixel 
.RE
.PP

.PP
Reimplemented from \fBmaxOS::drivers::Driver\fP\&.
.PP
Definition at line 117 of file vesa\&.cpp\&.
.PP
.nf
117                                                              {
118     return "NEC Home Electronics";  // Creator of the VESA standard
119 }
.fi
.SS "bool VideoElectronicsStandardsAssociation::internal_set_mode (uint32_t width, uint32_t height, uint32_t color_depth)\fC [final]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Sets the mode of the VESA driver (TODO: List of modes) 
.PP
\fBParameters\fP
.RS 4
\fIwidth\fP Width of the screen 
.br
\fIheight\fP Height of the screen 
.br
\fIcolor_depth\fP Color depth of the screen 
.RE
.PP
\fBReturns\fP
.RS 4
True if the mode was set successfully, false otherwise 
.RE
.PP

.PP
Reimplemented from \fBmaxOS::drivers::video::VideoDriver\fP\&.
.PP
Definition at line 40 of file vesa\&.cpp\&.
.PP
.nf
40                                                                                                                   {
41 
42 
43     // Check if the mode is supported
44     if(!supports_mode(width, height, color_depth)) {
45         return false;
46     }
47 
48     // Initialise the VESA driver
49     if(!init()) {
50         // VESA driver could not be initialised
51         return false;
52     }
53 
54     // Return true if the mode was set successfully
55     return true;
56 
57 
58 }
.fi
.PP
References supports_mode()\&.
.SS "void VideoElectronicsStandardsAssociation::render_pixel_32_bit (uint32_t x, uint32_t y, uint32_t colour)\fC [final]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Renders a pixel on the screen in 32 bit mode\&. 
.PP
\fBParameters\fP
.RS 4
\fIx\fP The x coordinate of the pixel 
.br
\fIy\fP The y coordinate of the pixel 
.br
\fIcolour\fP The 32bit colour of the pixel 
.RE
.PP

.PP
Reimplemented from \fBmaxOS::common::GraphicsContext\fP\&.
.PP
Definition at line 84 of file vesa\&.cpp\&.
.PP
.nf
84                                                                                                       {
85 
86     // Get the address of the pixel
87     uint32_t*pixel_address = (uint32_t*)((uint8_t *)m_framebuffer_address + m_pitch * (y) + m_bpp * (x) / 8);
88 
89     // Set the pixel
90     *pixel_address = colour;
91 
92 }
.fi
.PP
References m_bpp, m_framebuffer_address, m_pitch, maxOS::drivers::peripherals::x, and maxOS::drivers::peripherals::y\&.
.SS "bool VideoElectronicsStandardsAssociation::supports_mode (uint32_t width, uint32_t height, uint32_t color_depth)\fC [final]\fP, \fC [virtual]\fP"

.PP
Checks if the VESA driver supports the given mode\&. 
.PP
\fBParameters\fP
.RS 4
\fIwidth\fP The m_width of the screen 
.br
\fIheight\fP The m_height of the screen 
.br
\fIcolor_depth\fP The color depth of the screen 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Reimplemented from \fBmaxOS::drivers::video::VideoDriver\fP\&.
.PP
Definition at line 68 of file vesa\&.cpp\&.
.PP
.nf
68                                                                                                               {
69 
70     // Check if the mode is supported
71     if(width == (int)m_multiboot_info->framebuffer_width && height == (int)m_multiboot_info->framebuffer_height && color_depth == (int)m_multiboot_info->framebuffer_bpp) {
72         return true;
73     }
74     return false;
75 }
.fi
.PP
References maxOS::system::multiboot_info::framebuffer_bpp, maxOS::system::multiboot_info::framebuffer_height, maxOS::system::multiboot_info::framebuffer_width, and m_multiboot_info\&.
.PP
Referenced by internal_set_mode()\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t maxOS::drivers::video::VideoElectronicsStandardsAssociation::m_bpp\fC [protected]\fP"

.PP
Definition at line 40 of file vesa\&.h\&.
.PP
Referenced by get_rendered_pixel_32_bit(), and render_pixel_32_bit()\&.
.SS "uint32_t* maxOS::drivers::video::VideoElectronicsStandardsAssociation::m_framebuffer_address\fC [protected]\fP"

.PP
Definition at line 39 of file vesa\&.h\&.
.PP
Referenced by get_rendered_pixel_32_bit(), and render_pixel_32_bit()\&.
.SS "\fBsystem::multiboot_info_t\fP* maxOS::drivers::video::VideoElectronicsStandardsAssociation::m_multiboot_info\fC [protected]\fP"

.PP
Definition at line 37 of file vesa\&.h\&.
.PP
Referenced by supports_mode()\&.
.SS "uint16_t maxOS::drivers::video::VideoElectronicsStandardsAssociation::m_pitch\fC [protected]\fP"

.PP
Definition at line 41 of file vesa\&.h\&.
.PP
Referenced by get_rendered_pixel_32_bit(), and render_pixel_32_bit()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
