.TH "MaxOS::drivers::disk::AdvancedTechnologyAttachment" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::disk::AdvancedTechnologyAttachment \- \fBDriver\fP for the ATA controller, handles the reading and writing of data to the hard drive\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ata\&.h>\fP
.PP
Inherits \fBMaxOS::drivers::disk::Disk\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAdvancedTechnologyAttachment\fP (\fBuint16_t\fP port_base, \fBbool\fP \fBmaster\fP)"
.br
.RI "Constructor for the \fBAdvancedTechnologyAttachment\fP class\&. "
.ti -1c
.RI "\fBbool\fP \fBidentify\fP ()"
.br
.RI "Identify the ATA device\&. "
.ti -1c
.RI "\fBvoid\fP \fBread\fP (\fBuint32_t\fP \fBsector\fP, \fBcommon::buffer_t\fP *\fBdata_buffer\fP, \fBsize_t\fP \fBamount\fP) \fBfinal\fP"
.br
.RI "Read a sector from the ATA device\&. "
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBuint32_t\fP \fBsector\fP, \fBconst\fP \fBcommon::buffer_t\fP *\fBdata\fP, \fBsize_t\fP \fBcount\fP) \fBfinal\fP"
.br
.RI "write to a sector on the ATA device "
.ti -1c
.RI "\fBvoid\fP \fBflush\fP () \fBfinal\fP"
.br
.RI "Flush the cache of the ATA device\&. "
.ti -1c
.RI "\fBstring\fP \fBdevice_name\fP () \fBfinal\fP"
.br
.RI "Get the device name\&. "
.ti -1c
.RI "\fBstring\fP \fBvendor_name\fP () \fBfinal\fP"
.br
.RI "Get the vendor name\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::disk::Disk\fP
.in +1c
.ti -1c
.RI "\fBvoid\fP \fBread\fP (\fBuint32_t\fP \fBsector\fP, \fBcommon::buffer_t\fP *\fBdata_buffer\fP)"
.br
.RI "Read data from the disk into a buffer (max capacity 512 bytes) "
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBuint32_t\fP \fBsector\fP, \fBconst\fP \fBcommon::buffer_t\fP *\fBdata\fP)"
.br
.RI "Write data to the disk from a buffer (max capacity 512 bytes) "
.ti -1c
.RI "\fBvoid\fP \fBactivate\fP () \fBoverride\fP"
.br
.RI "Activate the disk driver\&. "
.ti -1c
.RI "\fBstring\fP \fBdevice_name\fP () \fBoverride\fP"
.br
.RI "Get the device name\&. "
.ti -1c
.RI "\fBstring\fP \fBvendor_name\fP () \fBoverride\fP"
.br
.RI "Get the vendor name\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::Driver\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdeactivate\fP ()"
.br
.RI "deactivate the driver "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBinitialise\fP ()"
.br
.RI "Initialise the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBuint32_t\fP \fBreset\fP ()"
.br
.RI "Reset the driver\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBDriver\fP for the ATA controller, handles the reading and writing of data to the hard drive\&. 
.PP
Definition at line \fB29\fP of file \fBata\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AdvancedTechnologyAttachment::AdvancedTechnologyAttachment (\fBuint16_t\fP port_base, \fBbool\fP master)"

.PP
Constructor for the \fBAdvancedTechnologyAttachment\fP class\&. 
.PP
\fBParameters\fP
.RS 4
\fIport_base\fP The base port for the ATA device 
.br
\fImaster\fP True if the device is master, false if slave 
.RE
.PP

.PP
Definition at line \fB23\fP of file \fBata\&.cpp\fP\&..PP
.nf
24 : m_data_port(port_base),
25   m_error_port(port_base + 1),
26   m_sector_count_port(port_base + 2),
27   m_LBA_low_port(port_base + 3),
28   m_LBA_mid_port(port_base + 4),
29   m_LBA_high_Port(port_base + 5),
30   m_device_port(port_base + 6),
31   m_command_port(port_base + 7),
32   m_control_port(port_base + 0x206),
33   m_is_master(master)
34 {
35 
36 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "\fBstring\fP AdvancedTechnologyAttachment::device_name ()\fC [final]\fP, \fC [virtual]\fP"

.PP
Get the device name\&. 
.PP
\fBReturns\fP
.RS 4
The name of the device 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::Driver\fP\&.
.PP
Definition at line \fB246\fP of file \fBata\&.cpp\fP\&..PP
.nf
246                                                  {
247     return "Advanced Technology Attachment";
248 }
.fi

.SS "\fBvoid\fP AdvancedTechnologyAttachment::flush ()\fC [final]\fP, \fC [virtual]\fP"

.PP
Flush the cache of the ATA device\&. 
.PP
Reimplemented from \fBMaxOS::drivers::disk::Disk\fP\&.
.PP
Definition at line \fB217\fP of file \fBata\&.cpp\fP\&..PP
.nf
217                                          {
218 
219     // Select the device (master or slave)
220     m_device_port\&.write(m_is_master ? 0xE0 : 0xF0);
221 
222     // Send the flush command
223     m_command_port\&.write(0xE7);
224 
225     // Make sure the device is there
226     uint8_t status = m_command_port\&.read();
227     if (status == 0x00)
228         return;
229 
230     // Wait for the device to be ready or for an error to occur
231     while (((status & 0x80) == 0x80) && ((status & 0x01) != 0x01))
232         status = m_command_port\&.read();
233 
234     // Check for an error
235     if (status & 0x01)
236         return;
237 
238     // \&.\&.\&.
239 }
.fi

.PP
References \fBMaxOS::hardwarecommunication::Port8Bit::read()\fP, and \fBMaxOS::hardwarecommunication::Port8Bit::write()\fP\&.
.PP
Referenced by \fBwrite()\fP\&.
.SS "\fBbool\fP AdvancedTechnologyAttachment::identify ()"

.PP
Identify the ATA device\&. 
.PP
\fBReturns\fP
.RS 4
True if the device is present, false otherwise 
.RE
.PP

.PP
Definition at line \fB45\fP of file \fBata\&.cpp\fP\&..PP
.nf
45                                             {
46 
47     // Select the device (master or slave)
48     m_device_port\&.write(m_is_master ? 0xA0 : 0xB0);
49 
50     // Reset the High Order Byte
51     m_control_port\&.write(0);
52 
53     // Check if the master is present
54     m_device_port\&.write(0xA0);
55     uint8_t status = m_command_port\&.read();
56     if (status == 0xFF) {
57         Logger::WARNING() << "ATA Device: Invalid status";
58         return false;
59     }
60 
61     // Select the device (master or slave)
62     m_device_port\&.write(m_is_master ? 0xA0 : 0xB0);
63 
64     // Clear the ports
65     m_sector_count_port\&.write(0);
66     m_LBA_low_port\&.write(0);
67     m_LBA_mid_port\&.write(0);
68     m_LBA_high_Port\&.write(0);
69 
70     // Check if the device is present
71     m_command_port\&.write(0x0EC);
72     status = m_command_port\&.read();
73     if (status == 0x00)
74         return false;
75 
76     // Wait for the device to be ready or for an error to occur
77     while (((status & 0x80) == 0x80) && ((status & 0x01) != 0x01))
78         status = m_command_port\&.read();
79 
80     //Check for any errors
81     if (status & 0x01) {
82         Logger::WARNING() << "ATA Device: Error reading status\\n";
83         return false;
84     }
85 
86     // Read the rest of the data as a whole sector needs to be read
87     for (uint16_t i = 0; i < 256; ++i)
88         uint16_t data = m_data_port\&.read();
89 
90     // Device is present and ready
91     return true;
92 }
.fi

.PP
References \fBdata\fP, \fBMaxOS::hardwarecommunication::Port8Bit::read()\fP, \fBMaxOS::hardwarecommunication::Port16Bit::read()\fP, \fBLogger::WARNING()\fP, and \fBMaxOS::hardwarecommunication::Port8Bit::write()\fP\&.
.SS "\fBvoid\fP AdvancedTechnologyAttachment::read (\fBuint32_t\fP sector, \fBcommon::buffer_t\fP * data_buffer, \fBsize_t\fP amount)\fC [final]\fP, \fC [virtual]\fP"

.PP
Read a sector from the ATA device\&. 
.PP
\fBParameters\fP
.RS 4
\fIsector\fP The sector to read 
.br
\fIdata_buffer\fP The data to read into 
.br
\fIamount\fP The amount of bytes to read from that sector 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::disk::Disk\fP\&.
.PP
Definition at line \fB101\fP of file \fBata\&.cpp\fP\&..PP
.nf
101                                                                                              {
102 
103     // Don't allow reading more than a sector
104     if (sector & 0xF0000000 || amount > m_bytes_per_sector)
105         return;
106 
107     // Select the device (master or slave)
108     m_device_port\&.write((m_is_master ? 0xE0 : 0xF0) | ((sector & 0x0F000000) >> 24));
109 
110     // Device is busy @todo yeild
111     while ((m_command_port\&.read() & 0x80) != 0);
112 
113     // Reset the device
114     m_error_port\&.write(0);
115     m_sector_count_port\&.write(1);
116 
117     // Split the sector into the ports
118     m_LBA_low_port\&.write(sector & 0x000000FF);
119     m_LBA_mid_port\&.write((sector & 0x0000FF00) >> 8);
120     m_LBA_high_Port\&.write((sector & 0x00FF0000) >> 16);
121 
122     // Tell the device to prepare for reading
123     m_command_port\&.write(0x20);
124 
125     // Make sure the device is there
126     uint8_t status = m_command_port\&.read();
127     if (status == 0x00)
128         return;
129 
130     // Wait for the device to be ready or for an error to occur @todo Userspace block here
131     while (((status & 0x80) == 0x80) && ((status & 0x01) != 0x01))
132         status = m_command_port\&.read();
133 
134     //Check for any errors
135     if (status & 0x01)
136         return;
137 
138     for (size_t i = 0; i < amount; i += 2) {
139 
140         // Read from the disk (2 bytes) and store the first byte
141         uint16_t read_data = m_data_port\&.read();
142         data_buffer\->write(read_data & 0x00FF);
143 
144         // Place the second byte in the array if there is one
145         if (i + 1 < amount)
146             data_buffer\->write((read_data >> 8) & 0x00FF);
147     }
148 
149     // Read the remaining bytes as a full sector has to be read
150     for (uint16_t i = amount + (amount % 2); i < m_bytes_per_sector; i += 2)
151         m_data_port\&.read();
152 }
.fi

.PP
References \fBMaxOS::hardwarecommunication::Port8Bit::read()\fP, \fBMaxOS::hardwarecommunication::Port16Bit::read()\fP, and \fBMaxOS::hardwarecommunication::Port8Bit::write()\fP\&.
.SS "\fBstring\fP AdvancedTechnologyAttachment::vendor_name ()\fC [final]\fP, \fC [virtual]\fP"

.PP
Get the vendor name\&. 
.PP
\fBReturns\fP
.RS 4
The name of the vendor 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::Driver\fP\&.
.PP
Definition at line \fB255\fP of file \fBata\&.cpp\fP\&..PP
.nf
255                                                  {
256     return "IDE";
257 }
.fi

.SS "\fBvoid\fP AdvancedTechnologyAttachment::write (\fBuint32_t\fP sector, \fBconst\fP \fBcommon::buffer_t\fP * data, \fBsize_t\fP count)\fC [final]\fP, \fC [virtual]\fP"

.PP
write to a sector on the ATA device 
.PP
\fBParameters\fP
.RS 4
\fIsector\fP The sector to write to 
.br
\fIdata\fP The data to write 
.br
\fIcount\fP The amount of data to write to that sector 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::drivers::disk::Disk\fP\&.
.PP
Definition at line \fB161\fP of file \fBata\&.cpp\fP\&..PP
.nf
161                                                                                             {
162 
163     // Don't allow writing more than a sector
164     if (sector > 0x0FFFFFFF || count > m_bytes_per_sector)
165         return;
166 
167     // Select the device (master or slave)
168     m_device_port\&.write(m_is_master ? 0xE0 : 0xF0 | ((sector & 0x0F000000) >> 24));
169 
170     // Device is busy @todo YIELD
171     while ((m_command_port\&.read() & 0x80) != 0);
172 
173     // Reset the device
174     m_error_port\&.write(0);
175     m_sector_count_port\&.write(1);
176 
177     // Split the sector into the ports
178     m_LBA_low_port\&.write(sector & 0x000000FF);
179     m_LBA_mid_port\&.write((sector & 0x0000FF00) >> 8);
180     m_LBA_high_Port\&.write((sector & 0x00FF0000) >> 16);
181 
182     // Send the write command
183     m_command_port\&.write(0x30);
184 
185     // Wait for the device be ready writing @todo YIELD
186     uint8_t status = m_command_port\&.read();
187     while ((status & 0x80) != 0 || (status & 0x08) == 0)
188         status = m_command_port\&.read();
189 
190     // Write the data to the device
191     for (uint16_t i = 0; i < m_bytes_per_sector; i += 2) {
192 
193         uint16_t writeData = data\->read();
194 
195         // Place the next byte in the array if there is one
196         if (i + 1 < count)
197             writeData |= (uint16_t) (data\->read()) << 8;
198 
199         m_data_port\&.write(writeData);
200     }
201 
202     // Write the remaining bytes as a full sector has to be written
203     for (int i = count + (count % 2); i < m_bytes_per_sector; i += 2)
204         m_data_port\&.write(0x0000);
205 
206     // Wait for the device to finish writing @todo YIELD
207     status = m_command_port\&.read();
208     while ((status & 0x80) != 0 || (status & 0x08) != 0)
209         status = m_command_port\&.read();
210 
211     flush();
212 }
.fi

.PP
References \fBdata\fP, \fBflush()\fP, \fBMaxOS::hardwarecommunication::Port8Bit::read()\fP, \fBMaxOS::hardwarecommunication::Port16Bit::write()\fP, and \fBMaxOS::hardwarecommunication::Port8Bit::write()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
