.TH "MaxOS::net::EthernetFramePayloadHandler" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::EthernetFramePayloadHandler \- Handles a specific type of Ethernet Frame payload\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ethernetframe\&.h>\fP
.PP
Inherited by \fBMaxOS::net::AddressResolutionProtocol\fP, and \fBMaxOS::net::InternetProtocolHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEthernetFramePayloadHandler\fP (\fBEthernetFrameHandler\fP *\fBframeHandler\fP, \fBuint16_t\fP \fBhandledType\fP)"
.br
.RI "Construct a new Ether Frame Payload Handler object\&. "
.ti -1c
.RI "\fB~EthernetFramePayloadHandler\fP ()"
.br
.RI "Destroy the EtherFrameHandler:: EtherFrameHandler object, Removes it from the handler list\&. "
.ti -1c
.RI "\fBvirtual\fP \fBbool\fP \fBhandleEthernetframePayload\fP (\fBuint8_t\fP *\fBethernetframePayload\fP, \fBuint32_t\fP \fBsize\fP)"
.br
.RI "Handle the received ethernet frame payload\&. "
.ti -1c
.RI "\fBvoid\fP \fBSend\fP (\fBuint64_t\fP \fBdestinationMAC\fP, \fBuint8_t\fP *\fBdata\fP, \fBuint32_t\fP \fBsize\fP)"
.br
.RI "Send an packet via the backend driver\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBEthernetFrameHandler\fP * \fBframeHandler\fP"
.br
.RI "The Ethernet frame handler this payload handler is connected to\&. "
.ti -1c
.RI "uint16_t \fBhandledType\fP"
.br
.RI "The Ethernet frame type this handler handles\&. "
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBEthernetFrameHandler\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles a specific type of Ethernet Frame payload\&. 
.PP
Definition at line \fB50\fP of file \fBethernetframe\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "EthernetFramePayloadHandler::EthernetFramePayloadHandler (\fBEthernetFrameHandler\fP * frameHandler, \fBuint16_t\fP handledType)"

.PP
Construct a new Ether Frame Payload Handler object\&. 
.PP
\fBParameters\fP
.RS 4
\fIframeHandler\fP the handler for the ethernet frame 
.br
\fIhandledType\fP the type of the protocol, which will be handled by this handler 
.RE
.PP

.PP
Definition at line \fB24\fP of file \fBethernetframe\&.cpp\fP\&..PP
.nf
24                                                                                                                  {
25 
26     this \-> handledType = handledType;
27     this \-> frameHandler = frameHandler;
28     frameHandler\->connectHandler(this);
29 
30 
31 }
.fi

.PP
References \fBMaxOS::net::EthernetFrameHandler::connectHandler()\fP, \fBframeHandler\fP, and \fBhandledType\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBbool\fP EthernetFramePayloadHandler::handleEthernetframePayload (\fBuint8_t\fP * ethernetframePayload, \fBuint32_t\fP size)\fC [virtual]\fP"

.PP
Handle the received ethernet frame payload\&. 
.PP
\fBParameters\fP
.RS 4
\fIethernetframePayload\fP the payload of the ethernet frame 
.br
\fIsize\fP the size of the payload
.RE
.PP
\fBReturns\fP
.RS 4
True if the data is to be sent back, false otherwise 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::net::AddressResolutionProtocol\fP, and \fBMaxOS::net::InternetProtocolHandler\fP\&.
.PP
Definition at line \fB48\fP of file \fBethernetframe\&.cpp\fP\&..PP
.nf
48                                                                                                          {
49 
50     //By default, don't handle it, will be handled in the override
51     return false;
52 
53 }
.fi

.SS "\fBvoid\fP EthernetFramePayloadHandler::Send (\fBuint64_t\fP destination, \fBuint8_t\fP * data, \fBuint32_t\fP size)"

.PP
Send an packet via the backend driver\&. 
.PP
\fBParameters\fP
.RS 4
\fIdestination\fP the destination MAC address 
.br
\fIdata\fP the data to send 
.br
\fIsize\fP the size of the payload 
.RE
.PP

.PP
Definition at line \fB62\fP of file \fBethernetframe\&.cpp\fP\&..PP
.nf
62                                                                                          {
63 
64     frameHandler \-> sendEthernetFrame (destination, handledType, data, size);
65 }
.fi

.PP
References \fBdata\fP, \fBdestination\fP, \fBframeHandler\fP, \fBhandledType\fP, and \fBsize\fP\&.
.PP
Referenced by \fBMaxOS::net::AddressResolutionProtocol::RequestMACAddress()\fP\&.
.SH "Friends And Related Symbol Documentation"
.PP 
.SS "friend class \fBEthernetFrameHandler\fP\fC [friend]\fP"

.PP
Definition at line \fB51\fP of file \fBethernetframe\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBEthernetFrameHandler\fP* MaxOS::net::EthernetFramePayloadHandler::frameHandler\fC [protected]\fP"

.PP
The Ethernet frame handler this payload handler is connected to\&. 
.PP
Definition at line \fB54\fP of file \fBethernetframe\&.h\fP\&.
.PP
Referenced by \fBEthernetFramePayloadHandler()\fP, \fBMaxOS::net::InternetProtocolHandler::GetMediaAccessControlAddress()\fP, \fBMaxOS::net::AddressResolutionProtocol::RequestMACAddress()\fP, \fBSend()\fP, and \fBMaxOS::net::InternetProtocolHandler::sendInternetProtocolPacket()\fP\&.
.SS "uint16_t MaxOS::net::EthernetFramePayloadHandler::handledType\fC [protected]\fP"

.PP
The Ethernet frame type this handler handles\&. 
.PP
Definition at line \fB55\fP of file \fBethernetframe\&.h\fP\&.
.PP
Referenced by \fBEthernetFramePayloadHandler()\fP, \fBSend()\fP, and \fBMaxOS::net::InternetProtocolHandler::sendInternetProtocolPacket()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
