.TH "MaxOS::system::StackFrame" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system::StackFrame \- A snapshot of the a frame in the call stack\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpu\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBStackFrame\fP * \fBnext\fP"
.br
.RI "Pointer to the next stack frame (up the call stack) "
.ti -1c
.RI "uintptr_t \fBrip\fP"
.br
.RI "The instruction pointer at this frame\&. "
.in -1c
.SH "Detailed Description"
.PP 
A snapshot of the a frame in the call stack\&. 
.PP
Definition at line \fB162\fP of file \fBcpu\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBStackFrame\fP* MaxOS::system::StackFrame::next"

.PP
Pointer to the next stack frame (up the call stack) 
.PP
Definition at line \fB163\fP of file \fBcpu\&.h\fP\&.
.SS "uintptr_t MaxOS::system::StackFrame::rip"

.PP
The instruction pointer at this frame\&. 
.PP
Definition at line \fB164\fP of file \fBcpu\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
