.TH "MaxOS::system::CoreBootInfo" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::system::CoreBootInfo \- Information needed when booting a core\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <cpu\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBstack\fP"
.br
.RI "The stack pointer for the core\&. "
.ti -1c
.RI "uint64_t \fBp4_table\fP"
.br
.RI "The physical address of the P4 page table\&. "
.ti -1c
.RI "uint8_t \fBid\fP"
.br
.RI "The ID of the core\&. "
.ti -1c
.RI "bool \fBactivated\fP"
.br
.RI "Whether the core has been activated\&. "
.ti -1c
.RI "void * \fBgdt_64_base\fP"
.br
.RI "The base of the 64-bit GDT\&. "
.in -1c
.SH "Detailed Description"
.PP 
Information needed when booting a core\&. 
.PP
Definition at line \fB171\fP of file \fBcpu\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool MaxOS::system::CoreBootInfo::activated"

.PP
Whether the core has been activated\&. 
.PP
Definition at line \fB175\fP of file \fBcpu\&.h\fP\&.
.SS "void* MaxOS::system::CoreBootInfo::gdt_64_base"

.PP
The base of the 64-bit GDT\&. 
.PP
Definition at line \fB176\fP of file \fBcpu\&.h\fP\&.
.SS "uint8_t MaxOS::system::CoreBootInfo::id"

.PP
The ID of the core\&. 
.PP
Definition at line \fB174\fP of file \fBcpu\&.h\fP\&.
.SS "uint64_t MaxOS::system::CoreBootInfo::p4_table"

.PP
The physical address of the P4 page table\&. 
.PP
Definition at line \fB173\fP of file \fBcpu\&.h\fP\&.
.SS "uint64_t MaxOS::system::CoreBootInfo::stack"

.PP
The stack pointer for the core\&. 
.PP
Definition at line \fB172\fP of file \fBcpu\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
