.TH "MaxOS::common::EventHandler< EventType >" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::common::EventHandler< EventType > \- Used to handle an event\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <eventHandler\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEventHandler\fP ()"
.br
.ti -1c
.RI "\fB~EventHandler\fP ()"
.br
.ti -1c
.RI "\fBvirtual\fP \fBEvent\fP< \fBEventType\fP > * \fBon_event\fP (\fBEvent\fP< \fBEventType\fP > *\fBevent\fP)"
.br
.RI "This function is called when an event is raised\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBtypename\fP \fBEventType\fP>
.br
class MaxOS::common::EventHandler< EventType >"Used to handle an event\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIEventType\fP The type of event 
.RE
.PP

.PP
Definition at line \fB47\fP of file \fBeventHandler\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<\fBtypename\fP \fBEventType\fP > \fBMaxOS::common::EventHandler\fP< \fBEventType\fP >::EventHandler ()\fC [default]\fP"

.SS "template<\fBtypename\fP \fBEventType\fP > \fBMaxOS::common::EventHandler\fP< \fBEventType\fP >::~\fBEventHandler\fP ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "template<\fBtypename\fP \fBEventType\fP > \fBEvent\fP< \fBEventType\fP > * \fBMaxOS::common::EventHandler\fP< \fBEventType\fP >::on_event (\fBEvent\fP< \fBEventType\fP > * event)\fC [virtual]\fP"

.PP
This function is called when an event is raised\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIEventType\fP The type of event 
.RE
.PP
\fBParameters\fP
.RS 4
\fIevent\fP The event that was raised 
.RE
.PP

.PP
Definition at line \fB94\fP of file \fBeventHandler\&.h\fP\&..PP
.nf
94                                                                                                                 {
95             return event;
96         }
.fi


.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
