.TH "MaxOS::memory::MemoryChunk" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::memory::MemoryChunk \- A span of memory in the heap, can be allocated or free\&. Used as a node in a doubly linked list\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memorymanagement\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMemoryChunk\fP * \fBnext\fP"
.br
.RI "Pointer to the chunk after this one in the list\&. "
.ti -1c
.RI "\fBMemoryChunk\fP * \fBprev\fP"
.br
.RI "Pointer to the chunk before this one in the list\&. "
.ti -1c
.RI "bool \fBallocated\fP"
.br
.RI "Whether this chunk is in use or can be allocated\&. "
.ti -1c
.RI "size_t \fBsize\fP"
.br
.RI "The size of this span of memory (not including the \fBMemoryChunk\fP struct itself) "
.in -1c
.SH "Detailed Description"
.PP 
A span of memory in the heap, can be allocated or free\&. Used as a node in a doubly linked list\&. 
.PP
Definition at line \fB25\fP of file \fBmemorymanagement\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool MaxOS::memory::MemoryChunk::allocated"

.PP
Whether this chunk is in use or can be allocated\&. 
.PP
Definition at line \fB30\fP of file \fBmemorymanagement\&.h\fP\&.
.PP
Referenced by \fBMaxOS::memory::MemoryManager::MemoryManager()\fP\&.
.SS "\fBMemoryChunk\fP* MaxOS::memory::MemoryChunk::next"

.PP
Pointer to the chunk after this one in the list\&. 
.PP
Definition at line \fB27\fP of file \fBmemorymanagement\&.h\fP\&.
.PP
Referenced by \fBMaxOS::memory::MemoryManager::MemoryManager()\fP\&.
.SS "\fBMemoryChunk\fP* MaxOS::memory::MemoryChunk::prev"

.PP
Pointer to the chunk before this one in the list\&. 
.PP
Definition at line \fB28\fP of file \fBmemorymanagement\&.h\fP\&.
.PP
Referenced by \fBMaxOS::memory::MemoryManager::MemoryManager()\fP\&.
.SS "size_t MaxOS::memory::MemoryChunk::size"

.PP
The size of this span of memory (not including the \fBMemoryChunk\fP struct itself) 
.PP
Definition at line \fB31\fP of file \fBmemorymanagement\&.h\fP\&.
.PP
Referenced by \fBMaxOS::memory::MemoryManager::MemoryManager()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
