.TH "MaxOS::hardwarecommunication::Port8Bit" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::Port8Bit \- Handles 8 bit ports\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <port\&.h>\fP
.PP
Inherits \fBMaxOS::hardwarecommunication::Port\fP\&.
.PP
Inherited by \fBMaxOS::hardwarecommunication::Port8BitSlow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPort8Bit\fP (uint16_t port_number)"
.br
.ti -1c
.RI "\fB~Port8Bit\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (uint8_t \fBdata\fP)"
.br
.RI "write a byte to the port "
.ti -1c
.RI "virtual uint8_t \fBread\fP ()"
.br
.RI "read a byte from the port "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::hardwarecommunication::Port\fP
.in +1c
.ti -1c
.RI "\fBPort\fP (uint16_t port_number)"
.br
.ti -1c
.RI "\fB~Port\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBMaxOS::hardwarecommunication::Port\fP
.in +1c
.ti -1c
.RI "uint16_t \fBm_port_number\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles 8 bit ports\&. 
.PP
Definition at line \fB28\fP of file \fBport\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Port8Bit::Port8Bit (uint16_t port_number)"

.PP
Definition at line \fB16\fP of file \fBport\&.cpp\fP\&..PP
.nf
17 : Port(port_number) {
18 }
.fi

.SS "Port8Bit::~Port8Bit ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "uint8_t Port8Bit::read ()\fC [virtual]\fP"

.PP
read a byte from the port 
.PP
\fBReturns\fP
.RS 4
the byte read 
.RE
.PP

.PP
Definition at line \fB37\fP of file \fBport\&.cpp\fP\&..PP
.nf
37                        {
38 
39     uint8_t result;
40     asm volatile("inb %1, %0" : "=a" (result) : "Nd" (m_port_number));
41     return result;
42 }
.fi

.PP
References \fBMaxOS::hardwarecommunication::Port::m_port_number\fP\&.
.PP
Referenced by \fBMaxOS::drivers::peripherals::KeyboardDriver::activate()\fP, \fBMaxOS::drivers::peripherals::MouseDriver::activate()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::flush()\fP, \fBMaxOS::drivers::video::VideoGraphicsArray::get_frame_buffer_segment()\fP, \fBMaxOS::drivers::peripherals::KeyboardDriver::handle_interrupt()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::identify()\fP, \fBMaxOS::drivers::SerialConsole::put_character()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::read()\fP, \fBMaxOS::drivers::clock::Clock::read_hardware_clock()\fP, \fBMaxOS::drivers::SerialConsole::SerialConsole()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::write()\fP, and \fBMaxOS::drivers::video::VideoGraphicsArray::write_registers()\fP\&.
.SS "void Port8Bit::write (uint8_t data)\fC [virtual]\fP"

.PP
write a byte to the port 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP the byte to write 
.RE
.PP

.PP
Reimplemented in \fBMaxOS::hardwarecommunication::Port8BitSlow\fP\&.
.PP
Definition at line \fB27\fP of file \fBport\&.cpp\fP\&..PP
.nf
27                                  {
28 
29     asm volatile("outb %0, %1" : : "a" (data), "Nd" (m_port_number));
30 }
.fi

.PP
References \fBdata\fP, and \fBMaxOS::hardwarecommunication::Port::m_port_number\fP\&.
.PP
Referenced by \fBMaxOS::drivers::peripherals::KeyboardDriver::activate()\fP, \fBMaxOS::drivers::peripherals::MouseDriver::activate()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::flush()\fP, \fBMaxOS::drivers::video::VideoGraphicsArray::get_frame_buffer_segment()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::identify()\fP, \fBMaxOS::drivers::SerialConsole::put_character()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::read()\fP, \fBMaxOS::drivers::clock::Clock::read_hardware_clock()\fP, \fBMaxOS::drivers::SerialConsole::SerialConsole()\fP, \fBMaxOS::drivers::clock::PIT::ticks_per_ms()\fP, \fBMaxOS::drivers::disk::AdvancedTechnologyAttachment::write()\fP, and \fBMaxOS::drivers::video::VideoGraphicsArray::write_registers()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
