.TH "MaxOS::drivers::SerialConsole" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::drivers::SerialConsole \- A driver for the serial output\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <serial\&.h>\fP
.PP
Inherits \fBMaxOS::drivers::Driver\fP, and \fBMaxOS::common::OutputStream\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSerialConsole\fP (\fBLogger\fP *logger)"
.br
.RI "Constructs a new Serial Console object and initializes the serial port\&. "
.ti -1c
.RI "void \fBput_character\fP (char c)"
.br
.RI "Waits for the serial port to be ready, then writes a character to it\&. "
.ti -1c
.RI "void \fBwrite_char\fP (char c) final"
.br
.RI "Writes a character to the output stream\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::drivers::Driver\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBactivate\fP ()"
.br
.RI "activate the driver "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBdeactivate\fP ()"
.br
.RI "deactivate the driver "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBinitialise\fP ()"
.br
.RI "Initialise the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBuint32_t\fP \fBreset\fP ()"
.br
.RI "Reset the driver\&. "
.ti -1c
.RI "\fBvirtual\fP \fBstring\fP \fBvendor_name\fP ()"
.br
.RI "Get who created the device\&. "
.ti -1c
.RI "\fBvirtual\fP \fBstring\fP \fBdevice_name\fP ()"
.br
.RI "Get the device name of the driver\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::OutputStream\fP
.in +1c
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBline_feed\fP ()"
.br
.RI "Writes a newline to the output stream\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBcarriageReturn\fP ()"
.br
.RI "Writes a carriage return to the output stream\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBclear\fP ()"
.br
.RI "Clears the output stream\&. "
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBstring\fP \fBstring_to_write\fP) \fBoverride\fP"
.br
.RI "Writes a string to the output stream\&. "
.ti -1c
.RI "\fBvoid\fP \fBwrite\fP (\fBconst\fP \fBchar\fP *\fBstring_to_write\fP)"
.br
.RI "Writes a string to the output stream\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBwrite_int\fP (\fBint\fP \fBint_to_write\fP)"
.br
.RI "Writes an integer to the output stream\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBwrite_hex\fP (\fBuint64_t\fP \fBhex_to_write\fP)"
.br
.RI "Writes a hex to the output stream\&. "
.ti -1c
.RI "\fBOutputStream\fP & \fBoperator<<\fP (\fBstring\fP \fBstring_to_write\fP) \fBoverride\fP"
.br
.RI "Writes a string to the output stream\&. "
.ti -1c
.RI "\fBOutputStream\fP & \fBoperator<<\fP (\fBconst\fP \fBchar\fP *\fBstring_to_write\fP)"
.br
.RI "Writes a string to the output stream\&. "
.ti -1c
.RI "\fBOutputStream\fP & \fBoperator<<\fP (\fBint\fP \fBint_to_write\fP)"
.br
.RI "Writes a integer to the output stream\&. "
.ti -1c
.RI "\fBOutputStream\fP & \fBoperator<<\fP (\fBuint64_t\fP \fBhex_to_write\fP)"
.br
.RI "Writes a hexadecimal to the output stream\&. "
.ti -1c
.RI "\fBOutputStream\fP & \fBoperator<<\fP (\fBchar\fP \fBchar_to_write\fP)"
.br
.RI "Writes a character to the output stream\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::GenericOutputStream< string >\fP
.in +1c
.ti -1c
.RI "\fBGenericOutputStream\fP ()"
.br
.RI "__________________________________________Templates__________________________________________________/// "
.ti -1c
.RI "\fB~GenericOutputStream\fP ()"
.br
.RI "Destructor of the \fBGenericOutputStream\fP class\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_stream_read\fP (\fBstring\fP) \fBoverride\fP"
.br
.RI "Writes the date that was read from the input stream to the output stream\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_end_of_stream\fP (\fBGenericInputStream\fP< \fBstring\fP > *) \fBoverride\fP"
.br
.RI "Close the stream and remove it from the list of streams when the end of the stream is reached\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBwrite\fP (\fBstring\fP)"
.br
.RI "write an element to the stream\&. "
.ti -1c
.RI "\fBvirtual\fP \fBvoid\fP \fBclose\fP ()"
.br
.RI "Close the stream\&. "
.ti -1c
.RI "\fBvirtual\fP \fBGenericOutputStream\fP< \fBstring\fP > & \fBoperator<<\fP (\fBstring\fP)"
.br
.RI "Overload the << operator to write an element to the stream\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::InputStreamProcessor< Type, ProcessorType >\fP
.in +1c
.ti -1c
.RI "\fBInputStreamProcessor\fP ()"
.br
.RI "Creates a new \fBInputStreamProcessor\fP\&. "
.ti -1c
.RI "\fBInputStreamProcessor\fP (\fBInputStreamEventHandler\fP< \fBProcessorType\fP > *\fBgeneric_stream_event_handler\fP)"
.br
.RI "Creates a new \fBInputStreamProcessor\fP\&. "
.ti -1c
.RI "\fB~InputStreamProcessor\fP ()"
.br
.RI "Destroys the \fBInputStreamProcessor\fP\&. "
.ti -1c
.RI "\fBvoid\fP \fBon_end_of_stream\fP (\fBGenericInputStream\fP< \fBType\fP > *\fBstream\fP) \fBoverride\fP"
.br
.RI "Called when a stream has finished\&. Passes the event on to the handlers and then removes the stream from the array of streams\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::InputStreamEventHandler< Type >\fP
.in +1c
.ti -1c
.RI "\fBInputStreamEventHandler\fP ()"
.br
.RI "_______________________________________________TEMPLATES_________________________________________________________________/// "
.ti -1c
.RI "\fB~InputStreamEventHandler\fP ()"
.br
.RI "Destroys the \fBInputStreamProcessor\fP and disconnects it from all streams\&. "
.in -1c

Public Member Functions inherited from \fBMaxOS::common::GenericInputStream< ProcessorType >\fP
.in +1c
.ti -1c
.RI "\fBGenericInputStream\fP ()"
.br
.RI "Creates a new \fBGenericInputStream\fP\&. "
.ti -1c
.RI "\fBGenericInputStream\fP (\fBInputStreamEventHandler\fP< \fBProcessorType\fP > *)"
.br
.RI "Creates a new \fBGenericInputStream\fP and connects it to the handler\&. "
.ti -1c
.RI "\fB~GenericInputStream\fP ()"
.br
.RI "Destroys the \fBGenericInputStream\fP and disconnects all handlers\&. "
.ti -1c
.RI "\fBvoid\fP \fBconnect_input_stream_event_handler\fP (\fBInputStreamEventHandler\fP< \fBProcessorType\fP > *)"
.br
.RI "Adds a inputStreamEventHandler to the list of internetProtocolHandlers\&. "
.ti -1c
.RI "\fBvoid\fP \fBdisconnect_input_stream_event_handler\fP (\fBInputStreamEventHandler\fP< \fBProcessorType\fP > *)"
.br
.RI "Removes a handler from the list of handlers\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBMaxOS::common::InputStreamEventHandler< Type >\fP
.in +1c
.ti -1c
.RI "\fBcommon::Vector\fP< \fBGenericInputStream\fP< \fBType\fP > * > \fBm_generic_input_streams\fP"
.br
.RI "List of streams being observed by this handler\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::common::GenericInputStream< ProcessorType >\fP
.in +1c
.ti -1c
.RI "\fBcommon::Vector\fP< \fBInputStreamEventHandler\fP< \fBProcessorType\fP > * > \fBm_input_stream_event_handlers\fP"
.br
.RI "List of streams being observed by this handler\&. "
.in -1c
.SH "Detailed Description"
.PP 
A driver for the serial output\&. 
.PP
Definition at line \fB25\fP of file \fBserial\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "SerialConsole::SerialConsole (\fBLogger\fP * logger)"

.PP
Constructs a new Serial Console object and initializes the serial port\&. 
.PP
\fBParameters\fP
.RS 4
\fIlogger\fP The logger which will use this serial console as a log writer 
.RE
.PP

.PP
Definition at line \fB18\fP of file \fBserial\&.cpp\fP\&..PP
.nf
19 : m_data_port(0x3F8),
20   m_interrupt_enable_port(0x3F9),
21   m_fifo_control_port(0x3FA),
22   m_line_control_port(0x3FB),
23   m_modem_control_port(0x3FC),
24   m_line_status_port(0x3FD)
25 {
26 
27     // Disable all interrupts
28     m_interrupt_enable_port\&.write(0x00);
29 
30     // Enable DLAB (set baud rate divisor)
31     m_line_control_port\&.write(0x80);
32 
33     // Set divisor to 3
34     m_data_port\&.write(0x03);
35     m_interrupt_enable_port\&.write(0x00);
36 
37     // 8 bits, no parity, one stop bit
38     m_line_control_port\&.write(0x03);
39 
40     // Enable FIFO, clear them, with 14\-byte threshold
41     m_fifo_control_port\&.write(0xC7);
42 
43     // IRQs enabled, RTS/DSR set
44     m_modem_control_port\&.write(0x0B);
45 
46     // Test serial chip
47     m_modem_control_port\&.write(0x1E);
48     m_data_port\&.write(0xAE);
49     if (m_data_port\&.read() != 0xAE)
50         return;
51 
52     // Enable serial chip
53     m_modem_control_port\&.write(0x0F);
54 
55     // Set the active serial console
56     logger\->add_log_writer(this);
57 }
.fi

.PP
References \fBLogger::add_log_writer()\fP, \fBMaxOS::hardwarecommunication::Port8Bit::read()\fP, and \fBMaxOS::hardwarecommunication::Port8Bit::write()\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void SerialConsole::put_character (char c)"

.PP
Waits for the serial port to be ready, then writes a character to it\&. 
.PP
\fBParameters\fP
.RS 4
\fIc\fP The character to write 
.RE
.PP

.PP
Definition at line \fB66\fP of file \fBserial\&.cpp\fP\&..PP
.nf
66                                         {
67 
68     // Wait for the serial port to be ready
69     while (0 == (m_line_status_port\&.read() & 0x20));
70 
71     // Write the character
72     m_data_port\&.write(c);
73 
74 }
.fi

.PP
References \fBMaxOS::hardwarecommunication::Port8Bit::read()\fP, and \fBMaxOS::hardwarecommunication::Port8Bit::write()\fP\&.
.PP
Referenced by \fBwrite_char()\fP\&.
.SS "void SerialConsole::write_char (char char_to_write)\fC [final]\fP, \fC [virtual]\fP"

.PP
Writes a character to the output stream\&. 
.PP
\fBParameters\fP
.RS 4
\fIchar_to_write\fP The character to write to the output stream\&. 
.RE
.PP

.PP
Reimplemented from \fBMaxOS::common::OutputStream\fP\&.
.PP
Definition at line \fB76\fP of file \fBserial\&.cpp\fP\&..PP
.nf
76                                      {
77     put_character(c);
78 }
.fi

.PP
References \fBput_character()\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
