.TH "MaxOS::memory::PageTableEntry" 3 "Sun Oct 13 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::memory::PageTableEntry
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <physical\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBpresent\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBwrite\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBuser\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBwrite_through\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBcache_disabled\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBaccessed\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBdirty\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBhuge_page\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBglobal\fP: 1"
.br
.ti -1c
.RI "uint64_t \fBavailable\fP: 3"
.br
.ti -1c
.RI "uint64_t \fBphysical_address\fP: 52"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 44 of file physical\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint64_t MaxOS::memory::PageTableEntry::accessed"

.PP
Definition at line 50 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::available"

.PP
Definition at line 54 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::cache_disabled"

.PP
Definition at line 49 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::dirty"

.PP
Definition at line 51 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::global"

.PP
Definition at line 53 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::huge_page"

.PP
Definition at line 52 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::physical_address"

.PP
Definition at line 55 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::present"

.PP
Definition at line 45 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::user"

.PP
Definition at line 47 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::write"

.PP
Definition at line 46 of file physical\&.h\&.
.SS "uint64_t MaxOS::memory::PageTableEntry::write_through"

.PP
Definition at line 48 of file physical\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
