.TH "MaxOS::filesystem::format::ext2::DirectoryEntry" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::format::ext2::DirectoryEntry \- An entry in a directory that points to a file or subdirectory (the name follows this struct)  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ext2\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBinode\fP"
.br
.RI "The inode number this entry points to (0 = unused) "
.ti -1c
.RI "uint16_t \fBsize\fP"
.br
.RI "The total size of this entry (including name) "
.ti -1c
.RI "uint8_t \fBname_length\fP"
.br
.RI "The length of the name\&. "
.ti -1c
.RI "uint8_t \fBtype\fP"
.br
.RI "The type of the entry (see EntryType) (only if the high bit of the superblock's optional_features is set) "
.in -1c
.SH "Detailed Description"
.PP 
An entry in a directory that points to a file or subdirectory (the name follows this struct) 
.PP
Definition at line \fB276\fP of file \fBext2\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t MaxOS::filesystem::format::ext2::DirectoryEntry::inode"

.PP
The inode number this entry points to (0 = unused) 
.PP
Definition at line \fB277\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::DirectoryEntry::name_length"

.PP
The length of the name\&. 
.PP
Definition at line \fB279\fP of file \fBext2\&.h\fP\&.
.SS "uint16_t MaxOS::filesystem::format::ext2::DirectoryEntry::size"

.PP
The total size of this entry (including name) 
.PP
Definition at line \fB278\fP of file \fBext2\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::ext2::DirectoryEntry::type"

.PP
The type of the entry (see EntryType) (only if the high bit of the superblock's optional_features is set) 
.PP
Definition at line \fB280\fP of file \fBext2\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
