.TH "MaxOS::hardwarecommunication::ACPISDTHeader" 3 "Sun Oct 13 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::ACPISDTHeader
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <acpi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBsignature\fP [4]"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.ti -1c
.RI "uint8_t \fBrevision\fP"
.br
.ti -1c
.RI "uint8_t \fBchecksum\fP"
.br
.ti -1c
.RI "char \fBOEM_id\fP [6]"
.br
.ti -1c
.RI "char \fBOEM_table_id\fP [8]"
.br
.ti -1c
.RI "uint32_t \fBOEM_revision\fP"
.br
.ti -1c
.RI "uint32_t \fBcreator_id\fP"
.br
.ti -1c
.RI "uint32_t \fBcreator_revision\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 34 of file acpi\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::hardwarecommunication::ACPISDTHeader::checksum"

.PP
Definition at line 38 of file acpi\&.h\&.
.SS "uint32_t MaxOS::hardwarecommunication::ACPISDTHeader::creator_id"

.PP
Definition at line 42 of file acpi\&.h\&.
.SS "uint32_t MaxOS::hardwarecommunication::ACPISDTHeader::creator_revision"

.PP
Definition at line 43 of file acpi\&.h\&.
.SS "uint32_t MaxOS::hardwarecommunication::ACPISDTHeader::length"

.PP
Definition at line 36 of file acpi\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::IOAPIC::init(), and print_boot_header()\&.
.SS "char MaxOS::hardwarecommunication::ACPISDTHeader::OEM_id[6]"

.PP
Definition at line 39 of file acpi\&.h\&.
.SS "uint32_t MaxOS::hardwarecommunication::ACPISDTHeader::OEM_revision"

.PP
Definition at line 41 of file acpi\&.h\&.
.SS "char MaxOS::hardwarecommunication::ACPISDTHeader::OEM_table_id[8]"

.PP
Definition at line 40 of file acpi\&.h\&.
.SS "uint8_t MaxOS::hardwarecommunication::ACPISDTHeader::revision"

.PP
Definition at line 37 of file acpi\&.h\&.
.SS "char MaxOS::hardwarecommunication::ACPISDTHeader::signature[4]"

.PP
Definition at line 35 of file acpi\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::find()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
