.TH "MaxOS::memory::MemIO16Bit" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::memory::MemIO16Bit \- Handles 16 bit memory IO\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memoryIO\&.h>\fP
.PP
Inherits \fBMaxOS::memory::MemIO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemIO16Bit\fP (uintptr_t address)"
.br
.RI "Construct a new Mem IO object for 16 bit reads/writes\&. "
.ti -1c
.RI "virtual void \fBwrite\fP (uint16_t data)"
.br
.RI "Writes data to the memory address\&. "
.ti -1c
.RI "virtual uint16_t \fBread\fP ()"
.br
.RI "Reads data from the memory address\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::memory::MemIO\fP
.in +1c
.ti -1c
.RI "\fBMemIO\fP (uintptr_t address)"
.br
.RI "Construct a new Mem IO object\&. "
.in -1c

Protected Attributes inherited from \fBMaxOS::memory::MemIO\fP
.in +1c
.ti -1c
.RI "uintptr_t \fBm_address\fP"
.br
.RI "The memory address to read from / write to\&. "
.in -1c
.SH "Detailed Description"
.PP 
Handles 16 bit memory IO\&. 
.PP
Definition at line \fB49\fP of file \fBmemoryIO\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MemIO16Bit::MemIO16Bit (uintptr_t address)\fC [explicit]\fP"

.PP
Construct a new Mem IO object for 16 bit reads/writes\&. 
.PP
\fBParameters\fP
.RS 4
\fIaddress\fP The memory address to read from / write to 
.RE
.PP

.PP
Definition at line \fB63\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
64 : MemIO(address)
65 {
66 }
.fi

.SH "Member Function Documentation"
.PP 
.SS "uint16_t MemIO16Bit::read ()\fC [virtual]\fP"

.PP
Reads data from the memory address\&. 
.PP
\fBReturns\fP
.RS 4
the data read 
.RE
.PP

.PP
Definition at line \fB85\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
85                           {
86 
87     return *((volatile uint16_t*) (m_address));
88 }
.fi

.PP
References \fBMaxOS::memory::MemIO::m_address\fP\&.
.SS "void MemIO16Bit::write (uint16_t data)\fC [virtual]\fP"

.PP
Writes data to the memory address\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP the data to write 
.RE
.PP

.PP
Definition at line \fB75\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
75                                     {
76 
77     (*((volatile uint16_t*) (m_address))) = (data);
78 }
.fi

.PP
References \fBMaxOS::memory::MemIO::m_address\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
