.TH "MaxOS" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBcommon\fP"
.br
.ti -1c
.RI "namespace \fBdrivers\fP"
.br
.ti -1c
.RI "namespace \fBfilesystem\fP"
.br
.ti -1c
.RI "namespace \fBgui\fP"
.br
.ti -1c
.RI "namespace \fBhardwarecommunication\fP"
.br
.ti -1c
.RI "namespace \fBmemory\fP"
.br
.ti -1c
.RI "namespace \fBnet\fP"
.br
.ti -1c
.RI "namespace \fBprocesses\fP"
.br
.ti -1c
.RI "namespace \fBruntime\fP"
.br
.ti -1c
.RI "namespace \fBsystem\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBString\fP"
.br
.RI "Dynamically sized string with various operations\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBString\fP \fBstring\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBString\fP \fBMaxOS::string\fP"

.PP
Definition at line \fB81\fP of file \fBstring\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
