.TH "MaxOS::common::Map< Key, Value >" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::common::Map< Key, Value > \- A list of key-value pairs\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <map\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBVector\fP< \fBPair\fP< \fBKey\fP, \fBValue\fP > >::iterator \fBiterator\fP"
.br
.RI "The iterator type for the map\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBValue\fP & \fBoperator[]\fP (\fBKey\fP)"
.br
.RI "Overloads the [] operator to return the value of the key\&. "
.ti -1c
.RI "\fBbool\fP \fBempty\fP ()"
.br
.RI "Returns whether the map is empty\&. "
.ti -1c
.RI "\fBint\fP \fBsize\fP ()"
.br
.RI "The number of elements in the map\&. "
.ti -1c
.RI "\fBiterator\fP \fBbegin\fP ()"
.br
.RI "Returns the beginning of the map\&. "
.ti -1c
.RI "\fBiterator\fP \fBend\fP ()"
.br
.RI "Returns the end of the map\&. "
.ti -1c
.RI "\fBiterator\fP \fBfind\fP (\fBKey\fP)"
.br
.RI "Finds an element in the map based on the key\&. "
.ti -1c
.RI "\fBiterator\fP \fBpush_back\fP (\fBKey\fP, \fBValue\fP)"
.br
.RI "Adds a new key-value pair to the end of the map\&. "
.ti -1c
.RI "\fBPair\fP< \fBKey\fP, \fBValue\fP > \fBpop_back\fP ()"
.br
.RI "Removes the last key-value pair from the map and returns it\&. "
.ti -1c
.RI "\fBiterator\fP \fBpush_front\fP (\fBKey\fP, \fBValue\fP)"
.br
.RI "Adds a new key-value pair to the front of the map\&. "
.ti -1c
.RI "\fBPair\fP< \fBKey\fP, \fBValue\fP > \fBpop_front\fP ()"
.br
.RI "Removes the first key-value pair from the map and returns it\&. "
.ti -1c
.RI "\fBvoid\fP \fBinsert\fP (\fBKey\fP, \fBValue\fP)"
.br
.RI "Updates the value of an element, or adds a new element if it does not exist\&. "
.ti -1c
.RI "\fBvoid\fP \fBerase\fP (\fBKey\fP)"
.br
.RI "Removes an element from the map\&. "
.ti -1c
.RI "\fBvoid\fP \fBerase\fP (\fBiterator\fP position)"
.br
.RI "Removes an element from the map at the specified position\&. "
.ti -1c
.RI "\fBvoid\fP \fBclear\fP ()"
.br
.RI "Removes all elements from the map\&. "
.ti -1c
.RI "\fBvoid\fP \fBreserve\fP (\fBsize_t\fP \fBamount\fP)"
.br
.RI "Reserves space in the map for a certain amount of elements to avoid reallocations\&. "
.ti -1c
.RI "\fBvoid\fP \fBincrease_size\fP ()"
.br
.RI "Doubles the size of the map\&. "
.ti -1c
.RI "\fBvoid\fP \fBiterate\fP (\fBMapIterationHandler\fP< \fBKey\fP, \fBValue\fP > *\fBhandler\fP)"
.br
.RI "Iterates through the map and calls the handler\&. "
.ti -1c
.RI "\fBvoid\fP \fBiterate\fP (\fBvoid\fP(*\fBcallback\fP)(\fBKey\fP &, \fBValue\fP &))"
.br
.RI "Iterates through the map and calls the callback\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBVector\fP< \fBPair\fP< \fBKey\fP, \fBValue\fP > > \fBm_elements\fP"
.br
.RI "The internal storage of the map, a vector of key-value pairs\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<\fBclass\fP \fBKey\fP, \fBclass\fP \fBValue\fP>
.br
class MaxOS::common::Map< Key, Value >"A list of key-value pairs\&. 


.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP

.PP
Definition at line \fB43\fP of file \fBmap\&.h\fP\&.
.SH "Member Typedef Documentation"
.PP 
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBtypedef\fP \fBVector\fP<\fBPair\fP<\fBKey\fP,\fBValue\fP>>::iterator \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::iterator"

.PP
The iterator type for the map\&. 
.PP
Definition at line \fB49\fP of file \fBmap\&.h\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBMap\fP< \fBKey\fP, \fBValue\fP >\fB::iterator\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::begin ()"

.PP
Returns the beginning of the map\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBReturns\fP
.RS 4
The m_first_memory_chunk element in the map 
.RE
.PP

.PP
Definition at line \fB133\fP of file \fBmap\&.h\fP\&..PP
.nf
133                                                                                                  {
134             return m_elements\&.begin();
135         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::begin()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBvoid\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::clear ()"

.PP
Removes all elements from the map\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP

.PP
Definition at line \fB245\fP of file \fBmap\&.h\fP\&..PP
.nf
245                                                                      {
246           m_elements\&.clear();
247         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::clear()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBbool\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::empty ()"

.PP
Returns whether the map is empty\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBReturns\fP
.RS 4
Whether the map is empty 
.RE
.PP

.PP
Definition at line \fB223\fP of file \fBmap\&.h\fP\&..PP
.nf
223                                                                      {
224             return m_elements\&.empty();
225         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::empty()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBMap\fP< \fBKey\fP, \fBValue\fP >\fB::iterator\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::end ()"

.PP
Returns the end of the map\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBReturns\fP
.RS 4
The last element in the map 
.RE
.PP

.PP
Definition at line \fB144\fP of file \fBmap\&.h\fP\&..PP
.nf
144                                                                                                {
145             return m_elements\&.end();
146         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::end()\fP\&.
.PP
Referenced by \fBMaxOS::processes::SharedMemory::open()\fP, \fBMaxOS::processes::SharedMemory::read()\fP, and \fBMaxOS::net::AddressResolutionProtocol::Resolve()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBvoid\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::erase (\fBMap\fP< \fBKey\fP, \fBValue\fP >\fB::iterator\fP position)"

.PP
Removes an element from the map at the specified position\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIposition\fP The iterator of the element to remove 
.RE
.PP

.PP
Definition at line \fB297\fP of file \fBmap\&.h\fP\&..PP
.nf
297                                                                                          {
298             m_elements\&.erase(position);
299 
300         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::erase()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBvoid\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::erase (\fBKey\fP key)"

.PP
Removes an element from the map\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The key of the element to remove 
.RE
.PP

.PP
Definition at line \fB278\fP of file \fBmap\&.h\fP\&..PP
.nf
278                                                                             {
279 
280             // Find the element
281             iterator it = find(key);
282 
283             // If the element is found then remove it
284             if (it != end()) {
285                 m_elements\&.erase(it);
286             }
287 
288         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::erase()\fP\&.
.PP
Referenced by \fBMaxOS::processes::BaseResourceRegistry::close_resource()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBMap\fP< \fBKey\fP, \fBValue\fP >\fB::iterator\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::find (\fBKey\fP element)"

.PP
Finds an element in the map based on the key\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIelement\fP The key to search for 
.RE
.PP
\fBReturns\fP
.RS 4
The iterator of the element, or the end iterator if not found 
.RE
.PP

.PP
Definition at line \fB156\fP of file \fBmap\&.h\fP\&..PP
.nf
156                                                                                                            {
157 
158             // Search for the element
159             for (iterator it = begin(); it != end(); it++)
160                 if (it \-> first == element)
161                     return it;
162 
163             // Item not found
164             return end();
165 
166         }
.fi

.PP
Referenced by \fBMaxOS::processes::SharedMemory::open()\fP, \fBMaxOS::processes::SharedMemory::read()\fP, and \fBMaxOS::net::AddressResolutionProtocol::Resolve()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBvoid\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::increase_size ()"

.PP
Doubles the size of the map\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP

.PP
Definition at line \fB319\fP of file \fBmap\&.h\fP\&..PP
.nf
319                                                                              {
320             m_elements\&.increase_size();
321         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::increase_size()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBvoid\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::insert (\fBKey\fP key, \fBValue\fP value)"

.PP
Updates the value of an element, or adds a new element if it does not exist\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The key of the new element 
.br
\fIvalue\fP The value of the new element 
.RE
.PP

.PP
Definition at line \fB257\fP of file \fBmap\&.h\fP\&..PP
.nf
257                                                                                           {
258 
259             // Find the element
260             iterator it = find(key);
261 
262             // If the element is found then update the value
263             if (it != end()) {
264                 it \-> second = value;
265             } else {
266                 // Otherwise, add a new element
267                 m_elements\&.push_back(Pair<Key, Value>(key, value));
268             }
269         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::push_back()\fP\&.
.PP
Referenced by \fBMaxOS::processes::GlobalScheduler::add_process()\fP, \fBMaxOS::processes::GlobalScheduler::add_thread()\fP, \fBMaxOS::net::AddressResolutionProtocol::handleEthernetframePayload()\fP, \fBMaxOS::processes::SharedMemory::open()\fP, \fBMaxOS::processes::BaseResourceRegistry::register_resource()\fP, and \fBMaxOS::net::AddressResolutionProtocol::Store()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBvoid\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::iterate (\fBMapIterationHandler\fP< \fBKey\fP, \fBValue\fP > * handler)"

.PP
Iterates through the map and calls the handler\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIhandler\fP The handler to call 
.RE
.PP

.PP
Definition at line \fB330\fP of file \fBmap\&.h\fP\&..PP
.nf
330                                                                                                                {
331 
332             // Loop through the elements
333             for(auto& it : m_elements) {
334 
335                 // Call the handler
336                 handler\->on_read(it\&.first, it\&.second);
337             }
338 
339             // Call the handler
340             handler\->on_end_of_stream();
341 
342         }
.fi

.PP
References \fBMaxOS::common::MapIterationHandler< Key, Value >::on_end_of_stream()\fP, and \fBMaxOS::common::MapIterationHandler< Key, Value >::on_read()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBvoid\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::iterate (\fBvoid\fP(*)(\fBKey\fP &, \fBValue\fP &) callback)"

.PP
Iterates through the map and calls the callback\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIcallback\fP The callback to call 
.RE
.PP

.PP
Definition at line \fB351\fP of file \fBmap\&.h\fP\&..PP
.nf
351                                                                                                        {
352 
353             // Call the callback for each element
354             for(auto& it : m_elements) {
355                     callback(it\&.first, it\&.second);
356             }
357         }
.fi

.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBValue\fP & \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::operator[] (\fBKey\fP key)"

.PP
Overloads the [] operator to return the value of the key\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The key to search for 
.RE
.PP
\fBReturns\fP
.RS 4
The value of the key 
.RE
.PP

.PP
Definition at line \fB120\fP of file \fBmap\&.h\fP\&..PP
.nf
120                                                                                    {
121 
122             // Return the value of the key (second item in the pair)
123             return find(key) \-> second;
124         }
.fi

.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBPair\fP< \fBKey\fP, \fBValue\fP > \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::pop_back ()"

.PP
Removes the last key-value pair from the map and returns it\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB188\fP of file \fBmap\&.h\fP\&..PP
.nf
188                                                                                     {
189             return m_elements\&.pop_back();
190         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::pop_back()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBPair\fP< \fBKey\fP, \fBValue\fP > \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::pop_front ()"

.PP
Removes the first key-value pair from the map and returns it\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBReturns\fP
.RS 4
The removed key-value pair 
.RE
.PP

.PP
Definition at line \fB212\fP of file \fBmap\&.h\fP\&..PP
.nf
212                                                                                      {
213             return m_elements\&.pop_front();
214         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::pop_front()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBMap\fP< \fBKey\fP, \fBValue\fP >\fB::iterator\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::push_back (\fBKey\fP key, \fBValue\fP value)"

.PP
Adds a new key-value pair to the end of the map\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The key 
.br
\fIvalue\fP The value 
.RE
.PP
\fBReturns\fP
.RS 4
The iterator of the new element 
.RE
.PP

.PP
Definition at line \fB177\fP of file \fBmap\&.h\fP\&..PP
.nf
177                                                                                                                 {
178             return m_elements\&.push_back(Pair<Key, Value>(key, value));
179         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::push_back()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBMap\fP< \fBKey\fP, \fBValue\fP >\fB::iterator\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::push_front (\fBKey\fP key, \fBValue\fP value)"

.PP
Adds a new key-value pair to the front of the map\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIkey\fP The key 
.br
\fIvalue\fP The value 
.RE
.PP
\fBReturns\fP
.RS 4
.RE
.PP

.PP
Definition at line \fB201\fP of file \fBmap\&.h\fP\&..PP
.nf
201                                                                                                                  {
202             return m_elements\&.push_front({key, value});
203         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::push_front()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBvoid\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::reserve (\fBsize_t\fP amount)"

.PP
Reserves space in the map for a certain amount of elements to avoid reallocations\&. 
.PP
\fBTemplate Parameters\fP
.RS 4
\fIKey\fP The key type 
.br
\fIValue\fP The value type 
.RE
.PP
\fBParameters\fP
.RS 4
\fIamount\fP The amount of elements to reserve space for 
.RE
.PP

.PP
Definition at line \fB309\fP of file \fBmap\&.h\fP\&..PP
.nf
309                                                                                     {
310             m_elements\&.reserve(amount);
311         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::reserve()\fP\&.
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBint\fP \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::size ()"

.PP
The number of elements in the map\&. 
.PP
\fBReturns\fP
.RS 4
The number of elements in the \fBMap\fP 
.RE
.PP

.PP
Definition at line \fB232\fP of file \fBmap\&.h\fP\&..PP
.nf
233         {
234             // Return the size of the vector
235             return m_elements\&.size();
236 
237         }
.fi

.PP
References \fBMaxOS::common::Vector< Type >::size()\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<\fBclass\fP \fBKey\fP , \fBclass\fP \fBValue\fP > \fBVector\fP<\fBPair\fP<\fBKey\fP, \fBValue\fP> > \fBMaxOS::common::Map\fP< \fBKey\fP, \fBValue\fP >::m_elements\fC [protected]\fP"

.PP
The internal storage of the map, a vector of key-value pairs\&. 
.PP
Definition at line \fB46\fP of file \fBmap\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
