.TH "MaxOS::net::ARPMessage" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::net::ARPMessage \- An ARP message\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <arp\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint16_t \fBhardware_type\fP"
.br
.RI "The type of device that sent the ARP message (1 = Ethernet) "
.ti -1c
.RI "uint16_t \fBprotocol\fP"
.br
.RI "The protocol being used (0x0800 = IPv4) "
.ti -1c
.RI "uint8_t \fBhardware_address_size\fP"
.br
.RI "The size of the hardware address (6 for MAC) "
.ti -1c
.RI "uint8_t \fBprotocol_address_size\fP"
.br
.RI "The size of the protocol address (4 for IPv4) "
.ti -1c
.RI "uint16_t \fBcommand\fP"
.br
.RI "The ARP command (1 = request, 2 = reply) "
.ti -1c
.RI "uint64_t \fBsrc_mac\fP: 48"
.br
.RI "The MAC address of the sender\&. "
.ti -1c
.RI "uint32_t \fBsrc_ip\fP"
.br
.RI "The IP address of the sender\&. "
.ti -1c
.RI "uint64_t \fBdst_mac\fP: 48"
.br
.RI "The MAC address of the target\&. "
.ti -1c
.RI "uint32_t \fBdst_ip\fP"
.br
.RI "The IP address of the target\&. "
.in -1c
.SH "Detailed Description"
.PP 
An ARP message\&. 
.PP
Definition at line \fB26\fP of file \fBarp\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint16_t MaxOS::net::ARPMessage::command"

.PP
The ARP command (1 = request, 2 = reply) 
.PP
Definition at line \fB33\fP of file \fBarp\&.h\fP\&.
.SS "uint32_t MaxOS::net::ARPMessage::dst_ip"

.PP
The IP address of the target\&. 
.PP
Definition at line \fB38\fP of file \fBarp\&.h\fP\&.
.SS "uint64_t MaxOS::net::ARPMessage::dst_mac"

.PP
The MAC address of the target\&. 
.PP
Definition at line \fB37\fP of file \fBarp\&.h\fP\&.
.PP
Referenced by \fBMaxOS::net::AddressResolutionProtocol::request_mac_address()\fP\&.
.SS "uint8_t MaxOS::net::ARPMessage::hardware_address_size"

.PP
The size of the hardware address (6 for MAC) 
.PP
Definition at line \fB30\fP of file \fBarp\&.h\fP\&.
.SS "uint16_t MaxOS::net::ARPMessage::hardware_type"

.PP
The type of device that sent the ARP message (1 = Ethernet) 
.PP
Definition at line \fB28\fP of file \fBarp\&.h\fP\&.
.SS "uint16_t MaxOS::net::ARPMessage::protocol"

.PP
The protocol being used (0x0800 = IPv4) 
.PP
Definition at line \fB29\fP of file \fBarp\&.h\fP\&.
.SS "uint8_t MaxOS::net::ARPMessage::protocol_address_size"

.PP
The size of the protocol address (4 for IPv4) 
.PP
Definition at line \fB31\fP of file \fBarp\&.h\fP\&.
.SS "uint32_t MaxOS::net::ARPMessage::src_ip"

.PP
The IP address of the sender\&. 
.PP
Definition at line \fB36\fP of file \fBarp\&.h\fP\&.
.SS "uint64_t MaxOS::net::ARPMessage::src_mac"

.PP
The MAC address of the sender\&. 
.PP
Definition at line \fB35\fP of file \fBarp\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
