.TH "MaxOS::memory::MemIO32Bit" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::memory::MemIO32Bit \- Handles 32 bit memory IO\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memoryIO\&.h>\fP
.PP
Inherits \fBMaxOS::memory::MemIO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemIO32Bit\fP (uintptr_t \fBaddress\fP)"
.br
.ti -1c
.RI "\fB~MemIO32Bit\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (uint32_t \fBdata\fP)"
.br
.RI "Writes data to the memory address\&. "
.ti -1c
.RI "virtual uint32_t \fBread\fP ()"
.br
.RI "Reads data from the memory address\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBMaxOS::memory::MemIO\fP
.in +1c
.ti -1c
.RI "\fBMemIO\fP (uintptr_t \fBaddress\fP)"
.br
.ti -1c
.RI "\fB~MemIO\fP ()"
.br
.in -1c

Protected Attributes inherited from \fBMaxOS::memory::MemIO\fP
.in +1c
.ti -1c
.RI "uintptr_t \fBm_address\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Handles 32 bit memory IO\&. 
.PP
Definition at line \fB56\fP of file \fBmemoryIO\&.h\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MemIO32Bit::MemIO32Bit (uintptr_t address)"

.PP
Definition at line \fB71\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
72 : MemIO(address)
73 {
74 }
.fi

.SS "MemIO32Bit::~MemIO32Bit ()\fC [default]\fP"

.SH "Member Function Documentation"
.PP 
.SS "uint32_t MemIO32Bit::read ()\fC [virtual]\fP"

.PP
Reads data from the memory address\&. 
.PP
\fBReturns\fP
.RS 4
the data read 
.RE
.PP

.PP
Definition at line \fB93\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
93                           {
94 
95     return *((volatile uint32_t*) (m_address));
96 }
.fi

.PP
References \fBMaxOS::memory::MemIO::m_address\fP\&.
.SS "void MemIO32Bit::write (uint32_t data)\fC [virtual]\fP"

.PP
Writes data to the memory address\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP the data to write 
.RE
.PP

.PP
Definition at line \fB83\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
83                                     {
84 
85     (*((volatile uint32_t*) (m_address))) = (data);
86 }
.fi

.PP
References \fBdata\fP, and \fBMaxOS::memory::MemIO::m_address\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
