.TH "MaxOS::hardwarecommunication::RSDPDescriptor2" 3 "Mon Jan 29 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::RSDPDescriptor2
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <acpi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRSDPDescriptor\fP \fBfirstPart\fP"
.br
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.ti -1c
.RI "uint64_t \fBxsdt_address\fP"
.br
.ti -1c
.RI "uint8_t \fBextended_checksum\fP"
.br
.ti -1c
.RI "uint8_t \fBreserved\fP [3]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 25 of file acpi\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::hardwarecommunication::RSDPDescriptor2::extended_checksum"

.PP
Definition at line 29 of file acpi\&.h\&.
.SS "\fBRSDPDescriptor\fP MaxOS::hardwarecommunication::RSDPDescriptor2::firstPart"

.PP
Definition at line 26 of file acpi\&.h\&.
.SS "uint32_t MaxOS::hardwarecommunication::RSDPDescriptor2::length"

.PP
Definition at line 27 of file acpi\&.h\&.
.SS "uint8_t MaxOS::hardwarecommunication::RSDPDescriptor2::reserved[3]"

.PP
Definition at line 30 of file acpi\&.h\&.
.SS "uint64_t MaxOS::hardwarecommunication::RSDPDescriptor2::xsdt_address"

.PP
Definition at line 28 of file acpi\&.h\&.
.PP
Referenced by MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::AdvancedConfigurationAndPowerInterface()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
