.TH "maxOS::memory::MemIO16Bit" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
maxOS::memory::MemIO16Bit \- Handles 16 bit memory IO\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <memoryIO\&.h>\fP
.PP
Inherits \fBmaxOS::memory::MemIO\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMemIO16Bit\fP (uint32_t \fBaddress\fP)"
.br
.ti -1c
.RI "\fB~MemIO16Bit\fP ()"
.br
.ti -1c
.RI "virtual void \fBwrite\fP (uint16_t \fBdata\fP)"
.br
.RI "Writes data to the memory address\&. "
.ti -1c
.RI "virtual uint16_t \fBread\fP ()"
.br
.RI "Reads data from the memory address\&. "
.in -1c
.SS "Additional Inherited Members"
.SH "Detailed Description"
.PP 
Handles 16 bit memory IO\&. 
.PP
Definition at line 43 of file memoryIO\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "MemIO16Bit::MemIO16Bit (uint32_t address)"

.PP
Definition at line 46 of file memoryIO\&.cpp\&.
.PP
.nf
47 : MemIO(address)
48 {
49 }
.fi
.SS "MemIO16Bit::~MemIO16Bit ()"

.PP
Definition at line 51 of file memoryIO\&.cpp\&.
.PP
.nf
51                         {
52 
53 }
.fi
.SH "Member Function Documentation"
.PP 
.SS "uint16_t MemIO16Bit::read ()\fC [virtual]\fP"

.PP
Reads data from the memory address\&. 
.PP
\fBReturns\fP
.RS 4
the data read 
.RE
.PP

.PP
Definition at line 69 of file memoryIO\&.cpp\&.
.PP
.nf
69                          {
70     return *((volatile uint16_t*)(m_address));
71 }
.fi
.PP
References maxOS::memory::MemIO::m_address\&.
.SS "void MemIO16Bit::write (uint16_t data)\fC [virtual]\fP"

.PP
Writes data to the memory address\&. 
.PP
\fBParameters\fP
.RS 4
\fIdata\fP the data to write 
.RE
.PP

.PP
Definition at line 60 of file memoryIO\&.cpp\&.
.PP
.nf
60                                    {
61     (*((volatile uint16_t*)(m_address)))=(data);
62 }
.fi
.PP
References data, and maxOS::memory::MemIO::m_address\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
