.TH "MaxOS::filesystem::format::FSInfo" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::filesystem::format::FSInfo
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <fat32\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint32_t \fBlead_signature\fP"
.br
.ti -1c
.RI "uint8_t \fBreserved1\fP [480]"
.br
.ti -1c
.RI "uint32_t \fBstructure_signature\fP"
.br
.ti -1c
.RI "uint32_t \fBfree_cluster_count\fP"
.br
.ti -1c
.RI "uint32_t \fBnext_free_cluster\fP"
.br
.ti -1c
.RI "uint8_t \fBreserved2\fP [12]"
.br
.ti -1c
.RI "uint32_t \fBtrail_signature\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB86\fP of file \fBfat32\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint32_t MaxOS::filesystem::format::FSInfo::free_cluster_count"

.PP
Definition at line \fB91\fP of file \fBfat32\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::FSInfo::lead_signature"

.PP
Definition at line \fB88\fP of file \fBfat32\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::FSInfo::next_free_cluster"

.PP
Definition at line \fB92\fP of file \fBfat32\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::FSInfo::reserved1[480]"

.PP
Definition at line \fB89\fP of file \fBfat32\&.h\fP\&.
.SS "uint8_t MaxOS::filesystem::format::FSInfo::reserved2[12]"

.PP
Definition at line \fB93\fP of file \fBfat32\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::FSInfo::structure_signature"

.PP
Definition at line \fB90\fP of file \fBfat32\&.h\fP\&.
.SS "uint32_t MaxOS::filesystem::format::FSInfo::trail_signature"

.PP
Definition at line \fB94\fP of file \fBfat32\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
