.TH "MaxOS::hardwarecommunication::RSDPDescriptor2" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MaxOS::hardwarecommunication::RSDPDescriptor2 \- Root System Description Pointer (RSDP) structure for ACPI 2 and above\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <acpi\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBRSDPDescriptor\fP \fBversion_1_info\fP"
.br
.RI "The ACPI 1 RSDP structure (see rsdp_descriptor_t) "
.ti -1c
.RI "uint32_t \fBlength\fP"
.br
.RI "The total length of the RSDP structure (including the version 1 part) "
.ti -1c
.RI "uint64_t \fBxsdt_address\fP"
.br
.RI "The physical address of the \fBXSDT\fP\&. "
.ti -1c
.RI "uint8_t \fBextended_checksum\fP"
.br
.RI "This byte added to all bytes in the table must equal zero for the table to be valid (including the version 1 part) "
.ti -1c
.RI "uint8_t \fBreserved\fP [3]"
.br
.RI "Reserved, must be zero\&. "
.in -1c
.SH "Detailed Description"
.PP 
Root System Description Pointer (RSDP) structure for ACPI 2 and above\&. 
.PP
Definition at line \fB44\fP of file \fBacpi\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "uint8_t MaxOS::hardwarecommunication::RSDPDescriptor2::extended_checksum"

.PP
This byte added to all bytes in the table must equal zero for the table to be valid (including the version 1 part) 
.PP
Definition at line \fB48\fP of file \fBacpi\&.h\fP\&.
.SS "uint32_t MaxOS::hardwarecommunication::RSDPDescriptor2::length"

.PP
The total length of the RSDP structure (including the version 1 part) 
.PP
Definition at line \fB46\fP of file \fBacpi\&.h\fP\&.
.SS "uint8_t MaxOS::hardwarecommunication::RSDPDescriptor2::reserved[3]"

.PP
Reserved, must be zero\&. 
.PP
Definition at line \fB49\fP of file \fBacpi\&.h\fP\&.
.SS "\fBRSDPDescriptor\fP MaxOS::hardwarecommunication::RSDPDescriptor2::version_1_info"

.PP
The ACPI 1 RSDP structure (see rsdp_descriptor_t) 
.PP
Definition at line \fB45\fP of file \fBacpi\&.h\fP\&.
.SS "uint64_t MaxOS::hardwarecommunication::RSDPDescriptor2::xsdt_address"

.PP
The physical address of the \fBXSDT\fP\&. 
.PP
Definition at line \fB47\fP of file \fBacpi\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
