.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/memory/memoryIO.h" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/memory/memoryIO.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::memory::MemIO\fP"
.br
.RI "base class for all memory IO "
.ti -1c
.RI "class \fBMaxOS::memory::MemIO8Bit\fP"
.br
.RI "Handles 8 bit memory IO\&. "
.ti -1c
.RI "class \fBMaxOS::memory::MemIO16Bit\fP"
.br
.RI "Handles 16 bit memory IO\&. "
.ti -1c
.RI "class \fBMaxOS::memory::MemIO32Bit\fP"
.br
.RI "Handles 32 bit memory IO\&. "
.ti -1c
.RI "class \fBMaxOS::memory::MemIO64Bit\fP"
.br
.RI "Handles 64 bit memory IO\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBMaxOS\fP"
.br
.ti -1c
.RI "namespace \fBMaxOS::memory\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBmemcpy\fP (void *\fBdestination\fP, const void *\fBsource\fP, uint64_t num)"
.br
.RI "Copies a block of memory from one location to another\&. "
.ti -1c
.RI "void * \fBmemset\fP (void *ptr, uint32_t value, uint64_t num)"
.br
.RI "Fills a block of memory with a specified value\&. "
.ti -1c
.RI "void * \fBmemmove\fP (void *\fBdestination\fP, const void *\fBsource\fP, uint64_t num)"
.br
.RI "Copies a block of memory from one location to another\&. "
.ti -1c
.RI "int \fBmemcmp\fP (const void *ptr1, const void *ptr2, uint64_t num)"
.br
.RI "Compares two blocks of memory\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "int memcmp (const void * ptr1, const void * ptr2, uint64_t num)"

.PP
Compares two blocks of memory\&. 
.PP
\fBParameters\fP
.RS 4
\fIptr1\fP The m_first_memory_chunk block of memory 
.br
\fIptr2\fP The second block of memory 
.br
\fInum\fP The number of bytes to compare 
.RE
.PP
\fBReturns\fP
.RS 4
0 if the blocks of memory are equal, -1 if ptr1 < ptr2, 1 if ptr1 > ptr2 
.RE
.PP

.PP
Definition at line \fB216\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
216                                                              {
217 
218     // Make sure the pointers exist
219     if (ptr1 == nullptr || ptr2 == nullptr)
220         return 0;
221 
222     const auto* p1 = (const unsigned char*) ptr1;
223     const auto* p2 = (const unsigned char*) ptr2;
224     for (size_t i = 0; i < num; i++) {
225         if (p1[i] < p2[i])
226             return \-1;
227         if (p1[i] > p2[i])
228             return 1;
229     }
230     return 0;
231 }
.fi

.SS "void * memcpy (void * destination, const void * source, uint64_t num)"

.PP
Copies a block of memory from one location to another\&. 
.PP
\fBSee also\fP
.RS 4
https://wiki.osdev.org/Meaty_Skeleton#memcpy.28.29
.RE
.PP
\fBParameters\fP
.RS 4
\fIdestination\fP The destination to copy to 
.br
\fIsource\fP The source to copy from 
.br
\fInum\fP The number of bytes to copy 
.RE
.PP
\fBReturns\fP
.RS 4
The destination 
.RE
.PP

.PP
Definition at line \fB136\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
136                                                                   {
137 
138     // Make sure the source and destination are not the same
139     if (destination == source)
140         return destination;
141 
142     // Make sure they exist
143     if (destination == nullptr || source == nullptr)
144         return destination;
145 
146     // Get the source and destination
147     auto* dst = (unsigned char*) destination;
148     const auto* src = (const unsigned char*) source;
149 
150     // Copy the data
151     for (size_t i = 0; i < num; i++)
152         dst[i] = src[i];
153 
154     // Usefully for easier code writing
155     return destination;
156 }
.fi

.PP
References \fBdestination\fP, and \fBsource\fP\&.
.PP
Referenced by \fBMaxOS::common::Buffer::copy_from()\fP, \fBMaxOS::common::Buffer::copy_from()\fP, \fBMaxOS::common::Buffer::copy_to()\fP, \fBMaxOS::common::Buffer::copy_to()\fP, \fBMaxOS::filesystem::format::ext2::Ext2Volume::Ext2Volume()\fP, \fBMaxOS::processes::SharedMessageEndpoint::read()\fP, \fBMaxOS::common::Buffer::resize()\fP, and \fBMaxOS::processes::Thread::Thread()\fP\&.
.SS "void * memmove (void * destination, const void * source, uint64_t num)"

.PP
Copies a block of memory from one location to another\&. 
.PP
\fBParameters\fP
.RS 4
\fIdestination\fP The destination to copy to 
.br
\fIsource\fP The source to copy from 
.br
\fInum\fP The number of bytes to copy 
.RE
.PP
\fBReturns\fP
.RS 4
The destination 
.RE
.PP

.PP
Definition at line \fB186\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
186                                                                    {
187 
188     // Make sure the source and destination are not the same
189     if (destination == source)
190         return destination;
191 
192     // Make sure they exist
193     if (destination == nullptr || source == nullptr)
194         return destination;
195 
196     auto* dst = (unsigned char*) destination;
197     const auto* src = (const unsigned char*) source;
198     if (dst < src) {
199         for (size_t i = 0; i < num; i++)
200             dst[i] = src[i];
201     } else {
202         for (size_t i = num; i != 0; i\-\-)
203             dst[i \- 1] = src[i \- 1];
204     }
205     return destination;
206 }
.fi

.PP
References \fBdestination\fP, and \fBsource\fP\&.
.PP
Referenced by \fBMaxOS::drivers::console::VESABootConsole::scroll_up()\fP\&.
.SS "void * memset (void * ptr, uint32_t value, uint64_t num)"

.PP
Fills a block of memory with a specified value\&. 
.PP
\fBParameters\fP
.RS 4
\fIptr\fP The pointer to the block of memory 
.br
\fIvalue\fP The value to fill the block of memory with 
.br
\fInum\fP The number of bytes to fill 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the block of memory 
.RE
.PP

.PP
Definition at line \fB166\fP of file \fBmemoryIO\&.cpp\fP\&..PP
.nf
166                                                       {
167 
168     // Make sure the pointer exists
169     if (ptr == nullptr)
170         return ptr;
171 
172     auto* dst = (unsigned char*) ptr;
173     for (size_t i = 0; i < num; i++)
174         dst[i] = (unsigned char) value;
175     return ptr;
176 }
.fi

.PP
Referenced by \fBMaxOS::common::Buffer::clear()\fP, and \fBMaxOS::common::Buffer::full()\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
