.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/memory/memoryIO.h" 3 "Sat Jan 6 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/memory/memoryIO.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <stddef\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaxOS::memory::MemIO\fP"
.br
.RI "base class for all memory IO "
.ti -1c
.RI "class \fBmaxOS::memory::MemIO8Bit\fP"
.br
.RI "Handles 8 bit memory IO\&. "
.ti -1c
.RI "class \fBmaxOS::memory::MemIO16Bit\fP"
.br
.RI "Handles 16 bit memory IO\&. "
.ti -1c
.RI "class \fBmaxOS::memory::MemIO32Bit\fP"
.br
.RI "Handles 32 bit memory IO\&. "
.ti -1c
.RI "class \fBmaxOS::memory::MemIO64Bit\fP"
.br
.RI "Handles 64 bit memory IO\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmaxOS\fP"
.br
.ti -1c
.RI " \fBmaxOS::memory\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
