.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/memory/memorymanagement.cpp" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/memory/memorymanagement.cpp \- Implementation of a Memory Manager for dynamic memory allocation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <memory/memorymanagement\&.h>\fP
.br
\fC#include <common/logger\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBsize_t\fP \fBsize\fP)  \fBthrow\fP ()"
.br
.RI "Overloaded new operator, allocates memory using the KERNEL memory manager\&. "
.ti -1c
.RI "\fBvoid\fP * \fBoperator new[]\fP (\fBsize_t\fP \fBsize\fP)  \fBthrow\fP ()"
.br
.RI "Overloaded new operator, allocates memory using the KERNEL memory manager\&. "
.ti -1c
.RI "\fBvoid\fP * \fBoperator new\fP (\fBsize_t\fP \fBsize\fP, \fBvoid\fP *pointer)"
.br
.RI "Overloaded new operator, allocates memory using the KERNEL memory manager\&. "
.ti -1c
.RI "\fBvoid\fP * \fBoperator new[]\fP (\fBsize_t\fP \fBsize\fP, \fBvoid\fP *pointer)"
.br
.RI "Overloaded new operator, allocates memory using the KERNEL memory manager\&. "
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *pointer)"
.br
.RI "Overloaded delete operator, frees memory using the KERNEL memory manager\&. "
.ti -1c
.RI "\fBvoid\fP \fBoperator delete[]\fP (\fBvoid\fP *pointer)"
.br
.RI "Overloaded delete operator, frees memory using the KERNEL memory manager\&. "
.ti -1c
.RI "\fBvoid\fP \fBoperator delete\fP (\fBvoid\fP *pointer, \fBsize_t\fP)"
.br
.RI "Overloaded delete operator, frees memory using the KERNEL memory manager\&. "
.ti -1c
.RI "\fBvoid\fP \fBoperator delete[]\fP (\fBvoid\fP *pointer, \fBsize_t\fP \fBsize\fP)"
.br
.RI "Overloaded delete operator, frees memory using the KERNEL memory manager\&. "
.in -1c
.SH "Detailed Description"
.PP 
Implementation of a Memory Manager for dynamic memory allocation\&. 


.PP
\fBDate\fP
.RS 4
20th October 2022 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBmemorymanagement\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "\fBvoid\fP \fBoperator\fP \fBdelete\fP (\fBvoid\fP * pointer)"

.PP
Overloaded delete operator, frees memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to free 
.RE
.PP

.PP
Definition at line \fB377\fP of file \fBmemorymanagement\&.cpp\fP\&..PP
.nf
377                                     {
378 
379     // Handle the memory freeing
380     return MaxOS::memory::MemoryManager::kfree(pointer);
381 }
.fi

.PP
References \fBMaxOS::memory::MemoryManager::kfree()\fP\&.
.SS "\fBvoid\fP \fBoperator\fP \fBdelete\fP (\fBvoid\fP * pointer, \fBsize_t\fP size)"

.PP
Overloaded delete operator, frees memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to free 
.br
\fIsize\fP The size of the memory to free - ignored in this implementation 
.RE
.PP

.PP
Definition at line \fB400\fP of file \fBmemorymanagement\&.cpp\fP\&..PP
.nf
400                                             {
401 
402     // Handle the memory freeing
403     return MaxOS::memory::MemoryManager::kfree(pointer);
404 }
.fi

.PP
References \fBMaxOS::memory::MemoryManager::kfree()\fP\&.
.SS "\fBvoid\fP \fBoperator\fP \fBdelete\fP[] (\fBvoid\fP * pointer)"

.PP
Overloaded delete operator, frees memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to free 
.RE
.PP

.PP
Definition at line \fB388\fP of file \fBmemorymanagement\&.cpp\fP\&..PP
.nf
388                                       {
389 
390     // Handle the memory freeing
391     return MaxOS::memory::MemoryManager::kfree(pointer);
392 }
.fi

.PP
References \fBMaxOS::memory::MemoryManager::kfree()\fP\&.
.SS "\fBvoid\fP \fBoperator\fP \fBdelete\fP[] (\fBvoid\fP * pointer, \fBsize_t\fP size)"

.PP
Overloaded delete operator, frees memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to free 
.br
\fIsize\fP The size of the memory to free - ignored in this implementation 
.RE
.PP

.PP
Definition at line \fB412\fP of file \fBmemorymanagement\&.cpp\fP\&..PP
.nf
412                                                    {
413 
414     // Handle the memory freeing
415     return MaxOS::memory::MemoryManager::kfree(pointer);
416 }
.fi

.PP
References \fBMaxOS::memory::MemoryManager::kfree()\fP\&.
.SS "\fBvoid\fP * \fBoperator\fP \fBnew\fP (\fBsize_t\fP size)"

.PP
Overloaded new operator, allocates memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP The size of the memory to allocate 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the allocated memory 
.RE
.PP

.PP
Definition at line \fB329\fP of file \fBmemorymanagement\&.cpp\fP\&..PP
.nf
329                                         {
330 
331     // Handle the memory allocation
332     return MaxOS::memory::MemoryManager::kmalloc(size);
333 }
.fi

.PP
References \fBMaxOS::memory::MemoryManager::kmalloc()\fP, and \fBsize\fP\&.
.SS "\fBvoid\fP * \fBoperator\fP \fBnew\fP (\fBsize_t\fP size, \fBvoid\fP * pointer)"

.PP
Overloaded new operator, allocates memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to allocate 
.br
\fIsize\fP The size of the memory to free - ignored in this implementation 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the memory 
.RE
.PP

.PP
Definition at line \fB354\fP of file \fBmemorymanagement\&.cpp\fP\&..PP
.nf
354                                                {
355 
356     return pointer;
357 }
.fi

.SS "\fBvoid\fP * \fBoperator\fP \fBnew\fP[] (\fBsize_t\fP size)"

.PP
Overloaded new operator, allocates memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP The size of the memory to allocate 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the allocated memory 
.RE
.PP

.PP
Definition at line \fB341\fP of file \fBmemorymanagement\&.cpp\fP\&..PP
.nf
341                                           {
342 
343     // Handle the memory allocation
344     return  MaxOS::memory::MemoryManager::kmalloc(size);
345 }
.fi

.PP
References \fBMaxOS::memory::MemoryManager::kmalloc()\fP, and \fBsize\fP\&.
.SS "\fBvoid\fP * \fBoperator\fP \fBnew\fP[] (\fBsize_t\fP size, \fBvoid\fP * pointer)"

.PP
Overloaded new operator, allocates memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP The size of the memory to free - ignored in this implementation 
.br
\fIpointer\fP The pointer to the memory to allocate 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the memory 
.RE
.PP

.PP
Definition at line \fB366\fP of file \fBmemorymanagement\&.cpp\fP\&..PP
.nf
366                                                  {
367 
368 
369     return pointer;
370 }
.fi

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
