.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/memory/memorymanagement.cpp" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/memory/memorymanagement.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <memory/memorymanagement\&.h>\fP
.br
\fC#include <common/kprint\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void * \fBoperator new\fP (size_t \fBsize\fP)  throw ()"
.br
.RI "Overloaded new operator, allocates memory using the KERNEL memory manager\&. "
.ti -1c
.RI "void * \fBoperator new[]\fP (size_t \fBsize\fP)  throw ()"
.br
.RI "Overloaded new operator, allocates memory using the KERNEL memory manager\&. "
.ti -1c
.RI "void * \fBoperator new\fP (size_t, void *pointer)"
.br
.RI "Overloaded new operator, allocates memory using the KERNEL memory manager\&. "
.ti -1c
.RI "void * \fBoperator new[]\fP (size_t, void *pointer)"
.br
.RI "Overloaded new operator, allocates memory using the KERNEL memory manager\&. "
.ti -1c
.RI "void \fBoperator delete\fP (void *pointer)"
.br
.RI "Overloaded delete operator, frees memory using the KERNEL memory manager\&. "
.ti -1c
.RI "void \fBoperator delete[]\fP (void *pointer)"
.br
.RI "Overloaded delete operator, frees memory using the KERNEL memory manager\&. "
.ti -1c
.RI "void \fBoperator delete\fP (void *pointer, size_t)"
.br
.RI "Overloaded delete operator, frees memory using the KERNEL memory manager\&. "
.ti -1c
.RI "void \fBoperator delete[]\fP (void *pointer, size_t)"
.br
.RI "Overloaded delete operator, frees memory using the KERNEL memory manager\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "void operator delete (void * pointer)"

.PP
Overloaded delete operator, frees memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to free 
.RE
.PP

.PP
Definition at line 454 of file memorymanagement\&.cpp\&.
.PP
.nf
454                                    {
455 
456   // Handle the memory freeing
457   return MaxOS::memory::MemoryManager::kfree(pointer);
458 
459 }
.fi
.PP
References MaxOS::memory::MemoryManager::kfree()\&.
.SS "void operator delete (void * pointer, size_t)"

.PP
Overloaded delete operator, frees memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to free 
.br
\fIsize\fP The size of the memory to free - ignored in this implementation 
.RE
.PP

.PP
Definition at line 480 of file memorymanagement\&.cpp\&.
.PP
.nf
480                                            {
481 
482   // Handle the memory freeing
483   return MaxOS::memory::MemoryManager::kfree(pointer);
484 
485 }
.fi
.PP
References MaxOS::memory::MemoryManager::kfree()\&.
.SS "void operator delete[] (void * pointer)"

.PP
Overloaded delete operator, frees memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to free 
.RE
.PP

.PP
Definition at line 466 of file memorymanagement\&.cpp\&.
.PP
.nf
466                                      {
467 
468   // Handle the memory freeing
469   return MaxOS::memory::MemoryManager::kfree(pointer);
470 
471 }
.fi
.PP
References MaxOS::memory::MemoryManager::kfree()\&.
.SS "void operator delete[] (void * pointer, size_t)"

.PP
Overloaded delete operator, frees memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to free 
.RE
.PP

.PP
Definition at line 492 of file memorymanagement\&.cpp\&.
.PP
.nf
492                                              {
493 
494   // Handle the memory freeing
495   return MaxOS::memory::MemoryManager::kfree(pointer);
496 
497 }
.fi
.PP
References MaxOS::memory::MemoryManager::kfree()\&.
.SS "void* operator new (size_t size)"

.PP
Overloaded new operator, allocates memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP The size of the memory to allocate 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the allocated memory 
.RE
.PP

.PP
Definition at line 404 of file memorymanagement\&.cpp\&.
.PP
.nf
404                                        {
405 
406     // Handle the memory allocation
407     return MaxOS::memory::MemoryManager::kmalloc(size);
408 
409 }
.fi
.PP
References MaxOS::memory::MemoryManager::kmalloc(), and size\&.
.SS "void* operator new (size_t, void * pointer)"

.PP
Overloaded new operator, allocates memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to allocate 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the memory 
.RE
.PP

.PP
Definition at line 430 of file memorymanagement\&.cpp\&.
.PP
.nf
430                                          {
431 
432     return pointer;
433 
434 }
.fi
.SS "void* operator new[] (size_t size)"

.PP
Overloaded new operator, allocates memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIsize\fP The size of the memory to allocate 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the allocated memory 
.RE
.PP

.PP
Definition at line 417 of file memorymanagement\&.cpp\&.
.PP
.nf
417                                          {
418 
419   // Handle the memory allocation
420   return MaxOS::memory::MemoryManager::kmalloc(size);
421 
422 }
.fi
.PP
References MaxOS::memory::MemoryManager::kmalloc(), and size\&.
.SS "void* operator new[] (size_t, void * pointer)"

.PP
Overloaded new operator, allocates memory using the KERNEL memory manager\&. 
.PP
\fBParameters\fP
.RS 4
\fIpointer\fP The pointer to the memory to allocate 
.RE
.PP
\fBReturns\fP
.RS 4
The pointer to the memory 
.RE
.PP

.PP
Definition at line 442 of file memorymanagement\&.cpp\&.
.PP
.nf
442                                            {
443 
444 
445     return pointer;
446 
447 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
