.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/peripherals/mouse.h" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/peripherals/mouse.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <common/vector\&.h>\fP
.br
\fC#include <common/string\&.h>\fP
.br
\fC#include <common/eventHandler\&.h>\fP
.br
\fC#include <hardwarecommunication/interrupts\&.h>\fP
.br
\fC#include <hardwarecommunication/port\&.h>\fP
.br
\fC#include <drivers/driver\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaxOS::drivers::peripherals::MouseMoveEvent\fP"
.br
.RI "Event that is triggered when the mouse moves, holds the x and y coordinates\&. "
.ti -1c
.RI "class \fBmaxOS::drivers::peripherals::MouseDownEvent\fP"
.br
.RI "Event that is triggered when a mouse button is pressed, holds the button that was pressed\&. "
.ti -1c
.RI "class \fBmaxOS::drivers::peripherals::MouseUpEvent\fP"
.br
.RI "Event that is triggered when a mouse button is released, holds the button that was released\&. "
.ti -1c
.RI "class \fBmaxOS::drivers::peripherals::MouseEventHandler\fP"
.br
.RI "Handles events that are triggered by the mouse driver\&. "
.ti -1c
.RI "class \fBmaxOS::drivers::peripherals::MouseDriver\fP"
.br
.RI "\fBDriver\fP for the PS/2 mouse, manages the mouse and triggers events when the mouse moves or a button is pressed\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmaxOS\fP"
.br
.ti -1c
.RI " \fBmaxOS::drivers\fP"
.br
.ti -1c
.RI " \fBmaxOS::drivers::peripherals\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBmaxOS::drivers::peripherals::MouseEvents\fP { \fBmaxOS::drivers::peripherals::MOUSE_MOVE\fP, \fBmaxOS::drivers::peripherals::MOUSE_DOWN\fP, \fBmaxOS::drivers::peripherals::MOUSE_UP\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
