.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/partition/msdos.cpp" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/filesystem/partition/msdos.cpp \- Implementation of MSDOS partition table reading and mounting\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <filesystem/partition/msdos\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of MSDOS partition table reading and mounting\&. 


.PP
\fBDate\fP
.RS 4
28th December 2022 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBmsdos\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
