.TH "multiboot_tag" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag \- Common header for all multiboot info tags\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "multiboot_uint32_t \fBtype\fP"
.br
.RI "The type of the tag\&. "
.ti -1c
.RI "multiboot_uint32_t \fBsize\fP"
.br
.RI "The size of the tag including this header\&. "
.in -1c
.SH "Detailed Description"
.PP 
Common header for all multiboot info tags\&. 
.PP
Definition at line \fB234\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "multiboot_uint32_t multiboot_tag::size"

.PP
The size of the tag including this header\&. 
.PP
Definition at line \fB236\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag::type"

.PP
The type of the tag\&. 
.PP
Definition at line \fB235\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
