.TH "multiboot_header_tag_console_flags" 3 "Mon Jan 29 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_header_tag_console_flags
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBconsole_flags\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 146 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_console_flags::console_flags"

.PP
Definition at line 151 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_header_tag_console_flags::flags"

.PP
Definition at line 149 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_console_flags::size"

.PP
Definition at line 150 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_header_tag_console_flags::type"

.PP
Definition at line 148 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
