.TH "multiboot_header_tag_module_align" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_header_tag_module_align
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB164\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint16_t\fP multiboot_header_tag_module_align::flags"

.PP
Definition at line \fB167\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_module_align::size"

.PP
Definition at line \fB168\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_header_tag_module_align::type"

.PP
Definition at line \fB166\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
