.TH "multiboot_tag_efi64_ih" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_efi64_ih
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint64_t\fP \fBpointer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 401 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint64_t\fP multiboot_tag_efi64_ih::pointer"

.PP
Definition at line 405 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_efi64_ih::size"

.PP
Definition at line 404 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_efi64_ih::type"

.PP
Definition at line 403 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
