.TH "multiboot_header_tag_entry_address" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_header_tag_entry_address
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBentry_addr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB138\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_entry_address::entry_addr"

.PP
Definition at line \fB143\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_header_tag_entry_address::flags"

.PP
Definition at line \fB141\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_entry_address::size"

.PP
Definition at line \fB142\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_header_tag_entry_address::type"

.PP
Definition at line \fB140\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
