.TH "multiboot_tag_vbe" 3 "Sun Oct 13 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_vbe
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_mode\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_interface_seg\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_interface_off\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_interface_len\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_vbe_info_block\fP \fBvbe_control_info\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_vbe_mode_info_block\fP \fBvbe_mode_info\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 261 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_vbe::size"

.PP
Definition at line 264 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_vbe::type"

.PP
Definition at line 263 of file multiboot\&.h\&.
.SS "struct \fBmultiboot_vbe_info_block\fP multiboot_tag_vbe::vbe_control_info"

.PP
Definition at line 271 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_vbe::vbe_interface_len"

.PP
Definition at line 269 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_vbe::vbe_interface_off"

.PP
Definition at line 268 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_vbe::vbe_interface_seg"

.PP
Definition at line 267 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_vbe::vbe_mode"

.PP
Definition at line 266 of file multiboot\&.h\&.
.SS "struct \fBmultiboot_vbe_mode_info_block\fP multiboot_tag_vbe::vbe_mode_info"

.PP
Definition at line 272 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
