.TH "multiboot_tag" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 203 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP multiboot_tag::size"

.PP
Definition at line 206 of file multiboot\&.h\&.
.PP
Referenced by MaxOS::system::Multiboot::is_reserved(), and MaxOS::system::Multiboot::Multiboot()\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag::type"

.PP
Definition at line 205 of file multiboot\&.h\&.
.PP
Referenced by MaxOS::system::Multiboot::is_reserved(), and MaxOS::system::Multiboot::Multiboot()\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
