.TH "multiboot_tag_mmap" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_mmap \- A tag containing the collection of memory map entries that outline the memory layout\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "multiboot_uint32_t \fBtype\fP"
.br
.RI "*copydoc \fBmultiboot_tag::type\fP "
.ti -1c
.RI "multiboot_uint32_t \fBsize\fP"
.br
.RI "*copydoc \fBmultiboot_tag::size\fP "
.ti -1c
.RI "multiboot_uint32_t \fBentry_size\fP"
.br
.RI "The size of each entry\&. "
.ti -1c
.RI "multiboot_uint32_t \fBentry_version\fP"
.br
.RI "The version of the entry structure (must be 0) "
.ti -1c
.RI "struct \fBmultiboot_mmap_entry\fP \fBentries\fP [0]"
.br
.RI "The memory map entries\&. "
.in -1c
.SH "Detailed Description"
.PP 
A tag containing the collection of memory map entries that outline the memory layout\&. 
.PP
Definition at line \fB288\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBmultiboot_mmap_entry\fP multiboot_tag_mmap::entries[0]"

.PP
The memory map entries\&. 
.PP
Definition at line \fB293\fP of file \fBmultiboot\&.h\fP\&.
.PP
Referenced by \fBMaxOS::memory::PhysicalMemoryManager::reserve_kernel_regions()\fP\&.
.SS "multiboot_uint32_t multiboot_tag_mmap::entry_size"

.PP
The size of each entry\&. 
.PP
Definition at line \fB291\fP of file \fBmultiboot\&.h\fP\&.
.PP
Referenced by \fBMaxOS::memory::PhysicalMemoryManager::reserve_kernel_regions()\fP\&.
.SS "multiboot_uint32_t multiboot_tag_mmap::entry_version"

.PP
The version of the entry structure (must be 0) 
.PP
Definition at line \fB292\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_mmap::size"

.PP
*copydoc \fBmultiboot_tag::size\fP 
.PP
Definition at line \fB290\fP of file \fBmultiboot\&.h\fP\&.
.PP
Referenced by \fBMaxOS::memory::PhysicalMemoryManager::reserve_kernel_regions()\fP\&.
.SS "multiboot_uint32_t multiboot_tag_mmap::type"

.PP
*copydoc \fBmultiboot_tag::type\fP 
.PP
Definition at line \fB289\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
