.TH "multiboot_tag_apm" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_apm
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBversion\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBcseg\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBoffset\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBcseg_16\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBdseg\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBcseg_len\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBcseg_16_len\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBdseg_len\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB325\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_apm::cseg"

.PP
Definition at line \fB330\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_apm::cseg_16"

.PP
Definition at line \fB332\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_apm::cseg_16_len"

.PP
Definition at line \fB336\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_apm::cseg_len"

.PP
Definition at line \fB335\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_apm::dseg"

.PP
Definition at line \fB333\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_apm::dseg_len"

.PP
Definition at line \fB337\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_apm::flags"

.PP
Definition at line \fB334\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_apm::offset"

.PP
Definition at line \fB331\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_apm::size"

.PP
Definition at line \fB328\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_apm::type"

.PP
Definition at line \fB327\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_apm::version"

.PP
Definition at line \fB329\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
