.TH "multiboot_tag_network" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_network \- A tag containing information about the network booting\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "multiboot_uint32_t \fBtype\fP"
.br
.RI "*copydoc \fBmultiboot_tag::type\fP "
.ti -1c
.RI "multiboot_uint32_t \fBsize\fP"
.br
.RI "*copydoc \fBmultiboot_tag::size\fP "
.ti -1c
.RI "multiboot_uint8_t \fBdhcpack\fP [0]"
.br
.RI "The DHCP ACK packet\&. "
.in -1c
.SH "Detailed Description"
.PP 
A tag containing information about the network booting\&. 
.PP
Definition at line \fB463\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "multiboot_uint8_t multiboot_tag_network::dhcpack[0]"

.PP
The DHCP ACK packet\&. 
.PP
Definition at line \fB466\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_network::size"

.PP
*copydoc \fBmultiboot_tag::size\fP 
.PP
Definition at line \fB465\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_network::type"

.PP
*copydoc \fBmultiboot_tag::type\fP 
.PP
Definition at line \fB464\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
