.TH "multiboot_vbe_mode_info_block" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_vbe_mode_info_block
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint8_t\fP \fBexternal_specification\fP [256]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB256\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint8_t\fP multiboot_vbe_mode_info_block::external_specification[256]"

.PP
Definition at line \fB258\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
