.TH "multiboot_tag_mmap" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_mmap
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBentry_size\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBentry_version\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_mmap_entry\fP \fBentries\fP [0]"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 242 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "struct \fBmultiboot_mmap_entry\fP multiboot_tag_mmap::entries[0]"

.PP
Definition at line 248 of file multiboot\&.h\&.
.PP
Referenced by MaxOS::memory::PhysicalMemoryManager::is_anonymous_available(), and MaxOS::memory::PhysicalMemoryManager::PhysicalMemoryManager()\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_mmap::entry_size"

.PP
Definition at line 246 of file multiboot\&.h\&.
.PP
Referenced by MaxOS::memory::PhysicalMemoryManager::is_anonymous_available(), and MaxOS::memory::PhysicalMemoryManager::PhysicalMemoryManager()\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_mmap::entry_version"

.PP
Definition at line 247 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_mmap::size"

.PP
Definition at line 245 of file multiboot\&.h\&.
.PP
Referenced by MaxOS::memory::PhysicalMemoryManager::is_anonymous_available(), and MaxOS::memory::PhysicalMemoryManager::PhysicalMemoryManager()\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_mmap::type"

.PP
Definition at line 244 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
