.TH "multiboot_mmap_entry" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_mmap_entry \- An entry in the memory map containing information about a region of memory\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "multiboot_uint64_t \fBaddr\fP"
.br
.RI "The starting address of the memory region\&. "
.ti -1c
.RI "multiboot_uint64_t \fBlen\fP"
.br
.RI "The length of the memory region\&. "
.ti -1c
.RI "multiboot_uint32_t \fBtype\fP"
.br
.RI "The type of memory region\&. "
.ti -1c
.RI "multiboot_uint32_t \fBzero\fP"
.br
.RI "Must be zero\&. "
.in -1c
.SH "Detailed Description"
.PP 
An entry in the memory map containing information about a region of memory\&. 
.PP
Definition at line \fB222\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "multiboot_uint64_t multiboot_mmap_entry::addr"

.PP
The starting address of the memory region\&. 
.PP
Definition at line \fB223\fP of file \fBmultiboot\&.h\fP\&.
.PP
Referenced by \fBMaxOS::memory::PhysicalMemoryManager::allocate_frame()\fP, \fBMaxOS::memory::PhysicalMemoryManager::PhysicalMemoryManager()\fP, and \fBMaxOS::memory::PhysicalMemoryManager::reserve_kernel_regions()\fP\&.
.SS "multiboot_uint64_t multiboot_mmap_entry::len"

.PP
The length of the memory region\&. 
.PP
Definition at line \fB224\fP of file \fBmultiboot\&.h\fP\&.
.PP
Referenced by \fBMaxOS::memory::PhysicalMemoryManager::PhysicalMemoryManager()\fP, and \fBMaxOS::memory::PhysicalMemoryManager::reserve_kernel_regions()\fP\&.
.SS "multiboot_uint32_t multiboot_mmap_entry::type"

.PP
The type of memory region\&. 
.PP
Definition at line \fB225\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_mmap_entry::zero"

.PP
Must be zero\&. 
.PP
Definition at line \fB226\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
