.TH "multiboot_header_tag_relocatable" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_header_tag_relocatable \- A tag containing information of where the OS image can be loaded\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "multiboot_uint16_t \fBtype\fP"
.br
.RI "*copydoc \fBmultiboot_header_tag::type\fP "
.ti -1c
.RI "multiboot_uint16_t \fBflags\fP"
.br
.RI "*copydoc \fBmultiboot_header_tag::flags\fP "
.ti -1c
.RI "multiboot_uint32_t \fBsize\fP"
.br
.RI "*copydoc \fBmultiboot_header_tag::size\fP "
.ti -1c
.RI "multiboot_uint32_t \fBmin_addr\fP"
.br
.RI "The lowest address the image can be loaded at\&. "
.ti -1c
.RI "multiboot_uint32_t \fBmax_addr\fP"
.br
.RI "The highest address the image can be loaded at\&. "
.ti -1c
.RI "multiboot_uint32_t \fBalign\fP"
.br
.RI "The alignment of the image\&. "
.ti -1c
.RI "multiboot_uint32_t \fBpreference\fP"
.br
.RI "The load address preference (0 = none, 1 = low, 2 = high) "
.in -1c
.SH "Detailed Description"
.PP 
A tag containing information of where the OS image can be loaded\&. 
.PP
Definition at line \fB192\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "multiboot_uint32_t multiboot_header_tag_relocatable::align"

.PP
The alignment of the image\&. 
.PP
Definition at line \fB198\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint16_t multiboot_header_tag_relocatable::flags"

.PP
*copydoc \fBmultiboot_header_tag::flags\fP 
.PP
Definition at line \fB194\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_header_tag_relocatable::max_addr"

.PP
The highest address the image can be loaded at\&. 
.PP
Definition at line \fB197\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_header_tag_relocatable::min_addr"

.PP
The lowest address the image can be loaded at\&. 
.PP
Definition at line \fB196\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_header_tag_relocatable::preference"

.PP
The load address preference (0 = none, 1 = low, 2 = high) 
.PP
Definition at line \fB199\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_header_tag_relocatable::size"

.PP
*copydoc \fBmultiboot_header_tag::size\fP 
.PP
Definition at line \fB195\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint16_t multiboot_header_tag_relocatable::type"

.PP
*copydoc \fBmultiboot_header_tag::type\fP 
.PP
Definition at line \fB193\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
