.TH "multiboot_header" 3 "Mon Jan 29 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_header
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBmagic\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBarchitecture\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBheader_length\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBchecksum\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 97 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP multiboot_header::architecture"

.PP
Definition at line 103 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header::checksum"

.PP
Definition at line 109 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header::header_length"

.PP
Definition at line 106 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header::magic"

.PP
Definition at line 100 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
