.TH "multiboot_tag_vbe" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_vbe
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_mode\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_interface_seg\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_interface_off\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBvbe_interface_len\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_vbe_info_block\fP \fBvbe_control_info\fP"
.br
.ti -1c
.RI "struct \fBmultiboot_vbe_mode_info_block\fP \fBvbe_mode_info\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB261\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_vbe::size"

.PP
Definition at line \fB264\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_vbe::type"

.PP
Definition at line \fB263\fP of file \fBmultiboot\&.h\fP\&.
.SS "struct \fBmultiboot_vbe_info_block\fP multiboot_tag_vbe::vbe_control_info"

.PP
Definition at line \fB271\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_vbe::vbe_interface_len"

.PP
Definition at line \fB269\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_vbe::vbe_interface_off"

.PP
Definition at line \fB268\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_vbe::vbe_interface_seg"

.PP
Definition at line \fB267\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_tag_vbe::vbe_mode"

.PP
Definition at line \fB266\fP of file \fBmultiboot\&.h\fP\&.
.SS "struct \fBmultiboot_vbe_mode_info_block\fP multiboot_tag_vbe::vbe_mode_info"

.PP
Definition at line \fB272\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
