.TH "multiboot_tag_framebuffer_common" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_framebuffer_common \- Common header for framebuffer tags\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "multiboot_uint32_t \fBtype\fP"
.br
.RI "*copydoc \fBmultiboot_tag::type\fP "
.ti -1c
.RI "multiboot_uint32_t \fBsize\fP"
.br
.RI "*copydoc \fBmultiboot_tag::size\fP "
.ti -1c
.RI "multiboot_uint64_t \fBframebuffer_addr\fP"
.br
.RI "The physical address of the framebuffer\&. "
.ti -1c
.RI "multiboot_uint32_t \fBframebuffer_pitch\fP"
.br
.RI "The number of bytes per horizontal line\&. "
.ti -1c
.RI "multiboot_uint32_t \fBframebuffer_width\fP"
.br
.RI "The width of the framebuffer in pixels\&. "
.ti -1c
.RI "multiboot_uint32_t \fBframebuffer_height\fP"
.br
.RI "The height of the framebuffer in pixels\&. "
.ti -1c
.RI "multiboot_uint8_t \fBframebuffer_bpp\fP"
.br
.RI "The number of bits per pixel\&. "
.ti -1c
.RI "multiboot_uint8_t \fBframebuffer_type\fP"
.br
.RI "The type of framebuffer\&. "
.ti -1c
.RI "multiboot_uint16_t \fBreserved\fP"
.br
.RI "2 bytes reserved "
.in -1c
.SH "Detailed Description"
.PP 
Common header for framebuffer tags\&. 
.PP
Definition at line \fB337\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "multiboot_uint64_t multiboot_tag_framebuffer_common::framebuffer_addr"

.PP
The physical address of the framebuffer\&. 
.PP
Definition at line \fB341\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint8_t multiboot_tag_framebuffer_common::framebuffer_bpp"

.PP
The number of bits per pixel\&. 
.PP
Definition at line \fB345\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_framebuffer_common::framebuffer_height"

.PP
The height of the framebuffer in pixels\&. 
.PP
Definition at line \fB344\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_framebuffer_common::framebuffer_pitch"

.PP
The number of bytes per horizontal line\&. 
.PP
Definition at line \fB342\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint8_t multiboot_tag_framebuffer_common::framebuffer_type"

.PP
The type of framebuffer\&. 
.PP
Definition at line \fB346\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_framebuffer_common::framebuffer_width"

.PP
The width of the framebuffer in pixels\&. 
.PP
Definition at line \fB343\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint16_t multiboot_tag_framebuffer_common::reserved"

.PP
2 bytes reserved 
.PP
Definition at line \fB347\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_framebuffer_common::size"

.PP
*copydoc \fBmultiboot_tag::size\fP 
.PP
Definition at line \fB339\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_framebuffer_common::type"

.PP
*copydoc \fBmultiboot_tag::type\fP 
.PP
Definition at line \fB338\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
