.TH "multiboot_header_tag_address" 3 "Sun Oct 13 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_header_tag_address
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint16_t\fP \fBflags\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBheader_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBload_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBload_end_addr\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBbss_end_addr\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 127 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_address::bss_end_addr"

.PP
Definition at line 135 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_header_tag_address::flags"

.PP
Definition at line 130 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_address::header_addr"

.PP
Definition at line 132 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_address::load_addr"

.PP
Definition at line 133 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_address::load_end_addr"

.PP
Definition at line 134 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_header_tag_address::size"

.PP
Definition at line 131 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint16_t\fP multiboot_header_tag_address::type"

.PP
Definition at line 129 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
