.TH "multiboot_tag_efi_mmap" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_efi_mmap \- A tag containing the EFI memory map\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "multiboot_uint32_t \fBtype\fP"
.br
.RI "*copydoc \fBmultiboot_tag::type\fP "
.ti -1c
.RI "multiboot_uint32_t \fBsize\fP"
.br
.RI "*copydoc \fBmultiboot_tag::size\fP "
.ti -1c
.RI "multiboot_uint32_t \fBdescr_size\fP"
.br
.RI "The size of each EFI memory descriptor\&. "
.ti -1c
.RI "multiboot_uint32_t \fBdescr_vers\fP"
.br
.RI "The version of the EFI memory descriptor\&. "
.ti -1c
.RI "multiboot_uint8_t \fBefi_mmap\fP [0]"
.br
.RI "The EFI memory map\&. "
.in -1c
.SH "Detailed Description"
.PP 
A tag containing the EFI memory map\&. 
.PP
Definition at line \fB473\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "multiboot_uint32_t multiboot_tag_efi_mmap::descr_size"

.PP
The size of each EFI memory descriptor\&. 
.PP
Definition at line \fB476\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_efi_mmap::descr_vers"

.PP
The version of the EFI memory descriptor\&. 
.PP
Definition at line \fB477\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint8_t multiboot_tag_efi_mmap::efi_mmap[0]"

.PP
The EFI memory map\&. 
.PP
Definition at line \fB478\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_efi_mmap::size"

.PP
*copydoc \fBmultiboot_tag::size\fP 
.PP
Definition at line \fB475\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_efi_mmap::type"

.PP
*copydoc \fBmultiboot_tag::type\fP 
.PP
Definition at line \fB474\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
