.TH "multiboot_tag_efi64" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_efi64
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint64_t\fP \fBpointer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB347\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint64_t\fP multiboot_tag_efi64::pointer"

.PP
Definition at line \fB351\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_efi64::size"

.PP
Definition at line \fB350\fP of file \fBmultiboot\&.h\fP\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_efi64::type"

.PP
Definition at line \fB349\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
