.TH "multiboot_tag_efi32_ih" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_efi32_ih
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBtype\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBmultiboot_uint32_t\fP \fBpointer\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 394 of file multiboot\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_efi32_ih::pointer"

.PP
Definition at line 398 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_efi32_ih::size"

.PP
Definition at line 397 of file multiboot\&.h\&.
.SS "\fBmultiboot_uint32_t\fP multiboot_tag_efi32_ih::type"

.PP
Definition at line 396 of file multiboot\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
