.TH "multiboot_tag_elf_sections" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_tag_elf_sections \- A tag containing information about the ELF sections of the OS image\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "multiboot_uint32_t \fBtype\fP"
.br
.RI "*copydoc \fBmultiboot_tag::type\fP "
.ti -1c
.RI "multiboot_uint32_t \fBsize\fP"
.br
.RI "*copydoc \fBmultiboot_tag::size\fP "
.ti -1c
.RI "multiboot_uint32_t \fBnum\fP"
.br
.RI "The number of section headers\&. "
.ti -1c
.RI "multiboot_uint32_t \fBentsize\fP"
.br
.RI "The size of each section header\&. "
.ti -1c
.RI "multiboot_uint32_t \fBshndx\fP"
.br
.RI "The section header string table index\&. "
.ti -1c
.RI "char \fBsections\fP [0]"
.br
.RI "The section headers\&. "
.in -1c
.SH "Detailed Description"
.PP 
A tag containing information about the ELF sections of the OS image\&. 
.PP
Definition at line \fB379\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "multiboot_uint32_t multiboot_tag_elf_sections::entsize"

.PP
The size of each section header\&. 
.PP
Definition at line \fB383\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_elf_sections::num"

.PP
The number of section headers\&. 
.PP
Definition at line \fB382\fP of file \fBmultiboot\&.h\fP\&.
.SS "char multiboot_tag_elf_sections::sections[0]"

.PP
The section headers\&. 
.PP
Definition at line \fB385\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_elf_sections::shndx"

.PP
The section header string table index\&. 
.PP
Definition at line \fB384\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_elf_sections::size"

.PP
*copydoc \fBmultiboot_tag::size\fP 
.PP
Definition at line \fB381\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_tag_elf_sections::type"

.PP
*copydoc \fBmultiboot_tag::type\fP 
.PP
Definition at line \fB380\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
