.TH "multiboot_header" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
multiboot_header \- Contains the Multiboot 2 header information\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <multiboot\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "multiboot_uint32_t \fBmagic\fP"
.br
.RI "The magic number identifying the header (Must be MULTIBOOT2_HEADER_MAGIC) "
.ti -1c
.RI "multiboot_uint32_t \fBarchitecture\fP"
.br
.RI "The architecture the OS image is for\&. "
.ti -1c
.RI "multiboot_uint32_t \fBheader_length\fP"
.br
.RI "Total length of the multiboot header\&. "
.ti -1c
.RI "multiboot_uint32_t \fBchecksum\fP"
.br
.RI "The fields of this structure added together must equal 0 mod 2^32\&. "
.in -1c
.SH "Detailed Description"
.PP 
Contains the Multiboot 2 header information\&. 
.PP
Definition at line \fB101\fP of file \fBmultiboot\&.h\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "multiboot_uint32_t multiboot_header::architecture"

.PP
The architecture the OS image is for\&. 
.PP
Definition at line \fB103\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_header::checksum"

.PP
The fields of this structure added together must equal 0 mod 2^32\&. 
.PP
Definition at line \fB105\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_header::header_length"

.PP
Total length of the multiboot header\&. 
.PP
Definition at line \fB104\fP of file \fBmultiboot\&.h\fP\&.
.SS "multiboot_uint32_t multiboot_header::magic"

.PP
The magic number identifying the header (Must be MULTIBOOT2_HEADER_MAGIC) 
.PP
Definition at line \fB102\fP of file \fBmultiboot\&.h\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
