.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/port.h" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/hardwarecommunication/port.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::Port\fP"
.br
.RI "base class for all ports "
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::Port8Bit\fP"
.br
.RI "Handles 8 bit ports\&. "
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::Port8BitSlow\fP"
.br
.RI "Handles 8 bit ports (slow) "
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::Port16Bit\fP"
.br
.RI "Handles 16 bit ports\&. "
.ti -1c
.RI "class \fBMaxOS::hardwarecommunication::Port32Bit\fP"
.br
.RI "Handles 32 bit ports\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMaxOS\fP"
.br
.ti -1c
.RI " \fBMaxOS::hardwarecommunication\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
