.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/ethernet/rawdatahandler.h" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/ethernet/rawdatahandler.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaxOS::drivers::ethernet::RawDataHandler\fP"
.br
.RI "Handles raw data received from the ethernet controller\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmaxOS\fP"
.br
.ti -1c
.RI " \fBmaxOS::drivers\fP"
.br
.ti -1c
.RI " \fBmaxOS::drivers::ethernet\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
