.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/console/serial.cpp" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/console/serial.cpp \- Implements a Serial Console for logging over a serial port\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <drivers/console/serial\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implements a Serial Console for logging over a serial port\&. 


.PP
\fBDate\fP
.RS 4
15th January 2024 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBserial\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
