.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/common/string.h" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/common/string.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::String\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMaxOS\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef String \fBMaxOS::string\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBstrcmp\fP (char const *str1, char const *str2)"
.br
.RI "Checks if one string is equal to another\&. "
.ti -1c
.RI "bool \fBstrcmp\fP (char const *str1, \fBMaxOS::String\fP const &str2)"
.br
.ti -1c
.RI "bool \fBstrcmp\fP (\fBMaxOS::String\fP const &str1, char const *str2)"
.br
.ti -1c
.RI "bool \fBstrcmp\fP (\fBMaxOS::String\fP const &str1, \fBMaxOS::String\fP const &str2)"
.br
.ti -1c
.RI "bool \fBstrncmp\fP (char const *str1, char const *str2, int \fBlength\fP)"
.br
.RI "Checks if one string is equal to another\&. "
.ti -1c
.RI "bool \fBstrncmp\fP (char const *str1, \fBMaxOS::String\fP const &str2, int \fBlength\fP)"
.br
.ti -1c
.RI "bool \fBstrncmp\fP (\fBMaxOS::String\fP const &str1, char const *str2, int \fBlength\fP)"
.br
.ti -1c
.RI "bool \fBstrncmp\fP (\fBMaxOS::String\fP const &str1, \fBMaxOS::String\fP const &str2, int \fBlength\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool strcmp (char const * str1, char const * str2)"

.PP
Checks if one string is equal to another\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr1\fP The first string 
.br
\fIstr2\fP The second string 
.RE
.PP
\fBReturns\fP
.RS 4
True if the strings are equal, false otherwise 
.RE
.PP

.PP
Definition at line 460 of file string\&.cpp\&.
.PP
.nf
460                                                 {
461 
462     // Check if the strings are equal
463     for (int i = 0; str1[i] != '\0' || str2[i] != '\0'; i++)
464       if (str1[i] != str2[i])
465             return false;
466 
467     // The strings are equal
468         return true;
469 
470 }
.fi
.PP
References MaxOS::drivers::peripherals::i\&.
.PP
Referenced by MaxOS::drivers::console::VESABootConsole::put_character(), and strcmp()\&.
.SS "bool strcmp (char const * str1, \fBMaxOS::String\fP const & str2)"

.PP
Definition at line 472 of file string\&.cpp\&.
.PP
.nf
472                                                   {
473 
474   // Use the other strcmp function
475   return strcmp(str1, str2\&.c_str());
476 
477 }
.fi
.PP
References MaxOS::String::c_str(), and strcmp()\&.
.SS "bool strcmp (\fBMaxOS::String\fP const & str1, char const * str2)"

.PP
Definition at line 479 of file string\&.cpp\&.
.PP
.nf
479                                                   {
480 
481     // Use the other strcmp function
482     return strcmp(str1\&.c_str(), str2);
483 }
.fi
.PP
References MaxOS::String::c_str(), and strcmp()\&.
.SS "bool strcmp (\fBMaxOS::String\fP const & str1, \fBMaxOS::String\fP const & str2)"

.PP
Definition at line 485 of file string\&.cpp\&.
.PP
.nf
485                                                     {
486 
487   // Use the other strcmp function
488   return strcmp(str1\&.c_str(), str2\&.c_str());
489 
490 }
.fi
.PP
References MaxOS::String::c_str(), and strcmp()\&.
.SS "bool strncmp (char const * str1, char const * str2, int length)"

.PP
Checks if one string is equal to another\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr1\fP The first string 
.br
\fIstr2\fP The second string 
.br
\fIlength\fP The length of the strings 
.RE
.PP
\fBReturns\fP
.RS 4
True if the strings are equal, false otherwise 
.RE
.PP

.PP
Definition at line 500 of file string\&.cpp\&.
.PP
.nf
500                                                              {
501 
502   // Check if the strings are equal
503   for (int i = 0; i < length; i++)
504     if (str1[i] != str2[i])
505         return false;
506 
507   // Strings are equal
508   return true;
509 
510 }
.fi
.PP
References MaxOS::drivers::peripherals::i, and length\&.
.PP
Referenced by MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::find(), and strncmp()\&.
.SS "bool strncmp (char const * str1, \fBMaxOS::String\fP const & str2, int length)"

.PP
Definition at line 512 of file string\&.cpp\&.
.PP
.nf
512                                                                {
513 
514   // Use the other strncmp function
515   return strncmp(str1, str2\&.c_str(), length);
516 
517 }
.fi
.PP
References MaxOS::String::c_str(), length, and strncmp()\&.
.SS "bool strncmp (\fBMaxOS::String\fP const & str1, char const * str2, int length)"

.PP
Definition at line 519 of file string\&.cpp\&.
.PP
.nf
519                                                                {
520 
521   // Use the other strncmp function
522   return strncmp(str1\&.c_str(), str2, length);
523 
524 }
.fi
.PP
References MaxOS::String::c_str(), length, and strncmp()\&.
.SS "bool strncmp (\fBMaxOS::String\fP const & str1, \fBMaxOS::String\fP const & str2, int length)"

.PP
Definition at line 526 of file string\&.cpp\&.
.PP
.nf
526                                                                  {
527 
528   // Use the other strncmp function
529   return strncmp(str1\&.c_str(), str2\&.c_str(), length);
530 }
.fi
.PP
References MaxOS::String::c_str(), length, and strncmp()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
