.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/common/string.cpp" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/common/string.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <common/string\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBstrcmp\fP (char const *str1, char const *str2)"
.br
.RI "Checks if one string is equal to another\&. "
.ti -1c
.RI "bool \fBstrcmp\fP (char const *str1, \fBString\fP const &str2)"
.br
.ti -1c
.RI "bool \fBstrcmp\fP (\fBString\fP const &str1, char const *str2)"
.br
.ti -1c
.RI "bool \fBstrcmp\fP (\fBString\fP const &str1, \fBString\fP const &str2)"
.br
.ti -1c
.RI "bool \fBstrncmp\fP (char const *str1, char const *str2, int \fBlength\fP)"
.br
.RI "Checks if one string is equal to another\&. "
.ti -1c
.RI "bool \fBstrncmp\fP (char const *str1, \fBString\fP const &str2, int \fBlength\fP)"
.br
.ti -1c
.RI "bool \fBstrncmp\fP (\fBString\fP const &str1, char const *str2, int \fBlength\fP)"
.br
.ti -1c
.RI "bool \fBstrncmp\fP (\fBString\fP const &str1, \fBString\fP const &str2, int \fBlength\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool strcmp (char const * str1, char const * str2)"

.PP
Checks if one string is equal to another\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr1\fP The first string 
.br
\fIstr2\fP The second string 
.RE
.PP
\fBReturns\fP
.RS 4
True if the strings are equal, false otherwise 
.RE
.PP

.PP
Definition at line 438 of file string\&.cpp\&.
.PP
.nf
438                                                 {
439 
440     // Check if the strings are equal
441     for (int i = 0; str1[i] != '\0' || str2[i] != '\0'; i++)
442       if (str1[i] != str2[i])
443             return false;
444 
445     // The strings are equal
446         return true;
447 
448 }
.fi
.PP
References MaxOS::drivers::peripherals::i\&.
.PP
Referenced by MaxOS::drivers::console::VESABootConsole::put_character(), and strcmp()\&.
.SS "bool strcmp (char const * str1, \fBString\fP const & str2)"

.PP
Definition at line 450 of file string\&.cpp\&.
.PP
.nf
450                                                   {
451 
452   // Use the other strcmp function
453   return strcmp(str1, str2\&.c_str());
454 
455 }
.fi
.PP
References MaxOS::String::c_str(), and strcmp()\&.
.SS "bool strcmp (\fBString\fP const & str1, char const * str2)"

.PP
Definition at line 457 of file string\&.cpp\&.
.PP
.nf
457                                                   {
458 
459     // Use the other strcmp function
460     return strcmp(str1\&.c_str(), str2);
461 }
.fi
.PP
References MaxOS::String::c_str(), and strcmp()\&.
.SS "bool strcmp (\fBString\fP const & str1, \fBString\fP const & str2)"

.PP
Definition at line 463 of file string\&.cpp\&.
.PP
.nf
463                                                     {
464 
465   // Use the other strcmp function
466   return strcmp(str1\&.c_str(), str2\&.c_str());
467 
468 }
.fi
.PP
References MaxOS::String::c_str(), and strcmp()\&.
.SS "bool strncmp (char const * str1, char const * str2, int length)"

.PP
Checks if one string is equal to another\&. 
.PP
\fBParameters\fP
.RS 4
\fIstr1\fP The first string 
.br
\fIstr2\fP The second string 
.br
\fIlength\fP The length of the strings 
.RE
.PP
\fBReturns\fP
.RS 4
True if the strings are equal, false otherwise 
.RE
.PP

.PP
Definition at line 478 of file string\&.cpp\&.
.PP
.nf
478                                                              {
479 
480   // Check if the strings are equal
481   for (int i = 0; i < length; i++)
482     if (str1[i] != str2[i])
483         return false;
484 
485   // Strings are equal
486   return true;
487 
488 }
.fi
.PP
References MaxOS::drivers::peripherals::i, and length\&.
.PP
Referenced by MaxOS::hardwarecommunication::AdvancedConfigurationAndPowerInterface::find(), and strncmp()\&.
.SS "bool strncmp (char const * str1, \fBString\fP const & str2, int length)"

.PP
Definition at line 490 of file string\&.cpp\&.
.PP
.nf
490                                                                {
491 
492   // Use the other strncmp function
493   return strncmp(str1, str2\&.c_str(), length);
494 
495 }
.fi
.PP
References MaxOS::String::c_str(), length, and strncmp()\&.
.SS "bool strncmp (\fBString\fP const & str1, char const * str2, int length)"

.PP
Definition at line 497 of file string\&.cpp\&.
.PP
.nf
497                                                                {
498 
499   // Use the other strncmp function
500   return strncmp(str1\&.c_str(), str2, length);
501 
502 }
.fi
.PP
References MaxOS::String::c_str(), length, and strncmp()\&.
.SS "bool strncmp (\fBString\fP const & str1, \fBString\fP const & str2, int length)"

.PP
Definition at line 504 of file string\&.cpp\&.
.PP
.nf
504                                                                  {
505 
506   // Use the other strncmp function
507   return strncmp(str1\&.c_str(), str2\&.c_str(), length);
508 }
.fi
.PP
References MaxOS::String::c_str(), length, and strncmp()\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
