.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/gui/widgets/text.cpp" 3 "Sun Oct 13 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/gui/widgets/text.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <gui/font/amiga_font\&.h>\fP
.br
\fC#include <gui/widgets/text\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
