.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/textmode.h" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/textmode.h \- Defines a TextModeConsole class for handling a console in text mode using VGA\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdint>\fP
.br
\fC#include <drivers/driver\&.h>\fP
.br
\fC#include <drivers/console/console\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::drivers::console::TextModeConsole\fP"
.br
.RI "\fBDriver\fP for the text mode console, handles the printing of characters and strings to the screen using VGA\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a TextModeConsole class for handling a console in text mode using VGA\&. 


.PP
\fBDate\fP
.RS 4
27th September 2023 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBtextmode\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
