.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/textmode.h" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/console/textmode.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <drivers/driver\&.h>\fP
.br
\fC#include <drivers/console/console\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::drivers::console::TextModeConsole\fP"
.br
.RI "\fBDriver\fP for the text mode console, handles the printing of characters and strings to the screen using VGA\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMaxOS\fP"
.br
.ti -1c
.RI " \fBMaxOS::drivers\fP"
.br
.ti -1c
.RI " \fBMaxOS::drivers::console\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
