.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/common/time.h" 3 "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/common/time.h \- Defines a Time struct for storing date and time information, along with functions for time manipulation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::common::Time\fP"
.br
.RI "Stores the year, month, day, hour, minute and second of a time\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "\fBtypedef\fP \fBstruct\fP \fBMaxOS::common::Time\fP \fBMaxOS::common::time_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBconstexpr\fP \fBuint8_t\fP \fBMaxOS::common::DAYS_IN_MONTH\fP []"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBuint16_t\fP \fBMaxOS::common::DAYS_PER_YEAR\fP = 365"
.br
.ti -1c
.RI "\fBconstexpr\fP \fBuint16_t\fP \fBMaxOS::common::DAYS_PER_LEAP_YEAR\fP = 366"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines a Time struct for storing date and time information, along with functions for time manipulation\&. 


.PP
\fBDate\fP
.RS 4
10th April 2023 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBtime\&.h\fP\&.
.SH "Variable Documentation"
.PP 
.SS "constexpr uint8_t MaxOS::common::DAYS_IN_MONTH[]\fC [constexpr]\fP"
\fBInitial value:\fP.PP
.nf
= {
            31, 
            28, 
            31, 
            30, 
            31, 
            30, 
            31, 
            31, 
            30, 
            31, 
            30, 
            31  
        }
.fi

.PP
Definition at line \fB67\fP of file \fBtime\&.h\fP\&..PP
.nf
67                                             {
68             31, // January
69             28, // February
70             31, // March
71             30, // April
72             31, // May
73             30, // June
74             31, // July
75             31, // August
76             30, // September
77             31, // October
78             30, // November
79             31  // December
80         };
.fi

.SS "constexpr uint16_t MaxOS::common::DAYS_PER_LEAP_YEAR = 366\fC [constexpr]\fP"

.PP
Definition at line \fB83\fP of file \fBtime\&.h\fP\&.
.SS "constexpr uint16_t MaxOS::common::DAYS_PER_YEAR = 365\fC [constexpr]\fP"

.PP
Definition at line \fB82\fP of file \fBtime\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
