.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/system/ubsan.h" 3 "Sat Mar 29 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/system/ubsan.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBMaxOS::system::source_location\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::system::type_descriptor\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::system::type_mismatch_info\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::system::type_mismatch_info_v1\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::system::overflow_info\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::system::shift_out_of_bounds_info\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::system::out_of_bounds_info\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::system::location_only_info\fP"
.br
.ti -1c
.RI "struct \fBMaxOS::system::invalid_value_info\fP"
.br
.ti -1c
.RI "class \fBMaxOS::system::UBSanHandler\fP"
.br
.RI "Handles undefined behaviour sanitizer\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMaxOS\fP"
.br
.ti -1c
.RI " \fBMaxOS::system\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBubsan_aligned\fP(value,  alignment)   !(value & (alignment \- 1))"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef struct \fBMaxOS::system::source_location\fP \fBMaxOS::system::source_location_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::type_descriptor\fP \fBMaxOS::system::type_descriptor_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::type_mismatch_info\fP \fBMaxOS::system::type_mismatch_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::type_mismatch_info_v1\fP \fBMaxOS::system::type_mismatch_info_v1_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::overflow_info\fP \fBMaxOS::system::overflow_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::shift_out_of_bounds_info\fP \fBMaxOS::system::shift_out_of_bounds_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::out_of_bounds_info\fP \fBMaxOS::system::out_of_bounds_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::location_only_info\fP \fBMaxOS::system::location_only_info_t\fP"
.br
.ti -1c
.RI "typedef struct \fBMaxOS::system::invalid_value_info\fP \fBMaxOS::system::invalid_value_info_t\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const char * \fBMaxOS::system::Type_Check_Kinds\fP []"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define ubsan_aligned(value, alignment)   !(value & (alignment \- 1))"

.PP
Definition at line 13 of file ubsan\&.h\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
