.TH "/home/runner/work/max-os/max-os/kernel/include/common/vector.h" 3 "Fri Jan 5 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/max-os/max-os/kernel/include/common/vector.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBmaxOS::common::VectorIterationHandler< Type >\fP"
.br
.RI "Handles the iteration of a \fBVector\fP providing read and end of stream functions\&. "
.ti -1c
.RI "class \fBmaxOS::common::Vector< Type >\fP"
.br
.RI "Dynamically stores an array of elements\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBmaxOS\fP"
.br
.ti -1c
.RI " \fBmaxOS::common\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
