.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/video/vesa.cpp" 3 "Tue Feb 25 2025" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/drivers/video/vesa.cpp
.SH SYNOPSIS
.br
.PP
\fC#include <drivers/video/vesa\&.h>\fP
.br
\fC#include <common/kprint\&.h>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
