.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/video/vga.h" 3 "Mon Jan 15 2024" "Version 0.1" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/drivers/video/vga.h
.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <common/string\&.h>\fP
.br
\fC#include <hardwarecommunication/interrupts\&.h>\fP
.br
\fC#include <hardwarecommunication/port\&.h>\fP
.br
\fC#include <drivers/video/video\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::drivers::video::VideoGraphicsArray\fP"
.br
.RI "\fBDriver\fP for the VGA graphics controller, handles the rendering of pixels to the screen\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBMaxOS\fP"
.br
.ti -1c
.RI " \fBMaxOS::drivers\fP"
.br
.ti -1c
.RI " \fBMaxOS::drivers::video\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
