.TH "/home/runner/work/MaxOS/MaxOS/kernel/include/gui/widget.h" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/include/gui/widget.h \- Defines a base Widget class and CompositeWidget class for creating graphical user interface elements\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <stdint\&.h>\fP
.br
\fC#include <common/rectangle\&.h>\fP
.br
\fC#include <common/vector\&.h>\fP
.br
\fC#include <common/graphicsContext\&.h>\fP
.br
\fC#include <common/coordinates\&.h>\fP
.br
\fC#include <drivers/peripherals/keyboard\&.h>\fP
.br
\fC#include <drivers/peripherals/mouse\&.h>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMaxOS::gui::Widget\fP"
.br
.RI "A graphical object that can be drawn on the screen\&. "
.ti -1c
.RI "class \fBMaxOS::gui::CompositeWidget\fP"
.br
.RI "A widget that can contain other widgets\&. "
.ti -1c
.RI "class \fBMaxOS::gui::WidgetMoverResizer< Left, Top, Width, Height >\fP"
.br
.RI "A template class that allows you to move and resize a widget\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 1, 1, 0, 0 > \fBMaxOS::gui::WidgetMover\fP"
.br
.RI "A widget mover that moves the widget without resizing it\&. "
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 1, 0, \-1 > \fBMaxOS::gui::WidgetMoverResizerTop\fP"
.br
.RI "A widget mover and resizer that resizes the top edge of the widget\&. "
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 0, 0, 1 > \fBMaxOS::gui::WidgetMoverResizerBottom\fP"
.br
.RI "A widget mover andresizer that resizes the bottom edge of the widget\&. "
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 1, 0, \-1, 0 > \fBMaxOS::gui::WidgetMoverResizerLeft\fP"
.br
.RI "A widget mover and resizer that resizes the left edge of the widget\&. "
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 0, 1, 0 > \fBMaxOS::gui::WidgetMoverResizerRight\fP"
.br
.RI "A widget mover and resizer that resizes the right edge of the widget\&. "
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 1, 1, \-1, \-1 > \fBMaxOS::gui::WidgetMoverResizerTopLeft\fP"
.br
.RI "A widget mover and resizer that resizes the top-left corner of the widget\&. "
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 1, 1, \-1 > \fBMaxOS::gui::WidgetMoverResizerTopRight\fP"
.br
.RI "A widget mover and resizer that resizes the top-right corner of the widget\&. "
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 1, 0, \-1, 1 > \fBMaxOS::gui::WidgetMoverResizerBottomLeft\fP"
.br
.RI "A widget mover and resizer that resizes the bottom-left corner of the widget\&. "
.ti -1c
.RI "typedef \fBWidgetMoverResizer\fP< 0, 0, 1, 1 > \fBMaxOS::gui::WidgetMoverResizerBottomRight\fP"
.br
.RI "A widget mover and resizer that resizes the bottom-right corner of the widget\&. "
.in -1c
.SH "Detailed Description"
.PP 
Defines a base Widget class and CompositeWidget class for creating graphical user interface elements\&. 


.PP
\fBDate\fP
.RS 4
15th October 2022 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBwidget\&.h\fP\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef WidgetMoverResizer<1, 1, 0, 0> \fBMaxOS::gui::WidgetMover\fP"

.PP
A widget mover that moves the widget without resizing it\&. 
.PP
Definition at line \fB139\fP of file \fBwidget\&.h\fP\&.
.SS "typedef WidgetMoverResizer<0, 0, 0, 1> \fBMaxOS::gui::WidgetMoverResizerBottom\fP"

.PP
A widget mover andresizer that resizes the bottom edge of the widget\&. 
.PP
Definition at line \fB142\fP of file \fBwidget\&.h\fP\&.
.SS "typedef WidgetMoverResizer<1, 0, \-1, 1> \fBMaxOS::gui::WidgetMoverResizerBottomLeft\fP"

.PP
A widget mover and resizer that resizes the bottom-left corner of the widget\&. 
.PP
Definition at line \fB148\fP of file \fBwidget\&.h\fP\&.
.SS "typedef WidgetMoverResizer<0, 0, 1, 1> \fBMaxOS::gui::WidgetMoverResizerBottomRight\fP"

.PP
A widget mover and resizer that resizes the bottom-right corner of the widget\&. 
.PP
Definition at line \fB149\fP of file \fBwidget\&.h\fP\&.
.SS "typedef WidgetMoverResizer<1, 0, \-1, 0> \fBMaxOS::gui::WidgetMoverResizerLeft\fP"

.PP
A widget mover and resizer that resizes the left edge of the widget\&. 
.PP
Definition at line \fB143\fP of file \fBwidget\&.h\fP\&.
.SS "typedef WidgetMoverResizer<0, 0, 1, 0> \fBMaxOS::gui::WidgetMoverResizerRight\fP"

.PP
A widget mover and resizer that resizes the right edge of the widget\&. 
.PP
Definition at line \fB144\fP of file \fBwidget\&.h\fP\&.
.SS "typedef WidgetMoverResizer<0, 1, 0, \-1> \fBMaxOS::gui::WidgetMoverResizerTop\fP"

.PP
A widget mover and resizer that resizes the top edge of the widget\&. 
.PP
Definition at line \fB141\fP of file \fBwidget\&.h\fP\&.
.SS "typedef WidgetMoverResizer<1, 1, \-1, \-1> \fBMaxOS::gui::WidgetMoverResizerTopLeft\fP"

.PP
A widget mover and resizer that resizes the top-left corner of the widget\&. 
.PP
Definition at line \fB146\fP of file \fBwidget\&.h\fP\&.
.SS "typedef WidgetMoverResizer<0, 1, 1, \-1> \fBMaxOS::gui::WidgetMoverResizerTopRight\fP"

.PP
A widget mover and resizer that resizes the top-right corner of the widget\&. 
.PP
Definition at line \fB147\fP of file \fBwidget\&.h\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
