.TH "/home/runner/work/MaxOS/MaxOS/kernel/src/gui/widget.cpp" 3 "Version 0.3" "Max OS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/runner/work/MaxOS/MaxOS/kernel/src/gui/widget.cpp \- Implementation of a GUI Widget base class for creating GUI elements\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <gui/widget\&.h>\fP
.br

.SH "Detailed Description"
.PP 
Implementation of a GUI Widget base class for creating GUI elements\&. 


.PP
\fBDate\fP
.RS 4
15th October 2022 
.RE
.PP
\fBAuthor\fP
.RS 4
Max Tyson 
.RE
.PP

.PP
Definition in file \fBwidget\&.cpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Max OS from the source code\&.
