var annotated_dup =
[
    [ "MaxOS", null, [
      [ "common", null, [
        [ "BlockingLock", "classMaxOS_1_1common_1_1BlockingLock.html", "classMaxOS_1_1common_1_1BlockingLock" ],
        [ "Buffer", "classMaxOS_1_1common_1_1Buffer.html", "classMaxOS_1_1common_1_1Buffer" ],
        [ "Colour", "classMaxOS_1_1common_1_1Colour.html", "classMaxOS_1_1common_1_1Colour" ],
        [ "Event", "classMaxOS_1_1common_1_1Event.html", "classMaxOS_1_1common_1_1Event" ],
        [ "EventHandler", "classMaxOS_1_1common_1_1EventHandler.html", "classMaxOS_1_1common_1_1EventHandler" ],
        [ "EventManager", "classMaxOS_1_1common_1_1EventManager.html", "classMaxOS_1_1common_1_1EventManager" ],
        [ "GenericInputStream", "classMaxOS_1_1common_1_1GenericInputStream.html", "classMaxOS_1_1common_1_1GenericInputStream" ],
        [ "GenericOutputStream", "classMaxOS_1_1common_1_1GenericOutputStream.html", "classMaxOS_1_1common_1_1GenericOutputStream" ],
        [ "GraphicsContext", "classMaxOS_1_1common_1_1GraphicsContext.html", "classMaxOS_1_1common_1_1GraphicsContext" ],
        [ "InputStream", "classMaxOS_1_1common_1_1InputStream.html", "classMaxOS_1_1common_1_1InputStream" ],
        [ "InputStreamBuffer", "classMaxOS_1_1common_1_1InputStreamBuffer.html", "classMaxOS_1_1common_1_1InputStreamBuffer" ],
        [ "InputStreamEventHandler", "classMaxOS_1_1common_1_1InputStreamEventHandler.html", "classMaxOS_1_1common_1_1InputStreamEventHandler" ],
        [ "InputStreamProcessor", "classMaxOS_1_1common_1_1InputStreamProcessor.html", "classMaxOS_1_1common_1_1InputStreamProcessor" ],
        [ "InputStreamSocket", "classMaxOS_1_1common_1_1InputStreamSocket.html", "classMaxOS_1_1common_1_1InputStreamSocket" ],
        [ "Map", "classMaxOS_1_1common_1_1Map.html", "classMaxOS_1_1common_1_1Map" ],
        [ "MapIterationHandler", "classMaxOS_1_1common_1_1MapIterationHandler.html", "classMaxOS_1_1common_1_1MapIterationHandler" ],
        [ "OutputStream", "classMaxOS_1_1common_1_1OutputStream.html", "classMaxOS_1_1common_1_1OutputStream" ],
        [ "Pair", "classMaxOS_1_1common_1_1Pair.html", "classMaxOS_1_1common_1_1Pair" ],
        [ "Rectangle", "classMaxOS_1_1common_1_1Rectangle.html", "classMaxOS_1_1common_1_1Rectangle" ],
        [ "Spinlock", "classMaxOS_1_1common_1_1Spinlock.html", "classMaxOS_1_1common_1_1Spinlock" ],
        [ "Time", "structMaxOS_1_1common_1_1Time.html", "structMaxOS_1_1common_1_1Time" ],
        [ "Vector", "classMaxOS_1_1common_1_1Vector.html", "classMaxOS_1_1common_1_1Vector" ],
        [ "VectorIterationHandler", "classMaxOS_1_1common_1_1VectorIterationHandler.html", "classMaxOS_1_1common_1_1VectorIterationHandler" ]
      ] ],
      [ "drivers", null, [
        [ "clock", null, [
          [ "Clock", "classMaxOS_1_1drivers_1_1clock_1_1Clock.html", "classMaxOS_1_1drivers_1_1clock_1_1Clock" ],
          [ "PIT", "classMaxOS_1_1drivers_1_1clock_1_1PIT.html", "classMaxOS_1_1drivers_1_1clock_1_1PIT" ],
          [ "PITCommand", "structMaxOS_1_1drivers_1_1clock_1_1PITCommand.html", "structMaxOS_1_1drivers_1_1clock_1_1PITCommand" ]
        ] ],
        [ "console", null, [
          [ "Console", "classMaxOS_1_1drivers_1_1console_1_1Console.html", "classMaxOS_1_1drivers_1_1console_1_1Console" ],
          [ "ConsoleArea", "classMaxOS_1_1drivers_1_1console_1_1ConsoleArea.html", "classMaxOS_1_1drivers_1_1console_1_1ConsoleArea" ],
          [ "ConsoleStream", "classMaxOS_1_1drivers_1_1console_1_1ConsoleStream.html", "classMaxOS_1_1drivers_1_1console_1_1ConsoleStream" ],
          [ "TextModeConsole", "classMaxOS_1_1drivers_1_1console_1_1TextModeConsole.html", "classMaxOS_1_1drivers_1_1console_1_1TextModeConsole" ],
          [ "VESABootConsole", "classMaxOS_1_1drivers_1_1console_1_1VESABootConsole.html", "classMaxOS_1_1drivers_1_1console_1_1VESABootConsole" ]
        ] ],
        [ "disk", null, [
          [ "AdvancedTechnologyAttachment", "classMaxOS_1_1drivers_1_1disk_1_1AdvancedTechnologyAttachment.html", "classMaxOS_1_1drivers_1_1disk_1_1AdvancedTechnologyAttachment" ],
          [ "Disk", "classMaxOS_1_1drivers_1_1disk_1_1Disk.html", "classMaxOS_1_1drivers_1_1disk_1_1Disk" ],
          [ "IntegratedDriveElectronicsController", "classMaxOS_1_1drivers_1_1disk_1_1IntegratedDriveElectronicsController.html", "classMaxOS_1_1drivers_1_1disk_1_1IntegratedDriveElectronicsController" ]
        ] ],
        [ "ethernet", null, [
          [ "AMD_AM79C973", "classMaxOS_1_1drivers_1_1ethernet_1_1AMD__AM79C973.html", "classMaxOS_1_1drivers_1_1ethernet_1_1AMD__AM79C973" ],
          [ "BeforeSendEvent", "classMaxOS_1_1drivers_1_1ethernet_1_1BeforeSendEvent.html", "classMaxOS_1_1drivers_1_1ethernet_1_1BeforeSendEvent" ],
          [ "BufferDescriptor", "structMaxOS_1_1drivers_1_1ethernet_1_1BufferDescriptor.html", "structMaxOS_1_1drivers_1_1ethernet_1_1BufferDescriptor" ],
          [ "DataReceivedEvent", "classMaxOS_1_1drivers_1_1ethernet_1_1DataReceivedEvent.html", "classMaxOS_1_1drivers_1_1ethernet_1_1DataReceivedEvent" ],
          [ "DataSentEvent", "classMaxOS_1_1drivers_1_1ethernet_1_1DataSentEvent.html", "classMaxOS_1_1drivers_1_1ethernet_1_1DataSentEvent" ],
          [ "EthernetDriver", "classMaxOS_1_1drivers_1_1ethernet_1_1EthernetDriver.html", "classMaxOS_1_1drivers_1_1ethernet_1_1EthernetDriver" ],
          [ "EthernetDriverEventHandler", "classMaxOS_1_1drivers_1_1ethernet_1_1EthernetDriverEventHandler.html", "classMaxOS_1_1drivers_1_1ethernet_1_1EthernetDriverEventHandler" ],
          [ "InitializationBlock", "structMaxOS_1_1drivers_1_1ethernet_1_1InitializationBlock.html", "structMaxOS_1_1drivers_1_1ethernet_1_1InitializationBlock" ],
          [ "IntelI217", "classMaxOS_1_1drivers_1_1ethernet_1_1IntelI217.html", "classMaxOS_1_1drivers_1_1ethernet_1_1IntelI217" ],
          [ "RawDataHandler", "classMaxOS_1_1drivers_1_1ethernet_1_1RawDataHandler.html", "classMaxOS_1_1drivers_1_1ethernet_1_1RawDataHandler" ],
          [ "ReceiveDescriptor", "structMaxOS_1_1drivers_1_1ethernet_1_1ReceiveDescriptor.html", "structMaxOS_1_1drivers_1_1ethernet_1_1ReceiveDescriptor" ],
          [ "SendDescriptor", "structMaxOS_1_1drivers_1_1ethernet_1_1SendDescriptor.html", "structMaxOS_1_1drivers_1_1ethernet_1_1SendDescriptor" ]
        ] ],
        [ "peripherals", null, [
          [ "KeyboardDriver", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardDriver.html", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardDriver" ],
          [ "KeyboardEventHandler", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardEventHandler.html", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardEventHandler" ],
          [ "KeyboardInterpreter", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardInterpreter.html", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardInterpreter" ],
          [ "KeyboardInterpreterEN_US", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardInterpreterEN__US.html", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardInterpreterEN__US" ],
          [ "KeyboardState", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardState.html", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyboardState" ],
          [ "KeyDownEvent", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyDownEvent.html", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyDownEvent" ],
          [ "KeyUpEvent", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyUpEvent.html", "classMaxOS_1_1drivers_1_1peripherals_1_1KeyUpEvent" ],
          [ "MouseDownEvent", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseDownEvent.html", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseDownEvent" ],
          [ "MouseDriver", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseDriver.html", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseDriver" ],
          [ "MouseEventHandler", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseEventHandler.html", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseEventHandler" ],
          [ "MouseMoveEvent", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseMoveEvent.html", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseMoveEvent" ],
          [ "MouseUpEvent", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseUpEvent.html", "classMaxOS_1_1drivers_1_1peripherals_1_1MouseUpEvent" ]
        ] ],
        [ "video", null, [
          [ "VideoDriver", "classMaxOS_1_1drivers_1_1video_1_1VideoDriver.html", "classMaxOS_1_1drivers_1_1video_1_1VideoDriver" ],
          [ "VideoElectronicsStandardsAssociation", "classMaxOS_1_1drivers_1_1video_1_1VideoElectronicsStandardsAssociation.html", "classMaxOS_1_1drivers_1_1video_1_1VideoElectronicsStandardsAssociation" ],
          [ "VideoGraphicsArray", "classMaxOS_1_1drivers_1_1video_1_1VideoGraphicsArray.html", "classMaxOS_1_1drivers_1_1video_1_1VideoGraphicsArray" ]
        ] ],
        [ "Driver", "classMaxOS_1_1drivers_1_1Driver.html", "classMaxOS_1_1drivers_1_1Driver" ],
        [ "DriverManager", "classMaxOS_1_1drivers_1_1DriverManager.html", "classMaxOS_1_1drivers_1_1DriverManager" ],
        [ "DriverSelector", "classMaxOS_1_1drivers_1_1DriverSelector.html", "classMaxOS_1_1drivers_1_1DriverSelector" ],
        [ "DriverSelectorEventHandler", "classMaxOS_1_1drivers_1_1DriverSelectorEventHandler.html", "classMaxOS_1_1drivers_1_1DriverSelectorEventHandler" ],
        [ "SerialConsole", "classMaxOS_1_1drivers_1_1SerialConsole.html", "classMaxOS_1_1drivers_1_1SerialConsole" ]
      ] ],
      [ "filesystem", null, [
        [ "format", null, [
          [ "ext2", null, [
            [ "BlockGroupDescriptor", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1BlockGroupDescriptor.html", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1BlockGroupDescriptor" ],
            [ "DirectoryEntry", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1DirectoryEntry.html", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1DirectoryEntry" ],
            [ "Ext2Directory", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Ext2Directory.html", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Ext2Directory" ],
            [ "Ext2File", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Ext2File.html", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Ext2File" ],
            [ "Ext2FileSystem", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Ext2FileSystem.html", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Ext2FileSystem" ],
            [ "Ext2Volume", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Ext2Volume.html", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Ext2Volume" ],
            [ "Inode", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Inode.html", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1Inode" ],
            [ "InodeHandler", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1InodeHandler.html", "classMaxOS_1_1filesystem_1_1format_1_1ext2_1_1InodeHandler" ],
            [ "InodeOS2Linux", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1InodeOS2Linux.html", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1InodeOS2Linux" ],
            [ "SuperBlock", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1SuperBlock.html", "structMaxOS_1_1filesystem_1_1format_1_1ext2_1_1SuperBlock" ]
          ] ],
          [ "BiosParameterBlock32", "structMaxOS_1_1filesystem_1_1format_1_1BiosParameterBlock32.html", "structMaxOS_1_1filesystem_1_1format_1_1BiosParameterBlock32" ],
          [ "DirectoryEntry", "structMaxOS_1_1filesystem_1_1format_1_1DirectoryEntry.html", "structMaxOS_1_1filesystem_1_1format_1_1DirectoryEntry" ],
          [ "Fat32Directory", "classMaxOS_1_1filesystem_1_1format_1_1Fat32Directory.html", "classMaxOS_1_1filesystem_1_1format_1_1Fat32Directory" ],
          [ "Fat32File", "classMaxOS_1_1filesystem_1_1format_1_1Fat32File.html", "classMaxOS_1_1filesystem_1_1format_1_1Fat32File" ],
          [ "Fat32FileSystem", "classMaxOS_1_1filesystem_1_1format_1_1Fat32FileSystem.html", "classMaxOS_1_1filesystem_1_1format_1_1Fat32FileSystem" ],
          [ "Fat32Volume", "classMaxOS_1_1filesystem_1_1format_1_1Fat32Volume.html", "classMaxOS_1_1filesystem_1_1format_1_1Fat32Volume" ],
          [ "FSInfo", "structMaxOS_1_1filesystem_1_1format_1_1FSInfo.html", "structMaxOS_1_1filesystem_1_1format_1_1FSInfo" ],
          [ "LongFileNameEntry", "structMaxOS_1_1filesystem_1_1format_1_1LongFileNameEntry.html", "structMaxOS_1_1filesystem_1_1format_1_1LongFileNameEntry" ]
        ] ],
        [ "partition", null, [
          [ "MasterBootRecord", "structMaxOS_1_1filesystem_1_1partition_1_1MasterBootRecord.html", "structMaxOS_1_1filesystem_1_1partition_1_1MasterBootRecord" ],
          [ "MSDOSPartition", "classMaxOS_1_1filesystem_1_1partition_1_1MSDOSPartition.html", null ],
          [ "PartitionTableEntry", "structMaxOS_1_1filesystem_1_1partition_1_1PartitionTableEntry.html", "structMaxOS_1_1filesystem_1_1partition_1_1PartitionTableEntry" ]
        ] ],
        [ "Directory", "classMaxOS_1_1filesystem_1_1Directory.html", "classMaxOS_1_1filesystem_1_1Directory" ],
        [ "DirectoryResource", "classMaxOS_1_1filesystem_1_1DirectoryResource.html", "classMaxOS_1_1filesystem_1_1DirectoryResource" ],
        [ "File", "classMaxOS_1_1filesystem_1_1File.html", "classMaxOS_1_1filesystem_1_1File" ],
        [ "FileResource", "classMaxOS_1_1filesystem_1_1FileResource.html", "classMaxOS_1_1filesystem_1_1FileResource" ],
        [ "FileSystem", "classMaxOS_1_1filesystem_1_1FileSystem.html", "classMaxOS_1_1filesystem_1_1FileSystem" ],
        [ "Path", "classMaxOS_1_1filesystem_1_1Path.html", null ],
        [ "VFSResourceRegistry", "classMaxOS_1_1filesystem_1_1VFSResourceRegistry.html", "classMaxOS_1_1filesystem_1_1VFSResourceRegistry" ],
        [ "VirtualFileSystem", "classMaxOS_1_1filesystem_1_1VirtualFileSystem.html", "classMaxOS_1_1filesystem_1_1VirtualFileSystem" ]
      ] ],
      [ "gui", null, [
        [ "widgets", null, [
          [ "Button", "classMaxOS_1_1gui_1_1widgets_1_1Button.html", "classMaxOS_1_1gui_1_1widgets_1_1Button" ],
          [ "ButtonEventHandler", "classMaxOS_1_1gui_1_1widgets_1_1ButtonEventHandler.html", "classMaxOS_1_1gui_1_1widgets_1_1ButtonEventHandler" ],
          [ "ButtonPressedEvent", "classMaxOS_1_1gui_1_1widgets_1_1ButtonPressedEvent.html", "classMaxOS_1_1gui_1_1widgets_1_1ButtonPressedEvent" ],
          [ "ButtonReleasedEvent", "classMaxOS_1_1gui_1_1widgets_1_1ButtonReleasedEvent.html", "classMaxOS_1_1gui_1_1widgets_1_1ButtonReleasedEvent" ],
          [ "InputBox", "classMaxOS_1_1gui_1_1widgets_1_1InputBox.html", "classMaxOS_1_1gui_1_1widgets_1_1InputBox" ],
          [ "InputBoxEventHandler", "classMaxOS_1_1gui_1_1widgets_1_1InputBoxEventHandler.html", "classMaxOS_1_1gui_1_1widgets_1_1InputBoxEventHandler" ],
          [ "InputBoxTextChangedEvent", "classMaxOS_1_1gui_1_1widgets_1_1InputBoxTextChangedEvent.html", "classMaxOS_1_1gui_1_1widgets_1_1InputBoxTextChangedEvent" ],
          [ "Text", "classMaxOS_1_1gui_1_1widgets_1_1Text.html", "classMaxOS_1_1gui_1_1widgets_1_1Text" ]
        ] ],
        [ "CompositeWidget", "classMaxOS_1_1gui_1_1CompositeWidget.html", "classMaxOS_1_1gui_1_1CompositeWidget" ],
        [ "Desktop", "classMaxOS_1_1gui_1_1Desktop.html", "classMaxOS_1_1gui_1_1Desktop" ],
        [ "Font", "classMaxOS_1_1gui_1_1Font.html", "classMaxOS_1_1gui_1_1Font" ],
        [ "Widget", "classMaxOS_1_1gui_1_1Widget.html", "classMaxOS_1_1gui_1_1Widget" ],
        [ "WidgetMoverResizer", "classMaxOS_1_1gui_1_1WidgetMoverResizer.html", "classMaxOS_1_1gui_1_1WidgetMoverResizer" ],
        [ "Window", "classMaxOS_1_1gui_1_1Window.html", "classMaxOS_1_1gui_1_1Window" ]
      ] ],
      [ "hardwarecommunication", null, [
        [ "ACPISDTHeader", "structMaxOS_1_1hardwarecommunication_1_1ACPISDTHeader.html", "structMaxOS_1_1hardwarecommunication_1_1ACPISDTHeader" ],
        [ "AdvancedConfigurationAndPowerInterface", "classMaxOS_1_1hardwarecommunication_1_1AdvancedConfigurationAndPowerInterface.html", "classMaxOS_1_1hardwarecommunication_1_1AdvancedConfigurationAndPowerInterface" ],
        [ "AdvancedProgrammableInterruptController", "classMaxOS_1_1hardwarecommunication_1_1AdvancedProgrammableInterruptController.html", "classMaxOS_1_1hardwarecommunication_1_1AdvancedProgrammableInterruptController" ],
        [ "BaseAddressRegister", "classMaxOS_1_1hardwarecommunication_1_1BaseAddressRegister.html", "classMaxOS_1_1hardwarecommunication_1_1BaseAddressRegister" ],
        [ "IDTR", "structMaxOS_1_1hardwarecommunication_1_1IDTR.html", "structMaxOS_1_1hardwarecommunication_1_1IDTR" ],
        [ "InterruptDescriptor", "structMaxOS_1_1hardwarecommunication_1_1InterruptDescriptor.html", "structMaxOS_1_1hardwarecommunication_1_1InterruptDescriptor" ],
        [ "InterruptHandler", "classMaxOS_1_1hardwarecommunication_1_1InterruptHandler.html", "classMaxOS_1_1hardwarecommunication_1_1InterruptHandler" ],
        [ "InterruptManager", "classMaxOS_1_1hardwarecommunication_1_1InterruptManager.html", "classMaxOS_1_1hardwarecommunication_1_1InterruptManager" ],
        [ "InterruptRedirect", "structMaxOS_1_1hardwarecommunication_1_1InterruptRedirect.html", "structMaxOS_1_1hardwarecommunication_1_1InterruptRedirect" ],
        [ "IOAPIC", "classMaxOS_1_1hardwarecommunication_1_1IOAPIC.html", "classMaxOS_1_1hardwarecommunication_1_1IOAPIC" ],
        [ "LocalAPIC", "classMaxOS_1_1hardwarecommunication_1_1LocalAPIC.html", "classMaxOS_1_1hardwarecommunication_1_1LocalAPIC" ],
        [ "MADT", "structMaxOS_1_1hardwarecommunication_1_1MADT.html", "structMaxOS_1_1hardwarecommunication_1_1MADT" ],
        [ "MADT_IO_APIC", "structMaxOS_1_1hardwarecommunication_1_1MADT__IO__APIC.html", "structMaxOS_1_1hardwarecommunication_1_1MADT__IO__APIC" ],
        [ "MADT_PROCESSOR_APIC", "structMaxOS_1_1hardwarecommunication_1_1MADT__PROCESSOR__APIC.html", "structMaxOS_1_1hardwarecommunication_1_1MADT__PROCESSOR__APIC" ],
        [ "MADTEntry", "structMaxOS_1_1hardwarecommunication_1_1MADTEntry.html", "structMaxOS_1_1hardwarecommunication_1_1MADTEntry" ],
        [ "Override", "structMaxOS_1_1hardwarecommunication_1_1Override.html", "structMaxOS_1_1hardwarecommunication_1_1Override" ],
        [ "PCIController", "classMaxOS_1_1hardwarecommunication_1_1PCIController.html", "classMaxOS_1_1hardwarecommunication_1_1PCIController" ],
        [ "PCIDeviceDescriptor", "classMaxOS_1_1hardwarecommunication_1_1PCIDeviceDescriptor.html", "classMaxOS_1_1hardwarecommunication_1_1PCIDeviceDescriptor" ],
        [ "Port", "classMaxOS_1_1hardwarecommunication_1_1Port.html", "classMaxOS_1_1hardwarecommunication_1_1Port" ],
        [ "Port16Bit", "classMaxOS_1_1hardwarecommunication_1_1Port16Bit.html", "classMaxOS_1_1hardwarecommunication_1_1Port16Bit" ],
        [ "Port32Bit", "classMaxOS_1_1hardwarecommunication_1_1Port32Bit.html", "classMaxOS_1_1hardwarecommunication_1_1Port32Bit" ],
        [ "Port8Bit", "classMaxOS_1_1hardwarecommunication_1_1Port8Bit.html", "classMaxOS_1_1hardwarecommunication_1_1Port8Bit" ],
        [ "Port8BitSlow", "classMaxOS_1_1hardwarecommunication_1_1Port8BitSlow.html", "classMaxOS_1_1hardwarecommunication_1_1Port8BitSlow" ],
        [ "RedirectionEntry", "unionMaxOS_1_1hardwarecommunication_1_1RedirectionEntry.html", "unionMaxOS_1_1hardwarecommunication_1_1RedirectionEntry" ],
        [ "RSDPDescriptor", "structMaxOS_1_1hardwarecommunication_1_1RSDPDescriptor.html", "structMaxOS_1_1hardwarecommunication_1_1RSDPDescriptor" ],
        [ "RSDPDescriptor2", "structMaxOS_1_1hardwarecommunication_1_1RSDPDescriptor2.html", "structMaxOS_1_1hardwarecommunication_1_1RSDPDescriptor2" ],
        [ "RSDT", "structMaxOS_1_1hardwarecommunication_1_1RSDT.html", "structMaxOS_1_1hardwarecommunication_1_1RSDT" ],
        [ "XSDT", "structMaxOS_1_1hardwarecommunication_1_1XSDT.html", "structMaxOS_1_1hardwarecommunication_1_1XSDT" ]
      ] ],
      [ "memory", null, [
        [ "FreeChunk", "structMaxOS_1_1memory_1_1FreeChunk.html", "structMaxOS_1_1memory_1_1FreeChunk" ],
        [ "MemIO", "classMaxOS_1_1memory_1_1MemIO.html", "classMaxOS_1_1memory_1_1MemIO" ],
        [ "MemIO16Bit", "classMaxOS_1_1memory_1_1MemIO16Bit.html", "classMaxOS_1_1memory_1_1MemIO16Bit" ],
        [ "MemIO32Bit", "classMaxOS_1_1memory_1_1MemIO32Bit.html", "classMaxOS_1_1memory_1_1MemIO32Bit" ],
        [ "MemIO64Bit", "classMaxOS_1_1memory_1_1MemIO64Bit.html", "classMaxOS_1_1memory_1_1MemIO64Bit" ],
        [ "MemIO8Bit", "classMaxOS_1_1memory_1_1MemIO8Bit.html", "classMaxOS_1_1memory_1_1MemIO8Bit" ],
        [ "MemoryChunk", "structMaxOS_1_1memory_1_1MemoryChunk.html", "structMaxOS_1_1memory_1_1MemoryChunk" ],
        [ "MemoryManager", "classMaxOS_1_1memory_1_1MemoryManager.html", "classMaxOS_1_1memory_1_1MemoryManager" ],
        [ "PageMapLevel", "structMaxOS_1_1memory_1_1PageMapLevel.html", "structMaxOS_1_1memory_1_1PageMapLevel" ],
        [ "PageTableEntry", "structMaxOS_1_1memory_1_1PageTableEntry.html", "structMaxOS_1_1memory_1_1PageTableEntry" ],
        [ "PhysicalMemoryManager", "classMaxOS_1_1memory_1_1PhysicalMemoryManager.html", "classMaxOS_1_1memory_1_1PhysicalMemoryManager" ],
        [ "VirtualMemoryChunk", "structMaxOS_1_1memory_1_1VirtualMemoryChunk.html", "structMaxOS_1_1memory_1_1VirtualMemoryChunk" ],
        [ "VirtualMemoryManager", "classMaxOS_1_1memory_1_1VirtualMemoryManager.html", "classMaxOS_1_1memory_1_1VirtualMemoryManager" ],
        [ "VirtualMemoryRegion", "structMaxOS_1_1memory_1_1VirtualMemoryRegion.html", "structMaxOS_1_1memory_1_1VirtualMemoryRegion" ]
      ] ],
      [ "net", null, [
        [ "AddressResolutionProtocol", "classMaxOS_1_1net_1_1AddressResolutionProtocol.html", "classMaxOS_1_1net_1_1AddressResolutionProtocol" ],
        [ "ARPMessage", "structMaxOS_1_1net_1_1ARPMessage.html", "structMaxOS_1_1net_1_1ARPMessage" ],
        [ "ConnectedEvent", "classMaxOS_1_1net_1_1ConnectedEvent.html", "classMaxOS_1_1net_1_1ConnectedEvent" ],
        [ "DataReceivedEvent", "classMaxOS_1_1net_1_1DataReceivedEvent.html", "classMaxOS_1_1net_1_1DataReceivedEvent" ],
        [ "DisconnectedEvent", "classMaxOS_1_1net_1_1DisconnectedEvent.html", "classMaxOS_1_1net_1_1DisconnectedEvent" ],
        [ "EthernetFrameFooter", "structMaxOS_1_1net_1_1EthernetFrameFooter.html", "structMaxOS_1_1net_1_1EthernetFrameFooter" ],
        [ "EthernetFrameHandler", "classMaxOS_1_1net_1_1EthernetFrameHandler.html", "classMaxOS_1_1net_1_1EthernetFrameHandler" ],
        [ "EthernetFrameHeader", "structMaxOS_1_1net_1_1EthernetFrameHeader.html", "structMaxOS_1_1net_1_1EthernetFrameHeader" ],
        [ "EthernetFramePayloadHandler", "classMaxOS_1_1net_1_1EthernetFramePayloadHandler.html", "classMaxOS_1_1net_1_1EthernetFramePayloadHandler" ],
        [ "ICMPHeader", "structMaxOS_1_1net_1_1ICMPHeader.html", "structMaxOS_1_1net_1_1ICMPHeader" ],
        [ "InternetControlMessageProtocol", "classMaxOS_1_1net_1_1InternetControlMessageProtocol.html", "classMaxOS_1_1net_1_1InternetControlMessageProtocol" ],
        [ "InternetProtocolHandler", "classMaxOS_1_1net_1_1InternetProtocolHandler.html", "classMaxOS_1_1net_1_1InternetProtocolHandler" ],
        [ "IPV4AddressResolver", "classMaxOS_1_1net_1_1IPV4AddressResolver.html", "classMaxOS_1_1net_1_1IPV4AddressResolver" ],
        [ "IPV4Header", "structMaxOS_1_1net_1_1IPV4Header.html", "structMaxOS_1_1net_1_1IPV4Header" ],
        [ "IPV4PayloadHandler", "classMaxOS_1_1net_1_1IPV4PayloadHandler.html", "classMaxOS_1_1net_1_1IPV4PayloadHandler" ],
        [ "TCPHeader", "structMaxOS_1_1net_1_1TCPHeader.html", "structMaxOS_1_1net_1_1TCPHeader" ],
        [ "TCPPayloadHandler", "classMaxOS_1_1net_1_1TCPPayloadHandler.html", "classMaxOS_1_1net_1_1TCPPayloadHandler" ],
        [ "TCPPseudoHeader", "structMaxOS_1_1net_1_1TCPPseudoHeader.html", "structMaxOS_1_1net_1_1TCPPseudoHeader" ],
        [ "TCPSocket", "classMaxOS_1_1net_1_1TCPSocket.html", "classMaxOS_1_1net_1_1TCPSocket" ],
        [ "TransmissionControlProtocolHandler", "classMaxOS_1_1net_1_1TransmissionControlProtocolHandler.html", "classMaxOS_1_1net_1_1TransmissionControlProtocolHandler" ],
        [ "UDPDataReceivedEvent", "classMaxOS_1_1net_1_1UDPDataReceivedEvent.html", "classMaxOS_1_1net_1_1UDPDataReceivedEvent" ],
        [ "UDPHeader", "structMaxOS_1_1net_1_1UDPHeader.html", "structMaxOS_1_1net_1_1UDPHeader" ],
        [ "UDPPayloadHandler", "classMaxOS_1_1net_1_1UDPPayloadHandler.html", "classMaxOS_1_1net_1_1UDPPayloadHandler" ],
        [ "UDPSocket", "classMaxOS_1_1net_1_1UDPSocket.html", "classMaxOS_1_1net_1_1UDPSocket" ],
        [ "UserDatagramProtocolHandler", "classMaxOS_1_1net_1_1UserDatagramProtocolHandler.html", "classMaxOS_1_1net_1_1UserDatagramProtocolHandler" ]
      ] ],
      [ "processes", null, [
        [ "BaseResourceRegistry", "classMaxOS_1_1processes_1_1BaseResourceRegistry.html", "classMaxOS_1_1processes_1_1BaseResourceRegistry" ],
        [ "ELF64", "classMaxOS_1_1processes_1_1ELF64.html", "classMaxOS_1_1processes_1_1ELF64" ],
        [ "ELFHeader64", "structMaxOS_1_1processes_1_1ELFHeader64.html", "structMaxOS_1_1processes_1_1ELFHeader64" ],
        [ "ELFProgramHeader64", "structMaxOS_1_1processes_1_1ELFProgramHeader64.html", "structMaxOS_1_1processes_1_1ELFProgramHeader64" ],
        [ "ELFSectionHeader64", "structMaxOS_1_1processes_1_1ELFSectionHeader64.html", "structMaxOS_1_1processes_1_1ELFSectionHeader64" ],
        [ "GlobalResourceRegistry", "classMaxOS_1_1processes_1_1GlobalResourceRegistry.html", "classMaxOS_1_1processes_1_1GlobalResourceRegistry" ],
        [ "GlobalScheduler", "classMaxOS_1_1processes_1_1GlobalScheduler.html", "classMaxOS_1_1processes_1_1GlobalScheduler" ],
        [ "Process", "classMaxOS_1_1processes_1_1Process.html", "classMaxOS_1_1processes_1_1Process" ],
        [ "Resource", "classMaxOS_1_1processes_1_1Resource.html", "classMaxOS_1_1processes_1_1Resource" ],
        [ "ResourceManager", "classMaxOS_1_1processes_1_1ResourceManager.html", "classMaxOS_1_1processes_1_1ResourceManager" ],
        [ "ResourceRegistry", "classMaxOS_1_1processes_1_1ResourceRegistry.html", "classMaxOS_1_1processes_1_1ResourceRegistry" ],
        [ "Scheduler", "classMaxOS_1_1processes_1_1Scheduler.html", "classMaxOS_1_1processes_1_1Scheduler" ],
        [ "SharedMemory", "classMaxOS_1_1processes_1_1SharedMemory.html", "classMaxOS_1_1processes_1_1SharedMemory" ],
        [ "SharedMessageEndpoint", "classMaxOS_1_1processes_1_1SharedMessageEndpoint.html", "classMaxOS_1_1processes_1_1SharedMessageEndpoint" ],
        [ "Thread", "classMaxOS_1_1processes_1_1Thread.html", "classMaxOS_1_1processes_1_1Thread" ]
      ] ],
      [ "runtime", null, [
        [ "atexit_func_entry_t", "structMaxOS_1_1runtime_1_1atexit__func__entry__t.html", "structMaxOS_1_1runtime_1_1atexit__func__entry__t" ],
        [ "InvaildValueInfo", "structMaxOS_1_1runtime_1_1InvaildValueInfo.html", "structMaxOS_1_1runtime_1_1InvaildValueInfo" ],
        [ "KASanHandler", "classMaxOS_1_1runtime_1_1KASanHandler.html", null ],
        [ "LocationOnlyInfo", "structMaxOS_1_1runtime_1_1LocationOnlyInfo.html", "structMaxOS_1_1runtime_1_1LocationOnlyInfo" ],
        [ "OutOfBoundsInfo", "structMaxOS_1_1runtime_1_1OutOfBoundsInfo.html", "structMaxOS_1_1runtime_1_1OutOfBoundsInfo" ],
        [ "OverflowInfo", "structMaxOS_1_1runtime_1_1OverflowInfo.html", "structMaxOS_1_1runtime_1_1OverflowInfo" ],
        [ "ShiftOutOfBoundsInfo", "structMaxOS_1_1runtime_1_1ShiftOutOfBoundsInfo.html", "structMaxOS_1_1runtime_1_1ShiftOutOfBoundsInfo" ],
        [ "SourceLocation", "structMaxOS_1_1runtime_1_1SourceLocation.html", "structMaxOS_1_1runtime_1_1SourceLocation" ],
        [ "TypeDescriptor", "structMaxOS_1_1runtime_1_1TypeDescriptor.html", "structMaxOS_1_1runtime_1_1TypeDescriptor" ],
        [ "TypeMismatchInfo", "structMaxOS_1_1runtime_1_1TypeMismatchInfo.html", "structMaxOS_1_1runtime_1_1TypeMismatchInfo" ],
        [ "TypeMismatchInfoV1", "structMaxOS_1_1runtime_1_1TypeMismatchInfoV1.html", "structMaxOS_1_1runtime_1_1TypeMismatchInfoV1" ],
        [ "UBSanHandler", "classMaxOS_1_1runtime_1_1UBSanHandler.html", null ],
        [ "VLABoundNotPositiveInfo", "structMaxOS_1_1runtime_1_1VLABoundNotPositiveInfo.html", "structMaxOS_1_1runtime_1_1VLABoundNotPositiveInfo" ]
      ] ],
      [ "system", null, [
        [ "Core", "classMaxOS_1_1system_1_1Core.html", "classMaxOS_1_1system_1_1Core" ],
        [ "CoreBootInfo", "structMaxOS_1_1system_1_1CoreBootInfo.html", "structMaxOS_1_1system_1_1CoreBootInfo" ],
        [ "CPU", "classMaxOS_1_1system_1_1CPU.html", "classMaxOS_1_1system_1_1CPU" ],
        [ "CPUStatus", "structMaxOS_1_1system_1_1CPUStatus.html", "structMaxOS_1_1system_1_1CPUStatus" ],
        [ "GDTRegister", "structMaxOS_1_1system_1_1GDTRegister.html", "structMaxOS_1_1system_1_1GDTRegister" ],
        [ "GlobalDescriptorTable", "classMaxOS_1_1system_1_1GlobalDescriptorTable.html", "classMaxOS_1_1system_1_1GlobalDescriptorTable" ],
        [ "Multiboot", "classMaxOS_1_1system_1_1Multiboot.html", "classMaxOS_1_1system_1_1Multiboot" ],
        [ "StackFrame", "structMaxOS_1_1system_1_1StackFrame.html", "structMaxOS_1_1system_1_1StackFrame" ],
        [ "SyscallArguments", "structMaxOS_1_1system_1_1SyscallArguments.html", "structMaxOS_1_1system_1_1SyscallArguments" ],
        [ "SyscallManager", "classMaxOS_1_1system_1_1SyscallManager.html", "classMaxOS_1_1system_1_1SyscallManager" ],
        [ "TaskStateSegment", "structMaxOS_1_1system_1_1TaskStateSegment.html", "structMaxOS_1_1system_1_1TaskStateSegment" ]
      ] ],
      [ "tests", null, [
        [ "ConditionalTest", "classMaxOS_1_1tests_1_1ConditionalTest.html", "classMaxOS_1_1tests_1_1ConditionalTest" ],
        [ "Test", "classMaxOS_1_1tests_1_1Test.html", "classMaxOS_1_1tests_1_1Test" ],
        [ "TestRunner", "classMaxOS_1_1tests_1_1TestRunner.html", null ]
      ] ],
      [ "Logger", "classMaxOS_1_1Logger.html", "classMaxOS_1_1Logger" ],
      [ "String", "classMaxOS_1_1String.html", "classMaxOS_1_1String" ],
      [ "StringBuilder", "classMaxOS_1_1StringBuilder.html", "classMaxOS_1_1StringBuilder" ]
    ] ],
    [ "multiboot_color", "structmultiboot__color.html", "structmultiboot__color" ],
    [ "multiboot_header", "structmultiboot__header.html", "structmultiboot__header" ],
    [ "multiboot_header_tag", "structmultiboot__header__tag.html", "structmultiboot__header__tag" ],
    [ "multiboot_header_tag_address", "structmultiboot__header__tag__address.html", "structmultiboot__header__tag__address" ],
    [ "multiboot_header_tag_console_flags", "structmultiboot__header__tag__console__flags.html", "structmultiboot__header__tag__console__flags" ],
    [ "multiboot_header_tag_entry_address", "structmultiboot__header__tag__entry__address.html", "structmultiboot__header__tag__entry__address" ],
    [ "multiboot_header_tag_framebuffer", "structmultiboot__header__tag__framebuffer.html", "structmultiboot__header__tag__framebuffer" ],
    [ "multiboot_header_tag_information_request", "structmultiboot__header__tag__information__request.html", "structmultiboot__header__tag__information__request" ],
    [ "multiboot_header_tag_module_align", "structmultiboot__header__tag__module__align.html", "structmultiboot__header__tag__module__align" ],
    [ "multiboot_header_tag_relocatable", "structmultiboot__header__tag__relocatable.html", "structmultiboot__header__tag__relocatable" ],
    [ "multiboot_mmap_entry", "structmultiboot__mmap__entry.html", "structmultiboot__mmap__entry" ],
    [ "multiboot_tag", "structmultiboot__tag.html", "structmultiboot__tag" ],
    [ "multiboot_tag_apm", "structmultiboot__tag__apm.html", "structmultiboot__tag__apm" ],
    [ "multiboot_tag_basic_meminfo", "structmultiboot__tag__basic__meminfo.html", "structmultiboot__tag__basic__meminfo" ],
    [ "multiboot_tag_bootdev", "structmultiboot__tag__bootdev.html", "structmultiboot__tag__bootdev" ],
    [ "multiboot_tag_efi32", "structmultiboot__tag__efi32.html", "structmultiboot__tag__efi32" ],
    [ "multiboot_tag_efi32_ih", "structmultiboot__tag__efi32__ih.html", "structmultiboot__tag__efi32__ih" ],
    [ "multiboot_tag_efi64", "structmultiboot__tag__efi64.html", "structmultiboot__tag__efi64" ],
    [ "multiboot_tag_efi64_ih", "structmultiboot__tag__efi64__ih.html", "structmultiboot__tag__efi64__ih" ],
    [ "multiboot_tag_efi_mmap", "structmultiboot__tag__efi__mmap.html", "structmultiboot__tag__efi__mmap" ],
    [ "multiboot_tag_elf_sections", "structmultiboot__tag__elf__sections.html", "structmultiboot__tag__elf__sections" ],
    [ "multiboot_tag_framebuffer", "structmultiboot__tag__framebuffer.html", "structmultiboot__tag__framebuffer" ],
    [ "multiboot_tag_framebuffer_common", "structmultiboot__tag__framebuffer__common.html", "structmultiboot__tag__framebuffer__common" ],
    [ "multiboot_tag_load_base_addr", "structmultiboot__tag__load__base__addr.html", "structmultiboot__tag__load__base__addr" ],
    [ "multiboot_tag_mmap", "structmultiboot__tag__mmap.html", "structmultiboot__tag__mmap" ],
    [ "multiboot_tag_module", "structmultiboot__tag__module.html", "structmultiboot__tag__module" ],
    [ "multiboot_tag_network", "structmultiboot__tag__network.html", "structmultiboot__tag__network" ],
    [ "multiboot_tag_new_acpi", "structmultiboot__tag__new__acpi.html", "structmultiboot__tag__new__acpi" ],
    [ "multiboot_tag_old_acpi", "structmultiboot__tag__old__acpi.html", "structmultiboot__tag__old__acpi" ],
    [ "multiboot_tag_smbios", "structmultiboot__tag__smbios.html", "structmultiboot__tag__smbios" ],
    [ "multiboot_tag_string", "structmultiboot__tag__string.html", "structmultiboot__tag__string" ],
    [ "multiboot_tag_vbe", "structmultiboot__tag__vbe.html", "structmultiboot__tag__vbe" ],
    [ "multiboot_vbe_info_block", "structmultiboot__vbe__info__block.html", "structmultiboot__vbe__info__block" ],
    [ "multiboot_vbe_mode_info_block", "structmultiboot__vbe__mode__info__block.html", "structmultiboot__vbe__mode__info__block" ]
];