var namespaceMaxOS_1_1hardwarecommunication =
[
    [ "ACPISDTHeader", "structMaxOS_1_1hardwarecommunication_1_1ACPISDTHeader.html", "structMaxOS_1_1hardwarecommunication_1_1ACPISDTHeader" ],
    [ "AdvancedConfigurationAndPowerInterface", "classMaxOS_1_1hardwarecommunication_1_1AdvancedConfigurationAndPowerInterface.html", "classMaxOS_1_1hardwarecommunication_1_1AdvancedConfigurationAndPowerInterface" ],
    [ "AdvancedProgrammableInterruptController", "classMaxOS_1_1hardwarecommunication_1_1AdvancedProgrammableInterruptController.html", "classMaxOS_1_1hardwarecommunication_1_1AdvancedProgrammableInterruptController" ],
    [ "BaseAddressRegister", "classMaxOS_1_1hardwarecommunication_1_1BaseAddressRegister.html", "classMaxOS_1_1hardwarecommunication_1_1BaseAddressRegister" ],
    [ "IDTR", "structMaxOS_1_1hardwarecommunication_1_1IDTR.html", "structMaxOS_1_1hardwarecommunication_1_1IDTR" ],
    [ "InterruptDescriptor", "structMaxOS_1_1hardwarecommunication_1_1InterruptDescriptor.html", "structMaxOS_1_1hardwarecommunication_1_1InterruptDescriptor" ],
    [ "InterruptHandler", "classMaxOS_1_1hardwarecommunication_1_1InterruptHandler.html", "classMaxOS_1_1hardwarecommunication_1_1InterruptHandler" ],
    [ "InterruptManager", "classMaxOS_1_1hardwarecommunication_1_1InterruptManager.html", "classMaxOS_1_1hardwarecommunication_1_1InterruptManager" ],
    [ "InterruptRedirect", "structMaxOS_1_1hardwarecommunication_1_1InterruptRedirect.html", "structMaxOS_1_1hardwarecommunication_1_1InterruptRedirect" ],
    [ "IOAPIC", "classMaxOS_1_1hardwarecommunication_1_1IOAPIC.html", "classMaxOS_1_1hardwarecommunication_1_1IOAPIC" ],
    [ "LocalAPIC", "classMaxOS_1_1hardwarecommunication_1_1LocalAPIC.html", "classMaxOS_1_1hardwarecommunication_1_1LocalAPIC" ],
    [ "MADT", "structMaxOS_1_1hardwarecommunication_1_1MADT.html", "structMaxOS_1_1hardwarecommunication_1_1MADT" ],
    [ "MADT_IOAPIC", "structMaxOS_1_1hardwarecommunication_1_1MADT__IOAPIC.html", "structMaxOS_1_1hardwarecommunication_1_1MADT__IOAPIC" ],
    [ "MADT_Item", "structMaxOS_1_1hardwarecommunication_1_1MADT__Item.html", "structMaxOS_1_1hardwarecommunication_1_1MADT__Item" ],
    [ "Override", "structMaxOS_1_1hardwarecommunication_1_1Override.html", "structMaxOS_1_1hardwarecommunication_1_1Override" ],
    [ "PeripheralComponentInterconnectController", "classMaxOS_1_1hardwarecommunication_1_1PeripheralComponentInterconnectController.html", "classMaxOS_1_1hardwarecommunication_1_1PeripheralComponentInterconnectController" ],
    [ "PeripheralComponentInterconnectDeviceDescriptor", "classMaxOS_1_1hardwarecommunication_1_1PeripheralComponentInterconnectDeviceDescriptor.html", "classMaxOS_1_1hardwarecommunication_1_1PeripheralComponentInterconnectDeviceDescriptor" ],
    [ "Port", "classMaxOS_1_1hardwarecommunication_1_1Port.html", "classMaxOS_1_1hardwarecommunication_1_1Port" ],
    [ "Port16Bit", "classMaxOS_1_1hardwarecommunication_1_1Port16Bit.html", "classMaxOS_1_1hardwarecommunication_1_1Port16Bit" ],
    [ "Port32Bit", "classMaxOS_1_1hardwarecommunication_1_1Port32Bit.html", "classMaxOS_1_1hardwarecommunication_1_1Port32Bit" ],
    [ "Port8Bit", "classMaxOS_1_1hardwarecommunication_1_1Port8Bit.html", "classMaxOS_1_1hardwarecommunication_1_1Port8Bit" ],
    [ "Port8BitSlow", "classMaxOS_1_1hardwarecommunication_1_1Port8BitSlow.html", "classMaxOS_1_1hardwarecommunication_1_1Port8BitSlow" ],
    [ "RedirectionEntry", "unionMaxOS_1_1hardwarecommunication_1_1RedirectionEntry.html", "unionMaxOS_1_1hardwarecommunication_1_1RedirectionEntry" ],
    [ "RSDPDescriptor", "structMaxOS_1_1hardwarecommunication_1_1RSDPDescriptor.html", "structMaxOS_1_1hardwarecommunication_1_1RSDPDescriptor" ],
    [ "RSDPDescriptor2", "structMaxOS_1_1hardwarecommunication_1_1RSDPDescriptor2.html", "structMaxOS_1_1hardwarecommunication_1_1RSDPDescriptor2" ],
    [ "RSDT", "structMaxOS_1_1hardwarecommunication_1_1RSDT.html", "structMaxOS_1_1hardwarecommunication_1_1RSDT" ],
    [ "XSDT", "structMaxOS_1_1hardwarecommunication_1_1XSDT.html", "structMaxOS_1_1hardwarecommunication_1_1XSDT" ],
    [ "interrupt_redirect_t", "namespaceMaxOS_1_1hardwarecommunication.html#a8ed1467ecf3306e3f6d39deae897fbe9", null ],
    [ "BaseAddressRegisterType", "namespaceMaxOS_1_1hardwarecommunication.html#afc5ea080a9107e056194cc643a761608", [
      [ "MemoryMapped", "namespaceMaxOS_1_1hardwarecommunication.html#afc5ea080a9107e056194cc643a761608a89bd90e73498b68e442cc6673edddefe", null ],
      [ "InputOutput", "namespaceMaxOS_1_1hardwarecommunication.html#afc5ea080a9107e056194cc643a761608aac7eafbd848f2f627c8da7d25a4faade", null ]
    ] ],
    [ "__attribute__", "namespaceMaxOS_1_1hardwarecommunication.html#abe45fccdf160be55b8dc7bd5417235ac", null ],
    [ "__attribute__", "namespaceMaxOS_1_1hardwarecommunication.html#a246df0da2f83d4427aeff9b62cb78b01", null ]
];